"""
WP-01A-02 ORM kernel —— 显式导入验收。

``app/models/trading`` 与 ``app/models`` 只做显式 import/export；``app/models`` 必须显式
导入全部 trading metadata，供 Alembic 发现；禁止动态扫描、I/O 或重复 metadata。
"""

import app.models  # noqa: F401
from app.models import Base
from app.models.trading import (
    ArchiveManifest,
    ArtifactLineageEdge,
    ArtifactObject,
    CapitalPermissionManifest,
    ExecutionSpecVersion,
    IdempotencyClaim,
    JobCompletion,
    ModelRoleBinding,
    OutboxDeliveryHistory,
    AuditSample,
    ContractSnapshot,
    ContractSpec,
    DecisionOpportunity,
    DecisionOpportunityMarket,
    EpisodeContractSpec,
    EpisodeMembership,
    EvaluationCohort,
    ForecastComponent,
    ForecastComponentContractSpec,
    ForecastComponentVersion,
    ForecastEpisode,
    GateDecision,
    InformationSnapshot,
    InformationSnapshotItem,
    PayoutFunction,
    PMBookCheckpoint,
    PMBookCurrent,
    PMBookLevel,
    PMConnectionEpoch,
    PMEvent,
    PMMarket,
    PMMarketCurrent,
    PMMarketLifecycleEvent,
    PMMarketVersion,
    PMQuoteBinding,
    PMSourceEventBatch,
    PMSourceEventIndex,
    PMToken,
    PMTokenVersion,
    PolicyFreeze,
    PortfolioDependencyEdge,
    ScreeningEpisode,
    UniverseMembership,
    WorldSchemaVersion,
    PolicyTypeScope,
    PUniverseFrame,
    PUniverseFramePage,
    ReleaseManifest,
    RetentionManifest,
    RuntimeConfigVersion,
    SecretAccessEvent,
    SecretVaultEntry,
    SecretVaultVersion,
    StrategyObjectiveContract,
    StrategyVersion,
    TransactionalOutbox,
    CoherenceCheck,
    EvidenceBundle,
    EvidenceBundleItem,
    EvidenceCoveragePolicy,
    EvidenceRevision,
    ForecastChallenge,
    ForecastInputManifest,
    ForecastLease,
    ForecastSubmission,
    PayoutProjection,
    Prior,
    AIInvocation,
    AIToolCall,
    AIValidationResult,
)
from app.models.trading.constants import TRADING_SCHEMA

EXPECTED = [
    "artifact_objects",
    "artifact_lineage_edges",
    "archive_manifests",
    "retention_manifests",
    "runtime_config_versions",
    "strategy_objective_contracts",
    "strategy_versions",
    "model_role_bindings",
    "execution_spec_versions",
    "capital_permission_manifests",
    "release_manifests",
    "policy_type_scopes",
    "policy_freezes",
    "secret_vault_entries",
    "secret_vault_versions",
    "secret_access_events",
    "idempotency_claims",
    "transactional_outbox",
    "outbox_delivery_history",
    "job_completions",
    "pm_universe_frames",
    "pm_universe_frame_pages",
    "pm_events",
    "pm_markets",
    "pm_market_versions",
    "pm_tokens",
    "pm_token_versions",
    "pm_market_lifecycle_events",
    "pm_market_current",
    "pm_connection_epochs",
    "pm_source_event_batches",
    "pm_source_event_index",
    "pm_book_checkpoints",
    "pm_book_levels",
    "pm_book_current",
    "pm_quote_bindings",
    "contract_snapshots",
    "contract_specs",
    "payout_functions",
    "forecast_components",
    "world_schema_versions",
    "forecast_component_versions",
    "forecast_component_contract_specs",
    "portfolio_dependency_edges",
    "evaluation_cohorts",
    "universe_memberships",
    "screening_episodes",
    "audit_samples",
    "decision_opportunities",
    "decision_opportunity_markets",
    "episode_memberships",
    "forecast_episodes",
    "episode_contract_specs",
    "information_snapshots",
    "information_snapshot_items",
    "gate_decisions",
    "priors",
    "evidence_coverage_policies",
    "evidence_revisions",
    "evidence_bundles",
    "evidence_bundle_items",
    "forecast_input_manifests",
    "forecast_submissions",
    "payout_projections",
    "coherence_checks",
    "forecast_challenges",
    "forecast_leases",
    "ai_invocations",
    "ai_tool_calls",
    "ai_validation_results",
]


def test_trading_metadata_registered_on_shared_base():
    trading = {t.name for t in Base.metadata.tables.values() if t.schema == TRADING_SCHEMA}
    assert trading == set(EXPECTED)


def test_explicit_model_symbols_importable():
    symbols = {
        "artifact_objects": ArtifactObject,
        "artifact_lineage_edges": ArtifactLineageEdge,
        "archive_manifests": ArchiveManifest,
        "retention_manifests": RetentionManifest,
        "runtime_config_versions": RuntimeConfigVersion,
        "strategy_objective_contracts": StrategyObjectiveContract,
        "strategy_versions": StrategyVersion,
        "model_role_bindings": ModelRoleBinding,
        "execution_spec_versions": ExecutionSpecVersion,
        "capital_permission_manifests": CapitalPermissionManifest,
        "release_manifests": ReleaseManifest,
        "policy_type_scopes": PolicyTypeScope,
        "policy_freezes": PolicyFreeze,
        "secret_vault_entries": SecretVaultEntry,
        "secret_vault_versions": SecretVaultVersion,
        "secret_access_events": SecretAccessEvent,
        "idempotency_claims": IdempotencyClaim,
        "transactional_outbox": TransactionalOutbox,
        "outbox_delivery_history": OutboxDeliveryHistory,
        "job_completions": JobCompletion,
        "pm_universe_frames": PUniverseFrame,
        "pm_universe_frame_pages": PUniverseFramePage,
        "pm_events": PMEvent,
        "pm_markets": PMMarket,
        "pm_market_versions": PMMarketVersion,
        "pm_tokens": PMToken,
        "pm_token_versions": PMTokenVersion,
        "pm_market_lifecycle_events": PMMarketLifecycleEvent,
        "pm_market_current": PMMarketCurrent,
        "pm_connection_epochs": PMConnectionEpoch,
        "pm_source_event_batches": PMSourceEventBatch,
        "pm_source_event_index": PMSourceEventIndex,
        "pm_book_checkpoints": PMBookCheckpoint,
        "pm_book_levels": PMBookLevel,
        "pm_book_current": PMBookCurrent,
        "pm_quote_bindings": PMQuoteBinding,
        "contract_snapshots": ContractSnapshot,
        "contract_specs": ContractSpec,
        "payout_functions": PayoutFunction,
        "forecast_components": ForecastComponent,
        "world_schema_versions": WorldSchemaVersion,
        "forecast_component_versions": ForecastComponentVersion,
        "forecast_component_contract_specs": ForecastComponentContractSpec,
        "portfolio_dependency_edges": PortfolioDependencyEdge,
        "evaluation_cohorts": EvaluationCohort,
        "universe_memberships": UniverseMembership,
        "screening_episodes": ScreeningEpisode,
        "audit_samples": AuditSample,
        "decision_opportunities": DecisionOpportunity,
        "decision_opportunity_markets": DecisionOpportunityMarket,
        "episode_memberships": EpisodeMembership,
        "forecast_episodes": ForecastEpisode,
        "episode_contract_specs": EpisodeContractSpec,
        "information_snapshots": InformationSnapshot,
        "information_snapshot_items": InformationSnapshotItem,
        "gate_decisions": GateDecision,
        "priors": Prior,
        "evidence_coverage_policies": EvidenceCoveragePolicy,
        "evidence_revisions": EvidenceRevision,
        "evidence_bundles": EvidenceBundle,
        "evidence_bundle_items": EvidenceBundleItem,
        "forecast_input_manifests": ForecastInputManifest,
        "forecast_submissions": ForecastSubmission,
        "payout_projections": PayoutProjection,
        "coherence_checks": CoherenceCheck,
        "forecast_challenges": ForecastChallenge,
        "forecast_leases": ForecastLease,
        "ai_invocations": AIInvocation,
        "ai_tool_calls": AIToolCall,
        "ai_validation_results": AIValidationResult,
    }
    for tablename, model in symbols.items():
        assert model.__tablename__ == tablename
        assert model.__table__.schema == TRADING_SCHEMA


def test_app_models_exports_trading():
    exported = set(app.models.__all__)
    for model in (
        "ArtifactObject", "ArtifactLineageEdge", "ArchiveManifest", "RetentionManifest",
        "RuntimeConfigVersion", "StrategyObjectiveContract", "StrategyVersion",
        "ModelRoleBinding", "ExecutionSpecVersion", "CapitalPermissionManifest",
        "ReleaseManifest", "PolicyTypeScope", "PolicyFreeze",
        "SecretVaultEntry", "SecretVaultVersion", "SecretAccessEvent",
        "IdempotencyClaim", "TransactionalOutbox", "OutboxDeliveryHistory", "JobCompletion",
        "PUniverseFrame", "PUniverseFramePage", "PMEvent", "PMMarket",
        "PMMarketVersion", "PMToken", "PMTokenVersion", "PMMarketLifecycleEvent", "PMMarketCurrent",
        "PMConnectionEpoch", "PMSourceEventBatch", "PMSourceEventIndex",
        "PMBookCheckpoint", "PMBookLevel", "PMBookCurrent", "PMQuoteBinding",
        "ContractSnapshot", "ContractSpec", "PayoutFunction", "ForecastComponent",
        "ForecastComponentVersion", "ForecastComponentContractSpec", "WorldSchemaVersion",
        "PortfolioDependencyEdge", "EvaluationCohort", "UniverseMembership",
        "ScreeningEpisode", "AuditSample", "DecisionOpportunity", "DecisionOpportunityMarket",
        "ForecastEpisode", "EpisodeContractSpec", "EpisodeMembership", "InformationSnapshot",
        "InformationSnapshotItem", "GateDecision",
        "Prior", "EvidenceCoveragePolicy", "EvidenceRevision", "EvidenceBundle",
        "EvidenceBundleItem", "ForecastInputManifest", "ForecastSubmission",
        "PayoutProjection", "CoherenceCheck", "ForecastChallenge", "ForecastLease",
        "AIInvocation", "AIToolCall", "AIValidationResult",
    ):
        assert model in exported, model


def test_no_duplicate_metadata_or_scan():
    # 同一物理表在 metadata 中只有一份；无动态扫描产生的重复
    from collections import Counter
    keys = Counter((t.schema, t.name) for t in Base.metadata.tables.values())
    assert all(v == 1 for v in keys.values()), [k for k, v in keys.items() if v > 1]
