"""
WP-01A-02 ORM kernel —— type factory / mixin 定向验收。

type factory 每次调用返回**独立**实例；DDL 分别为 ``TIMESTAMPTZ``、``NUMERIC(38,0)``、
``VARCHAR(64) COLLATE "C"``、``TEXT COLLATE "C"``。mixin：identity 为 ``GENERATED BY
DEFAULT``，version Python/server 初值 1 且启用 SQLAlchemy optimistic locking。
"""

from sqlalchemy import DateTime, Integer, Numeric, String, Text
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateTable, CreateColumn

from sqlalchemy.orm import Mapped

from app.models.trading.constants import TRADING_SCHEMA
from app.models.trading.mixins import (
    BigIntIdentityMixin,
    CreatedAtMixin,
    OptimisticVersionMixin,
    TimestampMixin,
)
from app.models.trading.types import (
    base_unit_type,
    external_id_type,
    sha256_type,
    utc_timestamp_type,
)


def test_trading_schema_constant():
    assert TRADING_SCHEMA == "trading"


def test_type_factories_return_independent_instances():
    a, b = utc_timestamp_type(), utc_timestamp_type()
    assert a is not b
    assert base_unit_type() is not base_unit_type()
    assert sha256_type() is not sha256_type()
    assert external_id_type() is not external_id_type()


def test_utc_timestamp_type():
    t = utc_timestamp_type()
    assert isinstance(t, DateTime)
    assert t.timezone is True
    sql = str(t.compile(dialect=postgresql.dialect()))
    assert "TIMESTAMP WITH TIME ZONE" in sql


def test_base_unit_type():
    t = base_unit_type()
    assert isinstance(t, Numeric)
    assert t.precision == 38
    assert t.scale == 0
    sql = str(t.compile(dialect=postgresql.dialect()))
    assert "NUMERIC(38, 0)" in sql


def test_sha256_type():
    t = sha256_type()
    assert isinstance(t, String)
    assert t.length == 64
    assert t.collation == "C"
    sql = str(t.compile(dialect=postgresql.dialect()))
    assert 'VARCHAR(64) COLLATE "C"' in sql


def test_external_id_type():
    t = external_id_type()
    assert isinstance(t, Text)
    assert t.collation == "C"
    sql = str(t.compile(dialect=postgresql.dialect()))
    assert 'TEXT COLLATE "C"' in sql


def _compile_column(typ):
    from sqlalchemy import Column
    return str(CreateColumn("c", Column("c", typ)).compile(dialect=postgresql.dialect()))


def test_bigint_identity_mixin_generated_by_default():
    from sqlalchemy import Column
    from sqlalchemy.orm import DeclarativeBase

    class _B(DeclarativeBase):
        pass

    class T(_B, BigIntIdentityMixin):
        __tablename__ = "t_x"

    col = T.__table__.c.id
    assert col.primary_key
    # Identity(always=False) → GENERATED BY DEFAULT
    assert col.identity is not None
    assert col.identity.always is False
    sql = str(CreateTable(T.__table__).compile(dialect=postgresql.dialect()))
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY" in sql


def test_optimistic_version_mixin_defaults_and_locking():
    from sqlalchemy import create_engine
    from sqlalchemy.orm import DeclarativeBase, Session

    class _B(DeclarativeBase):
        pass

    from sqlalchemy import BigInteger, String
    from sqlalchemy.orm import mapped_column

    class T(_B, OptimisticVersionMixin):
        __tablename__ = "t_v"
        id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
        name: Mapped[str] = mapped_column(String)

    ver = T.__table__.c.version
    assert ver.default.arg == 1
    assert ver.server_default.arg == "1" or getattr(ver.server_default, "text", "1") is not None
    # SQLAlchemy optimistic locking 必须绑定 mapped Column；字符串会在 flush 时抛 ArgumentError。
    assert T.__mapper__.version_id_col is ver

    engine = create_engine("sqlite://")
    _B.metadata.create_all(engine)
    with Session(engine, expire_on_commit=False) as session:
        row = T(id=1, name="before")
        session.add(row)
        session.commit()
        assert row.version == 1
        row.name = "after"
        session.commit()
        assert row.version == 2


def test_timestamp_mixin_has_both_columns():
    from sqlalchemy.orm import DeclarativeBase

    class _B(DeclarativeBase):
        pass

    from sqlalchemy import BigInteger
    from sqlalchemy.orm import mapped_column

    class T(_B, TimestampMixin):
        __tablename__ = "t_ts"
        id: Mapped[int] = mapped_column(BigInteger, primary_key=True)

    assert "created_at" in T.__table__.c
    assert "updated_at" in T.__table__.c
    assert T.__table__.c.created_at.server_default is not None
    assert T.__table__.c.updated_at.server_default is not None


def test_created_at_mixin_only():
    from sqlalchemy.orm import DeclarativeBase

    class _B(DeclarativeBase):
        pass

    from sqlalchemy import BigInteger
    from sqlalchemy.orm import mapped_column

    class T(_B, CreatedAtMixin):
        __tablename__ = "t_ca"
        id: Mapped[int] = mapped_column(BigInteger, primary_key=True)

    assert "created_at" in T.__table__.c
    assert "updated_at" not in T.__table__.c
