"""
WP-01A-02 foundation models —— 20 张表 / 约束矩阵验收（Checkpoint B §4.2）。

校验 metadata 层：表集合、schema-qualified BIGINT identity、FK 规则、唯一约束、
CHECK（含 JSONB object / 非负金额 / 状态白名单）、索引（含 partial index）、分区表定义。
"""

import importlib.util
from pathlib import Path

import app.models  # noqa: F401
from sqlalchemy import BigInteger, CheckConstraint, Column, Table, UniqueConstraint
from sqlalchemy.dialects import postgresql

from app.models import Base
from app.models.trading.constants import TRADING_SCHEMA

TRADING = {t.name: t for t in Base.metadata.tables.values() if t.schema == TRADING_SCHEMA}


def _constraints(table, kind):
    return [c for c in TRADING[table].constraints if isinstance(c, kind)]


def _checks(table):
    return [c.name for c in TRADING[table].constraints if isinstance(c, CheckConstraint)]


def _check_sql(table, name):
    return str(next(
        c.sqltext for c in TRADING[table].constraints
        if isinstance(c, CheckConstraint) and c.name == name
    ))


def _uniques(table):
    return [c for c in TRADING[table].constraints if isinstance(c, UniqueConstraint)]


def _fk_targets(table):
    return sorted(fk.target_fullname for fk in TRADING[table].foreign_keys)


def test_exactly_56_trading_tables():
    """20 foundation + 9 market master（0010）+ 7 market stream（0011）+ 8 semantics（0012）+ 12 cohort/episode（0013）。"""
    assert set(TRADING) == {
        "artifact_objects", "artifact_lineage_edges", "archive_manifests", "retention_manifests",
        "runtime_config_versions", "strategy_objective_contracts", "strategy_versions",
        "model_role_bindings", "execution_spec_versions", "capital_permission_manifests",
        "release_manifests", "policy_type_scopes", "policy_freezes",
        "secret_vault_entries", "secret_vault_versions", "secret_access_events",
        "idempotency_claims", "transactional_outbox", "outbox_delivery_history", "job_completions",
        "pm_universe_frames", "pm_universe_frame_pages", "pm_events", "pm_markets",
        "pm_market_versions", "pm_tokens", "pm_token_versions", "pm_market_lifecycle_events",
        "pm_market_current",
        "pm_connection_epochs", "pm_source_event_batches", "pm_source_event_index",
        "pm_book_checkpoints", "pm_book_levels", "pm_book_current", "pm_quote_bindings",
        "contract_snapshots", "contract_specs", "payout_functions", "forecast_components",
        "world_schema_versions", "forecast_component_versions", "forecast_component_contract_specs",
        "portfolio_dependency_edges",
        "evaluation_cohorts", "universe_memberships", "screening_episodes", "audit_samples",
        "decision_opportunities", "decision_opportunity_markets", "episode_memberships",
        "forecast_episodes", "episode_contract_specs", "information_snapshots",
        "information_snapshot_items", "gate_decisions",
    }


def test_all_tables_schema_qualified_bigint_identity_pk():
    # 分区证据表 PK = (id, 分区时间键)
    composite_pk_tables = {
        "outbox_delivery_history": "completed_at",
        "pm_source_event_batches": "received_at",
        "pm_source_event_index": "received_at",
        "pm_book_checkpoints": "received_at",
        "pm_book_levels": "received_at",
    }
    for name, t in TRADING.items():
        if name in composite_pk_tables:
            assert {c.name for c in t.primary_key} == {"id", composite_pk_tables[name]}
            continue
        pk = list(t.primary_key)
        assert len(pk) == 1, f"{name}: PK 必须单列"
        col = pk[0]
        assert col.identity is not None, f"{name}: id 必须是 GENERATED BY DEFAULT identity"
        assert col.identity.always is False


def test_artifact_objects_unique_key_and_size_checks():
    uq = _uniques("artifact_objects")
    assert any(
        [c.name for c in u.columns]
        == ["sha256", "compression", "storage_driver", "storage_version"]
        for u in uq
    )
    cks = _checks("artifact_objects")
    assert "ck_artifact_objects_original_size_nonneg" in cks
    assert "ck_artifact_objects_stored_size_nonneg" in cks
    assert "ck_artifact_objects_raw_size_equal" in cks  # compression='none' → 两尺寸相等
    assert "compression <> 'none'" in _check_sql(
        "artifact_objects", "ck_artifact_objects_raw_size_equal"
    )


def test_artifact_objects_exactly_represent_artifact_ref():
    table = TRADING["artifact_objects"]
    compression = _check_sql("artifact_objects", "ck_artifact_objects_compression_known")
    assert "'none'" in compression and "'zstd'" in compression
    assert "gzip" not in compression
    assert table.c.mime.nullable is False
    assert "mime_type" not in table.c
    assert table.c.storage_version.type.python_type is str
    assert table.c.storage_version.type.collation == "C"
    assert "'cas/v1'" in _check_sql(
        "artifact_objects", "ck_artifact_objects_storage_version_known"
    )
    driver = _check_sql("artifact_objects", "ck_artifact_objects_storage_driver_known")
    assert "'local'" in driver and "'s3'" in driver
    assert "^[0-9a-f]{64}$" in _check_sql(
        "artifact_objects", "ck_artifact_objects_sha256_lower_hex"
    )
    assert "length(mime) > 0" in _check_sql(
        "artifact_objects", "ck_artifact_objects_mime_valid"
    )
    assert "cas/v1/sha256/" in _check_sql(
        "artifact_objects", "ck_artifact_objects_locator_canonical"
    )


def test_artifact_lineage_edges_no_self_and_unique_and_cascade():
    uq = _uniques("artifact_lineage_edges")
    assert any({"from_artifact_id", "to_artifact_id", "relation"} <= {c.name for c in u.columns}
               for u in uq)
    assert "ck_artifact_lineage_edges_no_self" in _checks("artifact_lineage_edges")
    # lineage junction FK 用 CASCADE
    for fk in TRADING["artifact_lineage_edges"].foreign_keys:
        assert fk.ondelete == "CASCADE"


def test_archive_retention_manifests_jsonb_hash_status():
    for tbl in ("archive_manifests", "retention_manifests"):
        cks = _checks(tbl)
        assert f"ck_{tbl}_content_object" in cks
        assert f"ck_{tbl}_status_known" in cks
        assert "content_hash" in TRADING[tbl].c
        assert "updated_at" not in TRADING[tbl].c  # append-only


def test_control_versions_jsonb_and_status():
    for tbl in ("runtime_config_versions", "strategy_objective_contracts", "strategy_versions",
                "execution_spec_versions"):
        assert f"ck_{tbl}_content_object" in _checks(tbl)
        assert f"ck_{tbl}_status_known" in _checks(tbl)


def test_model_role_bindings_role_unique_within_strategy_version():
    uq = _uniques("model_role_bindings")
    assert any({c.name for c in u.columns} == {"strategy_version_id", "role"} for u in uq)
    assert _fk_targets("model_role_bindings") == ["trading.strategy_versions.id"]


def test_capital_permission_manifests_dual_capital_nonneg_base_unit():
    tbl = TRADING["capital_permission_manifests"]
    for col in ("evaluation_capital", "authorized_capital"):
        assert tbl.c[col].type.precision == 38 and tbl.c[col].type.scale == 0
    assert "ck_capital_permission_manifests_eval_cap_nonneg" in _checks("capital_permission_manifests")
    assert "ck_capital_permission_manifests_auth_cap_nonneg" in _checks("capital_permission_manifests")
    assert "ck_capital_permission_manifests_mode_known" in _checks("capital_permission_manifests")
    assert "kill_switch" in tbl.c
    mode = _check_sql(
        "capital_permission_manifests", "ck_capital_permission_manifests_mode_known"
    )
    assert "'canary'" in mode and "paper" not in mode


def test_release_manifests_pins_four_version_fks():
    fks = _fk_targets("release_manifests")
    assert "trading.runtime_config_versions.id" in fks
    assert "trading.strategy_versions.id" in fks
    assert "trading.execution_spec_versions.id" in fks
    assert "trading.capital_permission_manifests.id" in fks
    for col in ("git_sha", "image_digest", "db_revision", "total_hash"):
        assert col in TRADING["release_manifests"].c


def test_policy_type_scopes_unique_per_type():
    """WP-01C 强化：一个 policy type 只能映射一个合法 scope（禁 fallback）。"""
    uq = _uniques("policy_type_scopes")
    assert any({c.name for c in u.columns} == {"policy_type"} for u in uq)
    assert "ck_policy_type_scopes_scope_type_known" in _checks("policy_type_scopes")


def test_policy_freezes_pins_content_hash_and_release():
    assert "policy_content_hash" in TRADING["policy_freezes"].c
    assert _fk_targets("policy_freezes") == [
        "trading.policy_type_scopes.policy_type",
        "trading.policy_type_scopes.scope_type",
        "trading.release_manifests.id",
    ]
    assert "ck_policy_freezes_status_known" in _checks("policy_freezes")
    # WP-01C 强化：exact type/scope/version + frozen_at
    assert "policy_type" in TRADING["policy_freezes"].c
    assert "scope_type" in TRADING["policy_freezes"].c
    assert "policy_version" in TRADING["policy_freezes"].c
    assert "frozen_at" in TRADING["policy_freezes"].c
    assert "uq_policy_freezes_type_scope_version" in {u.name for u in _uniques("policy_freezes")}
    uq = next(u for u in _uniques("policy_freezes") if u.name == "uq_policy_freezes_type_scope_version")
    assert [c.name for c in uq.columns] == [
        "policy_type", "scope_type", "scope_key", "policy_version",
    ]


def test_vault_no_plaintext_fields():
    versions = TRADING["secret_vault_versions"].c
    for bad in ("value", "token", "password", "plaintext", "secret_content"):
        assert bad not in versions, f"vault version 不得含明文字段 {bad}"
    assert "ciphertext" in versions
    assert "nonce" in versions
    assert "aad_hash" in versions
    assert "algorithm" in versions
    assert "key_id" in versions and "key_version" in versions
    # access event 只含主体/用途/reason
    access = TRADING["secret_access_events"].c
    assert {"subject", "purpose", "result_reason"} <= set(access.keys())
    # entry 稳定 identity + 唯一 name
    assert any({c.name for c in u.columns} == {"name"} for u in _uniques("secret_vault_entries"))
    algorithm = _check_sql(
        "secret_vault_versions", "ck_secret_vault_versions_algorithm_known"
    )
    assert "aes-256-gcm" in algorithm and "cbc" not in algorithm


def test_revision_table_set_is_frozen_against_future_metadata():
    revision_path = (
        Path(__file__).resolve().parents[2]
        / "alembic/versions/b1000002_v2_0002_trading_foundation.py"
    )
    revision_source = revision_path.read_text(encoding="utf-8")
    assert "from app.models" not in revision_source
    assert ".__table__" not in revision_source
    spec = importlib.util.spec_from_file_location("v2_0002_frozen_probe", revision_path)
    assert spec is not None and spec.loader is not None
    revision = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(revision)

    probe = Table(
        "future_revision_probe",
        Base.metadata,
        Column("id", BigInteger, primary_key=True),
        schema=TRADING_SCHEMA,
    )
    try:
        tables = revision._trading_tables_in_order()
        assert len(tables) == 20
        assert "future_revision_probe" not in {table.name for table in tables}
    finally:
        Base.metadata.remove(probe)


def test_idempotency_claims_global_unique():
    uq = _uniques("idempotency_claims")
    assert any({c.name for c in u.columns} == {"scope", "key"} for u in uq)


def test_transactional_outbox_contracts():
    tbl = TRADING["transactional_outbox"]
    # event_id 唯一（显式命名）
    assert any({c.name for c in u.columns} == {"event_id"} for u in _uniques("transactional_outbox"))
    # payload JSONB object + payload XOR artifact
    cks = _checks("transactional_outbox")
    assert "ck_transactional_outbox_payload_object" in cks
    assert "ck_transactional_outbox_payload_xor_artifact" in cks
    assert "ck_transactional_outbox_priority_range" in cks
    # PENDING partial index (available_at, id)
    idx = [i for i in tbl.indexes if i.name == "ix_transactional_outbox_pending"]
    assert len(idx) == 1
    assert [c.name for c in idx[0].columns] == ["available_at", "id"]
    assert idx[0].dialect_options["postgresql"]["where"] is not None


def test_outbox_delivery_history_partitioned_and_composite_pk():
    tbl = TRADING["outbox_delivery_history"]
    assert tbl.dialect_options["postgresql"]["partition_by"] == "RANGE (completed_at)"
    pk_names = {c.name for c in tbl.primary_key}
    assert "completed_at" in pk_names and "id" in pk_names  # 分区唯一键含 completed_at
    # append-only terminal history：无 updated_at
    assert "updated_at" not in tbl.c
    # 可追溯原 outbox event
    assert "outbox_event_id" in tbl.c and "outbox_id" in tbl.c


def test_job_completions_unique_consumer_key():
    uq = _uniques("job_completions")
    assert any({c.name for c in u.columns} == {"consumer", "idempotency_key"} for u in uq)


def test_fk_default_is_restrict_not_cascade():
    """除 lineage junction 与 vault self-supersede 外，FK 默认 RESTRICT（无 ondelete CASCADE）。"""
    for name, t in TRADING.items():
        for fk in t.foreign_keys:
            if name == "artifact_lineage_edges":
                assert fk.ondelete == "CASCADE"
            elif fk.target_fullname.startswith("trading.secret_vault_versions"):
                assert fk.ondelete == "SET NULL"
            else:
                assert fk.ondelete is None, f"{name} FK {fk.name} 应 RESTRICT"


def test_all_check_and_unique_and_index_explicitly_named():
    """除 PK（PG 确定性 <table>_pkey）外，所有 CHECK/UNIQUE/FK/index 必须显式命名。"""
    for name, t in TRADING.items():
        for c in t.constraints:
            if type(c).__name__ == "PrimaryKeyConstraint":
                continue
            assert c.name, f"{name}: 未命名 {type(c).__name__}"
        for fk in t.foreign_keys:
            assert fk.name, f"{name}: 未命名 FK"
        for ix in t.indexes:
            assert ix.name, f"{name}: 未命名 index"


def test_ddl_golden_fragments():
    from sqlalchemy.schema import CreateTable
    # partial index 渲染 WHERE
    tbl = TRADING["transactional_outbox"]
    idx = next(i for i in tbl.indexes if i.name == "ix_transactional_outbox_pending")
    from sqlalchemy.schema import CreateIndex
    sql = str(CreateIndex(idx).compile(dialect=postgresql.dialect()))
    assert "WHERE status = 'PENDING'" in sql
    # 分区表 DDL 渲染 PARTITION BY RANGE
    odh = TRADING["outbox_delivery_history"]
    ddl = str(CreateTable(odh).compile(dialect=postgresql.dialect()))
    assert "PARTITION BY RANGE (completed_at)" in ddl
