"""create p1a market master

Revision ID: b1000010
Revises: b1000002
Create Date: 2026-08-10 05:30:00

v2_0010 —— market master（WP-01B Checkpoint B）：``trading`` schema 下创建 9 张 market 表。

- ``upgrade``：创建 9 张表（frame/page、event/market/token master 与 version、lifecycle、
  current projection）与独立索引；安装 guard triggers：
  - ``pm_universe_frame_pages`` / ``pm_market_versions`` / ``pm_token_versions`` /
    ``pm_market_lifecycle_events`` append-only（复用 0002 的 ``v2_reject_immutable_row``）；
  - ``pm_universe_frames`` 只允许 OPEN→COMPLETE|FAILED 终态 transition；
  - ``pm_market_current`` ``observed_at`` CAS 单调（旧帧/乱序不得覆盖新值）。
- ``downgrade``：按依赖逆序删除 9 张表与 0010 专属 guard 函数；**不**删除 0002 拥有的
  ``v2_reject_immutable_row``（其 trigger 随表删除）。
- revision DDL 是固定快照，不导入 live ORM（Alembic revisions 不可变）。
"""
from dataclasses import dataclass
from typing import Sequence, Union

from alembic import op

TRADING_SCHEMA = "trading"

# revision identifiers, used by Alembic.
revision: str = "b1000010"
down_revision: Union[str, Sequence[str], None] = "b1000002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


@dataclass(frozen=True)
class _FrozenTableSpec:
    name: str
    create_sql: str
    index_sql: tuple[str, ...] = ()
    append_only: bool = False


_MARKET_TABLES = (
    _FrozenTableSpec(
        name='pm_universe_frames',
        create_sql='\nCREATE TABLE trading.pm_universe_frames (\n\tstatus VARCHAR(32) DEFAULT \'OPEN\' NOT NULL, \n\tstarted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\towner TEXT COLLATE "C" NOT NULL, \n\tlease_expires_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tfencing_token BIGINT NOT NULL, \n\tcompleted_at TIMESTAMP WITH TIME ZONE, \n\tpage_count INTEGER DEFAULT \'0\' NOT NULL, \n\ttotal_events INTEGER DEFAULT \'0\' NOT NULL, \n\ttotal_markets INTEGER DEFAULT \'0\' NOT NULL, \n\tcontent_hash VARCHAR(64) COLLATE "C", \n\tartifact_id BIGINT, \n\tartifact_ref VARCHAR(64) COLLATE "C", \n\terror_reason VARCHAR(128), \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_pm_universe_frames_status_known CHECK (status IN (\'OPEN\',\'COMPLETE\',\'FAILED\')), \n\tCONSTRAINT ck_pm_universe_frames_page_count_nonneg CHECK (page_count >= 0), \n\tCONSTRAINT ck_pm_universe_frames_total_events_nonneg CHECK (total_events >= 0), \n\tCONSTRAINT ck_pm_universe_frames_total_markets_nonneg CHECK (total_markets >= 0), \n\tCONSTRAINT ck_pm_universe_frames_owner_nonempty CHECK (length(owner) > 0), \n\tCONSTRAINT ck_pm_universe_frames_fencing_positive CHECK (fencing_token > 0), \n\tCONSTRAINT ck_pm_universe_frames_lease_after_start CHECK (lease_expires_at > started_at), \n\tCONSTRAINT ck_pm_universe_frames_completed_after_start CHECK (completed_at IS NULL OR completed_at >= started_at), \n\tCONSTRAINT ck_pm_universe_frames_terminal_shape CHECK ((status = \'OPEN\' AND completed_at IS NULL AND error_reason IS NULL) OR (status = \'COMPLETE\' AND completed_at IS NOT NULL AND content_hash IS NOT NULL AND artifact_id IS NOT NULL AND error_reason IS NULL) OR (status = \'FAILED\' AND completed_at IS NOT NULL AND error_reason IS NOT NULL)), \n\tCONSTRAINT fk_pm_universe_frames_artifact FOREIGN KEY(artifact_id) REFERENCES trading.artifact_objects (id)\n)\n\n',
        index_sql=(
            "CREATE INDEX ix_pm_universe_frames_open_lease ON "
            "trading.pm_universe_frames (lease_expires_at) WHERE status = 'OPEN'",
        ),
    ),
    _FrozenTableSpec(
        name='pm_universe_frame_pages',
        create_sql='\nCREATE TABLE trading.pm_universe_frame_pages (\n\tframe_id BIGINT NOT NULL, \n\tpage_no INTEGER NOT NULL, \n\tendpoint VARCHAR(16) NOT NULL, \n\tcursor_input TEXT, \n\tcursor_output TEXT, \n\titem_count INTEGER DEFAULT \'0\' NOT NULL, \n\traw_artifact_id BIGINT NOT NULL, \n\traw_artifact_ref VARCHAR(64) COLLATE "C" NOT NULL, \n\traw_artifact_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\treceived_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_pm_universe_frame_pages_frame_page UNIQUE (frame_id, page_no), \n\tCONSTRAINT uq_pm_universe_frame_pages_frame_endpoint_cursor UNIQUE (frame_id, endpoint, cursor_input), \n\tCONSTRAINT ck_pm_universe_frame_pages_endpoint_known CHECK (endpoint IN (\'events_open\',\'events_closed\',\'markets_open\',\'markets_closed\')), \n\tCONSTRAINT ck_pm_universe_frame_pages_page_no_nonneg CHECK (page_no >= 0), \n\tCONSTRAINT ck_pm_universe_frame_pages_item_count_nonneg CHECK (item_count >= 0), \n\tCONSTRAINT fk_pm_universe_frame_pages_frame FOREIGN KEY(frame_id) REFERENCES trading.pm_universe_frames (id), \n\tCONSTRAINT fk_pm_universe_frame_pages_raw_artifact FOREIGN KEY(raw_artifact_id) REFERENCES trading.artifact_objects (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_pm_universe_frame_pages_frame ON trading.pm_universe_frame_pages (frame_id, page_no)',),
        append_only=True,
    ),
    _FrozenTableSpec(
        name='pm_events',
        create_sql='\nCREATE TABLE trading.pm_events (\n\tgamma_event_id TEXT COLLATE "C" NOT NULL, \n\tslug TEXT, \n\ttitle TEXT, \n\tdescription TEXT, \n\tstart_date TIMESTAMP WITH TIME ZONE, \n\tend_date TIMESTAMP WITH TIME ZONE, \n\tactive BOOLEAN, \n\tclosed BOOLEAN, \n\tarchived BOOLEAN, \n\tvolume NUMERIC(38, 12), \n\tliquidity NUMERIC(38, 12), \n\tcontent_hash VARCHAR(64) COLLATE "C", \n\traw_artifact_ref VARCHAR(64) COLLATE "C", \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_pm_events_gamma_event_id UNIQUE (gamma_event_id)\n)\n\n',
        index_sql=('CREATE INDEX ix_pm_events_closed ON trading.pm_events (closed)', 'CREATE INDEX ix_pm_events_slug ON trading.pm_events (slug)'),
    ),
    _FrozenTableSpec(
        name='pm_markets',
        create_sql='\nCREATE TABLE trading.pm_markets (\n\tgamma_market_id TEXT COLLATE "C" NOT NULL, \n\tgamma_event_id TEXT COLLATE "C", \n\tcondition_id TEXT COLLATE "C", \n\tquestion TEXT, \n\tslug TEXT, \n\tticker TEXT, \n\tactive BOOLEAN, \n\tclosed BOOLEAN, \n\tarchived BOOLEAN, \n\taccepting_orders BOOLEAN, \n\tenable_order_book BOOLEAN, \n\tneg_risk BOOLEAN, \n\tstart_date TIMESTAMP WITH TIME ZONE, \n\tend_date TIMESTAMP WITH TIME ZONE, \n\tclosed_at TIMESTAMP WITH TIME ZONE, \n\tvolume NUMERIC(38, 12), \n\tliquidity NUMERIC(38, 12), \n\tspread NUMERIC(38, 12), \n\tbest_bid NUMERIC(38, 12), \n\tbest_ask NUMERIC(38, 12), \n\tlast_trade_price NUMERIC(38, 12), \n\tcontent_hash VARCHAR(64) COLLATE "C", \n\traw_artifact_ref VARCHAR(64) COLLATE "C", \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_pm_markets_gamma_market_id UNIQUE (gamma_market_id), \n\tCONSTRAINT uq_pm_markets_condition_id UNIQUE (condition_id), \n\tCONSTRAINT fk_pm_markets_gamma_event FOREIGN KEY(gamma_event_id) REFERENCES trading.pm_events (gamma_event_id)\n)\n\n',
        index_sql=('CREATE INDEX ix_pm_markets_gamma_event ON trading.pm_markets (gamma_event_id)', 'CREATE INDEX ix_pm_markets_tradeable ON trading.pm_markets (end_date, gamma_market_id) WHERE active AND NOT closed AND accepting_orders AND enable_order_book'),
    ),
    _FrozenTableSpec(
        name='pm_market_versions',
        create_sql='\nCREATE TABLE trading.pm_market_versions (\n\tmarket_id BIGINT NOT NULL, \n\tversion_no INTEGER NOT NULL, \n\tquestion TEXT, \n\tdescription TEXT, \n\trules TEXT, \n\tresolution_source TEXT, \n\tstart_date TIMESTAMP WITH TIME ZONE, \n\tend_date TIMESTAMP WITH TIME ZONE, \n\tactive BOOLEAN, \n\tclosed BOOLEAN, \n\tarchived BOOLEAN, \n\taccepting_orders BOOLEAN, \n\tenable_order_book BOOLEAN, \n\tneg_risk BOOLEAN, \n\tobserved_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\treceived_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\traw_artifact_ref VARCHAR(64) COLLATE "C", \n\tnormalized_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_pm_market_versions_market_version UNIQUE (market_id, version_no), \n\tCONSTRAINT ck_pm_market_versions_version_positive CHECK (version_no > 0), \n\tCONSTRAINT fk_pm_market_versions_market FOREIGN KEY(market_id) REFERENCES trading.pm_markets (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_pm_market_versions_market ON trading.pm_market_versions (market_id)',),
        append_only=True,
    ),
    _FrozenTableSpec(
        name='pm_tokens',
        create_sql='\nCREATE TABLE trading.pm_tokens (\n\ttoken_id TEXT COLLATE "C" NOT NULL, \n\tmarket_id BIGINT NOT NULL, \n\toutcome_index INTEGER NOT NULL, \n\toutcome_label VARCHAR(64), \n\tprice_hint NUMERIC(38, 12), \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_pm_tokens_token_id UNIQUE (token_id), \n\tCONSTRAINT uq_pm_tokens_market_index UNIQUE (market_id, outcome_index), \n\tCONSTRAINT ck_pm_tokens_outcome_index_binary CHECK (outcome_index IN (0,1)), \n\tCONSTRAINT fk_pm_tokens_market FOREIGN KEY(market_id) REFERENCES trading.pm_markets (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='pm_token_versions',
        create_sql='\nCREATE TABLE trading.pm_token_versions (\n\ttoken_id BIGINT NOT NULL, \n\tversion_no INTEGER NOT NULL, \n\toutcome_index INTEGER NOT NULL, \n\toutcome_label VARCHAR(64), \n\tprice_hint NUMERIC(38, 12), \n\tobserved_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\treceived_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_pm_token_versions_token_version UNIQUE (token_id, version_no), \n\tCONSTRAINT ck_pm_token_versions_version_positive CHECK (version_no > 0), \n\tCONSTRAINT ck_pm_token_versions_outcome_index_binary CHECK (outcome_index IN (0,1)), \n\tCONSTRAINT fk_pm_token_versions_token FOREIGN KEY(token_id) REFERENCES trading.pm_tokens (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_pm_token_versions_token ON trading.pm_token_versions (token_id)',),
        append_only=True,
    ),
    _FrozenTableSpec(
        name='pm_market_lifecycle_events',
        create_sql='\nCREATE TABLE trading.pm_market_lifecycle_events (\n\tmarket_id BIGINT NOT NULL, \n\tevent_type VARCHAR(32) NOT NULL, \n\tprovider_event_time TIMESTAMP WITH TIME ZONE, \n\tobserved_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\treceived_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tpayload_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\traw_artifact_ref VARCHAR(64) COLLATE "C", \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_pm_market_lifecycle_events_dedup UNIQUE (market_id, event_type, observed_at, payload_hash), \n\tCONSTRAINT ck_pm_market_lifecycle_events_type_known CHECK (event_type IN (\'created\',\'updated\',\'closed\',\'reopened\',\'resolved\',\'incomplete\')), \n\tCONSTRAINT fk_pm_market_lifecycle_events_market FOREIGN KEY(market_id) REFERENCES trading.pm_markets (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_pm_market_lifecycle_events_market ON trading.pm_market_lifecycle_events (market_id)',),
        append_only=True,
    ),
    _FrozenTableSpec(
        name='pm_market_current',
        create_sql='\nCREATE TABLE trading.pm_market_current (\n\tmarket_id BIGINT NOT NULL, \n\tcondition_id TEXT COLLATE "C", \n\tgamma_market_id TEXT COLLATE "C" NOT NULL, \n\ttokens_ok BOOLEAN DEFAULT false NOT NULL, \n\tmapping_state VARCHAR(32) DEFAULT \'incomplete\' NOT NULL, \n\teligible BOOLEAN DEFAULT false NOT NULL, \n\tcurrent_version_no INTEGER DEFAULT \'0\' NOT NULL, \n\tobserved_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcontent_hash VARCHAR(64) COLLATE "C", \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_pm_market_current_market UNIQUE (market_id), \n\tCONSTRAINT uq_pm_market_current_condition UNIQUE (condition_id), \n\tCONSTRAINT ck_pm_market_current_mapping_state_known CHECK (mapping_state IN (\'complete\',\'incomplete\',\'conflict\')), \n\tCONSTRAINT fk_pm_market_current_market FOREIGN KEY(market_id) REFERENCES trading.pm_markets (id)\n)\n\n',
    ),
)

# b1000002 + b1000010 的 revision-frozen 顶层 relation 清单。downgrade 在任何 DROP 前
# 对照它，避免把未知/下游对象留在半降级状态后才由 0002 发现。
_FOUNDATION_RELATIONS = (
    "artifact_objects", "artifact_lineage_edges", "archive_manifests",
    "retention_manifests", "runtime_config_versions", "strategy_objective_contracts",
    "strategy_versions", "execution_spec_versions", "capital_permission_manifests",
    "model_role_bindings", "release_manifests", "policy_type_scopes", "policy_freezes",
    "secret_vault_entries", "secret_vault_versions", "secret_access_events",
    "idempotency_claims", "transactional_outbox", "outbox_delivery_history",
    "job_completions",
)


def _assert_downgrade_safe() -> None:
    """Fail before destructive DDL when ``trading`` contains an unknown relation."""
    allowed = ", ".join(
        f"'{name}'" for name in (*_FOUNDATION_RELATIONS, *(t.name for t in _MARKET_TABLES))
    )
    op.execute(
        f"""
DO $v2_wp01b_preflight$
DECLARE
    unknown_objects text;
BEGIN
    SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
      INTO unknown_objects
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'trading'
       AND c.relkind IN ('r', 'p', 'v', 'm', 'f')
       AND c.relname NOT IN ({allowed})
       AND NOT EXISTS (
           SELECT 1
             FROM pg_inherits inheritance
             JOIN pg_class parent ON parent.oid = inheritance.inhparent
             JOIN pg_namespace parent_ns ON parent_ns.oid = parent.relnamespace
            WHERE inheritance.inhrelid = c.oid
              AND parent_ns.nspname = 'trading'
              AND parent.relname = 'outbox_delivery_history'
              AND c.relname ~ '^outbox_delivery_history_[0-9]{{6}}$'
       );
    IF unknown_objects IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp01b_unknown_object:%', unknown_objects USING ERRCODE='55000';
    END IF;
END $v2_wp01b_preflight$
"""
    )


def _create_table_indexes(table: _FrozenTableSpec) -> None:
    for statement in table.index_sql:
        op.execute(statement)


def _create_guards() -> None:
    # 0010 专属 guard functions（0002 的 v2_reject_immutable_row 继续复用）
    op.execute(
        """
CREATE FUNCTION trading.v2_guard_universe_frame() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    endpoint_name text;
    endpoint_pages integer;
    roots integer;
    terminals integer;
    bad_links integer;
    reached integer;
    actual_pages integer;
    actual_events integer;
    actual_markets integer;
BEGIN
    IF TG_OP = 'DELETE' OR OLD.status IN ('COMPLETE', 'FAILED') THEN
        RAISE EXCEPTION 'v2_universe_frame_immutable' USING ERRCODE='55000';
    END IF;

    IF NEW.id IS DISTINCT FROM OLD.id
       OR NEW.created_at IS DISTINCT FROM OLD.created_at
       OR NEW.started_at IS DISTINCT FROM OLD.started_at THEN
        RAISE EXCEPTION 'v2_universe_frame_identity_immutable' USING ERRCODE='55000';
    END IF;

    IF NEW.status = 'OPEN' THEN
        IF NEW.owner IS DISTINCT FROM OLD.owner
           OR NEW.fencing_token IS DISTINCT FROM OLD.fencing_token THEN
            IF OLD.lease_expires_at > clock_timestamp()
               OR NEW.owner = OLD.owner
               OR NEW.fencing_token <= OLD.fencing_token
               OR NEW.lease_expires_at <= clock_timestamp() THEN
                RAISE EXCEPTION 'v2_universe_frame_lease_cas_failed' USING ERRCODE='55000';
            END IF;
        ELSIF NEW.lease_expires_at < OLD.lease_expires_at THEN
            RAISE EXCEPTION 'v2_universe_frame_lease_regressed' USING ERRCODE='55000';
        END IF;
        RETURN NEW;
    END IF;

    IF NEW.status NOT IN ('COMPLETE', 'FAILED')
       OR NEW.owner IS DISTINCT FROM OLD.owner
       OR NEW.fencing_token IS DISTINCT FROM OLD.fencing_token
       OR NEW.lease_expires_at IS DISTINCT FROM OLD.lease_expires_at
       OR OLD.lease_expires_at <= clock_timestamp() THEN
        RAISE EXCEPTION 'v2_universe_frame_terminal_cas_failed' USING ERRCODE='55000';
    END IF;

    IF NEW.status = 'COMPLETE' THEN
        SELECT count(*),
               coalesce(sum(item_count) FILTER (
                   WHERE endpoint IN ('events_open', 'events_closed')), 0),
               coalesce(sum(item_count) FILTER (
                   WHERE endpoint IN ('markets_open', 'markets_closed')), 0)
          INTO actual_pages, actual_events, actual_markets
          FROM trading.pm_universe_frame_pages
         WHERE frame_id = OLD.id;
        IF NEW.page_count <> actual_pages
           OR NEW.total_events <> actual_events
           OR NEW.total_markets <> actual_markets THEN
            RAISE EXCEPTION 'v2_universe_frame_count_mismatch' USING ERRCODE='55000';
        END IF;

        FOREACH endpoint_name IN ARRAY ARRAY[
            'events_open', 'events_closed', 'markets_open', 'markets_closed'
        ] LOOP
            SELECT count(*),
                   count(*) FILTER (WHERE cursor_input IS NULL),
                   count(*) FILTER (WHERE cursor_output IS NULL)
              INTO endpoint_pages, roots, terminals
              FROM trading.pm_universe_frame_pages
             WHERE frame_id = OLD.id AND endpoint = endpoint_name;
            IF endpoint_pages = 0 OR roots <> 1 OR terminals <> 1 THEN
                RAISE EXCEPTION 'v2_universe_frame_cursor_chain_invalid:%', endpoint_name
                    USING ERRCODE='55000';
            END IF;

            SELECT count(*) INTO bad_links
              FROM trading.pm_universe_frame_pages page
             WHERE page.frame_id = OLD.id
               AND page.endpoint = endpoint_name
               AND (
                    (page.cursor_input IS NOT NULL AND
                     (SELECT count(*) FROM trading.pm_universe_frame_pages predecessor
                       WHERE predecessor.frame_id = OLD.id
                         AND predecessor.endpoint = endpoint_name
                         AND predecessor.cursor_output = page.cursor_input) <> 1)
                    OR
                    (page.cursor_output IS NOT NULL AND
                     (SELECT count(*) FROM trading.pm_universe_frame_pages successor
                       WHERE successor.frame_id = OLD.id
                         AND successor.endpoint = endpoint_name
                         AND successor.cursor_input = page.cursor_output) <> 1)
               );
            IF bad_links <> 0 THEN
                RAISE EXCEPTION 'v2_universe_frame_cursor_chain_invalid:%', endpoint_name
                    USING ERRCODE='55000';
            END IF;

            WITH RECURSIVE chain(id, cursor_output, path) AS (
                SELECT id, cursor_output, ARRAY[id]
                  FROM trading.pm_universe_frame_pages
                 WHERE frame_id = OLD.id AND endpoint = endpoint_name AND cursor_input IS NULL
                UNION ALL
                SELECT page.id, page.cursor_output, chain.path || page.id
                  FROM chain
                  JOIN trading.pm_universe_frame_pages page
                    ON page.frame_id = OLD.id
                   AND page.endpoint = endpoint_name
                   AND page.cursor_input = chain.cursor_output
                 WHERE NOT page.id = ANY(chain.path)
            )
            SELECT count(DISTINCT id) INTO reached FROM chain;
            IF reached <> endpoint_pages THEN
                RAISE EXCEPTION 'v2_universe_frame_cursor_chain_invalid:%', endpoint_name
                    USING ERRCODE='55000';
            END IF;
        END LOOP;
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        """
CREATE FUNCTION trading.v2_guard_universe_frame_page() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    frame_status text;
    frame_lease timestamptz;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'v2_immutable_row:pm_universe_frame_pages' USING ERRCODE='55000';
    END IF;
    SELECT status, lease_expires_at INTO frame_status, frame_lease
      FROM trading.pm_universe_frames
     WHERE id = NEW.frame_id
     FOR UPDATE;
    IF frame_status IS DISTINCT FROM 'OPEN' OR frame_lease <= clock_timestamp() THEN
        RAISE EXCEPTION 'v2_universe_frame_not_writable' USING ERRCODE='55000';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE FUNCTION trading.v2_guard_market_current() RETURNS trigger "
        "LANGUAGE plpgsql AS $v2_guard$ "
        "BEGIN "
        "  IF TG_OP = 'UPDATE' AND NEW.observed_at < OLD.observed_at THEN "
        "    RAISE EXCEPTION 'v2_market_current_stale_overwrite' USING ERRCODE='55000'; "
        "  END IF; "
        "  RETURN NEW; "
        "END $v2_guard$"
    )
    op.execute(
        "CREATE TRIGGER trg_pm_universe_frames_lifecycle "
        "BEFORE UPDATE OR DELETE ON trading.pm_universe_frames "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_universe_frame()"
    )
    op.execute(
        "CREATE TRIGGER trg_pm_universe_frame_pages_guard "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.pm_universe_frame_pages "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_universe_frame_page()"
    )
    op.execute(
        "CREATE TRIGGER trg_pm_market_current_cas "
        "BEFORE UPDATE ON trading.pm_market_current "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_market_current()"
    )
    for table in _MARKET_TABLES:
        if table.append_only and table.name != "pm_universe_frame_pages":
            op.execute(
                f"CREATE TRIGGER trg_{table.name}_immutable "
                f"BEFORE UPDATE OR DELETE ON {TRADING_SCHEMA}.{table.name} "
                "FOR EACH ROW EXECUTE FUNCTION trading.v2_reject_immutable_row()"
            )


def _drop_guards() -> None:
    for table in _MARKET_TABLES:
        if table.append_only and table.name != "pm_universe_frame_pages":
            op.execute(
                f"DROP TRIGGER IF EXISTS trg_{table.name}_immutable "
                f"ON {TRADING_SCHEMA}.{table.name}"
            )
    op.execute(
        "DROP TRIGGER IF EXISTS trg_pm_universe_frame_pages_guard "
        "ON trading.pm_universe_frame_pages"
    )
    op.execute("DROP TRIGGER IF EXISTS trg_pm_market_current_cas ON trading.pm_market_current")
    op.execute("DROP TRIGGER IF EXISTS trg_pm_universe_frames_lifecycle ON trading.pm_universe_frames")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_market_current()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_universe_frame_page()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_universe_frame()")


def upgrade() -> None:
    """Create 9 market master tables + indexes + guards（0002 已创建 trading schema）。"""
    for table in _MARKET_TABLES:
        op.execute(table.create_sql)
        _create_table_indexes(table)
    _create_guards()


def downgrade() -> None:
    """Drop 9 tables (reverse dependency order) + 0010-owned guard functions. 0002 的
    ``v2_reject_immutable_row`` 不删除（仍被 0002 拥有）。"""
    _assert_downgrade_safe()
    _drop_guards()
    for table in reversed(_MARKET_TABLES):
        op.execute(f"DROP TABLE {TRADING_SCHEMA}.{table.name}")
