"""create p3 learning settlement / evaluation / audit

Revision ID: b1000040
Revises: b1000031
Create Date: 2026-08-11 16:00:00

v2_0040 —— Label 审计、五层评价、科学回放、G8（WP-04 Checkpoint B）。

- ``upgrade``：
  - 14 张表（全部 append-only，复用 0002 的 ``v2_reject_immutable_row``）：
    resolution_labels / resolution_clusters / resolution_cluster_memberships /
    score_targets / score_target_memberships / score_observations / experiments /
    experiment_variants / challenger_variants / metric_runs / error_reviews /
    ablation_runs / promotion_decisions / replay_runs。
  - resolution_labels 状态机 deferred guard：pending→provisional→disputed|final_*，
    supersede 同 contract、version 连续、前一状态允许、每 (contract,label_key) 单 current。
  - resolution_clusters：OPEN cluster 不得引用 final_admissible label；相同 contract_spec
    不得属于两个 active cluster version（deferred）。
  - score_target_memberships：member_weight 定点数，deferred 核验每 target 总和=1、
    token 双计禁止。
  - score_observations：label_version 必须 final_admissible（BEFORE trigger）。
  - metric_runs lifecycle guard：RUNNING→COMPLETED|FAILED|INVALIDATED，terminal 禁改。
  - promotion_decisions：``NOT (promotion_type='capital' AND status='APPROVED')`` CHECK。
  - ``gate_decisions`` 强化：G8 + target_kind=metric_run；deferred trigger
    ``v2_validate_gate_g8`` 校验 metric run COMPLETED 且 release 与 version_manifest 一致。
- ``downgrade``：先 fail-closed preflight（未知 trading 对象 RAISE），drop guards，撤销
  gate_decisions G8 强化，逆序删 14 表。
"""
from dataclasses import dataclass
from typing import Sequence, Union

from alembic import op

TRADING_SCHEMA = "trading"

# revision identifiers, used by Alembic.
revision: str = "b1000040"
down_revision: Union[str, Sequence[str], None] = "b1000031"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_GATES_0031 = ("G0", "R0", "G1", "G2", "R1", "G4", "G5A", "G5B", "G6", "G7A", "G7B")
_GATES_0040 = (*_GATES_0031, "G8")


@dataclass(frozen=True)
class _FrozenTableSpec:
    name: str
    create_sql: str
    index_sql: tuple[str, ...] = ()
    append_only: bool = True


_LEARNING_TABLES = (
    _FrozenTableSpec(
        name='resolution_clusters',
        create_sql='\nCREATE TABLE trading.resolution_clusters (\n\tcluster_key TEXT COLLATE "C" NOT NULL, \n\tcluster_version INTEGER NOT NULL, \n\tsplit VARCHAR(16) NOT NULL, \n\ttime_block_start TIMESTAMP WITH TIME ZONE NOT NULL, \n\ttime_block_end TIMESTAMP WITH TIME ZONE NOT NULL, \n\thorizon VARCHAR(64) NOT NULL, \n\tstatus VARCHAR(16) DEFAULT \'OPEN\' NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_resolution_clusters_key_version UNIQUE (cluster_key, cluster_version), \n\tCONSTRAINT ck_resolution_clusters_split_known CHECK (split IN (\'train\',\'validation\',\'forward_holdout\')), \n\tCONSTRAINT ck_resolution_clusters_block_order CHECK (time_block_end > time_block_start), \n\tCONSTRAINT ck_resolution_clusters_status_known CHECK (status IN (\'OPEN\',\'FROZEN\',\'RESOLVED\'))\n)\n\n',
        append_only=False,
    ),
    _FrozenTableSpec(
        name='score_targets',
        create_sql='\nCREATE TABLE trading.score_targets (\n\ttarget_key TEXT COLLATE "C" NOT NULL, \n\ttarget_type VARCHAR(16) NOT NULL, \n\tcontract_spec_id BIGINT NOT NULL, \n\tresolution_cluster_id BIGINT NOT NULL, \n\thorizon VARCHAR(64) NOT NULL, \n\ttarget_weight NUMERIC(38, 12) NOT NULL, \n\tpayout_function_id BIGINT, \n\tcanonical_side VARCHAR(8), \n\tmembers JSONB, \n\tpayout_type VARCHAR(32) NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_score_targets_key UNIQUE (target_key), \n\tCONSTRAINT ck_score_targets_type_known CHECK (target_type IN (\'bernoulli\',\'multiclass\',\'mean_only\')), \n\tCONSTRAINT ck_score_targets_bernoulli_shape CHECK ((target_type = \'bernoulli\') = (canonical_side IS NOT NULL AND members IS NULL)), \n\tCONSTRAINT ck_score_targets_multiclass_shape CHECK ((target_type = \'multiclass\') = (members IS NOT NULL AND jsonb_typeof(members) = \'array\' AND canonical_side IS NULL)), \n\tCONSTRAINT ck_score_targets_mean_shape CHECK (target_type <> \'mean_only\' OR (canonical_side IS NULL AND members IS NULL)), \n\tCONSTRAINT ck_score_targets_side_known CHECK (canonical_side IS NULL OR canonical_side IN (\'YES\',\'NO\')), \n\tCONSTRAINT ck_score_targets_weight_range CHECK (target_weight > 0 AND target_weight <= 1), \n\tCONSTRAINT ck_score_targets_horizon_nonempty CHECK (length(btrim(horizon)) > 0), \n\tCONSTRAINT ck_score_targets_payout_type_pair CHECK ((target_type = \'bernoulli\' AND payout_type = \'binary\' AND payout_function_id IS NOT NULL) OR (target_type = \'multiclass\' AND payout_type = \'multiclass\' AND payout_function_id IS NULL) OR (target_type = \'mean_only\' AND payout_type = \'scalar\' AND payout_function_id IS NOT NULL)), \n\tCONSTRAINT fk_score_targets_spec FOREIGN KEY(contract_spec_id) REFERENCES trading.contract_specs (id), \n\tCONSTRAINT fk_score_targets_cluster FOREIGN KEY(resolution_cluster_id) REFERENCES trading.resolution_clusters (id), \n\tCONSTRAINT fk_score_targets_payout FOREIGN KEY(payout_function_id) REFERENCES trading.payout_functions (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='resolution_labels',
        create_sql='\nCREATE TABLE trading.resolution_labels (\n\tcontract_spec_id BIGINT NOT NULL, \n\tlabel_key TEXT COLLATE "C" NOT NULL, \n\tversion_no INTEGER NOT NULL, \n\tstate VARCHAR(32) NOT NULL, \n\tresolution_state VARCHAR(64), \n\tresolution_source VARCHAR(128), \n\tevidence_artifact_id BIGINT, \n\traw_outcome JSONB, \n\ttoken_cashflow JSONB, \n\tpolicy_code_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tsupersedes_id BIGINT, \n\tauditor_identity VARCHAR(128), \n\texclusion_reason VARCHAR(255), \n\tconflict_set JSONB, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_resolution_labels_identity UNIQUE (contract_spec_id, label_key, version_no), \n\tCONSTRAINT uq_resolution_labels_supersedes UNIQUE (supersedes_id), \n\tCONSTRAINT ck_resolution_labels_state_known CHECK (state IN (\'pending\',\'provisional\',\'disputed\',\'final_admissible\',\'final_excluded\')), \n\tCONSTRAINT ck_resolution_labels_admissible_shape CHECK (state <> \'final_admissible\' OR (resolution_state IS NOT NULL AND exclusion_reason IS NULL)), \n\tCONSTRAINT ck_resolution_labels_excluded_reason CHECK (state <> \'final_excluded\' OR exclusion_reason IS NOT NULL), \n\tCONSTRAINT ck_resolution_labels_disputed_conflict CHECK (state <> \'disputed\' OR (conflict_set IS NOT NULL AND jsonb_typeof(conflict_set) = \'array\')), \n\tCONSTRAINT ck_resolution_labels_policy_hash_hex CHECK (policy_code_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_resolution_labels_first_version CHECK ((supersedes_id IS NULL) = (version_no = 1)), \n\tCONSTRAINT fk_resolution_labels_spec FOREIGN KEY(contract_spec_id) REFERENCES trading.contract_specs (id), \n\tCONSTRAINT fk_resolution_labels_evidence FOREIGN KEY(evidence_artifact_id) REFERENCES trading.artifact_objects (id), \n\tCONSTRAINT fk_resolution_labels_supersedes FOREIGN KEY(supersedes_id) REFERENCES trading.resolution_labels (id)\n)\n\n',
        index_sql=(
            'CREATE INDEX ix_resolution_labels_contract ON trading.resolution_labels (contract_spec_id)',
            'CREATE INDEX ix_resolution_labels_label_key ON trading.resolution_labels (label_key)',
        ),
    ),
    _FrozenTableSpec(
        name='experiments',
        create_sql='\nCREATE TABLE trading.experiments (\n\texperiment_key TEXT COLLATE "C" NOT NULL, \n\thypothesis TEXT NOT NULL, \n\thypothesis_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tprimary_metric VARCHAR(64) NOT NULL, \n\tguardrails JSONB NOT NULL, \n\tunique_change_field VARCHAR(128) NOT NULL, \n\tchampion_input_manifest_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tchallenger_input_manifest_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tsample_policy JSONB NOT NULL, \n\tstopping_rule JSONB NOT NULL, \n\tseed BIGINT NOT NULL, \n\tstatus VARCHAR(16) DEFAULT \'PLANNED\' NOT NULL, \n\ttime_block_start TIMESTAMP WITH TIME ZONE NOT NULL, \n\ttime_block_end TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_experiments_key UNIQUE (experiment_key), \n\tCONSTRAINT ck_experiments_status_known CHECK (status IN (\'PLANNED\',\'RUNNING\',\'COMPLETED\',\'INVALIDATED\')), \n\tCONSTRAINT ck_experiments_hypothesis_hash_hex CHECK (hypothesis_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_experiments_champion_hash_hex CHECK (champion_input_manifest_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_experiments_challenger_hash_hex CHECK (challenger_input_manifest_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_experiments_distinct_manifests CHECK (champion_input_manifest_hash <> challenger_input_manifest_hash), \n\tCONSTRAINT ck_experiments_guardrails_object CHECK (jsonb_typeof(guardrails) = \'object\'), \n\tCONSTRAINT ck_experiments_sample_policy_object CHECK (jsonb_typeof(sample_policy) = \'object\'), \n\tCONSTRAINT ck_experiments_stopping_rule_object CHECK (jsonb_typeof(stopping_rule) = \'object\'), \n\tCONSTRAINT ck_experiments_block_order CHECK (time_block_end > time_block_start)\n)\n\n',
        append_only=False,
    ),
    _FrozenTableSpec(
        name='metric_runs',
        create_sql='\nCREATE TABLE trading.metric_runs (\n\trun_key TEXT COLLATE "C" NOT NULL, \n\tcohort_query_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tstrategy_version_id BIGINT NOT NULL, \n\trelease_manifest_id BIGINT NOT NULL, \n\tcohort_id BIGINT NOT NULL, \n\tobservation_ids JSONB NOT NULL, \n\tobservation_set_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n\tlabel_versions JSONB NOT NULL, \n\tsplit VARCHAR(16) NOT NULL, \n\ttime_blocks JSONB NOT NULL, \n\tcode_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tconfig_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tseed BIGINT NOT NULL, \n\tn_market INTEGER NOT NULL, \n\tn_episode INTEGER NOT NULL, \n\tn_resolution_cluster INTEGER NOT NULL, \n\tn_eff NUMERIC(38, 12) NOT NULL, \n\tresults JSONB NOT NULL, \n\tci JSONB NOT NULL, \n\tartifact_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tstatus VARCHAR(16) DEFAULT \'RUNNING\' NOT NULL, \n\tcompleted_at TIMESTAMP WITH TIME ZONE, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_metric_runs_key UNIQUE (run_key), \n\tCONSTRAINT ck_metric_runs_status_known CHECK (status IN (\'RUNNING\',\'COMPLETED\',\'FAILED\',\'INVALIDATED\')), \n\tCONSTRAINT ck_metric_runs_completed_pair CHECK ((status = \'COMPLETED\') = (completed_at IS NOT NULL)), \n\tCONSTRAINT ck_metric_runs_cohort_hash_hex CHECK (cohort_query_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_metric_runs_code_hash_hex CHECK (code_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_metric_runs_config_hash_hex CHECK (config_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_metric_runs_artifact_hash_hex CHECK (artifact_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_metric_runs_observation_ids_array CHECK (jsonb_typeof(observation_ids)=\'array\' AND jsonb_array_length(observation_ids)>0), \n\tCONSTRAINT ck_metric_runs_observation_set_hash_hex CHECK (observation_set_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_metric_runs_label_versions_object CHECK (jsonb_typeof(label_versions) = \'object\'), \n\tCONSTRAINT ck_metric_runs_time_blocks_object CHECK (jsonb_typeof(time_blocks) = \'object\'), \n\tCONSTRAINT ck_metric_runs_results_object CHECK (jsonb_typeof(results) = \'object\'), \n\tCONSTRAINT ck_metric_runs_ci_object CHECK (jsonb_typeof(ci) = \'object\'), \n\tCONSTRAINT ck_metric_runs_split_known CHECK (split IN (\'train\',\'validation\',\'forward_holdout\')), \n\tCONSTRAINT ck_metric_runs_counts_valid CHECK (n_market >= 0 AND n_episode >= 0 AND n_resolution_cluster > 0 AND n_eff > 0 AND n_eff <= n_resolution_cluster), \n\tCONSTRAINT fk_metric_runs_strategy FOREIGN KEY(strategy_version_id) REFERENCES trading.strategy_versions (id), \n\tCONSTRAINT fk_metric_runs_release FOREIGN KEY(release_manifest_id) REFERENCES trading.release_manifests (id), \n\tCONSTRAINT fk_metric_runs_cohort FOREIGN KEY(cohort_id) REFERENCES trading.evaluation_cohorts (id)\n)\n\n',
        index_sql=(
            'CREATE INDEX ix_metric_runs_strategy ON trading.metric_runs (strategy_version_id)',
            'CREATE INDEX ix_metric_runs_release ON trading.metric_runs (release_manifest_id)',
        ),
        append_only=False,
    ),
    _FrozenTableSpec(
        name='resolution_cluster_memberships',
        create_sql='\nCREATE TABLE trading.resolution_cluster_memberships (\n\tresolution_cluster_id BIGINT NOT NULL, \n\tcontract_spec_id BIGINT NOT NULL, \n\ttoken_id BIGINT NOT NULL, \n\tadded_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_resolution_cluster_memberships_pair UNIQUE (resolution_cluster_id, contract_spec_id, token_id), \n\tCONSTRAINT fk_resolution_cluster_memberships_cluster FOREIGN KEY(resolution_cluster_id) REFERENCES trading.resolution_clusters (id), \n\tCONSTRAINT fk_resolution_cluster_memberships_spec FOREIGN KEY(contract_spec_id) REFERENCES trading.contract_specs (id), \n\tCONSTRAINT fk_resolution_cluster_memberships_token FOREIGN KEY(token_id) REFERENCES trading.pm_tokens (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_resolution_cluster_memberships_contract ON trading.resolution_cluster_memberships (contract_spec_id)',),
    ),
    _FrozenTableSpec(
        name='score_target_memberships',
        create_sql='\nCREATE TABLE trading.score_target_memberships (\n\tscore_target_id BIGINT NOT NULL, \n\ttoken_id BIGINT NOT NULL, \n\tmember_weight NUMERIC(38, 12) NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_score_target_memberships_pair UNIQUE (score_target_id, token_id), \n\tCONSTRAINT ck_score_target_memberships_weight_positive CHECK (member_weight > 0), \n\tCONSTRAINT fk_score_target_memberships_target FOREIGN KEY(score_target_id) REFERENCES trading.score_targets (id), \n\tCONSTRAINT fk_score_target_memberships_token FOREIGN KEY(token_id) REFERENCES trading.pm_tokens (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_score_target_memberships_target ON trading.score_target_memberships (score_target_id)',),
    ),
    _FrozenTableSpec(
        name='score_observations',
        create_sql='\nCREATE TABLE trading.score_observations (\n\tobservation_key TEXT COLLATE "C" NOT NULL, \n\tscore_target_id BIGINT NOT NULL, \n\tsubmission_id BIGINT NOT NULL, \n\ttrade_decision_id BIGINT, \n\tlabel_version_id BIGINT NOT NULL, \n\tstatus VARCHAR(16) DEFAULT \'INCLUDED\' NOT NULL, \n\texclusion_reason VARCHAR(128), \n\tbaseline_quote_binding_ids JSONB, \n\tbaseline_value JSONB, \n\tbaseline_value_hash VARCHAR(64) COLLATE \"C\", \n\tbaseline_checkpoint_received_at TIMESTAMP WITH TIME ZONE, \n\tbaseline_quote NUMERIC(38, 12), \n\tbaseline_policy_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tsplit VARCHAR(16) NOT NULL, \n\talgorithm_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tmetric_id VARCHAR(64) NOT NULL, \n\tscore_value NUMERIC(38, 12), \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_score_observations_submission_target_label_metric UNIQUE (submission_id, score_target_id, label_version_id, metric_id), \n\tCONSTRAINT uq_score_observations_key UNIQUE (observation_key), \n\tCONSTRAINT ck_score_observations_baseline_range CHECK (baseline_quote IS NULL OR (baseline_quote > 0 AND baseline_quote <= 1)), \n\tCONSTRAINT ck_score_observations_binding_ids_array CHECK (baseline_quote_binding_ids IS NULL OR (jsonb_typeof(baseline_quote_binding_ids) = \'array\' AND jsonb_array_length(baseline_quote_binding_ids) > 0)), \n\tCONSTRAINT ck_score_observations_baseline_value_object CHECK (baseline_value IS NULL OR jsonb_typeof(baseline_value) = \'object\'), \n\tCONSTRAINT ck_score_observations_baseline_value_hash_hex CHECK (baseline_value_hash IS NULL OR baseline_value_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_score_observations_split_known CHECK (split IN (\'train\',\'validation\',\'forward_holdout\')), \n\tCONSTRAINT ck_score_observations_status_known CHECK (status IN (\'INCLUDED\',\'EXCLUDED\')), \n\tCONSTRAINT ck_score_observations_disposition_shape CHECK ((status=\'INCLUDED\' AND exclusion_reason IS NULL AND baseline_quote_binding_ids IS NOT NULL AND baseline_value IS NOT NULL AND baseline_value_hash IS NOT NULL AND baseline_checkpoint_received_at IS NOT NULL AND score_value IS NOT NULL) OR (status=\'EXCLUDED\' AND exclusion_reason IS NOT NULL AND baseline_quote IS NULL AND baseline_quote_binding_ids IS NULL AND baseline_value IS NULL AND baseline_value_hash IS NULL AND baseline_checkpoint_received_at IS NULL AND score_value IS NULL)), \n\tCONSTRAINT ck_score_observations_baseline_hash_hex CHECK (baseline_policy_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_score_observations_algorithm_hash_hex CHECK (algorithm_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT fk_score_observations_target FOREIGN KEY(score_target_id) REFERENCES trading.score_targets (id), \n\tCONSTRAINT fk_score_observations_submission FOREIGN KEY(submission_id) REFERENCES trading.forecast_submissions (id), \n\tCONSTRAINT fk_score_observations_decision FOREIGN KEY(trade_decision_id) REFERENCES trading.trade_decisions (id), \n\tCONSTRAINT fk_score_observations_label FOREIGN KEY(label_version_id) REFERENCES trading.resolution_labels (id)\n)\n\n',
        index_sql=(
            'CREATE INDEX ix_score_observations_submission ON trading.score_observations (submission_id)',
            'CREATE INDEX ix_score_observations_target ON trading.score_observations (score_target_id)',
        ),
    ),
    _FrozenTableSpec(
        name='experiment_variants',
        create_sql='\nCREATE TABLE trading.experiment_variants (\n\texperiment_id BIGINT NOT NULL, \n\tvariant_key TEXT COLLATE "C" NOT NULL, \n\tvariant_type VARCHAR(16) NOT NULL, \n\tinput_manifest_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tstrategy_version_id BIGINT NOT NULL, \n\trelease_manifest_id BIGINT NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_experiment_variants_experiment_key UNIQUE (experiment_id, variant_key), \n\tCONSTRAINT ck_experiment_variants_type_known CHECK (variant_type IN (\'champion\',\'challenger\')), \n\tCONSTRAINT ck_experiment_variants_manifest_hex CHECK (input_manifest_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT fk_experiment_variants_experiment FOREIGN KEY(experiment_id) REFERENCES trading.experiments (id), \n\tCONSTRAINT fk_experiment_variants_strategy FOREIGN KEY(strategy_version_id) REFERENCES trading.strategy_versions (id), \n\tCONSTRAINT fk_experiment_variants_release FOREIGN KEY(release_manifest_id) REFERENCES trading.release_manifests (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='challenger_variants',
        create_sql='\nCREATE TABLE trading.challenger_variants (\n\texperiment_id BIGINT NOT NULL, \n\tvariant_key TEXT COLLATE "C" NOT NULL, \n\tchallenger_type VARCHAR(32) NOT NULL, \n\tchanged_fields JSONB NOT NULL, \n\tpolicy_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tstatus VARCHAR(16) DEFAULT \'ACTIVE\' NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_challenger_variants_experiment_key UNIQUE (experiment_id, variant_key), \n\tCONSTRAINT ck_challenger_variants_status_known CHECK (status IN (\'ACTIVE\',\'SUPERSEDED\')), \n\tCONSTRAINT ck_challenger_variants_policy_hex CHECK (policy_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_challenger_variants_changed_object CHECK (jsonb_typeof(changed_fields) = \'object\'), \n\tCONSTRAINT fk_challenger_variants_experiment FOREIGN KEY(experiment_id) REFERENCES trading.experiments (id)\n)\n\n',
        append_only=False,
    ),
    _FrozenTableSpec(
        name='error_reviews',
        create_sql='\nCREATE TABLE trading.error_reviews (\n\treview_key TEXT COLLATE "C" NOT NULL, \n\treview_type VARCHAR(32) NOT NULL, \n\tmetric_run_id BIGINT NOT NULL, \n\tobservation_key TEXT COLLATE "C" NOT NULL, \n\troot_cause TEXT NOT NULL, \n\troot_cause_taxonomy VARCHAR(128) NOT NULL, \n\tseed BIGINT NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_error_reviews_key UNIQUE (review_key), \n\tCONSTRAINT ck_error_reviews_type_known CHECK (review_type IN (\'top_loss\',\'top_regret\',\'random_success\')), \n\tCONSTRAINT fk_error_reviews_metric_run FOREIGN KEY(metric_run_id) REFERENCES trading.metric_runs (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_error_reviews_metric_run ON trading.error_reviews (metric_run_id)',),
    ),
    _FrozenTableSpec(
        name='ablation_runs',
        create_sql='\nCREATE TABLE trading.ablation_runs (\n\tablation_key TEXT COLLATE "C" NOT NULL, \n\tmetric_run_id BIGINT NOT NULL, \n\tbundle_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tablation_fields JSONB NOT NULL, \n\tresult_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_ablation_runs_key UNIQUE (ablation_key), \n\tCONSTRAINT ck_ablation_runs_bundle_hash_hex CHECK (bundle_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_ablation_runs_result_hash_hex CHECK (result_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT fk_ablation_runs_metric_run FOREIGN KEY(metric_run_id) REFERENCES trading.metric_runs (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='promotion_decisions',
        create_sql='\nCREATE TABLE trading.promotion_decisions (\n\tpromotion_key TEXT COLLATE "C" NOT NULL, \n\tmetric_run_id BIGINT NOT NULL, \n\tpromotion_type VARCHAR(16) NOT NULL, \n\tfrom_ref VARCHAR(64) COLLATE "C" NOT NULL, \n\tto_ref VARCHAR(64) COLLATE "C" NOT NULL, \n\tevidence_manifest_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tstatus VARCHAR(16) NOT NULL, \n\treason_code VARCHAR(128), \n\tfuture_effective_at TIMESTAMP WITH TIME ZONE, \n\tcapital_amount NUMERIC(38, 0) DEFAULT \'0\' NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_promotion_decisions_key UNIQUE (promotion_key), \n\tCONSTRAINT ck_promotion_decisions_type_known CHECK (promotion_type IN (\'capital\',\'strategy\')), \n\tCONSTRAINT ck_promotion_decisions_status_known CHECK (status IN (\'APPROVED\',\'REJECTED\',\'DEFERRED\')), \n\tCONSTRAINT ck_promotion_decisions_capital_never_approved CHECK (NOT (promotion_type = \'capital\' AND status = \'APPROVED\')), \n\tCONSTRAINT ck_promotion_decisions_distinct_refs CHECK (from_ref <> to_ref), \n\tCONSTRAINT ck_promotion_decisions_future_pair CHECK ((status = \'APPROVED\') = (future_effective_at IS NOT NULL)), \n\tCONSTRAINT ck_promotion_decisions_reason_pair CHECK ((status = \'APPROVED\' AND reason_code IS NULL) OR (status IN (\'REJECTED\',\'DEFERRED\') AND reason_code IS NOT NULL)), \n\tCONSTRAINT ck_promotion_decisions_wp04_zero_capital CHECK (capital_amount = 0), \n\tCONSTRAINT ck_promotion_decisions_from_hex CHECK (from_ref ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_promotion_decisions_to_hex CHECK (to_ref ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_promotion_decisions_evidence_hex CHECK (evidence_manifest_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT fk_promotion_decisions_metric_run FOREIGN KEY(metric_run_id) REFERENCES trading.metric_runs (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_promotion_decisions_metric_run ON trading.promotion_decisions (metric_run_id)',),
    ),
    _FrozenTableSpec(
        name='replay_runs',
        create_sql='\nCREATE TABLE trading.replay_runs (\n\trun_key TEXT COLLATE "C" NOT NULL, \n\treplay_kind VARCHAR(16) NOT NULL, \n\tmanifest_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tcode_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tseed BIGINT NOT NULL, \n\tinput_artifact_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\toutput_artifact_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tresult JSONB, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_replay_runs_key UNIQUE (run_key), \n\tCONSTRAINT ck_replay_runs_kind_known CHECK (replay_kind IN (\'original\',\'new_code\',\'variant\')), \n\tCONSTRAINT ck_replay_runs_manifest_hash_hex CHECK (manifest_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_replay_runs_code_hash_hex CHECK (code_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_replay_runs_input_hash_hex CHECK (input_artifact_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_replay_runs_output_hash_hex CHECK (output_artifact_hash ~ \'^[0-9a-f]{64}$\')\n)\n\n',
    ),
)

# b1000031 已存在的 trading 关系（downgrade preflight allowlist）
_PRE_0040_RELATIONS = (
    "artifact_objects", "artifact_lineage_edges", "archive_manifests",
    "retention_manifests", "runtime_config_versions", "strategy_objective_contracts",
    "strategy_versions", "execution_spec_versions", "capital_permission_manifests",
    "model_role_bindings", "release_manifests", "policy_type_scopes", "policy_freezes",
    "secret_vault_entries", "secret_vault_versions", "secret_access_events",
    "idempotency_claims", "transactional_outbox", "outbox_delivery_history",
    "job_completions", "pm_universe_frames", "pm_universe_frame_pages", "pm_events",
    "pm_markets", "pm_market_versions", "pm_tokens", "pm_token_versions",
    "pm_market_lifecycle_events", "pm_market_current", "pm_connection_epochs",
    "pm_source_event_batches", "pm_source_event_index", "pm_book_checkpoints",
    "pm_book_levels", "pm_book_current", "pm_quote_bindings", "contract_snapshots",
    "contract_specs", "payout_functions", "forecast_components", "world_schema_versions",
    "forecast_component_versions", "forecast_component_contract_specs",
    "portfolio_dependency_edges", "evaluation_cohorts", "universe_memberships",
    "screening_episodes", "audit_samples", "decision_opportunities",
    "decision_opportunity_markets", "episode_memberships", "forecast_episodes",
    "episode_contract_specs", "information_snapshots", "information_snapshot_items",
    "gate_decisions", "priors", "evidence_coverage_policies", "evidence_revisions",
    "evidence_bundles", "evidence_bundle_items", "forecast_input_manifests",
    "forecast_submissions", "payout_projections", "coherence_checks",
    "forecast_challenges", "forecast_leases", "ai_invocations", "ai_tool_calls",
    "ai_validation_results", "market_relative_decisions", "discrepancy_reviews",
    "trade_decisions", "action_candidates", "resolution_cashflows", "action_sets",
    "action_set_legs", "underwriting_plans", "economic_action_intents",
    "executions", "positions", "position_lots", "ledger_transactions",
    "ledger_postings", "operating_cost_entries",
)


def _assert_downgrade_safe() -> None:
    allowed = ", ".join(
        f"'{name}'" for name in (*_PRE_0040_RELATIONS, *(t.name for t in _LEARNING_TABLES))
    )
    owned = ", ".join(f"'{t.name}'" for t in _LEARNING_TABLES)
    known_indexes = ", ".join(
        f"'{statement.split(' ON ')[0].replace('CREATE INDEX ', '').strip()}'"
        for table in _LEARNING_TABLES for statement in table.index_sql
    ) or "''"
    known_triggers = ", ".join(
        f"'{name}'" for name in (
            *(f"trg_{t.name}_immutable" for t in _LEARNING_TABLES if t.append_only),
            "trg_resolution_labels_payload", "trg_resolution_labels_current",
            "trg_resolution_clusters_lifecycle",
            "trg_resolution_cluster_memberships_outcome",
            "trg_score_target_memberships_weight", "trg_score_targets_complete",
            "trg_score_observations_label", "trg_metric_runs_lifecycle",
            "trg_metric_runs_evidence", "trg_promotion_decisions_validate",
            "trg_experiments_lifecycle", "trg_challenger_variants_lifecycle",
        )
    )
    op.execute(
        f"""
DO $v2_wp04_learning_preflight$
DECLARE unknown_objects text;
        unknown_indexes text;
        unknown_triggers text;
BEGIN
    SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
      INTO unknown_objects
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'trading'
       AND c.relkind IN ('r','p','v','m','f')
       AND c.relname NOT IN ({allowed})
       AND NOT EXISTS (
           SELECT 1 FROM pg_inherits i
           JOIN pg_class p ON p.oid = i.inhparent
           JOIN pg_namespace pn ON pn.oid = p.relnamespace
           WHERE i.inhrelid = c.oid AND pn.nspname = 'trading'
             AND ((p.relname = 'outbox_delivery_history'
                   AND c.relname ~ '^outbox_delivery_history_[0-9]{{6}}$')
               OR (p.relname IN ('pm_source_event_batches','pm_source_event_index',
                                  'pm_book_checkpoints','pm_book_levels')
                   AND c.relname ~ ('^' || p.relname || '_[0-9]{{8}}$'))
               OR (p.relname IN ('ai_invocations','ai_tool_calls','ai_validation_results')
                   AND c.relname ~ ('^' || p.relname || '_[0-9]{{6}}$')))
       );
    IF unknown_objects IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp04_learning_unknown_object:%', unknown_objects USING ERRCODE='55000';
    END IF;
    SELECT string_agg(idx.relname, ', ' ORDER BY idx.relname)
      INTO unknown_indexes
      FROM pg_index i
      JOIN pg_class idx ON idx.oid=i.indexrelid
      JOIN pg_class tbl ON tbl.oid=i.indrelid
      JOIN pg_namespace n ON n.oid=tbl.relnamespace
     WHERE n.nspname='trading' AND tbl.relname IN ({owned})
       AND NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conindid=idx.oid)
       AND idx.relname NOT IN ({known_indexes});
    IF unknown_indexes IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp04_learning_unknown_index:%', unknown_indexes USING ERRCODE='55000';
    END IF;
    SELECT string_agg(t.tgname, ', ' ORDER BY t.tgname)
      INTO unknown_triggers
      FROM pg_trigger t
      JOIN pg_class tbl ON tbl.oid=t.tgrelid
      JOIN pg_namespace n ON n.oid=tbl.relnamespace
     WHERE n.nspname='trading' AND tbl.relname IN ({owned})
       AND NOT t.tgisinternal AND t.tgname NOT IN ({known_triggers});
    IF unknown_triggers IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp04_learning_unknown_trigger:%', unknown_triggers USING ERRCODE='55000';
    END IF;
END $v2_wp04_learning_preflight$
"""
    )


def _reinforce_gate_g8() -> None:
    gate_values = ", ".join(f"'{g}'" for g in _GATES_0040)
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "DROP CONSTRAINT IF EXISTS ck_gate_decisions_gate_known"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        f"ADD CONSTRAINT ck_gate_decisions_gate_known CHECK (gate IN ({gate_values}))"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "DROP CONSTRAINT IF EXISTS ck_gate_decisions_target_kind_known"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "ADD CONSTRAINT ck_gate_decisions_target_kind_known CHECK ("
        "target_kind IN ('screening','opportunity','episode','trade_decision','metric_run'))"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "DROP CONSTRAINT IF EXISTS ck_gate_decisions_gate_target_pair"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "ADD CONSTRAINT ck_gate_decisions_gate_target_pair CHECK ("
        "(gate IN ('G0','R0') AND target_kind = 'screening') OR "
        "(gate IN ('G1','G2') AND target_kind = 'opportunity') OR "
        "(gate IN ('R1','G4','G5A','G5B','G6') AND target_kind = 'episode') OR "
        "(gate IN ('G7A','G7B') AND target_kind = 'trade_decision') OR "
        "(gate IN ('G8') AND target_kind = 'metric_run'))"
    )


def _unreinforce_gate_g8() -> None:
    gate_values = ", ".join(f"'{g}'" for g in _GATES_0031)
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "DROP CONSTRAINT IF EXISTS ck_gate_decisions_gate_known"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        f"ADD CONSTRAINT ck_gate_decisions_gate_known CHECK (gate IN ({gate_values}))"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "DROP CONSTRAINT IF EXISTS ck_gate_decisions_target_kind_known"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "ADD CONSTRAINT ck_gate_decisions_target_kind_known CHECK ("
        "target_kind IN ('screening','opportunity','episode','trade_decision'))"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "DROP CONSTRAINT IF EXISTS ck_gate_decisions_gate_target_pair"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "ADD CONSTRAINT ck_gate_decisions_gate_target_pair CHECK ("
        "(gate IN ('G0','R0') AND target_kind = 'screening') OR "
        "(gate IN ('G1','G2') AND target_kind = 'opportunity') OR "
        "(gate IN ('R1','G4','G5A','G5B','G6') AND target_kind = 'episode') OR "
        "(gate IN ('G7A','G7B') AND target_kind = 'trade_decision'))"
    )


def _gate_guard_0031_fn() -> str:
    return r"""
CREATE FUNCTION trading.v2_guard_gate_decision() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    root_id bigint;
    screening_id bigint;
    opportunity_id bigint;
BEGIN
    IF NEW.gate IN ('G0','R0') THEN
        IF NOT EXISTS (SELECT 1 FROM trading.screening_episodes WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NEW.gate IN ('G1','G2') THEN
        IF NOT EXISTS (SELECT 1 FROM trading.decision_opportunities WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NEW.gate IN ('G7A','G7B') THEN
        IF NOT EXISTS (SELECT 1 FROM trading.trade_decisions WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NOT EXISTS (SELECT 1 FROM trading.forecast_episodes WHERE id = NEW.target_id) THEN
        RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
    END IF;

    IF (NEW.gate = 'G0' AND NEW.result NOT IN ('PASS','PREDICTION_RESEARCH_ONLY'))
       OR (NEW.gate = 'R0' AND NEW.result NOT IN ('SELECT','DEFER','REJECT'))
       OR (NEW.gate IN ('G1','G2') AND NEW.result NOT IN ('PASS','FAIL'))
       OR (NEW.gate = 'R1' AND NEW.result NOT IN ('reject','shallow','standard','deep'))
       OR (NEW.gate = 'G4' AND NEW.result NOT IN ('PASS','FAIL'))
       OR (NEW.gate = 'G5A' AND NEW.result NOT IN ('PASS','ABSTAIN_EVIDENCE_INTEGRITY'))
       OR (NEW.gate = 'G5B' AND NEW.result NOT IN ('PASS','WIDEN_REQUIRED','ABSTAIN_EVIDENCE_INSUFFICIENT'))
       OR (NEW.gate IN ('G6','G7A','G7B') AND NEW.result NOT IN ('PASS','FAIL')) THEN
        RAISE EXCEPTION 'v2_gate_result_invalid' USING ERRCODE='23514';
    END IF;
    IF NEW.result IN ('PREDICTION_RESEARCH_ONLY','DEFER','REJECT','FAIL',
                      'ABSTAIN_EVIDENCE_INTEGRITY','WIDEN_REQUIRED','ABSTAIN_EVIDENCE_INSUFFICIENT','reject')
       AND NEW.reason_code IS NULL THEN
        RAISE EXCEPTION 'v2_gate_failure_reason_required' USING ERRCODE='23514';
    END IF;

    IF NEW.gate = 'R0' AND NOT EXISTS (
        SELECT 1 FROM trading.gate_decisions gd
         WHERE gd.gate = 'G0' AND gd.target_kind = 'screening'
           AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
    ) THEN
        RAISE EXCEPTION 'v2_gate_order_g0_r0' USING ERRCODE='23514';
    ELSIF NEW.gate = 'G1' THEN
        SELECT COALESCE(o.parent_id, o.id) INTO STRICT root_id
          FROM trading.decision_opportunities o WHERE o.id = NEW.target_id;
        SELECT source_screening_episode_id INTO screening_id
          FROM trading.decision_opportunities WHERE id = root_id;
        IF screening_id IS NULL OR NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'R0' AND gd.target_kind = 'screening'
               AND gd.target_id = screening_id
               AND (gd.result = 'SELECT' OR EXISTS (
                    SELECT 1 FROM trading.screening_episodes se
                     WHERE se.id = screening_id AND se.audit_assigned))
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_r0_g1' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G2' THEN
        SELECT COALESCE(o.parent_id, o.id) INTO STRICT root_id
          FROM trading.decision_opportunities o WHERE o.id = NEW.target_id;
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
            JOIN trading.decision_opportunities prior ON prior.id = gd.target_id
             WHERE gd.gate = 'G1' AND gd.target_kind = 'opportunity' AND gd.result = 'PASS'
               AND COALESCE(prior.parent_id, prior.id) = root_id
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g1_g2' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'R1' THEN
        SELECT decision_opportunity_id INTO STRICT opportunity_id
          FROM trading.forecast_episodes WHERE id = NEW.target_id;
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G2' AND gd.target_kind = 'opportunity'
               AND gd.target_id = opportunity_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g2_r1' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G4' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'R1' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id
               AND gd.result IN ('shallow','standard','deep')
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_r1_g4' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G5A' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G4' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g4_g5a' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G5B' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G5A' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g5a_g5b' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G6' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G5B' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g5b_g6' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G7B' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G7A' AND gd.target_kind = 'trade_decision'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g7a_g7b' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $v2_guard$
"""


def _gate_guard_g8_fn() -> str:
    return r"""
CREATE FUNCTION trading.v2_guard_gate_decision() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    root_id bigint;
    screening_id bigint;
    opportunity_id bigint;
BEGIN
    IF NEW.gate IN ('G0','R0') THEN
        IF NOT EXISTS (SELECT 1 FROM trading.screening_episodes WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NEW.gate IN ('G1','G2') THEN
        IF NOT EXISTS (SELECT 1 FROM trading.decision_opportunities WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NEW.gate IN ('G7A','G7B') THEN
        IF NOT EXISTS (SELECT 1 FROM trading.trade_decisions WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NEW.gate = 'G8' THEN
        IF NOT EXISTS (SELECT 1 FROM trading.metric_runs WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NOT EXISTS (SELECT 1 FROM trading.forecast_episodes WHERE id = NEW.target_id) THEN
        RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
    END IF;

    IF (NEW.gate = 'G0' AND NEW.result NOT IN ('PASS','PREDICTION_RESEARCH_ONLY'))
       OR (NEW.gate = 'R0' AND NEW.result NOT IN ('SELECT','DEFER','REJECT'))
       OR (NEW.gate IN ('G1','G2') AND NEW.result NOT IN ('PASS','FAIL'))
       OR (NEW.gate = 'R1' AND NEW.result NOT IN ('reject','shallow','standard','deep'))
       OR (NEW.gate = 'G4' AND NEW.result NOT IN ('PASS','FAIL'))
       OR (NEW.gate = 'G5A' AND NEW.result NOT IN ('PASS','ABSTAIN_EVIDENCE_INTEGRITY'))
       OR (NEW.gate = 'G5B' AND NEW.result NOT IN ('PASS','WIDEN_REQUIRED','ABSTAIN_EVIDENCE_INSUFFICIENT'))
       OR (NEW.gate IN ('G6','G7A','G7B','G8') AND NEW.result NOT IN ('PASS','FAIL')) THEN
        RAISE EXCEPTION 'v2_gate_result_invalid' USING ERRCODE='23514';
    END IF;
    IF NEW.result IN ('PREDICTION_RESEARCH_ONLY','DEFER','REJECT','FAIL',
                      'ABSTAIN_EVIDENCE_INTEGRITY','WIDEN_REQUIRED','ABSTAIN_EVIDENCE_INSUFFICIENT','reject')
       AND NEW.reason_code IS NULL THEN
        RAISE EXCEPTION 'v2_gate_failure_reason_required' USING ERRCODE='23514';
    END IF;

    IF NEW.gate = 'R0' AND NOT EXISTS (
        SELECT 1 FROM trading.gate_decisions gd
         WHERE gd.gate = 'G0' AND gd.target_kind = 'screening'
           AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
    ) THEN
        RAISE EXCEPTION 'v2_gate_order_g0_r0' USING ERRCODE='23514';
    ELSIF NEW.gate = 'G1' THEN
        SELECT COALESCE(o.parent_id, o.id) INTO STRICT root_id
          FROM trading.decision_opportunities o WHERE o.id = NEW.target_id;
        SELECT source_screening_episode_id INTO screening_id
          FROM trading.decision_opportunities WHERE id = root_id;
        IF screening_id IS NULL OR NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'R0' AND gd.target_kind = 'screening'
               AND gd.target_id = screening_id
               AND (gd.result = 'SELECT' OR EXISTS (
                    SELECT 1 FROM trading.screening_episodes se
                     WHERE se.id = screening_id AND se.audit_assigned))
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_r0_g1' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G2' THEN
        SELECT COALESCE(o.parent_id, o.id) INTO STRICT root_id
          FROM trading.decision_opportunities o WHERE o.id = NEW.target_id;
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
            JOIN trading.decision_opportunities prior ON prior.id = gd.target_id
             WHERE gd.gate = 'G1' AND gd.target_kind = 'opportunity' AND gd.result = 'PASS'
               AND COALESCE(prior.parent_id, prior.id) = root_id
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g1_g2' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'R1' THEN
        SELECT decision_opportunity_id INTO STRICT opportunity_id
          FROM trading.forecast_episodes WHERE id = NEW.target_id;
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G2' AND gd.target_kind = 'opportunity'
               AND gd.target_id = opportunity_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g2_r1' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G4' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'R1' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id
               AND gd.result IN ('shallow','standard','deep')
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_r1_g4' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G5A' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G4' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g4_g5a' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G5B' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G5A' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g5a_g5b' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G6' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G5B' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g5b_g6' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G7B' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G7A' AND gd.target_kind = 'trade_decision'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g7a_g7b' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $v2_guard$
"""


def _create_guards() -> None:
    # append-only 事实表（14 张全部不可变）。
    for table in _LEARNING_TABLES:
        if table.append_only:
            op.execute(
                f"CREATE TRIGGER trg_{table.name}_immutable "
                f"BEFORE UPDATE OR DELETE ON {TRADING_SCHEMA}.{table.name} "
                "FOR EACH ROW EXECUTE FUNCTION trading.v2_reject_immutable_row()"
            )
    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_experiment_lifecycle() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    IF TG_OP='INSERT' THEN
        IF NEW.status <> 'PLANNED' THEN
            RAISE EXCEPTION 'v2_experiment_initial_state_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF TG_OP='DELETE' OR
       (to_jsonb(NEW)-'status') IS DISTINCT FROM (to_jsonb(OLD)-'status') THEN
        RAISE EXCEPTION 'v2_experiment_immutable' USING ERRCODE='55000';
    END IF;
    IF NOT ((OLD.status='PLANNED' AND NEW.status='RUNNING') OR
            (OLD.status='RUNNING' AND NEW.status IN ('COMPLETED','INVALIDATED'))) THEN
        RAISE EXCEPTION 'v2_experiment_transition_invalid' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_experiments_lifecycle BEFORE INSERT OR UPDATE OR DELETE "
        "ON trading.experiments FOR EACH ROW "
        "EXECUTE FUNCTION trading.v2_guard_experiment_lifecycle()"
    )
    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_challenger_variant_lifecycle() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    IF TG_OP='INSERT' THEN
        IF NEW.status <> 'ACTIVE' THEN
            RAISE EXCEPTION 'v2_challenger_initial_state_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF TG_OP='DELETE' OR
       (to_jsonb(NEW)-'status') IS DISTINCT FROM (to_jsonb(OLD)-'status') THEN
        RAISE EXCEPTION 'v2_challenger_immutable' USING ERRCODE='55000';
    END IF;
    IF NOT (OLD.status='ACTIVE' AND NEW.status='SUPERSEDED') THEN
        RAISE EXCEPTION 'v2_challenger_transition_invalid' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_challenger_variants_lifecycle "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.challenger_variants "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_challenger_variant_lifecycle()"
    )
    # Terminal labels must be backed by the frozen contract/payout set.  The
    # deterministic compiler remains responsible for artifact byte hashing;
    # the database closes direct-write paths around evidence shape, resolution
    # source, canonical state, exact token set, and frozen payout values.
    op.execute(
        r"""
CREATE FUNCTION trading.v2_validate_label_payload() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    expected_tokens integer;
    supplied_tokens integer;
    bad_payouts integer;
    frozen_source text;
BEGIN
    IF NEW.state IN ('disputed','final_admissible','final_excluded') THEN
        IF NEW.evidence_artifact_id IS NULL OR NEW.raw_outcome IS NULL
           OR jsonb_typeof(NEW.raw_outcome) <> 'object'
           OR NEW.resolution_source IS NULL OR btrim(NEW.resolution_source) = ''
           OR NEW.auditor_identity IS NULL OR btrim(NEW.auditor_identity) = '' THEN
            RAISE EXCEPTION 'v2_label_terminal_evidence_incomplete' USING ERRCODE='23514';
        END IF;
    END IF;
    IF NEW.state <> 'final_admissible' THEN
        RETURN NEW;
    END IF;
    SELECT cs.token_count, snap.resolution_source
      INTO STRICT expected_tokens, frozen_source
      FROM trading.contract_specs cs
      LEFT JOIN trading.contract_snapshots snap ON snap.id = cs.snapshot_id
     WHERE cs.id = NEW.contract_spec_id AND cs.status = 'pass'
       AND cs.kc_resolution_states ? NEW.resolution_state;
    IF frozen_source IS NOT NULL AND btrim(frozen_source) <> ''
       AND frozen_source <> NEW.resolution_source THEN
        RAISE EXCEPTION 'v2_label_resolution_source_mismatch' USING ERRCODE='23514';
    END IF;
    IF NEW.token_cashflow IS NULL OR jsonb_typeof(NEW.token_cashflow) <> 'object' THEN
        RAISE EXCEPTION 'v2_label_cashflow_object_required' USING ERRCODE='23514';
    END IF;
    SELECT count(*) INTO supplied_tokens FROM jsonb_object_keys(NEW.token_cashflow);
    IF supplied_tokens <> expected_tokens THEN
        RAISE EXCEPTION 'v2_label_cashflow_token_set_mismatch' USING ERRCODE='23514';
    END IF;
    SELECT count(*) INTO bad_payouts
      FROM trading.payout_functions pf
     WHERE pf.contract_spec_id = NEW.contract_spec_id
       AND (
           NOT (NEW.token_cashflow ? pf.pm_token_id::text)
           OR (NEW.token_cashflow ->> pf.pm_token_id::text)
                !~ '^-?[0-9]+(?:\.[0-9]+)?$'
           OR (pf.function_ir ->> NEW.resolution_state) IS NULL
           OR (pf.function_ir ->> NEW.resolution_state)
                !~ '^-?[0-9]+(?:\.[0-9]+)?$'
           OR (NEW.token_cashflow ->> pf.pm_token_id::text)::numeric
                <> (pf.function_ir ->> NEW.resolution_state)::numeric
       );
    IF bad_payouts <> 0 OR (
        SELECT count(*) FROM trading.payout_functions
         WHERE contract_spec_id = NEW.contract_spec_id
    ) <> expected_tokens THEN
        RAISE EXCEPTION 'v2_label_frozen_payout_mismatch' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
EXCEPTION WHEN NO_DATA_FOUND THEN
    RAISE EXCEPTION 'v2_label_contract_state_invalid' USING ERRCODE='23514';
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_resolution_labels_payload "
        "BEFORE INSERT ON trading.resolution_labels FOR EACH ROW "
        "EXECUTE FUNCTION trading.v2_validate_label_payload()"
    )
    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_resolution_cluster() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    IF TG_OP='INSERT' THEN
        IF NEW.status <> 'OPEN' THEN
            RAISE EXCEPTION 'v2_cluster_initial_state_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF TG_OP='DELETE' THEN
        RAISE EXCEPTION 'v2_cluster_immutable' USING ERRCODE='55000';
    END IF;
    IF (to_jsonb(NEW)-'status') IS DISTINCT FROM (to_jsonb(OLD)-'status')
       OR NOT ((OLD.status='OPEN' AND NEW.status='FROZEN')
               OR (OLD.status='FROZEN' AND NEW.status='RESOLVED')) THEN
        RAISE EXCEPTION 'v2_cluster_transition_invalid' USING ERRCODE='23514';
    END IF;
    IF NEW.status='RESOLVED' AND EXISTS (
        SELECT 1 FROM (
            SELECT DISTINCT contract_spec_id
              FROM trading.resolution_cluster_memberships
             WHERE resolution_cluster_id=NEW.id
        ) m WHERE NOT EXISTS (
            SELECT 1 FROM trading.resolution_labels rl
             WHERE rl.contract_spec_id=m.contract_spec_id
               AND rl.state IN ('final_admissible','final_excluded')
               AND NOT EXISTS (SELECT 1 FROM trading.resolution_labels nxt
                                WHERE nxt.supersedes_id=rl.id)
        )
    ) THEN
        RAISE EXCEPTION 'v2_cluster_resolution_labels_incomplete' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_resolution_clusters_lifecycle "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.resolution_clusters "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_resolution_cluster()"
    )
    # resolution_labels 状态机 + supersede 连续性 + 单 current（deferred）。
    op.execute(
        r"""
CREATE FUNCTION trading.v2_check_label_revision() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    prev_version integer;
    prev_state text;
    current_count integer;
BEGIN
    IF NEW.supersedes_id IS NOT NULL THEN
        IF NOT EXISTS (SELECT 1 FROM trading.resolution_labels WHERE id = NEW.supersedes_id) THEN
            RAISE EXCEPTION 'v2_label_supersedes_missing' USING ERRCODE='23503';
        END IF;
        SELECT version_no, state INTO STRICT prev_version, prev_state
          FROM trading.resolution_labels WHERE id = NEW.supersedes_id;
        IF NOT EXISTS (
            SELECT 1 FROM trading.resolution_labels p
             WHERE p.id = NEW.supersedes_id
               AND p.contract_spec_id = NEW.contract_spec_id
               AND p.label_key = NEW.label_key
        ) THEN
            RAISE EXCEPTION 'v2_label_supersedes_cross_contract' USING ERRCODE='23514';
        END IF;
        IF prev_version + 1 <> NEW.version_no THEN
            RAISE EXCEPTION 'v2_label_supersedes_version_gap' USING ERRCODE='23514';
        END IF;
        IF prev_state NOT IN ('pending','provisional') THEN
            RAISE EXCEPTION 'v2_label_supersedes_terminal_state' USING ERRCODE='23514';
        END IF;
        IF (prev_state = 'pending' AND NEW.state <> 'provisional')
           OR (prev_state = 'provisional' AND NEW.state NOT IN ('disputed','final_admissible','final_excluded')) THEN
            RAISE EXCEPTION 'v2_label_transition_invalid' USING ERRCODE='23514';
        END IF;
    ELSE
        IF NEW.version_no <> 1 THEN
            RAISE EXCEPTION 'v2_label_first_version_requires_no_supersede' USING ERRCODE='23514';
        END IF;
        IF NEW.state <> 'pending' THEN
            RAISE EXCEPTION 'v2_label_initial_state_must_be_pending' USING ERRCODE='23514';
        END IF;
    END IF;

    SELECT count(*) INTO current_count
      FROM trading.resolution_labels r
     WHERE r.contract_spec_id = NEW.contract_spec_id
       AND r.label_key = NEW.label_key
       AND NOT EXISTS (
           SELECT 1 FROM trading.resolution_labels s
            WHERE s.contract_spec_id = r.contract_spec_id
              AND s.label_key = r.label_key
              AND s.supersedes_id = r.id
       );
    IF current_count > 1 THEN
        RAISE EXCEPTION 'v2_label_multiple_current' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER trg_resolution_labels_current "
        "AFTER INSERT ON trading.resolution_labels "
        "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
        "EXECUTE FUNCTION trading.v2_check_label_revision()"
    )
    # resolution_clusters：OPEN cluster 不得引用 final_admissible label；同 contract_spec
    # 不得属于两个 active cluster version（deferred，双向）。
    op.execute(
        r"""
CREATE FUNCTION trading.v2_check_cluster_outcome_unknown() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    cluster_status text;
BEGIN
    PERFORM pg_advisory_xact_lock(hashtextextended(
        'v2_resolution_cluster_spec:' || NEW.contract_spec_id::text, 0));
    SELECT status INTO STRICT cluster_status
      FROM trading.resolution_clusters WHERE id = NEW.resolution_cluster_id;
    IF cluster_status <> 'OPEN' THEN
        RAISE EXCEPTION 'v2_cluster_membership_not_open' USING ERRCODE='23514';
    END IF;
    IF EXISTS (
        SELECT 1 FROM trading.resolution_labels rl
         WHERE rl.contract_spec_id = NEW.contract_spec_id
           AND rl.state <> 'pending'
    ) THEN
        RAISE EXCEPTION 'v2_cluster_assigned_after_outcome' USING ERRCODE='23514';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM trading.payout_functions pf
         WHERE pf.contract_spec_id = NEW.contract_spec_id
           AND pf.pm_token_id = NEW.token_id
    ) THEN
        RAISE EXCEPTION 'v2_cluster_membership_spec_token_mismatch' USING ERRCODE='23514';
    END IF;
    IF EXISTS (
        SELECT 1 FROM trading.resolution_cluster_memberships m
        JOIN trading.resolution_clusters c ON c.id = m.resolution_cluster_id
        WHERE m.contract_spec_id = NEW.contract_spec_id
          AND m.resolution_cluster_id <> NEW.resolution_cluster_id
          AND c.status IN ('OPEN','FROZEN')
    ) THEN
        RAISE EXCEPTION 'v2_cluster_membership_contract_already_active' USING ERRCODE='23505';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER trg_resolution_cluster_memberships_outcome "
        "AFTER INSERT ON trading.resolution_cluster_memberships "
        "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
        "EXECUTE FUNCTION trading.v2_check_cluster_outcome_unknown()"
    )
    # score_target_memberships：权重归一（总和=1）+ token 双计禁止（deferred）。
    op.execute(
        r"""
CREATE FUNCTION trading.v2_check_target_membership() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    total numeric;
    cluster_total numeric;
    target_contract bigint;
    target_cluster bigint;
    target_kind text;
    target_payout bigint;
    target_members jsonb;
    target_id bigint;
    member_count integer;
BEGIN
    target_id := COALESCE((to_jsonb(NEW)->>'score_target_id')::bigint, NEW.id);
    SELECT contract_spec_id, resolution_cluster_id, target_type,
           payout_function_id, members
      INTO STRICT target_contract, target_cluster, target_kind,
                  target_payout, target_members
      FROM trading.score_targets WHERE id = target_id;
    IF NOT EXISTS (
        SELECT 1 FROM trading.resolution_cluster_memberships m
        JOIN trading.resolution_clusters c ON c.id = m.resolution_cluster_id
         WHERE m.resolution_cluster_id = target_cluster
           AND m.contract_spec_id = target_contract
           AND c.horizon = (SELECT horizon FROM trading.score_targets WHERE id=target_id)
    ) THEN
        RAISE EXCEPTION 'v2_target_cluster_spec_horizon_mismatch' USING ERRCODE='23514';
    END IF;
    IF EXISTS (
        SELECT 1 FROM trading.score_target_memberships tm
        JOIN trading.score_targets t ON t.id = tm.score_target_id
        WHERE tm.token_id IN (
                SELECT token_id FROM trading.score_target_memberships
                 WHERE score_target_id = target_id)
          AND t.contract_spec_id = target_contract
          AND tm.score_target_id <> target_id
    ) THEN
        RAISE EXCEPTION 'v2_target_membership_token_double_counted' USING ERRCODE='23505';
    END IF;
    IF EXISTS (
        SELECT 1 FROM trading.score_target_memberships tm
         WHERE tm.score_target_id = target_id
           AND (NOT EXISTS (
                SELECT 1 FROM trading.payout_functions pf
                 WHERE pf.contract_spec_id = target_contract
                   AND pf.pm_token_id = tm.token_id)
                OR NOT EXISTS (
                SELECT 1 FROM trading.resolution_cluster_memberships cm
                 WHERE cm.resolution_cluster_id = target_cluster
                   AND cm.contract_spec_id = target_contract
                   AND cm.token_id = tm.token_id))
    ) THEN
        RAISE EXCEPTION 'v2_target_membership_spec_token_mismatch' USING ERRCODE='23514';
    END IF;
    SELECT COALESCE(sum(member_weight), 0) INTO total
      FROM trading.score_target_memberships
     WHERE score_target_id = target_id;
    IF total <> 1 THEN
        RAISE EXCEPTION 'v2_target_membership_weight_not_one' USING ERRCODE='23514';
    END IF;
    SELECT count(*) INTO member_count FROM trading.score_target_memberships
     WHERE score_target_id = target_id;
    IF (target_kind IN ('bernoulli','mean_only') AND member_count <> 1)
       OR (target_kind = 'multiclass' AND
           (member_count < 2 OR jsonb_array_length(target_members) <> member_count)) THEN
        RAISE EXCEPTION 'v2_target_membership_canonical_shape' USING ERRCODE='23514';
    END IF;
    IF target_payout IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM trading.payout_functions pf
        JOIN trading.score_target_memberships tm
          ON tm.score_target_id=target_id AND tm.token_id=pf.pm_token_id
         WHERE pf.id=target_payout AND pf.contract_spec_id=target_contract
    ) THEN
        RAISE EXCEPTION 'v2_target_payout_function_mismatch' USING ERRCODE='23514';
    END IF;
    SELECT COALESCE(sum(target_weight), 0) INTO cluster_total
      FROM trading.score_targets t
     WHERE t.resolution_cluster_id=target_cluster
       AND t.horizon=(SELECT horizon FROM trading.score_targets WHERE id=target_id);
    IF cluster_total <> 1 THEN
        RAISE EXCEPTION 'v2_target_cluster_weight_not_one' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER trg_score_target_memberships_weight "
        "AFTER INSERT OR UPDATE ON trading.score_target_memberships "
        "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
        "EXECUTE FUNCTION trading.v2_check_target_membership()"
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER trg_score_targets_complete "
        "AFTER INSERT ON trading.score_targets DEFERRABLE INITIALLY DEFERRED "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_check_target_membership()"
    )
    # score_observations：label_version 必须 final_admissible（§5.3）。
    op.execute(
        r"""
CREATE FUNCTION trading.v2_check_score_observation_label() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    target_contract bigint;
    target_cluster bigint;
    target_kind text;
    submission_episode bigint;
    blind_commit timestamptz;
    cluster_split text;
    expected_members integer;
    bound_members integer;
    baseline_total numeric;
    max_checkpoint_received_at timestamptz;
    min_checkpoint_received_at timestamptz;
BEGIN
    SELECT t.contract_spec_id, t.resolution_cluster_id, t.target_type,
           fs.episode_id, fs.committed_at, c.split
      INTO STRICT target_contract, target_cluster, target_kind,
                  submission_episode, blind_commit, cluster_split
      FROM trading.score_targets t
      JOIN trading.resolution_clusters c ON c.id=t.resolution_cluster_id
      JOIN trading.forecast_submissions fs ON fs.id=NEW.submission_id
     WHERE t.id=NEW.score_target_id AND fs.status='BLIND_COMMITTED';
    IF NOT EXISTS (
        SELECT 1 FROM trading.resolution_labels rl
         WHERE rl.id=NEW.label_version_id AND rl.state='final_admissible'
           AND rl.contract_spec_id=target_contract
    ) THEN
        RAISE EXCEPTION 'v2_score_observation_label_not_admissible' USING ERRCODE='23514';
    END IF;
    IF NEW.split <> cluster_split OR NOT EXISTS (
        SELECT 1 FROM trading.episode_contract_specs ecs
         WHERE ecs.episode_id=submission_episode
           AND ecs.contract_spec_id=target_contract
    ) THEN
        RAISE EXCEPTION 'v2_score_observation_target_split_mismatch' USING ERRCODE='23514';
    END IF;
    IF NEW.trade_decision_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM trading.trade_decisions td
         WHERE td.id=NEW.trade_decision_id
           AND td.forecast_submission_id=NEW.submission_id
           AND td.episode_id=submission_episode
    ) THEN
        RAISE EXCEPTION 'v2_score_observation_decision_mismatch' USING ERRCODE='23514';
    END IF;
    IF (target_kind='bernoulli' AND NEW.metric_id NOT IN ('bernoulli_brier','bernoulli_log_loss'))
       OR (target_kind='multiclass' AND NEW.metric_id NOT IN ('multiclass_brier','multiclass_log_loss'))
       OR (target_kind='mean_only' AND NEW.metric_id <> 'mean_squared_payout_loss') THEN
        RAISE EXCEPTION 'v2_score_observation_metric_target_mismatch' USING ERRCODE='23514';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM trading.forecast_submissions fs
        JOIN trading.forecast_episodes fe ON fe.id=fs.episode_id
        JOIN trading.decision_opportunities dop ON dop.id=fe.decision_opportunity_id
        JOIN trading.evaluation_cohorts ec ON ec.id=dop.cohort_id
        JOIN trading.policy_freezes pf
          ON pf.policy_content_hash=NEW.baseline_policy_hash
         AND pf.release_manifest_id=ec.release_manifest_id
         WHERE fs.id=NEW.submission_id
           AND ec.policy_hashes->>'baseline_convention'=NEW.baseline_policy_hash
    ) THEN
        RAISE EXCEPTION 'v2_score_observation_policy_not_frozen' USING ERRCODE='23514';
    END IF;
    IF NEW.status='EXCLUDED' THEN
        RETURN NEW;
    END IF;
    SELECT count(*) INTO expected_members FROM trading.score_target_memberships
     WHERE score_target_id=NEW.score_target_id;
    SELECT count(DISTINCT qb.id), min(qb.checkpoint_received_at),
           max(qb.checkpoint_received_at)
      INTO bound_members, min_checkpoint_received_at, max_checkpoint_received_at
      FROM jsonb_array_elements_text(NEW.baseline_quote_binding_ids) ids(value)
      JOIN trading.pm_quote_bindings qb ON qb.id=ids.value::bigint
      JOIN trading.pm_tokens pt ON pt.token_id=qb.token_id
      JOIN trading.score_target_memberships tm
        ON tm.score_target_id=NEW.score_target_id AND tm.token_id=pt.id
     WHERE qb.received_at <= blind_commit AND qb.stale_at > blind_commit
       AND NEW.baseline_value ? tm.token_id::text
       AND (NEW.baseline_value->>tm.token_id::text)
             ~ '^[0-9]+(?:\.[0-9]+)?$'
       AND (NEW.baseline_value->>tm.token_id::text)::numeric
             = (qb.best_bid + qb.best_ask) / 2;
    IF bound_members <> expected_members
       OR jsonb_array_length(NEW.baseline_quote_binding_ids) <> expected_members
       OR (SELECT count(*) FROM jsonb_object_keys(NEW.baseline_value)) <> expected_members
       OR max_checkpoint_received_at IS DISTINCT FROM NEW.baseline_checkpoint_received_at
       OR min_checkpoint_received_at IS DISTINCT FROM max_checkpoint_received_at THEN
        RAISE EXCEPTION 'v2_score_observation_baseline_mismatch' USING ERRCODE='23514';
    END IF;
    SELECT sum((value)::numeric) INTO baseline_total
      FROM jsonb_each_text(NEW.baseline_value);
    IF (target_kind='multiclass' AND
        (NEW.baseline_quote IS NOT NULL OR baseline_total <> 1))
       OR (target_kind IN ('bernoulli','mean_only') AND
           (expected_members <> 1 OR NEW.baseline_quote IS NULL OR
            NEW.baseline_quote <> (SELECT (value)::numeric
                                      FROM jsonb_each_text(NEW.baseline_value)))) THEN
        RAISE EXCEPTION 'v2_score_observation_baseline_shape' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
EXCEPTION WHEN NO_DATA_FOUND THEN
    RAISE EXCEPTION 'v2_score_observation_identity_missing' USING ERRCODE='23514';
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_score_observations_label "
        "BEFORE INSERT ON trading.score_observations "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_check_score_observation_label()"
    )
    op.execute(
        r"""
CREATE FUNCTION trading.v2_validate_metric_run_evidence() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    label_count integer;
    admissible_count integer;
    cluster_count integer;
    observation_count integer;
    valid_observation_count integer;
    episode_count integer;
    market_count integer;
    observation_label_count integer;
    eligible_observation_count integer;
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM trading.release_manifests rm
        JOIN trading.evaluation_cohorts ec
          ON ec.id=NEW.cohort_id
         AND ec.release_manifest_id=rm.id
         AND ec.strategy_version_id=NEW.strategy_version_id
        JOIN trading.capital_permission_manifests cp
          ON cp.id=rm.capital_permission_manifest_id
         WHERE rm.id=NEW.release_manifest_id
           AND rm.strategy_version_id=NEW.strategy_version_id
           AND rm.status='active' AND cp.status='active'
           AND cp.mode='shadow' AND cp.authorized_capital=0
           AND NOT cp.kill_switch
    ) THEN
        RAISE EXCEPTION 'v2_metric_run_release_mismatch' USING ERRCODE='23514';
    END IF;
    IF NEW.status <> 'COMPLETED' THEN
        RETURN NEW;
    END IF;
    IF NEW.label_versions='{}'::jsonb OR NEW.time_blocks='{}'::jsonb
       OR NOT (NEW.results ?& ARRAY['prediction','selection','edge','portfolio','execution'])
       OR NEW.ci='{}'::jsonb THEN
        RAISE EXCEPTION 'v2_metric_run_evidence_incomplete' USING ERRCODE='23514';
    END IF;
    WITH ids AS (
        SELECT value::bigint AS observation_id
          FROM jsonb_array_elements_text(NEW.observation_ids)
    ), checked AS (
        SELECT ids.observation_id, so.id AS valid_id, fs.episode_id,
               st.resolution_cluster_id
          FROM ids
          LEFT JOIN trading.score_observations so ON so.id=ids.observation_id
          LEFT JOIN trading.forecast_submissions fs ON fs.id=so.submission_id
          LEFT JOIN trading.forecast_episodes fe ON fe.id=fs.episode_id
          LEFT JOIN trading.decision_opportunities dop
            ON dop.id=fe.decision_opportunity_id
          LEFT JOIN trading.score_targets st ON st.id=so.score_target_id
          LEFT JOIN trading.resolution_clusters rc
            ON rc.id=st.resolution_cluster_id
          LEFT JOIN trading.trade_decisions td ON td.id=so.trade_decision_id
         WHERE so.split=NEW.split AND dop.cohort_id=NEW.cohort_id
           AND fe.strategy_version_id=NEW.strategy_version_id
           AND (td.id IS NULL OR td.release_manifest_id=NEW.release_manifest_id)
           AND NEW.time_blocks ? rc.horizon
           AND (NEW.time_blocks->>rc.horizon) ~ '^\d{4}-\d{2}-\d{2}$'
           AND (NEW.time_blocks->>rc.horizon)
                 BETWEEN rc.time_block_start::date::text
                     AND rc.time_block_end::date::text
    )
    SELECT count(DISTINCT observation_id), count(DISTINCT valid_id),
           count(DISTINCT episode_id), count(DISTINCT resolution_cluster_id)
      INTO observation_count, valid_observation_count, episode_count, cluster_count
      FROM checked;
    SELECT count(*) INTO eligible_observation_count
      FROM trading.score_observations so
      JOIN trading.forecast_submissions fs ON fs.id=so.submission_id
      JOIN trading.forecast_episodes fe ON fe.id=fs.episode_id
      JOIN trading.decision_opportunities dop
        ON dop.id=fe.decision_opportunity_id
      JOIN trading.score_targets st ON st.id=so.score_target_id
      JOIN trading.resolution_clusters rc ON rc.id=st.resolution_cluster_id
      LEFT JOIN trading.trade_decisions td ON td.id=so.trade_decision_id
     WHERE so.split=NEW.split AND dop.cohort_id=NEW.cohort_id
       AND fe.strategy_version_id=NEW.strategy_version_id
       AND (td.id IS NULL OR td.release_manifest_id=NEW.release_manifest_id)
       AND NEW.time_blocks ? rc.horizon
       AND (NEW.time_blocks->>rc.horizon) ~ '^\d{4}-\d{2}-\d{2}$'
       AND (NEW.time_blocks->>rc.horizon)
             BETWEEN rc.time_block_start::date::text
                 AND rc.time_block_end::date::text;
    SELECT count(DISTINCT pt.market_id) INTO market_count
      FROM jsonb_array_elements_text(NEW.observation_ids) ids(value)
      JOIN trading.score_observations so ON so.id=ids.value::bigint
      JOIN trading.score_target_memberships stm ON stm.score_target_id=so.score_target_id
      JOIN trading.pm_tokens pt ON pt.id=stm.token_id;
    IF observation_count <> jsonb_array_length(NEW.observation_ids)
       OR valid_observation_count <> observation_count
       OR eligible_observation_count <> observation_count
       OR episode_count <> NEW.n_episode OR cluster_count <> NEW.n_resolution_cluster
       OR market_count <> NEW.n_market THEN
        RAISE EXCEPTION 'v2_metric_run_observation_set_mismatch' USING ERRCODE='23514';
    END IF;
    WITH flat AS (
        SELECT jsonb_array_elements_text(
            CASE jsonb_typeof(e.value)
              WHEN 'array' THEN e.value ELSE jsonb_build_array(e.value) END
        )::bigint AS label_id
          FROM jsonb_each(NEW.label_versions) e
    ), checked AS (
        SELECT f.label_id, rl.id AS admissible_id, c.id AS cluster_id
          FROM flat f
          LEFT JOIN trading.resolution_labels rl
            ON rl.id=f.label_id AND rl.state='final_admissible'
          LEFT JOIN trading.resolution_cluster_memberships cm
            ON cm.contract_spec_id=rl.contract_spec_id
          LEFT JOIN trading.resolution_clusters c
            ON c.id=cm.resolution_cluster_id AND c.split=NEW.split
    )
    SELECT count(DISTINCT label_id), count(DISTINCT admissible_id),
           count(DISTINCT cluster_id)
      INTO label_count, admissible_count, cluster_count FROM checked;
    IF label_count=0 OR admissible_count<>label_count
       OR cluster_count<>NEW.n_resolution_cluster THEN
        RAISE EXCEPTION 'v2_metric_run_label_split_mismatch' USING ERRCODE='23514';
    END IF;
    SELECT count(DISTINCT so.label_version_id) INTO observation_label_count
      FROM jsonb_array_elements_text(NEW.observation_ids) ids(value)
      JOIN trading.score_observations so ON so.id=ids.value::bigint;
    IF observation_label_count<>label_count OR EXISTS (
        SELECT 1 FROM jsonb_array_elements_text(NEW.observation_ids) ids(value)
        JOIN trading.score_observations so ON so.id=ids.value::bigint
         WHERE so.label_version_id NOT IN (
             SELECT jsonb_array_elements_text(
                 CASE jsonb_typeof(e.value) WHEN 'array' THEN e.value
                      ELSE jsonb_build_array(e.value) END
             )::bigint FROM jsonb_each(NEW.label_versions) e
         )
    ) THEN
        RAISE EXCEPTION 'v2_metric_run_label_set_mismatch' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER trg_metric_runs_evidence "
        "AFTER INSERT OR UPDATE ON trading.metric_runs "
        "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
        "EXECUTE FUNCTION trading.v2_validate_metric_run_evidence()"
    )
    # metric_runs lifecycle guard：RUNNING→COMPLETED|FAILED|INVALIDATED；terminal 禁改。
    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_metric_run() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE terminal text[] := ARRAY['COMPLETED','FAILED','INVALIDATED'];
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_metric_run_immutable' USING ERRCODE='55000';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'RUNNING' OR NEW.completed_at IS NOT NULL THEN
            RAISE EXCEPTION 'v2_metric_run_initial_state_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF OLD.run_key IS DISTINCT FROM NEW.run_key
       OR OLD.cohort_query_hash IS DISTINCT FROM NEW.cohort_query_hash
       OR OLD.strategy_version_id IS DISTINCT FROM NEW.strategy_version_id
       OR OLD.release_manifest_id IS DISTINCT FROM NEW.release_manifest_id
       OR OLD.cohort_id IS DISTINCT FROM NEW.cohort_id
       OR OLD.observation_ids IS DISTINCT FROM NEW.observation_ids
       OR OLD.observation_set_hash IS DISTINCT FROM NEW.observation_set_hash
       OR OLD.label_versions IS DISTINCT FROM NEW.label_versions
       OR OLD.split IS DISTINCT FROM NEW.split
       OR OLD.time_blocks IS DISTINCT FROM NEW.time_blocks
       OR OLD.code_hash IS DISTINCT FROM NEW.code_hash
       OR OLD.config_hash IS DISTINCT FROM NEW.config_hash
       OR OLD.seed IS DISTINCT FROM NEW.seed
       OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
        RAISE EXCEPTION 'v2_metric_run_identity_immutable' USING ERRCODE='55000';
    END IF;
    IF OLD.status = ANY(terminal) AND NEW.status IS DISTINCT FROM OLD.status THEN
        RAISE EXCEPTION 'v2_metric_run_terminal_immutable' USING ERRCODE='55000';
    END IF;
    IF OLD.status = 'RUNNING' AND NEW.status IN ('COMPLETED','FAILED','INVALIDATED') THEN
        IF NEW.status = 'COMPLETED' AND NEW.completed_at IS NULL THEN
            RAISE EXCEPTION 'v2_metric_run_completed_requires_timestamp' USING ERRCODE='23514';
        END IF;
        IF NEW.status <> 'COMPLETED' AND NEW.completed_at IS NOT NULL THEN
            RAISE EXCEPTION 'v2_metric_run_noncompleted_no_timestamp' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'v2_metric_run_immutable' USING ERRCODE='55000';
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_metric_runs_lifecycle "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.metric_runs "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_metric_run()"
    )
    # gate_decisions：升级 guard（G8 target），并加 G8 deferred 校验。
    op.execute("DROP TRIGGER IF EXISTS trg_gate_decisions_semantics ON trading.gate_decisions")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_gate_decision()")
    op.execute(_gate_guard_g8_fn())
    op.execute(
        "CREATE TRIGGER trg_gate_decisions_semantics BEFORE INSERT ON trading.gate_decisions "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_gate_decision()"
    )
    op.execute(
        r"""
CREATE FUNCTION trading.v2_validate_gate_g8() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    IF NEW.gate = 'G8' AND NEW.target_kind = 'metric_run' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.metric_runs mr
            JOIN trading.policy_freezes pf
              ON pf.policy_content_hash=NEW.policy_hash
             AND pf.release_manifest_id=NEW.version_manifest_id
             WHERE mr.id = NEW.target_id
               AND mr.status = 'COMPLETED'
               AND mr.release_manifest_id = NEW.version_manifest_id
               AND mr.completed_at <= NEW.committed_at
               AND (NEW.result <> 'PASS' OR (
                    mr.split='forward_holdout'
                    AND COALESCE((mr.results->'portfolio'->>'not_evaluable')::boolean, true)=false
               ))
        ) THEN
            RAISE EXCEPTION 'v2_gate_g8_target_invalid' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER trg_gate_decisions_g8 "
        "AFTER INSERT OR UPDATE ON trading.gate_decisions "
        "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
        "EXECUTE FUNCTION trading.v2_validate_gate_g8()"
    )
    op.execute(
        r"""
CREATE FUNCTION trading.v2_validate_promotion_decision() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    IF NEW.status <> 'APPROVED' THEN
        RETURN NEW;
    END IF;
    IF NEW.promotion_type='capital' THEN
        RETURN NEW; -- table CHECK is the authoritative WP-04 capital veto
    END IF;
    IF NEW.promotion_type <> 'strategy'
       OR NEW.future_effective_at <= NEW.created_at
       OR NOT EXISTS (
           SELECT 1 FROM trading.metric_runs mr
           JOIN trading.gate_decisions gd
             ON gd.gate='G8' AND gd.target_kind='metric_run'
            AND gd.target_id=mr.id AND gd.result='PASS'
            AND gd.version_manifest_id=mr.release_manifest_id
           JOIN trading.experiments e
             ON e.status='COMPLETED'
            AND e.champion_input_manifest_hash=NEW.from_ref
            AND e.challenger_input_manifest_hash=NEW.to_ref
            AND e.seed=mr.seed
           JOIN trading.experiment_variants champion
             ON champion.experiment_id=e.id AND champion.variant_type='champion'
            AND champion.input_manifest_hash=NEW.from_ref
           JOIN trading.experiment_variants challenger
             ON challenger.experiment_id=e.id AND challenger.variant_type='challenger'
            AND challenger.input_manifest_hash=NEW.to_ref
            AND challenger.strategy_version_id=mr.strategy_version_id
            AND challenger.release_manifest_id=mr.release_manifest_id
           JOIN trading.challenger_variants cv
             ON cv.experiment_id=e.id AND cv.variant_key=challenger.variant_key
            AND cv.status='ACTIVE'
            WHERE mr.id=NEW.metric_run_id AND mr.status='COMPLETED'
              AND mr.split='forward_holdout'
              AND mr.artifact_hash=NEW.evidence_manifest_hash
              AND (SELECT count(*) FROM jsonb_object_keys(cv.changed_fields))=1
              AND cv.changed_fields ? e.unique_change_field
              AND NOT EXISTS (
                  SELECT 1 FROM jsonb_each_text(mr.time_blocks) tb
                   WHERE tb.value !~ '^\d{4}-\d{2}-\d{2}$'
                      OR tb.value < e.time_block_start::date::text
                      OR tb.value > e.time_block_end::date::text
              )
              AND (NOT (e.sample_policy ? 'split')
                   OR e.sample_policy->>'split'=mr.split)
              AND (NOT (e.sample_policy ? 'min_n_eff') OR (
                   (e.sample_policy->>'min_n_eff') ~ '^[0-9]+(?:\.[0-9]+)?$'
                   AND mr.n_eff >= (e.sample_policy->>'min_n_eff')::numeric))
              AND (NOT (e.stopping_rule ? 'min_n_eff') OR (
                   (e.stopping_rule->>'min_n_eff') ~ '^[0-9]+(?:\.[0-9]+)?$'
                   AND mr.n_eff >= (e.stopping_rule->>'min_n_eff')::numeric))
       ) THEN
        RAISE EXCEPTION 'v2_promotion_evidence_invalid' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_promotion_decisions_validate "
        "BEFORE INSERT ON trading.promotion_decisions FOR EACH ROW "
        "EXECUTE FUNCTION trading.v2_validate_promotion_decision()"
    )


def _drop_guards() -> None:
    op.execute(
        "DROP TRIGGER IF EXISTS trg_challenger_variants_lifecycle "
        "ON trading.challenger_variants"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_challenger_variant_lifecycle()")
    op.execute("DROP TRIGGER IF EXISTS trg_experiments_lifecycle ON trading.experiments")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_experiment_lifecycle()")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_promotion_decisions_validate "
        "ON trading.promotion_decisions"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_validate_promotion_decision()")
    op.execute("DROP TRIGGER IF EXISTS trg_gate_decisions_g8 ON trading.gate_decisions")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_validate_gate_g8()")
    op.execute("DROP TRIGGER IF EXISTS trg_gate_decisions_semantics ON trading.gate_decisions")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_gate_decision()")
    op.execute(_gate_guard_0031_fn())
    op.execute(
        "CREATE TRIGGER trg_gate_decisions_semantics BEFORE INSERT ON trading.gate_decisions "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_gate_decision()"
    )
    op.execute("DROP TRIGGER IF EXISTS trg_metric_runs_evidence ON trading.metric_runs")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_validate_metric_run_evidence()")
    op.execute("DROP TRIGGER IF EXISTS trg_metric_runs_lifecycle ON trading.metric_runs")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_metric_run()")
    op.execute("DROP TRIGGER IF EXISTS trg_score_observations_label ON trading.score_observations")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_check_score_observation_label()")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_score_target_memberships_weight "
        "ON trading.score_target_memberships"
    )
    op.execute("DROP TRIGGER IF EXISTS trg_score_targets_complete ON trading.score_targets")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_check_target_membership()")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_resolution_cluster_memberships_outcome "
        "ON trading.resolution_cluster_memberships"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS trg_resolution_labels_cluster_outcome "
        "ON trading.resolution_labels"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_check_cluster_outcome_unknown()")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_resolution_labels_current ON trading.resolution_labels"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_check_label_revision()")
    op.execute("DROP TRIGGER IF EXISTS trg_resolution_clusters_lifecycle ON trading.resolution_clusters")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_resolution_cluster()")
    op.execute("DROP TRIGGER IF EXISTS trg_resolution_labels_payload ON trading.resolution_labels")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_validate_label_payload()")
    for table in reversed(_LEARNING_TABLES):
        if table.append_only:
            op.execute(
                f"DROP TRIGGER IF EXISTS trg_{table.name}_immutable "
                f"ON {TRADING_SCHEMA}.{table.name}"
            )


def upgrade() -> None:
    for table in _LEARNING_TABLES:
        op.execute(table.create_sql)
        for statement in table.index_sql:
            op.execute(statement)
    _reinforce_gate_g8()
    _create_guards()


def downgrade() -> None:
    _assert_downgrade_safe()
    _drop_guards()
    _unreinforce_gate_g8()
    for table in reversed(_LEARNING_TABLES):
        op.execute(f"DROP TABLE {TRADING_SCHEMA}.{table.name}")
