"""chain settlement registry operations observations

Revision ID: b1000052
Revises: b1000051
Create Date: 2026-08-11 21:00:00

v2_0052 —— WP-06 Checkpoint B：Polygon/Relayer/settlement 数据层。

- ``upgrade``：
  - 新建且只新建 4 张 chain-settlement 表：contract_registry / chain_operations /
    chain_operation_state_history / settlement_observations。
  - 只对既有 executions / ledger_transactions 增加最小可空 lineage 列
    ``chain_operation_id``（不得创建平行账户/Vault/账本/label/投影表）。
  - guard：
    - registry 只 INSERT（append-only）；同 chain+kind 只允许一个 active；发布前
      completeness trigger（proxy kind 合法、resolved code 全长、beacon 字段齐备）。
    - chain_operations 绑定列不可变；状态机 CAS 由 history 触发推进（``FOR UPDATE`` +
      fence 校验 + terminal 拒绝 + finality evidence 必须齐备才 FINALIZED）；直接 UPDATE
      状态也必须通过同一转移表（无 GUC 绕过）。
    - chain_operation_state_history append-only，aggregate sequence 唯一；FINALIZED
      时同一触发内置 ``economic_effect_applied=true``（只允许 FINALIZED 记账）。
    - settlement_observations append-only；``COMPLETE`` 五元组 exact set 由 deferred
      constraint trigger 在提交时核验（缺失 → ``v2_settlement_observation_complete_set_missing``）。
    - 同 account+wallet+condition 同时最多一个 active REDEEM（partial unique）。
  - 状态机覆盖 ``PREPARED→SUBMITTING→UNKNOWN|RELAYER_NEW|EXECUTED|MINED|RELAYER_CONFIRMED→
    MINED_PROVISIONAL→FINALIZED`` 及 ``INVALID|FAILED|REORGED|SETTLEMENT_CONFLICT|REVERSED``；
    非法倒退、terminal mutation、跳过 finality 全部拒绝。
- ``downgrade``：fail-closed preflight（未知 trading 对象 RAISE
  ``v2_wp06_chain_settlement_unknown_object``，ERRCODE 55000，含动态分区子表白名单豁免；
  非 fixture registry / 任何 chain fact / UNKNOWN 或 active operation 任一存在整次拒绝），
  drop guards，移除 lineage 列，逆序 DROP 4 表。

fixed literal DDL；不 import live ORM 生成 DDL；无密钥/signature 明文。
"""
from dataclasses import dataclass
from typing import Sequence, Union

from alembic import op

TRADING_SCHEMA = "trading"

# revision identifiers, used by Alembic.
revision: str = "b1000052"
down_revision: Union[str, Sequence[str], None] = "b1000051"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_OP_STATUS = (
    "'PREPARED','SUBMITTING','UNKNOWN','RELAYER_NEW','EXECUTED','MINED',"
    "'RELAYER_CONFIRMED','MINED_PROVISIONAL','FINALIZED',"
    "'INVALID','FAILED','REORGED','SETTLEMENT_CONFLICT','REVERSED'"
)
_ACTIVE_OP_STATUS = (
    "'PREPARED','SUBMITTING','UNKNOWN','RELAYER_NEW','EXECUTED','MINED',"
    "'RELAYER_CONFIRMED','MINED_PROVISIONAL','REORGED'"
)
_OP_TYPE = "'SPLIT','MERGE','REDEEM'"
_REGISTRY_KIND = "'pusd','ctf','deposit_wallet','ctf_adapter_standard','neg_risk_adapter'"
_PROXY_KIND = "'none','eip1967','beacon'"
_SOURCE_KIND = (
    "'gamma_clob_closed','ctf_payout','data_api_redeemable','clob_winner_5050','label_audit'"
)
_REGISTRY_STATUS = "'ACTIVE','SUPERSEDED'"
_OBSERVATION_STATUS = "'PENDING','COMPLETE','CONFLICT'"

# 冻结 fixture registry 的 5 条 entry content_hash（downgrade 非 fixture registry 校验）。
_FIXTURE_REGISTRY_HASHES = (
    "05b16a969afb53ba80bb7fb179f940e3a0945e2bd61076bc5cdd1d461364b1ee",
    "f25d24c2df397567350d284cb29352b4c6d80aad5b2c1d27e96f0218f87f62d1",
    "741c1e6bd40254f51cd9265629c4e74195976b2fe2119656d9d3c278104c3c4e",
    "5cb33f788431d4ca478a318c97c516c5b27350da25de4b4df2abd80087d12c4a",
    "e8c8d66d337340814f5fa3046caf354100457c021d7718e21cd7b58a56b9886d",
)


@dataclass(frozen=True)
class _FrozenTableSpec:
    name: str
    create_sql: str
    index_sql: tuple[str, ...] = ()
    append_only: bool = False


_NEW_TABLES = (
    _FrozenTableSpec(
        name="contract_registry",
        create_sql=(
            "\nCREATE TABLE trading.contract_registry (\n"
            "\tregistry_version TEXT COLLATE \"C\" NOT NULL, \n"
            "\tkind VARCHAR(64) NOT NULL, \n"
            "\tversion_no INTEGER NOT NULL, \n"
            "\tchain_id BIGINT NOT NULL, \n"
            "\taddress TEXT COLLATE \"C\" NOT NULL, \n"
            "\tproxy_kind VARCHAR(16) NOT NULL, \n"
            "\truntime_keccak VARCHAR(66) COLLATE \"C\" NOT NULL, \n"
            "\tresolved_implementation_or_beacon TEXT COLLATE \"C\", \n"
            "\tresolved_code_keccak VARCHAR(66) COLLATE \"C\" NOT NULL, \n"
            "\tsnapshot_block_number BIGINT NOT NULL, \n"
            "\tsnapshot_block_hash VARCHAR(66) COLLATE \"C\" NOT NULL, \n"
            "\tsource_url TEXT NOT NULL, \n"
            "\tretrieved_at TIMESTAMP WITH TIME ZONE NOT NULL, \n"
            "\tcontent_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\textra JSONB, \n"
            "\tstatus VARCHAR(16) DEFAULT 'ACTIVE' NOT NULL, \n"
            "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n"
            "\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tPRIMARY KEY (id), \n"
            "\tCONSTRAINT uq_contract_registry_chain_kind_version "
            "UNIQUE (chain_id, kind, version_no), \n"
            "\tCONSTRAINT uq_contract_registry_chain_kind_addr "
            "UNIQUE (chain_id, kind, address), \n"
            "\tCONSTRAINT uq_contract_registry_runtime_keccak UNIQUE (runtime_keccak), \n"
            "\tCONSTRAINT ck_contract_registry_kind_known "
            "CHECK (kind IN (" + _REGISTRY_KIND + ")), \n"
            "\tCONSTRAINT ck_contract_registry_proxy_kind_known "
            "CHECK (proxy_kind IN (" + _PROXY_KIND + ")), \n"
            "\tCONSTRAINT ck_contract_registry_status_known "
            "CHECK (status IN (" + _REGISTRY_STATUS + ")), \n"
            "\tCONSTRAINT ck_contract_registry_version_positive CHECK (version_no > 0), \n"
            "\tCONSTRAINT ck_contract_registry_snapshot_positive "
            "CHECK (snapshot_block_number > 0), \n"
            "\tCONSTRAINT ck_contract_registry_chain_id CHECK (chain_id = 137), \n"
            "\tCONSTRAINT ck_contract_registry_address_hex "
            "CHECK (address ~ '^0x[0-9a-fA-F]{40}$'), \n"
            "\tCONSTRAINT ck_contract_registry_resolved_address_hex "
            "CHECK (resolved_implementation_or_beacon IS NULL "
            "OR resolved_implementation_or_beacon ~ '^0x[0-9a-fA-F]{40}$'), \n"
            "\tCONSTRAINT ck_contract_registry_runtime_keccak_hex "
            "CHECK (runtime_keccak ~ '^0x[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_contract_registry_resolved_code_hex "
            "CHECK (resolved_code_keccak ~ '^0x[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_contract_registry_block_hash_hex "
            "CHECK (snapshot_block_hash ~ '^0x[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_contract_registry_content_hash_hex "
            "CHECK (content_hash ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_contract_registry_resolved_pair CHECK ("
            "(proxy_kind = 'none') = (resolved_implementation_or_beacon IS NULL)), \n"
            "\tCONSTRAINT ck_contract_registry_extra_object "
            "CHECK (extra IS NULL OR jsonb_typeof(extra) = 'object')\n"
            ")\n\n"
        ),
        index_sql=(
            "CREATE UNIQUE INDEX uq_contract_registry_active_per_chain_kind "
            "ON trading.contract_registry (chain_id, kind) WHERE status = 'ACTIVE'",
            "CREATE INDEX ix_contract_registry_kind "
            "ON trading.contract_registry (kind)",
        ),
        append_only=True,
    ),
    _FrozenTableSpec(
        name="chain_operations",
        create_sql=(
            "\nCREATE TABLE trading.chain_operations (\n"
            "\toperation_key TEXT COLLATE \"C\" NOT NULL, \n"
            "\tidempotency_key VARCHAR(255) NOT NULL, \n"
            "\teconomic_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\toperation_type VARCHAR(16) NOT NULL, \n"
            "\tchain_id BIGINT NOT NULL, \n"
            "\taccount_id BIGINT NOT NULL, \n"
            "\twallet_address TEXT COLLATE \"C\" NOT NULL, \n"
            "\tcondition_id VARCHAR(66) COLLATE \"C\" NOT NULL, \n"
            "\tmarket_id BIGINT, \n"
            "\tregistry_version_id BIGINT NOT NULL, \n"
            "\ttarget_address TEXT COLLATE \"C\" NOT NULL, \n"
            "\tpermission_ref TEXT COLLATE \"C\" NOT NULL, \n"
            "\trelease_manifest_id BIGINT NOT NULL, \n"
            "\tcapital_permission_manifest_id BIGINT NOT NULL, \n"
            "\tfencing_token BIGINT NOT NULL, \n"
            "\tamount_base_units NUMERIC(38, 0) NOT NULL, \n"
            "\tcalldata TEXT COLLATE \"C\" NOT NULL, \n"
            "\tcalldata_keccak VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tbody_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tcall_set_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\texpected_operation_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tpreflight_hash1 VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tpreflight_hash2 VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tstatus VARCHAR(32) DEFAULT 'PREPARED' NOT NULL, \n"
            "\trelayer_nonce TEXT COLLATE \"C\", \n"
            "\tdeadline TIMESTAMP WITH TIME ZONE, \n"
            "\ttransaction_id TEXT COLLATE \"C\", \n"
            "\ttransaction_hash TEXT COLLATE \"C\", \n"
            "\treceipt_block_number BIGINT, \n"
            "\treceipt_block_hash VARCHAR(66) COLLATE \"C\", \n"
            "\tfinalized_block_number BIGINT, \n"
            "\tpre_balance JSONB, \n"
            "\tpost_balance JSONB, \n"
            "\teconomic_effect_applied BOOLEAN DEFAULT false NOT NULL, \n"
            "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n"
            "\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tPRIMARY KEY (id), \n"
            "\tCONSTRAINT uq_chain_operations_key UNIQUE (operation_key), \n"
            "\tCONSTRAINT uq_chain_operations_idempotency UNIQUE (idempotency_key), \n"
            "\tCONSTRAINT uq_chain_operations_economic_hash UNIQUE (economic_hash), \n"
            "\tCONSTRAINT uq_chain_operations_expected_hash "
            "UNIQUE (expected_operation_hash), \n"
            "\tCONSTRAINT ck_chain_operations_type_known "
            "CHECK (operation_type IN (" + _OP_TYPE + ")), \n"
            "\tCONSTRAINT ck_chain_operations_status_known "
            "CHECK (status IN (" + _OP_STATUS + ")), \n"
            "\tCONSTRAINT ck_chain_operations_chain_id CHECK (chain_id = 137), \n"
            "\tCONSTRAINT ck_chain_operations_fencing_positive CHECK (fencing_token > 0), \n"
            "\tCONSTRAINT ck_chain_operations_amount_range CHECK ("
            "(operation_type = 'REDEEM' AND amount_base_units = 0) OR "
            "(operation_type IN ('SPLIT','MERGE') AND amount_base_units > 0)), \n"
            "\tCONSTRAINT ck_chain_operations_hashes_hex CHECK ("
            "economic_hash ~ '^[0-9a-f]{64}$' AND calldata_keccak ~ '^[0-9a-f]{64}$' "
            "AND body_hash ~ '^[0-9a-f]{64}$' AND call_set_hash ~ '^[0-9a-f]{64}$' "
            "AND expected_operation_hash ~ '^[0-9a-f]{64}$' "
            "AND preflight_hash1 ~ '^[0-9a-f]{64}$' "
            "AND preflight_hash2 ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_chain_operations_wallet_hex "
            "CHECK (wallet_address ~ '^0x[0-9a-fA-F]{40}$'), \n"
            "\tCONSTRAINT ck_chain_operations_target_hex "
            "CHECK (target_address ~ '^0x[0-9a-fA-F]{40}$'), \n"
            "\tCONSTRAINT ck_chain_operations_condition_hex "
            "CHECK (condition_id ~ '^0x[0-9a-fA-F]{64}$'), \n"
            "\tCONSTRAINT ck_chain_operations_receipt_hash_hex "
            "CHECK (receipt_block_hash IS NULL OR receipt_block_hash ~ '^0x[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_chain_operations_balances_object CHECK ("
            "(pre_balance IS NULL OR jsonb_typeof(pre_balance) = 'object') AND "
            "(post_balance IS NULL OR jsonb_typeof(post_balance) = 'object')), \n"
            "\tCONSTRAINT ck_chain_operations_economic_once CHECK ("
            "NOT economic_effect_applied OR status IN "
            "('FINALIZED','SETTLEMENT_CONFLICT','REVERSED')), \n"
            "\tCONSTRAINT ck_chain_operations_finalized_evidence CHECK ("
            "status <> 'FINALIZED' OR ("
            "transaction_id IS NOT NULL AND transaction_hash IS NOT NULL AND "
            "receipt_block_number IS NOT NULL AND receipt_block_hash IS NOT NULL AND "
            "finalized_block_number IS NOT NULL AND "
            "pre_balance IS NOT NULL AND post_balance IS NOT NULL AND "
            "economic_effect_applied)), \n"
            "\tCONSTRAINT ck_chain_operations_mining_evidence CHECK ("
            "status NOT IN ('MINED_PROVISIONAL','FINALIZED') OR "
            "(transaction_hash IS NOT NULL AND receipt_block_number IS NOT NULL "
            "AND receipt_block_hash IS NOT NULL)), \n"
            "\tCONSTRAINT ck_chain_operations_relayer_evidence CHECK ("
            "status NOT IN ('RELAYER_CONFIRMED','MINED','MINED_PROVISIONAL','FINALIZED') "
            "OR (transaction_id IS NOT NULL AND transaction_hash IS NOT NULL)), \n"
            "\tCONSTRAINT fk_chain_operations_account "
            "FOREIGN KEY(account_id) REFERENCES trading.pm_accounts (id), \n"
            "\tCONSTRAINT fk_chain_operations_registry "
            "FOREIGN KEY(registry_version_id) REFERENCES trading.contract_registry (id), \n"
            "\tCONSTRAINT fk_chain_operations_release "
            "FOREIGN KEY(release_manifest_id) REFERENCES trading.release_manifests (id), \n"
            "\tCONSTRAINT fk_chain_operations_permission "
            "FOREIGN KEY(capital_permission_manifest_id) "
            "REFERENCES trading.capital_permission_manifests (id), \n"
            "\tCONSTRAINT fk_chain_operations_market "
            "FOREIGN KEY(market_id) REFERENCES trading.pm_markets (id)\n"
            ")\n\n"
        ),
        index_sql=(
            "CREATE UNIQUE INDEX uq_chain_operations_active_redeem "
            "ON trading.chain_operations (account_id, wallet_address, condition_id) "
            "WHERE operation_type = 'REDEEM' AND status IN (" + _ACTIVE_OP_STATUS + ")",
            "CREATE INDEX ix_chain_operations_status "
            "ON trading.chain_operations (status)",
            "CREATE INDEX ix_chain_operations_account "
            "ON trading.chain_operations (account_id)",
            "CREATE INDEX ix_chain_operations_condition "
            "ON trading.chain_operations (condition_id)",
        ),
        append_only=False,
    ),
    _FrozenTableSpec(
        name="chain_operation_state_history",
        create_sql=(
            "\nCREATE TABLE trading.chain_operation_state_history (\n"
            "\toperation_id BIGINT NOT NULL, \n"
            "\tsequence_no INTEGER NOT NULL, \n"
            "\ttransition_from VARCHAR(32) NOT NULL, \n"
            "\ttransition_to VARCHAR(32) NOT NULL, \n"
            "\tevent_type VARCHAR(32) NOT NULL, \n"
            "\tevent_payload JSONB NOT NULL, \n"
            "\tevent_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tfence_token BIGINT NOT NULL, \n"
            "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n"
            "\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tPRIMARY KEY (id), \n"
            "\tCONSTRAINT uq_chain_op_state_history_op_seq "
            "UNIQUE (operation_id, sequence_no), \n"
            "\tCONSTRAINT uq_chain_op_state_history_hash UNIQUE (event_hash), \n"
            "\tCONSTRAINT ck_chain_op_state_history_type_known "
            "CHECK (event_type IN (" + _OP_STATUS + ")), \n"
            "\tCONSTRAINT ck_chain_op_state_history_type_matches "
            "CHECK (event_type = transition_to), \n"
            "\tCONSTRAINT ck_chain_op_state_history_fence_positive "
            "CHECK (fence_token > 0), \n"
            "\tCONSTRAINT ck_chain_op_state_history_seq_nonneg CHECK (sequence_no >= 0), \n"
            "\tCONSTRAINT ck_chain_op_state_history_payload_object "
            "CHECK (jsonb_typeof(event_payload) = 'object'), \n"
            "\tCONSTRAINT ck_chain_op_state_history_event_hash_hex "
            "CHECK (event_hash ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_chain_op_state_history_transition_exact CHECK ("
            "(transition_from = 'PREPARED' AND transition_to = 'SUBMITTING') OR "
            "(transition_from = 'SUBMITTING' AND transition_to IN "
            "('UNKNOWN','RELAYER_NEW','EXECUTED','INVALID','FAILED')) OR "
            "(transition_from = 'UNKNOWN' AND transition_to IN "
            "('RELAYER_NEW','EXECUTED','REORGED','SETTLEMENT_CONFLICT','REVERSED')) OR "
            "(transition_from = 'RELAYER_NEW' AND transition_to IN "
            "('EXECUTED','MINED','INVALID','FAILED','UNKNOWN','REORGED')) OR "
            "(transition_from = 'EXECUTED' AND transition_to IN "
            "('MINED','INVALID','FAILED','UNKNOWN','REORGED')) OR "
            "(transition_from = 'MINED' AND transition_to IN "
            "('RELAYER_CONFIRMED','MINED_PROVISIONAL','INVALID','FAILED','UNKNOWN','REORGED')) OR "
            "(transition_from = 'RELAYER_CONFIRMED' AND transition_to IN "
            "('MINED_PROVISIONAL','FINALIZED','UNKNOWN','REORGED')) OR "
            "(transition_from = 'MINED_PROVISIONAL' AND transition_to IN "
            "('FINALIZED','REORGED','UNKNOWN')) OR "
            "(transition_from = 'FINALIZED' AND transition_to IN "
            "('SETTLEMENT_CONFLICT','REVERSED')) OR "
            "(transition_from = 'REVERSED' AND transition_to = 'SETTLEMENT_CONFLICT')\n"
            "),\n"
            "\tCONSTRAINT fk_chain_op_state_history_operation "
            "FOREIGN KEY(operation_id) REFERENCES trading.chain_operations (id)\n"
            ")\n\n"
        ),
        index_sql=(
            "CREATE INDEX ix_chain_op_state_history_operation "
            "ON trading.chain_operation_state_history (operation_id)",
        ),
        append_only=True,
    ),
    _FrozenTableSpec(
        name="settlement_observations",
        create_sql=(
            "\nCREATE TABLE trading.settlement_observations (\n"
            "\tobservation_key TEXT COLLATE \"C\" NOT NULL, \n"
            "\tsource_kind VARCHAR(32) NOT NULL, \n"
            "\tcondition_id VARCHAR(66) COLLATE \"C\" NOT NULL, \n"
            "\tmarket_id BIGINT, \n"
            "\ttoken_set JSONB NOT NULL, \n"
            "\toutcome_index VARCHAR(32), \n"
            "\tnumerator TEXT COLLATE \"C\", \n"
            "\tdenominator TEXT COLLATE \"C\", \n"
            "\twinner VARCHAR(32), \n"
            "\tis_50_50_outcome BOOLEAN, \n"
            "\tredeemable BOOLEAN, \n"
            "\tlabel_audit_version VARCHAR(64) COLLATE \"C\", \n"
            "\tas_of TIMESTAMP WITH TIME ZONE NOT NULL, \n"
            "\treceived_at TIMESTAMP WITH TIME ZONE NOT NULL, \n"
            "\traw_artifact_ref VARCHAR(64) COLLATE \"C\", \n"
            "\traw_artifact_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tcontent_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tpayload JSONB, \n"
            "\tstatus VARCHAR(16) DEFAULT 'PENDING' NOT NULL, \n"
            "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n"
            "\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tPRIMARY KEY (id), \n"
            "\tCONSTRAINT uq_settlement_observations_key UNIQUE (observation_key), \n"
            "\tCONSTRAINT uq_settlement_observations_hash UNIQUE (content_hash), \n"
            "\tCONSTRAINT ck_settlement_observations_source_known "
            "CHECK (source_kind IN (" + _SOURCE_KIND + ")), \n"
            "\tCONSTRAINT ck_settlement_observations_status_known "
            "CHECK (status IN (" + _OBSERVATION_STATUS + ")), \n"
            "\tCONSTRAINT ck_settlement_observations_condition_hex "
            "CHECK (condition_id ~ '^0x[0-9a-fA-F]{64}$'), \n"
            "\tCONSTRAINT ck_settlement_observations_artifact_hash_hex "
            "CHECK (raw_artifact_hash ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_settlement_observations_content_hash_hex "
            "CHECK (content_hash ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_settlement_observations_token_set "
            "CHECK (jsonb_typeof(token_set) = 'array'), \n"
            "\tCONSTRAINT ck_settlement_observations_payout_pair CHECK ("
            "(source_kind = 'ctf_payout') = (numerator IS NOT NULL "
            "AND denominator IS NOT NULL)), \n"
            "\tCONSTRAINT ck_settlement_observations_winner_pair CHECK ("
            "(source_kind = 'clob_winner_5050') = (winner IS NOT NULL "
            "OR is_50_50_outcome IS NOT NULL)), \n"
            "\tCONSTRAINT ck_settlement_observations_redeemable_pair CHECK ("
            "(source_kind = 'data_api_redeemable') = (redeemable IS NOT NULL)), \n"
            "\tCONSTRAINT fk_settlement_observations_market "
            "FOREIGN KEY(market_id) REFERENCES trading.pm_markets (id)\n"
            ")\n\n"
        ),
        index_sql=(
            "CREATE INDEX ix_settlement_observations_condition "
            "ON trading.settlement_observations (condition_id)",
            "CREATE INDEX ix_settlement_observations_source "
            "ON trading.settlement_observations (source_kind)",
        ),
        append_only=True,
    ),
)

# b1000051 已存在的 trading 关系（0052 downgrade preflight allowlist = 0051 全量 +
# 0051 的 9 张 execution-plane 表）。
_PRE_0052_RELATIONS = (
    # b1000002 ~ b1000041 全量
    "artifact_objects", "artifact_lineage_edges", "archive_manifests",
    "retention_manifests", "runtime_config_versions", "strategy_objective_contracts",
    "strategy_versions", "execution_spec_versions", "capital_permission_manifests",
    "model_role_bindings", "release_manifests", "policy_type_scopes", "policy_freezes",
    "secret_vault_entries", "secret_vault_versions", "secret_access_events",
    "idempotency_claims", "transactional_outbox", "outbox_delivery_history",
    "job_completions", "pm_universe_frames", "pm_universe_frame_pages", "pm_events",
    "pm_markets", "pm_market_versions", "pm_tokens", "pm_token_versions",
    "pm_market_lifecycle_events", "pm_market_current", "pm_connection_epochs",
    "pm_source_event_batches", "pm_source_event_index", "pm_book_checkpoints",
    "pm_book_levels", "pm_book_current", "pm_quote_bindings", "contract_snapshots",
    "contract_specs", "payout_functions", "forecast_components", "world_schema_versions",
    "forecast_component_versions", "forecast_component_contract_specs",
    "portfolio_dependency_edges", "evaluation_cohorts", "universe_memberships",
    "screening_episodes", "audit_samples", "decision_opportunities",
    "decision_opportunity_markets", "episode_memberships", "forecast_episodes",
    "episode_contract_specs", "information_snapshots", "information_snapshot_items",
    "gate_decisions", "priors", "evidence_coverage_policies", "evidence_revisions",
    "evidence_bundles", "evidence_bundle_items", "forecast_input_manifests",
    "forecast_submissions", "payout_projections", "coherence_checks",
    "forecast_challenges", "forecast_leases", "ai_invocations", "ai_tool_calls",
    "ai_validation_results", "market_relative_decisions", "discrepancy_reviews",
    "trade_decisions", "action_candidates", "resolution_cashflows", "action_sets",
    "action_set_legs", "underwriting_plans", "economic_action_intents",
    "executions", "positions", "position_lots", "ledger_transactions",
    "ledger_postings", "operating_cost_entries",
    "resolution_labels", "resolution_clusters", "resolution_cluster_memberships",
    "score_targets", "score_target_memberships", "score_observations", "experiments",
    "experiment_variants", "challenger_variants", "metric_runs", "error_reviews",
    "ablation_runs", "promotion_decisions", "replay_runs",
    "ops_health_current", "pipeline_funnel_hourly", "account_risk_current",
    "provider_cost_daily", "latest_chain_summary",
    "pm_accounts", "pm_balance_allowance_snapshots", "account_funds_current",
    "capital_reservations", "execution_leases",
    # b1000051 execution-plane（9 张）
    "execution_authorization_envelopes", "exchange_order_attempts", "exchange_orders",
    "order_state_events", "exchange_trades", "account_reconciliations",
    "workflow_events", "external_call_attempts", "alert_events",
)


def _index_name(statement: str) -> str:
    """``CREATE [UNIQUE] INDEX <name> ON ...`` → ``<name>``。"""
    rest = statement.replace("CREATE UNIQUE INDEX ", "").replace("CREATE INDEX ", "")
    return rest.split(" ON ")[0].strip()


def _assert_downgrade_safe() -> None:
    allowed = ", ".join(
        f"'{name}'" for name in (*_PRE_0052_RELATIONS, *(t.name for t in _NEW_TABLES))
    )
    owned = ", ".join(f"'{t.name}'" for t in _NEW_TABLES)
    known_indexes = ", ".join(
        f"'{_index_name(statement)}'"
        for table in _NEW_TABLES for statement in table.index_sql
    ) or "''"
    known_triggers = ", ".join(
        f"'{name}'" for name in (
            "trg_contract_registry_immutable",
            "trg_contract_registry_publish_check",
            "trg_chain_operations_lifecycle",
            "trg_chain_operation_state_cas",
            "trg_chain_operation_state_history_immutable",
            "trg_settlement_observations_immutable",
            "trg_settlement_observations_complete_set",
        )
    )
    fixture_hashes = ", ".join(f"'{h}'" for h in _FIXTURE_REGISTRY_HASHES)
    op.execute(
        f"""
DO $v2_wp06_chain_settlement_preflight$
DECLARE unknown_objects text;
        unknown_indexes text;
        unknown_triggers text;
        bad_registry text;
        active_ops bigint;
        chain_facts bigint;
BEGIN
    -- 非 fixture registry：任一 entry 的 content_hash 不在冻结 fixture 集 → 整次拒绝
    SELECT string_agg(content_hash, ', ' ORDER BY content_hash)
      INTO bad_registry
      FROM trading.contract_registry
     WHERE content_hash NOT IN ({fixture_hashes});
    IF bad_registry IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp06_chain_settlement_non_fixture_registry:%', bad_registry
        USING ERRCODE='55000';
    END IF;
    -- UNKNOWN / active operation：恢复期与活跃链上操作必须先完成只读 reconcile
    SELECT count(*) INTO active_ops
      FROM trading.chain_operations
     WHERE status IN ({_ACTIVE_OP_STATUS});
    IF active_ops <> 0 THEN
        RAISE EXCEPTION 'v2_wp06_chain_settlement_active_operations:%', active_ops
        USING ERRCODE='55000';
    END IF;
    -- 其他 chain fact（state history / observations / 任何 operation 行）不得被静默丢弃
    SELECT (SELECT count(*) FROM trading.chain_operations)
         + (SELECT count(*) FROM trading.chain_operation_state_history)
         + (SELECT count(*) FROM trading.settlement_observations)
      INTO chain_facts;
    IF chain_facts <> 0 THEN
        RAISE EXCEPTION 'v2_wp06_chain_settlement_chain_facts_present:%', chain_facts
        USING ERRCODE='55000';
    END IF;
    SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
      INTO unknown_objects
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'trading'
       AND c.relkind IN ('r','p','v','m','f')
       AND c.relname NOT IN ({allowed})
       AND NOT EXISTS (
           SELECT 1 FROM pg_inherits i
           JOIN pg_class p ON p.oid = i.inhparent
           JOIN pg_namespace pn ON pn.oid = p.relnamespace
           WHERE i.inhrelid = c.oid AND pn.nspname = 'trading'
             AND ((p.relname = 'outbox_delivery_history'
                   AND c.relname ~ '^outbox_delivery_history_[0-9]{{6}}$')
               OR (p.relname IN ('pm_source_event_batches','pm_source_event_index',
                                  'pm_book_checkpoints','pm_book_levels')
                   AND c.relname ~ ('^' || p.relname || '_[0-9]{{8}}$'))
               OR (p.relname IN ('ai_invocations','ai_tool_calls','ai_validation_results')
                   AND c.relname ~ ('^' || p.relname || '_[0-9]{{6}}$')))
       );
    IF unknown_objects IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp06_chain_settlement_unknown_object:%', unknown_objects
        USING ERRCODE='55000';
    END IF;
    SELECT string_agg(idx.relname, ', ' ORDER BY idx.relname)
      INTO unknown_indexes
      FROM pg_index i
      JOIN pg_class idx ON idx.oid=i.indexrelid
      JOIN pg_class tbl ON tbl.oid=i.indrelid
      JOIN pg_namespace n ON n.oid=tbl.relnamespace
     WHERE n.nspname='trading' AND tbl.relname IN ({owned})
       AND NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conindid=idx.oid)
       AND idx.relname NOT IN ({known_indexes});
    IF unknown_indexes IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp06_chain_settlement_unknown_index:%', unknown_indexes
        USING ERRCODE='55000';
    END IF;
    SELECT string_agg(t.tgname, ', ' ORDER BY t.tgname)
      INTO unknown_triggers
      FROM pg_trigger t
      JOIN pg_class tbl ON tbl.oid=t.tgrelid
      JOIN pg_namespace n ON n.oid=tbl.relnamespace
     WHERE n.nspname='trading' AND tbl.relname IN ({owned})
       AND NOT t.tgisinternal AND t.tgname NOT IN ({known_triggers});
    IF unknown_triggers IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp06_chain_settlement_unknown_trigger:%', unknown_triggers
        USING ERRCODE='55000';
    END IF;
END $v2_wp06_chain_settlement_preflight$
"""
    )


def _add_lineage() -> None:
    """只对既有 executions / ledger_transactions 增加最小可空 lineage 列。"""
    op.execute(
        "ALTER TABLE trading.executions ADD COLUMN chain_operation_id BIGINT"
    )
    op.execute(
        "ALTER TABLE trading.executions "
        "ADD CONSTRAINT fk_executions_chain_operation "
        "FOREIGN KEY(chain_operation_id) REFERENCES trading.chain_operations (id)"
    )
    op.execute(
        "ALTER TABLE trading.ledger_transactions ADD COLUMN chain_operation_id BIGINT"
    )
    op.execute(
        "ALTER TABLE trading.ledger_transactions "
        "ADD CONSTRAINT fk_ledger_transactions_chain_operation "
        "FOREIGN KEY(chain_operation_id) REFERENCES trading.chain_operations (id)"
    )
    op.execute(
        "CREATE INDEX ix_executions_chain_operation "
        "ON trading.executions (chain_operation_id)"
    )
    op.execute(
        "CREATE INDEX ix_ledger_transactions_chain_operation "
        "ON trading.ledger_transactions (chain_operation_id)"
    )


def _drop_lineage() -> None:
    op.execute(
        "ALTER TABLE trading.executions DROP COLUMN IF EXISTS chain_operation_id"
    )
    op.execute(
        "ALTER TABLE trading.ledger_transactions DROP COLUMN IF EXISTS chain_operation_id"
    )


def _create_guards() -> None:
    op.execute(
        """
CREATE FUNCTION trading.v2_guard_contract_registry_immutable() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'UPDATE' OR TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_contract_registry_immutable' USING ERRCODE='55000';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_contract_registry_immutable
    BEFORE UPDATE OR DELETE ON trading.contract_registry
    FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_contract_registry_immutable();
"""
    )
    op.execute(
        """
CREATE FUNCTION trading.v2_guard_contract_registry_publish() RETURNS trigger AS $$
BEGIN
    IF NEW.proxy_kind NOT IN ('none','eip1967','beacon') THEN
        RAISE EXCEPTION 'v2_contract_registry_proxy_kind_unknown' USING ERRCODE='23514';
    END IF;
    IF (NEW.proxy_kind = 'none') <> (NEW.resolved_implementation_or_beacon IS NULL) THEN
        RAISE EXCEPTION 'v2_contract_registry_resolved_pair_invalid' USING ERRCODE='23514';
    END IF;
    IF NEW.resolved_code_keccak IS NULL OR NEW.runtime_keccak IS NULL THEN
        RAISE EXCEPTION 'v2_contract_registry_code_missing' USING ERRCODE='23502';
    END IF;
    IF NEW.proxy_kind = 'beacon' THEN
        IF NEW.extra IS NULL
           OR NEW.extra->>'beacon_address' IS NULL
           OR NEW.extra->>'beacon_implementation' IS NULL
           OR NEW.extra->>'beacon_runtime_keccak' IS NULL
           OR NEW.extra->>'beacon_implementation_code_keccak' IS NULL THEN
            RAISE EXCEPTION 'v2_contract_registry_beacon_incomplete' USING ERRCODE='23502';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_contract_registry_publish_check
    BEFORE INSERT ON trading.contract_registry
    FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_contract_registry_publish();
"""
    )
    op.execute(
        """
CREATE FUNCTION trading.v2_guard_chain_operation_update() RETURNS trigger AS $$
BEGIN
    -- 绑定列不可变：account/wallet/condition/market/registry/permission/release/fence/
    -- call-set/body/preflight/calldata/economic hash 全部冻结。
    IF OLD.operation_key <> NEW.operation_key
       OR OLD.idempotency_key <> NEW.idempotency_key
       OR OLD.economic_hash <> NEW.economic_hash
       OR OLD.operation_type <> NEW.operation_type
       OR OLD.chain_id <> NEW.chain_id
       OR OLD.account_id <> NEW.account_id
       OR OLD.wallet_address <> NEW.wallet_address
       OR OLD.condition_id <> NEW.condition_id
       OR OLD.market_id IS DISTINCT FROM NEW.market_id
       OR OLD.registry_version_id <> NEW.registry_version_id
       OR OLD.target_address <> NEW.target_address
       OR OLD.permission_ref <> NEW.permission_ref
       OR OLD.release_manifest_id <> NEW.release_manifest_id
       OR OLD.capital_permission_manifest_id <> NEW.capital_permission_manifest_id
       OR OLD.fencing_token <> NEW.fencing_token
       OR OLD.amount_base_units <> NEW.amount_base_units
       OR OLD.calldata <> NEW.calldata
       OR OLD.calldata_keccak <> NEW.calldata_keccak
       OR OLD.body_hash <> NEW.body_hash
       OR OLD.call_set_hash <> NEW.call_set_hash
       OR OLD.expected_operation_hash <> NEW.expected_operation_hash
       OR OLD.preflight_hash1 <> NEW.preflight_hash1
       OR OLD.preflight_hash2 <> NEW.preflight_hash2 THEN
        RAISE EXCEPTION 'v2_chain_operation_binding_immutable' USING ERRCODE='55000';
    END IF;
    IF OLD.status <> NEW.status THEN
        IF NOT (
            (OLD.status = 'PREPARED' AND NEW.status = 'SUBMITTING') OR
            (OLD.status = 'SUBMITTING' AND NEW.status IN
             ('UNKNOWN','RELAYER_NEW','EXECUTED','INVALID','FAILED')) OR
            (OLD.status = 'UNKNOWN' AND NEW.status IN
             ('RELAYER_NEW','EXECUTED','REORGED','SETTLEMENT_CONFLICT','REVERSED')) OR
            (OLD.status = 'RELAYER_NEW' AND NEW.status IN
             ('EXECUTED','MINED','INVALID','FAILED','UNKNOWN','REORGED')) OR
            (OLD.status = 'EXECUTED' AND NEW.status IN
             ('MINED','INVALID','FAILED','UNKNOWN','REORGED')) OR
            (OLD.status = 'MINED' AND NEW.status IN
             ('RELAYER_CONFIRMED','MINED_PROVISIONAL','INVALID','FAILED','UNKNOWN','REORGED')) OR
            (OLD.status = 'RELAYER_CONFIRMED' AND NEW.status IN
             ('MINED_PROVISIONAL','FINALIZED','UNKNOWN','REORGED')) OR
            (OLD.status = 'MINED_PROVISIONAL' AND NEW.status IN
             ('FINALIZED','REORGED','UNKNOWN')) OR
            (OLD.status = 'FINALIZED' AND NEW.status IN ('SETTLEMENT_CONFLICT','REVERSED')) OR
            (OLD.status = 'REVERSED' AND NEW.status = 'SETTLEMENT_CONFLICT')
        ) THEN
            RAISE EXCEPTION 'v2_chain_operation_transition_invalid' USING ERRCODE='23514';
        END IF;
        IF OLD.status IN ('INVALID','FAILED','SETTLEMENT_CONFLICT','REVERSED') THEN
            RAISE EXCEPTION 'v2_chain_operation_terminal_mutation' USING ERRCODE='23514';
        END IF;
        IF OLD.status = 'FINALIZED' AND NEW.status NOT IN ('SETTLEMENT_CONFLICT','REVERSED') THEN
            RAISE EXCEPTION 'v2_chain_operation_terminal_mutation' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_chain_operations_lifecycle
    BEFORE UPDATE ON trading.chain_operations
    FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_chain_operation_update();
"""
    )
    op.execute(
        """
CREATE FUNCTION trading.v2_guard_chain_operation_state() RETURNS trigger AS $$
DECLARE cur_status VARCHAR(32);
        cur_fence BIGINT;
        applied_count bigint;
BEGIN
    IF TG_OP = 'UPDATE' OR TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_chain_operation_state_immutable' USING ERRCODE='55000';
    END IF;
    IF NEW.fence_token <= 0 THEN
        RAISE EXCEPTION 'v2_chain_operation_state_fence_nonpositive' USING ERRCODE='23514';
    END IF;
    SELECT status, fencing_token
      INTO cur_status, cur_fence
      FROM trading.chain_operations
     WHERE id = NEW.operation_id
     FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'v2_chain_operation_missing' USING ERRCODE='23503';
    END IF;
    IF NEW.transition_from <> cur_status THEN
        RAISE EXCEPTION 'v2_chain_operation_cas_mismatch expected=% actual=%',
            cur_status, NEW.transition_from USING ERRCODE='55000';
    END IF;
    IF NEW.fence_token <> cur_fence THEN
        RAISE EXCEPTION 'v2_chain_operation_fence_mismatch expected=% actual=%',
            cur_fence, NEW.fence_token USING ERRCODE='55000';
    END IF;
    IF cur_status IN ('INVALID','FAILED','SETTLEMENT_CONFLICT','REVERSED') THEN
        RAISE EXCEPTION 'v2_chain_operation_terminal_mutation' USING ERRCODE='23514';
    END IF;
    IF cur_status = 'FINALIZED' AND NEW.transition_to NOT IN ('SETTLEMENT_CONFLICT','REVERSED') THEN
        RAISE EXCEPTION 'v2_chain_operation_terminal_mutation' USING ERRCODE='23514';
    END IF;
    -- 转移合法性前置校验（与 history CHECK 同表；在 FINALIZED 证据路径前拒绝非法/跳 finality）
    IF NOT (
        (cur_status = 'PREPARED' AND NEW.transition_to = 'SUBMITTING') OR
        (cur_status = 'SUBMITTING' AND NEW.transition_to IN
         ('UNKNOWN','RELAYER_NEW','EXECUTED','INVALID','FAILED')) OR
        (cur_status = 'UNKNOWN' AND NEW.transition_to IN
         ('RELAYER_NEW','EXECUTED','REORGED','SETTLEMENT_CONFLICT','REVERSED')) OR
        (cur_status = 'RELAYER_NEW' AND NEW.transition_to IN
         ('EXECUTED','MINED','INVALID','FAILED','UNKNOWN','REORGED')) OR
        (cur_status = 'EXECUTED' AND NEW.transition_to IN
         ('MINED','INVALID','FAILED','UNKNOWN','REORGED')) OR
        (cur_status = 'MINED' AND NEW.transition_to IN
         ('RELAYER_CONFIRMED','MINED_PROVISIONAL','INVALID','FAILED','UNKNOWN','REORGED')) OR
        (cur_status = 'RELAYER_CONFIRMED' AND NEW.transition_to IN
         ('MINED_PROVISIONAL','FINALIZED','UNKNOWN','REORGED')) OR
        (cur_status = 'MINED_PROVISIONAL' AND NEW.transition_to IN
         ('FINALIZED','REORGED','UNKNOWN')) OR
        (cur_status = 'FINALIZED' AND NEW.transition_to IN ('SETTLEMENT_CONFLICT','REVERSED')) OR
        (cur_status = 'REVERSED' AND NEW.transition_to = 'SETTLEMENT_CONFLICT')
    ) THEN
        RAISE EXCEPTION 'v2_chain_operation_transition_invalid' USING ERRCODE='23514';
    END IF;
    IF NEW.transition_to = 'FINALIZED' THEN
        UPDATE trading.chain_operations
           SET status = 'FINALIZED', updated_at = now(), economic_effect_applied = true
         WHERE id = NEW.operation_id
           AND transaction_id IS NOT NULL
           AND transaction_hash IS NOT NULL
           AND receipt_block_number IS NOT NULL
           AND receipt_block_hash IS NOT NULL
           AND finalized_block_number IS NOT NULL
           AND pre_balance IS NOT NULL
           AND post_balance IS NOT NULL;
        GET DIAGNOSTICS applied_count = ROW_COUNT;
        IF applied_count <> 1 THEN
            RAISE EXCEPTION 'v2_chain_operation_finality_evidence_missing' USING ERRCODE='55000';
        END IF;
    ELSE
        UPDATE trading.chain_operations
           SET status = NEW.transition_to, updated_at = now()
         WHERE id = NEW.operation_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_chain_operation_state_cas
    BEFORE INSERT ON trading.chain_operation_state_history
    FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_chain_operation_state();
"""
    )
    op.execute(
        """
CREATE FUNCTION trading.v2_guard_chain_operation_state_history_immutable() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'v2_chain_operation_state_immutable' USING ERRCODE='55000';
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_chain_operation_state_history_immutable
    BEFORE UPDATE OR DELETE ON trading.chain_operation_state_history
    FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_chain_operation_state_history_immutable();
"""
    )
    op.execute(
        """
CREATE FUNCTION trading.v2_guard_settlement_observation_immutable() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'v2_settlement_observation_immutable' USING ERRCODE='55000';
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_settlement_observations_immutable
    BEFORE UPDATE OR DELETE ON trading.settlement_observations
    FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_settlement_observation_immutable();
"""
    )
    op.execute(
        """
CREATE FUNCTION trading.v2_guard_settlement_observation_complete() RETURNS trigger AS $$
DECLARE bad text;
BEGIN
    SELECT string_agg(DISTINCT obs.condition_id, ', ' ORDER BY obs.condition_id)
      INTO bad
      FROM (SELECT DISTINCT condition_id FROM trading.settlement_observations
             WHERE status = 'COMPLETE') obs
      LEFT JOIN LATERAL (
        SELECT count(*) AS total,
               count(*) FILTER (WHERE source_kind = 'gamma_clob_closed') AS g,
               count(*) FILTER (WHERE source_kind = 'ctf_payout') AS c,
               count(*) FILTER (WHERE source_kind = 'data_api_redeemable') AS d,
               count(*) FILTER (WHERE source_kind = 'clob_winner_5050') AS w,
               count(*) FILTER (WHERE source_kind = 'label_audit') AS l
          FROM trading.settlement_observations o
         WHERE o.condition_id = obs.condition_id
      ) s ON true
      WHERE s.total <> 5 OR s.g <> 1 OR s.c <> 1 OR s.d <> 1 OR s.w <> 1 OR s.l <> 1;
    IF bad IS NOT NULL THEN
        RAISE EXCEPTION 'v2_settlement_observation_complete_set_missing:%', bad
        USING ERRCODE='55000';
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;
CREATE CONSTRAINT TRIGGER trg_settlement_observations_complete_set
    AFTER INSERT OR UPDATE ON trading.settlement_observations
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_settlement_observation_complete();
"""
    )


def _drop_guards() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_contract_registry_immutable ON trading.contract_registry")
    op.execute("DROP TRIGGER IF EXISTS trg_contract_registry_publish_check ON trading.contract_registry")
    op.execute("DROP TRIGGER IF EXISTS trg_chain_operations_lifecycle ON trading.chain_operations")
    op.execute("DROP TRIGGER IF EXISTS trg_chain_operation_state_cas ON trading.chain_operation_state_history")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_chain_operation_state_history_immutable "
        "ON trading.chain_operation_state_history"
    )
    op.execute("DROP TRIGGER IF EXISTS trg_settlement_observations_immutable ON trading.settlement_observations")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_settlement_observations_complete_set "
        "ON trading.settlement_observations"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_contract_registry_immutable()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_contract_registry_publish()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_chain_operation_update()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_chain_operation_state()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_chain_operation_state_history_immutable()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_settlement_observation_immutable()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_settlement_observation_complete()")


def upgrade() -> None:
    for table in _NEW_TABLES:
        op.execute(table.create_sql)
    for table in _NEW_TABLES:
        for statement in table.index_sql:
            op.execute(statement)
    _add_lineage()
    _create_guards()


def downgrade() -> None:
    _assert_downgrade_safe()
    _drop_guards()
    _drop_lineage()
    for table in reversed(_NEW_TABLES):
        op.execute(f"DROP TABLE IF EXISTS trading.{table.name}")
