"""execution authorization envelopes orders trades reconcile

Revision ID: b1000051
Revises: b1000050
Create Date: 2026-08-11 21:00:00

v2_0051 —— WP-05 Checkpoint C：authorization envelopes / private CLOB orders / User WS /
trades / reconciliation。

- ``upgrade``：
  - 新建且只新建 9 张 execution-plane 表：
    execution_authorization_envelopes / exchange_order_attempts / exchange_orders /
    order_state_events / exchange_trades / account_reconciliations / workflow_events /
    external_call_attempts / alert_events。
  - 只对既有 executions / positions / position_lots / ledger_transactions 增加
    account/envelope/order/trade lineage 列（不得创建第二套 intent/position/cash ledger/
    reservation/order 表）。
  - guard：
    - append-only：order_state_events / exchange_trades / external_call_attempts /
      workflow_events / alert_events 复用 0002 ``v2_reject_immutable_row``；
    - exchange_orders 状态机（OPEN→ACK|PARTIAL|FILLED|CANCELLED|REJECTED|UNKNOWN→RECONCILED，
      filled_size 单调非降且 ≤ size）；
    - exchange_order_attempts 生命周期（SUBMITTED→terminal，一次 send 一次 result）；
    - execution_authorization_envelopes 生命周期（ACTIVE→USED|EXPIRED|REVOKED|SUPERSEDED）；
    - account_reconciliations 状态（RECONCILING→COMPLETED|FAILED；COMPLETED 必须
      differences 空数组 + completed_at 非空）；
    - deferred permission/intent-bind trigger：envelope 的 account/release 必须引用同一个
      active shadow permission（authorized_capital=0），authority 只允许 FAKE_CONFORMANCE，
      intent_hash 必须等于引用 intent 的唯一 hash。
- ``downgrade``：fail-closed preflight（未知 trading 对象 RAISE
  ``v2_wp05_execution_orders_unknown_object``，ERRCODE 55000，含动态分区子表白名单豁免），
  drop guards，移除 lineage 列，逆序 DROP 9 表。

fixed literal DDL；不 import live ORM 生成 DDL；无密钥/signature 明文。
"""
from dataclasses import dataclass
from typing import Sequence, Union

from alembic import op

TRADING_SCHEMA = "trading"

# revision identifiers, used by Alembic.
revision: str = "b1000051"
down_revision: Union[str, Sequence[str], None] = "b1000050"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_AUTHORITY_VALUES = "'FAKE_CONFORMANCE'"

_ATTEMPT_RESULTS = (
    "'SUBMITTED','ACK','PARTIAL','FILLED','CANCELLED','REJECTED','UNKNOWN','FAILED'"
)
_ORDER_STATUS = (
    "'OPEN','ACK','PARTIAL','FILLED','CANCELLED','REJECTED','UNKNOWN','RECONCILED'"
)
_EVENT_TYPES = (
    "'INTENT','SUBMITTED','ACK','PARTIAL','FILLED','CANCELLED','REJECTED','UNKNOWN','RECONCILED'"
)
_ENVELOPE_STATUS = "'ACTIVE','USED','EXPIRED','REVOKED','SUPERSEDED'"
_RECONCILIATION_STATUS = "'RECONCILING','COMPLETED','FAILED'"
_ALERT_SEVERITY = "'INFO','WARNING','ERROR','CRITICAL'"


@dataclass(frozen=True)
class _FrozenTableSpec:
    name: str
    create_sql: str
    index_sql: tuple[str, ...] = ()
    append_only: bool = False


_NEW_TABLES = (
    _FrozenTableSpec(
        name="execution_authorization_envelopes",
        create_sql=(
            "\nCREATE TABLE trading.execution_authorization_envelopes (\n"
            "\tenvelope_key TEXT COLLATE \"C\" NOT NULL, \n"
            "\tintent_id BIGINT NOT NULL, \n"
            "\taccount_id BIGINT NOT NULL, \n"
            "\trelease_manifest_id BIGINT NOT NULL, \n"
            "\texecution_spec_version_id BIGINT NOT NULL, \n"
            "\tcapital_permission_manifest_id BIGINT NOT NULL, \n"
            "\tauthority VARCHAR(64) NOT NULL, \n"
            "\tidempotency_key VARCHAR(255) NOT NULL, \n"
            "\tfencing_token BIGINT NOT NULL, \n"
            "\tintent_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tpreflight_hash1 VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tpreflight_hash2 VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tenvelope_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tstatus VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL, \n"
            "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n"
            "\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tPRIMARY KEY (id), \n"
            "\tCONSTRAINT uq_execution_authorization_envelopes_key UNIQUE (envelope_key), \n"
            "\tCONSTRAINT uq_execution_authorization_envelopes_hash UNIQUE (envelope_hash), \n"
            "\tCONSTRAINT uq_execution_authorization_envelopes_idempotency UNIQUE (idempotency_key), \n"
            "\tCONSTRAINT ck_execution_authorization_envelopes_authority_known "
            "CHECK (authority IN (" + _AUTHORITY_VALUES + ")), \n"
            "\tCONSTRAINT ck_execution_authorization_envelopes_status_known "
            "CHECK (status IN (" + _ENVELOPE_STATUS + ")), \n"
            "\tCONSTRAINT ck_execution_authorization_envelopes_fencing_positive "
            "CHECK (fencing_token > 0), \n"
            "\tCONSTRAINT ck_execution_authorization_envelopes_intent_hash_hex "
            "CHECK (intent_hash ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_execution_authorization_envelopes_preflight1_hex "
            "CHECK (preflight_hash1 ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_execution_authorization_envelopes_preflight2_hex "
            "CHECK (preflight_hash2 ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_execution_authorization_envelopes_hash_hex "
            "CHECK (envelope_hash ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT fk_execution_authorization_envelopes_intent "
            "FOREIGN KEY(intent_id) REFERENCES trading.economic_action_intents (id), \n"
            "\tCONSTRAINT fk_execution_authorization_envelopes_account "
            "FOREIGN KEY(account_id) REFERENCES trading.pm_accounts (id), \n"
            "\tCONSTRAINT fk_execution_authorization_envelopes_release "
            "FOREIGN KEY(release_manifest_id) REFERENCES trading.release_manifests (id), \n"
            "\tCONSTRAINT fk_execution_authorization_envelopes_exec_spec "
            "FOREIGN KEY(execution_spec_version_id) "
            "REFERENCES trading.execution_spec_versions (id), \n"
            "\tCONSTRAINT fk_execution_authorization_envelopes_permission "
            "FOREIGN KEY(capital_permission_manifest_id) "
            "REFERENCES trading.capital_permission_manifests (id)\n"
            ")\n\n"
        ),
        index_sql=(
            "CREATE INDEX ix_execution_authorization_envelopes_intent "
            "ON trading.execution_authorization_envelopes (intent_id)",
            "CREATE INDEX ix_execution_authorization_envelopes_account "
            "ON trading.execution_authorization_envelopes (account_id)",
        ),
    ),
    _FrozenTableSpec(
        name="exchange_orders",
        create_sql=(
            "\nCREATE TABLE trading.exchange_orders (\n"
            "\torder_key TEXT COLLATE \"C\" NOT NULL, \n"
            "\tattempt_id BIGINT, \n"
            "\taccount_id BIGINT NOT NULL, \n"
            "\texternal_order_id TEXT COLLATE \"C\", \n"
            "\ttoken_id TEXT COLLATE \"C\" NOT NULL, \n"
            "\tside VARCHAR(8) NOT NULL, \n"
            "\tprice NUMERIC(38, 12) NOT NULL, \n"
            "\tsize NUMERIC(38, 0) NOT NULL, \n"
            "\tfilled_size NUMERIC(38, 0) DEFAULT 0 NOT NULL, \n"
            "\tstatus VARCHAR(32) DEFAULT 'OPEN' NOT NULL, \n"
            "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n"
            "\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tPRIMARY KEY (id), \n"
            "\tCONSTRAINT uq_exchange_orders_key UNIQUE (order_key), \n"
            "\tCONSTRAINT uq_exchange_orders_account_ext "
            "UNIQUE (account_id, external_order_id), \n"
            "\tCONSTRAINT uq_exchange_orders_account_id_side "
            "UNIQUE (account_id, id, side), \n"
            "\tCONSTRAINT ck_exchange_orders_status_known "
            "CHECK (status IN (" + _ORDER_STATUS + ")), \n"
            "\tCONSTRAINT ck_exchange_orders_side_known CHECK (side IN ('BUY','SELL')), \n"
            "\tCONSTRAINT ck_exchange_orders_price_range "
            "CHECK (price > 0 AND price <= 1), \n"
            "\tCONSTRAINT ck_exchange_orders_size_positive CHECK (size > 0), \n"
            "\tCONSTRAINT ck_exchange_orders_filled_range "
            "CHECK (filled_size >= 0 AND filled_size <= size), \n"
            "\tCONSTRAINT fk_exchange_orders_account "
            "FOREIGN KEY(account_id) REFERENCES trading.pm_accounts (id)\n"
            ")\n\n"
        ),
        index_sql=(
            "CREATE INDEX ix_exchange_orders_account "
            "ON trading.exchange_orders (account_id, status)",
        ),
    ),
    _FrozenTableSpec(
        name="order_state_events",
        create_sql=(
            "\nCREATE TABLE trading.order_state_events (\n"
            "\tevent_key VARCHAR(255) NOT NULL, \n"
            "\torder_id BIGINT NOT NULL, \n"
            "\tevent_type VARCHAR(32) NOT NULL, \n"
            "\ttransition_from VARCHAR(32) NOT NULL, \n"
            "\ttransition_to VARCHAR(32) NOT NULL, \n"
            "\tevent_payload JSONB NOT NULL, \n"
            "\tevent_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tfence_token BIGINT NOT NULL, \n"
            "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n"
            "\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tPRIMARY KEY (id), \n"
            "\tCONSTRAINT uq_order_state_events_key UNIQUE (event_key), \n"
            "\tCONSTRAINT ck_order_state_events_type_known "
            "CHECK (event_type IN (" + _EVENT_TYPES + ")), \n"
            "\tCONSTRAINT ck_order_state_events_type_matches_transition "
            "CHECK (event_type = transition_to), \n"
            "\tCONSTRAINT ck_order_state_events_transition_exact CHECK ("
            "(transition_from = 'INTENT' AND transition_to = 'SUBMITTED') OR "
            "(transition_from = 'SUBMITTED' AND transition_to IN "
            "('ACK','PARTIAL','FILLED','CANCELLED','REJECTED','UNKNOWN')) OR "
            "(transition_from = 'ACK' AND transition_to IN "
            "('PARTIAL','FILLED','CANCELLED','UNKNOWN')) OR "
            "(transition_from = 'PARTIAL' AND transition_to IN "
            "('FILLED','CANCELLED','UNKNOWN')) OR "
            "(transition_from = 'UNKNOWN' AND transition_to = 'RECONCILED')), \n"
            "\tCONSTRAINT ck_order_state_events_payload_object "
            "CHECK (jsonb_typeof(event_payload) = 'object'), \n"
            "\tCONSTRAINT ck_order_state_events_hash_hex "
            "CHECK (event_hash ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_order_state_events_fence_positive CHECK (fence_token > 0), \n"
            "\tCONSTRAINT fk_order_state_events_order "
            "FOREIGN KEY(order_id) REFERENCES trading.exchange_orders (id)\n"
            ")\n\n"
        ),
        index_sql=(
            "CREATE INDEX ix_order_state_events_order "
            "ON trading.order_state_events (order_id, event_type)",
        ),
        append_only=True,
    ),
    _FrozenTableSpec(
        name="exchange_order_attempts",
        create_sql=(
            "\nCREATE TABLE trading.exchange_order_attempts (\n"
            "\tattempt_key TEXT COLLATE \"C\" NOT NULL, \n"
            "\tenvelope_id BIGINT NOT NULL, \n"
            "\tattempt_no INTEGER NOT NULL, \n"
            "\tbody_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\texpected_order_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tsdk_manifest_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tsalt BIGINT NOT NULL, \n"
            "\ttimestamp BIGINT NOT NULL, \n"
            "\tfencing_token BIGINT NOT NULL, \n"
            "\tresult VARCHAR(32) DEFAULT 'SUBMITTED' NOT NULL, \n"
            "\tstate_event_id BIGINT, \n"
            "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n"
            "\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tPRIMARY KEY (id), \n"
            "\tCONSTRAINT uq_exchange_order_attempts_key UNIQUE (attempt_key), \n"
            "\tCONSTRAINT uq_exchange_order_attempts_envelope_no "
            "UNIQUE (envelope_id, attempt_no), \n"
            "\tCONSTRAINT ck_exchange_order_attempts_result_known "
            "CHECK (result IN (" + _ATTEMPT_RESULTS + ")), \n"
            "\tCONSTRAINT ck_exchange_order_attempts_body_hash_hex "
            "CHECK (body_hash ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_exchange_order_attempts_order_hash_hex "
            "CHECK (expected_order_hash ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_exchange_order_attempts_sdk_hash_hex "
            "CHECK (sdk_manifest_hash ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_exchange_order_attempts_fencing_positive "
            "CHECK (fencing_token > 0), \n"
            "\tCONSTRAINT ck_exchange_order_attempts_salt_positive CHECK (salt > 0), \n"
            "\tCONSTRAINT ck_exchange_order_attempts_timestamp_positive CHECK (timestamp > 0), \n"
            "\tCONSTRAINT ck_exchange_order_attempts_no_positive CHECK (attempt_no >= 1), \n"
            "\tCONSTRAINT fk_exchange_order_attempts_envelope "
            "FOREIGN KEY(envelope_id) "
            "REFERENCES trading.execution_authorization_envelopes (id), \n"
            "\tCONSTRAINT fk_exchange_order_attempts_state_event "
            "FOREIGN KEY(state_event_id) REFERENCES trading.order_state_events (id)\n"
            ")\n\n"
        ),
        index_sql=(
            "CREATE INDEX ix_exchange_order_attempts_envelope "
            "ON trading.exchange_order_attempts (envelope_id, attempt_no)",
        ),
    ),
    _FrozenTableSpec(
        name="exchange_trades",
        create_sql=(
            "\nCREATE TABLE trading.exchange_trades (\n"
            "\ttrade_key TEXT COLLATE \"C\" NOT NULL, \n"
            "\torder_id BIGINT NOT NULL, \n"
            "\taccount_id BIGINT NOT NULL, \n"
            "\texternal_trade_id TEXT COLLATE \"C\" NOT NULL, \n"
            "\tside VARCHAR(8) NOT NULL, \n"
            "\tprice NUMERIC(38, 12) NOT NULL, \n"
            "\tsize NUMERIC(38, 0) NOT NULL, \n"
            "\tfee NUMERIC(38, 0) DEFAULT 0 NOT NULL, \n"
            "\ttrade_time TIMESTAMP WITH TIME ZONE NOT NULL, \n"
            "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n"
            "\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tPRIMARY KEY (id), \n"
            "\tCONSTRAINT uq_exchange_trades_key UNIQUE (trade_key), \n"
            "\tCONSTRAINT uq_exchange_trades_account_ext "
            "UNIQUE (account_id, external_trade_id), \n"
            "\tCONSTRAINT ck_exchange_trades_side_known CHECK (side IN ('BUY','SELL')), \n"
            "\tCONSTRAINT ck_exchange_trades_price_range "
            "CHECK (price > 0 AND price <= 1), \n"
            "\tCONSTRAINT ck_exchange_trades_size_positive CHECK (size > 0), \n"
            "\tCONSTRAINT ck_exchange_trades_fee_nonneg CHECK (fee >= 0), \n"
            "\tCONSTRAINT fk_exchange_trades_order "
            "FOREIGN KEY(order_id) REFERENCES trading.exchange_orders (id), \n"
            "\tCONSTRAINT fk_exchange_trades_account "
            "FOREIGN KEY(account_id) REFERENCES trading.pm_accounts (id), \n"
            "\tCONSTRAINT fk_exchange_trades_order_account_side "
            "FOREIGN KEY(account_id, order_id, side) "
            "REFERENCES trading.exchange_orders (account_id, id, side)\n"
            ")\n\n"
        ),
        index_sql=(
            "CREATE INDEX ix_exchange_trades_order "
            "ON trading.exchange_trades (order_id)",
        ),
        append_only=True,
    ),
    _FrozenTableSpec(
        name="account_reconciliations",
        create_sql=(
            "\nCREATE TABLE trading.account_reconciliations (\n"
            "\treconciliation_key TEXT COLLATE \"C\" NOT NULL, \n"
            "\taccount_id BIGINT NOT NULL, \n"
            "\ttrigger_reason VARCHAR(64) NOT NULL, \n"
            "\tws_watermark BIGINT NOT NULL, \n"
            "\trest_page_cursor JSONB NOT NULL, \n"
            "\trest_page_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tunknown_queries JSONB NOT NULL, \n"
            "\tinput_manifest_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\toutput_manifest_hash VARCHAR(64) COLLATE \"C\", \n"
            "\tdifferences JSONB NOT NULL, \n"
            "\tfencing_token BIGINT NOT NULL, \n"
            "\tstatus VARCHAR(32) DEFAULT 'RECONCILING' NOT NULL, \n"
            "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n"
            "\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tcompleted_at TIMESTAMP WITH TIME ZONE, \n"
            "\tPRIMARY KEY (id), \n"
            "\tCONSTRAINT uq_account_reconciliations_key UNIQUE (reconciliation_key), \n"
            "\tCONSTRAINT ck_account_reconciliations_status_known "
            "CHECK (status IN (" + _RECONCILIATION_STATUS + ")), \n"
            "\tCONSTRAINT ck_account_reconciliations_fencing_positive "
            "CHECK (fencing_token > 0), \n"
            "\tCONSTRAINT ck_account_reconciliations_ws_watermark_nonneg "
            "CHECK (ws_watermark >= 0), \n"
            "\tCONSTRAINT ck_account_reconciliations_page_hash_hex "
            "CHECK (rest_page_hash ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_account_reconciliations_input_hash_hex "
            "CHECK (input_manifest_hash ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_account_reconciliations_output_hash_hex "
            "CHECK (output_manifest_hash IS NULL OR output_manifest_hash ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_account_reconciliations_cursor_object "
            "CHECK (jsonb_typeof(rest_page_cursor) = 'object'), \n"
            "\tCONSTRAINT ck_account_reconciliations_unknown_object "
            "CHECK (jsonb_typeof(unknown_queries) = 'object'), \n"
            "\tCONSTRAINT ck_account_reconciliations_differences_array "
            "CHECK (jsonb_typeof(differences) = 'array'), \n"
            "\tCONSTRAINT ck_account_reconciliations_completed_pair "
            "CHECK ((status = 'COMPLETED') = (completed_at IS NOT NULL)), \n"
            "\tCONSTRAINT fk_account_reconciliations_account "
            "FOREIGN KEY(account_id) REFERENCES trading.pm_accounts (id)\n"
            ")\n\n"
        ),
        index_sql=(
            "CREATE INDEX ix_account_reconciliations_account "
            "ON trading.account_reconciliations (account_id, created_at)",
        ),
    ),
    _FrozenTableSpec(
        name="workflow_events",
        create_sql=(
            "\nCREATE TABLE trading.workflow_events (\n"
            "\tevent_key VARCHAR(255) NOT NULL, \n"
            "\tevent_type VARCHAR(64) NOT NULL, \n"
            "\taggregate_type VARCHAR(64) NOT NULL, \n"
            "\taggregate_id TEXT COLLATE \"C\" NOT NULL, \n"
            "\tpayload_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tpayload JSONB NOT NULL, \n"
            "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n"
            "\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tPRIMARY KEY (id), \n"
            "\tCONSTRAINT uq_workflow_events_key UNIQUE (event_key), \n"
            "\tCONSTRAINT ck_workflow_events_payload_hash_hex "
            "CHECK (payload_hash ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_workflow_events_type_nonempty "
            "CHECK (length(btrim(event_type)) > 0), \n"
            "\tCONSTRAINT ck_workflow_events_aggregate_type_nonempty "
            "CHECK (length(btrim(aggregate_type)) > 0)\n"
            ")\n\n"
        ),
        index_sql=(
            "CREATE INDEX ix_workflow_events_aggregate "
            "ON trading.workflow_events (aggregate_type, aggregate_id)",
        ),
        append_only=True,
    ),
    _FrozenTableSpec(
        name="external_call_attempts",
        create_sql=(
            "\nCREATE TABLE trading.external_call_attempts (\n"
            "\tattempt_key VARCHAR(255) NOT NULL, \n"
            "\tdriver VARCHAR(64) NOT NULL, \n"
            "\tendpoint TEXT COLLATE \"C\" NOT NULL, \n"
            "\tmethod VARCHAR(16) NOT NULL, \n"
            "\trequest_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tresponse_hash VARCHAR(64) COLLATE \"C\", \n"
            "\tstatus_code INTEGER, \n"
            "\tlatency_ms INTEGER NOT NULL, \n"
            "\trate_limit_remaining INTEGER, \n"
            "\terror_reason VARCHAR(128), \n"
            "\tfence_token BIGINT NOT NULL, \n"
            "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n"
            "\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tPRIMARY KEY (id), \n"
            "\tCONSTRAINT uq_external_call_attempts_key UNIQUE (attempt_key), \n"
            "\tCONSTRAINT ck_external_call_attempts_request_hash_hex "
            "CHECK (request_hash ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_external_call_attempts_response_hash_hex "
            "CHECK (response_hash IS NULL OR response_hash ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_external_call_attempts_latency_nonneg CHECK (latency_ms >= 0), \n"
            "\tCONSTRAINT ck_external_call_attempts_fencing_positive "
            "CHECK (fence_token > 0), \n"
            "\tCONSTRAINT ck_external_call_attempts_method_known "
            "CHECK (method IN ('GET','POST','DELETE','PUT','PATCH')), \n"
            "\tCONSTRAINT ck_external_call_attempts_status_nonneg CHECK (status_code >= 0)\n"
            ")\n\n"
        ),
        index_sql=(
            "CREATE INDEX ix_external_call_attempts_driver "
            "ON trading.external_call_attempts (driver, created_at)",
        ),
        append_only=True,
    ),
    _FrozenTableSpec(
        name="alert_events",
        create_sql=(
            "\nCREATE TABLE trading.alert_events (\n"
            "\talert_key VARCHAR(255) NOT NULL, \n"
            "\tseverity VARCHAR(16) NOT NULL, \n"
            "\tcode VARCHAR(128) NOT NULL, \n"
            "\tmessage_redacted TEXT NOT NULL, \n"
            "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n"
            "\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tPRIMARY KEY (id), \n"
            "\tCONSTRAINT uq_alert_events_key UNIQUE (alert_key), \n"
            "\tCONSTRAINT ck_alert_events_severity_known "
            "CHECK (severity IN (" + _ALERT_SEVERITY + ")), \n"
            "\tCONSTRAINT ck_alert_events_code_nonempty CHECK (length(btrim(code)) > 0)\n"
            ")\n\n"
        ),
        append_only=True,
    ),
)

# b1000050 已存在的 trading 关系（0051 downgrade preflight allowlist = 0041 的 pre-0041 全量
# + 0040 的 14 张 learning 表 + 0041 的 5 张投影表 + 0050 的 5 张 execution-plane 表）。
_PRE_0051_RELATIONS = (
    "artifact_objects", "artifact_lineage_edges", "archive_manifests",
    "retention_manifests", "runtime_config_versions", "strategy_objective_contracts",
    "strategy_versions", "execution_spec_versions", "capital_permission_manifests",
    "model_role_bindings", "release_manifests", "policy_type_scopes", "policy_freezes",
    "secret_vault_entries", "secret_vault_versions", "secret_access_events",
    "idempotency_claims", "transactional_outbox", "outbox_delivery_history",
    "job_completions", "pm_universe_frames", "pm_universe_frame_pages", "pm_events",
    "pm_markets", "pm_market_versions", "pm_tokens", "pm_token_versions",
    "pm_market_lifecycle_events", "pm_market_current", "pm_connection_epochs",
    "pm_source_event_batches", "pm_source_event_index", "pm_book_checkpoints",
    "pm_book_levels", "pm_book_current", "pm_quote_bindings", "contract_snapshots",
    "contract_specs", "payout_functions", "forecast_components", "world_schema_versions",
    "forecast_component_versions", "forecast_component_contract_specs",
    "portfolio_dependency_edges", "evaluation_cohorts", "universe_memberships",
    "screening_episodes", "audit_samples", "decision_opportunities",
    "decision_opportunity_markets", "episode_memberships", "forecast_episodes",
    "episode_contract_specs", "information_snapshots", "information_snapshot_items",
    "gate_decisions", "priors", "evidence_coverage_policies", "evidence_revisions",
    "evidence_bundles", "evidence_bundle_items", "forecast_input_manifests",
    "forecast_submissions", "payout_projections", "coherence_checks",
    "forecast_challenges", "forecast_leases", "ai_invocations", "ai_tool_calls",
    "ai_validation_results", "market_relative_decisions", "discrepancy_reviews",
    "trade_decisions", "action_candidates", "resolution_cashflows", "action_sets",
    "action_set_legs", "underwriting_plans", "economic_action_intents",
    "executions", "positions", "position_lots", "ledger_transactions",
    "ledger_postings", "operating_cost_entries",
    # b1000040 learning facts（14 张）
    "resolution_labels", "resolution_clusters", "resolution_cluster_memberships",
    "score_targets", "score_target_memberships", "score_observations", "experiments",
    "experiment_variants", "challenger_variants", "metric_runs", "error_reviews",
    "ablation_runs", "promotion_decisions", "replay_runs",
    # b1000041 read projections（5 张）
    "ops_health_current", "pipeline_funnel_hourly", "account_risk_current",
    "provider_cost_daily", "latest_chain_summary",
    # b1000050 execution-plane（5 张）
    "pm_accounts", "pm_balance_allowance_snapshots", "account_funds_current",
    "capital_reservations", "execution_leases",
)


def _assert_downgrade_safe() -> None:
    allowed = ", ".join(
        f"'{name}'" for name in (*_PRE_0051_RELATIONS, *(t.name for t in _NEW_TABLES))
    )
    owned = ", ".join(f"'{t.name}'" for t in _NEW_TABLES)
    known_indexes = ", ".join(
        f"'{statement.split(' ON ')[0].replace('CREATE INDEX ', '').strip()}'"
        for table in _NEW_TABLES for statement in table.index_sql
    ) or "''"
    known_triggers = ", ".join(
        f"'{name}'" for name in (
            *(f"trg_{t.name}_immutable" for t in _NEW_TABLES if t.append_only),
            "trg_execution_authorization_envelopes_lifecycle",
            "trg_exchange_orders_lifecycle",
            "trg_exchange_order_attempts_lifecycle",
            "trg_account_reconciliations_lifecycle",
            "trg_execution_envelope_permission_check",
            "trg_execution_envelope_intent_bind",
            "trg_exchange_orders_attempt_lineage",
        )
    )
    op.execute(
        f"""
DO $v2_wp05_execution_orders_preflight$
DECLARE unknown_objects text;
        unknown_indexes text;
        unknown_triggers text;
        unresolved_count bigint;
BEGIN
    SELECT (SELECT count(*) FROM trading.exchange_order_attempts
             WHERE result = 'SUBMITTED')
         + (SELECT count(*) FROM trading.exchange_orders
             WHERE status IN ('OPEN','ACK','PARTIAL','UNKNOWN'))
         + (SELECT count(*) FROM trading.account_reconciliations
             WHERE status IN ('RECONCILING','FAILED'))
         + (SELECT count(*) FROM trading.executions
             WHERE quote_checkpoint_id IS NULL)
         + (SELECT count(*) FROM trading.position_lots
             WHERE execution_id IS NULL)
      INTO unresolved_count;
    IF unresolved_count <> 0 THEN
        RAISE EXCEPTION 'v2_wp05_execution_orders_downgrade_unresolved_facts:%', unresolved_count
        USING ERRCODE='55000';
    END IF;
    SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
      INTO unknown_objects
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'trading'
       AND c.relkind IN ('r','p','v','m','f')
       AND c.relname NOT IN ({allowed})
       AND NOT EXISTS (
           SELECT 1 FROM pg_inherits i
           JOIN pg_class p ON p.oid = i.inhparent
           JOIN pg_namespace pn ON pn.oid = p.relnamespace
           WHERE i.inhrelid = c.oid AND pn.nspname = 'trading'
             AND ((p.relname = 'outbox_delivery_history'
                   AND c.relname ~ '^outbox_delivery_history_[0-9]{{6}}$')
               OR (p.relname IN ('pm_source_event_batches','pm_source_event_index',
                                  'pm_book_checkpoints','pm_book_levels')
                   AND c.relname ~ ('^' || p.relname || '_[0-9]{{8}}$'))
               OR (p.relname IN ('ai_invocations','ai_tool_calls','ai_validation_results')
                   AND c.relname ~ ('^' || p.relname || '_[0-9]{{6}}$')))
       );
    IF unknown_objects IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp05_execution_orders_unknown_object:%', unknown_objects
        USING ERRCODE='55000';
    END IF;
    SELECT string_agg(idx.relname, ', ' ORDER BY idx.relname)
      INTO unknown_indexes
      FROM pg_index i
      JOIN pg_class idx ON idx.oid=i.indexrelid
      JOIN pg_class tbl ON tbl.oid=i.indrelid
      JOIN pg_namespace n ON n.oid=tbl.relnamespace
     WHERE n.nspname='trading' AND tbl.relname IN ({owned})
       AND NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conindid=idx.oid)
       AND idx.relname NOT IN ({known_indexes});
    IF unknown_indexes IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp05_execution_orders_unknown_index:%', unknown_indexes
        USING ERRCODE='55000';
    END IF;
    SELECT string_agg(t.tgname, ', ' ORDER BY t.tgname)
      INTO unknown_triggers
      FROM pg_trigger t
      JOIN pg_class tbl ON tbl.oid=t.tgrelid
      JOIN pg_namespace n ON n.oid=tbl.relnamespace
     WHERE n.nspname='trading' AND tbl.relname IN ({owned})
       AND NOT t.tgisinternal AND t.tgname NOT IN ({known_triggers});
    IF unknown_triggers IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp05_execution_orders_unknown_trigger:%', unknown_triggers
        USING ERRCODE='55000';
    END IF;
END $v2_wp05_execution_orders_preflight$
"""
    )


def _add_lineage() -> None:
    """只对既有 executions/positions/position_lots/ledger_transactions 增加 lineage 列。"""
    # 真实 CLOB fill 走 exchange_trades/position_lots/ledger（executions 是 shadow 一次性
    # fill 事实，immutable 且 per-intent-leg）；放宽 executions.quote_checkpoint_id 与
    # position_lots.execution_id 为可空，供真实 fill 的 lot 直接落库。
    op.execute(
        "ALTER TABLE trading.executions ALTER COLUMN quote_checkpoint_id DROP NOT NULL"
    )
    op.execute(
        "ALTER TABLE trading.position_lots ALTER COLUMN execution_id DROP NOT NULL"
    )
    op.execute(
        "ALTER TABLE trading.executions ADD COLUMN account_id BIGINT"
    )
    op.execute(
        "ALTER TABLE trading.executions ADD COLUMN envelope_id BIGINT"
    )
    op.execute(
        "ALTER TABLE trading.executions ADD COLUMN order_id BIGINT"
    )
    op.execute(
        "ALTER TABLE trading.executions ADD COLUMN trade_id BIGINT"
    )
    op.execute(
        "ALTER TABLE trading.executions "
        "ADD CONSTRAINT fk_executions_account FOREIGN KEY(account_id) "
        "REFERENCES trading.pm_accounts (id)"
    )
    op.execute(
        "ALTER TABLE trading.executions "
        "ADD CONSTRAINT fk_executions_envelope FOREIGN KEY(envelope_id) "
        "REFERENCES trading.execution_authorization_envelopes (id)"
    )
    op.execute(
        "ALTER TABLE trading.executions "
        "ADD CONSTRAINT fk_executions_exchange_order FOREIGN KEY(order_id) "
        "REFERENCES trading.exchange_orders (id)"
    )
    op.execute(
        "ALTER TABLE trading.executions "
        "ADD CONSTRAINT fk_executions_exchange_trade FOREIGN KEY(trade_id) "
        "REFERENCES trading.exchange_trades (id)"
    )
    op.execute(
        "ALTER TABLE trading.executions "
        "ADD CONSTRAINT uq_executions_outer_lineage UNIQUE (order_id, trade_id)"
    )
    op.execute(
        "ALTER TABLE trading.positions ADD COLUMN account_id BIGINT"
    )
    op.execute(
        "ALTER TABLE trading.positions ADD COLUMN envelope_id BIGINT"
    )
    op.execute(
        "ALTER TABLE trading.positions ADD COLUMN order_id BIGINT"
    )
    op.execute(
        "ALTER TABLE trading.positions "
        "ADD CONSTRAINT fk_positions_account FOREIGN KEY(account_id) "
        "REFERENCES trading.pm_accounts (id)"
    )
    op.execute(
        "ALTER TABLE trading.positions "
        "ADD CONSTRAINT fk_positions_envelope FOREIGN KEY(envelope_id) "
        "REFERENCES trading.execution_authorization_envelopes (id)"
    )
    op.execute(
        "ALTER TABLE trading.positions "
        "ADD CONSTRAINT fk_positions_exchange_order FOREIGN KEY(order_id) "
        "REFERENCES trading.exchange_orders (id)"
    )
    op.execute(
        "ALTER TABLE trading.position_lots ADD COLUMN account_id BIGINT"
    )
    op.execute(
        "ALTER TABLE trading.position_lots ADD COLUMN order_id BIGINT"
    )
    op.execute(
        "ALTER TABLE trading.position_lots ADD COLUMN trade_id BIGINT"
    )
    op.execute(
        "ALTER TABLE trading.position_lots "
        "ADD CONSTRAINT fk_position_lots_account FOREIGN KEY(account_id) "
        "REFERENCES trading.pm_accounts (id)"
    )
    op.execute(
        "ALTER TABLE trading.position_lots "
        "ADD CONSTRAINT fk_position_lots_exchange_order FOREIGN KEY(order_id) "
        "REFERENCES trading.exchange_orders (id)"
    )
    op.execute(
        "ALTER TABLE trading.position_lots "
        "ADD CONSTRAINT fk_position_lots_exchange_trade FOREIGN KEY(trade_id) "
        "REFERENCES trading.exchange_trades (id)"
    )
    op.execute(
        "ALTER TABLE trading.ledger_transactions ADD COLUMN account_id BIGINT"
    )
    op.execute(
        "ALTER TABLE trading.ledger_transactions ADD COLUMN envelope_id BIGINT"
    )
    op.execute(
        "ALTER TABLE trading.ledger_transactions ADD COLUMN order_id BIGINT"
    )
    op.execute(
        "ALTER TABLE trading.ledger_transactions ADD COLUMN trade_id BIGINT"
    )
    op.execute(
        "ALTER TABLE trading.ledger_transactions "
        "ADD CONSTRAINT fk_ledger_transactions_account FOREIGN KEY(account_id) "
        "REFERENCES trading.pm_accounts (id)"
    )
    op.execute(
        "ALTER TABLE trading.ledger_transactions "
        "ADD CONSTRAINT fk_ledger_transactions_envelope FOREIGN KEY(envelope_id) "
        "REFERENCES trading.execution_authorization_envelopes (id)"
    )
    op.execute(
        "ALTER TABLE trading.ledger_transactions "
        "ADD CONSTRAINT fk_ledger_transactions_exchange_order FOREIGN KEY(order_id) "
        "REFERENCES trading.exchange_orders (id)"
    )
    op.execute(
        "ALTER TABLE trading.ledger_transactions "
        "ADD CONSTRAINT fk_ledger_transactions_exchange_trade FOREIGN KEY(trade_id) "
        "REFERENCES trading.exchange_trades (id)"
    )
    op.execute(
        "ALTER TABLE trading.exchange_orders "
        "ADD CONSTRAINT fk_exchange_orders_attempt FOREIGN KEY(attempt_id) "
        "REFERENCES trading.exchange_order_attempts (id) DEFERRABLE INITIALLY DEFERRED"
    )


def _remove_lineage() -> None:
    op.execute(
        "ALTER TABLE trading.exchange_orders "
        "DROP CONSTRAINT IF EXISTS fk_exchange_orders_attempt"
    )
    op.execute(
        "ALTER TABLE trading.ledger_transactions "
        "DROP CONSTRAINT IF EXISTS fk_ledger_transactions_exchange_trade"
    )
    op.execute(
        "ALTER TABLE trading.ledger_transactions "
        "DROP CONSTRAINT IF EXISTS fk_ledger_transactions_exchange_order"
    )
    op.execute(
        "ALTER TABLE trading.ledger_transactions "
        "DROP CONSTRAINT IF EXISTS fk_ledger_transactions_envelope"
    )
    op.execute(
        "ALTER TABLE trading.ledger_transactions "
        "DROP CONSTRAINT IF EXISTS fk_ledger_transactions_account"
    )
    for col in ("trade_id", "order_id", "envelope_id", "account_id"):
        op.execute(
            f"ALTER TABLE trading.ledger_transactions DROP COLUMN IF EXISTS {col}"
        )
    op.execute(
        "ALTER TABLE trading.position_lots "
        "DROP CONSTRAINT IF EXISTS fk_position_lots_exchange_trade"
    )
    op.execute(
        "ALTER TABLE trading.position_lots "
        "DROP CONSTRAINT IF EXISTS fk_position_lots_exchange_order"
    )
    op.execute(
        "ALTER TABLE trading.position_lots "
        "DROP CONSTRAINT IF EXISTS fk_position_lots_account"
    )
    # 恢复 0031 的 NOT NULL（若有 NULL 行则 fail-closed，符合回滚保护）。
    op.execute(
        "ALTER TABLE trading.position_lots ALTER COLUMN execution_id SET NOT NULL"
    )
    for col in ("trade_id", "order_id", "account_id"):
        op.execute(
            f"ALTER TABLE trading.position_lots DROP COLUMN IF EXISTS {col}"
        )
    op.execute(
        "ALTER TABLE trading.positions "
        "DROP CONSTRAINT IF EXISTS fk_positions_exchange_order"
    )
    op.execute(
        "ALTER TABLE trading.positions "
        "DROP CONSTRAINT IF EXISTS fk_positions_envelope"
    )
    op.execute(
        "ALTER TABLE trading.positions "
        "DROP CONSTRAINT IF EXISTS fk_positions_account"
    )
    for col in ("order_id", "envelope_id", "account_id"):
        op.execute(
            f"ALTER TABLE trading.positions DROP COLUMN IF EXISTS {col}"
        )
    op.execute(
        "ALTER TABLE trading.executions "
        "DROP CONSTRAINT IF EXISTS uq_executions_outer_lineage"
    )
    op.execute(
        "ALTER TABLE trading.executions "
        "DROP CONSTRAINT IF EXISTS fk_executions_exchange_trade"
    )
    op.execute(
        "ALTER TABLE trading.executions "
        "DROP CONSTRAINT IF EXISTS fk_executions_exchange_order"
    )
    op.execute(
        "ALTER TABLE trading.executions "
        "DROP CONSTRAINT IF EXISTS fk_executions_envelope"
    )
    op.execute(
        "ALTER TABLE trading.executions "
        "DROP CONSTRAINT IF EXISTS fk_executions_account"
    )
    for col in ("trade_id", "order_id", "envelope_id", "account_id"):
        op.execute(
            f"ALTER TABLE trading.executions DROP COLUMN IF EXISTS {col}"
        )
    # Restore the exact b1000050 schema; this remains fail-closed if an unsafe NULL exists.
    op.execute(
        "ALTER TABLE trading.executions ALTER COLUMN quote_checkpoint_id SET NOT NULL"
    )


def _create_guards() -> None:
    for table in _NEW_TABLES:
        if table.append_only:
            op.execute(
                f"CREATE TRIGGER trg_{table.name}_immutable "
                f"BEFORE UPDATE OR DELETE ON {TRADING_SCHEMA}.{table.name} "
                "FOR EACH ROW EXECUTE FUNCTION trading.v2_reject_immutable_row()"
            )
    # exchange_order_attempts：一次 send 一次 result。
    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_order_attempt() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_order_attempt_immutable' USING ERRCODE='55000';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.result <> 'SUBMITTED' OR NEW.state_event_id IS NULL THEN
            RAISE EXCEPTION 'v2_order_attempt_initial_state_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF (to_jsonb(NEW) - 'result') IS DISTINCT FROM (to_jsonb(OLD) - 'result') THEN
        RAISE EXCEPTION 'v2_order_attempt_payload_immutable' USING ERRCODE='55000';
    END IF;
    IF OLD.result <> 'SUBMITTED' THEN
        RAISE EXCEPTION 'v2_order_attempt_already_terminal' USING ERRCODE='23514';
    END IF;
    IF NEW.result = 'SUBMITTED'
       OR NEW.result NOT IN ('ACK','PARTIAL','FILLED','CANCELLED','REJECTED','UNKNOWN','FAILED') THEN
        RAISE EXCEPTION 'v2_order_attempt_transition_invalid' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_exchange_order_attempts_lifecycle "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.exchange_order_attempts "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_order_attempt()"
    )
    # exchange_orders：state-machine CAS projection。
    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_exchange_order() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_exchange_order_immutable' USING ERRCODE='55000';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'OPEN' OR NEW.filled_size <> 0
           OR NEW.attempt_id IS NOT NULL OR NEW.external_order_id IS NOT NULL THEN
            RAISE EXCEPTION 'v2_exchange_order_initial_state_invalid' USING ERRCODE='23514';
        END IF;
        IF NEW.filled_size < 0 OR NEW.filled_size > NEW.size THEN
            RAISE EXCEPTION 'v2_exchange_order_filled_range_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF (to_jsonb(NEW) - 'status' - 'filled_size' - 'updated_at' - 'external_order_id' - 'attempt_id') IS DISTINCT FROM
       (to_jsonb(OLD) - 'status' - 'filled_size' - 'updated_at' - 'external_order_id' - 'attempt_id') THEN
        RAISE EXCEPTION 'v2_exchange_order_payload_immutable' USING ERRCODE='55000';
    END IF;
    IF NEW.status = OLD.status THEN
        -- 仅允许一次性回填 attempt/external identity；禁止 terminal 或经济量无事件变化。
        IF OLD.status IN ('FILLED','CANCELLED','REJECTED','RECONCILED')
           OR NEW.filled_size <> OLD.filled_size
           OR (OLD.attempt_id IS NOT NULL AND NEW.attempt_id IS DISTINCT FROM OLD.attempt_id)
           OR (OLD.external_order_id IS NOT NULL
               AND NEW.external_order_id IS DISTINCT FROM OLD.external_order_id) THEN
            RAISE EXCEPTION 'v2_exchange_order_same_state_mutation_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF NOT (
        (OLD.status = 'OPEN' AND NEW.status IN ('ACK','PARTIAL','FILLED','CANCELLED','REJECTED','UNKNOWN'))
        OR (OLD.status = 'ACK' AND NEW.status IN ('PARTIAL','FILLED','CANCELLED','UNKNOWN'))
        OR (OLD.status = 'PARTIAL' AND NEW.status IN ('FILLED','CANCELLED','UNKNOWN'))
        OR (OLD.status = 'UNKNOWN' AND NEW.status = 'RECONCILED')
    ) THEN
        RAISE EXCEPTION 'v2_exchange_order_transition_invalid' USING ERRCODE='23514';
    END IF;
    IF NEW.filled_size < OLD.filled_size OR NEW.filled_size > NEW.size THEN
        RAISE EXCEPTION 'v2_exchange_order_filled_regression' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_exchange_orders_lifecycle "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.exchange_orders "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_exchange_order()"
    )
    # execution_authorization_envelopes 生命周期。
    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_envelope() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_envelope_immutable' USING ERRCODE='55000';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'ACTIVE' THEN
            RAISE EXCEPTION 'v2_envelope_initial_state_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF (to_jsonb(NEW) - 'status') IS DISTINCT FROM (to_jsonb(OLD) - 'status') THEN
        RAISE EXCEPTION 'v2_envelope_payload_immutable' USING ERRCODE='55000';
    END IF;
    IF NEW.status = OLD.status
       OR NEW.status NOT IN ('USED','EXPIRED','REVOKED','SUPERSEDED')
       OR OLD.status <> 'ACTIVE' THEN
        RAISE EXCEPTION 'v2_envelope_transition_invalid' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_execution_authorization_envelopes_lifecycle "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.execution_authorization_envelopes "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_envelope()"
    )
    # account_reconciliations 状态机。
    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_reconciliation() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_reconciliation_immutable' USING ERRCODE='55000';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'RECONCILING'
           OR NEW.output_manifest_hash IS NOT NULL
           OR NEW.completed_at IS NOT NULL
           OR jsonb_typeof(NEW.rest_page_cursor) <> 'object'
           OR jsonb_typeof(NEW.unknown_queries) <> 'object'
           OR jsonb_typeof(NEW.differences) <> 'array'
           OR jsonb_array_length(NEW.differences) <> 0 THEN
            RAISE EXCEPTION 'v2_reconciliation_initial_state_invalid' USING ERRCODE='23514';
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM trading.execution_leases l
             WHERE l.account_id=NEW.account_id AND l.lease_role='EXECUTION'
               AND l.fencing_token=NEW.fencing_token
               AND l.lease_until > statement_timestamp()
        ) THEN
            RAISE EXCEPTION 'v2_reconciliation_fence_not_current' USING ERRCODE='55000';
        END IF;
        RETURN NEW;
    END IF;
    IF OLD.status IN ('COMPLETED','FAILED') THEN
        RAISE EXCEPTION 'v2_reconciliation_terminal_immutable' USING ERRCODE='55000';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM trading.execution_leases l
         WHERE l.account_id=NEW.account_id AND l.lease_role='EXECUTION'
           AND l.fencing_token=NEW.fencing_token
           AND l.lease_until > statement_timestamp()
    ) THEN
        RAISE EXCEPTION 'v2_reconciliation_fence_not_current' USING ERRCODE='55000';
    END IF;
    IF (to_jsonb(NEW) - 'rest_page_cursor' - 'rest_page_hash' - 'unknown_queries'
                     - 'output_manifest_hash' - 'differences' - 'status' - 'completed_at')
       IS DISTINCT FROM
       (to_jsonb(OLD) - 'rest_page_cursor' - 'rest_page_hash' - 'unknown_queries'
                     - 'output_manifest_hash' - 'differences' - 'status' - 'completed_at') THEN
        RAISE EXCEPTION 'v2_reconciliation_input_immutable' USING ERRCODE='55000';
    END IF;
    IF jsonb_typeof(NEW.rest_page_cursor) <> 'object'
       OR jsonb_typeof(NEW.unknown_queries) <> 'object'
       OR jsonb_typeof(NEW.differences) <> 'array' THEN
        RAISE EXCEPTION 'v2_reconciliation_evidence_shape_invalid' USING ERRCODE='23514';
    END IF;
    IF NEW.status = OLD.status THEN
        IF NEW.status <> 'RECONCILING'
           OR NEW.output_manifest_hash IS NOT NULL
           OR NEW.completed_at IS NOT NULL
           OR jsonb_array_length(NEW.differences) <> 0 THEN
            RAISE EXCEPTION 'v2_reconciliation_in_progress_shape_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF NOT (OLD.status = 'RECONCILING' AND NEW.status IN ('COMPLETED','FAILED')) THEN
        RAISE EXCEPTION 'v2_reconciliation_transition_invalid' USING ERRCODE='23514';
    END IF;
    IF NEW.status = 'COMPLETED' AND (
        NEW.completed_at IS NULL
        OR jsonb_typeof(NEW.differences) <> 'array'
        OR jsonb_array_length(NEW.differences) <> 0
        OR NEW.output_manifest_hash IS NULL
    ) THEN
        RAISE EXCEPTION 'v2_reconciliation_complete_requires_zero_diff' USING ERRCODE='23514';
    END IF;
    IF NEW.status = 'FAILED' AND NEW.completed_at IS NOT NULL THEN
        RAISE EXCEPTION 'v2_reconciliation_failed_must_not_complete' USING ERRCODE='23514';
    END IF;
    IF NEW.status = 'FAILED' AND (
        jsonb_array_length(NEW.differences) = 0
        OR NEW.output_manifest_hash IS NULL
    ) THEN
        RAISE EXCEPTION 'v2_reconciliation_failed_requires_diff' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_account_reconciliations_lifecycle "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.account_reconciliations "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_reconciliation()"
    )
    # deferred permission twin + shadow/0 + authority。
    op.execute(
        r"""
CREATE FUNCTION trading.v2_check_envelope_permission() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE acct_permission_id bigint;
        acct_release_id bigint;
        acct_status varchar;
        rel_permission_id bigint;
        rel_execution_spec_id bigint;
        rel_status varchar;
        perm_mode varchar;
        perm_status varchar;
        perm_auth_cap numeric;
BEGIN
    SELECT capital_permission_manifest_id, release_manifest_id, status
      INTO acct_permission_id, acct_release_id, acct_status
      FROM trading.pm_accounts WHERE id = NEW.account_id;
    SELECT capital_permission_manifest_id, execution_spec_version_id, status
      INTO rel_permission_id, rel_execution_spec_id, rel_status
      FROM trading.release_manifests WHERE id = NEW.release_manifest_id;
    IF acct_permission_id IS DISTINCT FROM NEW.capital_permission_manifest_id
       OR rel_permission_id IS DISTINCT FROM NEW.capital_permission_manifest_id
       OR acct_release_id IS DISTINCT FROM NEW.release_manifest_id
       OR rel_execution_spec_id IS DISTINCT FROM NEW.execution_spec_version_id
       OR acct_status IS DISTINCT FROM 'active'
       OR rel_status IS DISTINCT FROM 'active' THEN
        RAISE EXCEPTION 'v2_envelope_permission_twin_mismatch' USING ERRCODE='55000';
    END IF;
    SELECT mode, status, authorized_capital INTO perm_mode, perm_status, perm_auth_cap
      FROM trading.capital_permission_manifests WHERE id = NEW.capital_permission_manifest_id;
    IF perm_status IS DISTINCT FROM 'active'
       OR perm_mode IS DISTINCT FROM 'shadow'
       OR perm_auth_cap IS DISTINCT FROM 0 THEN
        RAISE EXCEPTION 'v2_envelope_permission_not_shadow_zero' USING ERRCODE='55000';
    END IF;
    IF NEW.authority <> 'FAKE_CONFORMANCE' THEN
        RAISE EXCEPTION 'v2_envelope_authority_invalid' USING ERRCODE='55000';
    END IF;
    IF NOT EXISTS (
        SELECT 1
          FROM trading.execution_leases l
         WHERE l.account_id = NEW.account_id
           AND l.lease_role = 'EXECUTION'
           AND l.fencing_token = NEW.fencing_token
           AND l.lease_until > statement_timestamp()
    ) THEN
        RAISE EXCEPTION 'v2_envelope_fence_not_current' USING ERRCODE='55000';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER trg_execution_envelope_permission_check "
        "AFTER INSERT OR UPDATE OF capital_permission_manifest_id, release_manifest_id, "
        "account_id, authority ON trading.execution_authorization_envelopes "
        "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
        "EXECUTE FUNCTION trading.v2_check_envelope_permission()"
    )
    # deferred intent hash bind。
    op.execute(
        r"""
CREATE FUNCTION trading.v2_check_envelope_intent_bind() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE existing_hash varchar;
BEGIN
    SELECT i.intent_hash INTO existing_hash
      FROM trading.economic_action_intents i
      JOIN trading.trade_decisions d ON d.id = i.trade_decision_id
     WHERE i.id = NEW.intent_id
       AND i.status IN ('PLANNED','COMMITTED')
       AND d.status = 'ACTION'
       AND d.release_manifest_id = NEW.release_manifest_id
       AND d.execution_spec_version_id = NEW.execution_spec_version_id
       AND d.capital_permission_manifest_id = NEW.capital_permission_manifest_id;
    IF existing_hash IS DISTINCT FROM NEW.intent_hash THEN
        RAISE EXCEPTION 'v2_envelope_intent_hash_bind_mismatch' USING ERRCODE='55000';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER trg_execution_envelope_intent_bind "
        "AFTER INSERT OR UPDATE OF intent_id, intent_hash "
        "ON trading.execution_authorization_envelopes "
        "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
        "EXECUTE FUNCTION trading.v2_check_envelope_intent_bind()"
    )
    # The order projection, persisted send attempt, submitted event, envelope and fence are one
    # account-bound lineage.  Read the final projection row so insert-then-bind in one transaction
    # remains valid under a deferred constraint trigger.
    op.execute(
        r"""
CREATE FUNCTION trading.v2_check_order_attempt_lineage() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM trading.exchange_orders o
          JOIN trading.exchange_order_attempts a ON a.id = o.attempt_id
          JOIN trading.execution_authorization_envelopes e ON e.id = a.envelope_id
          JOIN trading.order_state_events ev ON ev.id = a.state_event_id
         WHERE o.id = NEW.id
           AND e.account_id = o.account_id
           AND ev.order_id = o.id
           AND ev.event_type = 'SUBMITTED'
           AND ev.transition_from = 'INTENT'
           AND ev.transition_to = 'SUBMITTED'
           AND a.fencing_token = e.fencing_token
           AND ev.fence_token = e.fencing_token
    ) THEN
        RAISE EXCEPTION 'v2_order_attempt_lineage_invalid' USING ERRCODE='55000';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER trg_exchange_orders_attempt_lineage "
        "AFTER INSERT OR UPDATE OF attempt_id, account_id ON trading.exchange_orders "
        "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
        "EXECUTE FUNCTION trading.v2_check_order_attempt_lineage()"
    )


def _relax_execution_identity_guard() -> None:
    """放宽 0031 的 executions 身份链 trigger：允许真实 CLOB fill 行。

    真实 fill 有 account/envelope/order/trade lineage + NULL quote_checkpoint +
    ``exec-<account_id>`` namespace（无 shadow quote binding 链）。其余仍走 0031 原校验。
    """
    op.execute(
        "DROP TRIGGER IF EXISTS trg_executions_identity ON trading.executions"
    )
    op.execute(
        r"""
CREATE OR REPLACE FUNCTION trading.v2_validate_execution_identity() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    -- WP-05 Checkpoint C：真实 CLOB fill（order/trade lineage + NULL checkpoint + exec- namespace）。
    IF NEW.account_id IS NOT NULL OR NEW.envelope_id IS NOT NULL
       OR NEW.order_id IS NOT NULL OR NEW.trade_id IS NOT NULL THEN
        IF NEW.account_id IS NULL OR NEW.envelope_id IS NULL
           OR NEW.order_id IS NULL OR NEW.trade_id IS NULL
           OR NEW.quote_checkpoint_id IS NOT NULL
           OR NEW.portfolio_namespace <> 'exec-' || NEW.account_id::text
           OR NOT EXISTS (
                SELECT 1
                  FROM trading.execution_authorization_envelopes env
                  JOIN trading.exchange_order_attempts att ON att.envelope_id = env.id
                  JOIN trading.exchange_orders ord ON ord.attempt_id = att.id
                  JOIN trading.exchange_trades tr
                    ON tr.order_id = ord.id AND tr.account_id = ord.account_id
                  JOIN trading.pm_tokens tok
                    ON tok.id = NEW.token_id AND tok.token_id = ord.token_id
                 WHERE env.id = NEW.envelope_id
                   AND env.account_id = NEW.account_id
                   AND env.intent_id = NEW.economic_action_intent_id
                   AND ord.id = NEW.order_id AND ord.account_id = NEW.account_id
                   AND tr.id = NEW.trade_id AND tr.side = ord.side
                   AND tr.size = NEW.quantity
           ) THEN
            RAISE EXCEPTION 'v2_execution_outer_lineage_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF NOT EXISTS (
        SELECT 1
          FROM trading.economic_action_intents intent
          JOIN trading.action_sets aset ON aset.id = intent.action_set_id
          JOIN trading.action_set_legs leg ON leg.action_set_id = aset.id
          JOIN trading.trade_decisions td ON td.id = intent.trade_decision_id
          JOIN trading.pm_tokens token ON token.id = leg.token_id
          JOIN trading.pm_quote_bindings quote
            ON quote.trade_decision_id = td.id
           AND quote.token_id = token.token_id
           AND quote.checkpoint_id = NEW.quote_checkpoint_id
          JOIN trading.release_manifests rm ON rm.id = td.release_manifest_id
          JOIN trading.capital_permission_manifests cp
            ON cp.id = td.capital_permission_manifest_id
         WHERE intent.id = NEW.economic_action_intent_id
           AND intent.status IN ('PLANNED','COMMITTED')
           AND aset.id = intent.action_set_id
           AND aset.trade_decision_id = td.id AND aset.disposition = 'ACTION'
           AND leg.id = NEW.action_set_leg_id
           AND leg.contract_spec_id = NEW.contract_spec_id
           AND leg.token_id = NEW.token_id
           AND leg.leg_role = NEW.fill_role
           AND leg.quantity = NEW.quantity
           AND td.status = 'ACTION' AND td.selected_action_type <> 'HOLD'
           AND NEW.portfolio_namespace = 'shadow-' || td.experiment_variant
           AND quote.stale_at > NEW.created_at
           AND rm.status = 'active'
           AND rm.capital_permission_manifest_id = cp.id
           AND cp.status = 'active' AND cp.mode = 'shadow'
           AND cp.authorized_capital = 0 AND NOT cp.kill_switch
    ) THEN
        RAISE EXCEPTION 'v2_execution_identity_chain_invalid' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_executions_identity "
        "BEFORE INSERT ON trading.executions "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_validate_execution_identity()"
    )


def _create_outer_lineage_guards() -> None:
    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_outer_lineage_immutable() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    IF TG_TABLE_NAME = 'executions' AND (
        NEW.account_id IS DISTINCT FROM OLD.account_id
        OR NEW.envelope_id IS DISTINCT FROM OLD.envelope_id
        OR NEW.order_id IS DISTINCT FROM OLD.order_id
        OR NEW.trade_id IS DISTINCT FROM OLD.trade_id
    ) THEN
        RAISE EXCEPTION 'v2_execution_outer_lineage_immutable' USING ERRCODE='55000';
    ELSIF TG_TABLE_NAME = 'positions' AND (
        NEW.account_id IS DISTINCT FROM OLD.account_id
        OR NEW.envelope_id IS DISTINCT FROM OLD.envelope_id
        OR NEW.order_id IS DISTINCT FROM OLD.order_id
    ) THEN
        RAISE EXCEPTION 'v2_position_outer_lineage_immutable' USING ERRCODE='55000';
    ELSIF TG_TABLE_NAME = 'ledger_transactions' AND (
        NEW.account_id IS DISTINCT FROM OLD.account_id
        OR NEW.envelope_id IS DISTINCT FROM OLD.envelope_id
        OR NEW.order_id IS DISTINCT FROM OLD.order_id
        OR NEW.trade_id IS DISTINCT FROM OLD.trade_id
    ) THEN
        RAISE EXCEPTION 'v2_ledger_outer_lineage_immutable' USING ERRCODE='55000';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        r"""
CREATE FUNCTION trading.v2_check_real_fill_lineage() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    IF TG_TABLE_NAME = 'ledger_transactions' THEN
        IF NEW.account_id IS NULL AND NEW.envelope_id IS NULL
           AND NEW.order_id IS NULL AND NEW.trade_id IS NULL THEN
            RETURN NEW;
        END IF;
        IF NEW.account_id IS NULL OR NEW.envelope_id IS NULL
           OR NEW.order_id IS NULL OR NEW.trade_id IS NULL
           OR NEW.portfolio_namespace <> 'exec-' || NEW.account_id::text
           OR NOT EXISTS (
                SELECT 1 FROM trading.execution_authorization_envelopes e
                JOIN trading.exchange_order_attempts a ON a.envelope_id=e.id
                JOIN trading.exchange_orders o ON o.attempt_id=a.id
                JOIN trading.exchange_trades t
                  ON t.order_id=o.id AND t.account_id=o.account_id
                JOIN trading.economic_action_intents i ON i.id=e.intent_id
                WHERE e.id=NEW.envelope_id AND e.account_id=NEW.account_id
                  AND o.id=NEW.order_id AND t.id=NEW.trade_id
                  AND i.trade_decision_id IS NOT DISTINCT FROM NEW.trade_decision_id
                  AND (NEW.execution_id IS NULL OR EXISTS (
                      SELECT 1 FROM trading.executions x
                       WHERE x.id=NEW.execution_id AND x.account_id=NEW.account_id
                         AND x.envelope_id=NEW.envelope_id AND x.order_id=NEW.order_id
                         AND x.trade_id=NEW.trade_id
                  ))
           ) THEN
            RAISE EXCEPTION 'v2_ledger_outer_lineage_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF TG_TABLE_NAME = 'position_lots' THEN
        IF NEW.execution_id IS NOT NULL AND NEW.account_id IS NULL
           AND NEW.order_id IS NULL AND NEW.trade_id IS NULL THEN
            RETURN NEW;
        END IF;
        IF NEW.account_id IS NULL
           OR NEW.order_id IS NULL OR NEW.trade_id IS NULL
           OR NEW.portfolio_namespace <> 'exec-' || NEW.account_id::text
           OR NOT EXISTS (
                SELECT 1 FROM trading.exchange_orders o
                JOIN trading.exchange_trades t
                  ON t.order_id=o.id AND t.account_id=o.account_id
                WHERE o.id=NEW.order_id AND o.account_id=NEW.account_id
                  AND t.id=NEW.trade_id
                  AND (NEW.execution_id IS NULL OR EXISTS (
                      SELECT 1 FROM trading.executions x
                       WHERE x.id=NEW.execution_id AND x.account_id=NEW.account_id
                         AND x.order_id=NEW.order_id AND x.trade_id=NEW.trade_id
                  ))
           ) THEN
            RAISE EXCEPTION 'v2_position_lot_outer_lineage_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF TG_TABLE_NAME = 'positions' THEN
        IF NEW.account_id IS NULL AND NEW.envelope_id IS NULL AND NEW.order_id IS NULL THEN
            RETURN NEW;
        END IF;
        IF NEW.account_id IS NULL OR NEW.envelope_id IS NULL OR NEW.order_id IS NULL
           OR NEW.portfolio_namespace <> 'exec-' || NEW.account_id::text
           OR NOT EXISTS (
                SELECT 1 FROM trading.execution_authorization_envelopes e
                JOIN trading.exchange_order_attempts a ON a.envelope_id=e.id
                JOIN trading.exchange_orders o ON o.attempt_id=a.id
                WHERE e.id=NEW.envelope_id AND e.account_id=NEW.account_id
                  AND o.id=NEW.order_id AND o.account_id=NEW.account_id
           ) THEN
            RAISE EXCEPTION 'v2_position_outer_lineage_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_ledger_transactions_outer_lineage "
        "BEFORE INSERT OR UPDATE OF account_id, envelope_id, order_id, trade_id "
        "ON trading.ledger_transactions FOR EACH ROW "
        "EXECUTE FUNCTION trading.v2_check_real_fill_lineage()"
    )
    op.execute(
        "CREATE TRIGGER trg_position_lots_outer_lineage "
        "BEFORE INSERT OR UPDATE OF account_id, order_id, trade_id "
        "ON trading.position_lots FOR EACH ROW "
        "EXECUTE FUNCTION trading.v2_check_real_fill_lineage()"
    )
    op.execute(
        "CREATE TRIGGER trg_positions_outer_lineage "
        "BEFORE INSERT OR UPDATE OF account_id, envelope_id, order_id "
        "ON trading.positions FOR EACH ROW "
        "EXECUTE FUNCTION trading.v2_check_real_fill_lineage()"
    )
    for table, columns in (
        ("executions", "account_id, envelope_id, order_id, trade_id"),
        ("positions", "account_id, envelope_id, order_id"),
        ("ledger_transactions", "account_id, envelope_id, order_id, trade_id"),
    ):
        op.execute(
            f"CREATE TRIGGER trg_{table}_outer_lineage_immutable "
            f"BEFORE UPDATE OF {columns} ON trading.{table} FOR EACH ROW "
            "EXECUTE FUNCTION trading.v2_guard_outer_lineage_immutable()"
        )


def _drop_outer_lineage_guards() -> None:
    for table in ("executions", "positions", "ledger_transactions"):
        op.execute(
            f"DROP TRIGGER IF EXISTS trg_{table}_outer_lineage_immutable "
            f"ON trading.{table}"
        )
    op.execute(
        "DROP TRIGGER IF EXISTS trg_positions_outer_lineage ON trading.positions"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS trg_ledger_transactions_outer_lineage "
        "ON trading.ledger_transactions"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS trg_position_lots_outer_lineage "
        "ON trading.position_lots"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_check_real_fill_lineage()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_outer_lineage_immutable()")


def _restore_execution_identity_guard() -> None:
    """降级时恢复 0031 原样 trigger。"""
    op.execute(
        "DROP TRIGGER IF EXISTS trg_executions_identity ON trading.executions"
    )
    op.execute(
        r"""
CREATE OR REPLACE FUNCTION trading.v2_validate_execution_identity() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM trading.economic_action_intents intent
          JOIN trading.action_sets aset ON aset.id = intent.action_set_id
          JOIN trading.action_set_legs leg ON leg.action_set_id = aset.id
          JOIN trading.trade_decisions td ON td.id = intent.trade_decision_id
          JOIN trading.pm_tokens token ON token.id = leg.token_id
          JOIN trading.pm_quote_bindings quote
            ON quote.trade_decision_id = td.id
           AND quote.token_id = token.token_id
           AND quote.checkpoint_id = NEW.quote_checkpoint_id
          JOIN trading.release_manifests rm ON rm.id = td.release_manifest_id
          JOIN trading.capital_permission_manifests cp
            ON cp.id = td.capital_permission_manifest_id
         WHERE intent.id = NEW.economic_action_intent_id
           AND intent.status IN ('PLANNED','COMMITTED')
           AND aset.id = intent.action_set_id
           AND aset.trade_decision_id = td.id AND aset.disposition = 'ACTION'
           AND leg.id = NEW.action_set_leg_id
           AND leg.contract_spec_id = NEW.contract_spec_id
           AND leg.token_id = NEW.token_id
           AND leg.leg_role = NEW.fill_role
           AND leg.quantity = NEW.quantity
           AND td.status = 'ACTION' AND td.selected_action_type <> 'HOLD'
           AND NEW.portfolio_namespace = 'shadow-' || td.experiment_variant
           AND quote.stale_at > NEW.created_at
           AND rm.status = 'active'
           AND rm.capital_permission_manifest_id = cp.id
           AND cp.status = 'active' AND cp.mode = 'shadow'
           AND cp.authorized_capital = 0 AND NOT cp.kill_switch
    ) THEN
        RAISE EXCEPTION 'v2_execution_identity_chain_invalid' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_executions_identity "
        "BEFORE INSERT ON trading.executions "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_validate_execution_identity()"
    )


def _drop_guards() -> None:
    op.execute(
        "DROP TRIGGER IF EXISTS trg_exchange_orders_attempt_lineage "
        "ON trading.exchange_orders"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_check_order_attempt_lineage()")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_execution_envelope_intent_bind "
        "ON trading.execution_authorization_envelopes"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_check_envelope_intent_bind()")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_execution_envelope_permission_check "
        "ON trading.execution_authorization_envelopes"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_check_envelope_permission()")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_account_reconciliations_lifecycle "
        "ON trading.account_reconciliations"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_reconciliation()")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_execution_authorization_envelopes_lifecycle "
        "ON trading.execution_authorization_envelopes"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_envelope()")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_exchange_orders_lifecycle "
        "ON trading.exchange_orders"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_exchange_order()")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_exchange_order_attempts_lifecycle "
        "ON trading.exchange_order_attempts"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_order_attempt()")
    for table in reversed(_NEW_TABLES):
        if table.append_only:
            op.execute(
                f"DROP TRIGGER IF EXISTS trg_{table.name}_immutable "
                f"ON {TRADING_SCHEMA}.{table.name}"
            )


def upgrade() -> None:
    # 建表顺序满足 FK 依赖：exchange_order_attempts 引用 envelopes + order_state_events；
    # exchange_orders.attempt_id 为普通列（避免 order→attempt→event→order 环形 FK，
    # 否则 alembic autogenerate 无法排序且 downgrade 需 CASCADE）。order 投影由 Logic 维护。
    for name in (
        "execution_authorization_envelopes",
        "exchange_orders",
        "order_state_events",
        "exchange_order_attempts",
    ):
        table = next(t for t in _NEW_TABLES if t.name == name)
        op.execute(table.create_sql)
        for statement in table.index_sql:
            op.execute(statement)
    for name in (
        "exchange_trades",
        "account_reconciliations",
        "workflow_events",
        "external_call_attempts",
        "alert_events",
    ):
        table = next(t for t in _NEW_TABLES if t.name == name)
        op.execute(table.create_sql)
        for statement in table.index_sql:
            op.execute(statement)
    _create_guards()
    _relax_execution_identity_guard()
    _add_lineage()
    _create_outer_lineage_guards()


def downgrade() -> None:
    _assert_downgrade_safe()
    _drop_outer_lineage_guards()
    _drop_guards()
    _restore_execution_identity_guard()
    _remove_lineage()
    for name in (
        "alert_events",
        "external_call_attempts",
        "workflow_events",
        "account_reconciliations",
        "exchange_trades",
        "exchange_order_attempts",
        "order_state_events",
        "exchange_orders",
        "execution_authorization_envelopes",
    ):
        op.execute(f"DROP TABLE {TRADING_SCHEMA}.{name}")
