"""create p2 shadow ledger

Revision ID: b1000031
Revises: b1000030
Create Date: 2026-08-11 15:00:00

v2_0031 —— Minimum Portfolio、Shadow Execution、Ledger（WP-03 Checkpoint C）。

- ``upgrade``：
  - 6 张表：executions、positions、position_lots、ledger_transactions、ledger_postings、
    operating_cost_entries。
  - deferred constraint trigger ``v2_check_ledger_balance``：POSTED 前每个 (asset_type, asset_key)
    的 signed postings 合计为 0 且至少两条。
  - execution lifecycle guard：``PENDING→PARTIAL|FILLED|REJECTED|FAILED``，四结果 terminal。
  - ledger_transactions：POSTED 后禁 UPDATE/DELETE（append-only guard 复用 reject）。
- ``downgrade``：逆序删 6 表 + guard/trigger；未知对象 fail-closed。
"""
from dataclasses import dataclass
from typing import Sequence, Union

from alembic import op

TRADING_SCHEMA = "trading"

# revision identifiers, used by Alembic.
revision: str = "b1000031"
down_revision: Union[str, Sequence[str], None] = "b1000030"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


@dataclass(frozen=True)
class _FrozenTableSpec:
    name: str
    create_sql: str
    index_sql: tuple[str, ...] = ()
    append_only: bool = True


_SHADOW_TABLES = (
    _FrozenTableSpec(
        name='executions',
        create_sql='\nCREATE TABLE trading.executions (\n\texecution_key TEXT COLLATE "C" NOT NULL, \n\teconomic_action_intent_id BIGINT NOT NULL, \n\taction_set_leg_id BIGINT NOT NULL, \n\tcontract_spec_id BIGINT NOT NULL, \n\ttoken_id BIGINT NOT NULL, \n\tfill_role VARCHAR(16) NOT NULL, \n\tquantity NUMERIC(38, 0) NOT NULL, \n\tfilled_quantity NUMERIC(38, 0) DEFAULT \'0\' NOT NULL, \n\tvwap NUMERIC(38, 0), \n\tfee NUMERIC(38, 0) DEFAULT \'0\' NOT NULL, \n\tstatus VARCHAR(16) DEFAULT \'PENDING\' NOT NULL, \n\tunfilled_reason VARCHAR(128), \n\tquote_checkpoint_id BIGINT, \n\tportfolio_namespace TEXT COLLATE "C" NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_executions_key UNIQUE (execution_key), \n\tCONSTRAINT ck_executions_status_known CHECK (status IN (\'PENDING\',\'PARTIAL\',\'FILLED\',\'REJECTED\',\'FAILED\')), \n\tCONSTRAINT ck_executions_filled_pair CHECK ((status IN (\'PENDING\',\'REJECTED\',\'FAILED\')) = (filled_quantity = 0)), \n\tCONSTRAINT ck_executions_quantity_positive CHECK (quantity > 0), \n\tCONSTRAINT ck_executions_filled_range CHECK (filled_quantity >= 0 AND filled_quantity <= quantity), \n\tCONSTRAINT ck_executions_vwap_positive CHECK (vwap IS NULL OR vwap > 0), \n\tCONSTRAINT ck_executions_fee_nonneg CHECK (fee >= 0), \n\tCONSTRAINT ck_executions_unfilled_pair CHECK (unfilled_reason IS NOT NULL = (filled_quantity < quantity AND status <> \'PENDING\')), \n\tCONSTRAINT fk_executions_intent FOREIGN KEY(economic_action_intent_id) REFERENCES trading.economic_action_intents (id), \n\tCONSTRAINT fk_executions_leg FOREIGN KEY(action_set_leg_id) REFERENCES trading.action_set_legs (id), \n\tCONSTRAINT fk_executions_spec FOREIGN KEY(contract_spec_id) REFERENCES trading.contract_specs (id), \n\tCONSTRAINT fk_executions_token FOREIGN KEY(token_id) REFERENCES trading.pm_tokens (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_executions_intent ON trading.executions (economic_action_intent_id)',),
        append_only=False,
    ),
    _FrozenTableSpec(
        name='positions',
        create_sql='\nCREATE TABLE trading.positions (\n\tportfolio_namespace TEXT COLLATE "C" NOT NULL, \n\tcontract_spec_id BIGINT NOT NULL, \n\ttoken_id BIGINT NOT NULL, \n\tmarket_id BIGINT, \n\tcomponent_id BIGINT, \n\tquantity NUMERIC(38, 0) DEFAULT \'0\' NOT NULL, \n\tcost_basis NUMERIC(38, 0) DEFAULT \'0\' NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tversion INTEGER DEFAULT 1 NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_positions_namespace_spec_token UNIQUE (portfolio_namespace, contract_spec_id, token_id), \n\tCONSTRAINT ck_positions_quantity_nonneg CHECK (quantity >= 0), \n\tCONSTRAINT ck_positions_cost_basis_nonneg CHECK (cost_basis >= 0), \n\tCONSTRAINT fk_positions_spec FOREIGN KEY(contract_spec_id) REFERENCES trading.contract_specs (id), \n\tCONSTRAINT fk_positions_token FOREIGN KEY(token_id) REFERENCES trading.pm_tokens (id), \n\tCONSTRAINT fk_positions_market FOREIGN KEY(market_id) REFERENCES trading.pm_markets (id), \n\tCONSTRAINT fk_positions_component FOREIGN KEY(component_id) REFERENCES trading.forecast_components (id)\n)\n\n',
        append_only=False,
    ),
    _FrozenTableSpec(
        name='position_lots',
        create_sql='\nCREATE TABLE trading.position_lots (\n\texecution_id BIGINT NOT NULL, \n\tportfolio_namespace TEXT COLLATE "C" NOT NULL, \n\tcontract_spec_id BIGINT NOT NULL, \n\ttoken_id BIGINT NOT NULL, \n\tquantity NUMERIC(38, 0) NOT NULL, \n\tentry_vwap NUMERIC(38, 0), \n\tfill_role VARCHAR(16) NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_position_lots_execution UNIQUE (execution_id), \n\tCONSTRAINT ck_position_lots_quantity_positive CHECK (quantity > 0), \n\tCONSTRAINT ck_position_lots_vwap_positive CHECK (entry_vwap IS NULL OR entry_vwap > 0), \n\tCONSTRAINT fk_position_lots_execution FOREIGN KEY(execution_id) REFERENCES trading.executions (id), \n\tCONSTRAINT fk_position_lots_spec FOREIGN KEY(contract_spec_id) REFERENCES trading.contract_specs (id), \n\tCONSTRAINT fk_position_lots_token FOREIGN KEY(token_id) REFERENCES trading.pm_tokens (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_position_lots_position ON trading.position_lots (portfolio_namespace, contract_spec_id, token_id)',),
    ),
    _FrozenTableSpec(
        name='ledger_transactions',
        create_sql='\nCREATE TABLE trading.ledger_transactions (\n\ttransaction_key TEXT COLLATE "C" NOT NULL, \n\tstatus VARCHAR(16) DEFAULT \'PENDING\' NOT NULL, \n\tkind VARCHAR(32) NOT NULL, \n\ttrade_decision_id BIGINT, \n\texecution_id BIGINT, \n\tportfolio_namespace TEXT COLLATE "C" NOT NULL, \n\tposted_at TIMESTAMP WITH TIME ZONE, \n\treference_transaction_id BIGINT, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_ledger_transactions_key UNIQUE (transaction_key), \n\tCONSTRAINT ck_ledger_transactions_status_known CHECK (status IN (\'PENDING\',\'POSTED\')), \n\tCONSTRAINT ck_ledger_transactions_posted_pair CHECK (posted_at IS NOT NULL = (status = \'POSTED\')), \n\tCONSTRAINT ck_ledger_transactions_kind_known CHECK (kind IN (\'FILL\',\'REVERSAL\',\'SETTLEMENT\',\'OPERATING_COST\')), \n\tCONSTRAINT fk_ledger_transactions_decision FOREIGN KEY(trade_decision_id) REFERENCES trading.trade_decisions (id), \n\tCONSTRAINT fk_ledger_transactions_execution FOREIGN KEY(execution_id) REFERENCES trading.executions (id), \n\tCONSTRAINT fk_ledger_transactions_reversal_ref FOREIGN KEY(reference_transaction_id) REFERENCES trading.ledger_transactions (id)\n)\n\n',
        index_sql=(
            'CREATE INDEX ix_ledger_transactions_decision ON trading.ledger_transactions (trade_decision_id)',
            'CREATE INDEX ix_ledger_transactions_execution ON trading.ledger_transactions (execution_id)',
        ),
        append_only=False,
    ),
    _FrozenTableSpec(
        name='ledger_postings',
        create_sql='\nCREATE TABLE trading.ledger_postings (\n\ttransaction_id BIGINT NOT NULL, \n\tposting_no INTEGER NOT NULL, \n\tasset_type VARCHAR(16) NOT NULL, \n\tasset_key TEXT COLLATE "C" NOT NULL, \n\tamount NUMERIC(38, 0) NOT NULL, \n\tcounterparty TEXT COLLATE "C" NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_ledger_postings_tx_no UNIQUE (transaction_id, posting_no), \n\tCONSTRAINT ck_ledger_postings_asset_type_known CHECK (asset_type IN (\'CASH\',\'TOKEN\')), \n\tCONSTRAINT ck_ledger_postings_amount_nonzero CHECK (amount <> 0), \n\tCONSTRAINT ck_ledger_postings_no_nonneg CHECK (posting_no >= 0), \n\tCONSTRAINT fk_ledger_postings_transaction FOREIGN KEY(transaction_id) REFERENCES trading.ledger_transactions (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_ledger_postings_asset ON trading.ledger_postings (asset_type, asset_key)',),
    ),
    _FrozenTableSpec(
        name='operating_cost_entries',
        create_sql='\nCREATE TABLE trading.operating_cost_entries (\n\tcost_key TEXT COLLATE "C" NOT NULL, \n\tcost_kind VARCHAR(32) NOT NULL, \n\tamount NUMERIC(38, 0) NOT NULL, \n\trelease_manifest_id BIGINT, \n\tepisode_id BIGINT, \n\ttrade_decision_id BIGINT, \n\tperiod_start TIMESTAMP WITH TIME ZONE, \n\tperiod_end TIMESTAMP WITH TIME ZONE, \n\tallocation_policy JSONB NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_operating_cost_entries_key UNIQUE (cost_key), \n\tCONSTRAINT ck_operating_cost_entries_kind_known CHECK (cost_kind IN (\'DATA\',\'LLM\',\'SEARCH\',\'INFRASTRUCTURE\',\'HUMAN\',\'OPERATIONAL_LOSS\')), \n\tCONSTRAINT ck_operating_cost_entries_amount_nonneg CHECK (amount >= 0), \n\tCONSTRAINT ck_operating_cost_entries_allocation_object CHECK (jsonb_typeof(allocation_policy) = \'object\'), \n\tCONSTRAINT fk_operating_cost_entries_release FOREIGN KEY(release_manifest_id) REFERENCES trading.release_manifests (id), \n\tCONSTRAINT fk_operating_cost_entries_episode FOREIGN KEY(episode_id) REFERENCES trading.forecast_episodes (id), \n\tCONSTRAINT fk_operating_cost_entries_decision FOREIGN KEY(trade_decision_id) REFERENCES trading.trade_decisions (id)\n)\n\n',
        index_sql=(),
    ),
)

_PRE_0031_RELATIONS = (
    "artifact_objects", "artifact_lineage_edges", "archive_manifests",
    "retention_manifests", "runtime_config_versions", "strategy_objective_contracts",
    "strategy_versions", "execution_spec_versions", "capital_permission_manifests",
    "model_role_bindings", "release_manifests", "policy_type_scopes", "policy_freezes",
    "secret_vault_entries", "secret_vault_versions", "secret_access_events",
    "idempotency_claims", "transactional_outbox", "outbox_delivery_history",
    "job_completions", "pm_universe_frames", "pm_universe_frame_pages", "pm_events",
    "pm_markets", "pm_market_versions", "pm_tokens", "pm_token_versions",
    "pm_market_lifecycle_events", "pm_market_current", "pm_connection_epochs",
    "pm_source_event_batches", "pm_source_event_index", "pm_book_checkpoints",
    "pm_book_levels", "pm_book_current", "pm_quote_bindings", "contract_snapshots",
    "contract_specs", "payout_functions", "forecast_components", "world_schema_versions",
    "forecast_component_versions", "forecast_component_contract_specs",
    "portfolio_dependency_edges", "evaluation_cohorts", "universe_memberships",
    "screening_episodes", "audit_samples", "decision_opportunities",
    "decision_opportunity_markets", "episode_memberships", "forecast_episodes",
    "episode_contract_specs", "information_snapshots", "information_snapshot_items",
    "gate_decisions", "priors", "evidence_coverage_policies", "evidence_revisions",
    "evidence_bundles", "evidence_bundle_items", "forecast_input_manifests",
    "forecast_submissions", "payout_projections", "coherence_checks",
    "forecast_challenges", "forecast_leases", "ai_invocations", "ai_tool_calls",
    "ai_validation_results", "market_relative_decisions", "discrepancy_reviews",
    "trade_decisions", "action_candidates", "resolution_cashflows", "action_sets",
    "action_set_legs", "underwriting_plans", "economic_action_intents",
)


def _assert_downgrade_safe() -> None:
    allowed = ", ".join(
        f"'{name}'" for name in (*_PRE_0031_RELATIONS, *(t.name for t in _SHADOW_TABLES))
    )
    op.execute(
        f"""
DO $v2_wp03_ledger_preflight$
DECLARE unknown_objects text;
BEGIN
    SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
      INTO unknown_objects
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'trading'
       AND c.relkind IN ('r','p','v','m','f')
       AND c.relname NOT IN ({allowed})
       AND NOT EXISTS (
           SELECT 1 FROM pg_inherits i
           JOIN pg_class p ON p.oid = i.inhparent
           JOIN pg_namespace pn ON pn.oid = p.relnamespace
           WHERE i.inhrelid = c.oid AND pn.nspname = 'trading'
             AND ((p.relname = 'outbox_delivery_history'
                   AND c.relname ~ '^outbox_delivery_history_[0-9]{{6}}$')
               OR (p.relname IN ('pm_source_event_batches','pm_source_event_index',
                                  'pm_book_checkpoints','pm_book_levels')
                   AND c.relname ~ ('^' || p.relname || '_[0-9]{{8}}$'))
               OR (p.relname IN ('ai_invocations','ai_tool_calls','ai_validation_results')
                   AND c.relname ~ ('^' || p.relname || '_[0-9]{{6}}$')))
       );
    IF unknown_objects IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp03_ledger_unknown_object:%', unknown_objects USING ERRCODE='55000';
    END IF;
END $v2_wp03_ledger_preflight$
"""
    )


def _create_guards() -> None:
    # append-only 事实表：positions 除外（乐观锁可更新）。
    for table in _SHADOW_TABLES:
        if table.append_only:
            op.execute(
                f"CREATE TRIGGER trg_{table.name}_immutable "
                f"BEFORE UPDATE OR DELETE ON {TRADING_SCHEMA}.{table.name} "
                "FOR EACH ROW EXECUTE FUNCTION trading.v2_reject_immutable_row()"
            )
    # ledger_transactions 生命周期 guard：PENDING→POSTED；POSTED 后禁改/禁删（任务 §4.13）。
    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_ledger_transaction() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_ledger_transaction_immutable' USING ERRCODE='55000';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'PENDING' OR NEW.posted_at IS NOT NULL THEN
            RAISE EXCEPTION 'v2_ledger_transaction_initial_state_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF OLD.transaction_key IS DISTINCT FROM NEW.transaction_key
       OR OLD.kind IS DISTINCT FROM NEW.kind
       OR OLD.trade_decision_id IS DISTINCT FROM NEW.trade_decision_id
       OR OLD.execution_id IS DISTINCT FROM NEW.execution_id
       OR OLD.portfolio_namespace IS DISTINCT FROM NEW.portfolio_namespace
       OR OLD.reference_transaction_id IS DISTINCT FROM NEW.reference_transaction_id
       OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
        RAISE EXCEPTION 'v2_ledger_transaction_identity_immutable' USING ERRCODE='55000';
    END IF;
    IF OLD.status = 'POSTED' THEN
        RAISE EXCEPTION 'v2_ledger_transaction_immutable' USING ERRCODE='55000';
    END IF;
    IF OLD.status = 'PENDING' AND NEW.status = 'POSTED' AND NEW.posted_at IS NOT NULL THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'v2_ledger_transaction_immutable' USING ERRCODE='55000';
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_ledger_transactions_lifecycle "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.ledger_transactions "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_ledger_transaction()"
    )
    # execution lifecycle guard：PENDING→PARTIAL|FILLED|REJECTED|FAILED
    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_execution() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE terminal text[] := ARRAY['PARTIAL','FILLED','REJECTED','FAILED'];
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_execution_immutable' USING ERRCODE='55000';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'PENDING' OR NEW.filled_quantity <> 0 OR NEW.vwap IS NOT NULL THEN
            RAISE EXCEPTION 'v2_execution_initial_state_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF OLD.execution_key IS DISTINCT FROM NEW.execution_key
       OR OLD.economic_action_intent_id IS DISTINCT FROM NEW.economic_action_intent_id
       OR OLD.action_set_leg_id IS DISTINCT FROM NEW.action_set_leg_id
       OR OLD.contract_spec_id IS DISTINCT FROM NEW.contract_spec_id
       OR OLD.token_id IS DISTINCT FROM NEW.token_id
       OR OLD.fill_role IS DISTINCT FROM NEW.fill_role
       OR OLD.quantity IS DISTINCT FROM NEW.quantity
       OR OLD.portfolio_namespace IS DISTINCT FROM NEW.portfolio_namespace
       OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
        RAISE EXCEPTION 'v2_execution_identity_immutable' USING ERRCODE='55000';
    END IF;
    IF OLD.status = ANY(terminal) AND NEW.status IS DISTINCT FROM OLD.status THEN
        RAISE EXCEPTION 'v2_execution_terminal_immutable' USING ERRCODE='55000';
    END IF;
    IF OLD.status = 'PENDING' AND NEW.status = ANY(terminal) THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'v2_execution_immutable' USING ERRCODE='55000';
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_executions_lifecycle "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.executions "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_execution()"
    )
    # ledger_transactions/ledger_postings 的 append-only immutable trigger 已由上面
    # ``_SHADOW_TABLES`` 循环（append_only=True）创建；deferred balance 由下方校验。
    # deferred ledger balance：每个 (asset_type, asset_key) signed 合计=0 且 ≥2 postings。
    op.execute(
        r"""
CREATE FUNCTION trading.v2_check_ledger_balance() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    tx_ref bigint;
    tx_status text;
    balance numeric;
    posting_count integer;
BEGIN
    IF TG_TABLE_NAME = 'ledger_transactions' THEN
        tx_ref := NEW.id;
    ELSE
        tx_ref := NEW.transaction_id;
    END IF;
    SELECT status INTO STRICT tx_status FROM trading.ledger_transactions WHERE id = tx_ref;
    IF tx_status <> 'POSTED' THEN
        RETURN NEW;
    END IF;
    FOR balance, posting_count IN
        SELECT sum(amount), count(*)
          FROM trading.ledger_postings
         WHERE transaction_id = tx_ref
         GROUP BY asset_type, asset_key
    LOOP
        IF posting_count < 2 OR balance <> 0 THEN
            RAISE EXCEPTION 'v2_ledger_unbalanced:%', balance USING ERRCODE='23514';
        END IF;
    END LOOP;
    -- 至少两个 asset 组（BUY 形成 cash + token 双对手）
    SELECT count(DISTINCT asset_type || ':' || asset_key)
      INTO posting_count
      FROM trading.ledger_postings WHERE transaction_id = tx_ref;
    IF posting_count < 2 THEN
        RAISE EXCEPTION 'v2_ledger_requires_two_asset_groups' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    for table, events in (("ledger_transactions", "INSERT OR UPDATE"), ("ledger_postings", "INSERT OR UPDATE")):
        op.execute(
            f"CREATE CONSTRAINT TRIGGER trg_{table}_ledger_balance "
            f"AFTER {events} ON trading.{table} "
            "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
            "EXECUTE FUNCTION trading.v2_check_ledger_balance()"
        )


def _drop_guards() -> None:
    for table in ("ledger_postings", "ledger_transactions"):
        op.execute(
            f"DROP TRIGGER IF EXISTS trg_{table}_ledger_balance ON trading.{table}"
        )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_check_ledger_balance()")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_ledger_transactions_lifecycle "
        "ON trading.ledger_transactions"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_ledger_transaction()")
    op.execute("DROP TRIGGER IF EXISTS trg_executions_lifecycle ON trading.executions")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_execution()")
    for table in reversed(_SHADOW_TABLES):
        if table.append_only:
            op.execute(
                f"DROP TRIGGER IF EXISTS trg_{table.name}_immutable "
                f"ON {TRADING_SCHEMA}.{table.name}"
            )


def upgrade() -> None:
    for table in _SHADOW_TABLES:
        op.execute(table.create_sql)
        for statement in table.index_sql:
            op.execute(statement)
    _create_guards()


def downgrade() -> None:
    _assert_downgrade_safe()
    _drop_guards()
    for table in reversed(_SHADOW_TABLES):
        op.execute(f"DROP TABLE {TRADING_SCHEMA}.{table.name}")
