"""create p3 read projections

Revision ID: b1000041
Revises: b1000040
Create Date: 2026-08-11 18:00:00

v2_0041 —— 五张只读投影表（WP-04 Checkpoint D）。

- ``upgrade``：
  - 5 张可重建 read model：ops_health_current / pipeline_funnel_hourly /
    account_risk_current / provider_cost_daily / latest_chain_summary。
  - 每张表带 ``as_of / source_high_watermark / projection_version / projection_hash /
    created_at`` 与 ``ix_<table>_as_of`` keyset 复合索引 ``(as_of, id)``。
  - 每行 INSERT 后禁止 UPDATE/DELETE（append-only 投影；重建 = 整表清空重插，
    immutable trigger 复用 0002 的 ``v2_reject_immutable_row``）。
  - 投影不是事实源：无任何 FK 引用业务表，不连账本/label/permission。
- ``downgrade``：先 fail-closed preflight（未知 trading 对象 RAISE
  ``v2_wp04_projection_unknown_object``，ERRCODE 55000，含动态分区子表白名单豁免），
  drop 投影 immutable trigger，逆序 DROP 5 表。

fixed literal DDL；不 import live ORM 生成 DDL；无密钥。
"""
from dataclasses import dataclass
from typing import Sequence, Union

from alembic import op

TRADING_SCHEMA = "trading"

# revision identifiers, used by Alembic.
revision: str = "b1000041"
down_revision: Union[str, Sequence[str], None] = "b1000040"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_COMMON_TAIL = (
    "\tas_of TIMESTAMP WITH TIME ZONE NOT NULL, \n"
    "\tsource_high_watermark BIGINT NOT NULL, \n"
    "\tprojection_version INTEGER NOT NULL, \n"
    "\tprojection_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
    "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n"
    "\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
    "\tPRIMARY KEY (id), \n"
)


@dataclass(frozen=True)
class _FrozenTableSpec:
    name: str
    create_sql: str
    index_sql: tuple[str, ...] = ()


_PROJECTION_TABLES = (
    _FrozenTableSpec(
        name="ops_health_current",
        create_sql=(
            "\nCREATE TABLE trading.ops_health_current (\n"
            "\tmetric_name TEXT COLLATE \"C\" NOT NULL, \n"
            "\tmetric_value NUMERIC(38, 12) NOT NULL, \n"
            "\tstatus VARCHAR(32) NOT NULL, \n"
            + _COMMON_TAIL +
            "\tCONSTRAINT uq_ops_health_current_metric_asof UNIQUE (metric_name, as_of), \n"
            "\tCONSTRAINT ck_ops_health_current_status_known "
            "CHECK (status IN ('ok','degraded','stale','error'))\n"
            ")\n\n"
        ),
        index_sql=(
            "CREATE INDEX ix_ops_health_current_as_of "
            "ON trading.ops_health_current (as_of, id)",
        ),
    ),
    _FrozenTableSpec(
        name="pipeline_funnel_hourly",
        create_sql=(
            "\nCREATE TABLE trading.pipeline_funnel_hourly (\n"
            "\thour_start TIMESTAMP WITH TIME ZONE NOT NULL, \n"
            "\tstage VARCHAR(32) NOT NULL, \n"
            "\tevent_count BIGINT NOT NULL, \n"
            + _COMMON_TAIL +
            "\tCONSTRAINT uq_pipeline_funnel_hourly_stage_hour UNIQUE (stage, hour_start), \n"
            "\tCONSTRAINT ck_pipeline_funnel_hourly_stage_known CHECK (stage IN "
            "('universe','screen','cohort','episode','forecast','decision','execution')), \n"
            "\tCONSTRAINT ck_pipeline_funnel_hourly_count_nonneg CHECK (event_count >= 0)\n"
            ")\n\n"
        ),
        index_sql=(
            "CREATE INDEX ix_pipeline_funnel_hourly_as_of "
            "ON trading.pipeline_funnel_hourly (as_of, id)",
        ),
    ),
    _FrozenTableSpec(
        name="account_risk_current",
        create_sql=(
            "\nCREATE TABLE trading.account_risk_current (\n"
            "\tportfolio_namespace TEXT COLLATE \"C\" NOT NULL, \n"
            "\tmarket_id BIGINT, \n"
            "\tcomponent_id BIGINT, \n"
            "\texposure NUMERIC(38, 12) NOT NULL, \n"
            "\tnet_risk_capital NUMERIC(38, 12) NOT NULL, \n"
            "\tcvar NUMERIC(38, 12) NOT NULL, \n"
            "\tcapital_days NUMERIC(38, 12) NOT NULL, \n"
            + _COMMON_TAIL +
            "\tCONSTRAINT uq_account_risk_current_namespace_market_component "
            "UNIQUE (portfolio_namespace, market_id, component_id), \n"
            "\tCONSTRAINT ck_account_risk_current_exposure_nonneg CHECK (exposure >= 0), \n"
            "\tCONSTRAINT ck_account_risk_current_net_risk_nonneg CHECK (net_risk_capital >= 0), \n"
            "\tCONSTRAINT ck_account_risk_current_capital_days_nonneg CHECK (capital_days >= 0)\n"
            ")\n\n"
        ),
        index_sql=(
            "CREATE INDEX ix_account_risk_current_as_of "
            "ON trading.account_risk_current (as_of, id)",
        ),
    ),
    _FrozenTableSpec(
        name="provider_cost_daily",
        create_sql=(
            "\nCREATE TABLE trading.provider_cost_daily (\n"
            "\tcost_date DATE NOT NULL, \n"
            "\tprovider VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tcost_kind VARCHAR(32) NOT NULL, \n"
            "\tamount NUMERIC(38, 12) NOT NULL, \n"
            + _COMMON_TAIL +
            "\tCONSTRAINT uq_provider_cost_daily_provider_kind_date "
            "UNIQUE (provider, cost_kind, cost_date), \n"
            "\tCONSTRAINT ck_provider_cost_daily_kind_known CHECK (cost_kind IN "
            "('DATA','LLM','SEARCH','INFRASTRUCTURE','HUMAN','OPERATIONAL_LOSS')), \n"
            "\tCONSTRAINT ck_provider_cost_daily_amount_nonneg CHECK (amount >= 0)\n"
            ")\n\n"
        ),
        index_sql=(
            "CREATE INDEX ix_provider_cost_daily_as_of "
            "ON trading.provider_cost_daily (as_of, id)",
        ),
    ),
    _FrozenTableSpec(
        name="latest_chain_summary",
        create_sql=(
            "\nCREATE TABLE trading.latest_chain_summary (\n"
            "\tchain_key VARCHAR(128) COLLATE \"C\" NOT NULL, \n"
            "\tchain_value NUMERIC(38, 12) NOT NULL, \n"
            "\tperiod_end TIMESTAMP WITH TIME ZONE NOT NULL, \n"
            + _COMMON_TAIL +
            "\tCONSTRAINT uq_latest_chain_summary_key_period UNIQUE (chain_key, period_end)\n"
            ")\n\n"
        ),
        index_sql=(
            "CREATE INDEX ix_latest_chain_summary_as_of "
            "ON trading.latest_chain_summary (as_of, id)",
        ),
    ),
)

# b1000040 已存在的 trading 关系（0041 downgrade preflight allowlist = 0031 全量 +
# 0040 的 14 张 learning 表 + 0041 的 5 张投影表）。
_PRE_0041_RELATIONS = (
    "artifact_objects", "artifact_lineage_edges", "archive_manifests",
    "retention_manifests", "runtime_config_versions", "strategy_objective_contracts",
    "strategy_versions", "execution_spec_versions", "capital_permission_manifests",
    "model_role_bindings", "release_manifests", "policy_type_scopes", "policy_freezes",
    "secret_vault_entries", "secret_vault_versions", "secret_access_events",
    "idempotency_claims", "transactional_outbox", "outbox_delivery_history",
    "job_completions", "pm_universe_frames", "pm_universe_frame_pages", "pm_events",
    "pm_markets", "pm_market_versions", "pm_tokens", "pm_token_versions",
    "pm_market_lifecycle_events", "pm_market_current", "pm_connection_epochs",
    "pm_source_event_batches", "pm_source_event_index", "pm_book_checkpoints",
    "pm_book_levels", "pm_book_current", "pm_quote_bindings", "contract_snapshots",
    "contract_specs", "payout_functions", "forecast_components", "world_schema_versions",
    "forecast_component_versions", "forecast_component_contract_specs",
    "portfolio_dependency_edges", "evaluation_cohorts", "universe_memberships",
    "screening_episodes", "audit_samples", "decision_opportunities",
    "decision_opportunity_markets", "episode_memberships", "forecast_episodes",
    "episode_contract_specs", "information_snapshots", "information_snapshot_items",
    "gate_decisions", "priors", "evidence_coverage_policies", "evidence_revisions",
    "evidence_bundles", "evidence_bundle_items", "forecast_input_manifests",
    "forecast_submissions", "payout_projections", "coherence_checks",
    "forecast_challenges", "forecast_leases", "ai_invocations", "ai_tool_calls",
    "ai_validation_results", "market_relative_decisions", "discrepancy_reviews",
    "trade_decisions", "action_candidates", "resolution_cashflows", "action_sets",
    "action_set_legs", "underwriting_plans", "economic_action_intents",
    "executions", "positions", "position_lots", "ledger_transactions",
    "ledger_postings", "operating_cost_entries",
    # b1000040 learning facts（14 张）
    "resolution_labels", "resolution_clusters", "resolution_cluster_memberships",
    "score_targets", "score_target_memberships", "score_observations", "experiments",
    "experiment_variants", "challenger_variants", "metric_runs", "error_reviews",
    "ablation_runs", "promotion_decisions", "replay_runs",
)


def _assert_downgrade_safe() -> None:
    allowed = ", ".join(
        f"'{name}'" for name in (*_PRE_0041_RELATIONS, *(t.name for t in _PROJECTION_TABLES))
    )
    op.execute(
        f"""
DO $v2_wp04_projection_preflight$
DECLARE unknown_objects text;
BEGIN
    SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
      INTO unknown_objects
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'trading'
       AND c.relkind IN ('r','p','v','m','f')
       AND c.relname NOT IN ({allowed})
       AND NOT EXISTS (
           SELECT 1 FROM pg_inherits i
           JOIN pg_class p ON p.oid = i.inhparent
           JOIN pg_namespace pn ON pn.oid = p.relnamespace
           WHERE i.inhrelid = c.oid AND pn.nspname = 'trading'
             AND ((p.relname = 'outbox_delivery_history'
                   AND c.relname ~ '^outbox_delivery_history_[0-9]{{6}}$')
               OR (p.relname IN ('pm_source_event_batches','pm_source_event_index',
                                  'pm_book_checkpoints','pm_book_levels')
                   AND c.relname ~ ('^' || p.relname || '_[0-9]{{8}}$'))
               OR (p.relname IN ('ai_invocations','ai_tool_calls','ai_validation_results')
                   AND c.relname ~ ('^' || p.relname || '_[0-9]{{6}}$')))
       );
    IF unknown_objects IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp04_projection_unknown_object:%', unknown_objects
        USING ERRCODE='55000';
    END IF;
END $v2_wp04_projection_preflight$
"""
    )


def _create_guards() -> None:
    for table in _PROJECTION_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table.name}_immutable "
            f"BEFORE UPDATE OR DELETE ON {TRADING_SCHEMA}.{table.name} "
            "FOR EACH ROW EXECUTE FUNCTION trading.v2_reject_immutable_row()"
        )


def _drop_guards() -> None:
    for table in reversed(_PROJECTION_TABLES):
        op.execute(
            f"DROP TRIGGER IF EXISTS trg_{table.name}_immutable "
            f"ON {TRADING_SCHEMA}.{table.name}"
        )


def upgrade() -> None:
    for table in _PROJECTION_TABLES:
        op.execute(table.create_sql)
        for statement in table.index_sql:
            op.execute(statement)
    _create_guards()


def downgrade() -> None:
    _assert_downgrade_safe()
    _drop_guards()
    for table in reversed(_PROJECTION_TABLES):
        op.execute(f"DROP TABLE {TRADING_SCHEMA}.{table.name}")
