"""chain settlement registry operations observations

Revision ID: b1000052
Revises: b1000051
Create Date: 2026-08-11 21:00:00

v2_0052 —— WP-06 Checkpoint B：Polygon/Relayer/settlement 数据层。

- ``upgrade``：
  - 新建且只新建 4 张 chain-settlement 表：contract_registry / chain_operations /
    chain_operation_state_history / settlement_observations。
  - 只对既有 executions / ledger_transactions 增加最小可空 lineage 列
    ``chain_operation_id``（不得创建平行账户/Vault/账本/label/投影表）。
  - guard：
    - registry 字段不可变，仅原子 publisher 可将 ACTIVE→SUPERSEDED；同
      chain+kind 只允许一个 active；发布前校验 none/EIP-1967/beacon 的
      resolved code 全长证据。
    - chain_operations 绑定列不可变；状态机 CAS 由 history 触发推进（``FOR UPDATE`` +
      fence 校验 + terminal 拒绝 + finality evidence 必须齐备才 FINALIZED）；直接 UPDATE
      状态也必须通过同一转移表（无 GUC 绕过）。
    - chain_operation_state_history append-only，aggregate sequence 唯一；FINALIZED
      在提交时 deferred 验证真实 position/ledger/workflow/outbox 经济事实，
      禁止状态触发器伪造 ``economic_effect_applied``。
    - settlement_observations append-only；``COMPLETE`` 五元组 exact set 由 deferred
      constraint trigger 在提交时核验（缺失 → ``v2_settlement_observation_complete_set_missing``）。
    - 同 account+wallet+condition 同时最多一个 active REDEEM（partial unique）。
  - 状态机覆盖 ``PREPARED→SUBMITTING→UNKNOWN|RELAYER_NEW|EXECUTED|MINED|RELAYER_CONFIRMED→
    MINED_PROVISIONAL→FINALIZED`` 及 ``INVALID|FAILED|REORGED|SETTLEMENT_CONFLICT|REVERSED``；
    非法倒退、terminal mutation、跳过 finality 全部拒绝。
- ``downgrade``：fail-closed preflight（未知 trading 对象 RAISE
  ``v2_wp06_chain_settlement_unknown_object``，ERRCODE 55000，含动态分区子表白名单豁免；
  非 fixture registry / 任何 chain fact / UNKNOWN 或 active operation 任一存在整次拒绝），
  drop guards，移除 lineage 列，逆序 DROP 4 表。

fixed literal DDL；不 import live ORM 生成 DDL；无密钥/signature 明文。
"""
from dataclasses import dataclass
from typing import Sequence, Union

from alembic import op

TRADING_SCHEMA = "trading"

# revision identifiers, used by Alembic.
revision: str = "b1000052"
down_revision: Union[str, Sequence[str], None] = "b1000051"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_OP_STATUS = (
    "'PREPARED','SUBMITTING','UNKNOWN','RELAYER_NEW','EXECUTED','MINED',"
    "'RELAYER_CONFIRMED','MINED_PROVISIONAL','FINALIZED',"
    "'INVALID','FAILED','REORGED','SETTLEMENT_CONFLICT','REVERSED'"
)
_ACTIVE_OP_STATUS = (
    "'PREPARED','SUBMITTING','UNKNOWN','RELAYER_NEW','EXECUTED','MINED',"
    "'RELAYER_CONFIRMED','MINED_PROVISIONAL','REORGED'"
)
_OP_TYPE = "'SPLIT','MERGE','REDEEM'"
_REGISTRY_KIND = "'pusd','ctf','deposit_wallet','ctf_adapter_standard','neg_risk_adapter'"
_PROXY_KIND = "'none','eip1967','beacon'"
_SOURCE_KIND = (
    "'gamma_clob_closed','ctf_payout','data_api_redeemable','clob_winner_5050','label_audit'"
)
_REGISTRY_STATUS = "'ACTIVE','SUPERSEDED'"
_OBSERVATION_STATUS = "'PENDING','COMPLETE','CONFLICT'"

# 冻结 fixture registry 的 5 条 entry content_hash（downgrade 非 fixture registry 校验）。
_FIXTURE_REGISTRY_HASHES = (
    "2a45596924268153acef218ee104ed69f355399701725f88aea967438f91bd4d",
    "6fe9adbfbb71a1d191341218da25185e0871a61b76df2758b0873d884f87cc5b",
    "774caf5580ff19b5fefbf7fd8236885e353f4ac15803449d921aaa2a02d9511f",
    "9668ef928815b964220d02ef2562f2cf5713e9f06bf7c475b0011bae89af8741",
    "97376e86cad7664dd9b745188ed06ca7fc45965966f61ce407146902380954c7",
)


@dataclass(frozen=True)
class _FrozenTableSpec:
    name: str
    create_sql: str
    index_sql: tuple[str, ...] = ()
    append_only: bool = False


_NEW_TABLES = (
    _FrozenTableSpec(
        name="contract_registry",
        create_sql=(
            "\nCREATE TABLE trading.contract_registry (\n"
            "\tregistry_version TEXT COLLATE \"C\" NOT NULL, \n"
            "\tkind VARCHAR(64) NOT NULL, \n"
            "\tversion_no INTEGER NOT NULL, \n"
            "\tchain_id BIGINT NOT NULL, \n"
            "\taddress TEXT COLLATE \"C\" NOT NULL, \n"
            "\tproxy_kind VARCHAR(16) NOT NULL, \n"
            "\truntime_keccak VARCHAR(66) COLLATE \"C\" NOT NULL, \n"
            "\tresolved_implementation_or_beacon TEXT COLLATE \"C\", \n"
            "\tresolved_code_keccak VARCHAR(66) COLLATE \"C\" NOT NULL, \n"
            "\tsnapshot_block_number BIGINT NOT NULL, \n"
            "\tsnapshot_block_hash VARCHAR(66) COLLATE \"C\" NOT NULL, \n"
            "\tsource_url TEXT NOT NULL, \n"
            "\tretrieved_at TIMESTAMP WITH TIME ZONE NOT NULL, \n"
            "\tcontent_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\textra JSONB, \n"
            "\tstatus VARCHAR(16) DEFAULT 'ACTIVE' NOT NULL, \n"
            "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n"
            "\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tPRIMARY KEY (id), \n"
            "\tCONSTRAINT uq_contract_registry_chain_kind_version "
            "UNIQUE (chain_id, kind, version_no), \n"
            "\tCONSTRAINT ck_contract_registry_kind_known "
            "CHECK (kind IN (" + _REGISTRY_KIND + ")), \n"
            "\tCONSTRAINT ck_contract_registry_proxy_kind_known "
            "CHECK (proxy_kind IN (" + _PROXY_KIND + ")), \n"
            "\tCONSTRAINT ck_contract_registry_status_known "
            "CHECK (status IN (" + _REGISTRY_STATUS + ")), \n"
            "\tCONSTRAINT ck_contract_registry_version_positive CHECK (version_no > 0), \n"
            "\tCONSTRAINT ck_contract_registry_snapshot_positive "
            "CHECK (snapshot_block_number > 0), \n"
            "\tCONSTRAINT ck_contract_registry_chain_id CHECK (chain_id = 137), \n"
            "\tCONSTRAINT ck_contract_registry_address_hex "
            "CHECK (address ~ '^0x[0-9a-fA-F]{40}$'), \n"
            "\tCONSTRAINT ck_contract_registry_resolved_address_hex "
            "CHECK (resolved_implementation_or_beacon IS NULL "
            "OR resolved_implementation_or_beacon ~ '^0x[0-9a-fA-F]{40}$'), \n"
            "\tCONSTRAINT ck_contract_registry_runtime_keccak_hex "
            "CHECK (runtime_keccak ~ '^0x[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_contract_registry_resolved_code_hex "
            "CHECK (resolved_code_keccak ~ '^0x[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_contract_registry_block_hash_hex "
            "CHECK (snapshot_block_hash ~ '^0x[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_contract_registry_content_hash_hex "
            "CHECK (content_hash ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_contract_registry_resolved_pair CHECK ("
            "(proxy_kind = 'none') = (resolved_implementation_or_beacon IS NULL)), \n"
            "\tCONSTRAINT ck_contract_registry_extra_object "
            "CHECK (extra IS NULL OR jsonb_typeof(extra) = 'object')\n"
            ")\n\n"
        ),
        index_sql=(
            "CREATE UNIQUE INDEX uq_contract_registry_active_per_chain_kind "
            "ON trading.contract_registry (chain_id, kind) WHERE status = 'ACTIVE'",
            "CREATE INDEX ix_contract_registry_kind "
            "ON trading.contract_registry (kind)",
        ),
        append_only=True,
    ),
    _FrozenTableSpec(
        name="chain_operations",
        create_sql=(
            "\nCREATE TABLE trading.chain_operations (\n"
            "\toperation_key TEXT COLLATE \"C\" NOT NULL, \n"
            "\tidempotency_key VARCHAR(255) NOT NULL, \n"
            "\teconomic_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\toperation_type VARCHAR(16) NOT NULL, \n"
            "\tchain_id BIGINT NOT NULL, \n"
            "\taccount_id BIGINT NOT NULL, \n"
            "\twallet_address TEXT COLLATE \"C\" NOT NULL, \n"
            "\tcondition_id VARCHAR(66) COLLATE \"C\" NOT NULL, \n"
            "\tmarket_id BIGINT NOT NULL, \n"
            "\tregistry_version_id BIGINT NOT NULL, \n"
            "\ttarget_address TEXT COLLATE \"C\" NOT NULL, \n"
            "\tpermission_ref TEXT COLLATE \"C\" NOT NULL, \n"
            "\tlease_owner TEXT COLLATE \"C\" NOT NULL, \n"
            "\trelease_manifest_id BIGINT NOT NULL, \n"
            "\tcapital_permission_manifest_id BIGINT NOT NULL, \n"
            "\tfencing_token BIGINT NOT NULL, \n"
            "\tamount_base_units NUMERIC(38, 0) NOT NULL, \n"
            "\tcalldata TEXT COLLATE \"C\" NOT NULL, \n"
            "\tcalldata_keccak VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tbody_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tcall_set_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\texpected_operation_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tpreflight_hash1 VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tpreflight_hash2 VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tstatus VARCHAR(32) DEFAULT 'PREPARED' NOT NULL, \n"
            "\trelayer_nonce TEXT COLLATE \"C\", \n"
            "\tdeadline TIMESTAMP WITH TIME ZONE, \n"
            "\ttransaction_id TEXT COLLATE \"C\", \n"
            "\ttransaction_hash TEXT COLLATE \"C\", \n"
            "\treceipt_block_number BIGINT, \n"
            "\treceipt_block_hash VARCHAR(66) COLLATE \"C\", \n"
            "\treceipt_status BOOLEAN, \n"
            "\tcanonical_block_hash VARCHAR(66) COLLATE \"C\", \n"
            "\tfinalized_block_number BIGINT, \n"
            "\tfinalized_block_hash VARCHAR(66) COLLATE \"C\", \n"
            "\tregistry_content_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tregistry_bundle JSONB NOT NULL, \n"
            "\tregistry_bundle_content_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tregistry_evidence_artifact_id BIGINT NOT NULL, \n"
            "\tregistry_evidence_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tgeo_evidence_artifact_id BIGINT NOT NULL, \n"
            "\tgeo_evidence_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tgeo_allowed BOOLEAN NOT NULL, \n"
            "\tgeo_observed_at TIMESTAMP WITH TIME ZONE NOT NULL, \n"
            "\tgeo_source_version VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tbalance_evidence_artifact_id BIGINT, \n"
            "\tbalance_evidence_hash VARCHAR(64) COLLATE \"C\", \n"
            "\tsettlement_set_key VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tsettlement_allocation JSONB NOT NULL, \n"
            "\tsettlement_allocation_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tpre_balance JSONB, \n"
            "\tpost_balance JSONB, \n"
            "\teconomic_effect_applied BOOLEAN DEFAULT false NOT NULL, \n"
            "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n"
            "\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tPRIMARY KEY (id), \n"
            "\tCONSTRAINT uq_chain_operations_key UNIQUE (operation_key), \n"
            "\tCONSTRAINT uq_chain_operations_idempotency UNIQUE (idempotency_key), \n"
            "\tCONSTRAINT uq_chain_operations_economic_hash UNIQUE (economic_hash), \n"
            "\tCONSTRAINT uq_chain_operations_expected_hash "
            "UNIQUE (expected_operation_hash), \n"
            "\tCONSTRAINT ck_chain_operations_type_known "
            "CHECK (operation_type IN (" + _OP_TYPE + ")), \n"
            "\tCONSTRAINT ck_chain_operations_status_known "
            "CHECK (status IN (" + _OP_STATUS + ")), \n"
            "\tCONSTRAINT ck_chain_operations_chain_id CHECK (chain_id = 137), \n"
            "\tCONSTRAINT ck_chain_operations_fencing_positive CHECK (fencing_token > 0), \n"
            "\tCONSTRAINT ck_chain_operations_amount_range CHECK ("
            "(operation_type = 'REDEEM' AND amount_base_units = 0) OR "
            "(operation_type IN ('SPLIT','MERGE') AND amount_base_units > 0)), \n"
            "\tCONSTRAINT ck_chain_operations_hashes_hex CHECK ("
            "economic_hash ~ '^[0-9a-f]{64}$' AND calldata_keccak ~ '^[0-9a-f]{64}$' "
            "AND body_hash ~ '^[0-9a-f]{64}$' AND call_set_hash ~ '^[0-9a-f]{64}$' "
            "AND expected_operation_hash ~ '^[0-9a-f]{64}$' "
            "AND preflight_hash1 ~ '^[0-9a-f]{64}$' "
            "AND preflight_hash2 ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_chain_operations_wallet_hex "
            "CHECK (wallet_address ~ '^0x[0-9a-fA-F]{40}$'), \n"
            "\tCONSTRAINT ck_chain_operations_target_hex "
            "CHECK (target_address ~ '^0x[0-9a-fA-F]{40}$'), \n"
            "\tCONSTRAINT ck_chain_operations_condition_hex "
            "CHECK (condition_id ~ '^0x[0-9a-fA-F]{64}$'), \n"
            "\tCONSTRAINT ck_chain_operations_receipt_hash_hex "
            "CHECK (receipt_block_hash IS NULL OR receipt_block_hash ~ '^0x[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_chain_operations_canonical_hash_hex CHECK ("
            "canonical_block_hash IS NULL OR canonical_block_hash ~ '^0x[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_chain_operations_finalized_hash_hex CHECK ("
            "finalized_block_hash IS NULL OR finalized_block_hash ~ '^0x[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_chain_operations_evidence_hashes_hex CHECK ("
            "registry_content_hash ~ '^[0-9a-f]{64}$' AND "
            "registry_bundle_content_hash ~ '^[0-9a-f]{64}$' AND "
            "registry_evidence_hash ~ '^[0-9a-f]{64}$' AND "
            "geo_evidence_hash ~ '^[0-9a-f]{64}$' AND "
            "(balance_evidence_hash IS NULL OR balance_evidence_hash ~ '^[0-9a-f]{64}$') AND "
            "(settlement_set_key IS NULL OR settlement_set_key ~ '^[0-9a-f]{64}$')), \n"
            "\tCONSTRAINT ck_chain_operations_balances_object CHECK ("
            "(pre_balance IS NULL OR jsonb_typeof(pre_balance) = 'object') AND "
            "(post_balance IS NULL OR jsonb_typeof(post_balance) = 'object') AND "
            "jsonb_typeof(registry_bundle) = 'object'), \n"
            "\tCONSTRAINT ck_chain_operations_balance_artifact_pair CHECK ("
            "(balance_evidence_artifact_id IS NULL) = (balance_evidence_hash IS NULL)), \n"
            "\tCONSTRAINT ck_chain_operations_geo_source_nonempty CHECK ("
            "length(btrim(geo_source_version)) > 0), \n"
            "\tCONSTRAINT ck_chain_operations_allocation_shape CHECK ("
            "jsonb_typeof(settlement_allocation) = 'array' "
            "AND jsonb_array_length(settlement_allocation) > 0 "
            "AND settlement_allocation_hash ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_chain_operations_economic_once CHECK ("
            "NOT economic_effect_applied OR status IN "
            "('FINALIZED','SETTLEMENT_CONFLICT','REVERSED')), \n"
            "\tCONSTRAINT ck_chain_operations_finalized_evidence CHECK ("
            "status <> 'FINALIZED' OR ("
            "transaction_id IS NOT NULL AND transaction_hash IS NOT NULL AND "
            "receipt_block_number IS NOT NULL AND receipt_block_hash IS NOT NULL AND "
            "receipt_status IS TRUE AND canonical_block_hash = receipt_block_hash AND "
            "finalized_block_number IS NOT NULL AND finalized_block_hash IS NOT NULL AND "
            "finalized_block_number > receipt_block_number AND "
            "registry_evidence_hash IS NOT NULL AND balance_evidence_hash IS NOT NULL AND "
            "settlement_set_key IS NOT NULL AND "
            "pre_balance IS NOT NULL AND post_balance IS NOT NULL)), \n"
            "\tCONSTRAINT ck_chain_operations_mining_evidence CHECK ("
            "status NOT IN ('MINED_PROVISIONAL','FINALIZED') OR "
            "(transaction_hash IS NOT NULL AND receipt_block_number IS NOT NULL "
            "AND receipt_block_hash IS NOT NULL)), \n"
            "\tCONSTRAINT ck_chain_operations_relayer_evidence CHECK ("
            "status NOT IN ('RELAYER_CONFIRMED','MINED','MINED_PROVISIONAL','FINALIZED') "
            "OR (transaction_id IS NOT NULL AND transaction_hash IS NOT NULL)), \n"
            "\tCONSTRAINT fk_chain_operations_account "
            "FOREIGN KEY(account_id) REFERENCES trading.pm_accounts (id), \n"
            "\tCONSTRAINT fk_chain_operations_registry "
            "FOREIGN KEY(registry_version_id) REFERENCES trading.contract_registry (id), \n"
            "\tCONSTRAINT fk_chain_operations_release "
            "FOREIGN KEY(release_manifest_id) REFERENCES trading.release_manifests (id), \n"
            "\tCONSTRAINT fk_chain_operations_permission "
            "FOREIGN KEY(capital_permission_manifest_id) "
            "REFERENCES trading.capital_permission_manifests (id), \n"
            "\tCONSTRAINT fk_chain_operations_market "
            "FOREIGN KEY(market_id) REFERENCES trading.pm_markets (id), \n"
            "\tCONSTRAINT fk_chain_operations_registry_evidence_artifact "
            "FOREIGN KEY(registry_evidence_artifact_id) REFERENCES trading.artifact_objects (id), \n"
            "\tCONSTRAINT fk_chain_operations_geo_evidence_artifact "
            "FOREIGN KEY(geo_evidence_artifact_id) REFERENCES trading.artifact_objects (id), \n"
            "\tCONSTRAINT fk_chain_operations_balance_evidence_artifact "
            "FOREIGN KEY(balance_evidence_artifact_id) REFERENCES trading.artifact_objects (id)\n"
            ")\n\n"
        ),
        index_sql=(
            "CREATE UNIQUE INDEX uq_chain_operations_active_redeem "
            "ON trading.chain_operations (account_id, wallet_address, condition_id) "
            "WHERE operation_type = 'REDEEM' AND status IN (" + _ACTIVE_OP_STATUS + ")",
            "CREATE INDEX ix_chain_operations_status "
            "ON trading.chain_operations (status)",
            "CREATE INDEX ix_chain_operations_account "
            "ON trading.chain_operations (account_id)",
            "CREATE INDEX ix_chain_operations_condition "
            "ON trading.chain_operations (condition_id)",
        ),
        append_only=False,
    ),
    _FrozenTableSpec(
        name="chain_operation_state_history",
        create_sql=(
            "\nCREATE TABLE trading.chain_operation_state_history (\n"
            "\toperation_id BIGINT NOT NULL, \n"
            "\tsequence_no INTEGER NOT NULL, \n"
            "\ttransition_from VARCHAR(32) NOT NULL, \n"
            "\ttransition_to VARCHAR(32) NOT NULL, \n"
            "\tevent_type VARCHAR(32) NOT NULL, \n"
            "\tevent_payload JSONB NOT NULL, \n"
            "\tevent_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tlease_owner TEXT COLLATE \"C\" NOT NULL, \n"
            "\tfence_token BIGINT NOT NULL, \n"
            "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n"
            "\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tPRIMARY KEY (id), \n"
            "\tCONSTRAINT uq_chain_op_state_history_op_seq "
            "UNIQUE (operation_id, sequence_no), \n"
            "\tCONSTRAINT uq_chain_op_state_history_hash UNIQUE (event_hash), \n"
            "\tCONSTRAINT ck_chain_op_state_history_type_known "
            "CHECK (event_type IN (" + _OP_STATUS + ")), \n"
            "\tCONSTRAINT ck_chain_op_state_history_type_matches "
            "CHECK (event_type = transition_to), \n"
            "\tCONSTRAINT ck_chain_op_state_history_fence_positive "
            "CHECK (fence_token > 0), \n"
            "\tCONSTRAINT ck_chain_op_state_history_seq_nonneg CHECK (sequence_no >= 0), \n"
            "\tCONSTRAINT ck_chain_op_state_history_payload_object "
            "CHECK (jsonb_typeof(event_payload) = 'object'), \n"
            "\tCONSTRAINT ck_chain_op_state_history_event_hash_hex "
            "CHECK (event_hash ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_chain_op_state_history_transition_exact CHECK ("
            "(transition_from = 'PREPARED' AND transition_to = 'SUBMITTING') OR "
            "(transition_from = 'SUBMITTING' AND transition_to IN "
            "('UNKNOWN','RELAYER_NEW','EXECUTED','INVALID','FAILED')) OR "
            "(transition_from = 'UNKNOWN' AND transition_to IN "
            "('RELAYER_NEW','EXECUTED','INVALID','FAILED','REORGED','SETTLEMENT_CONFLICT','REVERSED')) OR "
            "(transition_from = 'RELAYER_NEW' AND transition_to IN "
            "('EXECUTED','MINED','INVALID','FAILED','UNKNOWN','REORGED')) OR "
            "(transition_from = 'EXECUTED' AND transition_to IN "
            "('MINED','INVALID','FAILED','UNKNOWN','REORGED')) OR "
            "(transition_from = 'MINED' AND transition_to IN "
            "('RELAYER_CONFIRMED','MINED_PROVISIONAL','INVALID','FAILED','UNKNOWN','REORGED')) OR "
            "(transition_from = 'RELAYER_CONFIRMED' AND transition_to IN "
            "('MINED_PROVISIONAL','FINALIZED','INVALID','FAILED','UNKNOWN','REORGED','SETTLEMENT_CONFLICT')) OR "
            "(transition_from = 'MINED_PROVISIONAL' AND transition_to IN "
            "('FINALIZED','INVALID','FAILED','REORGED','UNKNOWN','SETTLEMENT_CONFLICT')) OR "
            "(transition_from = 'FINALIZED' AND transition_to IN "
            "('SETTLEMENT_CONFLICT','REVERSED')) OR "
            "(transition_from = 'REORGED' AND transition_to = 'UNKNOWN') OR "
            "(transition_from = 'REVERSED' AND transition_to = 'SETTLEMENT_CONFLICT')\n"
            "),\n"
            "\tCONSTRAINT fk_chain_op_state_history_operation "
            "FOREIGN KEY(operation_id) REFERENCES trading.chain_operations (id)\n"
            ")\n\n"
        ),
        index_sql=(
            "CREATE INDEX ix_chain_op_state_history_operation "
            "ON trading.chain_operation_state_history (operation_id)",
        ),
        append_only=True,
    ),
    _FrozenTableSpec(
        name="settlement_observations",
        create_sql=(
            "\nCREATE TABLE trading.settlement_observations (\n"
            "\tobservation_key TEXT COLLATE \"C\" NOT NULL, \n"
            "\tsettlement_set_key VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tsource_kind VARCHAR(32) NOT NULL, \n"
            "\tcondition_id VARCHAR(66) COLLATE \"C\" NOT NULL, \n"
            "\tmarket_id BIGINT NOT NULL, \n"
            "\ttoken_set JSONB NOT NULL, \n"
            "\ttoken_set_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tpayout_vector JSONB, \n"
            "\toutcome_index VARCHAR(32), \n"
            "\tnumerator TEXT COLLATE \"C\", \n"
            "\tdenominator TEXT COLLATE \"C\", \n"
            "\twinner VARCHAR(32), \n"
            "\tis_50_50_outcome BOOLEAN, \n"
            "\tredeemable BOOLEAN, \n"
            "\tlabel_audit_version VARCHAR(64) COLLATE \"C\", \n"
            "\tsource_version VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tsource_cutoff TIMESTAMP WITH TIME ZONE NOT NULL, \n"
            "\tas_of TIMESTAMP WITH TIME ZONE NOT NULL, \n"
            "\treceived_at TIMESTAMP WITH TIME ZONE NOT NULL, \n"
            "\traw_artifact_ref VARCHAR(64) COLLATE \"C\", \n"
            "\traw_artifact_id BIGINT, \n"
            "\traw_artifact_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tcontent_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tpayload JSONB, \n"
            "\tstatus VARCHAR(16) DEFAULT 'PENDING' NOT NULL, \n"
            "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n"
            "\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tPRIMARY KEY (id), \n"
            "\tCONSTRAINT uq_settlement_observations_key UNIQUE (observation_key), \n"
            "\tCONSTRAINT uq_settlement_observations_hash UNIQUE (content_hash), \n"
            "\tCONSTRAINT uq_settlement_observations_set_source "
            "UNIQUE (settlement_set_key, source_kind), \n"
            "\tCONSTRAINT ck_settlement_observations_source_known "
            "CHECK (source_kind IN (" + _SOURCE_KIND + ")), \n"
            "\tCONSTRAINT ck_settlement_observations_status_known "
            "CHECK (status IN (" + _OBSERVATION_STATUS + ")), \n"
            "\tCONSTRAINT ck_settlement_observations_condition_hex "
            "CHECK (condition_id ~ '^0x[0-9a-fA-F]{64}$'), \n"
            "\tCONSTRAINT ck_settlement_observations_artifact_hash_hex "
            "CHECK (raw_artifact_hash ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_settlement_observations_content_hash_hex "
            "CHECK (content_hash ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_settlement_observations_set_hashes_hex CHECK ("
            "settlement_set_key ~ '^[0-9a-f]{64}$' AND token_set_hash ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_settlement_observations_token_set "
            "CHECK (jsonb_typeof(token_set) = 'array' AND jsonb_array_length(token_set) = 2), \n"
            "\tCONSTRAINT ck_settlement_observations_time_order CHECK ("
            "as_of <= received_at AND as_of <= source_cutoff), \n"
            "\tCONSTRAINT ck_settlement_observations_source_version_nonempty "
            "CHECK (length(btrim(source_version)) > 0), \n"
            "\tCONSTRAINT ck_settlement_observations_artifact_ref CHECK ("
            "raw_artifact_id IS NOT NULL OR raw_artifact_ref ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT ck_settlement_observations_complete_artifact CHECK ("
            "status <> 'COMPLETE' OR raw_artifact_id IS NOT NULL), \n"
            "\tCONSTRAINT ck_settlement_observations_payout_pair CHECK ("
            "(source_kind = 'ctf_payout') = (numerator IS NOT NULL "
            "AND denominator IS NOT NULL AND payout_vector IS NOT NULL)), \n"
            "\tCONSTRAINT ck_settlement_observations_payout_vector CHECK ("
            "payout_vector IS NULL OR (jsonb_typeof(payout_vector) = 'object' "
            "AND jsonb_typeof(payout_vector->'numerators') = 'array' "
            "AND jsonb_array_length(payout_vector->'numerators') = 2 "
            "AND payout_vector ? 'denominator')), \n"
            "\tCONSTRAINT ck_settlement_observations_winner_pair CHECK ("
            "(source_kind = 'clob_winner_5050') = (winner IS NOT NULL "
            "OR is_50_50_outcome IS NOT NULL)), \n"
            "\tCONSTRAINT ck_settlement_observations_redeemable_pair CHECK ("
            "(source_kind = 'data_api_redeemable') = (redeemable IS NOT NULL)), \n"
            "\tCONSTRAINT fk_settlement_observations_market "
            "FOREIGN KEY(market_id) REFERENCES trading.pm_markets (id), \n"
            "\tCONSTRAINT fk_settlement_observations_artifact "
            "FOREIGN KEY(raw_artifact_id) REFERENCES trading.artifact_objects (id)\n"
            ")\n\n"
        ),
        index_sql=(
            "CREATE INDEX ix_settlement_observations_condition "
            "ON trading.settlement_observations (condition_id)",
            "CREATE INDEX ix_settlement_observations_source "
            "ON trading.settlement_observations (source_kind)",
        ),
        append_only=True,
    ),
)

# b1000051 已存在的 trading 关系（0052 downgrade preflight allowlist = 0051 全量 +
# 0051 的 9 张 execution-plane 表）。
_PRE_0052_RELATIONS = (
    # b1000002 ~ b1000041 全量
    "artifact_objects", "artifact_lineage_edges", "archive_manifests",
    "retention_manifests", "runtime_config_versions", "strategy_objective_contracts",
    "strategy_versions", "execution_spec_versions", "capital_permission_manifests",
    "model_role_bindings", "release_manifests", "policy_type_scopes", "policy_freezes",
    "secret_vault_entries", "secret_vault_versions", "secret_access_events",
    "idempotency_claims", "transactional_outbox", "outbox_delivery_history",
    "job_completions", "pm_universe_frames", "pm_universe_frame_pages", "pm_events",
    "pm_markets", "pm_market_versions", "pm_tokens", "pm_token_versions",
    "pm_market_lifecycle_events", "pm_market_current", "pm_connection_epochs",
    "pm_source_event_batches", "pm_source_event_index", "pm_book_checkpoints",
    "pm_book_levels", "pm_book_current", "pm_quote_bindings", "contract_snapshots",
    "contract_specs", "payout_functions", "forecast_components", "world_schema_versions",
    "forecast_component_versions", "forecast_component_contract_specs",
    "portfolio_dependency_edges", "evaluation_cohorts", "universe_memberships",
    "screening_episodes", "audit_samples", "decision_opportunities",
    "decision_opportunity_markets", "episode_memberships", "forecast_episodes",
    "episode_contract_specs", "information_snapshots", "information_snapshot_items",
    "gate_decisions", "priors", "evidence_coverage_policies", "evidence_revisions",
    "evidence_bundles", "evidence_bundle_items", "forecast_input_manifests",
    "forecast_submissions", "payout_projections", "coherence_checks",
    "forecast_challenges", "forecast_leases", "ai_invocations", "ai_tool_calls",
    "ai_validation_results", "market_relative_decisions", "discrepancy_reviews",
    "trade_decisions", "action_candidates", "resolution_cashflows", "action_sets",
    "action_set_legs", "underwriting_plans", "economic_action_intents",
    "executions", "positions", "position_lots", "ledger_transactions",
    "ledger_postings", "operating_cost_entries",
    "resolution_labels", "resolution_clusters", "resolution_cluster_memberships",
    "score_targets", "score_target_memberships", "score_observations", "experiments",
    "experiment_variants", "challenger_variants", "metric_runs", "error_reviews",
    "ablation_runs", "promotion_decisions", "replay_runs",
    "ops_health_current", "pipeline_funnel_hourly", "account_risk_current",
    "provider_cost_daily", "latest_chain_summary",
    "pm_accounts", "pm_balance_allowance_snapshots", "account_funds_current",
    "capital_reservations", "execution_leases",
    # b1000051 execution-plane（9 张）
    "execution_authorization_envelopes", "exchange_order_attempts", "exchange_orders",
    "order_state_events", "exchange_trades", "account_reconciliations",
    "workflow_events", "external_call_attempts", "alert_events",
)


def _index_name(statement: str) -> str:
    """``CREATE [UNIQUE] INDEX <name> ON ...`` → ``<name>``。"""
    rest = statement.replace("CREATE UNIQUE INDEX ", "").replace("CREATE INDEX ", "")
    return rest.split(" ON ")[0].strip()


def _assert_downgrade_safe() -> None:
    allowed = ", ".join(
        f"'{name}'" for name in (*_PRE_0052_RELATIONS, *(t.name for t in _NEW_TABLES))
    )
    owned = ", ".join(f"'{t.name}'" for t in _NEW_TABLES)
    known_indexes = ", ".join(
        f"'{_index_name(statement)}'"
        for table in _NEW_TABLES for statement in table.index_sql
    ) or "''"
    known_triggers = ", ".join(
        f"'{name}'" for name in (
            "trg_contract_registry_immutable",
            "trg_contract_registry_publish_check",
            "trg_chain_operations_lifecycle",
            "trg_chain_operations_preflight",
            "trg_chain_operations_finality_complete",
            "trg_chain_operation_state_cas",
            "trg_chain_operation_state_history_immutable",
            "trg_settlement_observations_immutable",
            "trg_settlement_observations_complete_set",
        )
    )
    fixture_hashes = ", ".join(f"'{h}'" for h in _FIXTURE_REGISTRY_HASHES)
    op.execute(
        f"""
DO $v2_wp06_chain_settlement_preflight$
DECLARE unknown_objects text;
        unknown_indexes text;
        unknown_triggers text;
        unknown_fks text;
        unknown_dependencies text;
        bad_registry text;
        active_ops bigint;
        chain_facts bigint;
BEGIN
    -- 非 fixture registry：任一 entry 的 content_hash 不在冻结 fixture 集 → 整次拒绝
    SELECT string_agg(content_hash, ', ' ORDER BY content_hash)
      INTO bad_registry
      FROM trading.contract_registry
     WHERE content_hash NOT IN ({fixture_hashes});
    IF bad_registry IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp06_chain_settlement_non_fixture_registry:%', bad_registry
        USING ERRCODE='55000';
    END IF;
    -- UNKNOWN / active operation：恢复期与活跃链上操作必须先完成只读 reconcile
    SELECT count(*) INTO active_ops
      FROM trading.chain_operations
     WHERE status IN ({_ACTIVE_OP_STATUS});
    IF active_ops <> 0 THEN
        RAISE EXCEPTION 'v2_wp06_chain_settlement_active_operations:%', active_ops
        USING ERRCODE='55000';
    END IF;
    -- 其他 chain fact（state history / observations / 任何 operation 行）不得被静默丢弃
    SELECT (SELECT count(*) FROM trading.chain_operations)
         + (SELECT count(*) FROM trading.chain_operation_state_history)
         + (SELECT count(*) FROM trading.settlement_observations)
      INTO chain_facts;
    IF chain_facts <> 0 THEN
        RAISE EXCEPTION 'v2_wp06_chain_settlement_chain_facts_present:%', chain_facts
        USING ERRCODE='55000';
    END IF;
    SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
      INTO unknown_objects
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'trading'
       AND c.relkind IN ('r','p','v','m','f')
       AND c.relname NOT IN ({allowed})
       AND NOT EXISTS (
           SELECT 1 FROM pg_inherits i
           JOIN pg_class p ON p.oid = i.inhparent
           JOIN pg_namespace pn ON pn.oid = p.relnamespace
           WHERE i.inhrelid = c.oid AND pn.nspname = 'trading'
             AND ((p.relname = 'outbox_delivery_history'
                   AND c.relname ~ '^outbox_delivery_history_[0-9]{{6}}$')
               OR (p.relname IN ('pm_source_event_batches','pm_source_event_index',
                                  'pm_book_checkpoints','pm_book_levels')
                   AND c.relname ~ ('^' || p.relname || '_[0-9]{{8}}$'))
               OR (p.relname IN ('ai_invocations','ai_tool_calls','ai_validation_results')
                   AND c.relname ~ ('^' || p.relname || '_[0-9]{{6}}$')))
       );
    IF unknown_objects IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp06_chain_settlement_unknown_object:%', unknown_objects
        USING ERRCODE='55000';
    END IF;
    SELECT string_agg(idx.relname, ', ' ORDER BY idx.relname)
      INTO unknown_indexes
      FROM pg_index i
      JOIN pg_class idx ON idx.oid=i.indexrelid
      JOIN pg_class tbl ON tbl.oid=i.indrelid
      JOIN pg_namespace n ON n.oid=tbl.relnamespace
     WHERE n.nspname='trading' AND tbl.relname IN ({owned})
       AND NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conindid=idx.oid)
       AND idx.relname NOT IN ({known_indexes});
    IF unknown_indexes IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp06_chain_settlement_unknown_index:%', unknown_indexes
        USING ERRCODE='55000';
    END IF;
    SELECT string_agg(t.tgname, ', ' ORDER BY t.tgname)
      INTO unknown_triggers
      FROM pg_trigger t
      JOIN pg_class tbl ON tbl.oid=t.tgrelid
      JOIN pg_namespace n ON n.oid=tbl.relnamespace
     WHERE n.nspname='trading' AND tbl.relname IN ({owned})
       AND NOT t.tgisinternal AND t.tgname NOT IN ({known_triggers});
    IF unknown_triggers IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp06_chain_settlement_unknown_trigger:%', unknown_triggers
        USING ERRCODE='55000';
    END IF;
    SELECT string_agg(con.conname, ', ' ORDER BY con.conname)
      INTO unknown_fks
      FROM pg_constraint con
      JOIN pg_class src ON src.oid=con.conrelid
      JOIN pg_class dst ON dst.oid=con.confrelid
      JOIN pg_namespace sn ON sn.oid=src.relnamespace
      JOIN pg_namespace dn ON dn.oid=dst.relnamespace
     WHERE con.contype='f'
       AND ((sn.nspname='trading' AND src.relname IN ({owned}))
         OR (dn.nspname='trading' AND dst.relname IN ({owned})))
       AND con.conname NOT IN (
          'fk_chain_operations_account','fk_chain_operations_registry',
          'fk_chain_operations_release','fk_chain_operations_permission',
          'fk_chain_operations_market','fk_chain_op_state_history_operation',
          'fk_chain_operations_registry_evidence_artifact',
          'fk_chain_operations_geo_evidence_artifact',
          'fk_chain_operations_balance_evidence_artifact',
          'fk_settlement_observations_market','fk_settlement_observations_artifact',
          'fk_executions_chain_operation','fk_ledger_transactions_chain_operation');
    IF unknown_fks IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp06_chain_settlement_unknown_fk:%', unknown_fks
        USING ERRCODE='55000';
    END IF;
    SELECT string_agg(n.nspname || '.' || dependent.relname, ', '
                      ORDER BY n.nspname || '.' || dependent.relname)
      INTO unknown_dependencies
      FROM pg_depend d
      JOIN pg_rewrite rw ON rw.oid=d.objid
      JOIN pg_class dependent ON dependent.oid=rw.ev_class
      JOIN pg_namespace n ON n.oid=dependent.relnamespace
      JOIN pg_class referenced ON referenced.oid=d.refobjid
      JOIN pg_namespace rn ON rn.oid=referenced.relnamespace
     WHERE rn.nspname='trading' AND referenced.relname IN ({owned})
       AND dependent.oid<>referenced.oid;
    IF unknown_dependencies IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp06_chain_settlement_unknown_dependency:%', unknown_dependencies
        USING ERRCODE='55000';
    END IF;
END $v2_wp06_chain_settlement_preflight$
"""
    )


def _add_lineage() -> None:
    """只对既有 executions / ledger_transactions 增加最小可空 lineage 列。"""
    op.execute(
        "ALTER TABLE trading.executions ADD COLUMN chain_operation_id BIGINT"
    )
    op.execute(
        "ALTER TABLE trading.executions "
        "ADD CONSTRAINT fk_executions_chain_operation "
        "FOREIGN KEY(chain_operation_id) REFERENCES trading.chain_operations (id)"
    )
    op.execute(
        "ALTER TABLE trading.ledger_transactions ADD COLUMN chain_operation_id BIGINT"
    )
    op.execute(
        "ALTER TABLE trading.ledger_transactions "
        "ADD CONSTRAINT fk_ledger_transactions_chain_operation "
        "FOREIGN KEY(chain_operation_id) REFERENCES trading.chain_operations (id)"
    )
    op.execute(
        "CREATE INDEX ix_executions_chain_operation "
        "ON trading.executions (chain_operation_id)"
    )
    op.execute(
        "CREATE INDEX ix_ledger_transactions_chain_operation "
        "ON trading.ledger_transactions (chain_operation_id)"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_ledger_transactions_chain_operation_settlement "
        "ON trading.ledger_transactions (chain_operation_id, portfolio_namespace) "
        "WHERE chain_operation_id IS NOT NULL AND kind = 'SETTLEMENT'"
    )


def _drop_lineage() -> None:
    op.execute(
        "ALTER TABLE trading.executions DROP COLUMN IF EXISTS chain_operation_id"
    )
    op.execute(
        "ALTER TABLE trading.ledger_transactions DROP COLUMN IF EXISTS chain_operation_id"
    )


def _restore_wp05_real_fill_lineage() -> None:
    """Restore the exact b1000051 guard before removing WP-06 lineage columns."""
    op.execute(
        r"""
CREATE OR REPLACE FUNCTION trading.v2_check_real_fill_lineage() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    IF TG_TABLE_NAME = 'ledger_transactions' THEN
        IF NEW.account_id IS NULL AND NEW.envelope_id IS NULL
           AND NEW.order_id IS NULL AND NEW.trade_id IS NULL THEN
            RETURN NEW;
        END IF;
        IF NEW.account_id IS NULL OR NEW.envelope_id IS NULL
           OR NEW.order_id IS NULL OR NEW.trade_id IS NULL
           OR NEW.portfolio_namespace <> 'exec-' || NEW.account_id::text
           OR NOT EXISTS (
                SELECT 1 FROM trading.execution_authorization_envelopes e
                JOIN trading.exchange_order_attempts a ON a.envelope_id=e.id
                JOIN trading.exchange_orders o ON o.attempt_id=a.id
                JOIN trading.exchange_trades t
                  ON t.order_id=o.id AND t.account_id=o.account_id
                JOIN trading.economic_action_intents i ON i.id=e.intent_id
                WHERE e.id=NEW.envelope_id AND e.account_id=NEW.account_id
                  AND o.id=NEW.order_id AND t.id=NEW.trade_id
                  AND i.trade_decision_id IS NOT DISTINCT FROM NEW.trade_decision_id
                  AND (NEW.execution_id IS NULL OR EXISTS (
                      SELECT 1 FROM trading.executions x
                       WHERE x.id=NEW.execution_id AND x.account_id=NEW.account_id
                         AND x.envelope_id=NEW.envelope_id AND x.order_id=NEW.order_id
                         AND x.trade_id=NEW.trade_id
                  ))
           ) THEN
            RAISE EXCEPTION 'v2_ledger_outer_lineage_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF TG_TABLE_NAME = 'position_lots' THEN
        IF NEW.execution_id IS NOT NULL AND NEW.account_id IS NULL
           AND NEW.order_id IS NULL AND NEW.trade_id IS NULL THEN
            RETURN NEW;
        END IF;
        IF NEW.account_id IS NULL
           OR NEW.order_id IS NULL OR NEW.trade_id IS NULL
           OR NEW.portfolio_namespace <> 'exec-' || NEW.account_id::text
           OR NOT EXISTS (
                SELECT 1 FROM trading.exchange_orders o
                JOIN trading.exchange_trades t
                  ON t.order_id=o.id AND t.account_id=o.account_id
                WHERE o.id=NEW.order_id AND o.account_id=NEW.account_id
                  AND t.id=NEW.trade_id
                  AND (NEW.execution_id IS NULL OR EXISTS (
                      SELECT 1 FROM trading.executions x
                       WHERE x.id=NEW.execution_id AND x.account_id=NEW.account_id
                         AND x.order_id=NEW.order_id AND x.trade_id=NEW.trade_id
                  ))
           ) THEN
            RAISE EXCEPTION 'v2_position_lot_outer_lineage_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF TG_TABLE_NAME = 'positions' THEN
        IF NEW.account_id IS NULL AND NEW.envelope_id IS NULL AND NEW.order_id IS NULL THEN
            RETURN NEW;
        END IF;
        IF NEW.account_id IS NULL OR NEW.envelope_id IS NULL OR NEW.order_id IS NULL
           OR NEW.portfolio_namespace <> 'exec-' || NEW.account_id::text
           OR NOT EXISTS (
                SELECT 1 FROM trading.execution_authorization_envelopes e
                JOIN trading.exchange_order_attempts a ON a.envelope_id=e.id
                JOIN trading.exchange_orders o ON o.attempt_id=a.id
                WHERE e.id=NEW.envelope_id AND e.account_id=NEW.account_id
                  AND o.id=NEW.order_id AND o.account_id=NEW.account_id
           ) THEN
            RAISE EXCEPTION 'v2_position_outer_lineage_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )


def _create_guards() -> None:
    op.execute(
        """
CREATE FUNCTION trading.v2_guard_contract_registry_immutable() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_contract_registry_immutable' USING ERRCODE='55000';
    END IF;
    -- Lifecycle metadata may only be advanced by the atomic publisher below.  Every
    -- provenance/address/code field remains byte-for-byte immutable.
    IF TG_OP = 'UPDATE' THEN
        IF COALESCE(current_setting('trading.registry_publish', true), 'off') <> 'on'
           OR OLD.status <> 'ACTIVE' OR NEW.status <> 'SUPERSEDED'
           OR (to_jsonb(OLD) - 'status') IS DISTINCT FROM (to_jsonb(NEW) - 'status') THEN
            RAISE EXCEPTION 'v2_contract_registry_immutable' USING ERRCODE='55000';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_contract_registry_immutable
    BEFORE UPDATE OR DELETE ON trading.contract_registry
    FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_contract_registry_immutable();
"""
    )
    op.execute(
        """
CREATE FUNCTION trading.v2_guard_contract_registry_publish() RETURNS trigger AS $$
BEGIN
    IF NEW.proxy_kind NOT IN ('none','eip1967','beacon') THEN
        RAISE EXCEPTION 'v2_contract_registry_proxy_kind_unknown' USING ERRCODE='23514';
    END IF;
    IF (NEW.proxy_kind = 'none') <> (NEW.resolved_implementation_or_beacon IS NULL) THEN
        RAISE EXCEPTION 'v2_contract_registry_resolved_pair_invalid' USING ERRCODE='23514';
    END IF;
    IF NEW.resolved_code_keccak IS NULL OR NEW.runtime_keccak IS NULL THEN
        RAISE EXCEPTION 'v2_contract_registry_code_missing' USING ERRCODE='23502';
    END IF;
    IF length(btrim(NEW.registry_version)) = 0 OR length(btrim(NEW.source_url)) = 0 THEN
        RAISE EXCEPTION 'v2_contract_registry_provenance_missing' USING ERRCODE='23502';
    END IF;
    IF NEW.proxy_kind = 'none' AND NEW.resolved_code_keccak <> NEW.runtime_keccak THEN
        RAISE EXCEPTION 'v2_contract_registry_direct_code_mismatch' USING ERRCODE='23514';
    END IF;
    IF NEW.proxy_kind = 'eip1967' THEN
        IF NEW.extra IS NULL
           OR NEW.extra->>'implementation_slot' IS NULL
           OR NEW.extra->>'implementation_slot' !~ '^0x[0-9a-f]{64}$' THEN
            RAISE EXCEPTION 'v2_contract_registry_eip1967_incomplete' USING ERRCODE='23502';
        END IF;
    END IF;
    IF NEW.proxy_kind = 'beacon' THEN
        IF NEW.extra IS NULL
           OR NEW.extra->>'beacon_address' IS NULL
           OR NEW.extra->>'beacon_implementation' IS NULL
           OR NEW.extra->>'beacon_runtime_keccak' IS NULL
           OR NEW.extra->>'beacon_implementation_code_keccak' IS NULL THEN
            RAISE EXCEPTION 'v2_contract_registry_beacon_incomplete' USING ERRCODE='23502';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_contract_registry_publish_check
    BEFORE INSERT ON trading.contract_registry
    FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_contract_registry_publish();
"""
    )
    op.execute(
        r"""
CREATE FUNCTION trading.v2_publish_contract_registry(
    p_registry_version text, p_kind text, p_version_no integer, p_chain_id bigint,
    p_address text, p_proxy_kind text, p_runtime_keccak text,
    p_resolved text, p_resolved_code_keccak text, p_snapshot_block_number bigint,
    p_snapshot_block_hash text, p_source_url text, p_retrieved_at timestamptz,
    p_content_hash text, p_extra jsonb
) RETURNS bigint AS $$
DECLARE published_id bigint;
        existing trading.contract_registry%ROWTYPE;
        latest trading.contract_registry%ROWTYPE;
BEGIN
    PERFORM pg_advisory_xact_lock(p_chain_id::integer, hashtext(p_kind));
    SELECT * INTO existing
      FROM trading.contract_registry
     WHERE chain_id=p_chain_id AND kind=p_kind AND version_no=p_version_no;
    IF FOUND THEN
        IF existing.registry_version IS DISTINCT FROM p_registry_version
           OR existing.address IS DISTINCT FROM p_address
           OR existing.proxy_kind IS DISTINCT FROM p_proxy_kind
           OR existing.runtime_keccak IS DISTINCT FROM p_runtime_keccak
           OR existing.resolved_implementation_or_beacon IS DISTINCT FROM p_resolved
           OR existing.resolved_code_keccak IS DISTINCT FROM p_resolved_code_keccak
           OR existing.snapshot_block_number IS DISTINCT FROM p_snapshot_block_number
           OR existing.snapshot_block_hash IS DISTINCT FROM p_snapshot_block_hash
           OR existing.source_url IS DISTINCT FROM p_source_url
           OR existing.retrieved_at IS DISTINCT FROM p_retrieved_at
           OR existing.content_hash IS DISTINCT FROM p_content_hash
           OR existing.extra IS DISTINCT FROM p_extra THEN
            RAISE EXCEPTION 'v2_contract_registry_version_conflict:%:%:%',
                p_chain_id,p_kind,p_version_no USING ERRCODE='23505';
        END IF;
        RETURN existing.id;
    END IF;
    SELECT * INTO latest FROM trading.contract_registry
     WHERE chain_id=p_chain_id AND kind=p_kind ORDER BY version_no DESC LIMIT 1;
    IF FOUND THEN
        IF p_version_no <> latest.version_no + 1 THEN
            RAISE EXCEPTION 'v2_contract_registry_version_not_linear expected=% actual=%',
                latest.version_no + 1,p_version_no USING ERRCODE='23514';
        END IF;
        IF p_snapshot_block_number < latest.snapshot_block_number
           OR p_retrieved_at < latest.retrieved_at THEN
            RAISE EXCEPTION 'v2_contract_registry_provenance_regression' USING ERRCODE='23514';
        END IF;
    ELSIF p_version_no <> 1 THEN
        RAISE EXCEPTION 'v2_contract_registry_first_version_not_one' USING ERRCODE='23514';
    END IF;
    PERFORM set_config('trading.registry_publish', 'on', true);
    UPDATE trading.contract_registry
       SET status='SUPERSEDED'
     WHERE chain_id=p_chain_id AND kind=p_kind AND status='ACTIVE';
    INSERT INTO trading.contract_registry(
        registry_version,kind,version_no,chain_id,address,proxy_kind,runtime_keccak,
        resolved_implementation_or_beacon,resolved_code_keccak,snapshot_block_number,
        snapshot_block_hash,source_url,retrieved_at,content_hash,extra,status
    ) VALUES (
        p_registry_version,p_kind,p_version_no,p_chain_id,p_address,p_proxy_kind,
        p_runtime_keccak,p_resolved,p_resolved_code_keccak,p_snapshot_block_number,
        p_snapshot_block_hash,p_source_url,p_retrieved_at,p_content_hash,p_extra,'ACTIVE'
    ) RETURNING id INTO published_id;
    PERFORM set_config('trading.registry_publish', 'off', true);
    RETURN published_id;
END;
$$ LANGUAGE plpgsql;
"""
    )
    op.execute(
        """
CREATE FUNCTION trading.v2_guard_chain_operation_update() RETURNS trigger AS $$
BEGIN
    -- 绑定列不可变：account/wallet/condition/market/registry/permission/release/fence/
    -- call-set/body/preflight/calldata/economic hash 全部冻结。
    IF OLD.operation_key <> NEW.operation_key
       OR OLD.idempotency_key <> NEW.idempotency_key
       OR OLD.economic_hash <> NEW.economic_hash
       OR OLD.operation_type <> NEW.operation_type
       OR OLD.chain_id <> NEW.chain_id
       OR OLD.account_id <> NEW.account_id
       OR OLD.wallet_address <> NEW.wallet_address
       OR OLD.condition_id <> NEW.condition_id
       OR OLD.market_id IS DISTINCT FROM NEW.market_id
       OR OLD.registry_version_id <> NEW.registry_version_id
       OR OLD.target_address <> NEW.target_address
       OR OLD.permission_ref <> NEW.permission_ref
       OR OLD.lease_owner <> NEW.lease_owner
       OR OLD.release_manifest_id <> NEW.release_manifest_id
       OR OLD.capital_permission_manifest_id <> NEW.capital_permission_manifest_id
       OR OLD.fencing_token <> NEW.fencing_token
       OR OLD.amount_base_units <> NEW.amount_base_units
       OR OLD.calldata <> NEW.calldata
       OR OLD.calldata_keccak <> NEW.calldata_keccak
       OR OLD.body_hash <> NEW.body_hash
       OR OLD.call_set_hash <> NEW.call_set_hash
       OR OLD.expected_operation_hash <> NEW.expected_operation_hash
       OR OLD.preflight_hash1 <> NEW.preflight_hash1
       OR OLD.preflight_hash2 <> NEW.preflight_hash2
       OR OLD.registry_content_hash <> NEW.registry_content_hash
       OR OLD.registry_bundle <> NEW.registry_bundle
       OR OLD.registry_bundle_content_hash <> NEW.registry_bundle_content_hash
       OR OLD.registry_evidence_artifact_id <> NEW.registry_evidence_artifact_id
       OR OLD.registry_evidence_hash <> NEW.registry_evidence_hash
       OR OLD.geo_evidence_artifact_id <> NEW.geo_evidence_artifact_id
       OR OLD.geo_evidence_hash <> NEW.geo_evidence_hash
       OR OLD.geo_allowed <> NEW.geo_allowed
       OR OLD.geo_observed_at <> NEW.geo_observed_at
       OR OLD.geo_source_version <> NEW.geo_source_version
       OR OLD.settlement_set_key <> NEW.settlement_set_key
       OR OLD.settlement_allocation <> NEW.settlement_allocation
       OR OLD.settlement_allocation_hash <> NEW.settlement_allocation_hash THEN
        RAISE EXCEPTION 'v2_chain_operation_binding_immutable' USING ERRCODE='55000';
    END IF;
    IF (OLD.relayer_nonce IS NOT NULL AND OLD.relayer_nonce IS DISTINCT FROM NEW.relayer_nonce)
       OR (OLD.deadline IS NOT NULL AND OLD.deadline IS DISTINCT FROM NEW.deadline)
       OR (OLD.transaction_id IS NOT NULL AND OLD.transaction_id IS DISTINCT FROM NEW.transaction_id)
       OR (OLD.transaction_hash IS NOT NULL AND OLD.transaction_hash IS DISTINCT FROM NEW.transaction_hash)
       OR (OLD.receipt_block_number IS NOT NULL AND OLD.receipt_block_number IS DISTINCT FROM NEW.receipt_block_number)
       OR (OLD.receipt_block_hash IS NOT NULL AND OLD.receipt_block_hash IS DISTINCT FROM NEW.receipt_block_hash)
       OR (OLD.receipt_status IS NOT NULL AND OLD.receipt_status IS DISTINCT FROM NEW.receipt_status)
       OR (OLD.canonical_block_hash IS NOT NULL AND OLD.canonical_block_hash IS DISTINCT FROM NEW.canonical_block_hash)
       OR (OLD.finalized_block_number IS NOT NULL AND OLD.finalized_block_number IS DISTINCT FROM NEW.finalized_block_number)
       OR (OLD.finalized_block_hash IS NOT NULL AND OLD.finalized_block_hash IS DISTINCT FROM NEW.finalized_block_hash)
       OR (OLD.balance_evidence_artifact_id IS NOT NULL AND OLD.balance_evidence_artifact_id IS DISTINCT FROM NEW.balance_evidence_artifact_id)
       OR (OLD.balance_evidence_hash IS NOT NULL AND OLD.balance_evidence_hash IS DISTINCT FROM NEW.balance_evidence_hash)
       OR (OLD.pre_balance IS NOT NULL AND OLD.pre_balance IS DISTINCT FROM NEW.pre_balance)
       OR (OLD.post_balance IS NOT NULL AND OLD.post_balance IS DISTINCT FROM NEW.post_balance) THEN
        RAISE EXCEPTION 'v2_chain_operation_evidence_immutable' USING ERRCODE='55000';
    END IF;
    IF OLD.economic_effect_applied IS DISTINCT FROM NEW.economic_effect_applied THEN
        IF OLD.economic_effect_applied OR NOT NEW.economic_effect_applied
           OR NEW.status <> 'FINALIZED'
           OR NOT EXISTS (
               SELECT 1 FROM trading.ledger_transactions tx
                WHERE tx.chain_operation_id=NEW.id AND tx.kind='SETTLEMENT'
                  AND tx.status='POSTED'
           ) THEN
            RAISE EXCEPTION 'v2_chain_operation_effect_invalid' USING ERRCODE='55000';
        END IF;
    END IF;
    IF OLD.status <> NEW.status THEN
        IF COALESCE(current_setting('trading.chain_state_transition', true), 'off') <> 'on' THEN
            RAISE EXCEPTION 'v2_chain_operation_status_requires_history' USING ERRCODE='55000';
        END IF;
        IF NOT (
            (OLD.status = 'PREPARED' AND NEW.status = 'SUBMITTING') OR
            (OLD.status = 'SUBMITTING' AND NEW.status IN
             ('UNKNOWN','RELAYER_NEW','EXECUTED','INVALID','FAILED')) OR
            (OLD.status = 'UNKNOWN' AND NEW.status IN
             ('RELAYER_NEW','EXECUTED','INVALID','FAILED','REORGED','SETTLEMENT_CONFLICT','REVERSED')) OR
            (OLD.status = 'RELAYER_NEW' AND NEW.status IN
             ('EXECUTED','MINED','INVALID','FAILED','UNKNOWN','REORGED')) OR
            (OLD.status = 'EXECUTED' AND NEW.status IN
             ('MINED','INVALID','FAILED','UNKNOWN','REORGED')) OR
            (OLD.status = 'MINED' AND NEW.status IN
             ('RELAYER_CONFIRMED','MINED_PROVISIONAL','INVALID','FAILED','UNKNOWN','REORGED')) OR
            (OLD.status = 'RELAYER_CONFIRMED' AND NEW.status IN
             ('MINED_PROVISIONAL','FINALIZED','INVALID','FAILED','UNKNOWN','REORGED','SETTLEMENT_CONFLICT')) OR
            (OLD.status = 'MINED_PROVISIONAL' AND NEW.status IN
             ('FINALIZED','INVALID','FAILED','REORGED','UNKNOWN','SETTLEMENT_CONFLICT')) OR
            (OLD.status = 'FINALIZED' AND NEW.status IN ('SETTLEMENT_CONFLICT','REVERSED')) OR
            (OLD.status = 'REORGED' AND NEW.status = 'UNKNOWN') OR
            (OLD.status = 'REVERSED' AND NEW.status = 'SETTLEMENT_CONFLICT')
        ) THEN
            RAISE EXCEPTION 'v2_chain_operation_transition_invalid' USING ERRCODE='23514';
        END IF;
        IF OLD.status IN ('INVALID','FAILED','SETTLEMENT_CONFLICT','REVERSED') THEN
            RAISE EXCEPTION 'v2_chain_operation_terminal_mutation' USING ERRCODE='23514';
        END IF;
        IF OLD.status = 'FINALIZED' AND NEW.status NOT IN ('SETTLEMENT_CONFLICT','REVERSED') THEN
            RAISE EXCEPTION 'v2_chain_operation_terminal_mutation' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_chain_operations_lifecycle
    BEFORE UPDATE ON trading.chain_operations
    FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_chain_operation_update();
"""
    )
    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_chain_operation_preflight() RETURNS trigger AS $$
DECLARE expected_kind text;
        selected_registry trading.contract_registry%ROWTYPE;
        expected_bundle jsonb;
        expected_bundle_hash text;
        bundle_count integer;
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM trading.pm_accounts a
          JOIN trading.release_manifests rel ON rel.id=NEW.release_manifest_id
          JOIN trading.capital_permission_manifests perm
            ON perm.id=NEW.capital_permission_manifest_id
          JOIN trading.execution_leases lease
            ON lease.account_id=a.id AND lease.lease_role='EXECUTION'
         WHERE a.id=NEW.account_id AND a.status='active'
           AND a.provider='polymarket' AND a.chain_id=NEW.chain_id
           AND a.identity_type='FIXTURE_ONLY' AND a.network_mode='fixture'
           AND a.funder_address=NEW.wallet_address AND a.maker_address=NEW.wallet_address
           AND a.release_manifest_id=rel.id
           AND a.capital_permission_manifest_id=perm.id
           AND rel.status='active' AND rel.capital_permission_manifest_id=perm.id
           AND perm.status='active' AND perm.mode='shadow'
           AND perm.authorized_capital=0 AND perm.kill_switch=false
           AND perm.capability->>'chain_settlement'='FAKE_CONFORMANCE'
           AND perm.content_hash=NEW.permission_ref
           AND lease.owner=NEW.lease_owner
           AND lease.fencing_token=NEW.fencing_token
           AND lease.lease_until > statement_timestamp()
           AND NOT EXISTS (
               SELECT 1 FROM trading.account_reconciliations ar
                WHERE ar.account_id=a.id AND (ar.status='RECONCILING' OR
                     (ar.status='FAILED' AND NOT EXISTS (
                        SELECT 1 FROM trading.account_reconciliations ok
                         WHERE ok.account_id=a.id AND ok.status='COMPLETED' AND ok.id>ar.id)))
           )
    ) THEN
        RAISE EXCEPTION 'v2_chain_operation_preflight_invalid' USING ERRCODE='55000';
    END IF;
    SELECT CASE WHEN m.neg_risk THEN 'neg_risk_adapter' ELSE 'ctf_adapter_standard' END
      INTO expected_kind
      FROM trading.pm_markets m
     WHERE m.id=NEW.market_id AND m.condition_id=NEW.condition_id
       AND m.neg_risk IS NOT NULL;
    IF expected_kind IS NULL THEN
        RAISE EXCEPTION 'v2_chain_operation_market_registry_invalid' USING ERRCODE='55000';
    END IF;
    SELECT * INTO selected_registry FROM trading.contract_registry r
     WHERE r.id=NEW.registry_version_id AND r.chain_id=NEW.chain_id
       AND r.kind=expected_kind AND r.address=NEW.target_address
       AND r.status='ACTIVE';
    IF NOT FOUND OR selected_registry.content_hash<>NEW.registry_content_hash THEN
        RAISE EXCEPTION 'v2_chain_operation_market_registry_invalid' USING ERRCODE='55000';
    END IF;
    SELECT jsonb_object_agg(r.kind,r.content_hash ORDER BY r.kind),count(*)
      INTO expected_bundle,bundle_count
      FROM trading.contract_registry r
     WHERE r.chain_id=NEW.chain_id AND r.status='ACTIVE'
       AND r.kind IN ('pusd','ctf','deposit_wallet',expected_kind)
       AND r.registry_version=selected_registry.registry_version
       AND r.version_no=selected_registry.version_no
       AND r.snapshot_block_number=selected_registry.snapshot_block_number
       AND r.snapshot_block_hash=selected_registry.snapshot_block_hash;
    expected_bundle_hash := encode(sha256(convert_to(expected_bundle::text,'UTF8')),'hex');
    IF bundle_count<>4 OR NEW.registry_bundle IS DISTINCT FROM expected_bundle
       OR NEW.registry_bundle_content_hash<>expected_bundle_hash THEN
        RAISE EXCEPTION 'v2_chain_operation_registry_bundle_invalid' USING ERRCODE='55000';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM trading.artifact_objects a
         WHERE a.id=NEW.registry_evidence_artifact_id
           AND a.sha256=NEW.registry_evidence_hash
    ) THEN
        RAISE EXCEPTION 'v2_chain_operation_registry_artifact_invalid' USING ERRCODE='55000';
    END IF;
    IF NEW.geo_allowed IS NOT TRUE
       OR NEW.geo_observed_at > statement_timestamp()
       OR NEW.geo_observed_at < statement_timestamp() - interval '30 seconds'
       OR length(btrim(NEW.geo_source_version))=0
       OR NOT EXISTS (
          SELECT 1 FROM trading.artifact_objects a
           WHERE a.id=NEW.geo_evidence_artifact_id
             AND a.sha256=NEW.geo_evidence_hash) THEN
        RAISE EXCEPTION 'v2_chain_operation_geo_evidence_invalid' USING ERRCODE='55000';
    END IF;
    IF NEW.operation_type='REDEEM' THEN
        IF NOT EXISTS (
          SELECT 1 FROM trading.pm_markets m WHERE m.id=NEW.market_id
            AND m.closed IS TRUE AND m.accepting_orders IS FALSE)
           OR (SELECT count(*) FROM trading.settlement_observations o
                WHERE o.settlement_set_key=NEW.settlement_set_key
                  AND o.market_id=NEW.market_id AND o.condition_id=NEW.condition_id
                  AND o.status='COMPLETE') <> 5 THEN
            RAISE EXCEPTION 'v2_chain_operation_settlement_preflight_invalid' USING ERRCODE='55000';
        END IF;
        IF NEW.pre_balance IS NULL OR jsonb_typeof(NEW.pre_balance->'tokens')<>'object'
           OR NEW.pre_balance->>'pusd' IS NULL OR NEW.pre_balance->>'pusd' !~ '^[0-9]+$'
           OR (SELECT count(*) FROM jsonb_object_keys(NEW.pre_balance->'tokens'))<>2
           OR EXISTS (
             SELECT 1 FROM jsonb_each_text(NEW.pre_balance->'tokens') b(token,quantity)
              WHERE quantity !~ '^[0-9]+$'
                 OR NOT EXISTS (SELECT 1 FROM trading.pm_tokens t
                                 WHERE t.market_id=NEW.market_id AND t.token_id=token))
           OR EXISTS (
             SELECT 1 FROM trading.pm_tokens t WHERE t.market_id=NEW.market_id
               AND NOT (NEW.pre_balance->'tokens' ? t.token_id)) THEN
            RAISE EXCEPTION 'v2_chain_operation_pre_balance_invalid' USING ERRCODE='55000';
        END IF;
        IF EXISTS (
             SELECT 1 FROM jsonb_array_elements(NEW.settlement_allocation) item
              WHERE jsonb_typeof(item)<>'object'
                 OR NOT (item ? 'portfolio_namespace' AND item ? 'token_id'
                         AND item ? 'quantity_base_units' AND item ? 'expected_cash_base_units')
                 OR length(btrim(item->>'portfolio_namespace'))=0
                 OR item->>'quantity_base_units' !~ '^[1-9][0-9]*$'
                 OR item->>'expected_cash_base_units' !~ '^[0-9]+$')
           OR (SELECT count(*) FROM jsonb_array_elements(NEW.settlement_allocation)) <>
              (SELECT count(*) FROM (
                 SELECT item->>'portfolio_namespace',item->>'token_id'
                   FROM jsonb_array_elements(NEW.settlement_allocation) item
                  GROUP BY 1,2) pairs)
           OR EXISTS (
             SELECT 1 FROM (
               SELECT item->>'portfolio_namespace' namespace,item->>'token_id' token,
                      sum((item->>'quantity_base_units')::numeric) quantity
                 FROM jsonb_array_elements(NEW.settlement_allocation) item GROUP BY 1,2
             ) alloc FULL JOIN (
               SELECT p.portfolio_namespace namespace,t.token_id token,sum(p.quantity) quantity
                 FROM trading.positions p JOIN trading.pm_tokens t ON t.id=p.token_id
                WHERE p.account_id=NEW.account_id AND p.market_id=NEW.market_id AND p.quantity>0
                GROUP BY 1,2
             ) pos USING(namespace,token)
             WHERE alloc.quantity IS DISTINCT FROM pos.quantity)
           OR EXISTS (
             SELECT 1 FROM (
               SELECT item->>'token_id' token,sum((item->>'quantity_base_units')::numeric) quantity
                 FROM jsonb_array_elements(NEW.settlement_allocation) item GROUP BY 1
             ) alloc FULL JOIN (
               SELECT token,quantity::numeric
                 FROM jsonb_each_text(NEW.pre_balance->'tokens') AS balance(token,quantity)
                WHERE quantity::numeric>0
             ) bal USING(token)
             WHERE alloc.quantity IS DISTINCT FROM bal.quantity)
           OR EXISTS (
             SELECT 1
               FROM jsonb_array_elements(NEW.settlement_allocation) item
               JOIN trading.settlement_observations obs
                 ON obs.settlement_set_key=NEW.settlement_set_key
                AND obs.source_kind='ctf_payout' AND obs.status='COMPLETE'
               JOIN LATERAL jsonb_array_elements_text(obs.token_set)
                    WITH ORDINALITY token(value,ord) ON token.value=item->>'token_id'
               JOIN LATERAL jsonb_array_elements_text(obs.payout_vector->'numerators')
                    WITH ORDINALITY numerator(value,ord) ON numerator.ord=token.ord
              WHERE (item->>'expected_cash_base_units')::numeric <>
                    (item->>'quantity_base_units')::numeric * numerator.value::numeric /
                    (obs.payout_vector->>'denominator')::numeric)
        THEN
            RAISE EXCEPTION 'v2_chain_operation_settlement_allocation_invalid' USING ERRCODE='55000';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_chain_operations_preflight
    BEFORE INSERT ON trading.chain_operations
    FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_chain_operation_preflight();
"""
    )
    op.execute(
        """
CREATE FUNCTION trading.v2_guard_chain_operation_state() RETURNS trigger AS $$
DECLARE cur_status VARCHAR(32);
        creation_fence BIGINT;
        expected_sequence INTEGER;
        applied_count bigint;
BEGIN
    IF TG_OP = 'UPDATE' OR TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_chain_operation_state_immutable' USING ERRCODE='55000';
    END IF;
    IF NEW.fence_token <= 0 THEN
        RAISE EXCEPTION 'v2_chain_operation_state_fence_nonpositive' USING ERRCODE='23514';
    END IF;
    SELECT status, fencing_token
      INTO cur_status, creation_fence
      FROM trading.chain_operations
     WHERE id = NEW.operation_id
     FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'v2_chain_operation_missing' USING ERRCODE='23503';
    END IF;
    IF NEW.transition_from <> cur_status THEN
        RAISE EXCEPTION 'v2_chain_operation_cas_mismatch expected=% actual=%',
            cur_status, NEW.transition_from USING ERRCODE='55000';
    END IF;
    IF NEW.fence_token < creation_fence OR NOT EXISTS (
        SELECT 1 FROM trading.execution_leases lease
         JOIN trading.chain_operations cop ON cop.account_id=lease.account_id
        WHERE cop.id=NEW.operation_id AND lease.lease_role='EXECUTION'
          AND lease.owner=NEW.lease_owner
          AND lease.fencing_token=NEW.fence_token
          AND lease.lease_until > statement_timestamp()
    ) THEN
        RAISE EXCEPTION 'v2_chain_operation_fence_mismatch creation=% actual=%',
            creation_fence, NEW.fence_token USING ERRCODE='55000';
    END IF;
    SELECT COALESCE(max(sequence_no), -1) + 1 INTO expected_sequence
      FROM trading.chain_operation_state_history WHERE operation_id=NEW.operation_id;
    IF NEW.sequence_no <> expected_sequence THEN
        RAISE EXCEPTION 'v2_chain_operation_sequence_mismatch expected=% actual=%',
            expected_sequence, NEW.sequence_no USING ERRCODE='55000';
    END IF;
    IF cur_status IN ('INVALID','FAILED','SETTLEMENT_CONFLICT','REVERSED') THEN
        RAISE EXCEPTION 'v2_chain_operation_terminal_mutation' USING ERRCODE='23514';
    END IF;
    IF cur_status = 'FINALIZED' AND NEW.transition_to NOT IN ('SETTLEMENT_CONFLICT','REVERSED') THEN
        RAISE EXCEPTION 'v2_chain_operation_terminal_mutation' USING ERRCODE='23514';
    END IF;
    -- 转移合法性前置校验（与 history CHECK 同表；在 FINALIZED 证据路径前拒绝非法/跳 finality）
    IF NOT (
        (cur_status = 'PREPARED' AND NEW.transition_to = 'SUBMITTING') OR
        (cur_status = 'SUBMITTING' AND NEW.transition_to IN
         ('UNKNOWN','RELAYER_NEW','EXECUTED','INVALID','FAILED')) OR
        (cur_status = 'UNKNOWN' AND NEW.transition_to IN
         ('RELAYER_NEW','EXECUTED','INVALID','FAILED','REORGED','SETTLEMENT_CONFLICT','REVERSED')) OR
        (cur_status = 'RELAYER_NEW' AND NEW.transition_to IN
         ('EXECUTED','MINED','INVALID','FAILED','UNKNOWN','REORGED')) OR
        (cur_status = 'EXECUTED' AND NEW.transition_to IN
         ('MINED','INVALID','FAILED','UNKNOWN','REORGED')) OR
        (cur_status = 'MINED' AND NEW.transition_to IN
         ('RELAYER_CONFIRMED','MINED_PROVISIONAL','INVALID','FAILED','UNKNOWN','REORGED')) OR
        (cur_status = 'RELAYER_CONFIRMED' AND NEW.transition_to IN
         ('MINED_PROVISIONAL','FINALIZED','INVALID','FAILED','UNKNOWN','REORGED','SETTLEMENT_CONFLICT')) OR
        (cur_status = 'MINED_PROVISIONAL' AND NEW.transition_to IN
         ('FINALIZED','INVALID','FAILED','REORGED','UNKNOWN','SETTLEMENT_CONFLICT')) OR
        (cur_status = 'FINALIZED' AND NEW.transition_to IN ('SETTLEMENT_CONFLICT','REVERSED')) OR
        (cur_status = 'REORGED' AND NEW.transition_to = 'UNKNOWN') OR
        (cur_status = 'REVERSED' AND NEW.transition_to = 'SETTLEMENT_CONFLICT')
    ) THEN
        RAISE EXCEPTION 'v2_chain_operation_transition_invalid' USING ERRCODE='23514';
    END IF;
    IF NEW.transition_to = 'FINALIZED' THEN
        PERFORM set_config('trading.chain_state_transition', 'on', true);
        UPDATE trading.chain_operations
           SET status = 'FINALIZED', updated_at = now()
         WHERE id = NEW.operation_id
           AND transaction_id IS NOT NULL
           AND transaction_hash IS NOT NULL
           AND receipt_block_number IS NOT NULL
           AND receipt_block_hash IS NOT NULL
           AND receipt_status IS TRUE
           AND canonical_block_hash = receipt_block_hash
           AND finalized_block_number IS NOT NULL
           AND finalized_block_hash IS NOT NULL
           AND finalized_block_number > receipt_block_number
           AND registry_evidence_hash IS NOT NULL
           AND balance_evidence_hash IS NOT NULL
           AND settlement_set_key IS NOT NULL
           AND pre_balance IS NOT NULL
           AND post_balance IS NOT NULL;
        GET DIAGNOSTICS applied_count = ROW_COUNT;
        IF applied_count <> 1 THEN
            RAISE EXCEPTION 'v2_chain_operation_finality_evidence_missing' USING ERRCODE='55000';
        END IF;
    ELSE
        PERFORM set_config('trading.chain_state_transition', 'on', true);
        UPDATE trading.chain_operations
           SET status = NEW.transition_to, updated_at = now()
         WHERE id = NEW.operation_id;
    END IF;
    PERFORM set_config('trading.chain_state_transition', 'off', true);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_chain_operation_state_cas
    BEFORE INSERT ON trading.chain_operation_state_history
    FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_chain_operation_state();
"""
    )
    # WP-05's outer-lineage guard only distinguished anonymous shadow facts from
    # real CLOB fills.  WP-06 settlement ledgers are account-bound but are not fills:
    # bind them to the frozen chain operation and exec namespace while forbidding
    # envelope/order/trade/execution identities. All other WP-05 branches stay exact.
    op.execute(
        r"""
CREATE OR REPLACE FUNCTION trading.v2_check_real_fill_lineage() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    IF TG_TABLE_NAME = 'ledger_transactions' THEN
        IF NEW.kind = 'SETTLEMENT' AND NEW.chain_operation_id IS NOT NULL THEN
            IF NEW.account_id IS NULL
               OR NEW.portfolio_namespace <> 'exec-' || NEW.account_id::text
               OR NEW.envelope_id IS NOT NULL OR NEW.order_id IS NOT NULL
               OR NEW.trade_id IS NOT NULL OR NEW.execution_id IS NOT NULL
               OR NOT EXISTS (
                    SELECT 1 FROM trading.chain_operations cop
                     WHERE cop.id=NEW.chain_operation_id
                       AND cop.account_id=NEW.account_id
               ) THEN
                RAISE EXCEPTION 'v2_settlement_ledger_lineage_invalid' USING ERRCODE='23514';
            END IF;
            RETURN NEW;
        END IF;
        IF NEW.account_id IS NULL AND NEW.envelope_id IS NULL
           AND NEW.order_id IS NULL AND NEW.trade_id IS NULL THEN
            RETURN NEW;
        END IF;
        IF NEW.account_id IS NULL OR NEW.envelope_id IS NULL
           OR NEW.order_id IS NULL OR NEW.trade_id IS NULL
           OR NEW.portfolio_namespace <> 'exec-' || NEW.account_id::text
           OR NOT EXISTS (
                SELECT 1 FROM trading.execution_authorization_envelopes e
                JOIN trading.exchange_order_attempts a ON a.envelope_id=e.id
                JOIN trading.exchange_orders o ON o.attempt_id=a.id
                JOIN trading.exchange_trades t
                  ON t.order_id=o.id AND t.account_id=o.account_id
                JOIN trading.economic_action_intents i ON i.id=e.intent_id
                WHERE e.id=NEW.envelope_id AND e.account_id=NEW.account_id
                  AND o.id=NEW.order_id AND t.id=NEW.trade_id
                  AND i.trade_decision_id IS NOT DISTINCT FROM NEW.trade_decision_id
                  AND (NEW.execution_id IS NULL OR EXISTS (
                      SELECT 1 FROM trading.executions x
                       WHERE x.id=NEW.execution_id AND x.account_id=NEW.account_id
                         AND x.envelope_id=NEW.envelope_id AND x.order_id=NEW.order_id
                         AND x.trade_id=NEW.trade_id
                  ))
           ) THEN
            RAISE EXCEPTION 'v2_ledger_outer_lineage_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF TG_TABLE_NAME = 'position_lots' THEN
        IF NEW.execution_id IS NOT NULL AND NEW.account_id IS NULL
           AND NEW.order_id IS NULL AND NEW.trade_id IS NULL THEN
            RETURN NEW;
        END IF;
        IF NEW.account_id IS NULL
           OR NEW.order_id IS NULL OR NEW.trade_id IS NULL
           OR NEW.portfolio_namespace <> 'exec-' || NEW.account_id::text
           OR NOT EXISTS (
                SELECT 1 FROM trading.exchange_orders o
                JOIN trading.exchange_trades t
                  ON t.order_id=o.id AND t.account_id=o.account_id
                WHERE o.id=NEW.order_id AND o.account_id=NEW.account_id
                  AND t.id=NEW.trade_id
                  AND (NEW.execution_id IS NULL OR EXISTS (
                      SELECT 1 FROM trading.executions x
                       WHERE x.id=NEW.execution_id AND x.account_id=NEW.account_id
                         AND x.order_id=NEW.order_id AND x.trade_id=NEW.trade_id
                  ))
           ) THEN
            RAISE EXCEPTION 'v2_position_lot_outer_lineage_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF TG_TABLE_NAME = 'positions' THEN
        IF NEW.account_id IS NULL AND NEW.envelope_id IS NULL AND NEW.order_id IS NULL THEN
            RETURN NEW;
        END IF;
        IF NEW.account_id IS NULL OR NEW.envelope_id IS NULL OR NEW.order_id IS NULL
           OR NEW.portfolio_namespace <> 'exec-' || NEW.account_id::text
           OR NOT EXISTS (
                SELECT 1 FROM trading.execution_authorization_envelopes e
                JOIN trading.exchange_order_attempts a ON a.envelope_id=e.id
                JOIN trading.exchange_orders o ON o.attempt_id=a.id
                WHERE e.id=NEW.envelope_id AND e.account_id=NEW.account_id
                  AND o.id=NEW.order_id AND o.account_id=NEW.account_id
           ) THEN
            RAISE EXCEPTION 'v2_position_outer_lineage_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        """
CREATE FUNCTION trading.v2_guard_chain_operation_state_history_immutable() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'v2_chain_operation_state_immutable' USING ERRCODE='55000';
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_chain_operation_state_history_immutable
    BEFORE UPDATE OR DELETE ON trading.chain_operation_state_history
    FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_chain_operation_state_history_immutable();
"""
    )
    op.execute(
        """
CREATE FUNCTION trading.v2_guard_settlement_observation_immutable() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'v2_settlement_observation_immutable' USING ERRCODE='55000';
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_settlement_observations_immutable
    BEFORE UPDATE OR DELETE ON trading.settlement_observations
    FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_settlement_observation_immutable();
"""
    )
    op.execute(
        """
CREATE FUNCTION trading.v2_guard_settlement_observation_complete() RETURNS trigger AS $$
DECLARE row_count integer;
        identity_count integer;
        market_condition text;
        canonical_tokens jsonb;
BEGIN
    IF NEW.status <> 'COMPLETE' THEN
        RETURN NULL;
    END IF;
    IF NEW.raw_artifact_id IS NULL OR NOT EXISTS (
        SELECT 1 FROM trading.artifact_objects artifact
         WHERE artifact.id=NEW.raw_artifact_id
           AND artifact.sha256=NEW.raw_artifact_hash
    ) THEN
        RAISE EXCEPTION 'v2_settlement_observation_artifact_invalid:%',
            NEW.observation_key USING ERRCODE='55000';
    END IF;
    SELECT count(*), count(DISTINCT
        condition_id || ':' || market_id::text || ':' || token_set_hash || ':' ||
        source_cutoff::text)
      INTO row_count, identity_count
      FROM trading.settlement_observations
     WHERE settlement_set_key=NEW.settlement_set_key AND status='COMPLETE';
    IF row_count <> 5 OR identity_count <> 1 OR EXISTS (
        SELECT required.kind FROM (VALUES
          ('gamma_clob_closed'),('ctf_payout'),('data_api_redeemable'),
          ('clob_winner_5050'),('label_audit')) required(kind)
        WHERE NOT EXISTS (
          SELECT 1 FROM trading.settlement_observations o
           WHERE o.settlement_set_key=NEW.settlement_set_key
             AND o.status='COMPLETE' AND o.source_kind=required.kind)
    ) THEN
        RAISE EXCEPTION 'v2_settlement_observation_complete_set_missing:%',
            NEW.settlement_set_key USING ERRCODE='55000';
    END IF;
    SELECT condition_id INTO market_condition
      FROM trading.pm_markets WHERE id=NEW.market_id;
    SELECT jsonb_agg(t.token_id ORDER BY t.outcome_index) INTO canonical_tokens
      FROM trading.pm_tokens t WHERE t.market_id=NEW.market_id;
    IF market_condition IS DISTINCT FROM NEW.condition_id
       OR canonical_tokens IS DISTINCT FROM NEW.token_set
       OR EXISTS (
          SELECT 1 FROM trading.settlement_observations o
           WHERE o.settlement_set_key=NEW.settlement_set_key AND o.status='COMPLETE'
             AND (o.market_id<>NEW.market_id OR o.condition_id<>NEW.condition_id
                  OR o.token_set<>NEW.token_set OR o.token_set_hash<>NEW.token_set_hash
                  OR o.source_cutoff<>NEW.source_cutoff)
       ) THEN
        RAISE EXCEPTION 'v2_settlement_observation_identity_mismatch:%',
            NEW.settlement_set_key USING ERRCODE='55000';
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;
CREATE CONSTRAINT TRIGGER trg_settlement_observations_complete_set
    AFTER INSERT OR UPDATE ON trading.settlement_observations
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_settlement_observation_complete();
"""
    )
    op.execute(
        r"""
CREATE FUNCTION trading.v2_check_chain_operation_finality_complete() RETURNS trigger AS $$
DECLARE op_row trading.chain_operations%ROWTYPE;
        selected_registry trading.contract_registry%ROWTYPE;
        expected_bundle jsonb;
        bundle_count integer;
        ledger_count integer;
        namespace_count integer;
        expected_cash numeric;
        observed_cash numeric;
        pusd_address text;
BEGIN
    IF NEW.transition_to <> 'FINALIZED' THEN
        RETURN NULL;
    END IF;
    SELECT * INTO STRICT op_row FROM trading.chain_operations WHERE id=NEW.operation_id;
    SELECT * INTO STRICT selected_registry FROM trading.contract_registry
     WHERE id=op_row.registry_version_id;
    SELECT jsonb_object_agg(r.kind,r.content_hash ORDER BY r.kind),count(*),
           max(r.address) FILTER (WHERE r.kind='pusd')
      INTO expected_bundle,bundle_count,pusd_address
      FROM trading.contract_registry r
     WHERE r.chain_id=op_row.chain_id
       AND r.kind IN ('pusd','ctf','deposit_wallet',selected_registry.kind)
       AND op_row.registry_bundle ? r.kind
       AND r.content_hash=op_row.registry_bundle->>r.kind
       AND r.registry_version=selected_registry.registry_version
       AND r.version_no=selected_registry.version_no
       AND r.snapshot_block_number=selected_registry.snapshot_block_number
       AND r.snapshot_block_hash=selected_registry.snapshot_block_hash;
    SELECT count(*) INTO ledger_count FROM trading.ledger_transactions tx
     WHERE tx.chain_operation_id=op_row.id AND tx.kind='SETTLEMENT' AND tx.status='POSTED';
    SELECT count(DISTINCT item->>'portfolio_namespace'),
           COALESCE(sum((item->>'expected_cash_base_units')::numeric),0)
      INTO namespace_count,expected_cash
      FROM jsonb_array_elements(op_row.settlement_allocation) item;
    observed_cash := (op_row.post_balance->>'pusd')::numeric -
                     (op_row.pre_balance->>'pusd')::numeric;
    IF op_row.status <> 'FINALIZED' OR NOT op_row.economic_effect_applied
       OR bundle_count<>4 OR expected_bundle IS DISTINCT FROM op_row.registry_bundle
       OR encode(sha256(convert_to(expected_bundle::text,'UTF8')),'hex')<>
          op_row.registry_bundle_content_hash
       OR selected_registry.content_hash<>op_row.registry_content_hash
       OR NOT EXISTS (
          SELECT 1 FROM trading.artifact_objects a
           WHERE a.id=op_row.registry_evidence_artifact_id
             AND a.sha256=op_row.registry_evidence_hash)
       OR NOT EXISTS (
          SELECT 1 FROM trading.artifact_objects a
           WHERE a.id=op_row.balance_evidence_artifact_id
             AND a.sha256=op_row.balance_evidence_hash)
       OR ledger_count<>namespace_count OR ledger_count=0
       OR observed_cash<>expected_cash
       OR (SELECT count(*) FROM jsonb_object_keys(op_row.post_balance->'tokens'))<>2
       OR EXISTS (
          SELECT 1 FROM jsonb_each_text(op_row.post_balance->'tokens') b(token,quantity)
           WHERE quantity::numeric<>0 OR NOT (op_row.pre_balance->'tokens' ? token))
       OR EXISTS (
          SELECT 1 FROM jsonb_object_keys(op_row.pre_balance->'tokens') token
           WHERE NOT (op_row.post_balance->'tokens' ? token))
       OR EXISTS (
          SELECT 1 FROM jsonb_array_elements(op_row.settlement_allocation) item
           WHERE NOT EXISTS (
             SELECT 1 FROM trading.positions p JOIN trading.pm_tokens t ON t.id=p.token_id
              WHERE p.account_id=op_row.account_id AND p.market_id=op_row.market_id
                AND p.portfolio_namespace=item->>'portfolio_namespace'
                AND t.token_id=item->>'token_id' AND p.quantity=0))
       OR EXISTS (
          SELECT 1 FROM trading.positions p
           WHERE p.account_id=op_row.account_id AND p.market_id=op_row.market_id
             AND p.quantity<>0)
       OR EXISTS (
          SELECT 1 FROM jsonb_array_elements(op_row.settlement_allocation) item
           WHERE (SELECT count(*) FROM trading.ledger_transactions tx
                   WHERE tx.chain_operation_id=op_row.id AND tx.kind='SETTLEMENT'
                     AND tx.status='POSTED' AND tx.account_id=op_row.account_id
                     AND tx.portfolio_namespace=item->>'portfolio_namespace')<>1
              OR (SELECT count(*) FROM trading.ledger_postings p
                   JOIN trading.ledger_transactions tx ON tx.id=p.transaction_id
                  WHERE tx.chain_operation_id=op_row.id AND tx.kind='SETTLEMENT'
                    AND tx.portfolio_namespace=item->>'portfolio_namespace'
                    AND p.asset_type='TOKEN' AND p.asset_key=item->>'token_id'
                    AND p.amount=-(item->>'quantity_base_units')::numeric
                    AND p.counterparty=item->>'portfolio_namespace')<>1
              OR (SELECT count(*) FROM trading.ledger_postings p
                   JOIN trading.ledger_transactions tx ON tx.id=p.transaction_id
                  WHERE tx.chain_operation_id=op_row.id AND tx.kind='SETTLEMENT'
                    AND tx.portfolio_namespace=item->>'portfolio_namespace'
                    AND p.asset_type='TOKEN' AND p.asset_key=item->>'token_id'
                    AND p.amount=(item->>'quantity_base_units')::numeric
                    AND p.counterparty='ctf:redeem')<>1)
       OR EXISTS (
          SELECT 1 FROM (
            SELECT item->>'portfolio_namespace' namespace,
                   sum((item->>'expected_cash_base_units')::numeric) cash,
                   count(*) token_count
              FROM jsonb_array_elements(op_row.settlement_allocation) item GROUP BY 1
          ) alloc
          JOIN trading.ledger_transactions tx
            ON tx.chain_operation_id=op_row.id AND tx.kind='SETTLEMENT'
           AND tx.status='POSTED' AND tx.portfolio_namespace=alloc.namespace
          WHERE (SELECT count(*) FROM trading.ledger_postings p
                  WHERE p.transaction_id=tx.id) <>
                2*alloc.token_count + CASE WHEN alloc.cash>0 THEN 2 ELSE 0 END
             OR (alloc.cash>0 AND (
                (SELECT count(*) FROM trading.ledger_postings p
                  WHERE p.transaction_id=tx.id AND p.asset_type='CASH'
                    AND lower(p.asset_key)=lower(pusd_address) AND p.amount=alloc.cash
                    AND p.counterparty=alloc.namespace)<>1 OR
                (SELECT count(*) FROM trading.ledger_postings p
                  WHERE p.transaction_id=tx.id AND p.asset_type='CASH'
                    AND lower(p.asset_key)=lower(pusd_address) AND p.amount=-alloc.cash
                    AND p.counterparty='ctf:redeem')<>1))
             OR (alloc.cash=0 AND EXISTS (
                SELECT 1 FROM trading.ledger_postings p
                 WHERE p.transaction_id=tx.id AND p.asset_type='CASH')))
       OR NOT EXISTS (
          SELECT 1 FROM trading.chain_operation_state_history h
           WHERE h.operation_id=op_row.id AND h.transition_to='RELAYER_CONFIRMED')
       OR EXISTS (
          SELECT 1 FROM trading.chain_operation_state_history h
           WHERE h.operation_id=op_row.id AND h.transition_to='SETTLEMENT_CONFLICT')
       OR (SELECT count(*) FROM trading.settlement_observations o
            WHERE o.settlement_set_key=op_row.settlement_set_key
              AND o.condition_id=op_row.condition_id AND o.market_id=op_row.market_id
              AND o.status='COMPLETE')<>5
       OR NOT EXISTS (
          SELECT 1 FROM trading.workflow_events w
           WHERE w.aggregate_type='chain_operation' AND w.aggregate_id=op_row.operation_key
             AND w.event_type='SETTLEMENT_FINALIZED'
             AND w.payload->>'operation_id'=op_row.id::text
             AND w.payload->>'balance_artifact_hash'=op_row.balance_evidence_hash)
       OR NOT EXISTS (
          SELECT 1 FROM trading.transactional_outbox o
           WHERE o.aggregate_type='chain_operation' AND o.aggregate_id=op_row.operation_key
             AND o.topic='chain.settlement.finalized'
             AND o.payload->>'operation_id'=op_row.id::text
             AND o.payload->>'operation_key'=op_row.operation_key
             AND o.payload->>'cash_delta'=expected_cash::text
             AND o.payload->>'balance_artifact_hash'=op_row.balance_evidence_hash
             AND jsonb_typeof(o.payload->'ledger_transaction_ids')='array'
             AND (SELECT count(*) FROM jsonb_array_elements(o.payload->'ledger_transaction_ids'))=
                 ledger_count
             AND NOT EXISTS (
               SELECT 1 FROM trading.ledger_transactions tx
                WHERE tx.chain_operation_id=op_row.id AND tx.kind='SETTLEMENT'
                  AND tx.status='POSTED'
                  AND NOT (o.payload->'ledger_transaction_ids' @> to_jsonb(ARRAY[tx.id]))))
    THEN
        RAISE EXCEPTION 'v2_chain_operation_finality_effect_incomplete:%',op_row.id
        USING ERRCODE='55000';
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;
CREATE CONSTRAINT TRIGGER trg_chain_operations_finality_complete
    AFTER INSERT ON trading.chain_operation_state_history
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
    EXECUTE FUNCTION trading.v2_check_chain_operation_finality_complete();
"""
    )


def _drop_guards() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_contract_registry_immutable ON trading.contract_registry")
    op.execute("DROP TRIGGER IF EXISTS trg_contract_registry_publish_check ON trading.contract_registry")
    op.execute("DROP TRIGGER IF EXISTS trg_chain_operations_lifecycle ON trading.chain_operations")
    op.execute("DROP TRIGGER IF EXISTS trg_chain_operations_preflight ON trading.chain_operations")
    op.execute("DROP TRIGGER IF EXISTS trg_chain_operation_state_cas ON trading.chain_operation_state_history")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_chain_operation_state_history_immutable "
        "ON trading.chain_operation_state_history"
    )
    op.execute("DROP TRIGGER IF EXISTS trg_settlement_observations_immutable ON trading.settlement_observations")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_settlement_observations_complete_set "
        "ON trading.settlement_observations"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS trg_chain_operations_finality_complete "
        "ON trading.chain_operation_state_history"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_contract_registry_immutable()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_contract_registry_publish()")
    op.execute(
        "DROP FUNCTION IF EXISTS trading.v2_publish_contract_registry(text,text,integer,bigint,"
        "text,text,text,text,text,bigint,text,text,timestamptz,text,jsonb)"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_chain_operation_update()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_chain_operation_preflight()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_chain_operation_state()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_chain_operation_state_history_immutable()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_settlement_observation_immutable()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_settlement_observation_complete()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_check_chain_operation_finality_complete()")


def upgrade() -> None:
    for table in _NEW_TABLES:
        op.execute(table.create_sql)
    for table in _NEW_TABLES:
        for statement in table.index_sql:
            op.execute(statement)
    _add_lineage()
    _create_guards()


def downgrade() -> None:
    _assert_downgrade_safe()
    _drop_guards()
    _restore_wp05_real_fill_lineage()
    _drop_lineage()
    for table in reversed(_NEW_TABLES):
        op.execute(f"DROP TABLE IF EXISTS trading.{table.name}")
