"""gamma tag catalog + event attachment + admin page

Revision ID: b1000072
Revises: b1000071
Create Date: 2026-08-13 00:00:00

v2_0072 —— Gamma tag 目录、event 挂载、本地处置 overlay、Admin 菜单。

- ``upgrade``：
  - ``trading.pm_tags`` / ``trading.pm_event_tags``
  - 本地 ``disposition``（SELECT/DEFER/REJECT，可空）
  - ``v2:tags:view`` / ``v2:tags:manage`` 权限 + 可见 Tags 菜单页
- ``downgrade``：先 fail-closed preflight，再删菜单/权限/表。

fixed literal DDL；不 import live ORM；无密钥。
"""
from typing import Sequence, Union

from alembic import op

revision: str = "b1000072"
down_revision: Union[str, Sequence[str], None] = "b1000071"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_MENU_DIR_SLUG = "v2-admin"
_PERM_VIEW = ("v2-tags-view", "Tags", "v2:tags:view")
_PERM_MANAGE = ("v2-tags-manage", "Tags Manage", "v2:tags:manage")
_PAGE = (
    "v2-page-tags", "Tags", "/v2/tags", "v2/tags/index", "v2:tags:view", True, 15,
)
_ALL_SLUGS = (
    f"'{_PERM_VIEW[0]}', '{_PERM_MANAGE[0]}', '{_PAGE[0]}'"
)


def upgrade() -> None:
    op.execute(
        """
CREATE TABLE trading.pm_tags (
    gamma_tag_id TEXT COLLATE "C" NOT NULL,
    slug TEXT,
    label TEXT,
    seen_in_catalog BOOLEAN DEFAULT false NOT NULL,
    seen_in_event BOOLEAN DEFAULT false NOT NULL,
    disposition VARCHAR(16),
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    content_hash VARCHAR(64) COLLATE "C" NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_pm_tags_gamma_tag_id UNIQUE (gamma_tag_id),
    CONSTRAINT ck_pm_tags_seen_source CHECK (seen_in_catalog OR seen_in_event),
    CONSTRAINT ck_pm_tags_disposition_known
        CHECK (disposition IS NULL OR disposition IN ('SELECT','DEFER','REJECT'))
)
"""
    )
    op.execute("CREATE INDEX ix_pm_tags_slug ON trading.pm_tags (slug)")
    op.execute("CREATE INDEX ix_pm_tags_created_at ON trading.pm_tags (created_at, id)")
    op.execute(
        """
CREATE TABLE trading.pm_event_tags (
    gamma_event_id TEXT COLLATE "C" NOT NULL,
    gamma_tag_id TEXT COLLATE "C" NOT NULL,
    position INTEGER NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_pm_event_tags_event_tag UNIQUE (gamma_event_id, gamma_tag_id),
    CONSTRAINT ck_pm_event_tags_position_nonneg CHECK (position >= 0),
    CONSTRAINT fk_pm_event_tags_event FOREIGN KEY(gamma_event_id)
        REFERENCES trading.pm_events (gamma_event_id),
    CONSTRAINT fk_pm_event_tags_tag FOREIGN KEY(gamma_tag_id)
        REFERENCES trading.pm_tags (gamma_tag_id)
)
"""
    )
    op.execute("CREATE INDEX ix_pm_event_tags_tag ON trading.pm_event_tags (gamma_tag_id)")
    op.execute(
        f"""
DO $v2_wp_gamma_tags_menu$
DECLARE v2_dir bigint;
BEGIN
    IF to_regclass('public.menus') IS NULL THEN
        RETURN;
    END IF;
    SELECT id INTO v2_dir FROM public.menus WHERE slug = '{_MENU_DIR_SLUG}';
    IF v2_dir IS NULL THEN
        RAISE EXCEPTION 'v2_wp_gamma_tags_parent_missing:{_MENU_DIR_SLUG}'
        USING ERRCODE='55000';
    END IF;
    INSERT INTO public.menus (parent_id, type, slug, label, path, template_path, perms,
                              is_visible, sort, status)
    SELECT v2_dir, 2, '{_PERM_VIEW[0]}', '{_PERM_VIEW[1]}', NULL, NULL,
           '{_PERM_VIEW[2]}', false, 0, 1
     WHERE NOT EXISTS (SELECT 1 FROM public.menus m WHERE m.slug = '{_PERM_VIEW[0]}');
    INSERT INTO public.menus (parent_id, type, slug, label, path, template_path, perms,
                              is_visible, sort, status)
    SELECT v2_dir, 2, '{_PERM_MANAGE[0]}', '{_PERM_MANAGE[1]}', NULL, NULL,
           '{_PERM_MANAGE[2]}', false, 0, 1
     WHERE NOT EXISTS (SELECT 1 FROM public.menus m WHERE m.slug = '{_PERM_MANAGE[0]}');
    INSERT INTO public.menus (parent_id, type, slug, label, path, template_path, perms,
                              is_visible, sort, status)
    SELECT v2_dir, 1, '{_PAGE[0]}', '{_PAGE[1]}', '{_PAGE[2]}', '{_PAGE[3]}',
           '{_PAGE[4]}', {str(_PAGE[5]).lower()}, {_PAGE[6]}, 1
     WHERE NOT EXISTS (SELECT 1 FROM public.menus m WHERE m.slug = '{_PAGE[0]}');
    IF NOT EXISTS (SELECT 1 FROM public.menus WHERE slug = '{_PERM_VIEW[0]}')
       OR NOT EXISTS (SELECT 1 FROM public.menus WHERE slug = '{_PERM_MANAGE[0]}')
       OR NOT EXISTS (SELECT 1 FROM public.menus WHERE slug = '{_PAGE[0]}') THEN
        RAISE EXCEPTION 'v2_wp_gamma_tags_menu_seed_failed' USING ERRCODE='55000';
    END IF;
END $v2_wp_gamma_tags_menu$
"""
    )


def downgrade() -> None:
    op.execute(
        """
DO $v2_wp_gamma_tags_preflight$
DECLARE missing text;
        bound_count bigint;
BEGIN
    SELECT string_agg(name, ', ' ORDER BY name)
      INTO missing
      FROM (VALUES ('pm_tags'), ('pm_event_tags')) AS t(name)
     WHERE to_regclass('trading.' || name) IS NULL;
    IF missing IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp_gamma_tags_missing:%', missing
        USING ERRCODE='55000';
    END IF;
    IF to_regclass('public.menus') IS NOT NULL
       AND to_regclass('public.role_menus') IS NOT NULL THEN
        SELECT count(*) INTO bound_count
          FROM public.role_menus rm
          JOIN public.menus m ON m.id = rm.menu_id
         WHERE m.slug IN ({slugs});
        IF bound_count <> 0 THEN
            RAISE EXCEPTION 'v2_wp_gamma_tags_menu_bound' USING ERRCODE='55000';
        END IF;
    END IF;
END $v2_wp_gamma_tags_preflight$
""".format(slugs=_ALL_SLUGS)
    )
    op.execute(
        f"""
DO $v2_wp_gamma_tags_menu_cleanup$
BEGIN
    IF to_regclass('public.menus') IS NOT NULL THEN
        DELETE FROM public.menus WHERE slug IN ({_ALL_SLUGS});
    END IF;
END $v2_wp_gamma_tags_menu_cleanup$
"""
    )
    op.execute("DROP TABLE trading.pm_event_tags")
    op.execute("DROP TABLE trading.pm_tags")
