"""execution readiness vault accounts funds reservations fencing

Revision ID: b1000050
Revises: b1000041
Create Date: 2026-08-11 20:00:00

v2_0050 —— WP-05 Checkpoint B：vault 强化 + accounts / funds / reservations / fencing。

- ``upgrade``：
  - 非空 vault precondition：任一 vault 表有非空行且无法无歧义补齐 identity/AAD/version
    → RAISE ``VAULT_BACKFILL_DECISION_REQUIRED``（ERRCODE 55000），version 前进前整体回滚；
    禁止猜 secret kind 或解密旧值（本实现任何既有 vault 行都无法无歧义补齐 → 直接 raise）。
  - 强化 0002 三张 vault skeleton 表（不重建平行 vault）：
    secret_vault_entries 加 secret_kind / runtime_identity + CHECK 白名单；
    secret_vault_versions 加 version_no / aad_context / ciphertext_hash / status +
    (entry_id,version_no) 与 (key_id,key_version,nonce) 唯一 + 单 ACTIVE deferred trigger；
    secret_access_events 加 secret_version_id / identity / key_version / result。
  - 新建且只新建 5 张表：pm_accounts / pm_balance_allowance_snapshots /
    account_funds_current / capital_reservations / execution_leases。
  - guard：reservation 状态机（HELD→PROVIDER_BOUND|UNKNOWN|RELEASED；
    UNKNOWN→PROVIDER_BOUND|CONSUMED 禁直接 RELEASED；PROVIDER_BOUND→CONSUMED|RELEASED）、
    vault version 生命周期 + 单 active deferred、funds 恒等式 CHECK、
    lease UNIQUE(account_id,lease_role) + fencing_token>0。
- ``downgrade``：fail-closed preflight（未知 trading 对象 RAISE
  ``v2_wp05_execution_vault_unknown_object``，ERRCODE 55000，含动态分区子表白名单豁免），
  drop guards，逆序 DROP 5 表，撤销 vault 强化（恢复 0002 原样：重建 immutable trigger）。

fixed literal DDL；不 import live ORM 生成 DDL；无密钥。
"""
from dataclasses import dataclass
from typing import Sequence, Union

from alembic import op

TRADING_SCHEMA = "trading"

# revision identifiers, used by Alembic.
revision: str = "b1000050"
down_revision: Union[str, Sequence[str], None] = "b1000041"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_SECRET_KIND_VALUES = (
    "'generic','api_credential','signer_private_key','l2_secret','passphrase'"
)


@dataclass(frozen=True)
class _FrozenTableSpec:
    name: str
    create_sql: str
    index_sql: tuple[str, ...] = ()
    append_only: bool = False


_NEW_TABLES = (
    _FrozenTableSpec(
        name="pm_accounts",
        create_sql=(
            "\nCREATE TABLE trading.pm_accounts (\n"
            "\taccount_key TEXT COLLATE \"C\" NOT NULL, \n"
            "\tprovider VARCHAR(64) NOT NULL, \n"
            "\tchain_id BIGINT NOT NULL, \n"
            "\tidentity_type VARCHAR(32) NOT NULL, \n"
            "\tfunder_address TEXT COLLATE \"C\", \n"
            "\tmaker_address TEXT COLLATE \"C\", \n"
            "\tsigning_identity TEXT COLLATE \"C\", \n"
            "\twallet_type VARCHAR(64) NOT NULL, \n"
            "\tsignature_type VARCHAR(16) DEFAULT '3' NOT NULL, \n"
            "\tsigner_secret_entry_id BIGINT, \n"
            "\tsigner_secret_version_id BIGINT, \n"
            "\tl2_secret_entry_id BIGINT, \n"
            "\tl2_secret_version_id BIGINT, \n"
            "\trelease_manifest_id BIGINT NOT NULL, \n"
            "\tcapital_permission_manifest_id BIGINT NOT NULL, \n"
            "\tnetwork_mode VARCHAR(32) NOT NULL, \n"
            "\tstatus VARCHAR(32) DEFAULT 'active' NOT NULL, \n"
            "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n"
            "\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tPRIMARY KEY (id), \n"
            "\tCONSTRAINT uq_pm_accounts_key UNIQUE (account_key), \n"
            "\tCONSTRAINT ck_pm_accounts_identity_type_known "
            "CHECK (identity_type IN ('FIXTURE_ONLY','CANARY','LIVE')), \n"
            "\tCONSTRAINT ck_pm_accounts_wallet_type_known "
            "CHECK (wallet_type IN ('deposit_wallet','privately_owned')), \n"
            "\tCONSTRAINT ck_pm_accounts_signature_type_known "
            "CHECK (signature_type IN ('0','1','2','3')), \n"
            "\tCONSTRAINT ck_pm_accounts_network_mode_known "
            "CHECK (network_mode IN ('mainnet','matic_mumbai','amoy','fixture')), \n"
            "\tCONSTRAINT ck_pm_accounts_status_known CHECK (status IN ('active','disabled')), \n"
            "\tCONSTRAINT ck_pm_accounts_wp05_fixture_only "
            "CHECK (identity_type = 'FIXTURE_ONLY'), \n"
            "\tCONSTRAINT ck_pm_accounts_fixture_network_pair "
            "CHECK (identity_type = 'FIXTURE_ONLY' OR network_mode <> 'fixture'), \n"
            "\tCONSTRAINT fk_pm_accounts_release "
            "FOREIGN KEY(release_manifest_id) REFERENCES trading.release_manifests (id), \n"
            "\tCONSTRAINT fk_pm_accounts_capital FOREIGN KEY(capital_permission_manifest_id) "
            "REFERENCES trading.capital_permission_manifests (id), \n"
            "\tCONSTRAINT fk_pm_accounts_signer_entry FOREIGN KEY(signer_secret_entry_id) "
            "REFERENCES trading.secret_vault_entries (id), \n"
            "\tCONSTRAINT fk_pm_accounts_l2_entry FOREIGN KEY(l2_secret_entry_id) "
            "REFERENCES trading.secret_vault_entries (id)\n"
            ")\n\n"
        ),
    ),
    _FrozenTableSpec(
        name="pm_balance_allowance_snapshots",
        create_sql=(
            "\nCREATE TABLE trading.pm_balance_allowance_snapshots (\n"
            "\taccount_id BIGINT NOT NULL, \n"
            "\tasset_key TEXT COLLATE \"C\" NOT NULL, \n"
            "\tspender TEXT COLLATE \"C\", \n"
            "\tbalance NUMERIC(38, 0) NOT NULL, \n"
            "\tallowance NUMERIC(38, 0) NOT NULL, \n"
            "\tprovider_reserved NUMERIC(38, 0) NOT NULL, \n"
            "\tobserved_at TIMESTAMP WITH TIME ZONE NOT NULL, \n"
            "\trequest_hash VARCHAR(64) COLLATE \"C\" NOT NULL, \n"
            "\tfencing_token BIGINT NOT NULL, \n"
            "\tcompleteness VARCHAR(32) NOT NULL, \n"
            "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n"
            "\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tPRIMARY KEY (id), \n"
            "\tCONSTRAINT ck_pm_balance_allowance_snapshots_balance_nonneg "
            "CHECK (balance >= 0), \n"
            "\tCONSTRAINT ck_pm_balance_allowance_snapshots_allowance_nonneg "
            "CHECK (allowance >= 0), \n"
            "\tCONSTRAINT ck_pm_balance_allowance_snapshots_reserved_nonneg "
            "CHECK (provider_reserved >= 0), \n"
            "\tCONSTRAINT ck_pm_balance_allowance_snapshots_fencing_positive "
            "CHECK (fencing_token > 0), \n"
            "\tCONSTRAINT ck_pm_balance_allowance_snapshots_completeness_known "
            "CHECK (completeness IN ('COMPLETE','PARTIAL','STALE')), \n"
            "\tCONSTRAINT ck_pm_balance_allowance_snapshots_request_hash_hex "
            "CHECK (request_hash ~ '^[0-9a-f]{64}$'), \n"
            "\tCONSTRAINT fk_pm_balance_allowance_snapshots_account "
            "FOREIGN KEY(account_id) REFERENCES trading.pm_accounts (id)\n"
            ")\n\n"
        ),
        index_sql=(
            "CREATE INDEX ix_pm_balance_allowance_snapshots_account "
            "ON trading.pm_balance_allowance_snapshots (account_id, asset_key, observed_at)",
        ),
        append_only=True,
    ),
    _FrozenTableSpec(
        name="account_funds_current",
        create_sql=(
            "\nCREATE TABLE trading.account_funds_current (\n"
            "\taccount_id BIGINT NOT NULL, \n"
            "\tasset_key TEXT COLLATE \"C\" NOT NULL, \n"
            "\tconfirmed NUMERIC(38, 0) NOT NULL, \n"
            "\tprovider_reserved NUMERIC(38, 0) NOT NULL, \n"
            "\tlocal_reserved NUMERIC(38, 0) NOT NULL, \n"
            "\tavailable NUMERIC(38, 0) NOT NULL, \n"
            "\tsource_snapshot_id BIGINT NOT NULL, \n"
            "\treconcile_watermark BIGINT NOT NULL, \n"
            "\tversion INTEGER DEFAULT 1 NOT NULL, \n"
            "\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n"
            "\tPRIMARY KEY (id), \n"
            "\tCONSTRAINT uq_account_funds_current_account_asset "
            "UNIQUE (account_id, asset_key), \n"
            "\tCONSTRAINT ck_account_funds_current_confirmed_nonneg CHECK (confirmed >= 0), \n"
            "\tCONSTRAINT ck_account_funds_current_provider_reserved_nonneg "
            "CHECK (provider_reserved >= 0), \n"
            "\tCONSTRAINT ck_account_funds_current_local_reserved_nonneg "
            "CHECK (local_reserved >= 0), \n"
            "\tCONSTRAINT ck_account_funds_current_available_nonneg CHECK (available >= 0), \n"
            "\tCONSTRAINT ck_account_funds_current_identity "
            "CHECK (available = confirmed - provider_reserved - local_reserved), \n"
            "\tCONSTRAINT ck_account_funds_current_reconcile_watermark_nonneg "
            "CHECK (reconcile_watermark >= 0), \n"
            "\tCONSTRAINT fk_account_funds_current_account "
            "FOREIGN KEY(account_id) REFERENCES trading.pm_accounts (id)\n"
            ")\n\n"
        ),
    ),
    _FrozenTableSpec(
        name="capital_reservations",
        create_sql=(
            "\nCREATE TABLE trading.capital_reservations (\n"
            "\treservation_key TEXT COLLATE \"C\" NOT NULL, \n"
            "\tintent_id BIGINT NOT NULL, \n"
            "\taccount_id BIGINT NOT NULL, \n"
            "\tasset_key TEXT COLLATE \"C\" NOT NULL, \n"
            "\tamount NUMERIC(38, 0) NOT NULL, \n"
            "\tidempotency_key VARCHAR(255) NOT NULL, \n"
            "\tstatus VARCHAR(32) DEFAULT 'HELD' NOT NULL, \n"
            "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n"
            "\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tPRIMARY KEY (id), \n"
            "\tCONSTRAINT uq_capital_reservations_key UNIQUE (reservation_key), \n"
            "\tCONSTRAINT uq_capital_reservations_idempotency "
            "UNIQUE (account_id, asset_key, idempotency_key), \n"
            "\tCONSTRAINT ck_capital_reservations_amount_positive CHECK (amount > 0), \n"
            "\tCONSTRAINT ck_capital_reservations_status_known CHECK (status IN "
            "('HELD','UNKNOWN','PROVIDER_BOUND','CONSUMED','RELEASED')), \n"
            "\tCONSTRAINT fk_capital_reservations_intent "
            "FOREIGN KEY(intent_id) REFERENCES trading.economic_action_intents (id), \n"
            "\tCONSTRAINT fk_capital_reservations_account "
            "FOREIGN KEY(account_id) REFERENCES trading.pm_accounts (id)\n"
            ")\n\n"
        ),
        index_sql=(
            "CREATE INDEX ix_capital_reservations_intent "
            "ON trading.capital_reservations (intent_id)",
            "CREATE INDEX ix_capital_reservations_account "
            "ON trading.capital_reservations (account_id)",
        ),
    ),
    _FrozenTableSpec(
        name="execution_leases",
        create_sql=(
            "\nCREATE TABLE trading.execution_leases (\n"
            "\taccount_id BIGINT NOT NULL, \n"
            "\tlease_role VARCHAR(16) NOT NULL, \n"
            "\towner TEXT COLLATE \"C\" NOT NULL, \n"
            "\tlease_until TIMESTAMP WITH TIME ZONE NOT NULL, \n"
            "\tfencing_token BIGINT NOT NULL, \n"
            "\tlatest_heartbeat_id VARCHAR(255), \n"
            "\tlatest_heartbeat_hash VARCHAR(64) COLLATE \"C\", \n"
            "\tversion INTEGER DEFAULT 1 NOT NULL, \n"
            "\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n"
            "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n"
            "\tPRIMARY KEY (id), \n"
            "\tCONSTRAINT uq_execution_leases_account_role "
            "UNIQUE (account_id, lease_role), \n"
            "\tCONSTRAINT ck_execution_leases_role_known "
            "CHECK (lease_role IN ('EXECUTION','HEARTBEAT')), \n"
            "\tCONSTRAINT ck_execution_leases_fencing_positive CHECK (fencing_token > 0), \n"
            "\tCONSTRAINT ck_execution_leases_owner_nonempty "
            "CHECK (length(btrim(owner)) > 0), \n"
            "\tCONSTRAINT fk_execution_leases_account "
            "FOREIGN KEY(account_id) REFERENCES trading.pm_accounts (id)\n"
            ")\n\n"
        ),
    ),
)

# b1000041 已存在的 trading 关系（0050 downgrade preflight allowlist = 0041 的 pre-0041 全量
# + 0040 的 14 张 learning 表 + 0041 的 5 张投影表）。
_PRE_0050_RELATIONS = (
    "artifact_objects", "artifact_lineage_edges", "archive_manifests",
    "retention_manifests", "runtime_config_versions", "strategy_objective_contracts",
    "strategy_versions", "execution_spec_versions", "capital_permission_manifests",
    "model_role_bindings", "release_manifests", "policy_type_scopes", "policy_freezes",
    "secret_vault_entries", "secret_vault_versions", "secret_access_events",
    "idempotency_claims", "transactional_outbox", "outbox_delivery_history",
    "job_completions", "pm_universe_frames", "pm_universe_frame_pages", "pm_events",
    "pm_markets", "pm_market_versions", "pm_tokens", "pm_token_versions",
    "pm_market_lifecycle_events", "pm_market_current", "pm_connection_epochs",
    "pm_source_event_batches", "pm_source_event_index", "pm_book_checkpoints",
    "pm_book_levels", "pm_book_current", "pm_quote_bindings", "contract_snapshots",
    "contract_specs", "payout_functions", "forecast_components", "world_schema_versions",
    "forecast_component_versions", "forecast_component_contract_specs",
    "portfolio_dependency_edges", "evaluation_cohorts", "universe_memberships",
    "screening_episodes", "audit_samples", "decision_opportunities",
    "decision_opportunity_markets", "episode_memberships", "forecast_episodes",
    "episode_contract_specs", "information_snapshots", "information_snapshot_items",
    "gate_decisions", "priors", "evidence_coverage_policies", "evidence_revisions",
    "evidence_bundles", "evidence_bundle_items", "forecast_input_manifests",
    "forecast_submissions", "payout_projections", "coherence_checks",
    "forecast_challenges", "forecast_leases", "ai_invocations", "ai_tool_calls",
    "ai_validation_results", "market_relative_decisions", "discrepancy_reviews",
    "trade_decisions", "action_candidates", "resolution_cashflows", "action_sets",
    "action_set_legs", "underwriting_plans", "economic_action_intents",
    "executions", "positions", "position_lots", "ledger_transactions",
    "ledger_postings", "operating_cost_entries",
    # b1000040 learning facts（14 张）
    "resolution_labels", "resolution_clusters", "resolution_cluster_memberships",
    "score_targets", "score_target_memberships", "score_observations", "experiments",
    "experiment_variants", "challenger_variants", "metric_runs", "error_reviews",
    "ablation_runs", "promotion_decisions", "replay_runs",
    # b1000041 read projections（5 张）
    "ops_health_current", "pipeline_funnel_hourly", "account_risk_current",
    "provider_cost_daily", "latest_chain_summary",
)


def _assert_downgrade_safe() -> None:
    allowed = ", ".join(
        f"'{name}'" for name in (*_PRE_0050_RELATIONS, *(t.name for t in _NEW_TABLES))
    )
    owned = ", ".join(f"'{t.name}'" for t in _NEW_TABLES)
    known_indexes = ", ".join(
        f"'{statement.split(' ON ')[0].replace('CREATE INDEX ', '').strip()}'"
        for table in _NEW_TABLES for statement in table.index_sql
    ) or "''"
    known_triggers = ", ".join(
        f"'{name}'" for name in (
            *(f"trg_{t.name}_immutable" for t in _NEW_TABLES if t.append_only),
            "trg_capital_reservations_lifecycle",
        )
    )
    op.execute(
        f"""
DO $v2_wp05_execution_vault_preflight$
DECLARE unknown_objects text;
        unknown_indexes text;
        unknown_triggers text;
BEGIN
    SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
      INTO unknown_objects
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'trading'
       AND c.relkind IN ('r','p','v','m','f')
       AND c.relname NOT IN ({allowed})
       AND NOT EXISTS (
           SELECT 1 FROM pg_inherits i
           JOIN pg_class p ON p.oid = i.inhparent
           JOIN pg_namespace pn ON pn.oid = p.relnamespace
           WHERE i.inhrelid = c.oid AND pn.nspname = 'trading'
             AND ((p.relname = 'outbox_delivery_history'
                   AND c.relname ~ '^outbox_delivery_history_[0-9]{{6}}$')
               OR (p.relname IN ('pm_source_event_batches','pm_source_event_index',
                                  'pm_book_checkpoints','pm_book_levels')
                   AND c.relname ~ ('^' || p.relname || '_[0-9]{{8}}$'))
               OR (p.relname IN ('ai_invocations','ai_tool_calls','ai_validation_results')
                   AND c.relname ~ ('^' || p.relname || '_[0-9]{{6}}$')))
       );
    IF unknown_objects IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp05_execution_vault_unknown_object:%', unknown_objects
        USING ERRCODE='55000';
    END IF;
    SELECT string_agg(idx.relname, ', ' ORDER BY idx.relname)
      INTO unknown_indexes
      FROM pg_index i
      JOIN pg_class idx ON idx.oid=i.indexrelid
      JOIN pg_class tbl ON tbl.oid=i.indrelid
      JOIN pg_namespace n ON n.oid=tbl.relnamespace
     WHERE n.nspname='trading' AND tbl.relname IN ({owned})
       AND NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conindid=idx.oid)
       AND idx.relname NOT IN ({known_indexes});
    IF unknown_indexes IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp05_execution_vault_unknown_index:%', unknown_indexes
        USING ERRCODE='55000';
    END IF;
    SELECT string_agg(t.tgname, ', ' ORDER BY t.tgname)
      INTO unknown_triggers
      FROM pg_trigger t
      JOIN pg_class tbl ON tbl.oid=t.tgrelid
      JOIN pg_namespace n ON n.oid=tbl.relnamespace
     WHERE n.nspname='trading' AND tbl.relname IN ({owned})
       AND NOT t.tgisinternal AND t.tgname NOT IN ({known_triggers});
    IF unknown_triggers IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp05_execution_vault_unknown_trigger:%', unknown_triggers
        USING ERRCODE='55000';
    END IF;
END $v2_wp05_execution_vault_preflight$
"""
    )


def _assert_vault_backfillable() -> None:
    """非空 vault precondition：任何既有 vault 行都无法无歧义补齐 identity/AAD/version。

    本实现从不解密旧值、从不猜 secret kind；因此任一 vault 表有非空行即 RAISE
    ``VAULT_BACKFILL_DECISION_REQUIRED``（ERRCODE 55000）。env.py 单外层事务保证该
    DO 块抛错时 version 不前进并整体回滚。
    """
    op.execute(
        f"""
DO $v2_wp05_vault_backfill_precondition$
DECLARE vault_hits integer;
BEGIN
    SELECT (
        (SELECT count(*) FROM trading.secret_vault_entries)
        + (SELECT count(*) FROM trading.secret_vault_versions)
        + (SELECT count(*) FROM trading.secret_access_events)
    ) INTO vault_hits;
    IF vault_hits <> 0 THEN
        RAISE EXCEPTION 'VAULT_BACKFILL_DECISION_REQUIRED:'
            'existing vault rows require an explicit identity/AAD/version backfill'
        USING ERRCODE='55000';
    END IF;
END $v2_wp05_vault_backfill_precondition$
"""
    )


def _strengthen_vault() -> None:
    """强化 0002 三张 vault skeleton 表；不重建平行 vault。"""
    # secret_vault_entries：secret kind 白名单 + execution-plane identity。
    op.execute(
        "ALTER TABLE trading.secret_vault_entries "
        "ADD COLUMN secret_kind VARCHAR(32) NOT NULL"
    )
    op.execute(
        "ALTER TABLE trading.secret_vault_entries "
        "ADD COLUMN runtime_identity TEXT COLLATE \"C\" NOT NULL"
    )
    op.execute(
        "ALTER TABLE trading.secret_vault_entries "
        f"ADD CONSTRAINT ck_secret_vault_entries_secret_kind_known "
        f"CHECK (secret_kind IN ({_SECRET_KIND_VALUES}))"
    )
    # secret_vault_versions：version_no / AAD context / ciphertext hash / status。
    op.execute(
        "ALTER TABLE trading.secret_vault_versions "
        "ADD COLUMN version_no INTEGER NOT NULL"
    )
    op.execute(
        "ALTER TABLE trading.secret_vault_versions "
        "ADD COLUMN aad_context JSONB NOT NULL"
    )
    op.execute(
        "ALTER TABLE trading.secret_vault_versions "
        "ADD COLUMN ciphertext_hash VARCHAR(64) COLLATE \"C\" NOT NULL"
    )
    op.execute(
        "ALTER TABLE trading.secret_vault_versions "
        "ADD COLUMN status VARCHAR(32) DEFAULT 'active' NOT NULL"
    )
    op.execute(
        "ALTER TABLE trading.secret_vault_versions "
        "ADD CONSTRAINT uq_secret_vault_versions_entry_version "
        "UNIQUE (entry_id, version_no)"
    )
    op.execute(
        "ALTER TABLE trading.secret_vault_versions "
        "ADD CONSTRAINT uq_secret_vault_versions_key_nonce "
        "UNIQUE (key_id, key_version, nonce)"
    )
    op.execute(
        "ALTER TABLE trading.secret_vault_versions "
        "ADD CONSTRAINT ck_secret_vault_versions_status_known "
        "CHECK (status IN ('active','retired'))"
    )
    op.execute(
        "ALTER TABLE trading.secret_vault_versions "
        "ADD CONSTRAINT ck_secret_vault_versions_ciphertext_hash_hex "
        "CHECK (ciphertext_hash ~ '^[0-9a-f]{64}$')"
    )
    # secret_access_events：版本/身份/key version/结果。
    op.execute(
        "ALTER TABLE trading.secret_access_events "
        "ADD COLUMN secret_version_id BIGINT"
    )
    op.execute(
        "ALTER TABLE trading.secret_access_events "
        "ADD COLUMN identity VARCHAR(255)"
    )
    op.execute(
        "ALTER TABLE trading.secret_access_events "
        "ADD COLUMN key_version VARCHAR(64)"
    )
    op.execute(
        "ALTER TABLE trading.secret_access_events "
        "ADD COLUMN result VARCHAR(64)"
    )
    op.execute(
        "ALTER TABLE trading.secret_access_events "
        "ADD CONSTRAINT fk_secret_access_events_version "
        "FOREIGN KEY(secret_version_id) REFERENCES trading.secret_vault_versions (id) "
        "ON DELETE SET NULL"
    )


def _unstrengthen_vault() -> None:
    """撤销 0050 对 vault 的强化，降回 0002 原样。"""
    op.execute(
        "ALTER TABLE trading.secret_access_events "
        "DROP CONSTRAINT IF EXISTS fk_secret_access_events_version"
    )
    op.execute("ALTER TABLE trading.secret_access_events DROP COLUMN IF EXISTS result")
    op.execute("ALTER TABLE trading.secret_access_events DROP COLUMN IF EXISTS key_version")
    op.execute("ALTER TABLE trading.secret_access_events DROP COLUMN IF EXISTS identity")
    op.execute("ALTER TABLE trading.secret_access_events DROP COLUMN IF EXISTS secret_version_id")
    op.execute(
        "ALTER TABLE trading.secret_vault_versions "
        "DROP CONSTRAINT IF EXISTS ck_secret_vault_versions_ciphertext_hash_hex"
    )
    op.execute(
        "ALTER TABLE trading.secret_vault_versions "
        "DROP CONSTRAINT IF EXISTS ck_secret_vault_versions_status_known"
    )
    op.execute(
        "ALTER TABLE trading.secret_vault_versions "
        "DROP CONSTRAINT IF EXISTS uq_secret_vault_versions_key_nonce"
    )
    op.execute(
        "ALTER TABLE trading.secret_vault_versions "
        "DROP CONSTRAINT IF EXISTS uq_secret_vault_versions_entry_version"
    )
    op.execute("ALTER TABLE trading.secret_vault_versions DROP COLUMN IF EXISTS status")
    op.execute("ALTER TABLE trading.secret_vault_versions DROP COLUMN IF EXISTS ciphertext_hash")
    op.execute("ALTER TABLE trading.secret_vault_versions DROP COLUMN IF EXISTS aad_context")
    op.execute("ALTER TABLE trading.secret_vault_versions DROP COLUMN IF EXISTS version_no")
    op.execute(
        "ALTER TABLE trading.secret_vault_entries "
        "DROP CONSTRAINT IF EXISTS ck_secret_vault_entries_secret_kind_known"
    )
    op.execute(
        "ALTER TABLE trading.secret_vault_entries DROP COLUMN IF EXISTS runtime_identity"
    )
    op.execute(
        "ALTER TABLE trading.secret_vault_entries DROP COLUMN IF EXISTS secret_kind"
    )


def _create_vault_version_guards() -> None:
    """替换 0002 的纯 immutable trigger 为带 active→retired 生命周期的 guard。"""
    op.execute(
        "DROP TRIGGER IF EXISTS trg_secret_vault_versions_immutable "
        "ON trading.secret_vault_versions"
    )
    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_vault_version() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_vault_version_immutable' USING ERRCODE='55000';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.status NOT IN ('active','retired') THEN
            RAISE EXCEPTION 'v2_vault_version_initial_state_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF (to_jsonb(NEW) - 'status') IS DISTINCT FROM (to_jsonb(OLD) - 'status') THEN
        RAISE EXCEPTION 'v2_vault_version_immutable' USING ERRCODE='55000';
    END IF;
    IF NEW.status = OLD.status
       OR NEW.status NOT IN ('active','retired')
       OR OLD.status NOT IN ('active','retired') THEN
        RAISE EXCEPTION 'v2_vault_version_transition_invalid' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_secret_vault_versions_lifecycle "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.secret_vault_versions "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_vault_version()"
    )
    op.execute(
        r"""
CREATE FUNCTION trading.v2_check_vault_single_active() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE active_count integer;
BEGIN
    SELECT count(*) INTO active_count
      FROM trading.secret_vault_versions
     WHERE entry_id = NEW.entry_id AND status = 'active';
    IF active_count > 1 THEN
        RAISE EXCEPTION 'v2_vault_entry_multiple_active' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER trg_secret_vault_versions_single_active "
        "AFTER INSERT OR UPDATE OF status ON trading.secret_vault_versions "
        "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
        "EXECUTE FUNCTION trading.v2_check_vault_single_active()"
    )


def _drop_vault_version_guards() -> None:
    """撤销 0050 vault version guard，重建 0002 的 immutable trigger。"""
    op.execute(
        "DROP TRIGGER IF EXISTS trg_secret_vault_versions_single_active "
        "ON trading.secret_vault_versions"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_check_vault_single_active()")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_secret_vault_versions_lifecycle "
        "ON trading.secret_vault_versions"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_vault_version()")
    op.execute(
        "CREATE TRIGGER trg_secret_vault_versions_immutable "
        "BEFORE UPDATE OR DELETE ON trading.secret_vault_versions "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_reject_immutable_row()"
    )


def _create_guards() -> None:
    """新建 5 张表的 guard：append-only snapshot、reservation 状态机。"""
    for table in _NEW_TABLES:
        if table.append_only:
            op.execute(
                f"CREATE TRIGGER trg_{table.name}_immutable "
                f"BEFORE UPDATE OR DELETE ON {TRADING_SCHEMA}.{table.name} "
                "FOR EACH ROW EXECUTE FUNCTION trading.v2_reject_immutable_row()"
            )
    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_capital_reservation() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_reservation_immutable' USING ERRCODE='55000';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'HELD' THEN
            RAISE EXCEPTION 'v2_reservation_initial_state_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF (to_jsonb(NEW) - 'status' - 'updated_at') IS DISTINCT FROM
       (to_jsonb(OLD) - 'status' - 'updated_at') THEN
        RAISE EXCEPTION 'v2_reservation_payload_immutable' USING ERRCODE='55000';
    END IF;
    IF NOT (
        (OLD.status = 'HELD' AND NEW.status IN ('PROVIDER_BOUND','UNKNOWN','RELEASED'))
        OR (OLD.status = 'UNKNOWN' AND NEW.status IN ('PROVIDER_BOUND','CONSUMED'))
        OR (OLD.status = 'PROVIDER_BOUND' AND NEW.status IN ('CONSUMED','RELEASED'))
    ) THEN
        RAISE EXCEPTION 'v2_reservation_transition_invalid' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_capital_reservations_lifecycle "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.capital_reservations "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_capital_reservation()"
    )


def _drop_guards() -> None:
    op.execute(
        "DROP TRIGGER IF EXISTS trg_capital_reservations_lifecycle "
        "ON trading.capital_reservations"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_capital_reservation()")
    for table in reversed(_NEW_TABLES):
        if table.append_only:
            op.execute(
                f"DROP TRIGGER IF EXISTS trg_{table.name}_immutable "
                f"ON {TRADING_SCHEMA}.{table.name}"
            )


def upgrade() -> None:
    _assert_vault_backfillable()
    _strengthen_vault()
    _create_vault_version_guards()
    for table in _NEW_TABLES:
        op.execute(table.create_sql)
        for statement in table.index_sql:
            op.execute(statement)
    _create_guards()


def downgrade() -> None:
    _assert_downgrade_safe()
    _drop_guards()
    for table in reversed(_NEW_TABLES):
        op.execute(f"DROP TABLE {TRADING_SCHEMA}.{table.name}")
    _drop_vault_version_guards()
    _unstrengthen_vault()
