"""create trading foundation

Revision ID: b1000002
Revises: b1000001
Create Date: 2026-08-10 04:30:00

v2_0002 —— Trading foundation：``trading`` schema + 20 张 foundation 表（WP-01A-02）。

- ``upgrade``：创建 ``trading`` schema 与 20 张表（artifact/control/vault/outbox），
  不调用 ``Base.metadata.create_all()``，不改 ``public`` Base 对象/seed/menu/legacy runner。
  ``outbox_delivery_history`` 按 ``completed_at`` 月 RANGE 分区，创建升级当月及后两月分区。
- ``downgrade``：按依赖逆序删除 20 张表与空的 ``trading`` schema；非空/未知对象 fail-closed，
  不用 ``CASCADE``。
- 迁移遵守 env.py 单 run 外层事务 / advisory lock / search path / offline SQL 合同。
"""
from dataclasses import dataclass
from datetime import date, datetime, timezone
from typing import Sequence, Union

from alembic import op

TRADING_SCHEMA = "trading"

# revision identifiers, used by Alembic.
revision: str = "b1000002"
down_revision: Union[str, Sequence[str], None] = "b1000001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Alembic revisions are immutable.  The DDL below is a literal snapshot: importing live
# ORM metadata here would make a future model edit silently rewrite historical b1000002.
@dataclass(frozen=True)
class _FrozenTableSpec:
    name: str
    create_sql: str
    index_sql: tuple[str, ...] = ()

_FOUNDATION_TABLES = (
    _FrozenTableSpec(
        name='artifact_objects',
        create_sql='\nCREATE TABLE trading.artifact_objects (\n\tsha256 VARCHAR(64) COLLATE "C" NOT NULL, \n\toriginal_size NUMERIC(38, 0) NOT NULL, \n\tstored_size NUMERIC(38, 0) NOT NULL, \n\tmime VARCHAR(255) NOT NULL, \n\tcompression VARCHAR(32) DEFAULT \'none\' NOT NULL, \n\tstorage_driver VARCHAR(64) NOT NULL, \n\tstorage_version TEXT COLLATE "C" NOT NULL, \n\tlocator TEXT NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_artifact_objects_storage_key UNIQUE (sha256, compression, storage_driver, storage_version), \n\tCONSTRAINT ck_artifact_objects_sha256_lower_hex CHECK (sha256 ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_artifact_objects_original_size_nonneg CHECK (original_size >= 0), \n\tCONSTRAINT ck_artifact_objects_stored_size_nonneg CHECK (stored_size >= 0), \n\tCONSTRAINT ck_artifact_objects_raw_size_equal CHECK (compression <> \'none\' OR original_size = stored_size), \n\tCONSTRAINT ck_artifact_objects_compression_known CHECK (compression IN (\'none\',\'zstd\')), \n\tCONSTRAINT ck_artifact_objects_storage_driver_known CHECK (storage_driver IN (\'local\',\'s3\')), \n\tCONSTRAINT ck_artifact_objects_storage_version_known CHECK (storage_version = \'cas/v1\'), \n\tCONSTRAINT ck_artifact_objects_mime_valid CHECK (length(mime) > 0 AND position(chr(10) in mime) = 0 AND position(chr(13) in mime) = 0), \n\tCONSTRAINT ck_artifact_objects_locator_canonical CHECK (locator = \'cas/v1/sha256/\' || substr(sha256,1,2) || \'/\' || substr(sha256,3,2) || \'/\' || sha256 || CASE WHEN compression = \'zstd\' THEN \'.zst\' ELSE \'.raw\' END)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='artifact_lineage_edges',
        create_sql='\nCREATE TABLE trading.artifact_lineage_edges (\n\tfrom_artifact_id BIGINT NOT NULL, \n\tto_artifact_id BIGINT NOT NULL, \n\trelation VARCHAR(64) NOT NULL, \n\tinvocation_ref TEXT COLLATE "C", \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_artifact_lineage_edges_edge UNIQUE (from_artifact_id, to_artifact_id, relation), \n\tCONSTRAINT ck_artifact_lineage_edges_no_self CHECK (from_artifact_id <> to_artifact_id), \n\tCONSTRAINT ck_artifact_lineage_edges_relation_known CHECK (relation IN (\'derived\',\'supersedes\',\'references\',\'raw\')), \n\tCONSTRAINT fk_artifact_lineage_edges_from_artifact FOREIGN KEY(from_artifact_id) REFERENCES trading.artifact_objects (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_artifact_lineage_edges_to_artifact FOREIGN KEY(to_artifact_id) REFERENCES trading.artifact_objects (id) ON DELETE CASCADE\n)\n\n',
    ),
    _FrozenTableSpec(
        name='archive_manifests',
        create_sql='\nCREATE TABLE trading.archive_manifests (\n\tcontent JSONB NOT NULL, \n\tcontent_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tstatus VARCHAR(32) DEFAULT \'staged\' NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_archive_manifests_content_object CHECK (jsonb_typeof(content) = \'object\'), \n\tCONSTRAINT ck_archive_manifests_status_known CHECK (status IN (\'staged\',\'committed\'))\n)\n\n',
        index_sql=('CREATE INDEX ix_archive_manifests_content_hash ON trading.archive_manifests (content_hash)',),
    ),
    _FrozenTableSpec(
        name='retention_manifests',
        create_sql='\nCREATE TABLE trading.retention_manifests (\n\tcontent JSONB NOT NULL, \n\tcontent_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tstatus VARCHAR(32) DEFAULT \'staged\' NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_retention_manifests_content_object CHECK (jsonb_typeof(content) = \'object\'), \n\tCONSTRAINT ck_retention_manifests_status_known CHECK (status IN (\'staged\',\'committed\'))\n)\n\n',
        index_sql=('CREATE INDEX ix_retention_manifests_content_hash ON trading.retention_manifests (content_hash)',),
    ),
    _FrozenTableSpec(
        name='runtime_config_versions',
        create_sql='\nCREATE TABLE trading.runtime_config_versions (\n\tconfig_key TEXT COLLATE "C" NOT NULL, \n\tversion_no INTEGER NOT NULL, \n\tcontent JSONB NOT NULL, \n\tschema_version INTEGER NOT NULL, \n\tcontent_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tstatus VARCHAR(32) DEFAULT \'draft\' NOT NULL, \n\tcreator TEXT COLLATE "C", \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_runtime_config_versions_key_version UNIQUE (config_key, version_no), \n\tCONSTRAINT ck_runtime_config_versions_content_object CHECK (jsonb_typeof(content) = \'object\'), \n\tCONSTRAINT ck_runtime_config_versions_status_known CHECK (status IN (\'draft\', \'active\', \'retired\', \'rejected\'))\n)\n\n',
    ),
    _FrozenTableSpec(
        name='strategy_objective_contracts',
        create_sql='\nCREATE TABLE trading.strategy_objective_contracts (\n\tcontract_key TEXT COLLATE "C" NOT NULL, \n\tversion_no INTEGER NOT NULL, \n\tcontent JSONB NOT NULL, \n\tschema_version INTEGER NOT NULL, \n\tcontent_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tstatus VARCHAR(32) DEFAULT \'draft\' NOT NULL, \n\tcreator TEXT COLLATE "C", \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_strategy_objective_contracts_key_version UNIQUE (contract_key, version_no), \n\tCONSTRAINT ck_strategy_objective_contracts_content_object CHECK (jsonb_typeof(content) = \'object\'), \n\tCONSTRAINT ck_strategy_objective_contracts_status_known CHECK (status IN (\'draft\', \'active\', \'retired\', \'rejected\'))\n)\n\n',
    ),
    _FrozenTableSpec(
        name='strategy_versions',
        create_sql='\nCREATE TABLE trading.strategy_versions (\n\tstrategy_key TEXT COLLATE "C" NOT NULL, \n\tversion_no INTEGER NOT NULL, \n\tcontent JSONB NOT NULL, \n\tschema_version INTEGER NOT NULL, \n\tcontent_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tstatus VARCHAR(32) DEFAULT \'draft\' NOT NULL, \n\tcreator TEXT COLLATE "C", \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_strategy_versions_key_version UNIQUE (strategy_key, version_no), \n\tCONSTRAINT ck_strategy_versions_content_object CHECK (jsonb_typeof(content) = \'object\'), \n\tCONSTRAINT ck_strategy_versions_status_known CHECK (status IN (\'draft\', \'active\', \'retired\', \'rejected\'))\n)\n\n',
    ),
    _FrozenTableSpec(
        name='execution_spec_versions',
        create_sql='\nCREATE TABLE trading.execution_spec_versions (\n\tspec_key TEXT COLLATE "C" NOT NULL, \n\tversion_no INTEGER NOT NULL, \n\tcontent JSONB NOT NULL, \n\tschema_version INTEGER NOT NULL, \n\tcontent_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tstatus VARCHAR(32) DEFAULT \'draft\' NOT NULL, \n\tcreator TEXT COLLATE "C", \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_execution_spec_versions_key_version UNIQUE (spec_key, version_no), \n\tCONSTRAINT ck_execution_spec_versions_content_object CHECK (jsonb_typeof(content) = \'object\'), \n\tCONSTRAINT ck_execution_spec_versions_status_known CHECK (status IN (\'draft\', \'active\', \'retired\', \'rejected\'))\n)\n\n',
    ),
    _FrozenTableSpec(
        name='capital_permission_manifests',
        create_sql='\nCREATE TABLE trading.capital_permission_manifests (\n\tname TEXT COLLATE "C" NOT NULL, \n\tmode VARCHAR(32) NOT NULL, \n\tcapability JSONB NOT NULL, \n\tlimits JSONB NOT NULL, \n\tevaluation_capital NUMERIC(38, 0) NOT NULL, \n\tauthorized_capital NUMERIC(38, 0) NOT NULL, \n\tkill_switch BOOLEAN DEFAULT \'false\' NOT NULL, \n\tcontent_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tstatus VARCHAR(32) DEFAULT \'draft\' NOT NULL, \n\tcreator TEXT COLLATE "C", \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_capital_permission_manifests_eval_cap_nonneg CHECK (evaluation_capital >= 0), \n\tCONSTRAINT ck_capital_permission_manifests_auth_cap_nonneg CHECK (authorized_capital >= 0), \n\tCONSTRAINT ck_capital_permission_manifests_mode_known CHECK (mode IN (\'shadow\',\'canary\',\'live\')), \n\tCONSTRAINT ck_capital_permission_manifests_capability_object CHECK (jsonb_typeof(capability) = \'object\'), \n\tCONSTRAINT ck_capital_permission_manifests_limits_object CHECK (jsonb_typeof(limits) = \'object\'), \n\tCONSTRAINT ck_capital_permission_manifests_status_known CHECK (status IN (\'draft\', \'active\', \'retired\', \'rejected\'))\n)\n\n',
    ),
    _FrozenTableSpec(
        name='model_role_bindings',
        create_sql='\nCREATE TABLE trading.model_role_bindings (\n\tstrategy_version_id BIGINT NOT NULL, \n\trole VARCHAR(64) NOT NULL, \n\tmodel_ref TEXT COLLATE "C" NOT NULL, \n\tcontent_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_model_role_bindings_strategy_role UNIQUE (strategy_version_id, role), \n\tCONSTRAINT fk_model_role_bindings_strategy_version FOREIGN KEY(strategy_version_id) REFERENCES trading.strategy_versions (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='release_manifests',
        create_sql='\nCREATE TABLE trading.release_manifests (\n\trelease_name TEXT COLLATE "C" NOT NULL, \n\tconfig_version_id BIGINT NOT NULL, \n\tstrategy_version_id BIGINT NOT NULL, \n\texecution_spec_version_id BIGINT NOT NULL, \n\tcapital_permission_manifest_id BIGINT NOT NULL, \n\tgit_sha VARCHAR(64) COLLATE "C" NOT NULL, \n\timage_digest VARCHAR(255) NOT NULL, \n\tdb_revision VARCHAR(64) NOT NULL, \n\ttotal_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tstatus VARCHAR(32) DEFAULT \'draft\' NOT NULL, \n\tcreator TEXT COLLATE "C", \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_release_manifests_status_known CHECK (status IN (\'draft\', \'active\', \'retired\', \'rejected\')), \n\tCONSTRAINT fk_release_manifests_config FOREIGN KEY(config_version_id) REFERENCES trading.runtime_config_versions (id), \n\tCONSTRAINT fk_release_manifests_strategy FOREIGN KEY(strategy_version_id) REFERENCES trading.strategy_versions (id), \n\tCONSTRAINT fk_release_manifests_execution FOREIGN KEY(execution_spec_version_id) REFERENCES trading.execution_spec_versions (id), \n\tCONSTRAINT fk_release_manifests_capital FOREIGN KEY(capital_permission_manifest_id) REFERENCES trading.capital_permission_manifests (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='policy_type_scopes',
        create_sql='\nCREATE TABLE trading.policy_type_scopes (\n\tpolicy_type VARCHAR(64) NOT NULL, \n\tscope_type VARCHAR(64) NOT NULL, \n\tscope_key TEXT COLLATE "C" NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_policy_type_scopes_triple UNIQUE (policy_type, scope_type, scope_key)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='policy_freezes',
        create_sql='\nCREATE TABLE trading.policy_freezes (\n\tpolicy_content_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\trelease_manifest_id BIGINT NOT NULL, \n\tstatus VARCHAR(32) DEFAULT \'frozen\' NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_policy_freezes_status_known CHECK (status IN (\'frozen\',\'released\')), \n\tCONSTRAINT fk_policy_freezes_release FOREIGN KEY(release_manifest_id) REFERENCES trading.release_manifests (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='secret_vault_entries',
        create_sql='\nCREATE TABLE trading.secret_vault_entries (\n\tname TEXT COLLATE "C" NOT NULL, \n\tstatus VARCHAR(32) DEFAULT \'active\' NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_secret_vault_entries_name UNIQUE (name), \n\tCONSTRAINT ck_secret_vault_entries_status_known CHECK (status IN (\'active\',\'disabled\'))\n)\n\n',
    ),
    _FrozenTableSpec(
        name='secret_vault_versions',
        create_sql='\nCREATE TABLE trading.secret_vault_versions (\n\tentry_id BIGINT NOT NULL, \n\tkey_id TEXT COLLATE "C" NOT NULL, \n\tkey_version TEXT COLLATE "C" NOT NULL, \n\tnonce TEXT COLLATE "C" NOT NULL, \n\tciphertext BYTEA NOT NULL, \n\taad_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\talgorithm VARCHAR(64) NOT NULL, \n\tsupersedes BIGINT, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_secret_vault_versions_algorithm_known CHECK (algorithm = \'aes-256-gcm\'), \n\tCONSTRAINT fk_secret_vault_versions_entry FOREIGN KEY(entry_id) REFERENCES trading.secret_vault_entries (id), \n\tCONSTRAINT fk_secret_vault_versions_supersedes FOREIGN KEY(supersedes) REFERENCES trading.secret_vault_versions (id) ON DELETE SET NULL\n)\n\n',
    ),
    _FrozenTableSpec(
        name='secret_access_events',
        create_sql='\nCREATE TABLE trading.secret_access_events (\n\tentry_id BIGINT NOT NULL, \n\tsubject TEXT COLLATE "C" NOT NULL, \n\tpurpose VARCHAR(128) NOT NULL, \n\tresult_reason VARCHAR(64) NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT fk_secret_access_events_entry FOREIGN KEY(entry_id) REFERENCES trading.secret_vault_entries (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='idempotency_claims',
        create_sql='\nCREATE TABLE trading.idempotency_claims (\n\tscope TEXT COLLATE "C" NOT NULL, \n\tkey TEXT COLLATE "C" NOT NULL, \n\towner TEXT COLLATE "C", \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_idempotency_claims_scope_key UNIQUE (scope, key)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='transactional_outbox',
        create_sql='\nCREATE TABLE trading.transactional_outbox (\n\tevent_id VARCHAR(64) COLLATE "C" NOT NULL, \n\ttopic VARCHAR(128) NOT NULL, \n\tschema_version INTEGER NOT NULL, \n\taggregate_type VARCHAR(64) NOT NULL, \n\taggregate_id TEXT COLLATE "C" NOT NULL, \n\tidempotency_key VARCHAR(255) NOT NULL, \n\trelease_manifest_id BIGINT, \n\tpriority SMALLINT DEFAULT \'128\' NOT NULL, \n\tpayload JSONB, \n\tartifact_ref VARCHAR(64) COLLATE "C", \n\tstatus VARCHAR(32) DEFAULT \'PENDING\' NOT NULL, \n\tattempt INTEGER DEFAULT \'0\' NOT NULL, \n\tavailable_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeadline TIMESTAMP WITH TIME ZONE, \n\tvisibility_deadline TIMESTAMP WITH TIME ZONE, \n\tlease_owner TEXT COLLATE "C", \n\tlease_token TEXT COLLATE "C", \n\terror_reason VARCHAR(128), \n\terror_at TIMESTAMP WITH TIME ZONE, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_transactional_outbox_event_id UNIQUE (event_id), \n\tCONSTRAINT ck_transactional_outbox_status_known CHECK (status IN (\'PENDING\',\'DISPATCHED\',\'COMPLETED\',\'DEAD\')), \n\tCONSTRAINT ck_transactional_outbox_payload_object CHECK (jsonb_typeof(payload) = \'object\'), \n\tCONSTRAINT ck_transactional_outbox_payload_xor_artifact CHECK ((payload IS NOT NULL) <> (artifact_ref IS NOT NULL)), \n\tCONSTRAINT ck_transactional_outbox_priority_range CHECK (priority BETWEEN 0 AND 255), \n\tCONSTRAINT fk_transactional_outbox_release FOREIGN KEY(release_manifest_id) REFERENCES trading.release_manifests (id)\n)\n\n',
        index_sql=("CREATE INDEX ix_transactional_outbox_pending ON trading.transactional_outbox (available_at, id) WHERE status = 'PENDING'",),
    ),
    _FrozenTableSpec(
        name='outbox_delivery_history',
        create_sql='\nCREATE TABLE trading.outbox_delivery_history (\n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\toutbox_event_id VARCHAR(64) COLLATE "C" NOT NULL, \n\toutbox_id BIGINT NOT NULL, \n\tcompleted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tstatus VARCHAR(32) NOT NULL, \n\tconsumer VARCHAR(64) NOT NULL, \n\tattempt INTEGER NOT NULL, \n\terror_reason VARCHAR(128), \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id, completed_at), \n\tCONSTRAINT ck_outbox_delivery_history_status_known CHECK (status IN (\'DELIVERED\',\'DEAD\',\'EXPIRED\',\'REQUEUED\'))\n)\n PARTITION BY RANGE (completed_at)\n\n',
        index_sql=('CREATE INDEX ix_outbox_delivery_history_event ON trading.outbox_delivery_history (outbox_event_id)',),
    ),
    _FrozenTableSpec(
        name='job_completions',
        create_sql="\nCREATE TABLE trading.job_completions (\n\tconsumer VARCHAR(64) NOT NULL, \n\tidempotency_key VARCHAR(255) NOT NULL, \n\toutcome VARCHAR(32) NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_job_completions_consumer_key UNIQUE (consumer, idempotency_key), \n\tCONSTRAINT ck_job_completions_outcome_known CHECK (outcome IN ('success','failed','dead'))\n)\n\n",
    ),
)

_IMMUTABLE_TABLES = (
    "artifact_objects",
    "artifact_lineage_edges",
    "secret_vault_versions",
    "secret_access_events",
    "idempotency_claims",
    "outbox_delivery_history",
    "job_completions",
)

_LIFECYCLE_MANIFEST_TABLES = (
    "archive_manifests",
    "retention_manifests",
)

_CONTROL_VERSION_TABLES = (
    "runtime_config_versions",
    "strategy_objective_contracts",
    "strategy_versions",
    "execution_spec_versions",
    "capital_permission_manifests",
    "release_manifests",
)

_IMMUTABLE_CONTROL_TABLES = (
    "policy_type_scopes",
)


def _trading_tables_in_order():
    """Return the revision-frozen 20-table dependency order."""
    return _FOUNDATION_TABLES


def _create_table_ddl(table: _FrozenTableSpec) -> str:
    return table.create_sql


def _drop_table_ddl(table: _FrozenTableSpec) -> str:
    return f"DROP TABLE {TRADING_SCHEMA}.{table.name}"


def _month_bounds(anchor: date, offset: int):
    """anchor 月 + offset 的 [start, end) 月份边界。"""
    y, m = anchor.year, anchor.month
    total = y * 12 + (m - 1) + offset
    sy, sm = divmod(total, 12)
    start = date(sy, sm + 1, 1)
    ey, em = divmod(total + 1, 12)
    end = date(ey, em + 1, 1)
    return start, end


def _partition_names(anchor: date):
    for offset in (0, 1, 2):
        start, end = _month_bounds(anchor, offset)
        name = f"outbox_delivery_history_{start:%Y%m}"
        yield name, start, end


def _create_table_indexes(table: _FrozenTableSpec) -> None:
    for statement in table.index_sql:
        op.execute(statement)


def _create_partitions(anchor: date) -> None:
    for name, start, end in _partition_names(anchor):
        op.execute(
            f"CREATE TABLE {TRADING_SCHEMA}.{name} PARTITION OF "
            f"{TRADING_SCHEMA}.outbox_delivery_history "
            f"FOR VALUES FROM ('{start.isoformat()} 00:00:00+00') "
            f"TO ('{end.isoformat()} 00:00:00+00')"
        )


def _drop_partitions(anchor: date) -> None:
    # 分区子表随父表 DROP 一并删除；这里只做兜底幂等（正常路径父表已带分区）。
    for name, _s, _e in _partition_names(anchor):
        op.execute(f"DROP TABLE IF EXISTS {TRADING_SCHEMA}.{name}")


def _create_immutability_guards() -> None:
    """Install database-enforced append-only and published-content guards."""
    op.execute(
        "CREATE FUNCTION trading.v2_reject_immutable_row() RETURNS trigger "
        "LANGUAGE plpgsql AS $v2_guard$ "
        "BEGIN "
        "  RAISE EXCEPTION 'v2_immutable_row:%', TG_TABLE_NAME USING ERRCODE='55000'; "
        "END $v2_guard$"
    )
    for table_name in _IMMUTABLE_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table_name}_immutable "
            f"BEFORE UPDATE OR DELETE ON {TRADING_SCHEMA}.{table_name} "
            "FOR EACH ROW EXECUTE FUNCTION trading.v2_reject_immutable_row()"
        )
    for table_name in _IMMUTABLE_CONTROL_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table_name}_immutable "
            f"BEFORE UPDATE OR DELETE ON {TRADING_SCHEMA}.{table_name} "
            "FOR EACH ROW EXECUTE FUNCTION trading.v2_reject_immutable_row()"
        )

    op.execute(
        "CREATE FUNCTION trading.v2_guard_vault_entry() RETURNS trigger "
        "LANGUAGE plpgsql AS $v2_guard$ "
        "BEGIN "
        "  IF TG_OP = 'UPDATE' "
        "     AND OLD.status = 'active' AND NEW.status = 'disabled' "
        "     AND (to_jsonb(NEW) - 'status') = (to_jsonb(OLD) - 'status') THEN "
        "    RETURN NEW; "
        "  END IF; "
        "  RAISE EXCEPTION 'v2_vault_entry_immutable' USING ERRCODE='55000'; "
        "END $v2_guard$"
    )
    op.execute(
        "CREATE TRIGGER trg_secret_vault_entries_lifecycle "
        "BEFORE UPDATE OR DELETE ON trading.secret_vault_entries "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_vault_entry()"
    )

    op.execute(
        "CREATE FUNCTION trading.v2_guard_manifest_lifecycle() RETURNS trigger "
        "LANGUAGE plpgsql AS $v2_guard$ "
        "BEGIN "
        "  IF TG_OP = 'UPDATE' "
        "     AND OLD.status = 'staged' AND NEW.status = 'committed' "
        "     AND (to_jsonb(NEW) - 'status') = (to_jsonb(OLD) - 'status') THEN "
        "    RETURN NEW; "
        "  END IF; "
        "  RAISE EXCEPTION 'v2_manifest_immutable:%', TG_TABLE_NAME USING ERRCODE='55000'; "
        "END $v2_guard$"
    )
    for table_name in _LIFECYCLE_MANIFEST_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table_name}_lifecycle "
            f"BEFORE UPDATE OR DELETE ON {TRADING_SCHEMA}.{table_name} "
            "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_manifest_lifecycle()"
        )

    op.execute(
        "CREATE FUNCTION trading.v2_guard_published_control() RETURNS trigger "
        "LANGUAGE plpgsql AS $v2_guard$ "
        "DECLARE payload_unchanged boolean; transition_allowed boolean; "
        "BEGIN "
        "  IF TG_OP = 'DELETE' THEN "
        "    IF OLD.status = 'draft' THEN RETURN OLD; END IF; "
        "    RAISE EXCEPTION 'v2_published_control_immutable:%', TG_TABLE_NAME "
        "      USING ERRCODE='55000'; "
        "  END IF; "
        "  payload_unchanged := "
        "    (to_jsonb(NEW) - 'status' - 'updated_at') = "
        "    (to_jsonb(OLD) - 'status' - 'updated_at'); "
        "  transition_allowed := "
        "    NEW.status = OLD.status "
        "    OR (OLD.status = 'draft' AND NEW.status IN ('active','rejected')) "
        "    OR (OLD.status = 'active' AND NEW.status = 'retired'); "
        "  IF NOT transition_allowed THEN "
        "    RAISE EXCEPTION 'v2_control_transition_invalid:%', TG_TABLE_NAME "
        "      USING ERRCODE='55000'; "
        "  END IF; "
        "  IF OLD.status <> 'draft' AND NOT payload_unchanged THEN "
        "    RAISE EXCEPTION 'v2_published_control_immutable:%', TG_TABLE_NAME "
        "      USING ERRCODE='55000'; "
        "  END IF; "
        "  IF NEW.status <> OLD.status AND NOT payload_unchanged THEN "
        "    RAISE EXCEPTION 'v2_control_publish_payload_changed:%', TG_TABLE_NAME "
        "      USING ERRCODE='55000'; "
        "  END IF; "
        "  RETURN NEW; "
        "END $v2_guard$"
    )
    for table_name in _CONTROL_VERSION_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table_name}_published_guard "
            f"BEFORE UPDATE OR DELETE ON {TRADING_SCHEMA}.{table_name} "
            "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_published_control()"
        )

    op.execute(
        "CREATE FUNCTION trading.v2_guard_model_role_binding() RETURNS trigger "
        "LANGUAGE plpgsql AS $v2_guard$ "
        "DECLARE old_status text; new_status text; "
        "BEGIN "
        "  IF TG_OP IN ('UPDATE','DELETE') THEN "
        "    SELECT status INTO old_status FROM trading.strategy_versions "
        "      WHERE id = OLD.strategy_version_id; "
        "    IF old_status IS DISTINCT FROM 'draft' THEN "
        "      RAISE EXCEPTION 'v2_published_model_binding_immutable' USING ERRCODE='55000'; "
        "    END IF; "
        "  END IF; "
        "  IF TG_OP IN ('INSERT','UPDATE') THEN "
        "    SELECT status INTO new_status FROM trading.strategy_versions "
        "      WHERE id = NEW.strategy_version_id; "
        "    IF new_status IS DISTINCT FROM 'draft' THEN "
        "      RAISE EXCEPTION 'v2_published_model_binding_immutable' USING ERRCODE='55000'; "
        "    END IF; "
        "  END IF; "
        "  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF; "
        "  RETURN NEW; "
        "END $v2_guard$"
    )
    op.execute(
        "CREATE TRIGGER trg_model_role_bindings_published_guard "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.model_role_bindings "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_model_role_binding()"
    )

    op.execute(
        "CREATE FUNCTION trading.v2_guard_policy_freeze() RETURNS trigger "
        "LANGUAGE plpgsql AS $v2_guard$ "
        "BEGIN "
        "  IF TG_OP = 'UPDATE' "
        "     AND OLD.status = 'frozen' AND NEW.status = 'released' "
        "     AND (to_jsonb(NEW) - 'status') = (to_jsonb(OLD) - 'status') THEN "
        "    RETURN NEW; "
        "  END IF; "
        "  RAISE EXCEPTION 'v2_policy_freeze_immutable' USING ERRCODE='55000'; "
        "END $v2_guard$"
    )
    op.execute(
        "CREATE TRIGGER trg_policy_freezes_lifecycle "
        "BEFORE UPDATE OR DELETE ON trading.policy_freezes "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_policy_freeze()"
    )


def _drop_immutability_guard_functions() -> None:
    op.execute("DROP FUNCTION trading.v2_guard_policy_freeze()")
    op.execute("DROP FUNCTION trading.v2_guard_model_role_binding()")
    op.execute("DROP FUNCTION trading.v2_guard_published_control()")
    op.execute("DROP FUNCTION trading.v2_guard_manifest_lifecycle()")
    op.execute("DROP FUNCTION trading.v2_guard_vault_entry()")
    op.execute("DROP FUNCTION trading.v2_reject_immutable_row()")


def upgrade() -> None:
    """Create trading schema + 20 foundation tables + current/next-2-month partitions."""
    op.execute(f"CREATE SCHEMA {TRADING_SCHEMA}")

    for table in _trading_tables_in_order():
        op.execute(_create_table_ddl(table))
        _create_table_indexes(table)

    _create_partitions(datetime.now(timezone.utc).date())
    _create_immutability_guards()


def downgrade() -> None:
    """Drop 20 tables (reverse dependency order) + empty trading schema; fail-closed, no CASCADE."""
    for table in reversed(_trading_tables_in_order()):
        op.execute(_drop_table_ddl(table))

    _drop_immutability_guard_functions()

    # fail-closed：20 张表 DROP 后若 schema 仍非空（未知对象），禁止删除 schema 并抛错；
    # 不用 CASCADE。正常路径 schema 为空 → 只删空的 trading schema。
    op.execute(
        "DO $v2_drop_schema$ "
        "DECLARE remaining integer; "
        "BEGIN "
        "  IF EXISTS (SELECT 1 FROM pg_namespace n WHERE n.nspname = 'trading') THEN "
        "    SELECT count(*) INTO remaining FROM pg_class c "
        "      JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='trading'; "
        "    IF remaining = 0 THEN "
        "      EXECUTE 'DROP SCHEMA trading'; "
        "    ELSE "
        "      RAISE EXCEPTION 'v2_trading_schema_not_empty'; "
        "    END IF; "
        "  END IF; "
        "END $v2_drop_schema$"
    )
