"""create p3 learning settlement / evaluation / audit

Revision ID: b1000040
Revises: b1000031
Create Date: 2026-08-11 16:00:00

v2_0040 —— Label 审计、五层评价、科学回放、G8（WP-04 Checkpoint B）。

- ``upgrade``：
  - 14 张表（全部 append-only，复用 0002 的 ``v2_reject_immutable_row``）：
    resolution_labels / resolution_clusters / resolution_cluster_memberships /
    score_targets / score_target_memberships / score_observations / experiments /
    experiment_variants / challenger_variants / metric_runs / error_reviews /
    ablation_runs / promotion_decisions / replay_runs。
  - resolution_labels 状态机 deferred guard：pending→provisional→disputed|final_*，
    supersede 同 contract、version 连续、前一状态允许、每 (contract,label_key) 单 current。
  - resolution_clusters：OPEN cluster 不得引用 final_admissible label；相同 contract_spec
    不得属于两个 active cluster version（deferred）。
  - score_target_memberships：member_weight 定点数，deferred 核验每 target 总和=1、
    token 双计禁止。
  - score_observations：label_version 必须 final_admissible（BEFORE trigger）。
  - metric_runs lifecycle guard：RUNNING→COMPLETED|FAILED|INVALIDATED，terminal 禁改。
  - promotion_decisions：``NOT (promotion_type='capital' AND status='APPROVED')`` CHECK。
  - ``gate_decisions`` 强化：G8 + target_kind=metric_run；deferred trigger
    ``v2_validate_gate_g8`` 校验 metric run COMPLETED 且 release 与 version_manifest 一致。
- ``downgrade``：先 fail-closed preflight（未知 trading 对象 RAISE），drop guards，撤销
  gate_decisions G8 强化，逆序删 14 表。
"""
from dataclasses import dataclass
from typing import Sequence, Union

from alembic import op

TRADING_SCHEMA = "trading"

# revision identifiers, used by Alembic.
revision: str = "b1000040"
down_revision: Union[str, Sequence[str], None] = "b1000031"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_GATES_0031 = ("G0", "R0", "G1", "G2", "R1", "G4", "G5A", "G5B", "G6", "G7A", "G7B")
_GATES_0040 = (*_GATES_0031, "G8")


@dataclass(frozen=True)
class _FrozenTableSpec:
    name: str
    create_sql: str
    index_sql: tuple[str, ...] = ()
    append_only: bool = True


_LEARNING_TABLES = (
    _FrozenTableSpec(
        name='resolution_clusters',
        create_sql='\nCREATE TABLE trading.resolution_clusters (\n\tcluster_key TEXT COLLATE "C" NOT NULL, \n\tcluster_version INTEGER NOT NULL, \n\tsplit VARCHAR(16) NOT NULL, \n\ttime_block_start TIMESTAMP WITH TIME ZONE NOT NULL, \n\ttime_block_end TIMESTAMP WITH TIME ZONE NOT NULL, \n\thorizon VARCHAR(64) NOT NULL, \n\tstatus VARCHAR(16) DEFAULT \'OPEN\' NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_resolution_clusters_key_version UNIQUE (cluster_key, cluster_version), \n\tCONSTRAINT ck_resolution_clusters_split_known CHECK (split IN (\'train\',\'validation\',\'forward_holdout\')), \n\tCONSTRAINT ck_resolution_clusters_block_order CHECK (time_block_end > time_block_start), \n\tCONSTRAINT ck_resolution_clusters_status_known CHECK (status IN (\'OPEN\',\'FROZEN\',\'RESOLVED\'))\n)\n\n',
    ),
    _FrozenTableSpec(
        name='score_targets',
        create_sql='\nCREATE TABLE trading.score_targets (\n\ttarget_key TEXT COLLATE "C" NOT NULL, \n\ttarget_type VARCHAR(16) NOT NULL, \n\tcontract_spec_id BIGINT NOT NULL, \n\tpayout_function_id BIGINT, \n\tcanonical_side VARCHAR(8), \n\tmembers JSONB, \n\tpayout_type VARCHAR(32), \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_score_targets_key UNIQUE (target_key), \n\tCONSTRAINT ck_score_targets_type_known CHECK (target_type IN (\'bernoulli\',\'multiclass\',\'mean_only\')), \n\tCONSTRAINT ck_score_targets_bernoulli_shape CHECK ((target_type = \'bernoulli\') = (canonical_side IS NOT NULL AND members IS NULL)), \n\tCONSTRAINT ck_score_targets_multiclass_shape CHECK ((target_type = \'multiclass\') = (members IS NOT NULL AND jsonb_typeof(members) = \'array\' AND canonical_side IS NULL)), \n\tCONSTRAINT ck_score_targets_mean_shape CHECK (target_type <> \'mean_only\' OR (canonical_side IS NULL AND members IS NULL)), \n\tCONSTRAINT ck_score_targets_side_known CHECK (canonical_side IS NULL OR canonical_side IN (\'YES\',\'NO\')), \n\tCONSTRAINT fk_score_targets_spec FOREIGN KEY(contract_spec_id) REFERENCES trading.contract_specs (id), \n\tCONSTRAINT fk_score_targets_payout FOREIGN KEY(payout_function_id) REFERENCES trading.payout_functions (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='resolution_labels',
        create_sql='\nCREATE TABLE trading.resolution_labels (\n\tcontract_spec_id BIGINT NOT NULL, \n\tlabel_key TEXT COLLATE "C" NOT NULL, \n\tversion_no INTEGER NOT NULL, \n\tstate VARCHAR(32) NOT NULL, \n\tresolution_state VARCHAR(64), \n\tresolution_source VARCHAR(128), \n\tevidence_artifact_id BIGINT, \n\traw_outcome JSONB, \n\ttoken_cashflow JSONB, \n\tpolicy_code_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tsupersedes_id BIGINT, \n\tauditor_identity VARCHAR(128), \n\texclusion_reason VARCHAR(255), \n\tconflict_set JSONB, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_resolution_labels_identity UNIQUE (contract_spec_id, label_key, version_no), \n\tCONSTRAINT ck_resolution_labels_state_known CHECK (state IN (\'pending\',\'provisional\',\'disputed\',\'final_admissible\',\'final_excluded\')), \n\tCONSTRAINT ck_resolution_labels_admissible_shape CHECK (state <> \'final_admissible\' OR (resolution_state IS NOT NULL AND exclusion_reason IS NULL)), \n\tCONSTRAINT ck_resolution_labels_excluded_reason CHECK (state <> \'final_excluded\' OR exclusion_reason IS NOT NULL), \n\tCONSTRAINT ck_resolution_labels_disputed_conflict CHECK (state <> \'disputed\' OR (conflict_set IS NOT NULL AND jsonb_typeof(conflict_set) = \'array\')), \n\tCONSTRAINT ck_resolution_labels_policy_hash_hex CHECK (policy_code_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_resolution_labels_first_version CHECK ((supersedes_id IS NULL) = (version_no = 1)), \n\tCONSTRAINT fk_resolution_labels_spec FOREIGN KEY(contract_spec_id) REFERENCES trading.contract_specs (id), \n\tCONSTRAINT fk_resolution_labels_evidence FOREIGN KEY(evidence_artifact_id) REFERENCES trading.artifact_objects (id), \n\tCONSTRAINT fk_resolution_labels_supersedes FOREIGN KEY(supersedes_id) REFERENCES trading.resolution_labels (id)\n)\n\n',
        index_sql=(
            'CREATE INDEX ix_resolution_labels_contract ON trading.resolution_labels (contract_spec_id)',
            'CREATE INDEX ix_resolution_labels_label_key ON trading.resolution_labels (label_key)',
        ),
    ),
    _FrozenTableSpec(
        name='experiments',
        create_sql='\nCREATE TABLE trading.experiments (\n\texperiment_key TEXT COLLATE "C" NOT NULL, \n\thypothesis TEXT NOT NULL, \n\thypothesis_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tprimary_metric VARCHAR(64) NOT NULL, \n\tguardrails JSONB NOT NULL, \n\tunique_change_field VARCHAR(128) NOT NULL, \n\tchampion_input_manifest_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tchallenger_input_manifest_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tsample_policy JSONB NOT NULL, \n\tstopping_rule JSONB NOT NULL, \n\tseed BIGINT NOT NULL, \n\tstatus VARCHAR(16) DEFAULT \'PLANNED\' NOT NULL, \n\ttime_block_start TIMESTAMP WITH TIME ZONE NOT NULL, \n\ttime_block_end TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_experiments_key UNIQUE (experiment_key), \n\tCONSTRAINT ck_experiments_status_known CHECK (status IN (\'PLANNED\',\'RUNNING\',\'COMPLETED\',\'INVALIDATED\')), \n\tCONSTRAINT ck_experiments_hypothesis_hash_hex CHECK (hypothesis_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_experiments_champion_hash_hex CHECK (champion_input_manifest_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_experiments_challenger_hash_hex CHECK (challenger_input_manifest_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_experiments_distinct_manifests CHECK (champion_input_manifest_hash <> challenger_input_manifest_hash), \n\tCONSTRAINT ck_experiments_guardrails_object CHECK (jsonb_typeof(guardrails) = \'object\'), \n\tCONSTRAINT ck_experiments_sample_policy_object CHECK (jsonb_typeof(sample_policy) = \'object\'), \n\tCONSTRAINT ck_experiments_stopping_rule_object CHECK (jsonb_typeof(stopping_rule) = \'object\'), \n\tCONSTRAINT ck_experiments_block_order CHECK (time_block_end > time_block_start)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='metric_runs',
        create_sql='\nCREATE TABLE trading.metric_runs (\n\trun_key TEXT COLLATE "C" NOT NULL, \n\tcohort_query_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tstrategy_version_id BIGINT NOT NULL, \n\trelease_manifest_id BIGINT NOT NULL, \n\tlabel_versions JSONB NOT NULL, \n\tsplit VARCHAR(16) NOT NULL, \n\ttime_blocks JSONB NOT NULL, \n\tcode_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tconfig_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tseed BIGINT NOT NULL, \n\tn_market INTEGER NOT NULL, \n\tn_episode INTEGER NOT NULL, \n\tn_resolution_cluster INTEGER NOT NULL, \n\tn_eff NUMERIC(38, 12) NOT NULL, \n\tresults JSONB NOT NULL, \n\tci JSONB NOT NULL, \n\tartifact_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tstatus VARCHAR(16) DEFAULT \'RUNNING\' NOT NULL, \n\tcompleted_at TIMESTAMP WITH TIME ZONE, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_metric_runs_key UNIQUE (run_key), \n\tCONSTRAINT ck_metric_runs_status_known CHECK (status IN (\'RUNNING\',\'COMPLETED\',\'FAILED\',\'INVALIDATED\')), \n\tCONSTRAINT ck_metric_runs_completed_pair CHECK ((status = \'COMPLETED\') = (completed_at IS NOT NULL)), \n\tCONSTRAINT ck_metric_runs_cohort_hash_hex CHECK (cohort_query_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_metric_runs_code_hash_hex CHECK (code_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_metric_runs_config_hash_hex CHECK (config_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_metric_runs_artifact_hash_hex CHECK (artifact_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_metric_runs_label_versions_object CHECK (jsonb_typeof(label_versions) = \'object\'), \n\tCONSTRAINT ck_metric_runs_time_blocks_object CHECK (jsonb_typeof(time_blocks) = \'object\'), \n\tCONSTRAINT ck_metric_runs_results_object CHECK (jsonb_typeof(results) = \'object\'), \n\tCONSTRAINT ck_metric_runs_ci_object CHECK (jsonb_typeof(ci) = \'object\'), \n\tCONSTRAINT fk_metric_runs_strategy FOREIGN KEY(strategy_version_id) REFERENCES trading.strategy_versions (id), \n\tCONSTRAINT fk_metric_runs_release FOREIGN KEY(release_manifest_id) REFERENCES trading.release_manifests (id)\n)\n\n',
        index_sql=(
            'CREATE INDEX ix_metric_runs_strategy ON trading.metric_runs (strategy_version_id)',
            'CREATE INDEX ix_metric_runs_release ON trading.metric_runs (release_manifest_id)',
        ),
        append_only=False,
    ),
    _FrozenTableSpec(
        name='resolution_cluster_memberships',
        create_sql='\nCREATE TABLE trading.resolution_cluster_memberships (\n\tresolution_cluster_id BIGINT NOT NULL, \n\tcontract_spec_id BIGINT NOT NULL, \n\ttoken_id BIGINT NOT NULL, \n\tadded_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_resolution_cluster_memberships_pair UNIQUE (resolution_cluster_id, contract_spec_id, token_id), \n\tCONSTRAINT fk_resolution_cluster_memberships_cluster FOREIGN KEY(resolution_cluster_id) REFERENCES trading.resolution_clusters (id), \n\tCONSTRAINT fk_resolution_cluster_memberships_spec FOREIGN KEY(contract_spec_id) REFERENCES trading.contract_specs (id), \n\tCONSTRAINT fk_resolution_cluster_memberships_token FOREIGN KEY(token_id) REFERENCES trading.pm_tokens (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_resolution_cluster_memberships_contract ON trading.resolution_cluster_memberships (contract_spec_id)',),
    ),
    _FrozenTableSpec(
        name='score_target_memberships',
        create_sql='\nCREATE TABLE trading.score_target_memberships (\n\tscore_target_id BIGINT NOT NULL, \n\ttoken_id BIGINT NOT NULL, \n\tmember_weight NUMERIC(38, 12) NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_score_target_memberships_pair UNIQUE (score_target_id, token_id), \n\tCONSTRAINT ck_score_target_memberships_weight_positive CHECK (member_weight > 0), \n\tCONSTRAINT fk_score_target_memberships_target FOREIGN KEY(score_target_id) REFERENCES trading.score_targets (id), \n\tCONSTRAINT fk_score_target_memberships_token FOREIGN KEY(token_id) REFERENCES trading.pm_tokens (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_score_target_memberships_target ON trading.score_target_memberships (score_target_id)',),
    ),
    _FrozenTableSpec(
        name='score_observations',
        create_sql='\nCREATE TABLE trading.score_observations (\n\tobservation_key TEXT COLLATE "C" NOT NULL, \n\tscore_target_id BIGINT NOT NULL, \n\tsubmission_id BIGINT NOT NULL, \n\ttrade_decision_id BIGINT, \n\tlabel_version_id BIGINT NOT NULL, \n\tbaseline_quote NUMERIC(38, 12) NOT NULL, \n\tbaseline_policy_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tsplit VARCHAR(16) NOT NULL, \n\talgorithm_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tmetric_id VARCHAR(64) NOT NULL, \n\tscore_value NUMERIC(38, 12) NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_score_observations_submission_target_label_metric UNIQUE (submission_id, score_target_id, label_version_id, metric_id), \n\tCONSTRAINT ck_score_observations_baseline_positive CHECK (baseline_quote > 0), \n\tCONSTRAINT ck_score_observations_baseline_hash_hex CHECK (baseline_policy_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_score_observations_algorithm_hash_hex CHECK (algorithm_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT fk_score_observations_target FOREIGN KEY(score_target_id) REFERENCES trading.score_targets (id), \n\tCONSTRAINT fk_score_observations_submission FOREIGN KEY(submission_id) REFERENCES trading.forecast_submissions (id), \n\tCONSTRAINT fk_score_observations_decision FOREIGN KEY(trade_decision_id) REFERENCES trading.trade_decisions (id), \n\tCONSTRAINT fk_score_observations_label FOREIGN KEY(label_version_id) REFERENCES trading.resolution_labels (id)\n)\n\n',
        index_sql=(
            'CREATE INDEX ix_score_observations_submission ON trading.score_observations (submission_id)',
            'CREATE INDEX ix_score_observations_target ON trading.score_observations (score_target_id)',
        ),
    ),
    _FrozenTableSpec(
        name='experiment_variants',
        create_sql='\nCREATE TABLE trading.experiment_variants (\n\texperiment_id BIGINT NOT NULL, \n\tvariant_key TEXT COLLATE "C" NOT NULL, \n\tvariant_type VARCHAR(16) NOT NULL, \n\tinput_manifest_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tstrategy_version_id BIGINT NOT NULL, \n\trelease_manifest_id BIGINT NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_experiment_variants_experiment_key UNIQUE (experiment_id, variant_key), \n\tCONSTRAINT ck_experiment_variants_type_known CHECK (variant_type IN (\'champion\',\'challenger\')), \n\tCONSTRAINT ck_experiment_variants_manifest_hex CHECK (input_manifest_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT fk_experiment_variants_experiment FOREIGN KEY(experiment_id) REFERENCES trading.experiments (id), \n\tCONSTRAINT fk_experiment_variants_strategy FOREIGN KEY(strategy_version_id) REFERENCES trading.strategy_versions (id), \n\tCONSTRAINT fk_experiment_variants_release FOREIGN KEY(release_manifest_id) REFERENCES trading.release_manifests (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='challenger_variants',
        create_sql='\nCREATE TABLE trading.challenger_variants (\n\texperiment_id BIGINT NOT NULL, \n\tvariant_key TEXT COLLATE "C" NOT NULL, \n\tchallenger_type VARCHAR(32) NOT NULL, \n\tchanged_fields JSONB NOT NULL, \n\tpolicy_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tstatus VARCHAR(16) DEFAULT \'ACTIVE\' NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_challenger_variants_experiment_key UNIQUE (experiment_id, variant_key), \n\tCONSTRAINT ck_challenger_variants_status_known CHECK (status IN (\'ACTIVE\',\'SUPERSEDED\')), \n\tCONSTRAINT ck_challenger_variants_policy_hex CHECK (policy_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_challenger_variants_changed_object CHECK (jsonb_typeof(changed_fields) = \'object\'), \n\tCONSTRAINT fk_challenger_variants_experiment FOREIGN KEY(experiment_id) REFERENCES trading.experiments (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='error_reviews',
        create_sql='\nCREATE TABLE trading.error_reviews (\n\treview_key TEXT COLLATE "C" NOT NULL, \n\treview_type VARCHAR(32) NOT NULL, \n\tmetric_run_id BIGINT NOT NULL, \n\tobservation_key TEXT COLLATE "C" NOT NULL, \n\troot_cause TEXT NOT NULL, \n\troot_cause_taxonomy VARCHAR(128) NOT NULL, \n\tseed BIGINT NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_error_reviews_key UNIQUE (review_key), \n\tCONSTRAINT ck_error_reviews_type_known CHECK (review_type IN (\'top_loss\',\'top_regret\',\'random_success\')), \n\tCONSTRAINT fk_error_reviews_metric_run FOREIGN KEY(metric_run_id) REFERENCES trading.metric_runs (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_error_reviews_metric_run ON trading.error_reviews (metric_run_id)',),
    ),
    _FrozenTableSpec(
        name='ablation_runs',
        create_sql='\nCREATE TABLE trading.ablation_runs (\n\tablation_key TEXT COLLATE "C" NOT NULL, \n\tmetric_run_id BIGINT NOT NULL, \n\tbundle_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tablation_fields JSONB NOT NULL, \n\tresult_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_ablation_runs_key UNIQUE (ablation_key), \n\tCONSTRAINT ck_ablation_runs_bundle_hash_hex CHECK (bundle_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_ablation_runs_result_hash_hex CHECK (result_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT fk_ablation_runs_metric_run FOREIGN KEY(metric_run_id) REFERENCES trading.metric_runs (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='promotion_decisions',
        create_sql='\nCREATE TABLE trading.promotion_decisions (\n\tpromotion_key TEXT COLLATE "C" NOT NULL, \n\tmetric_run_id BIGINT NOT NULL, \n\tpromotion_type VARCHAR(16) NOT NULL, \n\tfrom_ref VARCHAR(64) COLLATE "C" NOT NULL, \n\tto_ref VARCHAR(64) COLLATE "C" NOT NULL, \n\tevidence_manifest_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tstatus VARCHAR(16) NOT NULL, \n\treason_code VARCHAR(128), \n\tfuture_effective_at TIMESTAMP WITH TIME ZONE, \n\tcapital_amount NUMERIC(38, 0) DEFAULT \'0\' NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_promotion_decisions_key UNIQUE (promotion_key), \n\tCONSTRAINT ck_promotion_decisions_type_known CHECK (promotion_type IN (\'capital\',\'strategy\')), \n\tCONSTRAINT ck_promotion_decisions_status_known CHECK (status IN (\'APPROVED\',\'REJECTED\',\'DEFERRED\')), \n\tCONSTRAINT ck_promotion_decisions_capital_never_approved CHECK (NOT (promotion_type = \'capital\' AND status = \'APPROVED\')), \n\tCONSTRAINT ck_promotion_decisions_from_hex CHECK (from_ref ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_promotion_decisions_to_hex CHECK (to_ref ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_promotion_decisions_evidence_hex CHECK (evidence_manifest_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT fk_promotion_decisions_metric_run FOREIGN KEY(metric_run_id) REFERENCES trading.metric_runs (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_promotion_decisions_metric_run ON trading.promotion_decisions (metric_run_id)',),
    ),
    _FrozenTableSpec(
        name='replay_runs',
        create_sql='\nCREATE TABLE trading.replay_runs (\n\trun_key TEXT COLLATE "C" NOT NULL, \n\treplay_kind VARCHAR(16) NOT NULL, \n\tmanifest_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tcode_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tseed BIGINT NOT NULL, \n\tinput_artifact_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\toutput_artifact_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tresult JSONB, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_replay_runs_key UNIQUE (run_key), \n\tCONSTRAINT ck_replay_runs_kind_known CHECK (replay_kind IN (\'original\',\'new_code\',\'variant\')), \n\tCONSTRAINT ck_replay_runs_manifest_hash_hex CHECK (manifest_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_replay_runs_code_hash_hex CHECK (code_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_replay_runs_input_hash_hex CHECK (input_artifact_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_replay_runs_output_hash_hex CHECK (output_artifact_hash ~ \'^[0-9a-f]{64}$\')\n)\n\n',
    ),
)

# b1000031 已存在的 trading 关系（downgrade preflight allowlist）
_PRE_0040_RELATIONS = (
    "artifact_objects", "artifact_lineage_edges", "archive_manifests",
    "retention_manifests", "runtime_config_versions", "strategy_objective_contracts",
    "strategy_versions", "execution_spec_versions", "capital_permission_manifests",
    "model_role_bindings", "release_manifests", "policy_type_scopes", "policy_freezes",
    "secret_vault_entries", "secret_vault_versions", "secret_access_events",
    "idempotency_claims", "transactional_outbox", "outbox_delivery_history",
    "job_completions", "pm_universe_frames", "pm_universe_frame_pages", "pm_events",
    "pm_markets", "pm_market_versions", "pm_tokens", "pm_token_versions",
    "pm_market_lifecycle_events", "pm_market_current", "pm_connection_epochs",
    "pm_source_event_batches", "pm_source_event_index", "pm_book_checkpoints",
    "pm_book_levels", "pm_book_current", "pm_quote_bindings", "contract_snapshots",
    "contract_specs", "payout_functions", "forecast_components", "world_schema_versions",
    "forecast_component_versions", "forecast_component_contract_specs",
    "portfolio_dependency_edges", "evaluation_cohorts", "universe_memberships",
    "screening_episodes", "audit_samples", "decision_opportunities",
    "decision_opportunity_markets", "episode_memberships", "forecast_episodes",
    "episode_contract_specs", "information_snapshots", "information_snapshot_items",
    "gate_decisions", "priors", "evidence_coverage_policies", "evidence_revisions",
    "evidence_bundles", "evidence_bundle_items", "forecast_input_manifests",
    "forecast_submissions", "payout_projections", "coherence_checks",
    "forecast_challenges", "forecast_leases", "ai_invocations", "ai_tool_calls",
    "ai_validation_results", "market_relative_decisions", "discrepancy_reviews",
    "trade_decisions", "action_candidates", "resolution_cashflows", "action_sets",
    "action_set_legs", "underwriting_plans", "economic_action_intents",
    "executions", "positions", "position_lots", "ledger_transactions",
    "ledger_postings", "operating_cost_entries",
)


def _assert_downgrade_safe() -> None:
    allowed = ", ".join(
        f"'{name}'" for name in (*_PRE_0040_RELATIONS, *(t.name for t in _LEARNING_TABLES))
    )
    op.execute(
        f"""
DO $v2_wp04_learning_preflight$
DECLARE unknown_objects text;
BEGIN
    SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
      INTO unknown_objects
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'trading'
       AND c.relkind IN ('r','p','v','m','f')
       AND c.relname NOT IN ({allowed})
       AND NOT EXISTS (
           SELECT 1 FROM pg_inherits i
           JOIN pg_class p ON p.oid = i.inhparent
           JOIN pg_namespace pn ON pn.oid = p.relnamespace
           WHERE i.inhrelid = c.oid AND pn.nspname = 'trading'
             AND ((p.relname = 'outbox_delivery_history'
                   AND c.relname ~ '^outbox_delivery_history_[0-9]{{6}}$')
               OR (p.relname IN ('pm_source_event_batches','pm_source_event_index',
                                  'pm_book_checkpoints','pm_book_levels')
                   AND c.relname ~ ('^' || p.relname || '_[0-9]{{8}}$'))
               OR (p.relname IN ('ai_invocations','ai_tool_calls','ai_validation_results')
                   AND c.relname ~ ('^' || p.relname || '_[0-9]{{6}}$')))
       );
    IF unknown_objects IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp04_learning_unknown_object:%', unknown_objects USING ERRCODE='55000';
    END IF;
END $v2_wp04_learning_preflight$
"""
    )


def _reinforce_gate_g8() -> None:
    gate_values = ", ".join(f"'{g}'" for g in _GATES_0040)
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "DROP CONSTRAINT IF EXISTS ck_gate_decisions_gate_known"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        f"ADD CONSTRAINT ck_gate_decisions_gate_known CHECK (gate IN ({gate_values}))"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "DROP CONSTRAINT IF EXISTS ck_gate_decisions_target_kind_known"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "ADD CONSTRAINT ck_gate_decisions_target_kind_known CHECK ("
        "target_kind IN ('screening','opportunity','episode','trade_decision','metric_run'))"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "DROP CONSTRAINT IF EXISTS ck_gate_decisions_gate_target_pair"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "ADD CONSTRAINT ck_gate_decisions_gate_target_pair CHECK ("
        "(gate IN ('G0','R0') AND target_kind = 'screening') OR "
        "(gate IN ('G1','G2') AND target_kind = 'opportunity') OR "
        "(gate IN ('R1','G4','G5A','G5B','G6') AND target_kind = 'episode') OR "
        "(gate IN ('G7A','G7B') AND target_kind = 'trade_decision') OR "
        "(gate IN ('G8') AND target_kind = 'metric_run'))"
    )


def _unreinforce_gate_g8() -> None:
    gate_values = ", ".join(f"'{g}'" for g in _GATES_0031)
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "DROP CONSTRAINT IF EXISTS ck_gate_decisions_gate_known"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        f"ADD CONSTRAINT ck_gate_decisions_gate_known CHECK (gate IN ({gate_values}))"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "DROP CONSTRAINT IF EXISTS ck_gate_decisions_target_kind_known"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "ADD CONSTRAINT ck_gate_decisions_target_kind_known CHECK ("
        "target_kind IN ('screening','opportunity','episode','trade_decision'))"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "DROP CONSTRAINT IF EXISTS ck_gate_decisions_gate_target_pair"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "ADD CONSTRAINT ck_gate_decisions_gate_target_pair CHECK ("
        "(gate IN ('G0','R0') AND target_kind = 'screening') OR "
        "(gate IN ('G1','G2') AND target_kind = 'opportunity') OR "
        "(gate IN ('R1','G4','G5A','G5B','G6') AND target_kind = 'episode') OR "
        "(gate IN ('G7A','G7B') AND target_kind = 'trade_decision'))"
    )


def _gate_guard_0031_fn() -> str:
    return r"""
CREATE FUNCTION trading.v2_guard_gate_decision() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    root_id bigint;
    screening_id bigint;
    opportunity_id bigint;
BEGIN
    IF NEW.gate IN ('G0','R0') THEN
        IF NOT EXISTS (SELECT 1 FROM trading.screening_episodes WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NEW.gate IN ('G1','G2') THEN
        IF NOT EXISTS (SELECT 1 FROM trading.decision_opportunities WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NEW.gate IN ('G7A','G7B') THEN
        IF NOT EXISTS (SELECT 1 FROM trading.trade_decisions WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NOT EXISTS (SELECT 1 FROM trading.forecast_episodes WHERE id = NEW.target_id) THEN
        RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
    END IF;

    IF (NEW.gate = 'G0' AND NEW.result NOT IN ('PASS','PREDICTION_RESEARCH_ONLY'))
       OR (NEW.gate = 'R0' AND NEW.result NOT IN ('SELECT','DEFER','REJECT'))
       OR (NEW.gate IN ('G1','G2') AND NEW.result NOT IN ('PASS','FAIL'))
       OR (NEW.gate = 'R1' AND NEW.result NOT IN ('reject','shallow','standard','deep'))
       OR (NEW.gate = 'G4' AND NEW.result NOT IN ('PASS','FAIL'))
       OR (NEW.gate = 'G5A' AND NEW.result NOT IN ('PASS','ABSTAIN_EVIDENCE_INTEGRITY'))
       OR (NEW.gate = 'G5B' AND NEW.result NOT IN ('PASS','WIDEN_REQUIRED','ABSTAIN_EVIDENCE_INSUFFICIENT'))
       OR (NEW.gate IN ('G6','G7A','G7B') AND NEW.result NOT IN ('PASS','FAIL')) THEN
        RAISE EXCEPTION 'v2_gate_result_invalid' USING ERRCODE='23514';
    END IF;
    IF NEW.result IN ('PREDICTION_RESEARCH_ONLY','DEFER','REJECT','FAIL',
                      'ABSTAIN_EVIDENCE_INTEGRITY','WIDEN_REQUIRED','ABSTAIN_EVIDENCE_INSUFFICIENT','reject')
       AND NEW.reason_code IS NULL THEN
        RAISE EXCEPTION 'v2_gate_failure_reason_required' USING ERRCODE='23514';
    END IF;

    IF NEW.gate = 'R0' AND NOT EXISTS (
        SELECT 1 FROM trading.gate_decisions gd
         WHERE gd.gate = 'G0' AND gd.target_kind = 'screening'
           AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
    ) THEN
        RAISE EXCEPTION 'v2_gate_order_g0_r0' USING ERRCODE='23514';
    ELSIF NEW.gate = 'G1' THEN
        SELECT COALESCE(o.parent_id, o.id) INTO STRICT root_id
          FROM trading.decision_opportunities o WHERE o.id = NEW.target_id;
        SELECT source_screening_episode_id INTO screening_id
          FROM trading.decision_opportunities WHERE id = root_id;
        IF screening_id IS NULL OR NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'R0' AND gd.target_kind = 'screening'
               AND gd.target_id = screening_id
               AND (gd.result = 'SELECT' OR EXISTS (
                    SELECT 1 FROM trading.screening_episodes se
                     WHERE se.id = screening_id AND se.audit_assigned))
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_r0_g1' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G2' THEN
        SELECT COALESCE(o.parent_id, o.id) INTO STRICT root_id
          FROM trading.decision_opportunities o WHERE o.id = NEW.target_id;
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
            JOIN trading.decision_opportunities prior ON prior.id = gd.target_id
             WHERE gd.gate = 'G1' AND gd.target_kind = 'opportunity' AND gd.result = 'PASS'
               AND COALESCE(prior.parent_id, prior.id) = root_id
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g1_g2' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'R1' THEN
        SELECT decision_opportunity_id INTO STRICT opportunity_id
          FROM trading.forecast_episodes WHERE id = NEW.target_id;
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G2' AND gd.target_kind = 'opportunity'
               AND gd.target_id = opportunity_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g2_r1' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G4' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'R1' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id
               AND gd.result IN ('shallow','standard','deep')
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_r1_g4' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G5A' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G4' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g4_g5a' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G5B' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G5A' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g5a_g5b' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G6' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G5B' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g5b_g6' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G7B' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G7A' AND gd.target_kind = 'trade_decision'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g7a_g7b' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $v2_guard$
"""


def _gate_guard_g8_fn() -> str:
    return r"""
CREATE FUNCTION trading.v2_guard_gate_decision() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    root_id bigint;
    screening_id bigint;
    opportunity_id bigint;
BEGIN
    IF NEW.gate IN ('G0','R0') THEN
        IF NOT EXISTS (SELECT 1 FROM trading.screening_episodes WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NEW.gate IN ('G1','G2') THEN
        IF NOT EXISTS (SELECT 1 FROM trading.decision_opportunities WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NEW.gate IN ('G7A','G7B') THEN
        IF NOT EXISTS (SELECT 1 FROM trading.trade_decisions WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NEW.gate = 'G8' THEN
        IF NOT EXISTS (SELECT 1 FROM trading.metric_runs WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NOT EXISTS (SELECT 1 FROM trading.forecast_episodes WHERE id = NEW.target_id) THEN
        RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
    END IF;

    IF (NEW.gate = 'G0' AND NEW.result NOT IN ('PASS','PREDICTION_RESEARCH_ONLY'))
       OR (NEW.gate = 'R0' AND NEW.result NOT IN ('SELECT','DEFER','REJECT'))
       OR (NEW.gate IN ('G1','G2') AND NEW.result NOT IN ('PASS','FAIL'))
       OR (NEW.gate = 'R1' AND NEW.result NOT IN ('reject','shallow','standard','deep'))
       OR (NEW.gate = 'G4' AND NEW.result NOT IN ('PASS','FAIL'))
       OR (NEW.gate = 'G5A' AND NEW.result NOT IN ('PASS','ABSTAIN_EVIDENCE_INTEGRITY'))
       OR (NEW.gate = 'G5B' AND NEW.result NOT IN ('PASS','WIDEN_REQUIRED','ABSTAIN_EVIDENCE_INSUFFICIENT'))
       OR (NEW.gate IN ('G6','G7A','G7B','G8') AND NEW.result NOT IN ('PASS','FAIL')) THEN
        RAISE EXCEPTION 'v2_gate_result_invalid' USING ERRCODE='23514';
    END IF;
    IF NEW.result IN ('PREDICTION_RESEARCH_ONLY','DEFER','REJECT','FAIL',
                      'ABSTAIN_EVIDENCE_INTEGRITY','WIDEN_REQUIRED','ABSTAIN_EVIDENCE_INSUFFICIENT','reject')
       AND NEW.reason_code IS NULL THEN
        RAISE EXCEPTION 'v2_gate_failure_reason_required' USING ERRCODE='23514';
    END IF;

    IF NEW.gate = 'R0' AND NOT EXISTS (
        SELECT 1 FROM trading.gate_decisions gd
         WHERE gd.gate = 'G0' AND gd.target_kind = 'screening'
           AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
    ) THEN
        RAISE EXCEPTION 'v2_gate_order_g0_r0' USING ERRCODE='23514';
    ELSIF NEW.gate = 'G1' THEN
        SELECT COALESCE(o.parent_id, o.id) INTO STRICT root_id
          FROM trading.decision_opportunities o WHERE o.id = NEW.target_id;
        SELECT source_screening_episode_id INTO screening_id
          FROM trading.decision_opportunities WHERE id = root_id;
        IF screening_id IS NULL OR NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'R0' AND gd.target_kind = 'screening'
               AND gd.target_id = screening_id
               AND (gd.result = 'SELECT' OR EXISTS (
                    SELECT 1 FROM trading.screening_episodes se
                     WHERE se.id = screening_id AND se.audit_assigned))
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_r0_g1' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G2' THEN
        SELECT COALESCE(o.parent_id, o.id) INTO STRICT root_id
          FROM trading.decision_opportunities o WHERE o.id = NEW.target_id;
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
            JOIN trading.decision_opportunities prior ON prior.id = gd.target_id
             WHERE gd.gate = 'G1' AND gd.target_kind = 'opportunity' AND gd.result = 'PASS'
               AND COALESCE(prior.parent_id, prior.id) = root_id
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g1_g2' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'R1' THEN
        SELECT decision_opportunity_id INTO STRICT opportunity_id
          FROM trading.forecast_episodes WHERE id = NEW.target_id;
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G2' AND gd.target_kind = 'opportunity'
               AND gd.target_id = opportunity_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g2_r1' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G4' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'R1' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id
               AND gd.result IN ('shallow','standard','deep')
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_r1_g4' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G5A' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G4' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g4_g5a' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G5B' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G5A' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g5a_g5b' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G6' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G5B' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g5b_g6' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G7B' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G7A' AND gd.target_kind = 'trade_decision'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g7a_g7b' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $v2_guard$
"""


def _create_guards() -> None:
    # append-only 事实表（14 张全部不可变）。
    for table in _LEARNING_TABLES:
        if table.append_only:
            op.execute(
                f"CREATE TRIGGER trg_{table.name}_immutable "
                f"BEFORE UPDATE OR DELETE ON {TRADING_SCHEMA}.{table.name} "
                "FOR EACH ROW EXECUTE FUNCTION trading.v2_reject_immutable_row()"
            )
    # resolution_labels 状态机 + supersede 连续性 + 单 current（deferred）。
    op.execute(
        r"""
CREATE FUNCTION trading.v2_check_label_revision() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    prev_version integer;
    prev_state text;
    current_count integer;
BEGIN
    IF NEW.supersedes_id IS NOT NULL THEN
        IF NOT EXISTS (SELECT 1 FROM trading.resolution_labels WHERE id = NEW.supersedes_id) THEN
            RAISE EXCEPTION 'v2_label_supersedes_missing' USING ERRCODE='23503';
        END IF;
        SELECT version_no, state INTO STRICT prev_version, prev_state
          FROM trading.resolution_labels WHERE id = NEW.supersedes_id;
        IF NOT EXISTS (
            SELECT 1 FROM trading.resolution_labels p
             WHERE p.id = NEW.supersedes_id
               AND p.contract_spec_id = NEW.contract_spec_id
               AND p.label_key = NEW.label_key
        ) THEN
            RAISE EXCEPTION 'v2_label_supersedes_cross_contract' USING ERRCODE='23514';
        END IF;
        IF prev_version + 1 <> NEW.version_no THEN
            RAISE EXCEPTION 'v2_label_supersedes_version_gap' USING ERRCODE='23514';
        END IF;
        IF prev_state NOT IN ('pending','provisional') THEN
            RAISE EXCEPTION 'v2_label_supersedes_terminal_state' USING ERRCODE='23514';
        END IF;
        IF (prev_state = 'pending' AND NEW.state <> 'provisional')
           OR (prev_state = 'provisional' AND NEW.state NOT IN ('disputed','final_admissible','final_excluded')) THEN
            RAISE EXCEPTION 'v2_label_transition_invalid' USING ERRCODE='23514';
        END IF;
    ELSE
        IF NEW.version_no <> 1 THEN
            RAISE EXCEPTION 'v2_label_first_version_requires_no_supersede' USING ERRCODE='23514';
        END IF;
        IF NEW.state <> 'pending' THEN
            RAISE EXCEPTION 'v2_label_initial_state_must_be_pending' USING ERRCODE='23514';
        END IF;
    END IF;

    SELECT count(*) INTO current_count
      FROM trading.resolution_labels r
     WHERE r.contract_spec_id = NEW.contract_spec_id
       AND r.label_key = NEW.label_key
       AND NOT EXISTS (
           SELECT 1 FROM trading.resolution_labels s
            WHERE s.contract_spec_id = r.contract_spec_id
              AND s.label_key = r.label_key
              AND s.supersedes_id = r.id
       );
    IF current_count > 1 THEN
        RAISE EXCEPTION 'v2_label_multiple_current' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER trg_resolution_labels_current "
        "AFTER INSERT ON trading.resolution_labels "
        "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
        "EXECUTE FUNCTION trading.v2_check_label_revision()"
    )
    # resolution_clusters：OPEN cluster 不得引用 final_admissible label；同 contract_spec
    # 不得属于两个 active cluster version（deferred，双向）。
    op.execute(
        r"""
CREATE FUNCTION trading.v2_check_cluster_outcome_unknown() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    cluster_status text;
BEGIN
    IF TG_TABLE_NAME = 'resolution_labels' THEN
        IF NEW.state = 'final_admissible' AND EXISTS (
            SELECT 1 FROM trading.resolution_cluster_memberships m
            JOIN trading.resolution_clusters c ON c.id = m.resolution_cluster_id
            WHERE m.contract_spec_id = NEW.contract_spec_id
              AND c.status = 'OPEN'
        ) THEN
            RAISE EXCEPTION 'v2_cluster_open_references_final_label' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    SELECT status INTO STRICT cluster_status
      FROM trading.resolution_clusters WHERE id = NEW.resolution_cluster_id;
    IF cluster_status = 'OPEN' AND EXISTS (
        SELECT 1 FROM trading.resolution_labels rl
         WHERE rl.contract_spec_id = NEW.contract_spec_id
           AND rl.state = 'final_admissible'
    ) THEN
        RAISE EXCEPTION 'v2_cluster_open_references_final_label' USING ERRCODE='23514';
    END IF;
    IF EXISTS (
        SELECT 1 FROM trading.resolution_cluster_memberships m
        JOIN trading.resolution_clusters c ON c.id = m.resolution_cluster_id
        WHERE m.contract_spec_id = NEW.contract_spec_id
          AND m.resolution_cluster_id <> NEW.resolution_cluster_id
          AND c.status IN ('OPEN','FROZEN')
    ) THEN
        RAISE EXCEPTION 'v2_cluster_membership_contract_already_active' USING ERRCODE='23505';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER trg_resolution_labels_cluster_outcome "
        "AFTER INSERT OR UPDATE ON trading.resolution_labels "
        "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
        "EXECUTE FUNCTION trading.v2_check_cluster_outcome_unknown()"
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER trg_resolution_cluster_memberships_outcome "
        "AFTER INSERT ON trading.resolution_cluster_memberships "
        "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
        "EXECUTE FUNCTION trading.v2_check_cluster_outcome_unknown()"
    )
    # score_target_memberships：权重归一（总和=1）+ token 双计禁止（deferred）。
    op.execute(
        r"""
CREATE FUNCTION trading.v2_check_target_membership() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    total numeric;
    target_contract bigint;
BEGIN
    SELECT contract_spec_id INTO STRICT target_contract
      FROM trading.score_targets WHERE id = NEW.score_target_id;
    IF EXISTS (
        SELECT 1 FROM trading.score_target_memberships tm
        JOIN trading.score_targets t ON t.id = tm.score_target_id
        WHERE tm.token_id = NEW.token_id
          AND t.contract_spec_id = target_contract
          AND tm.score_target_id <> NEW.score_target_id
    ) THEN
        RAISE EXCEPTION 'v2_target_membership_token_double_counted' USING ERRCODE='23505';
    END IF;
    SELECT COALESCE(sum(member_weight), 0) INTO total
      FROM trading.score_target_memberships
     WHERE score_target_id = NEW.score_target_id;
    IF total <> 1 THEN
        RAISE EXCEPTION 'v2_target_membership_weight_not_one' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER trg_score_target_memberships_weight "
        "AFTER INSERT OR UPDATE ON trading.score_target_memberships "
        "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
        "EXECUTE FUNCTION trading.v2_check_target_membership()"
    )
    # score_observations：label_version 必须 final_admissible（§5.3）。
    op.execute(
        r"""
CREATE FUNCTION trading.v2_check_score_observation_label() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM trading.resolution_labels rl
         WHERE rl.id = NEW.label_version_id
           AND rl.state = 'final_admissible'
    ) THEN
        RAISE EXCEPTION 'v2_score_observation_label_not_admissible' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_score_observations_label "
        "BEFORE INSERT ON trading.score_observations "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_check_score_observation_label()"
    )
    # metric_runs lifecycle guard：RUNNING→COMPLETED|FAILED|INVALIDATED；terminal 禁改。
    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_metric_run() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE terminal text[] := ARRAY['COMPLETED','FAILED','INVALIDATED'];
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_metric_run_immutable' USING ERRCODE='55000';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'RUNNING' OR NEW.completed_at IS NOT NULL THEN
            RAISE EXCEPTION 'v2_metric_run_initial_state_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF OLD.run_key IS DISTINCT FROM NEW.run_key
       OR OLD.cohort_query_hash IS DISTINCT FROM NEW.cohort_query_hash
       OR OLD.strategy_version_id IS DISTINCT FROM NEW.strategy_version_id
       OR OLD.release_manifest_id IS DISTINCT FROM NEW.release_manifest_id
       OR OLD.label_versions IS DISTINCT FROM NEW.label_versions
       OR OLD.split IS DISTINCT FROM NEW.split
       OR OLD.time_blocks IS DISTINCT FROM NEW.time_blocks
       OR OLD.code_hash IS DISTINCT FROM NEW.code_hash
       OR OLD.config_hash IS DISTINCT FROM NEW.config_hash
       OR OLD.seed IS DISTINCT FROM NEW.seed
       OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
        RAISE EXCEPTION 'v2_metric_run_identity_immutable' USING ERRCODE='55000';
    END IF;
    IF OLD.status = ANY(terminal) AND NEW.status IS DISTINCT FROM OLD.status THEN
        RAISE EXCEPTION 'v2_metric_run_terminal_immutable' USING ERRCODE='55000';
    END IF;
    IF OLD.status = 'RUNNING' AND NEW.status IN ('COMPLETED','FAILED','INVALIDATED') THEN
        IF NEW.status = 'COMPLETED' AND NEW.completed_at IS NULL THEN
            RAISE EXCEPTION 'v2_metric_run_completed_requires_timestamp' USING ERRCODE='23514';
        END IF;
        IF NEW.status <> 'COMPLETED' AND NEW.completed_at IS NOT NULL THEN
            RAISE EXCEPTION 'v2_metric_run_noncompleted_no_timestamp' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'v2_metric_run_immutable' USING ERRCODE='55000';
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_metric_runs_lifecycle "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.metric_runs "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_metric_run()"
    )
    # gate_decisions：升级 guard（G8 target），并加 G8 deferred 校验。
    op.execute("DROP TRIGGER IF EXISTS trg_gate_decisions_semantics ON trading.gate_decisions")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_gate_decision()")
    op.execute(_gate_guard_g8_fn())
    op.execute(
        "CREATE TRIGGER trg_gate_decisions_semantics BEFORE INSERT ON trading.gate_decisions "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_gate_decision()"
    )
    op.execute(
        r"""
CREATE FUNCTION trading.v2_validate_gate_g8() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    IF NEW.gate = 'G8' AND NEW.target_kind = 'metric_run' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.metric_runs mr
             WHERE mr.id = NEW.target_id
               AND mr.status = 'COMPLETED'
               AND mr.release_manifest_id = NEW.version_manifest_id
        ) THEN
            RAISE EXCEPTION 'v2_gate_g8_target_invalid' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER trg_gate_decisions_g8 "
        "AFTER INSERT OR UPDATE ON trading.gate_decisions "
        "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
        "EXECUTE FUNCTION trading.v2_validate_gate_g8()"
    )


def _drop_guards() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_gate_decisions_g8 ON trading.gate_decisions")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_validate_gate_g8()")
    op.execute("DROP TRIGGER IF EXISTS trg_gate_decisions_semantics ON trading.gate_decisions")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_gate_decision()")
    op.execute(_gate_guard_0031_fn())
    op.execute(
        "CREATE TRIGGER trg_gate_decisions_semantics BEFORE INSERT ON trading.gate_decisions "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_gate_decision()"
    )
    op.execute("DROP TRIGGER IF EXISTS trg_metric_runs_lifecycle ON trading.metric_runs")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_metric_run()")
    op.execute("DROP TRIGGER IF EXISTS trg_score_observations_label ON trading.score_observations")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_check_score_observation_label()")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_score_target_memberships_weight "
        "ON trading.score_target_memberships"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_check_target_membership()")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_resolution_cluster_memberships_outcome "
        "ON trading.resolution_cluster_memberships"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS trg_resolution_labels_cluster_outcome "
        "ON trading.resolution_labels"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_check_cluster_outcome_unknown()")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_resolution_labels_current ON trading.resolution_labels"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_check_label_revision()")
    for table in reversed(_LEARNING_TABLES):
        if table.append_only:
            op.execute(
                f"DROP TRIGGER IF EXISTS trg_{table.name}_immutable "
                f"ON {TRADING_SCHEMA}.{table.name}"
            )


def upgrade() -> None:
    for table in _LEARNING_TABLES:
        op.execute(table.create_sql)
        for statement in table.index_sql:
            op.execute(statement)
    _reinforce_gate_g8()
    _create_guards()


def downgrade() -> None:
    _assert_downgrade_safe()
    _drop_guards()
    _unreinforce_gate_g8()
    for table in reversed(_LEARNING_TABLES):
        op.execute(f"DROP TABLE {TRADING_SCHEMA}.{table.name}")
