"""create p1b ai observability

Revision ID: b1000021
Revises: b1000020
Create Date: 2026-08-11 13:00:00

v2_0021 —— AI invocation 事实与 provider-neutral Gateway（WP-02 Checkpoint B）。

- ``upgrade``：
  - 3 张 UTC 月 RANGE 分区事实表（ai_invocations / ai_tool_calls / ai_validation_results），
    无 default partition，预建测试覆盖月份（当前月 + 未来 1 月，避免插入落空）。
  - ``model_role_bindings`` 可逆强化为 typed、版本化 capability binding：新增
    provider/route/network_policy/allowed_tools/allowed_domains/capability/binding_version；
    旧行按 provider=model_ref 拆分的 legacy 反填；唯一键改为 (strategy_version_id, role,
    binding_version)。
  - ``artifact_lineage_edges.relation`` allowlist 扩展为
    ``READS|PRODUCES|VALIDATES|SUPERSEDES|PROJECTS_TO|USED_BY``，保留旧值（可逆）。
- ``downgrade``：逆序删 3 表 + 分区；撤销 model_role_bindings/lineage 强化并恢复原约束。
  未知对象 fail-closed。
"""
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op

TRADING_SCHEMA = "trading"

# revision identifiers, used by Alembic.
revision: str = "b1000021"
down_revision: Union[str, Sequence[str], None] = "b1000020"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


@dataclass(frozen=True)
class _FrozenTableSpec:
    name: str
    create_sql: str
    index_sql: tuple[str, ...] = ()
    append_only: bool = True
    partitioned: bool = True


_AI_TABLES = (
    _FrozenTableSpec(
        name='ai_invocations',
        create_sql='\nCREATE TABLE trading.ai_invocations (\n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\toccurred_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tinvocation_key TEXT COLLATE "C" NOT NULL, \n\tepisode_id BIGINT NOT NULL, \n\tstage VARCHAR(32) NOT NULL, \n\trole VARCHAR(64) NOT NULL, \n\tattempt_no INTEGER NOT NULL, \n\texperiment_variant VARCHAR(64) DEFAULT \'champion\' NOT NULL, \n\tparent_invocation_id BIGINT, \n\tretry_of_invocation_id BIGINT, \n\tfallback_of_invocation_id BIGINT, \n\tcausation_event_id TEXT COLLATE "C", \n\trelease_manifest_id BIGINT, \n\tstrategy_version_id BIGINT, \n\tconfig_version_id BIGINT, \n\tgit_sha VARCHAR(64) COLLATE "C", \n\tdb_revision VARCHAR(64), \n\tmodel_role_binding_id BIGINT, \n\trequested_provider VARCHAR(32) NOT NULL, \n\trequested_route VARCHAR(64) NOT NULL, \n\trequested_model TEXT COLLATE "C" NOT NULL, \n\treturned_provider VARCHAR(32), \n\treturned_route VARCHAR(64), \n\treturned_model TEXT COLLATE "C", \n\teffort VARCHAR(32), \n\tsampling JSONB, \n\tseed BIGINT, \n\tnetwork_policy VARCHAR(32) NOT NULL, \n\tallowed_tools JSONB, \n\tallowed_domains JSONB, \n\tcontext_class VARCHAR(32) NOT NULL, \n\ttaint_report JSONB NOT NULL, \n\tprompt_version VARCHAR(64), \n\tprompt_artifact_ref VARCHAR(64) COLLATE "C", \n\tschema_version VARCHAR(64), \n\tschema_artifact_ref VARCHAR(64) COLLATE "C", \n\tinput_manifest JSONB NOT NULL, \n\tinput_manifest_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\traw_response_artifact_ref VARCHAR(64) COLLATE "C", \n\tparsed_output_artifact_ref VARCHAR(64) COLLATE "C", \n\tnormalized_output_artifact_ref VARCHAR(64) COLLATE "C", \n\tlifecycle_state VARCHAR(32) DEFAULT \'PLANNED\' NOT NULL, \n\tresult VARCHAR(32), \n\tterminal_reason VARCHAR(128), \n\tretriable BOOLEAN, \n\taccepted_at TIMESTAMP WITH TIME ZONE, \n\tqueued_at TIMESTAMP WITH TIME ZONE, \n\tstarted_at TIMESTAMP WITH TIME ZONE, \n\tfirst_token_at TIMESTAMP WITH TIME ZONE, \n\tresponse_at TIMESTAMP WITH TIME ZONE, \n\tparsed_at TIMESTAMP WITH TIME ZONE, \n\tvalidated_at TIMESTAMP WITH TIME ZONE, \n\tcompleted_at TIMESTAMP WITH TIME ZONE, \n\tinput_tokens BIGINT, \n\tcache_tokens BIGINT, \n\toutput_tokens BIGINT, \n\treasoning_tokens BIGINT, \n\ttool_count INTEGER DEFAULT \'0\' NOT NULL, \n\tsearch_count INTEGER DEFAULT \'0\' NOT NULL, \n\tprovider_request_id TEXT COLLATE "C", \n\tcost_estimated NUMERIC(38, 0) DEFAULT \'0\' NOT NULL, \n\tcost_currency VARCHAR(16), \n\tpricing_snapshot JSONB NOT NULL, \n\tcost_reconciliation VARCHAR(32), \n\taccepted_output_binding TEXT COLLATE "C", \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id, occurred_at), \n\tCONSTRAINT uq_ai_invocations_attempt_identity UNIQUE (episode_id, stage, role, experiment_variant, attempt_no, occurred_at), \n\tCONSTRAINT ck_ai_invocations_lifecycle_known CHECK (lifecycle_state IN (\'PLANNED\',\'STARTED\',\'TOOL_RUNNING\',\'RESPONSE_RECEIVED\',\'PARSED\',\'VALIDATED\',\'ACCEPTED\',\'REJECTED\',\'FAILED\',\'TIMEOUT\',\'CANCELLED\',\'UNKNOWN\')), \n\tCONSTRAINT ck_ai_invocations_network_policy_known CHECK (network_policy IN (\'NONE\',\'WEB_X\',\'SEARCH_URL\')), \n\tCONSTRAINT ck_ai_invocations_context_class_known CHECK (context_class IN (\'CONTRACT\',\'PRIOR\',\'EVIDENCE\',\'QUOTE\',\'ODDS\',\'CROWD\',\'LABEL\',\'FUTURE_FACT\')), \n\tCONSTRAINT ck_ai_invocations_requested_provider_known CHECK (requested_provider IN (\'deepseek\',\'xai\',\'gemini\',\'kimi\',\'packy\')), \n\tCONSTRAINT ck_ai_invocations_returned_provider_known CHECK (returned_provider IS NULL OR returned_provider IN (\'deepseek\',\'xai\',\'gemini\',\'kimi\',\'packy\')), \n\tCONSTRAINT ck_ai_invocations_accepted_pair CHECK (accepted_at IS NOT NULL = (lifecycle_state = \'ACCEPTED\')), \n\tCONSTRAINT ck_ai_invocations_terminal_pair CHECK ((lifecycle_state IN (\'REJECTED\',\'FAILED\',\'TIMEOUT\',\'CANCELLED\',\'UNKNOWN\')) = (terminal_reason IS NOT NULL)), \n\tCONSTRAINT ck_ai_invocations_attempt_no_positive CHECK (attempt_no > 0), \n\tCONSTRAINT ck_ai_invocations_cost_estimated_nonneg CHECK (cost_estimated >= 0), \n\tCONSTRAINT ck_ai_invocations_tool_requires_network CHECK (tool_count = 0 OR network_policy <> \'NONE\'), \n\tCONSTRAINT ck_ai_invocations_revealed_requires_network CHECK (context_class IN (\'CONTRACT\',\'PRIOR\',\'EVIDENCE\') OR network_policy <> \'NONE\'), \n\tCONSTRAINT ck_ai_invocations_input_manifest_object CHECK (jsonb_typeof(input_manifest) = \'object\'), \n\tCONSTRAINT ck_ai_invocations_pricing_snapshot_object CHECK (jsonb_typeof(pricing_snapshot) = \'object\'), \n\tCONSTRAINT ck_ai_invocations_taint_report_object CHECK (jsonb_typeof(taint_report) = \'object\')\n)\n PARTITION BY RANGE (occurred_at)\n\n',
        index_sql=(
            'CREATE INDEX ix_ai_invocations_episode ON trading.ai_invocations (episode_id, occurred_at)',
            'CREATE INDEX ix_ai_invocations_role ON trading.ai_invocations (role, occurred_at)',
        ),
    ),
    _FrozenTableSpec(
        name='ai_tool_calls',
        create_sql='\nCREATE TABLE trading.ai_tool_calls (\n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\toccurred_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tinvocation_id BIGINT NOT NULL, \n\tordinal INTEGER NOT NULL, \n\ttool_type VARCHAR(64) NOT NULL, \n\ttool_version VARCHAR(64), \n\targuments JSONB NOT NULL, \n\targuments_artifact_ref VARCHAR(64) COLLATE "C", \n\tstarted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcompleted_at TIMESTAMP WITH TIME ZONE, \n\tstatus VARCHAR(32) NOT NULL, \n\terror_code VARCHAR(128), \n\tresult_artifact_ref VARCHAR(64) COLLATE "C", \n\tsource_urls JSONB, \n\tpublished_at TIMESTAMP WITH TIME ZONE, \n\tobserved_at TIMESTAMP WITH TIME ZONE, \n\tusage JSONB, \n\tcost NUMERIC(38, 0) DEFAULT \'0\' NOT NULL, \n\tprovider_tool_call_id TEXT COLLATE "C", \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id, occurred_at), \n\tCONSTRAINT uq_ai_tool_calls_invocation_ordinal UNIQUE (invocation_id, ordinal, occurred_at), \n\tCONSTRAINT ck_ai_tool_calls_status_known CHECK (status IN (\'STARTED\',\'COMPLETED\',\'FAILED\',\'TIMED_OUT\',\'CANCELLED\')), \n\tCONSTRAINT ck_ai_tool_calls_ordinal_nonneg CHECK (ordinal >= 0), \n\tCONSTRAINT ck_ai_tool_calls_arguments_object CHECK (jsonb_typeof(arguments) = \'object\'), \n\tCONSTRAINT ck_ai_tool_calls_completed_pair CHECK (completed_at IS NOT NULL = (status = \'COMPLETED\')), \n\tCONSTRAINT ck_ai_tool_calls_cost_nonneg CHECK (cost >= 0)\n)\n PARTITION BY RANGE (occurred_at)\n\n',
        index_sql=('CREATE INDEX ix_ai_tool_calls_invocation ON trading.ai_tool_calls (invocation_id, occurred_at)',),
    ),
    _FrozenTableSpec(
        name='ai_validation_results',
        create_sql='\nCREATE TABLE trading.ai_validation_results (\n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\toccurred_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tinvocation_id BIGINT NOT NULL, \n\tvalidator_name VARCHAR(64) NOT NULL, \n\tvalidator_version VARCHAR(64), \n\tpassed BOOLEAN NOT NULL, \n\tseverity VARCHAR(16) NOT NULL, \n\treason_code VARCHAR(128), \n\tdetails_artifact_hash VARCHAR(64) COLLATE "C", \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id, occurred_at), \n\tCONSTRAINT uq_ai_validation_results_invocation_validator UNIQUE (invocation_id, validator_name, occurred_at), \n\tCONSTRAINT ck_ai_validation_results_severity_known CHECK (severity IN (\'hard\',\'soft\')), \n\tCONSTRAINT ck_ai_validation_results_name_nonempty CHECK (validator_name <> \'\')\n)\n PARTITION BY RANGE (occurred_at)\n\n',
        index_sql=('CREATE INDEX ix_ai_validation_results_invocation ON trading.ai_validation_results (invocation_id, occurred_at)',),
    ),
)

# b1000021 之前已存在的 trading 关系（downgrade preflight allowlist）
_PRE_0021_RELATIONS = (
    "artifact_objects", "artifact_lineage_edges", "archive_manifests",
    "retention_manifests", "runtime_config_versions", "strategy_objective_contracts",
    "strategy_versions", "execution_spec_versions", "capital_permission_manifests",
    "model_role_bindings", "release_manifests", "policy_type_scopes", "policy_freezes",
    "secret_vault_entries", "secret_vault_versions", "secret_access_events",
    "idempotency_claims", "transactional_outbox", "outbox_delivery_history",
    "job_completions", "pm_universe_frames", "pm_universe_frame_pages", "pm_events",
    "pm_markets", "pm_market_versions", "pm_tokens", "pm_token_versions",
    "pm_market_lifecycle_events", "pm_market_current", "pm_connection_epochs",
    "pm_source_event_batches", "pm_source_event_index", "pm_book_checkpoints",
    "pm_book_levels", "pm_book_current", "pm_quote_bindings", "contract_snapshots",
    "contract_specs", "payout_functions", "forecast_components", "world_schema_versions",
    "forecast_component_versions", "forecast_component_contract_specs",
    "portfolio_dependency_edges", "evaluation_cohorts", "universe_memberships",
    "screening_episodes", "audit_samples", "decision_opportunities",
    "decision_opportunity_markets", "episode_memberships", "forecast_episodes",
    "episode_contract_specs", "information_snapshots", "information_snapshot_items",
    "gate_decisions", "priors", "evidence_coverage_policies", "evidence_revisions",
    "evidence_bundles", "evidence_bundle_items", "forecast_input_manifests",
    "forecast_submissions", "payout_projections", "coherence_checks",
    "forecast_challenges", "forecast_leases",
)


def _partition_names(anchor: str, table: str):
    """返回 (分区名, 起始, 结束) 元组；anchor 为 'YYYY-MM'。"""
    year, month = int(anchor[:4]), int(anchor[5:7])
    names = []
    for offset in (0, 1):
        y, m = (year, month + offset)
        while m > 12:
            y, m = y + 1, m - 12
        start = f"{y:04d}-{m:02d}-01"
        y2, m2 = (y, m + 1)
        while m2 > 12:
            y2, m2 = y2 + 1, m2 - 12
        end = f"{y2:04d}-{m2:02d}-01"
        names.append((f"{table}_{y:04d}{m:02d}", start, end))
    return names


def _assert_downgrade_safe() -> None:
    """拒绝在存在未知下游对象时直接 downgrade。"""
    allowed = ", ".join(
        f"'{name}'" for name in (*_PRE_0021_RELATIONS, *(t.name for t in _AI_TABLES))
    )
    op.execute(
        f"""
DO $v2_wp02_ai_preflight$
DECLARE unknown_objects text;
BEGIN
    SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
      INTO unknown_objects
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'trading'
       AND c.relkind IN ('r','p','v','m','f')
       AND c.relname NOT IN ({allowed})
       AND NOT EXISTS (
           SELECT 1 FROM pg_inherits i
           JOIN pg_class p ON p.oid = i.inhparent
           JOIN pg_namespace pn ON pn.oid = p.relnamespace
           WHERE i.inhrelid = c.oid AND pn.nspname = 'trading'
             AND ((p.relname = 'outbox_delivery_history'
                   AND c.relname ~ '^outbox_delivery_history_[0-9]{{6}}$')
               OR (p.relname IN ('pm_source_event_batches','pm_source_event_index',
                                  'pm_book_checkpoints','pm_book_levels')
                   AND c.relname ~ ('^' || p.relname || '_[0-9]{{8}}$'))
               OR (p.relname IN ('ai_invocations','ai_tool_calls','ai_validation_results')
                   AND c.relname ~ ('^' || p.relname || '_[0-9]{{6}}$')))
       );
    IF unknown_objects IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp02_ai_unknown_object:%', unknown_objects USING ERRCODE='55000';
    END IF;
END $v2_wp02_ai_preflight$
"""
    )


def _create_table_indexes(table: _FrozenTableSpec) -> None:
    for statement in table.index_sql:
        op.execute(statement)


def _create_partitions(anchor: str) -> None:
    for table in _AI_TABLES:
        if not table.partitioned:
            continue
        for name, start, end in _partition_names(anchor, table.name):
            op.execute(
                f"CREATE TABLE {TRADING_SCHEMA}.{name} "
                f"PARTITION OF {TRADING_SCHEMA}.{table.name} "
                f"FOR VALUES FROM ('{start}') TO ('{end}')"
            )


def _reinforce_bindings_and_lineage() -> None:
    """model_role_bindings → typed/versioned；artifact_lineage_edges.relation → 新 allowlist。"""
    # model_role_bindings：legacy 行按可解析旧值反填（provider 从 model_ref 前缀猜测失败时
    # 用 '__legacy__' 保留），保证旧数据不丢、不伪造 live binding。
    op.execute(
        """
DO $v2_mrb_preflight$
DECLARE
    ambiguous integer;
BEGIN
    SELECT count(*) INTO ambiguous
      FROM (
        SELECT strategy_version_id, role FROM trading.model_role_bindings
         GROUP BY strategy_version_id, role HAVING count(*) > 1
      ) d;
    IF ambiguous > 0 THEN
        RAISE EXCEPTION 'v2_model_role_binding_ambiguous' USING ERRCODE='55000';
    END IF;
END $v2_mrb_preflight$
"""
    )
    op.execute("ALTER TABLE trading.model_role_bindings ADD COLUMN provider VARCHAR(32)")
    op.execute("ALTER TABLE trading.model_role_bindings ADD COLUMN route VARCHAR(64)")
    op.execute("ALTER TABLE trading.model_role_bindings ADD COLUMN network_policy VARCHAR(32)")
    op.execute("ALTER TABLE trading.model_role_bindings ADD COLUMN allowed_tools JSONB")
    op.execute("ALTER TABLE trading.model_role_bindings ADD COLUMN allowed_domains JSONB")
    op.execute("ALTER TABLE trading.model_role_bindings ADD COLUMN capability JSONB")
    op.execute("ALTER TABLE trading.model_role_bindings ADD COLUMN binding_version INTEGER")
    op.execute(
        "UPDATE trading.model_role_bindings SET "
        "provider='__legacy__', route='__legacy__', network_policy='NONE', "
        "allowed_tools='[]'::jsonb, allowed_domains='[]'::jsonb, "
        "capability='{}'::jsonb, binding_version=0"
    )
    for column in (
        "provider", "route", "network_policy", "allowed_tools", "allowed_domains",
        "capability", "binding_version",
    ):
        op.execute(f"ALTER TABLE trading.model_role_bindings ALTER COLUMN {column} SET NOT NULL")
    # 与 ORM server_default 一致，避免 alembic check 报 modify_default drift
    op.execute(
        "ALTER TABLE trading.model_role_bindings ALTER COLUMN network_policy SET DEFAULT 'NONE'"
    )
    op.execute(
        "ALTER TABLE trading.model_role_bindings ALTER COLUMN allowed_tools SET DEFAULT '[]'::jsonb"
    )
    op.execute(
        "ALTER TABLE trading.model_role_bindings ALTER COLUMN allowed_domains SET DEFAULT '[]'::jsonb"
    )
    op.execute(
        "ALTER TABLE trading.model_role_bindings ALTER COLUMN capability SET DEFAULT '{}'::jsonb"
    )
    op.execute(
        "ALTER TABLE trading.model_role_bindings ALTER COLUMN binding_version SET DEFAULT 0"
    )
    op.execute(
        "ALTER TABLE trading.model_role_bindings "
        "DROP CONSTRAINT IF EXISTS uq_model_role_bindings_strategy_role"
    )
    op.execute(
        "ALTER TABLE trading.model_role_bindings "
        "ADD CONSTRAINT uq_model_role_bindings_strategy_role_version "
        "UNIQUE (strategy_version_id, role, binding_version)"
    )
    op.execute(
        "ALTER TABLE trading.model_role_bindings "
        "ADD CONSTRAINT ck_model_role_bindings_provider_known "
        "CHECK (provider IN ('deepseek','xai','gemini','kimi','packy','__legacy__'))"
    )
    op.execute(
        "ALTER TABLE trading.model_role_bindings "
        "ADD CONSTRAINT ck_model_role_bindings_network_policy_known "
        "CHECK (network_policy IN ('NONE','WEB_X','SEARCH_URL'))"
    )
    op.execute(
        "ALTER TABLE trading.model_role_bindings "
        "ADD CONSTRAINT ck_model_role_bindings_tools_array "
        "CHECK (jsonb_typeof(allowed_tools) = 'array')"
    )
    op.execute(
        "ALTER TABLE trading.model_role_bindings "
        "ADD CONSTRAINT ck_model_role_bindings_domains_array "
        "CHECK (jsonb_typeof(allowed_domains) = 'array')"
    )
    op.execute(
        "ALTER TABLE trading.model_role_bindings "
        "ADD CONSTRAINT ck_model_role_bindings_capability_object "
        "CHECK (jsonb_typeof(capability) = 'object')"
    )
    op.execute(
        "ALTER TABLE trading.model_role_bindings "
        "ADD CONSTRAINT ck_model_role_bindings_version_nonneg "
        "CHECK (binding_version >= 0)"
    )

    # artifact_lineage_edges.relation：扩展 allowlist，保留旧值。
    op.execute(
        "ALTER TABLE trading.artifact_lineage_edges "
        "DROP CONSTRAINT IF EXISTS ck_artifact_lineage_edges_relation_known"
    )
    op.execute(
        "ALTER TABLE trading.artifact_lineage_edges "
        "ADD CONSTRAINT ck_artifact_lineage_edges_relation_known "
        "CHECK (relation IN ('READS','PRODUCES','VALIDATES','SUPERSEDES','PROJECTS_TO','USED_BY',"
        " 'derived','supersedes','references','raw'))"
    )


def _unreinforce_bindings_and_lineage() -> None:
    """撤销强化并恢复 b1000020 原约束。"""
    op.execute(
        "ALTER TABLE trading.artifact_lineage_edges "
        "DROP CONSTRAINT IF EXISTS ck_artifact_lineage_edges_relation_known"
    )
    op.execute(
        "ALTER TABLE trading.artifact_lineage_edges "
        "ADD CONSTRAINT ck_artifact_lineage_edges_relation_known "
        "CHECK (relation IN ('derived','supersedes','references','raw'))"
    )
    op.execute(
        "ALTER TABLE trading.model_role_bindings "
        "DROP CONSTRAINT IF EXISTS ck_model_role_bindings_version_nonneg"
    )
    op.execute(
        "ALTER TABLE trading.model_role_bindings "
        "DROP CONSTRAINT IF EXISTS ck_model_role_bindings_capability_object"
    )
    op.execute(
        "ALTER TABLE trading.model_role_bindings "
        "DROP CONSTRAINT IF EXISTS ck_model_role_bindings_domains_array"
    )
    op.execute(
        "ALTER TABLE trading.model_role_bindings "
        "DROP CONSTRAINT IF EXISTS ck_model_role_bindings_tools_array"
    )
    op.execute(
        "ALTER TABLE trading.model_role_bindings "
        "DROP CONSTRAINT IF EXISTS ck_model_role_bindings_network_policy_known"
    )
    op.execute(
        "ALTER TABLE trading.model_role_bindings "
        "DROP CONSTRAINT IF EXISTS ck_model_role_bindings_provider_known"
    )
    op.execute(
        "ALTER TABLE trading.model_role_bindings "
        "DROP CONSTRAINT IF EXISTS uq_model_role_bindings_strategy_role_version"
    )
    op.execute(
        "ALTER TABLE trading.model_role_bindings "
        "ADD CONSTRAINT uq_model_role_bindings_strategy_role "
        "UNIQUE (strategy_version_id, role)"
    )
    op.execute("ALTER TABLE trading.model_role_bindings DROP COLUMN IF EXISTS binding_version")
    op.execute("ALTER TABLE trading.model_role_bindings DROP COLUMN IF EXISTS capability")
    op.execute("ALTER TABLE trading.model_role_bindings DROP COLUMN IF EXISTS allowed_domains")
    op.execute("ALTER TABLE trading.model_role_bindings DROP COLUMN IF EXISTS allowed_tools")
    op.execute("ALTER TABLE trading.model_role_bindings DROP COLUMN IF EXISTS network_policy")
    op.execute("ALTER TABLE trading.model_role_bindings DROP COLUMN IF EXISTS route")
    op.execute("ALTER TABLE trading.model_role_bindings DROP COLUMN IF EXISTS provider")


def _create_guards() -> None:
    """ai_invocations 用生命周期 guard（允许状态推进、禁改 terminal/identity）；
    其余两张纯 append-only。"""
    # ai_tool_calls / ai_validation_results：纯 append-only
    for table in ("ai_tool_calls", "ai_validation_results"):
        op.execute(
            f"CREATE TRIGGER trg_{table}_immutable "
            f"BEFORE UPDATE OR DELETE ON {TRADING_SCHEMA}.{table} "
            "FOR EACH ROW EXECUTE FUNCTION trading.v2_reject_immutable_row()"
        )
    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_ai_invocation() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    terminal text[] := ARRAY['ACCEPTED','REJECTED','FAILED','TIMEOUT','CANCELLED','UNKNOWN'];
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.lifecycle_state <> 'PLANNED' OR NEW.accepted_at IS NOT NULL
           OR NEW.terminal_reason IS NOT NULL THEN
            RAISE EXCEPTION 'v2_ai_invocation_initial_state_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_ai_invocation_immutable' USING ERRCODE='55000';
    END IF;
    -- identity 不可变
    IF OLD.invocation_key IS DISTINCT FROM NEW.invocation_key
       OR OLD.episode_id IS DISTINCT FROM NEW.episode_id
       OR OLD.stage IS DISTINCT FROM NEW.stage
       OR OLD.role IS DISTINCT FROM NEW.role
       OR OLD.attempt_no IS DISTINCT FROM NEW.attempt_no
       OR OLD.experiment_variant IS DISTINCT FROM NEW.experiment_variant
       OR OLD.requested_provider IS DISTINCT FROM NEW.requested_provider
       OR OLD.requested_route IS DISTINCT FROM NEW.requested_route
       OR OLD.requested_model IS DISTINCT FROM NEW.requested_model
       OR OLD.network_policy IS DISTINCT FROM NEW.network_policy
       OR OLD.context_class IS DISTINCT FROM NEW.context_class
       OR OLD.input_manifest_hash IS DISTINCT FROM NEW.input_manifest_hash
       OR OLD.occurred_at IS DISTINCT FROM NEW.occurred_at
       OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
        RAISE EXCEPTION 'v2_ai_invocation_identity_immutable' USING ERRCODE='55000';
    END IF;
    -- terminal 行禁止再改
    IF OLD.lifecycle_state = ANY(terminal) AND NEW.lifecycle_state IS DISTINCT FROM OLD.lifecycle_state THEN
        RAISE EXCEPTION 'v2_ai_invocation_terminal_immutable' USING ERRCODE='55000';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_ai_invocations_lifecycle "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.ai_invocations "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_ai_invocation()"
    )


def _drop_guards() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_ai_invocations_lifecycle ON trading.ai_invocations")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_ai_invocation()")
    for table in ("ai_validation_results", "ai_tool_calls"):
        op.execute(
            f"DROP TRIGGER IF EXISTS trg_{table}_immutable "
            f"ON {TRADING_SCHEMA}.{table}"
        )


def upgrade() -> None:
    """Create 3 AI partitioned tables + partitions + reinforcement + guards."""
    for table in _AI_TABLES:
        op.execute(table.create_sql)
        _create_table_indexes(table)
    anchor = datetime.now(timezone.utc).strftime("%Y-%m")
    _create_partitions(anchor)
    _reinforce_bindings_and_lineage()
    _create_guards()


def downgrade() -> None:
    """Drop 3 tables + partitions + undo reinforcement."""
    _assert_downgrade_safe()
    _drop_guards()
    for table in reversed(_AI_TABLES):
        # 先删分区子表再删父表
        for name, _, _ in _partition_names(datetime.now(timezone.utc).strftime("%Y-%m"), table.name):
            op.execute(f"DROP TABLE IF EXISTS {TRADING_SCHEMA}.{name}")
        op.execute(f"DROP TABLE {TRADING_SCHEMA}.{table.name}")
    _unreinforce_bindings_and_lineage()
