"""create p2 decision shadow

Revision ID: b1000030
Revises: b1000021
Create Date: 2026-08-11 14:00:00

v2_0030 —— Decision、G7A、Action Set（WP-03 Checkpoint B）。

- ``upgrade``：
  - 9 张 decision 表（market_relative_decisions、discrepancy_reviews、trade_decisions、
    action_candidates、resolution_cashflows、action_sets、action_set_legs、underwriting_plans、
    economic_action_intents）。
  - ``pm_quote_bindings`` 强化：新增 nullable ``trade_decision_id`` FK；删除旧
    ``(token_id,checkpoint_id,checkpoint_received_at)`` 唯一约束，允许不同 decision 复用同一
    checkpoint；新增 partial unique index ``(trade_decision_id,token_id) WHERE trade_decision_id
    IS NOT NULL``。
  - ``gate_decisions`` / ``information_snapshots`` 强化：gate allowlist 增加 ``G7A/G7B``
    （绑 trade_decision）；information_snapshots 新增 ``trade_decision_id`` 目标。
  - ``forecast_episodes`` 强化：status 允许 ``REVEALED/DECIDED``。
  - lifecycle guards：trade_decisions 状态机（CREATED→QUOTE_BOUND→G7A→G7B→ACTION|WAIT|ABSTAIN，
    三结果 terminal）；action_sets/intent/market_relative append-only。
- ``downgrade``：逆序删 9 表 + guard；撤销 quote/gate/episode 强化；恢复 b1000021 原约束。
  未知对象 fail-closed。
"""
from dataclasses import dataclass
from typing import Sequence, Union

from alembic import op

TRADING_SCHEMA = "trading"

# revision identifiers, used by Alembic.
revision: str = "b1000030"
down_revision: Union[str, Sequence[str], None] = "b1000021"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_GATES = ("G0", "R0", "G1", "G2", "R1", "G4", "G5A", "G5B", "G6", "G7A", "G7B")
_GATE_VALUES = ", ".join(f"'{g}'" for g in _GATES)


@dataclass(frozen=True)
class _FrozenTableSpec:
    name: str
    create_sql: str
    index_sql: tuple[str, ...] = ()
    append_only: bool = True


_DECISION_TABLES = (
    _FrozenTableSpec(
        name='trade_decisions',
        create_sql='\nCREATE TABLE trading.trade_decisions (\n\tdecision_key VARCHAR(64) COLLATE "C" NOT NULL, \n\tepisode_id BIGINT NOT NULL, \n\tforecast_submission_id BIGINT NOT NULL, \n\tforecast_lease_id BIGINT, \n\tobjective_contract_id BIGINT NOT NULL, \n\tstrategy_version_id BIGINT NOT NULL, \n\trelease_manifest_id BIGINT NOT NULL, \n\texecution_spec_version_id BIGINT NOT NULL, \n\tcapital_permission_manifest_id BIGINT NOT NULL, \n\texperiment_variant VARCHAR(64) NOT NULL, \n\tdecision_class VARCHAR(32) DEFAULT \'CHAMPION\' NOT NULL, \n\tstatus VARCHAR(16) DEFAULT \'CREATED\' NOT NULL, \n\tselected_action_type VARCHAR(32), \n\ttrigger_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tquote_bound_at TIMESTAMP WITH TIME ZONE, \n\tdecided_at TIMESTAMP WITH TIME ZONE, \n\tinput_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\toutput_hash VARCHAR(64) COLLATE "C", \n\treason_code VARCHAR(128), \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_trade_decisions_key UNIQUE (decision_key), \n\tCONSTRAINT ck_trade_decisions_status_known CHECK (status IN (\'CREATED\',\'QUOTE_BOUND\',\'G7A\',\'G7B\',\'ACTION\',\'WAIT\',\'ABSTAIN\')), \n\tCONSTRAINT ck_trade_decisions_class_known CHECK (decision_class IN (\'CHAMPION\',\'RISK_REVIEW\')), \n\tCONSTRAINT ck_trade_decisions_variant_nonempty CHECK (experiment_variant <> \'\'), \n\tCONSTRAINT ck_trade_decisions_quote_bound_pair CHECK (quote_bound_at IS NOT NULL = (status IN (\'QUOTE_BOUND\',\'G7A\',\'G7B\',\'ACTION\',\'WAIT\',\'ABSTAIN\'))), \n\tCONSTRAINT ck_trade_decisions_terminal_pair CHECK ((status IN (\'ACTION\',\'WAIT\',\'ABSTAIN\')) = (decided_at IS NOT NULL)), \n\tCONSTRAINT ck_trade_decisions_timeline_order CHECK (quote_bound_at IS NULL OR (trigger_at < quote_bound_at AND  (decided_at IS NULL OR quote_bound_at <= decided_at))), \n\tCONSTRAINT ck_trade_decisions_abstain_reason CHECK (status <> \'ABSTAIN\' OR reason_code IS NOT NULL), \n\tCONSTRAINT fk_trade_decisions_episode FOREIGN KEY(episode_id) REFERENCES trading.forecast_episodes (id), \n\tCONSTRAINT fk_trade_decisions_submission FOREIGN KEY(forecast_submission_id) REFERENCES trading.forecast_submissions (id), \n\tCONSTRAINT fk_trade_decisions_lease FOREIGN KEY(forecast_lease_id) REFERENCES trading.forecast_leases (id), \n\tCONSTRAINT fk_trade_decisions_objective FOREIGN KEY(objective_contract_id) REFERENCES trading.strategy_objective_contracts (id), \n\tCONSTRAINT fk_trade_decisions_strategy FOREIGN KEY(strategy_version_id) REFERENCES trading.strategy_versions (id), \n\tCONSTRAINT fk_trade_decisions_release FOREIGN KEY(release_manifest_id) REFERENCES trading.release_manifests (id), \n\tCONSTRAINT fk_trade_decisions_exec_spec FOREIGN KEY(execution_spec_version_id) REFERENCES trading.execution_spec_versions (id), \n\tCONSTRAINT fk_trade_decisions_capital FOREIGN KEY(capital_permission_manifest_id) REFERENCES trading.capital_permission_manifests (id)\n)\n\n',
        append_only=False,
    ),
    _FrozenTableSpec(
        name='market_relative_decisions',
        create_sql='\nCREATE TABLE trading.market_relative_decisions (\n\ttrade_decision_id BIGINT NOT NULL, \n\tdecision_mode VARCHAR(32) NOT NULL, \n\tw_blind NUMERIC(38, 0), \n\tq_blind JSONB NOT NULL, \n\tq_decision JSONB NOT NULL, \n\tu_decision JSONB NOT NULL, \n\tu_blind_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tu_decision_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\ttoken_gaps JSONB NOT NULL, \n\treference_identifiability JSONB NOT NULL, \n\tinput_manifest_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\toutput_manifest_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_market_relative_decisions_trade_decision UNIQUE (trade_decision_id), \n\tCONSTRAINT ck_market_relative_decisions_mode_known CHECK (decision_mode IN (\'BLIND_ONLY\',\'LINEAR_SHRINKAGE\')), \n\tCONSTRAINT ck_market_relative_decisions_w_range CHECK (w_blind IS NULL OR (w_blind >= 0 AND w_blind <= 1)), \n\tCONSTRAINT ck_market_relative_decisions_q_blind_object CHECK (jsonb_typeof(q_blind) = \'object\'), \n\tCONSTRAINT ck_market_relative_decisions_q_decision_object CHECK (jsonb_typeof(q_decision) = \'object\'), \n\tCONSTRAINT ck_market_relative_decisions_u_decision_array CHECK (jsonb_typeof(u_decision) = \'array\'), \n\tCONSTRAINT ck_market_relative_decisions_gaps_object CHECK (jsonb_typeof(token_gaps) = \'object\'), \n\tCONSTRAINT ck_market_relative_decisions_reference_object CHECK (jsonb_typeof(reference_identifiability) = \'object\'), \n\tCONSTRAINT fk_market_relative_decisions_decision FOREIGN KEY(trade_decision_id) REFERENCES trading.trade_decisions (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='discrepancy_reviews',
        create_sql='\nCREATE TABLE trading.discrepancy_reviews (\n\ttrade_decision_id BIGINT NOT NULL, \n\treview_key TEXT COLLATE "C" NOT NULL, \n\tkind VARCHAR(32) NOT NULL, \n\tresult VARCHAR(16) NOT NULL, \n\treason_code VARCHAR(128), \n\tfindings JSONB NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_discrepancy_reviews_decision_key UNIQUE (trade_decision_id, review_key), \n\tCONSTRAINT ck_discrepancy_reviews_kind_known CHECK (kind IN (\'materiality\',\'staleness\',\'rule_schema\',\'book_integrity\')), \n\tCONSTRAINT ck_discrepancy_reviews_result_known CHECK (result IN (\'PASS\',\'FAIL\')), \n\tCONSTRAINT ck_discrepancy_reviews_findings_object CHECK (jsonb_typeof(findings) = \'object\'), \n\tCONSTRAINT fk_discrepancy_reviews_decision FOREIGN KEY(trade_decision_id) REFERENCES trading.trade_decisions (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='action_candidates',
        create_sql='\nCREATE TABLE trading.action_candidates (\n\ttrade_decision_id BIGINT NOT NULL, \n\tcontract_spec_id BIGINT NOT NULL, \n\ttoken_id BIGINT NOT NULL, \n\taction_type VARCHAR(32) NOT NULL, \n\tfill_quantity NUMERIC(38, 0) NOT NULL, \n\tvwap NUMERIC(38, 0) NOT NULL, \n\texecutable_depth JSONB NOT NULL, \n\tcost_components JSONB NOT NULL, \n\tcashflow_reconciliation_residual NUMERIC(38, 0) DEFAULT \'0\' NOT NULL, \n\tgross_edge NUMERIC(38, 0), \n\tbreak_even_payout_probability NUMERIC(38, 0), \n\tnet_edge NUMERIC(38, 0), \n\trobust_ev NUMERIC(38, 0), \n\tpoint_ev NUMERIC(38, 0), \n\troi NUMERIC(38, 0), \n\texpected_log_growth NUMERIC(38, 0), \n\tworst_loss NUMERIC(38, 0), \n\tcapital_days NUMERIC(38, 0), \n\tedge_delay_erosion NUMERIC(38, 0), \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_action_candidates_decision_token_action UNIQUE (trade_decision_id, contract_spec_id, token_id, action_type), \n\tCONSTRAINT ck_action_candidates_action_known CHECK (action_type IN (\'BUY_TOKEN\',\'ADD_TOKEN\',\'SELL_TOKEN_TO_REDUCE\',\'SELL_TOKEN_TO_CLOSE\',\'HOLD\',\'FLIP\')), \n\tCONSTRAINT ck_action_candidates_depth_object CHECK (jsonb_typeof(executable_depth) = \'object\'), \n\tCONSTRAINT ck_action_candidates_cost_object CHECK (jsonb_typeof(cost_components) = \'object\'), \n\tCONSTRAINT ck_action_candidates_recon_zero CHECK (cashflow_reconciliation_residual = 0), \n\tCONSTRAINT ck_action_candidates_fill_positive CHECK (fill_quantity >= 0 AND vwap > 0), \n\tCONSTRAINT ck_action_candidates_gross_nonneg CHECK (gross_edge IS NULL OR gross_edge >= 0), \n\tCONSTRAINT fk_action_candidates_decision FOREIGN KEY(trade_decision_id) REFERENCES trading.trade_decisions (id), \n\tCONSTRAINT fk_action_candidates_spec FOREIGN KEY(contract_spec_id) REFERENCES trading.contract_specs (id), \n\tCONSTRAINT fk_action_candidates_token FOREIGN KEY(token_id) REFERENCES trading.pm_tokens (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='action_sets',
        create_sql='\nCREATE TABLE trading.action_sets (\n\taction_set_key VARCHAR(64) COLLATE "C" NOT NULL, \n\ttrade_decision_id BIGINT NOT NULL, \n\tdisposition VARCHAR(16) NOT NULL, \n\treason_code VARCHAR(128), \n\twake_condition VARCHAR(255), \n\trecheck_at TIMESTAMP WITH TIME ZONE, \n\taction_set_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_action_sets_key UNIQUE (action_set_key), \n\tCONSTRAINT ck_action_sets_disposition_known CHECK (disposition IN (\'ACTION\',\'WAIT\',\'ABSTAIN\')), \n\tCONSTRAINT ck_action_sets_abstain_reason CHECK (disposition <> \'ABSTAIN\' OR reason_code IS NOT NULL), \n\tCONSTRAINT ck_action_sets_wait_wake CHECK (disposition <> \'WAIT\' OR (wake_condition IS NOT NULL OR recheck_at IS NOT NULL)), \n\tCONSTRAINT fk_action_sets_decision FOREIGN KEY(trade_decision_id) REFERENCES trading.trade_decisions (id)\n)\n\n',
        append_only=False,
    ),
    _FrozenTableSpec(
        name='underwriting_plans',
        create_sql='\nCREATE TABLE trading.underwriting_plans (\n\ttrade_decision_id BIGINT NOT NULL, \n\tplan_version INTEGER NOT NULL, \n\tentry_range JSONB NOT NULL, \n\thold_to_resolution BOOLEAN NOT NULL, \n\tthesis_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tinvalidation JSONB NOT NULL, \n\twake_condition VARCHAR(255), \n\tedge_close_threshold NUMERIC(38, 0), \n\ttime_stop_at TIMESTAMP WITH TIME ZONE, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_underwriting_plans_decision_version UNIQUE (trade_decision_id, plan_version), \n\tCONSTRAINT ck_underwriting_plans_version_positive CHECK (plan_version > 0), \n\tCONSTRAINT ck_underwriting_plans_entry_range_object CHECK (jsonb_typeof(entry_range) = \'object\'), \n\tCONSTRAINT ck_underwriting_plans_invalidation_object CHECK (jsonb_typeof(invalidation) = \'object\'), \n\tCONSTRAINT ck_underwriting_plans_thesis_hex CHECK (thesis_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT fk_underwriting_plans_decision FOREIGN KEY(trade_decision_id) REFERENCES trading.trade_decisions (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='resolution_cashflows',
        create_sql='\nCREATE TABLE trading.resolution_cashflows (\n\taction_candidate_id BIGINT NOT NULL, \n\tworld_state_id TEXT COLLATE "C" NOT NULL, \n\tcashflow NUMERIC(38, 0) NOT NULL, \n\tsigned_flag VARCHAR(8) NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_resolution_cashflows_candidate_state UNIQUE (action_candidate_id, world_state_id), \n\tCONSTRAINT fk_resolution_cashflows_candidate FOREIGN KEY(action_candidate_id) REFERENCES trading.action_candidates (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='action_set_legs',
        create_sql='\nCREATE TABLE trading.action_set_legs (\n\taction_set_id BIGINT NOT NULL, \n\tcontract_spec_id BIGINT NOT NULL, \n\ttoken_id BIGINT NOT NULL, \n\tleg_role VARCHAR(16) NOT NULL, \n\tquantity NUMERIC(38, 0) NOT NULL, \n\tsigned_quantity NUMERIC(38, 0) NOT NULL, \n\tentry_vwap NUMERIC(38, 0) NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_action_set_legs_set_spec_token_role UNIQUE (action_set_id, contract_spec_id, token_id, leg_role), \n\tCONSTRAINT ck_action_set_legs_role_known CHECK (leg_role IN (\'open\',\'close\',\'reduce\',\'hold\')), \n\tCONSTRAINT ck_action_set_legs_quantity_positive CHECK (quantity > 0), \n\tCONSTRAINT ck_action_set_legs_signed_nonzero CHECK (signed_quantity <> 0), \n\tCONSTRAINT fk_action_set_legs_set FOREIGN KEY(action_set_id) REFERENCES trading.action_sets (id), \n\tCONSTRAINT fk_action_set_legs_spec FOREIGN KEY(contract_spec_id) REFERENCES trading.contract_specs (id), \n\tCONSTRAINT fk_action_set_legs_token FOREIGN KEY(token_id) REFERENCES trading.pm_tokens (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='economic_action_intents',
        create_sql='\nCREATE TABLE trading.economic_action_intents (\n\tintent_key TEXT COLLATE "C" NOT NULL, \n\tintent_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\ttrade_decision_id BIGINT NOT NULL, \n\taction_set_id BIGINT NOT NULL, \n\tstatus VARCHAR(32) DEFAULT \'PLANNED\' NOT NULL, \n\tttl_at TIMESTAMP WITH TIME ZONE, \n\tpreflight JSONB NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_economic_action_intents_key UNIQUE (intent_key), \n\tCONSTRAINT uq_economic_action_intents_hash UNIQUE (intent_hash), \n\tCONSTRAINT ck_economic_action_intents_hash_hex CHECK (intent_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_economic_action_intents_status_known CHECK (status IN (\'PLANNED\',\'COMMITTED\',\'SUPERSEDED\')), \n\tCONSTRAINT ck_economic_action_intents_preflight_object CHECK (jsonb_typeof(preflight) = \'object\'), \n\tCONSTRAINT ck_economic_action_intents_ttl_future CHECK (ttl_at IS NULL OR ttl_at > created_at), \n\tCONSTRAINT fk_economic_action_intents_decision FOREIGN KEY(trade_decision_id) REFERENCES trading.trade_decisions (id), \n\tCONSTRAINT fk_economic_action_intents_action_set FOREIGN KEY(action_set_id) REFERENCES trading.action_sets (id)\n)\n\n',
        append_only=False,
    ),
)
# b1000030 之前已存在的 trading 关系（downgrade preflight allowlist）
_PRE_0030_RELATIONS = (
    "artifact_objects", "artifact_lineage_edges", "archive_manifests",
    "retention_manifests", "runtime_config_versions", "strategy_objective_contracts",
    "strategy_versions", "execution_spec_versions", "capital_permission_manifests",
    "model_role_bindings", "release_manifests", "policy_type_scopes", "policy_freezes",
    "secret_vault_entries", "secret_vault_versions", "secret_access_events",
    "idempotency_claims", "transactional_outbox", "outbox_delivery_history",
    "job_completions", "pm_universe_frames", "pm_universe_frame_pages", "pm_events",
    "pm_markets", "pm_market_versions", "pm_tokens", "pm_token_versions",
    "pm_market_lifecycle_events", "pm_market_current", "pm_connection_epochs",
    "pm_source_event_batches", "pm_source_event_index", "pm_book_checkpoints",
    "pm_book_levels", "pm_book_current", "pm_quote_bindings", "contract_snapshots",
    "contract_specs", "payout_functions", "forecast_components", "world_schema_versions",
    "forecast_component_versions", "forecast_component_contract_specs",
    "portfolio_dependency_edges", "evaluation_cohorts", "universe_memberships",
    "screening_episodes", "audit_samples", "decision_opportunities",
    "decision_opportunity_markets", "episode_memberships", "forecast_episodes",
    "episode_contract_specs", "information_snapshots", "information_snapshot_items",
    "gate_decisions", "priors", "evidence_coverage_policies", "evidence_revisions",
    "evidence_bundles", "evidence_bundle_items", "forecast_input_manifests",
    "forecast_submissions", "payout_projections", "coherence_checks",
    "forecast_challenges", "forecast_leases", "ai_invocations", "ai_tool_calls",
    "ai_validation_results",
)


def _assert_downgrade_safe() -> None:
    allowed = ", ".join(
        f"'{name}'" for name in (*_PRE_0030_RELATIONS, *(t.name for t in _DECISION_TABLES))
    )
    op.execute(
        f"""
DO $v2_wp03_preflight$
DECLARE unknown_objects text;
BEGIN
    SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
      INTO unknown_objects
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'trading'
       AND c.relkind IN ('r','p','v','m','f')
       AND c.relname NOT IN ({allowed})
       AND NOT EXISTS (
           SELECT 1 FROM pg_inherits i
           JOIN pg_class p ON p.oid = i.inhparent
           JOIN pg_namespace pn ON pn.oid = p.relnamespace
           WHERE i.inhrelid = c.oid AND pn.nspname = 'trading'
             AND ((p.relname = 'outbox_delivery_history'
                   AND c.relname ~ '^outbox_delivery_history_[0-9]{{6}}$')
               OR (p.relname IN ('pm_source_event_batches','pm_source_event_index',
                                  'pm_book_checkpoints','pm_book_levels')
                   AND c.relname ~ ('^' || p.relname || '_[0-9]{{8}}$'))
               OR (p.relname IN ('ai_invocations','ai_tool_calls','ai_validation_results')
                   AND c.relname ~ ('^' || p.relname || '_[0-9]{{6}}$')))
       );
    IF unknown_objects IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp03_unknown_object:%', unknown_objects USING ERRCODE='55000';
    END IF;
END $v2_wp03_preflight$
"""
    )


def _reinforce_existing() -> None:
    """pm_quote_bindings / gate_decisions / information_snapshots / forecast_episodes 强化。"""
    # pm_quote_bindings：加 trade_decision_id；删旧唯一；加 partial unique index。
    op.execute("ALTER TABLE trading.pm_quote_bindings ADD COLUMN trade_decision_id BIGINT")
    op.execute(
        "ALTER TABLE trading.pm_quote_bindings ADD CONSTRAINT fk_pm_quote_bindings_trade_decision "
        "FOREIGN KEY(trade_decision_id) REFERENCES trading.trade_decisions (id)"
    )
    op.execute(
        "ALTER TABLE trading.pm_quote_bindings "
        "DROP CONSTRAINT IF EXISTS uq_pm_quote_bindings_token_checkpoint"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_pm_quote_bindings_decision_token "
        "ON trading.pm_quote_bindings (trade_decision_id, token_id) "
        "WHERE trade_decision_id IS NOT NULL"
    )
    # gate_decisions：G7A/G7B + trade_decision target
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "DROP CONSTRAINT IF EXISTS ck_gate_decisions_gate_known"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        f"ADD CONSTRAINT ck_gate_decisions_gate_known CHECK (gate IN ({_GATE_VALUES}))"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "DROP CONSTRAINT IF EXISTS ck_gate_decisions_target_kind_known"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "ADD CONSTRAINT ck_gate_decisions_target_kind_known CHECK ("
        "target_kind IN ('screening','opportunity','episode','trade_decision'))"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "DROP CONSTRAINT IF EXISTS ck_gate_decisions_gate_target_pair"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "ADD CONSTRAINT ck_gate_decisions_gate_target_pair CHECK ("
        "(gate IN ('G0','R0') AND target_kind = 'screening') OR "
        "(gate IN ('G1','G2') AND target_kind = 'opportunity') OR "
        "(gate IN ('R1','G4','G5A','G5B','G6') AND target_kind = 'episode') OR "
        "(gate IN ('G7A','G7B') AND target_kind = 'trade_decision'))"
    )
    # information_snapshots：G7A/G7B + trade_decision_id 目标
    op.execute(
        "ALTER TABLE trading.information_snapshots "
        "DROP CONSTRAINT IF EXISTS ck_information_snapshots_gate_known"
    )
    op.execute(
        "ALTER TABLE trading.information_snapshots "
        f"ADD CONSTRAINT ck_information_snapshots_gate_known CHECK (gate IN ({_GATE_VALUES}))"
    )
    op.execute("ALTER TABLE trading.information_snapshots ADD COLUMN trade_decision_id BIGINT")
    op.execute(
        "ALTER TABLE trading.information_snapshots ADD CONSTRAINT fk_information_snapshots_trade_decision "
        "FOREIGN KEY(trade_decision_id) REFERENCES trading.trade_decisions (id)"
    )
    op.execute(
        "ALTER TABLE trading.information_snapshots "
        "DROP CONSTRAINT IF EXISTS ck_information_snapshots_one_target"
    )
    op.execute(
        "ALTER TABLE trading.information_snapshots "
        "ADD CONSTRAINT ck_information_snapshots_one_target CHECK ("
        "(episode_id IS NOT NULL)::int + (opportunity_id IS NOT NULL)::int "
        "+ (trade_decision_id IS NOT NULL)::int = 1)"
    )
    # forecast_episodes：REVEALED/DECIDED
    op.execute(
        "ALTER TABLE trading.forecast_episodes "
        "DROP CONSTRAINT IF EXISTS ck_forecast_episodes_status_known"
    )
    op.execute(
        "ALTER TABLE trading.forecast_episodes "
        "ADD CONSTRAINT ck_forecast_episodes_status_known CHECK ("
        "status IN ('DRAFT','ROUTED','BLIND_COMMITTED','REVEALED','DECIDED','PRE_COMMIT_TERMINAL'))"
    )


def _unreinforce_existing() -> None:
    """撤销强化并恢复 b1000021 原约束。"""
    op.execute(
        "ALTER TABLE trading.forecast_episodes "
        "DROP CONSTRAINT IF EXISTS ck_forecast_episodes_status_known"
    )
    op.execute(
        "ALTER TABLE trading.forecast_episodes "
        "ADD CONSTRAINT ck_forecast_episodes_status_known CHECK ("
        "status IN ('DRAFT','ROUTED','BLIND_COMMITTED','PRE_COMMIT_TERMINAL'))"
    )
    op.execute(
        "ALTER TABLE trading.information_snapshots "
        "DROP CONSTRAINT IF EXISTS ck_information_snapshots_one_target"
    )
    op.execute(
        "ALTER TABLE trading.information_snapshots "
        "ADD CONSTRAINT ck_information_snapshots_one_target CHECK ("
        "(episode_id IS NULL) <> (opportunity_id IS NULL))"
    )
    op.execute(
        "ALTER TABLE trading.information_snapshots "
        "DROP CONSTRAINT IF EXISTS fk_information_snapshots_trade_decision"
    )
    op.execute("ALTER TABLE trading.information_snapshots DROP COLUMN IF EXISTS trade_decision_id")
    op.execute(
        "ALTER TABLE trading.information_snapshots "
        "DROP CONSTRAINT IF EXISTS ck_information_snapshots_gate_known"
    )
    op.execute(
        "ALTER TABLE trading.information_snapshots "
        "ADD CONSTRAINT ck_information_snapshots_gate_known CHECK ("
        "gate IN ('G0','R0','G1','G2','R1','G4','G5A','G5B','G6'))"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "DROP CONSTRAINT IF EXISTS ck_gate_decisions_gate_target_pair"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "ADD CONSTRAINT ck_gate_decisions_gate_target_pair CHECK ("
        "(gate IN ('G0','R0') AND target_kind = 'screening') OR "
        "(gate IN ('G1','G2') AND target_kind = 'opportunity') OR "
        "(gate IN ('R1','G4','G5A','G5B','G6') AND target_kind = 'episode'))"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "DROP CONSTRAINT IF EXISTS ck_gate_decisions_target_kind_known"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "ADD CONSTRAINT ck_gate_decisions_target_kind_known CHECK ("
        "target_kind IN ('screening','opportunity','episode'))"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "DROP CONSTRAINT IF EXISTS ck_gate_decisions_gate_known"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "ADD CONSTRAINT ck_gate_decisions_gate_known CHECK ("
        "gate IN ('G0','R0','G1','G2','R1','G4','G5A','G5B','G6'))"
    )
    op.execute("DROP INDEX IF EXISTS uq_pm_quote_bindings_decision_token")
    op.execute(
        "ALTER TABLE trading.pm_quote_bindings "
        "ADD CONSTRAINT uq_pm_quote_bindings_token_checkpoint "
        "UNIQUE (token_id, checkpoint_id, checkpoint_received_at)"
    )
    op.execute(
        "ALTER TABLE trading.pm_quote_bindings "
        "DROP CONSTRAINT IF EXISTS fk_pm_quote_bindings_trade_decision"
    )
    op.execute("ALTER TABLE trading.pm_quote_bindings DROP COLUMN IF EXISTS trade_decision_id")


def _gate_guard_fn() -> str:
    return r"""
CREATE FUNCTION trading.v2_guard_gate_decision() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    root_id bigint;
    screening_id bigint;
    opportunity_id bigint;
BEGIN
    IF NEW.gate IN ('G0','R0') THEN
        IF NOT EXISTS (SELECT 1 FROM trading.screening_episodes WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NEW.gate IN ('G1','G2') THEN
        IF NOT EXISTS (SELECT 1 FROM trading.decision_opportunities WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NEW.gate IN ('G7A','G7B') THEN
        IF NOT EXISTS (SELECT 1 FROM trading.trade_decisions WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NOT EXISTS (SELECT 1 FROM trading.forecast_episodes WHERE id = NEW.target_id) THEN
        RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
    END IF;

    IF (NEW.gate = 'G0' AND NEW.result NOT IN ('PASS','PREDICTION_RESEARCH_ONLY'))
       OR (NEW.gate = 'R0' AND NEW.result NOT IN ('SELECT','DEFER','REJECT'))
       OR (NEW.gate IN ('G1','G2') AND NEW.result NOT IN ('PASS','FAIL'))
       OR (NEW.gate = 'R1' AND NEW.result NOT IN ('reject','shallow','standard','deep'))
       OR (NEW.gate = 'G4' AND NEW.result NOT IN ('PASS','FAIL'))
       OR (NEW.gate = 'G5A' AND NEW.result NOT IN ('PASS','ABSTAIN_EVIDENCE_INTEGRITY'))
       OR (NEW.gate = 'G5B' AND NEW.result NOT IN ('PASS','WIDEN_REQUIRED','ABSTAIN_EVIDENCE_INSUFFICIENT'))
       OR (NEW.gate IN ('G6','G7A','G7B') AND NEW.result NOT IN ('PASS','FAIL')) THEN
        RAISE EXCEPTION 'v2_gate_result_invalid' USING ERRCODE='23514';
    END IF;
    IF NEW.result IN ('PREDICTION_RESEARCH_ONLY','DEFER','REJECT','FAIL',
                      'ABSTAIN_EVIDENCE_INTEGRITY','WIDEN_REQUIRED','ABSTAIN_EVIDENCE_INSUFFICIENT','reject')
       AND NEW.reason_code IS NULL THEN
        RAISE EXCEPTION 'v2_gate_failure_reason_required' USING ERRCODE='23514';
    END IF;

    IF NEW.gate = 'R0' AND NOT EXISTS (
        SELECT 1 FROM trading.gate_decisions gd
         WHERE gd.gate = 'G0' AND gd.target_kind = 'screening'
           AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
    ) THEN
        RAISE EXCEPTION 'v2_gate_order_g0_r0' USING ERRCODE='23514';
    ELSIF NEW.gate = 'G1' THEN
        SELECT COALESCE(o.parent_id, o.id) INTO STRICT root_id
          FROM trading.decision_opportunities o WHERE o.id = NEW.target_id;
        SELECT source_screening_episode_id INTO screening_id
          FROM trading.decision_opportunities WHERE id = root_id;
        IF screening_id IS NULL OR NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'R0' AND gd.target_kind = 'screening'
               AND gd.target_id = screening_id
               AND (gd.result = 'SELECT' OR EXISTS (
                    SELECT 1 FROM trading.screening_episodes se
                     WHERE se.id = screening_id AND se.audit_assigned))
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_r0_g1' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G2' THEN
        SELECT COALESCE(o.parent_id, o.id) INTO STRICT root_id
          FROM trading.decision_opportunities o WHERE o.id = NEW.target_id;
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
            JOIN trading.decision_opportunities prior ON prior.id = gd.target_id
             WHERE gd.gate = 'G1' AND gd.target_kind = 'opportunity' AND gd.result = 'PASS'
               AND COALESCE(prior.parent_id, prior.id) = root_id
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g1_g2' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'R1' THEN
        SELECT decision_opportunity_id INTO STRICT opportunity_id
          FROM trading.forecast_episodes WHERE id = NEW.target_id;
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G2' AND gd.target_kind = 'opportunity'
               AND gd.target_id = opportunity_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g2_r1' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G4' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'R1' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id
               AND gd.result IN ('shallow','standard','deep')
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_r1_g4' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G5A' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G4' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g4_g5a' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G5B' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G5A' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g5a_g5b' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G6' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G5B' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g5b_g6' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G7B' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G7A' AND gd.target_kind = 'trade_decision'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g7a_g7b' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $v2_guard$
"""


def _create_guards() -> None:
    for table in _DECISION_TABLES:
        if table.append_only:
            op.execute(
                f"CREATE TRIGGER trg_{table.name}_immutable "
                f"BEFORE UPDATE OR DELETE ON {TRADING_SCHEMA}.{table.name} "
                "FOR EACH ROW EXECUTE FUNCTION trading.v2_reject_immutable_row()"
            )
    # 替换 gate guard（G7A/G7B target + order）
    op.execute("DROP TRIGGER IF EXISTS trg_gate_decisions_semantics ON trading.gate_decisions")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_gate_decision()")
    op.execute(_gate_guard_fn())
    op.execute(
        "CREATE TRIGGER trg_gate_decisions_semantics BEFORE INSERT ON trading.gate_decisions "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_gate_decision()"
    )
    # trade_decisions 生命周期 guard
    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_trade_decision() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE terminal text[] := ARRAY['ACTION','WAIT','ABSTAIN'];
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_trade_decision_immutable' USING ERRCODE='55000';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'CREATED' OR NEW.quote_bound_at IS NOT NULL
           OR NEW.decided_at IS NOT NULL OR NEW.output_hash IS NOT NULL THEN
            RAISE EXCEPTION 'v2_trade_decision_initial_state_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF OLD.decision_key IS DISTINCT FROM NEW.decision_key
       OR OLD.episode_id IS DISTINCT FROM NEW.episode_id
       OR OLD.forecast_submission_id IS DISTINCT FROM NEW.forecast_submission_id
       OR OLD.objective_contract_id IS DISTINCT FROM NEW.objective_contract_id
       OR OLD.strategy_version_id IS DISTINCT FROM NEW.strategy_version_id
       OR OLD.release_manifest_id IS DISTINCT FROM NEW.release_manifest_id
       OR OLD.execution_spec_version_id IS DISTINCT FROM NEW.execution_spec_version_id
       OR OLD.capital_permission_manifest_id IS DISTINCT FROM NEW.capital_permission_manifest_id
       OR OLD.experiment_variant IS DISTINCT FROM NEW.experiment_variant
       OR OLD.trigger_at IS DISTINCT FROM NEW.trigger_at
       OR OLD.input_hash IS DISTINCT FROM NEW.input_hash
       OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
        RAISE EXCEPTION 'v2_trade_decision_identity_immutable' USING ERRCODE='55000';
    END IF;
    -- terminal 后禁改
    IF OLD.status = ANY(terminal) AND NEW.status IS DISTINCT FROM OLD.status THEN
        RAISE EXCEPTION 'v2_trade_decision_terminal_immutable' USING ERRCODE='55000';
    END IF;
    -- 状态机
    IF OLD.status = 'CREATED' AND NEW.status = 'QUOTE_BOUND' AND NEW.quote_bound_at IS NOT NULL
       AND NEW.decided_at IS NULL THEN
        RETURN NEW;
    ELSIF OLD.status = 'QUOTE_BOUND' AND NEW.status = 'G7A' AND NEW.decided_at IS NULL THEN
        RETURN NEW;
    ELSIF OLD.status = 'G7A' AND NEW.status = 'G7B' AND NEW.decided_at IS NULL THEN
        RETURN NEW;
    ELSIF OLD.status = 'G7B' AND NEW.status = ANY(terminal)
          AND NEW.decided_at IS NOT NULL AND NEW.output_hash IS NOT NULL THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'v2_trade_decision_immutable' USING ERRCODE='55000';
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_trade_decisions_lifecycle "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.trade_decisions "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_trade_decision()"
    )
    # action_sets：ACTION 必须至少 1 leg，WAIT/ABSTAIN 无 leg（deferred 核验）
    op.execute(
        r"""
CREATE FUNCTION trading.v2_check_action_set() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    set_ref bigint;
    leg_count integer;
    set_disposition text;
BEGIN
    IF TG_TABLE_NAME = 'action_sets' THEN
        set_ref := NEW.id;
    ELSE
        set_ref := NEW.action_set_id;
    END IF;
    SELECT disposition INTO STRICT set_disposition
      FROM trading.action_sets WHERE id = set_ref;
    IF set_disposition = 'ACTION' THEN
        SELECT count(*) INTO leg_count FROM trading.action_set_legs WHERE action_set_id = set_ref;
        IF leg_count = 0 THEN
            RAISE EXCEPTION 'v2_action_set_action_requires_leg' USING ERRCODE='23514';
        END IF;
    ELSIF set_disposition IN ('WAIT','ABSTAIN') THEN
        IF EXISTS (SELECT 1 FROM trading.action_set_legs WHERE action_set_id = set_ref) THEN
            RAISE EXCEPTION 'v2_action_set_wait_abstain_no_leg' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    for table, events in (("action_sets", "INSERT"), ("action_set_legs", "INSERT OR UPDATE")):
        op.execute(
            f"CREATE CONSTRAINT TRIGGER trg_{table}_action_set_complete "
            f"AFTER {events} ON trading.{table} "
            "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
            "EXECUTE FUNCTION trading.v2_check_action_set()"
        )
    # economic_action_intents：PLANNED→COMMITTED|SUPERSEDED；terminal 禁改
    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_action_intent() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_action_intent_immutable' USING ERRCODE='55000';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'PLANNED' THEN
            RAISE EXCEPTION 'v2_action_intent_initial_state_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF OLD.intent_key IS DISTINCT FROM NEW.intent_key
       OR OLD.intent_hash IS DISTINCT FROM NEW.intent_hash
       OR OLD.trade_decision_id IS DISTINCT FROM NEW.trade_decision_id
       OR OLD.action_set_id IS DISTINCT FROM NEW.action_set_id
       OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
        RAISE EXCEPTION 'v2_action_intent_identity_immutable' USING ERRCODE='55000';
    END IF;
    IF OLD.status IN ('COMMITTED','SUPERSEDED') AND NEW.status IS DISTINCT FROM OLD.status THEN
        RAISE EXCEPTION 'v2_action_intent_terminal_immutable' USING ERRCODE='55000';
    END IF;
    IF OLD.status = 'PLANNED' AND NEW.status IN ('COMMITTED','SUPERSEDED') THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'v2_action_intent_immutable' USING ERRCODE='55000';
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_economic_action_intents_lifecycle "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.economic_action_intents "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_action_intent()"
    )


def _gate_guard_0021_fn() -> str:
    return r"""
CREATE FUNCTION trading.v2_guard_gate_decision() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    root_id bigint;
    screening_id bigint;
    opportunity_id bigint;
BEGIN
    IF NEW.gate IN ('G0','R0') THEN
        IF NOT EXISTS (SELECT 1 FROM trading.screening_episodes WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NEW.gate IN ('G1','G2') THEN
        IF NOT EXISTS (SELECT 1 FROM trading.decision_opportunities WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NOT EXISTS (SELECT 1 FROM trading.forecast_episodes WHERE id = NEW.target_id) THEN
        RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
    END IF;

    IF (NEW.gate = 'G0' AND NEW.result NOT IN ('PASS','PREDICTION_RESEARCH_ONLY'))
       OR (NEW.gate = 'R0' AND NEW.result NOT IN ('SELECT','DEFER','REJECT'))
       OR (NEW.gate IN ('G1','G2') AND NEW.result NOT IN ('PASS','FAIL'))
       OR (NEW.gate = 'R1' AND NEW.result NOT IN ('reject','shallow','standard','deep'))
       OR (NEW.gate = 'G4' AND NEW.result NOT IN ('PASS','FAIL'))
       OR (NEW.gate = 'G5A' AND NEW.result NOT IN ('PASS','ABSTAIN_EVIDENCE_INTEGRITY'))
       OR (NEW.gate = 'G5B' AND NEW.result NOT IN ('PASS','WIDEN_REQUIRED','ABSTAIN_EVIDENCE_INSUFFICIENT'))
       OR (NEW.gate = 'G6' AND NEW.result NOT IN ('PASS','FAIL')) THEN
        RAISE EXCEPTION 'v2_gate_result_invalid' USING ERRCODE='23514';
    END IF;
    IF NEW.result IN ('PREDICTION_RESEARCH_ONLY','DEFER','REJECT','FAIL',
                      'ABSTAIN_EVIDENCE_INTEGRITY','WIDEN_REQUIRED','ABSTAIN_EVIDENCE_INSUFFICIENT','reject')
       AND NEW.reason_code IS NULL THEN
        RAISE EXCEPTION 'v2_gate_failure_reason_required' USING ERRCODE='23514';
    END IF;

    IF NEW.gate = 'R0' AND NOT EXISTS (
        SELECT 1 FROM trading.gate_decisions gd
         WHERE gd.gate = 'G0' AND gd.target_kind = 'screening'
           AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
    ) THEN
        RAISE EXCEPTION 'v2_gate_order_g0_r0' USING ERRCODE='23514';
    ELSIF NEW.gate = 'G1' THEN
        SELECT COALESCE(o.parent_id, o.id) INTO STRICT root_id
          FROM trading.decision_opportunities o WHERE o.id = NEW.target_id;
        SELECT source_screening_episode_id INTO screening_id
          FROM trading.decision_opportunities WHERE id = root_id;
        IF screening_id IS NULL OR NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'R0' AND gd.target_kind = 'screening'
               AND gd.target_id = screening_id
               AND (gd.result = 'SELECT' OR EXISTS (
                    SELECT 1 FROM trading.screening_episodes se
                     WHERE se.id = screening_id AND se.audit_assigned))
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_r0_g1' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G2' THEN
        SELECT COALESCE(o.parent_id, o.id) INTO STRICT root_id
          FROM trading.decision_opportunities o WHERE o.id = NEW.target_id;
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
            JOIN trading.decision_opportunities prior ON prior.id = gd.target_id
             WHERE gd.gate = 'G1' AND gd.target_kind = 'opportunity' AND gd.result = 'PASS'
               AND COALESCE(prior.parent_id, prior.id) = root_id
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g1_g2' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'R1' THEN
        SELECT decision_opportunity_id INTO STRICT opportunity_id
          FROM trading.forecast_episodes WHERE id = NEW.target_id;
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G2' AND gd.target_kind = 'opportunity'
               AND gd.target_id = opportunity_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g2_r1' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G4' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'R1' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id
               AND gd.result IN ('shallow','standard','deep')
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_r1_g4' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G5A' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G4' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g4_g5a' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G5B' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G5A' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g5a_g5b' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G6' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G5B' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g5b_g6' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $v2_guard$
"""


def _drop_guards() -> None:
    op.execute(
        "DROP TRIGGER IF EXISTS trg_economic_action_intents_lifecycle "
        "ON trading.economic_action_intents"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_action_intent()")
    for table in ("action_set_legs", "action_sets"):
        op.execute(
            f"DROP TRIGGER IF EXISTS trg_{table}_action_set_complete ON trading.{table}"
        )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_check_action_set()")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_trade_decisions_lifecycle ON trading.trade_decisions"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_trade_decision()")
    # 恢复 0021 gate guard
    op.execute("DROP TRIGGER IF EXISTS trg_gate_decisions_semantics ON trading.gate_decisions")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_gate_decision()")
    op.execute(_gate_guard_0021_fn())
    op.execute(
        "CREATE TRIGGER trg_gate_decisions_semantics BEFORE INSERT ON trading.gate_decisions "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_gate_decision()"
    )
    for table in reversed(_DECISION_TABLES):
        if table.append_only:
            op.execute(
                f"DROP TRIGGER IF EXISTS trg_{table.name}_immutable "
                f"ON {TRADING_SCHEMA}.{table.name}"
            )


_DECISION_INDEXES = (
    "CREATE INDEX ix_trade_decisions_episode ON trading.trade_decisions (episode_id)",
    "CREATE INDEX ix_trade_decisions_submission ON trading.trade_decisions (forecast_submission_id)",
    "CREATE INDEX ix_action_candidates_decision ON trading.action_candidates (trade_decision_id)",
    "CREATE INDEX ix_resolution_cashflows_candidate ON trading.resolution_cashflows (action_candidate_id)",
    "CREATE INDEX ix_action_set_legs_set ON trading.action_set_legs (action_set_id)",
    "CREATE INDEX ix_economic_action_intents_action_set ON trading.economic_action_intents (action_set_id)",
)


def _create_indexes() -> None:
    for statement in _DECISION_INDEXES:
        op.execute(statement)


def _drop_indexes() -> None:
    for statement in _DECISION_INDEXES:
        index_name = statement.split(" ON ")[0].replace("CREATE INDEX ", "").strip()
        op.execute(f"DROP INDEX IF EXISTS {TRADING_SCHEMA}.{index_name}")


def upgrade() -> None:
    for table in _DECISION_TABLES:
        op.execute(table.create_sql)
    _create_indexes()
    _reinforce_existing()
    _create_guards()


def downgrade() -> None:
    _assert_downgrade_safe()
    _drop_guards()
    _unreinforce_existing()
    _drop_indexes()
    for table in reversed(_DECISION_TABLES):
        op.execute(f"DROP TABLE {TRADING_SCHEMA}.{table.name}")
