"""create p1b cognition

Revision ID: b1000020
Revises: b1000013
Create Date: 2026-08-11 12:00:00

v2_0020 —— Cognition facts & deterministic forecast（WP-02 Checkpoint A）：创建 11 张
forecast/evidence 表 + 对既有表的可逆强化。

- ``upgrade``：
  - 11 张新表（priors、evidence_coverage_policies、evidence_revisions、evidence_bundles、
    evidence_bundle_items、forecast_input_manifests、forecast_submissions、payout_projections、
    coherence_checks、forecast_challenges、forecast_leases）与 append-only guards。
  - ``forecast_episodes`` 强化：新增 cognition_status/prior_frozen_at/evidence_bundle_at/
    forecast_committed_at；status 允许 ``BLIND_COMMITTED``；替换 episode lifecycle guard
    允许 ``ROUTED→BLIND_COMMITTED`` 与 cognition 状态推进（G4/G5A/G6）。
  - ``gate_decisions`` / ``information_snapshots`` 强化：gate allowlist 增加
    ``G4/G5A/G5B/G6``（绑 episode）；替换 gate guard 增加认知 Gate 顺序与 result 校验。
  - ``v2_check_episode_spec_set`` 强化：BLIND_COMMITTED 也要求 R1 route 存在。
- ``downgrade``：逆序删 11 表 + guard；撤销 episode/gate/snapshot 强化并恢复 b1000013 原函数。
  未知对象 fail-closed（与 0012/0013 一致）。
"""
from dataclasses import dataclass
from typing import Sequence, Union

from alembic import op

TRADING_SCHEMA = "trading"

# revision identifiers, used by Alembic.
revision: str = "b1000020"
down_revision: Union[str, Sequence[str], None] = "b1000013"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# 认知 Gate allowlist（与 models/workflow.py GATE_NAMES 一致）
_GATES = ("G0", "R0", "G1", "G2", "R1", "G4", "G5A", "G5B", "G6")
_GATE_VALUES = ", ".join(f"'{g}'" for g in _GATES)
# cognition status（与 models/workflow.py COGNITION_STATUS 一致）
_COGNITION_STATUS = (
    "PENDING", "PRIOR_READY", "EVIDENCE_READY", "FORECAST_READY",
    "COMMITTED", "PRE_COMMIT_TERMINAL",
)
_COGNITION_VALUES = ", ".join(f"'{s}'" for s in _COGNITION_STATUS)


@dataclass(frozen=True)
class _FrozenTableSpec:
    name: str
    create_sql: str
    index_sql: tuple[str, ...] = ()
    append_only: bool = True


_COGNITION_TABLES = (
    _FrozenTableSpec(
        name='priors',
        create_sql='\nCREATE TABLE trading.priors (\n\tepisode_id BIGINT NOT NULL, \n\tversion_no INTEGER NOT NULL, \n\treference_class TEXT, \n\thazard_ref TEXT, \n\tapplicability JSONB NOT NULL, \n\tsample_rule JSONB NOT NULL, \n\twidth JSONB NOT NULL, \n\tfailure_conditions JSONB NOT NULL, \n\tmarket_blind_declaration BOOLEAN NOT NULL, \n\tcontent JSONB NOT NULL, \n\tcontent_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tstatus VARCHAR(32) DEFAULT \'draft\' NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_priors_episode_version UNIQUE (episode_id, version_no), \n\tCONSTRAINT ck_priors_version_positive CHECK (version_no > 0), \n\tCONSTRAINT ck_priors_content_object CHECK (jsonb_typeof(content) = \'object\'), \n\tCONSTRAINT ck_priors_hash_hex CHECK (content_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_priors_status_known CHECK (status IN (\'draft\',\'active\',\'superseded\')), \n\tCONSTRAINT ck_priors_market_blind_declared CHECK (market_blind_declaration), \n\tCONSTRAINT ck_priors_reference_or_hazard CHECK (reference_class IS NOT NULL OR hazard_ref IS NOT NULL), \n\tCONSTRAINT fk_priors_episode FOREIGN KEY(episode_id) REFERENCES trading.forecast_episodes (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_priors_episode ON trading.priors (episode_id)',),
    ),
    _FrozenTableSpec(
        name='evidence_coverage_policies',
        create_sql='\nCREATE TABLE trading.evidence_coverage_policies (\n\tcohort_id BIGINT NOT NULL, \n\tpolicy_version INTEGER NOT NULL, \n\tcontent JSONB NOT NULL, \n\tcontent_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tstatus VARCHAR(32) DEFAULT \'draft\' NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_evidence_coverage_policies_cohort_version UNIQUE (cohort_id, policy_version), \n\tCONSTRAINT ck_evidence_coverage_policies_version_positive CHECK (policy_version > 0), \n\tCONSTRAINT ck_evidence_coverage_policies_content_object CHECK (jsonb_typeof(content) = \'object\'), \n\tCONSTRAINT ck_evidence_coverage_policies_hash_hex CHECK (content_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_evidence_coverage_policies_status_known CHECK (status IN (\'draft\',\'active\',\'superseded\')), \n\tCONSTRAINT fk_evidence_coverage_policies_cohort FOREIGN KEY(cohort_id) REFERENCES trading.evaluation_cohorts (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_evidence_coverage_policies_cohort ON trading.evidence_coverage_policies (cohort_id)',),
    ),
    _FrozenTableSpec(
        name='evidence_revisions',
        create_sql='\nCREATE TABLE trading.evidence_revisions (\n\tepisode_id BIGINT NOT NULL, \n\trevision_key TEXT COLLATE "C" NOT NULL, \n\tkind VARCHAR(32) NOT NULL, \n\tevent_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tpublished_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tobserved_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tingested_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tsource TEXT NOT NULL, \n\tsource_type VARCHAR(64) NOT NULL, \n\tbranch VARCHAR(64) NOT NULL, \n\tprev_revision_id BIGINT, \n\traw_artifact_id BIGINT NOT NULL, \n\tcontent JSONB NOT NULL, \n\tcontent_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\ttaint_status VARCHAR(32) DEFAULT \'none\' NOT NULL, \n\tmarket_conditioned_discovery BOOLEAN DEFAULT false NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_evidence_revisions_episode_key UNIQUE (episode_id, revision_key), \n\tCONSTRAINT uq_evidence_revisions_episode_hash UNIQUE (episode_id, content_hash), \n\tCONSTRAINT ck_evidence_revisions_key_nonempty CHECK (revision_key <> \'\'), \n\tCONSTRAINT ck_evidence_revisions_kind_known CHECK (kind IN (\'observation\',\'source_claim\',\'inference\',\'conflict\',\'missing\')), \n\tCONSTRAINT ck_evidence_revisions_taint_known CHECK (taint_status IN (\'none\',\'market\',\'odds\',\'crowd\',\'label\',\'future_fact\',\'quarantined\')), \n\tCONSTRAINT ck_evidence_revisions_publish_le_observe CHECK (published_at <= observed_at), \n\tCONSTRAINT ck_evidence_revisions_observe_le_ingest CHECK (observed_at <= ingested_at), \n\tCONSTRAINT ck_evidence_revisions_hash_hex CHECK (content_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_evidence_revisions_content_object CHECK (jsonb_typeof(content) = \'object\'), \n\tCONSTRAINT ck_evidence_revisions_taint_conditioned_pair CHECK (market_conditioned_discovery = false OR taint_status <> \'none\'), \n\tCONSTRAINT fk_evidence_revisions_episode FOREIGN KEY(episode_id) REFERENCES trading.forecast_episodes (id), \n\tCONSTRAINT fk_evidence_revisions_prev FOREIGN KEY(prev_revision_id) REFERENCES trading.evidence_revisions (id), \n\tCONSTRAINT fk_evidence_revisions_raw_artifact FOREIGN KEY(raw_artifact_id) REFERENCES trading.artifact_objects (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_evidence_revisions_episode ON trading.evidence_revisions (episode_id)',),
    ),
    _FrozenTableSpec(
        name='evidence_bundles',
        create_sql='\nCREATE TABLE trading.evidence_bundles (\n\tepisode_id BIGINT NOT NULL, \n\tbundle_key TEXT COLLATE "C" NOT NULL, \n\tinformation_cutoff_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tbundle_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tstatus VARCHAR(32) DEFAULT \'draft\' NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_evidence_bundles_episode_key UNIQUE (episode_id, bundle_key), \n\tCONSTRAINT uq_evidence_bundles_hash UNIQUE (bundle_hash), \n\tCONSTRAINT ck_evidence_bundles_hash_hex CHECK (bundle_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_evidence_bundles_status_known CHECK (status IN (\'draft\',\'frozen\')), \n\tCONSTRAINT fk_evidence_bundles_episode FOREIGN KEY(episode_id) REFERENCES trading.forecast_episodes (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_evidence_bundles_episode ON trading.evidence_bundles (episode_id)',),
    ),
    _FrozenTableSpec(
        name='evidence_bundle_items',
        create_sql='\nCREATE TABLE trading.evidence_bundle_items (\n\tbundle_id BIGINT NOT NULL, \n\trevision_id BIGINT NOT NULL, \n\titem_no INTEGER NOT NULL, \n\teligible BOOLEAN DEFAULT true NOT NULL, \n\teligibility_reason VARCHAR(128), \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_evidence_bundle_items_bundle_revision UNIQUE (bundle_id, revision_id), \n\tCONSTRAINT uq_evidence_bundle_items_bundle_no UNIQUE (bundle_id, item_no), \n\tCONSTRAINT ck_evidence_bundle_items_no_nonneg CHECK (item_no >= 0), \n\tCONSTRAINT fk_evidence_bundle_items_bundle FOREIGN KEY(bundle_id) REFERENCES trading.evidence_bundles (id), \n\tCONSTRAINT fk_evidence_bundle_items_revision FOREIGN KEY(revision_id) REFERENCES trading.evidence_revisions (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_evidence_bundle_items_bundle ON trading.evidence_bundle_items (bundle_id)',),
    ),
    _FrozenTableSpec(
        name='forecast_input_manifests',
        create_sql='\nCREATE TABLE trading.forecast_input_manifests (\n\tepisode_id BIGINT NOT NULL, \n\tmanifest_key TEXT COLLATE "C" NOT NULL, \n\tmanifest_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tevidence_bundle_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tcontract_spec_set_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tworld_schema_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tprior_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\ttaxonomy_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tmodel_binding_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tprompt_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tcode_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tcontent JSONB NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_forecast_input_manifests_episode_key UNIQUE (episode_id, manifest_key), \n\tCONSTRAINT uq_forecast_input_manifests_hash UNIQUE (manifest_hash), \n\tCONSTRAINT ck_forecast_input_manifests_hash_hex CHECK (manifest_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_forecast_input_manifests_content_object CHECK (jsonb_typeof(content) = \'object\'), \n\tCONSTRAINT fk_forecast_input_manifests_episode FOREIGN KEY(episode_id) REFERENCES trading.forecast_episodes (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_forecast_input_manifests_episode ON trading.forecast_input_manifests (episode_id)',),
    ),
    _FrozenTableSpec(
        name='forecast_submissions',
        create_sql='\nCREATE TABLE trading.forecast_submissions (\n\tepisode_id BIGINT NOT NULL, \n\tsubmission_key TEXT COLLATE "C" NOT NULL, \n\tstatus VARCHAR(32) DEFAULT \'DRAFT\' NOT NULL, \n\tQ JSONB NOT NULL, \n\tU JSONB NOT NULL, \n\tforecast_input_manifest_id BIGINT NOT NULL, \n\tcontract_schema_prior_evidence_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\talgorithm_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tcommitted_at TIMESTAMP WITH TIME ZONE, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_forecast_submissions_episode_key UNIQUE (episode_id, submission_key), \n\tCONSTRAINT ck_forecast_submissions_status_known CHECK (status IN (\'DRAFT\',\'BLIND_COMMITTED\')), \n\tCONSTRAINT ck_forecast_submissions_q_object CHECK (jsonb_typeof(Q) = \'object\'), \n\tCONSTRAINT ck_forecast_submissions_u_array CHECK (jsonb_typeof(U) = \'array\'), \n\tCONSTRAINT ck_forecast_submissions_u_nonempty CHECK (jsonb_array_length(U) > 0), \n\tCONSTRAINT ck_forecast_submissions_commit_pair CHECK (committed_at IS NOT NULL = (status = \'BLIND_COMMITTED\')), \n\tCONSTRAINT fk_forecast_submissions_episode FOREIGN KEY(episode_id) REFERENCES trading.forecast_episodes (id), \n\tCONSTRAINT fk_forecast_submissions_manifest FOREIGN KEY(forecast_input_manifest_id) REFERENCES trading.forecast_input_manifests (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_forecast_submissions_episode ON trading.forecast_submissions (episode_id)',),
        append_only=False,
    ),
    _FrozenTableSpec(
        name='payout_projections',
        create_sql='\nCREATE TABLE trading.payout_projections (\n\tsubmission_id BIGINT NOT NULL, \n\tcontract_spec_id BIGINT NOT NULL, \n\tpm_token_id BIGINT NOT NULL, \n\tmu JSONB NOT NULL, \n\tv NUMERIC(38, 0) NOT NULL, \n\tu_lower NUMERIC(38, 0) NOT NULL, \n\tu_upper NUMERIC(38, 0) NOT NULL, \n\tp_blind NUMERIC(38, 0), \n\talgorithm_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\th_c_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tg_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_payout_projections_submission_spec_token UNIQUE (submission_id, contract_spec_id, pm_token_id), \n\tCONSTRAINT ck_payout_projections_mu_object CHECK (jsonb_typeof(mu) = \'object\'), \n\tCONSTRAINT ck_payout_projections_v_range CHECK (v >= 0 AND v <= 1), \n\tCONSTRAINT ck_payout_projections_lower_range CHECK (u_lower >= 0 AND u_lower <= 1), \n\tCONSTRAINT ck_payout_projections_upper_range CHECK (u_upper >= 0 AND u_upper <= 1), \n\tCONSTRAINT ck_payout_projections_bounds_order CHECK (u_lower <= v AND v <= u_upper), \n\tCONSTRAINT ck_payout_projections_pblind_range CHECK (p_blind IS NULL OR (p_blind >= 0 AND p_blind <= 1)), \n\tCONSTRAINT ck_payout_projections_alg_hash_hex CHECK (algorithm_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_payout_projections_g_hash_hex CHECK (g_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT fk_payout_projections_submission FOREIGN KEY(submission_id) REFERENCES trading.forecast_submissions (id), \n\tCONSTRAINT fk_payout_projections_spec FOREIGN KEY(contract_spec_id) REFERENCES trading.contract_specs (id), \n\tCONSTRAINT fk_payout_projections_token FOREIGN KEY(pm_token_id) REFERENCES trading.pm_tokens (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_payout_projections_submission ON trading.payout_projections (submission_id)',),
    ),
    _FrozenTableSpec(
        name='coherence_checks',
        create_sql='\nCREATE TABLE trading.coherence_checks (\n\tsubmission_id BIGINT NOT NULL, \n\tcheck_name VARCHAR(64) NOT NULL, \n\tpassed BOOLEAN NOT NULL, \n\tseverity VARCHAR(16) NOT NULL, \n\treason_code VARCHAR(128), \n\tdetails_artifact_hash VARCHAR(64) COLLATE "C", \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_coherence_checks_submission_check UNIQUE (submission_id, check_name), \n\tCONSTRAINT fk_coherence_checks_submission FOREIGN KEY(submission_id) REFERENCES trading.forecast_submissions (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_coherence_checks_submission ON trading.coherence_checks (submission_id)',),
    ),
    _FrozenTableSpec(
        name='forecast_challenges',
        create_sql='\nCREATE TABLE trading.forecast_challenges (\n\tepisode_id BIGINT NOT NULL, \n\tchallenge_key TEXT COLLATE "C" NOT NULL, \n\tchallenger_role VARCHAR(64) NOT NULL, \n\tstatus VARCHAR(32) DEFAULT \'planned\' NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_forecast_challenges_episode_key UNIQUE (episode_id, challenge_key), \n\tCONSTRAINT ck_forecast_challenges_status_known CHECK (status IN (\'planned\',\'running\',\'accepted\',\'rejected\',\'superseded\')), \n\tCONSTRAINT fk_forecast_challenges_episode FOREIGN KEY(episode_id) REFERENCES trading.forecast_episodes (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_forecast_challenges_episode ON trading.forecast_challenges (episode_id)',),
    ),
    _FrozenTableSpec(
        name='forecast_leases',
        create_sql='\nCREATE TABLE trading.forecast_leases (\n\tsubmission_id BIGINT NOT NULL, \n\tvalid_until TIMESTAMP WITH TIME ZONE NOT NULL, \n\tinvalidation_conditions JSONB NOT NULL, \n\tevidence_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tschema_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tspec_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_forecast_leases_submission UNIQUE (submission_id), \n\tCONSTRAINT ck_forecast_leases_conditions_object CHECK (jsonb_typeof(invalidation_conditions) = \'object\'), \n\tCONSTRAINT ck_forecast_leases_evidence_hash_hex CHECK (evidence_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_forecast_leases_schema_hash_hex CHECK (schema_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_forecast_leases_spec_hash_hex CHECK (spec_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT fk_forecast_leases_submission FOREIGN KEY(submission_id) REFERENCES trading.forecast_submissions (id)\n)\n\n',
    ),
)

# 全部在 b1000020 之前的 trading 关系（downgrade preflight allowlist）
_PRE_0020_RELATIONS = (
    "artifact_objects", "artifact_lineage_edges", "archive_manifests",
    "retention_manifests", "runtime_config_versions", "strategy_objective_contracts",
    "strategy_versions", "execution_spec_versions", "capital_permission_manifests",
    "model_role_bindings", "release_manifests", "policy_type_scopes", "policy_freezes",
    "secret_vault_entries", "secret_vault_versions", "secret_access_events",
    "idempotency_claims", "transactional_outbox", "outbox_delivery_history",
    "job_completions", "pm_universe_frames", "pm_universe_frame_pages", "pm_events",
    "pm_markets", "pm_market_versions", "pm_tokens", "pm_token_versions",
    "pm_market_lifecycle_events", "pm_market_current", "pm_connection_epochs",
    "pm_source_event_batches", "pm_source_event_index", "pm_book_checkpoints",
    "pm_book_levels", "pm_book_current", "pm_quote_bindings", "contract_snapshots",
    "contract_specs", "payout_functions", "forecast_components", "world_schema_versions",
    "forecast_component_versions", "forecast_component_contract_specs",
    "portfolio_dependency_edges", "evaluation_cohorts", "universe_memberships",
    "screening_episodes", "audit_samples", "decision_opportunities",
    "decision_opportunity_markets", "episode_memberships", "forecast_episodes",
    "episode_contract_specs", "information_snapshots", "information_snapshot_items",
    "gate_decisions",
)

def _assert_downgrade_safe() -> None:
    """拒绝在存在未知下游对象时直接 downgrade（与 0012/0013 一致）。"""
    allowed = ", ".join(
        f"'{name}'" for name in (*_PRE_0020_RELATIONS, *(t.name for t in _COGNITION_TABLES))
    )
    op.execute(
        f"""
DO $v2_wp02_preflight$
DECLARE unknown_objects text;
BEGIN
    SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
      INTO unknown_objects
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'trading'
       AND c.relkind IN ('r','p','v','m','f')
       AND c.relname NOT IN ({allowed})
       AND NOT EXISTS (
           SELECT 1 FROM pg_inherits i
           JOIN pg_class p ON p.oid = i.inhparent
           JOIN pg_namespace pn ON pn.oid = p.relnamespace
           WHERE i.inhrelid = c.oid AND pn.nspname = 'trading'
             AND ((p.relname = 'outbox_delivery_history'
                   AND c.relname ~ '^outbox_delivery_history_[0-9]{{6}}$')
               OR (p.relname IN ('pm_source_event_batches','pm_source_event_index',
                                  'pm_book_checkpoints','pm_book_levels')
                   AND c.relname ~ ('^' || p.relname || '_[0-9]{{8}}$')))
       );
    IF unknown_objects IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp02_unknown_object:%', unknown_objects USING ERRCODE='55000';
    END IF;
END $v2_wp02_preflight$
"""
    )


def _create_table_indexes(table: _FrozenTableSpec) -> None:
    for statement in table.index_sql:
        op.execute(statement)


def _reinforce_episode_and_gates() -> None:
    """强化 forecast_episodes 与 gate_decisions/information_snapshots。"""
    # ---- forecast_episodes ----
    op.execute("ALTER TABLE trading.forecast_episodes ADD COLUMN cognition_status VARCHAR(32) DEFAULT 'PENDING' NOT NULL")
    op.execute("ALTER TABLE trading.forecast_episodes ADD COLUMN prior_frozen_at TIMESTAMP WITH TIME ZONE")
    op.execute("ALTER TABLE trading.forecast_episodes ADD COLUMN evidence_bundle_at TIMESTAMP WITH TIME ZONE")
    op.execute("ALTER TABLE trading.forecast_episodes ADD COLUMN forecast_committed_at TIMESTAMP WITH TIME ZONE")
    op.execute(
        "ALTER TABLE trading.forecast_episodes "
        "ADD CONSTRAINT ck_forecast_episodes_cognition_status_known "
        f"CHECK (cognition_status IN ({_COGNITION_VALUES}))"
    )
    op.execute(
        "ALTER TABLE trading.forecast_episodes "
        "DROP CONSTRAINT IF EXISTS ck_forecast_episodes_status_known"
    )
    op.execute(
        "ALTER TABLE trading.forecast_episodes "
        "ADD CONSTRAINT ck_forecast_episodes_status_known "
        "CHECK (status IN ('DRAFT','ROUTED','BLIND_COMMITTED','PRE_COMMIT_TERMINAL'))"
    )

    # ---- gate_decisions / information_snapshots ----
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "DROP CONSTRAINT IF EXISTS ck_gate_decisions_gate_known"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        f"ADD CONSTRAINT ck_gate_decisions_gate_known CHECK (gate IN ({_GATE_VALUES}))"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "DROP CONSTRAINT IF EXISTS ck_gate_decisions_gate_target_pair"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "ADD CONSTRAINT ck_gate_decisions_gate_target_pair CHECK ("
        "(gate IN ('G0','R0') AND target_kind = 'screening') OR "
        "(gate IN ('G1','G2') AND target_kind = 'opportunity') OR "
        "(gate IN ('R1','G4','G5A','G5B','G6') AND target_kind = 'episode'))"
    )
    op.execute(
        "ALTER TABLE trading.information_snapshots "
        "DROP CONSTRAINT IF EXISTS ck_information_snapshots_gate_known"
    )
    op.execute(
        "ALTER TABLE trading.information_snapshots "
        f"ADD CONSTRAINT ck_information_snapshots_gate_known CHECK (gate IN ({_GATE_VALUES}))"
    )


def _unreinforce_episode_and_gates() -> None:
    """撤销强化并恢复 b1000013 原 CHECK。"""
    op.execute(
        "ALTER TABLE trading.forecast_episodes "
        "DROP CONSTRAINT IF EXISTS ck_forecast_episodes_status_known"
    )
    op.execute(
        "ALTER TABLE trading.forecast_episodes "
        "ADD CONSTRAINT ck_forecast_episodes_status_known "
        "CHECK (status IN ('DRAFT','ROUTED','PRE_COMMIT_TERMINAL'))"
    )
    op.execute(
        "ALTER TABLE trading.forecast_episodes "
        "DROP CONSTRAINT IF EXISTS ck_forecast_episodes_cognition_status_known"
    )
    op.execute("ALTER TABLE trading.forecast_episodes DROP COLUMN IF EXISTS forecast_committed_at")
    op.execute("ALTER TABLE trading.forecast_episodes DROP COLUMN IF EXISTS evidence_bundle_at")
    op.execute("ALTER TABLE trading.forecast_episodes DROP COLUMN IF EXISTS prior_frozen_at")
    op.execute("ALTER TABLE trading.forecast_episodes DROP COLUMN IF EXISTS cognition_status")
    op.execute(
        "ALTER TABLE trading.information_snapshots "
        "DROP CONSTRAINT IF EXISTS ck_information_snapshots_gate_known"
    )
    op.execute(
        "ALTER TABLE trading.information_snapshots "
        "ADD CONSTRAINT ck_information_snapshots_gate_known "
        "CHECK (gate IN ('G0','R0','G1','G2','R1'))"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "DROP CONSTRAINT IF EXISTS ck_gate_decisions_gate_target_pair"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "ADD CONSTRAINT ck_gate_decisions_gate_target_pair CHECK ("
        "(gate IN ('G0','R0') AND target_kind = 'screening') OR "
        "(gate IN ('G1','G2') AND target_kind = 'opportunity') OR "
        "(gate = 'R1' AND target_kind = 'episode'))"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "DROP CONSTRAINT IF EXISTS ck_gate_decisions_gate_known"
    )
    op.execute(
        "ALTER TABLE trading.gate_decisions "
        "ADD CONSTRAINT ck_gate_decisions_gate_known "
        "CHECK (gate IN ('G0','R0','G1','G2','R1'))"
    )


def _episode_guard_fn() -> str:
    return r"""
CREATE FUNCTION trading.v2_guard_episode() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    opportunity_row record;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_episode_immutable' USING ERRCODE='55000';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'DRAFT' OR NEW.drop_reason IS NOT NULL
           OR NEW.cognition_status <> 'PENDING'
           OR NEW.prior_frozen_at IS NOT NULL OR NEW.evidence_bundle_at IS NOT NULL
           OR NEW.forecast_committed_at IS NOT NULL THEN
            RAISE EXCEPTION 'v2_episode_initial_state_invalid' USING ERRCODE='23514';
        END IF;
        SELECT objective_contract_id, strategy_version_id, status
          INTO STRICT opportunity_row
          FROM trading.decision_opportunities WHERE id = NEW.decision_opportunity_id;
        IF opportunity_row.objective_contract_id <> NEW.objective_contract_id
           OR opportunity_row.strategy_version_id <> NEW.strategy_version_id
           OR opportunity_row.status <> 'OPEN' THEN
            RAISE EXCEPTION 'v2_episode_opportunity_identity_mismatch' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF OLD.episode_key IS DISTINCT FROM NEW.episode_key
       OR OLD.decision_opportunity_id IS DISTINCT FROM NEW.decision_opportunity_id
       OR OLD.component_version_id IS DISTINCT FROM NEW.component_version_id
       OR OLD.strategy_version_id IS DISTINCT FROM NEW.strategy_version_id
       OR OLD.objective_contract_id IS DISTINCT FROM NEW.objective_contract_id
       OR OLD.trigger IS DISTINCT FROM NEW.trigger
       OR OLD.cutoff_at IS DISTINCT FROM NEW.cutoff_at
       OR OLD.horizon IS DISTINCT FROM NEW.horizon
       OR OLD.experiment_variant IS DISTINCT FROM NEW.experiment_variant
       OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
        RAISE EXCEPTION 'v2_episode_immutable' USING ERRCODE='55000';
    END IF;

    -- DRAFT → ROUTED / PRE_COMMIT_TERMINAL（R1；b1000013 语义）
    IF OLD.status = 'DRAFT' THEN
        IF NEW.status = 'ROUTED' AND NEW.drop_reason IS NULL
           AND NEW.cognition_status = 'PENDING'
           AND NEW.prior_frozen_at IS NULL AND NEW.evidence_bundle_at IS NULL
           AND NEW.forecast_committed_at IS NULL THEN
            RETURN NEW;
        END IF;
        IF NEW.status = 'PRE_COMMIT_TERMINAL' AND NEW.drop_reason IS NOT NULL
           AND NEW.cognition_status = 'PENDING'
           AND NEW.prior_frozen_at IS NULL AND NEW.evidence_bundle_at IS NULL
           AND NEW.forecast_committed_at IS NULL THEN
            RETURN NEW;
        END IF;
        RAISE EXCEPTION 'v2_episode_immutable' USING ERRCODE='55000';
    END IF;

    -- ROUTED：cognition 推进 或 终态
    IF OLD.status = 'ROUTED' THEN
        -- PENDING→PRIOR_READY（G4）
        IF NEW.status = 'ROUTED' AND NEW.cognition_status = 'PRIOR_READY'
           AND OLD.cognition_status = 'PENDING'
           AND NEW.prior_frozen_at IS NOT NULL
           AND NEW.drop_reason IS NULL
           AND NEW.evidence_bundle_at IS NULL AND NEW.forecast_committed_at IS NULL THEN
            RETURN NEW;
        END IF;
        -- PRIOR_READY→EVIDENCE_READY（G5A/G5B）
        IF NEW.status = 'ROUTED' AND NEW.cognition_status = 'EVIDENCE_READY'
           AND OLD.cognition_status = 'PRIOR_READY'
           AND NEW.evidence_bundle_at IS NOT NULL
           AND NEW.drop_reason IS NULL
           AND NEW.forecast_committed_at IS NULL THEN
            RETURN NEW;
        END IF;
        -- EVIDENCE_READY→BLIND_COMMITTED（G6 原子封账）
        IF NEW.status = 'BLIND_COMMITTED' AND NEW.cognition_status = 'COMMITTED'
           AND OLD.cognition_status = 'EVIDENCE_READY'
           AND NEW.drop_reason IS NULL
           AND NEW.prior_frozen_at IS NOT NULL AND NEW.evidence_bundle_at IS NOT NULL
           AND NEW.forecast_committed_at IS NOT NULL THEN
            RETURN NEW;
        END IF;
        -- ROUTED→PRE_COMMIT_TERMINAL（G6 fail）
        IF NEW.status = 'PRE_COMMIT_TERMINAL' AND NEW.drop_reason IS NOT NULL THEN
            RETURN NEW;
        END IF;
        RAISE EXCEPTION 'v2_episode_immutable' USING ERRCODE='55000';
    END IF;
    RAISE EXCEPTION 'v2_episode_immutable' USING ERRCODE='55000';
END $v2_guard$
"""


def _episode_spec_fn() -> str:
    return r"""
CREATE FUNCTION trading.v2_check_episode_spec_set() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    episode_ref bigint;
    n integer;
    episode_status text;
    opportunity_ref bigint;
    component_status text;
    episode_objective bigint;
    episode_strategy bigint;
    opportunity_objective bigint;
    opportunity_strategy bigint;
    route text;
BEGIN
    IF TG_TABLE_NAME = 'forecast_episodes' THEN
        episode_ref := NEW.id;
    ELSE
        episode_ref := NEW.episode_id;
    END IF;
    SELECT fe.status, fe.decision_opportunity_id, cv.status,
           fe.objective_contract_id, fe.strategy_version_id,
           o.objective_contract_id, o.strategy_version_id
      INTO STRICT episode_status, opportunity_ref, component_status,
                  episode_objective, episode_strategy,
                  opportunity_objective, opportunity_strategy
      FROM trading.forecast_episodes fe
      JOIN trading.forecast_component_versions cv ON cv.id = fe.component_version_id
      JOIN trading.decision_opportunities o ON o.id = fe.decision_opportunity_id
     WHERE fe.id = episode_ref;
    IF component_status <> 'active' OR episode_objective <> opportunity_objective
       OR episode_strategy <> opportunity_strategy THEN
        RAISE EXCEPTION 'v2_episode_identity_or_component_invalid' USING ERRCODE='23514';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM trading.gate_decisions gd
         WHERE gd.gate = 'G2' AND gd.target_kind = 'opportunity'
           AND gd.target_id = opportunity_ref AND gd.result = 'PASS'
    ) THEN
        RAISE EXCEPTION 'v2_episode_requires_g2_pass' USING ERRCODE='23514';
    END IF;
    SELECT count(*) INTO n FROM (
        SELECT ecs.contract_spec_id FROM trading.episode_contract_specs ecs
         WHERE ecs.episode_id = episode_ref
        EXCEPT
        SELECT fcs.contract_spec_id
          FROM trading.forecast_episodes fe
          JOIN trading.forecast_component_contract_specs fcs
            ON fcs.component_version_id = fe.component_version_id
         WHERE fe.id = episode_ref
    ) extra;
    IF n > 0 THEN RAISE EXCEPTION 'v2_episode_spec_extra' USING ERRCODE='23514'; END IF;
    SELECT count(*) INTO n FROM (
        SELECT fcs.contract_spec_id
          FROM trading.forecast_episodes fe
          JOIN trading.forecast_component_contract_specs fcs
            ON fcs.component_version_id = fe.component_version_id
         WHERE fe.id = episode_ref
        EXCEPT
        SELECT ecs.contract_spec_id FROM trading.episode_contract_specs ecs
         WHERE ecs.episode_id = episode_ref
    ) missing;
    IF n > 0 THEN RAISE EXCEPTION 'v2_episode_spec_missing' USING ERRCODE='23514'; END IF;
    -- BLIND_COMMITTED（WP-02）同样要求 R1 route 已存在。
    IF episode_status IN ('ROUTED','BLIND_COMMITTED','PRE_COMMIT_TERMINAL') THEN
        SELECT count(*), min(route_channel) INTO n, route
          FROM trading.episode_memberships WHERE episode_id = episode_ref;
        IF n <> 1 OR NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'R1' AND gd.target_kind = 'episode'
               AND gd.target_id = episode_ref AND gd.result = route
        ) THEN
            RAISE EXCEPTION 'v2_episode_r1_route_missing' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $v2_guard$
"""


def _gate_guard_fn() -> str:
    return r"""
CREATE FUNCTION trading.v2_guard_gate_decision() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    root_id bigint;
    screening_id bigint;
    opportunity_id bigint;
BEGIN
    IF NEW.gate IN ('G0','R0') THEN
        IF NOT EXISTS (SELECT 1 FROM trading.screening_episodes WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NEW.gate IN ('G1','G2') THEN
        IF NOT EXISTS (SELECT 1 FROM trading.decision_opportunities WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NOT EXISTS (SELECT 1 FROM trading.forecast_episodes WHERE id = NEW.target_id) THEN
        RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
    END IF;

    IF (NEW.gate = 'G0' AND NEW.result NOT IN ('PASS','PREDICTION_RESEARCH_ONLY'))
       OR (NEW.gate = 'R0' AND NEW.result NOT IN ('SELECT','DEFER','REJECT'))
       OR (NEW.gate IN ('G1','G2') AND NEW.result NOT IN ('PASS','FAIL'))
       OR (NEW.gate = 'R1' AND NEW.result NOT IN ('reject','shallow','standard','deep'))
       OR (NEW.gate = 'G4' AND NEW.result NOT IN ('PASS','FAIL'))
       OR (NEW.gate = 'G5A' AND NEW.result NOT IN ('PASS','ABSTAIN_EVIDENCE_INTEGRITY'))
       OR (NEW.gate = 'G5B' AND NEW.result NOT IN ('PASS','WIDEN_REQUIRED','ABSTAIN_EVIDENCE_INSUFFICIENT'))
       OR (NEW.gate = 'G6' AND NEW.result NOT IN ('PASS','FAIL')) THEN
        RAISE EXCEPTION 'v2_gate_result_invalid' USING ERRCODE='23514';
    END IF;
    IF NEW.result IN ('PREDICTION_RESEARCH_ONLY','DEFER','REJECT','FAIL',
                      'ABSTAIN_EVIDENCE_INTEGRITY','WIDEN_REQUIRED','ABSTAIN_EVIDENCE_INSUFFICIENT','reject')
       AND NEW.reason_code IS NULL THEN
        RAISE EXCEPTION 'v2_gate_failure_reason_required' USING ERRCODE='23514';
    END IF;

    IF NEW.gate = 'R0' AND NOT EXISTS (
        SELECT 1 FROM trading.gate_decisions gd
         WHERE gd.gate = 'G0' AND gd.target_kind = 'screening'
           AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
    ) THEN
        RAISE EXCEPTION 'v2_gate_order_g0_r0' USING ERRCODE='23514';
    ELSIF NEW.gate = 'G1' THEN
        SELECT COALESCE(o.parent_id, o.id) INTO STRICT root_id
          FROM trading.decision_opportunities o WHERE o.id = NEW.target_id;
        SELECT source_screening_episode_id INTO screening_id
          FROM trading.decision_opportunities WHERE id = root_id;
        IF screening_id IS NULL OR NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'R0' AND gd.target_kind = 'screening'
               AND gd.target_id = screening_id
               AND (gd.result = 'SELECT' OR EXISTS (
                    SELECT 1 FROM trading.screening_episodes se
                     WHERE se.id = screening_id AND se.audit_assigned))
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_r0_g1' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G2' THEN
        SELECT COALESCE(o.parent_id, o.id) INTO STRICT root_id
          FROM trading.decision_opportunities o WHERE o.id = NEW.target_id;
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
            JOIN trading.decision_opportunities prior ON prior.id = gd.target_id
             WHERE gd.gate = 'G1' AND gd.target_kind = 'opportunity' AND gd.result = 'PASS'
               AND COALESCE(prior.parent_id, prior.id) = root_id
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g1_g2' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'R1' THEN
        SELECT decision_opportunity_id INTO STRICT opportunity_id
          FROM trading.forecast_episodes WHERE id = NEW.target_id;
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G2' AND gd.target_kind = 'opportunity'
               AND gd.target_id = opportunity_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g2_r1' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G4' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'R1' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id
               AND gd.result IN ('shallow','standard','deep')
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_r1_g4' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G5A' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G4' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g4_g5a' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G5B' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G5A' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g5a_g5b' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G6' THEN
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G5B' AND gd.target_kind = 'episode'
               AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g5b_g6' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $v2_guard$
"""


def _create_guards() -> None:
    for table in _COGNITION_TABLES:
        if table.append_only:
            op.execute(
                f"CREATE TRIGGER trg_{table.name}_immutable "
                f"BEFORE UPDATE OR DELETE ON {TRADING_SCHEMA}.{table.name} "
                "FOR EACH ROW EXECUTE FUNCTION trading.v2_reject_immutable_row()"
            )

    # 替换 b1000013 的三个 guard 函数（episode lifecycle / spec-set / gate）
    op.execute("DROP TRIGGER IF EXISTS trg_forecast_episodes_lifecycle ON trading.forecast_episodes")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_episode()")
    op.execute(_episode_guard_fn())
    op.execute(
        "CREATE TRIGGER trg_forecast_episodes_lifecycle "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.forecast_episodes "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_episode()"
    )

    op.execute("DROP TRIGGER IF EXISTS trg_gate_decisions_semantics ON trading.gate_decisions")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_gate_decision()")
    op.execute(_gate_guard_fn())
    op.execute(
        "CREATE TRIGGER trg_gate_decisions_semantics BEFORE INSERT ON trading.gate_decisions "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_gate_decision()"
    )

    for table in ("episode_memberships", "episode_contract_specs", "forecast_episodes"):
        op.execute(
            f"DROP TRIGGER IF EXISTS trg_{table}_episode_complete ON trading.{table}"
        )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_check_episode_spec_set()")
    op.execute(_episode_spec_fn())
    for table, events in (
        ("forecast_episodes", "INSERT OR UPDATE"),
        ("episode_contract_specs", "INSERT OR UPDATE"),
        ("episode_memberships", "INSERT OR UPDATE"),
    ):
        op.execute(
            f"CREATE CONSTRAINT TRIGGER trg_{table}_episode_complete "
            f"AFTER {events} ON trading.{table} "
            "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
            "EXECUTE FUNCTION trading.v2_check_episode_spec_set()"
        )

    # forecast_submissions：DRAFT→BLIND_COMMITTED 唯一合法 UPDATE（原子不可变封账）
    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_submission() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_submission_immutable' USING ERRCODE='55000';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'DRAFT' OR NEW.committed_at IS NOT NULL THEN
            RAISE EXCEPTION 'v2_submission_initial_state_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF OLD.episode_id IS DISTINCT FROM NEW.episode_id
       OR OLD.submission_key IS DISTINCT FROM NEW.submission_key
       OR OLD.Q IS DISTINCT FROM NEW.Q
       OR OLD.U IS DISTINCT FROM NEW.U
       OR OLD.forecast_input_manifest_id IS DISTINCT FROM NEW.forecast_input_manifest_id
       OR OLD.contract_schema_prior_evidence_hash IS DISTINCT FROM NEW.contract_schema_prior_evidence_hash
       OR OLD.algorithm_hash IS DISTINCT FROM NEW.algorithm_hash
       OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
        RAISE EXCEPTION 'v2_submission_immutable' USING ERRCODE='55000';
    END IF;
    IF NEW.status = 'BLIND_COMMITTED' AND OLD.status = 'DRAFT'
       AND NEW.committed_at IS NOT NULL THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'v2_submission_immutable' USING ERRCODE='55000';
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_forecast_submissions_lifecycle "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.forecast_submissions "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_submission()"
    )


def _drop_guards() -> None:
    op.execute(
        "DROP TRIGGER IF EXISTS trg_forecast_submissions_lifecycle "
        "ON trading.forecast_submissions"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_submission()")
    for table in ("episode_memberships", "episode_contract_specs", "forecast_episodes"):
        op.execute(
            f"DROP TRIGGER IF EXISTS trg_{table}_episode_complete ON trading.{table}"
        )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_check_episode_spec_set()")
    op.execute("DROP TRIGGER IF EXISTS trg_gate_decisions_semantics ON trading.gate_decisions")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_gate_decision()")
    op.execute("DROP TRIGGER IF EXISTS trg_forecast_episodes_lifecycle ON trading.forecast_episodes")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_episode()")
    for table in reversed(_COGNITION_TABLES):
        if table.append_only:
            op.execute(
                f"DROP TRIGGER IF EXISTS trg_{table.name}_immutable "
                f"ON {TRADING_SCHEMA}.{table.name}"
            )


def _gate_guard_0013_fn() -> str:
    return r"""
CREATE FUNCTION trading.v2_guard_gate_decision() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    root_id bigint;
    screening_id bigint;
    opportunity_id bigint;
BEGIN
    IF NEW.gate IN ('G0','R0') THEN
        IF NOT EXISTS (SELECT 1 FROM trading.screening_episodes WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NEW.gate IN ('G1','G2') THEN
        IF NOT EXISTS (SELECT 1 FROM trading.decision_opportunities WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NOT EXISTS (SELECT 1 FROM trading.forecast_episodes WHERE id = NEW.target_id) THEN
        RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
    END IF;

    IF (NEW.gate = 'G0' AND NEW.result NOT IN ('PASS','PREDICTION_RESEARCH_ONLY'))
       OR (NEW.gate = 'R0' AND NEW.result NOT IN ('SELECT','DEFER','REJECT'))
       OR (NEW.gate IN ('G1','G2') AND NEW.result NOT IN ('PASS','FAIL'))
       OR (NEW.gate = 'R1' AND NEW.result NOT IN ('reject','shallow','standard','deep')) THEN
        RAISE EXCEPTION 'v2_gate_result_invalid' USING ERRCODE='23514';
    END IF;
    IF NEW.result IN ('PREDICTION_RESEARCH_ONLY','DEFER','REJECT','FAIL','reject')
       AND NEW.reason_code IS NULL THEN
        RAISE EXCEPTION 'v2_gate_failure_reason_required' USING ERRCODE='23514';
    END IF;

    IF NEW.gate = 'R0' AND NOT EXISTS (
        SELECT 1 FROM trading.gate_decisions gd
         WHERE gd.gate = 'G0' AND gd.target_kind = 'screening'
           AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
    ) THEN
        RAISE EXCEPTION 'v2_gate_order_g0_r0' USING ERRCODE='23514';
    ELSIF NEW.gate = 'G1' THEN
        SELECT COALESCE(o.parent_id, o.id) INTO STRICT root_id
          FROM trading.decision_opportunities o WHERE o.id = NEW.target_id;
        SELECT source_screening_episode_id INTO screening_id
          FROM trading.decision_opportunities WHERE id = root_id;
        IF screening_id IS NULL OR NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'R0' AND gd.target_kind = 'screening'
               AND gd.target_id = screening_id
               AND (gd.result = 'SELECT' OR EXISTS (
                    SELECT 1 FROM trading.screening_episodes se
                     WHERE se.id = screening_id AND se.audit_assigned))
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_r0_g1' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G2' THEN
        SELECT COALESCE(o.parent_id, o.id) INTO STRICT root_id
          FROM trading.decision_opportunities o WHERE o.id = NEW.target_id;
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
            JOIN trading.decision_opportunities prior ON prior.id = gd.target_id
             WHERE gd.gate = 'G1' AND gd.target_kind = 'opportunity' AND gd.result = 'PASS'
               AND COALESCE(prior.parent_id, prior.id) = root_id
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g1_g2' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'R1' THEN
        SELECT decision_opportunity_id INTO STRICT opportunity_id
          FROM trading.forecast_episodes WHERE id = NEW.target_id;
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G2' AND gd.target_kind = 'opportunity'
               AND gd.target_id = opportunity_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g2_r1' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $v2_guard$
"""


def _episode_spec_0013_fn() -> str:
    return r"""
CREATE FUNCTION trading.v2_check_episode_spec_set() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    episode_ref bigint;
    n integer;
    episode_status text;
    opportunity_ref bigint;
    component_status text;
    episode_objective bigint;
    episode_strategy bigint;
    opportunity_objective bigint;
    opportunity_strategy bigint;
    route text;
BEGIN
    IF TG_TABLE_NAME = 'forecast_episodes' THEN
        episode_ref := NEW.id;
    ELSE
        episode_ref := NEW.episode_id;
    END IF;
    SELECT fe.status, fe.decision_opportunity_id, cv.status,
           fe.objective_contract_id, fe.strategy_version_id,
           o.objective_contract_id, o.strategy_version_id
      INTO STRICT episode_status, opportunity_ref, component_status,
                  episode_objective, episode_strategy,
                  opportunity_objective, opportunity_strategy
      FROM trading.forecast_episodes fe
      JOIN trading.forecast_component_versions cv ON cv.id = fe.component_version_id
      JOIN trading.decision_opportunities o ON o.id = fe.decision_opportunity_id
     WHERE fe.id = episode_ref;
    IF component_status <> 'active' OR episode_objective <> opportunity_objective
       OR episode_strategy <> opportunity_strategy THEN
        RAISE EXCEPTION 'v2_episode_identity_or_component_invalid' USING ERRCODE='23514';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM trading.gate_decisions gd
         WHERE gd.gate = 'G2' AND gd.target_kind = 'opportunity'
           AND gd.target_id = opportunity_ref AND gd.result = 'PASS'
    ) THEN
        RAISE EXCEPTION 'v2_episode_requires_g2_pass' USING ERRCODE='23514';
    END IF;
    SELECT count(*) INTO n FROM (
        SELECT ecs.contract_spec_id FROM trading.episode_contract_specs ecs
         WHERE ecs.episode_id = episode_ref
        EXCEPT
        SELECT fcs.contract_spec_id
          FROM trading.forecast_episodes fe
          JOIN trading.forecast_component_contract_specs fcs
            ON fcs.component_version_id = fe.component_version_id
         WHERE fe.id = episode_ref
    ) extra;
    IF n > 0 THEN RAISE EXCEPTION 'v2_episode_spec_extra' USING ERRCODE='23514'; END IF;
    SELECT count(*) INTO n FROM (
        SELECT fcs.contract_spec_id
          FROM trading.forecast_episodes fe
          JOIN trading.forecast_component_contract_specs fcs
            ON fcs.component_version_id = fe.component_version_id
         WHERE fe.id = episode_ref
        EXCEPT
        SELECT ecs.contract_spec_id FROM trading.episode_contract_specs ecs
         WHERE ecs.episode_id = episode_ref
    ) missing;
    IF n > 0 THEN RAISE EXCEPTION 'v2_episode_spec_missing' USING ERRCODE='23514'; END IF;
    IF episode_status IN ('ROUTED','PRE_COMMIT_TERMINAL') THEN
        SELECT count(*), min(route_channel) INTO n, route
          FROM trading.episode_memberships WHERE episode_id = episode_ref;
        IF n <> 1 OR NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'R1' AND gd.target_kind = 'episode'
               AND gd.target_id = episode_ref AND gd.result = route
        ) THEN
            RAISE EXCEPTION 'v2_episode_r1_route_missing' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $v2_guard$
"""


def _restore_0013_guards() -> None:
    """恢复 b1000013 版本的全部原 guard 函数（episode/gate/spec-set）与触发器。"""
    op.execute(_episode_spec_0013_fn())
    for table, events in (
        ("forecast_episodes", "INSERT OR UPDATE"),
        ("episode_contract_specs", "INSERT OR UPDATE"),
        ("episode_memberships", "INSERT OR UPDATE"),
    ):
        op.execute(
            f"CREATE CONSTRAINT TRIGGER trg_{table}_episode_complete "
            f"AFTER {events} ON trading.{table} "
            "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
            "EXECUTE FUNCTION trading.v2_check_episode_spec_set()"
        )
    op.execute(_gate_guard_0013_fn())
    op.execute(
        "CREATE TRIGGER trg_gate_decisions_semantics BEFORE INSERT ON trading.gate_decisions "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_gate_decision()"
    )
    # 直接从 b1000013 的 SQL 恢复。为避免重复实现，这里内联 b1000013 的原函数体。
    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_episode() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    opportunity_row record;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_episode_immutable' USING ERRCODE='55000';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'DRAFT' OR NEW.drop_reason IS NOT NULL THEN
            RAISE EXCEPTION 'v2_episode_initial_state_invalid' USING ERRCODE='23514';
        END IF;
        SELECT objective_contract_id, strategy_version_id, status
          INTO STRICT opportunity_row
          FROM trading.decision_opportunities WHERE id = NEW.decision_opportunity_id;
        IF opportunity_row.objective_contract_id <> NEW.objective_contract_id
           OR opportunity_row.strategy_version_id <> NEW.strategy_version_id
           OR opportunity_row.status <> 'OPEN' THEN
            RAISE EXCEPTION 'v2_episode_opportunity_identity_mismatch' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF OLD.episode_key IS DISTINCT FROM NEW.episode_key
       OR OLD.decision_opportunity_id IS DISTINCT FROM NEW.decision_opportunity_id
       OR OLD.component_version_id IS DISTINCT FROM NEW.component_version_id
       OR OLD.strategy_version_id IS DISTINCT FROM NEW.strategy_version_id
       OR OLD.objective_contract_id IS DISTINCT FROM NEW.objective_contract_id
       OR OLD.trigger IS DISTINCT FROM NEW.trigger
       OR OLD.cutoff_at IS DISTINCT FROM NEW.cutoff_at
       OR OLD.horizon IS DISTINCT FROM NEW.horizon
       OR OLD.experiment_variant IS DISTINCT FROM NEW.experiment_variant
       OR OLD.created_at IS DISTINCT FROM NEW.created_at
       OR OLD.status <> 'DRAFT'
       OR NEW.status NOT IN ('ROUTED','PRE_COMMIT_TERMINAL') THEN
        RAISE EXCEPTION 'v2_episode_immutable' USING ERRCODE='55000';
    END IF;
    IF NEW.status = 'ROUTED' AND NEW.drop_reason IS NOT NULL THEN
        RAISE EXCEPTION 'v2_episode_terminal_shape_invalid' USING ERRCODE='23514';
    ELSIF NEW.status = 'PRE_COMMIT_TERMINAL' AND NEW.drop_reason IS NULL THEN
        RAISE EXCEPTION 'v2_episode_terminal_shape_invalid' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_forecast_episodes_lifecycle "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.forecast_episodes "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_episode()"
    )


def upgrade() -> None:
    """Create 11 cognition tables + reinforcement + guards."""
    for table in _COGNITION_TABLES:
        op.execute(table.create_sql)
        _create_table_indexes(table)
    _reinforce_episode_and_gates()
    _create_guards()


def downgrade() -> None:
    """Drop 11 tables + undo reinforcement + restore b1000013 guards."""
    _assert_downgrade_safe()
    _drop_guards()
    for table in reversed(_COGNITION_TABLES):
        op.execute(f"DROP TABLE {TRADING_SCHEMA}.{table.name}")
    _unreinforce_episode_and_gates()
    _restore_0013_guards()
