"""create p1a cohort episode

Revision ID: b1000013
Revises: b1000012
Create Date: 2026-08-10 11:30:00

v2_0013 —— Cohort & Episode（WP-01C Checkpoint B/C）：创建 12 张表 + 对既有 policy 表可逆强化。

- ``upgrade``：
  - 12 张新表（cohort 4 + workflow 8）与 append-only guards（复用 0002 immutable 函数）；
  - 对 ``policy_type_scopes`` / ``policy_freezes`` 可逆强化（任务 §6）：
    - ``policy_type_scopes``：drop 三元组唯一 → policy_type 唯一 + scope_type CHECK；
    - ``policy_freezes``：新增 policy_type/scope_type/scope_key/policy_version/frozen_at 列，
      type+scope+version 唯一 + scope_type CHECK；
  - deferred constraint trigger ``v2_check_episode_spec_set``：提交时核验 episode 的
    contract-spec 集与 component membership 完全相等（任务 §7 / 架构 §1.2）。
- ``downgrade``：逆序删 12 表 + guard 函数；移除 policy 强化（删约束/列、恢复三元组唯一）；
  不删 0002 的 ``v2_reject_immutable_row``。
"""
from dataclasses import dataclass
from typing import Sequence, Union

from alembic import op

TRADING_SCHEMA = "trading"

# revision identifiers, used by Alembic.
revision: str = "b1000013"
down_revision: Union[str, Sequence[str], None] = "b1000012"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# policy 唯一 scope 类型（与 models/control.py CHECK 一致）
_SCOPE_TYPES = (
    "strategy", "cohort", "component_version", "episode_submission",
    "execution_spec", "promotion",
)


@dataclass(frozen=True)
class _FrozenTableSpec:
    name: str
    create_sql: str
    index_sql: tuple[str, ...] = ()


_STREAM_TABLES = (
    _FrozenTableSpec(
        name='evaluation_cohorts',
        create_sql='\nCREATE TABLE trading.evaluation_cohorts (\n\tcohort_key TEXT COLLATE "C" NOT NULL, \n\tstatus VARCHAR(32) DEFAULT \'DRAFT\' NOT NULL, \n\tobjective_contract_id BIGINT NOT NULL, \n\tstrategy_version_id BIGINT NOT NULL, \n\trelease_manifest_id BIGINT NOT NULL, \n\tpolicy_hashes JSONB NOT NULL, \n\tseed_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\topened_at TIMESTAMP WITH TIME ZONE, \n\tclosed_at TIMESTAMP WITH TIME ZONE, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_evaluation_cohorts_key UNIQUE (cohort_key), \n\tCONSTRAINT ck_evaluation_cohorts_status_known CHECK (status IN (\'DRAFT\',\'OPEN\',\'CLOSED\',\'SUPERSEDED\')), \n\tCONSTRAINT ck_evaluation_cohorts_seed_hash_hex CHECK (seed_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_evaluation_cohorts_policy_hashes_object CHECK (jsonb_typeof(policy_hashes) = \'object\'), \n\tCONSTRAINT fk_evaluation_cohorts_objective FOREIGN KEY(objective_contract_id) REFERENCES trading.strategy_objective_contracts (id), \n\tCONSTRAINT fk_evaluation_cohorts_strategy FOREIGN KEY(strategy_version_id) REFERENCES trading.strategy_versions (id), \n\tCONSTRAINT fk_evaluation_cohorts_release FOREIGN KEY(release_manifest_id) REFERENCES trading.release_manifests (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='universe_memberships',
        create_sql='\nCREATE TABLE trading.universe_memberships (\n\tcohort_id BIGINT NOT NULL, \n\tmarket_id BIGINT NOT NULL, \n\tfirst_seen_source VARCHAR(16) NOT NULL, \n\tfirst_observed_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tfirst_ingested_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tmetadata_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tconfirmed_frame_id BIGINT, \n\tconfirmed_at TIMESTAMP WITH TIME ZONE, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_universe_memberships_cohort_market UNIQUE (cohort_id, market_id), \n\tCONSTRAINT ck_universe_memberships_first_seen_source_known CHECK (first_seen_source IN (\'REST_FRAME\',\'WS_HINT\')), \n\tCONSTRAINT ck_universe_memberships_metadata_hash_hex CHECK (metadata_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_universe_memberships_confirmation_pair CHECK ((confirmed_frame_id IS NULL) = (confirmed_at IS NULL)), \n\tCONSTRAINT fk_universe_memberships_cohort FOREIGN KEY(cohort_id) REFERENCES trading.evaluation_cohorts (id), \n\tCONSTRAINT fk_universe_memberships_market FOREIGN KEY(market_id) REFERENCES trading.pm_markets (id), \n\tCONSTRAINT fk_universe_memberships_confirmed_frame FOREIGN KEY(confirmed_frame_id) REFERENCES trading.pm_universe_frames (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_universe_memberships_cohort ON trading.universe_memberships (cohort_id)',),
    ),
    _FrozenTableSpec(
        name='screening_episodes',
        create_sql='\nCREATE TABLE trading.screening_episodes (\n\tcohort_id BIGINT NOT NULL, \n\tmarket_id BIGINT NOT NULL, \n\tepisode_no INTEGER NOT NULL, \n\tobjective_contract_id BIGINT NOT NULL, \n\tinput_snapshot JSONB NOT NULL, \n\tinput_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tresult VARCHAR(16) NOT NULL, \n\treason_code VARCHAR(128), \n\trecheck_at TIMESTAMP WITH TIME ZONE, \n\trecheck_condition VARCHAR(255), \n\taudit_assigned BOOLEAN DEFAULT \'false\' NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_screening_episodes_cohort_market_no UNIQUE (cohort_id, market_id, episode_no), \n\tCONSTRAINT ck_screening_episodes_result_known CHECK (result IN (\'SELECT\',\'DEFER\',\'REJECT\')), \n\tCONSTRAINT ck_screening_episodes_input_hash_hex CHECK (input_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_screening_episodes_no_positive CHECK (episode_no > 0), \n\tCONSTRAINT ck_screening_episodes_disposition_shape CHECK ((result = \'SELECT\' AND reason_code IS NULL AND recheck_at IS NULL AND recheck_condition IS NULL) OR (result IN (\'DEFER\',\'REJECT\') AND reason_code IS NOT NULL AND (recheck_at IS NOT NULL OR recheck_condition IS NOT NULL))), \n\tCONSTRAINT fk_screening_episodes_membership FOREIGN KEY(cohort_id, market_id) REFERENCES trading.universe_memberships (cohort_id, market_id), \n\tCONSTRAINT fk_screening_episodes_cohort FOREIGN KEY(cohort_id) REFERENCES trading.evaluation_cohorts (id), \n\tCONSTRAINT fk_screening_episodes_market FOREIGN KEY(market_id) REFERENCES trading.pm_markets (id), \n\tCONSTRAINT fk_screening_episodes_objective FOREIGN KEY(objective_contract_id) REFERENCES trading.strategy_objective_contracts (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_screening_episodes_cohort ON trading.screening_episodes (cohort_id, market_id)',),
    ),
    _FrozenTableSpec(
        name='audit_samples',
        create_sql='\nCREATE TABLE trading.audit_samples (\n\tcohort_id BIGINT NOT NULL, \n\ttarget VARCHAR(16) NOT NULL, \n\tcontent_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tstratum VARCHAR(64) NOT NULL, \n\tseed_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\talgorithm_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tu NUMERIC(38, 12) NOT NULL, \n\tinclusion_probability NUMERIC(38, 12) NOT NULL, \n\tselected BOOLEAN NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_audit_samples_cohort_target_hash UNIQUE (cohort_id, target, content_hash), \n\tCONSTRAINT ck_audit_samples_target_known CHECK (target IN (\'r0\',\'r1\',\'contract\',\'component\')), \n\tCONSTRAINT ck_audit_samples_seed_hash_hex CHECK (seed_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_audit_samples_algorithm_hash_hex CHECK (algorithm_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_audit_samples_content_hash_hex CHECK (content_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_audit_samples_u_range CHECK (u >= 0 AND u < 1), \n\tCONSTRAINT ck_audit_samples_probability_range CHECK (inclusion_probability >= 0 AND inclusion_probability <= 1), \n\tCONSTRAINT ck_audit_samples_selection_consistent CHECK (selected = (u < inclusion_probability)), \n\tCONSTRAINT fk_audit_samples_cohort FOREIGN KEY(cohort_id) REFERENCES trading.evaluation_cohorts (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='decision_opportunities',
        create_sql='\nCREATE TABLE trading.decision_opportunities (\n\topportunity_key TEXT COLLATE "C" NOT NULL, \n\tcohort_id BIGINT NOT NULL, \n\tparent_id BIGINT, \n\tchain_type VARCHAR(16) NOT NULL, \n\tobjective_contract_id BIGINT NOT NULL, \n\tstrategy_version_id BIGINT NOT NULL, \n\tsource_screening_episode_id BIGINT, \n\tstatus VARCHAR(32) DEFAULT \'OPEN\' NOT NULL, \n\tdisposition VARCHAR(32) DEFAULT \'deferred\' NOT NULL, \n\tterminal_reason VARCHAR(128), \n\tg0_manifest_hash VARCHAR(64) COLLATE "C", \n\taudit_tag VARCHAR(32), \n\ttriggered_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_decision_opportunities_key UNIQUE (opportunity_key), \n\tCONSTRAINT ck_decision_opportunities_chain_type_known CHECK (chain_type IN (\'DECISION\',\'RESEARCH_EVAL\')), \n\tCONSTRAINT ck_decision_opportunities_status_known CHECK (status IN (\'OPEN\',\'PRE_COMMIT_TERMINAL\',\'ROUTED\',\'SUPERSEDED\')), \n\tCONSTRAINT ck_decision_opportunities_disposition_known CHECK (disposition IN (\'completed\',\'rejected\',\'deferred\',\'failed\',\'expired\',\'superseded\')), \n\tCONSTRAINT fk_decision_opportunities_cohort FOREIGN KEY(cohort_id) REFERENCES trading.evaluation_cohorts (id), \n\tCONSTRAINT fk_decision_opportunities_parent FOREIGN KEY(parent_id) REFERENCES trading.decision_opportunities (id), \n\tCONSTRAINT fk_decision_opportunities_objective FOREIGN KEY(objective_contract_id) REFERENCES trading.strategy_objective_contracts (id), \n\tCONSTRAINT fk_decision_opportunities_strategy FOREIGN KEY(strategy_version_id) REFERENCES trading.strategy_versions (id), \n\tCONSTRAINT fk_decision_opportunities_screening FOREIGN KEY(source_screening_episode_id) REFERENCES trading.screening_episodes (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_decision_opportunities_cohort ON trading.decision_opportunities (cohort_id)',),
    ),
    _FrozenTableSpec(
        name='decision_opportunity_markets',
        create_sql='\nCREATE TABLE trading.decision_opportunity_markets (\n\topportunity_id BIGINT NOT NULL, \n\tmarket_id BIGINT NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_decision_opportunity_markets_pair UNIQUE (opportunity_id, market_id), \n\tCONSTRAINT fk_decision_opportunity_markets_opp FOREIGN KEY(opportunity_id) REFERENCES trading.decision_opportunities (id), \n\tCONSTRAINT fk_decision_opportunity_markets_market FOREIGN KEY(market_id) REFERENCES trading.pm_markets (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='forecast_episodes',
        create_sql='\nCREATE TABLE trading.forecast_episodes (\n\tepisode_key VARCHAR(64) COLLATE "C" NOT NULL, \n\tdecision_opportunity_id BIGINT NOT NULL, \n\tcomponent_version_id BIGINT NOT NULL, \n\tstrategy_version_id BIGINT NOT NULL, \n\tobjective_contract_id BIGINT NOT NULL, \n\ttrigger VARCHAR(32) NOT NULL, \n\tcutoff_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\thorizon VARCHAR(64) NOT NULL, \n\texperiment_variant VARCHAR(64) NOT NULL, \n\tstatus VARCHAR(32) DEFAULT \'DRAFT\' NOT NULL, \n\tdrop_reason VARCHAR(128), \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_forecast_episodes_key UNIQUE (episode_key), \n\tCONSTRAINT ck_forecast_episodes_status_known CHECK (status IN (\'DRAFT\',\'ROUTED\',\'PRE_COMMIT_TERMINAL\')), \n\tCONSTRAINT ck_forecast_episodes_key_hex CHECK (episode_key ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT fk_forecast_episodes_opportunity FOREIGN KEY(decision_opportunity_id) REFERENCES trading.decision_opportunities (id), \n\tCONSTRAINT fk_forecast_episodes_component_version FOREIGN KEY(component_version_id) REFERENCES trading.forecast_component_versions (id), \n\tCONSTRAINT fk_forecast_episodes_strategy FOREIGN KEY(strategy_version_id) REFERENCES trading.strategy_versions (id), \n\tCONSTRAINT fk_forecast_episodes_objective FOREIGN KEY(objective_contract_id) REFERENCES trading.strategy_objective_contracts (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_forecast_episodes_opportunity ON trading.forecast_episodes (decision_opportunity_id)',),
    ),
    _FrozenTableSpec(
        name='episode_contract_specs',
        create_sql='\nCREATE TABLE trading.episode_contract_specs (\n\tepisode_id BIGINT NOT NULL, \n\tcontract_spec_id BIGINT NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_episode_contract_specs_pair UNIQUE (episode_id, contract_spec_id), \n\tCONSTRAINT fk_episode_contract_specs_episode FOREIGN KEY(episode_id) REFERENCES trading.forecast_episodes (id), \n\tCONSTRAINT fk_episode_contract_specs_spec FOREIGN KEY(contract_spec_id) REFERENCES trading.contract_specs (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='episode_memberships',
        create_sql="\nCREATE TABLE trading.episode_memberships (\n\tepisode_id BIGINT NOT NULL, \n\troute_channel VARCHAR(16) NOT NULL, \n\tfirst_rejected_gate VARCHAR(8), \n\treason_code VARCHAR(128), \n\trecheck_at TIMESTAMP WITH TIME ZONE, \n\trecheck_condition VARCHAR(255), \n\tprocessing_disposition VARCHAR(32) NOT NULL, \n\taction_eligible BOOLEAN DEFAULT 'false' NOT NULL, \n\tqualification_eligible BOOLEAN DEFAULT 'false' NOT NULL, \n\tcapital_evidence_eligible BOOLEAN DEFAULT 'false' NOT NULL, \n\taudit_selected BOOLEAN DEFAULT 'false' NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_episode_memberships_episode UNIQUE (episode_id), \n\tCONSTRAINT ck_episode_memberships_route_known CHECK (route_channel IN ('reject','shallow','standard','deep')), \n\tCONSTRAINT ck_episode_memberships_disposition_known CHECK (processing_disposition IN ('completed','rejected','deferred','failed','expired','superseded')), \n\tCONSTRAINT ck_episode_memberships_wp01c_no_eligibility CHECK (NOT action_eligible AND NOT qualification_eligible AND NOT capital_evidence_eligible), \n\tCONSTRAINT ck_episode_memberships_reject_shape CHECK (route_channel <> 'reject' OR (reason_code IS NOT NULL AND (recheck_at IS NOT NULL OR recheck_condition IS NOT NULL))), \n\tCONSTRAINT fk_episode_memberships_episode FOREIGN KEY(episode_id) REFERENCES trading.forecast_episodes (id)\n)\n\n",
    ),
    _FrozenTableSpec(
        name='information_snapshots',
        create_sql='\nCREATE TABLE trading.information_snapshots (\n\tsnapshot_key TEXT COLLATE "C" NOT NULL, \n\tepisode_id BIGINT, \n\topportunity_id BIGINT, \n\tgate VARCHAR(8) NOT NULL, \n\tcontent JSONB NOT NULL, \n\tcontent_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_information_snapshots_key UNIQUE (snapshot_key), \n\tCONSTRAINT ck_information_snapshots_hash_hex CHECK (content_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_information_snapshots_gate_known CHECK (gate IN (\'G0\',\'R0\',\'G1\',\'G2\',\'R1\')), \n\tCONSTRAINT ck_information_snapshots_content_object CHECK (jsonb_typeof(content) = \'object\'), \n\tCONSTRAINT ck_information_snapshots_one_target CHECK ((episode_id IS NULL) <> (opportunity_id IS NULL)), \n\tCONSTRAINT fk_information_snapshots_episode FOREIGN KEY(episode_id) REFERENCES trading.forecast_episodes (id), \n\tCONSTRAINT fk_information_snapshots_opportunity FOREIGN KEY(opportunity_id) REFERENCES trading.decision_opportunities (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='information_snapshot_items',
        create_sql='\nCREATE TABLE trading.information_snapshot_items (\n\tsnapshot_id BIGINT NOT NULL, \n\titem_no INTEGER NOT NULL, \n\tkind VARCHAR(32) NOT NULL, \n\tartifact_ref VARCHAR(64) COLLATE "C", \n\tversion_hash VARCHAR(64) COLLATE "C", \n\titem_data JSONB NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_information_snapshot_items_snapshot_no UNIQUE (snapshot_id, item_no), \n\tCONSTRAINT fk_information_snapshot_items_snapshot FOREIGN KEY(snapshot_id) REFERENCES trading.information_snapshots (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='gate_decisions',
        create_sql='\nCREATE TABLE trading.gate_decisions (\n\tgate VARCHAR(8) NOT NULL, \n\ttarget_kind VARCHAR(16) NOT NULL, \n\ttarget_id BIGINT NOT NULL, \n\tinput_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tpolicy_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tversion_manifest_id BIGINT NOT NULL, \n\tresult VARCHAR(32) NOT NULL, \n\treason_code VARCHAR(128), \n\tcommitted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_gate_decisions_target UNIQUE (gate, target_id, target_kind), \n\tCONSTRAINT ck_gate_decisions_gate_known CHECK (gate IN (\'G0\',\'R0\',\'G1\',\'G2\',\'R1\')), \n\tCONSTRAINT ck_gate_decisions_target_kind_known CHECK (target_kind IN (\'screening\',\'opportunity\',\'episode\')), \n\tCONSTRAINT ck_gate_decisions_gate_target_pair CHECK ((gate IN (\'G0\',\'R0\') AND target_kind = \'screening\') OR (gate IN (\'G1\',\'G2\') AND target_kind = \'opportunity\') OR (gate = \'R1\' AND target_kind = \'episode\')), \n\tCONSTRAINT ck_gate_decisions_input_hash_hex CHECK (input_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_gate_decisions_policy_hash_hex CHECK (policy_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT fk_gate_decisions_release FOREIGN KEY(version_manifest_id) REFERENCES trading.release_manifests (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_gate_decisions_target ON trading.gate_decisions (gate, target_kind, target_id)',),
    ),
)

_IMMUTABLE_TABLES = (
    "screening_episodes",
    "audit_samples",
    "decision_opportunity_markets",
    "episode_contract_specs",
    "episode_memberships",
    "information_snapshots",
    "information_snapshot_items",
    "gate_decisions",
)

_PRE_0013_RELATIONS = (
    "artifact_objects", "artifact_lineage_edges", "archive_manifests",
    "retention_manifests", "runtime_config_versions", "strategy_objective_contracts",
    "strategy_versions", "execution_spec_versions", "capital_permission_manifests",
    "model_role_bindings", "release_manifests", "policy_type_scopes", "policy_freezes",
    "secret_vault_entries", "secret_vault_versions", "secret_access_events",
    "idempotency_claims", "transactional_outbox", "outbox_delivery_history",
    "job_completions", "pm_universe_frames", "pm_universe_frame_pages", "pm_events",
    "pm_markets", "pm_market_versions", "pm_tokens", "pm_token_versions",
    "pm_market_lifecycle_events", "pm_market_current", "pm_connection_epochs",
    "pm_source_event_batches", "pm_source_event_index", "pm_book_checkpoints",
    "pm_book_levels", "pm_book_current", "pm_quote_bindings", "contract_snapshots",
    "contract_specs", "payout_functions", "forecast_components", "world_schema_versions",
    "forecast_component_versions", "forecast_component_contract_specs",
    "portfolio_dependency_edges",
)


def _assert_downgrade_safe() -> None:
    allowed = ", ".join(
        f"'{name}'" for name in (*_PRE_0013_RELATIONS, *(t.name for t in _STREAM_TABLES))
    )
    op.execute(
        f"""
DO $v2_wp01c_preflight$
DECLARE unknown_objects text;
BEGIN
    SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
      INTO unknown_objects
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'trading'
       AND c.relkind IN ('r','p','v','m','f')
       AND c.relname NOT IN ({allowed})
       AND NOT EXISTS (
           SELECT 1 FROM pg_inherits i
           JOIN pg_class p ON p.oid = i.inhparent
           JOIN pg_namespace pn ON pn.oid = p.relnamespace
           WHERE i.inhrelid = c.oid AND pn.nspname = 'trading'
             AND ((p.relname = 'outbox_delivery_history'
                   AND c.relname ~ '^outbox_delivery_history_[0-9]{{6}}$')
               OR (p.relname IN ('pm_source_event_batches','pm_source_event_index',
                                  'pm_book_checkpoints','pm_book_levels')
                   AND c.relname ~ ('^' || p.relname || '_[0-9]{{8}}$')))
       );
    IF unknown_objects IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp01c_unknown_object:%', unknown_objects USING ERRCODE='55000';
    END IF;
END $v2_wp01c_preflight$
"""
    )


def _create_table_indexes(table: _FrozenTableSpec) -> None:
    for statement in table.index_sql:
        op.execute(statement)


def _reinforce_policies() -> None:
    """Strengthen the existing policy tables without corrupting populated b1000012 heads."""
    scope_vals = ",".join(f"'{s}'" for s in _SCOPE_TYPES)
    op.execute(
        """
DO $v2_policy_preflight$
BEGIN
    IF EXISTS (
        SELECT 1 FROM trading.policy_type_scopes
         GROUP BY policy_type HAVING count(*) > 1
    ) THEN
        RAISE EXCEPTION 'v2_policy_scope_ambiguous' USING ERRCODE='55000';
    END IF;
END $v2_policy_preflight$
"""
    )
    op.execute(
        "ALTER TABLE trading.policy_type_scopes "
        "DROP CONSTRAINT IF EXISTS uq_policy_type_scopes_triple"
    )
    op.execute(
        "ALTER TABLE trading.policy_type_scopes "
        "ADD CONSTRAINT uq_policy_type_scopes_type UNIQUE (policy_type)"
    )
    op.execute(
        "ALTER TABLE trading.policy_type_scopes "
        "ADD CONSTRAINT uq_policy_type_scopes_type_scope "
        "UNIQUE (policy_type, scope_type)"
    )
    op.execute(
        "ALTER TABLE trading.policy_type_scopes "
        f"ADD CONSTRAINT ck_policy_type_scopes_scope_type_known "
        f"CHECK (scope_type IN ({scope_vals}))"
    )

    # Old rows have no reconstructable type/scope. Preserve their original facts and quarantine
    # them under deterministic, non-resolvable legacy identities rather than inventing a live policy.
    op.execute("ALTER TABLE trading.policy_freezes DISABLE TRIGGER trg_policy_freezes_lifecycle")
    op.execute("ALTER TABLE trading.policy_freezes ADD COLUMN policy_type VARCHAR(64)")
    op.execute("ALTER TABLE trading.policy_freezes ADD COLUMN scope_type VARCHAR(64)")
    op.execute("ALTER TABLE trading.policy_freezes ADD COLUMN scope_key TEXT COLLATE \"C\"")
    op.execute("ALTER TABLE trading.policy_freezes ADD COLUMN policy_version INTEGER")
    op.execute("ALTER TABLE trading.policy_freezes ADD COLUMN frozen_at TIMESTAMP WITH TIME ZONE")
    op.execute(
        "UPDATE trading.policy_freezes SET "
        "policy_type='__legacy_freeze__:' || id::text, scope_type='promotion', "
        "scope_key='legacy:' || id::text, policy_version=0, frozen_at=created_at"
    )
    op.execute(
        "ALTER TABLE trading.policy_freezes "
        "ALTER COLUMN frozen_at SET DEFAULT now()"
    )
    op.execute(
        "INSERT INTO trading.policy_type_scopes (policy_type, scope_type, scope_key) "
        "SELECT policy_type, scope_type, '__legacy__' FROM trading.policy_freezes "
        "ON CONFLICT (policy_type) DO NOTHING"
    )
    for column in ("policy_type", "scope_type", "scope_key", "policy_version", "frozen_at"):
        op.execute(f"ALTER TABLE trading.policy_freezes ALTER COLUMN {column} SET NOT NULL")
    op.execute(
        "ALTER TABLE trading.policy_freezes "
        "ADD CONSTRAINT uq_policy_freezes_type_scope_version "
        "UNIQUE (policy_type, scope_type, scope_key, policy_version)"
    )
    op.execute(
        "ALTER TABLE trading.policy_freezes "
        f"ADD CONSTRAINT ck_policy_freezes_scope_type_known "
        f"CHECK (scope_type IN ({scope_vals}))"
    )
    op.execute(
        "ALTER TABLE trading.policy_freezes "
        "ADD CONSTRAINT ck_policy_freezes_version_nonneg CHECK (policy_version >= 0)"
    )
    op.execute(
        "ALTER TABLE trading.policy_freezes "
        "ADD CONSTRAINT fk_policy_freezes_policy_scope "
        "FOREIGN KEY (policy_type, scope_type) "
        "REFERENCES trading.policy_type_scopes (policy_type, scope_type)"
    )
    op.execute("ALTER TABLE trading.policy_freezes ENABLE TRIGGER trg_policy_freezes_lifecycle")


def _unreinforce_policies() -> None:
    """Undo the schema reinforcement and remove migration-only legacy registry rows."""
    op.execute(
        "ALTER TABLE trading.policy_freezes "
        "DROP CONSTRAINT IF EXISTS fk_policy_freezes_policy_scope"
    )
    op.execute(
        "ALTER TABLE trading.policy_freezes "
        "DROP CONSTRAINT IF EXISTS ck_policy_freezes_version_nonneg"
    )
    op.execute(
        "ALTER TABLE trading.policy_freezes "
        "DROP CONSTRAINT IF EXISTS ck_policy_freezes_scope_type_known"
    )
    op.execute(
        "ALTER TABLE trading.policy_freezes "
        "DROP CONSTRAINT IF EXISTS uq_policy_freezes_type_scope_version"
    )
    op.execute("ALTER TABLE trading.policy_type_scopes DISABLE TRIGGER trg_policy_type_scopes_immutable")
    op.execute("DELETE FROM trading.policy_type_scopes WHERE policy_type LIKE '__legacy_freeze__:%'")
    op.execute("ALTER TABLE trading.policy_type_scopes ENABLE TRIGGER trg_policy_type_scopes_immutable")
    op.execute("ALTER TABLE trading.policy_freezes DROP COLUMN IF EXISTS frozen_at")
    op.execute("ALTER TABLE trading.policy_freezes DROP COLUMN IF EXISTS policy_version")
    op.execute("ALTER TABLE trading.policy_freezes DROP COLUMN IF EXISTS scope_key")
    op.execute("ALTER TABLE trading.policy_freezes DROP COLUMN IF EXISTS scope_type")
    op.execute("ALTER TABLE trading.policy_freezes DROP COLUMN IF EXISTS policy_type")
    op.execute(
        "ALTER TABLE trading.policy_type_scopes "
        "DROP CONSTRAINT IF EXISTS ck_policy_type_scopes_scope_type_known"
    )
    op.execute(
        "ALTER TABLE trading.policy_type_scopes "
        "DROP CONSTRAINT IF EXISTS uq_policy_type_scopes_type"
    )
    op.execute(
        "ALTER TABLE trading.policy_type_scopes "
        "DROP CONSTRAINT IF EXISTS uq_policy_type_scopes_type_scope"
    )
    op.execute(
        "ALTER TABLE trading.policy_type_scopes "
        "ADD CONSTRAINT uq_policy_type_scopes_triple "
        "UNIQUE (policy_type, scope_type, scope_key)"
    )

def _create_guards() -> None:
    for table in _IMMUTABLE_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table}_immutable "
            f"BEFORE UPDATE OR DELETE ON {TRADING_SCHEMA}.{table} "
            "FOR EACH ROW EXECUTE FUNCTION trading.v2_reject_immutable_row()"
        )

    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_cohort_lifecycle() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    objective_status text;
    strategy_status text;
    release_status text;
    release_strategy bigint;
    policy_count integer;
    freeze_count integer;
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'DRAFT' OR NEW.opened_at IS NOT NULL OR NEW.closed_at IS NOT NULL THEN
            RAISE EXCEPTION 'v2_cohort_must_start_draft' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_cohort_immutable' USING ERRCODE='55000';
    END IF;
    IF OLD.cohort_key IS DISTINCT FROM NEW.cohort_key
       OR OLD.objective_contract_id IS DISTINCT FROM NEW.objective_contract_id
       OR OLD.strategy_version_id IS DISTINCT FROM NEW.strategy_version_id
       OR OLD.release_manifest_id IS DISTINCT FROM NEW.release_manifest_id
       OR OLD.seed_hash IS DISTINCT FROM NEW.seed_hash
       OR OLD.policy_hashes IS DISTINCT FROM NEW.policy_hashes
       OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
        RAISE EXCEPTION 'v2_cohort_identity_immutable' USING ERRCODE='55000';
    END IF;

    IF OLD.status = 'DRAFT' AND NEW.status = 'OPEN' THEN
        SELECT status INTO STRICT objective_status
          FROM trading.strategy_objective_contracts WHERE id = NEW.objective_contract_id;
        SELECT status INTO STRICT strategy_status
          FROM trading.strategy_versions WHERE id = NEW.strategy_version_id;
        SELECT status, strategy_version_id INTO STRICT release_status, release_strategy
          FROM trading.release_manifests WHERE id = NEW.release_manifest_id;
        IF objective_status <> 'active' OR strategy_status <> 'active'
           OR release_status <> 'active' OR release_strategy <> NEW.strategy_version_id THEN
            RAISE EXCEPTION 'v2_cohort_control_binding_not_active' USING ERRCODE='23514';
        END IF;
        SELECT count(*) INTO policy_count FROM jsonb_object_keys(NEW.policy_hashes);
        IF policy_count <> 10 OR EXISTS (
            SELECT 1 FROM jsonb_object_keys(NEW.policy_hashes) p(policy_type)
             WHERE policy_type NOT IN (
                'eligibility','taxonomy','horizon','r0','r1','evidence_coverage',
                'shrinkage','baseline_scoring','split_inference','reject_audit'
             ) OR (NEW.policy_hashes ->> policy_type) !~ '^[0-9a-f]{64}$'
        ) THEN
            RAISE EXCEPTION 'v2_cohort_policy_set_incomplete' USING ERRCODE='23514';
        END IF;
        SELECT count(*) INTO freeze_count
          FROM trading.policy_freezes pf
          JOIN trading.policy_type_scopes pts ON pts.policy_type = pf.policy_type
         WHERE pf.scope_type = 'cohort'
           AND pts.scope_type = 'cohort'
           AND pf.scope_key = NEW.cohort_key
           AND pf.release_manifest_id = NEW.release_manifest_id
           AND pf.status = 'frozen'
           AND pf.policy_type IN (
                'eligibility','taxonomy','horizon','r0','r1','evidence_coverage',
                'shrinkage','baseline_scoring','split_inference','reject_audit'
           )
           AND pf.policy_content_hash = NEW.policy_hashes ->> pf.policy_type;
        IF freeze_count <> 10 THEN
            RAISE EXCEPTION 'v2_cohort_policy_freezes_incomplete:%', freeze_count USING ERRCODE='23514';
        END IF;
        IF NEW.opened_at IS NULL OR NEW.closed_at IS NOT NULL THEN
            RAISE EXCEPTION 'v2_cohort_open_timestamp_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    ELSIF OLD.status = 'DRAFT' AND NEW.status = 'SUPERSEDED' THEN
        IF NEW.opened_at IS NOT NULL THEN
            RAISE EXCEPTION 'v2_cohort_superseded_timestamp_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    ELSIF OLD.status = 'OPEN' AND NEW.status IN ('CLOSED','SUPERSEDED') THEN
        IF NEW.opened_at IS DISTINCT FROM OLD.opened_at OR NEW.closed_at IS NULL THEN
            RAISE EXCEPTION 'v2_cohort_close_timestamp_invalid' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'v2_cohort_immutable' USING ERRCODE='55000';
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_evaluation_cohorts_lifecycle "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.evaluation_cohorts "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_cohort_lifecycle()"
    )

    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_membership_confirm() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    cohort_status text;
    frame_status text;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_membership_immutable' USING ERRCODE='55000';
    END IF;
    IF TG_OP = 'INSERT' THEN
        SELECT status INTO STRICT cohort_status
          FROM trading.evaluation_cohorts WHERE id = NEW.cohort_id;
        IF cohort_status <> 'OPEN' THEN
            RAISE EXCEPTION 'v2_membership_requires_open_cohort' USING ERRCODE='23514';
        END IF;
    ELSE
        IF OLD.first_seen_source IS DISTINCT FROM NEW.first_seen_source
           OR OLD.market_id IS DISTINCT FROM NEW.market_id
           OR OLD.cohort_id IS DISTINCT FROM NEW.cohort_id
           OR OLD.metadata_hash IS DISTINCT FROM NEW.metadata_hash
           OR OLD.first_observed_at IS DISTINCT FROM NEW.first_observed_at
           OR OLD.first_ingested_at IS DISTINCT FROM NEW.first_ingested_at
           OR OLD.created_at IS DISTINCT FROM NEW.created_at
           OR OLD.confirmed_frame_id IS NOT NULL
           OR NEW.confirmed_frame_id IS NULL
           OR NEW.confirmed_at IS NULL THEN
            RAISE EXCEPTION 'v2_membership_immutable' USING ERRCODE='55000';
        END IF;
    END IF;
    IF NEW.confirmed_frame_id IS NOT NULL THEN
        SELECT status INTO STRICT frame_status
          FROM trading.pm_universe_frames WHERE id = NEW.confirmed_frame_id;
        IF frame_status <> 'COMPLETE' THEN
            RAISE EXCEPTION 'v2_membership_frame_not_complete' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_universe_memberships_confirm "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.universe_memberships "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_membership_confirm()"
    )

    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_screening_episode() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    cohort_status text;
    cohort_objective bigint;
BEGIN
    SELECT status, objective_contract_id INTO STRICT cohort_status, cohort_objective
      FROM trading.evaluation_cohorts WHERE id = NEW.cohort_id;
    IF cohort_status <> 'OPEN' OR cohort_objective <> NEW.objective_contract_id THEN
        RAISE EXCEPTION 'v2_screening_objective_mismatch' USING ERRCODE='23514';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM trading.universe_memberships m
         WHERE m.cohort_id = NEW.cohort_id AND m.market_id = NEW.market_id
           AND m.confirmed_frame_id IS NOT NULL
    ) THEN
        RAISE EXCEPTION 'v2_screening_requires_confirmed_membership' USING ERRCODE='23514';
    END IF;
    IF trading.v2_jsonb_has_forbidden_key(NEW.input_snapshot) THEN
        RAISE EXCEPTION 'v2_screening_forbidden_input' USING ERRCODE='23514';
    END IF;
    IF NEW.audit_assigned AND NOT EXISTS (
        SELECT 1 FROM trading.audit_samples a
         WHERE a.cohort_id = NEW.cohort_id AND a.target = 'r0'
           AND a.content_hash = NEW.input_hash AND a.selected
    ) THEN
        RAISE EXCEPTION 'v2_screening_audit_assignment_missing' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_screening_episodes_semantics "
        "BEFORE INSERT ON trading.screening_episodes "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_screening_episode()"
    )

    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_opportunity() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    parent_row record;
    cohort_objective bigint;
    cohort_strategy bigint;
    screening_row record;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_opportunity_immutable' USING ERRCODE='55000';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'OPEN' OR NEW.disposition <> 'deferred' OR NEW.terminal_reason IS NOT NULL THEN
            RAISE EXCEPTION 'v2_opportunity_initial_state_invalid' USING ERRCODE='23514';
        END IF;
        SELECT objective_contract_id, strategy_version_id
          INTO STRICT cohort_objective, cohort_strategy
          FROM trading.evaluation_cohorts WHERE id = NEW.cohort_id;
        IF cohort_objective <> NEW.objective_contract_id
           OR cohort_strategy <> NEW.strategy_version_id THEN
            RAISE EXCEPTION 'v2_opportunity_cohort_identity_mismatch' USING ERRCODE='23514';
        END IF;
        IF NEW.parent_id IS NULL THEN
            IF NEW.source_screening_episode_id IS NULL THEN
                RAISE EXCEPTION 'v2_parent_opportunity_requires_screening' USING ERRCODE='23514';
            END IF;
            SELECT cohort_id, objective_contract_id, result, audit_assigned
              INTO STRICT screening_row
              FROM trading.screening_episodes WHERE id = NEW.source_screening_episode_id;
            IF screening_row.cohort_id <> NEW.cohort_id
               OR screening_row.objective_contract_id <> NEW.objective_contract_id
               OR NOT (screening_row.result = 'SELECT' OR screening_row.audit_assigned) THEN
                RAISE EXCEPTION 'v2_parent_opportunity_screening_ineligible' USING ERRCODE='23514';
            END IF;
            IF screening_row.result <> 'SELECT' AND NEW.chain_type <> 'RESEARCH_EVAL' THEN
                RAISE EXCEPTION 'v2_audit_parent_must_be_research_eval' USING ERRCODE='23514';
            END IF;
        ELSE
            IF NEW.source_screening_episode_id IS NOT NULL THEN
                RAISE EXCEPTION 'v2_child_opportunity_cannot_bind_screening' USING ERRCODE='23514';
            END IF;
            SELECT cohort_id, chain_type, objective_contract_id, strategy_version_id
              INTO STRICT parent_row
              FROM trading.decision_opportunities WHERE id = NEW.parent_id;
            IF parent_row.cohort_id <> NEW.cohort_id
               OR parent_row.chain_type <> NEW.chain_type
               OR parent_row.objective_contract_id <> NEW.objective_contract_id
               OR parent_row.strategy_version_id <> NEW.strategy_version_id THEN
                RAISE EXCEPTION 'v2_child_opportunity_parent_identity_mismatch' USING ERRCODE='23514';
            END IF;
        END IF;
        RETURN NEW;
    END IF;
    IF OLD.opportunity_key IS DISTINCT FROM NEW.opportunity_key
       OR OLD.cohort_id IS DISTINCT FROM NEW.cohort_id
       OR OLD.parent_id IS DISTINCT FROM NEW.parent_id
       OR OLD.chain_type IS DISTINCT FROM NEW.chain_type
       OR OLD.objective_contract_id IS DISTINCT FROM NEW.objective_contract_id
       OR OLD.strategy_version_id IS DISTINCT FROM NEW.strategy_version_id
       OR OLD.source_screening_episode_id IS DISTINCT FROM NEW.source_screening_episode_id
       OR OLD.g0_manifest_hash IS DISTINCT FROM NEW.g0_manifest_hash
       OR OLD.audit_tag IS DISTINCT FROM NEW.audit_tag
       OR OLD.triggered_at IS DISTINCT FROM NEW.triggered_at
       OR OLD.created_at IS DISTINCT FROM NEW.created_at
       OR OLD.status <> 'OPEN'
       OR NEW.status NOT IN ('PRE_COMMIT_TERMINAL','ROUTED','SUPERSEDED') THEN
        RAISE EXCEPTION 'v2_opportunity_immutable' USING ERRCODE='55000';
    END IF;
    IF NEW.status = 'ROUTED' THEN
        IF NEW.disposition <> 'completed' OR NEW.terminal_reason IS NOT NULL THEN
            RAISE EXCEPTION 'v2_opportunity_terminal_shape_invalid' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.terminal_reason IS NULL OR NEW.disposition NOT IN ('rejected','failed','expired','superseded') THEN
        RAISE EXCEPTION 'v2_opportunity_terminal_shape_invalid' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_decision_opportunities_lifecycle "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.decision_opportunities "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_opportunity()"
    )

    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_episode() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    opportunity_row record;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_episode_immutable' USING ERRCODE='55000';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'DRAFT' OR NEW.drop_reason IS NOT NULL THEN
            RAISE EXCEPTION 'v2_episode_initial_state_invalid' USING ERRCODE='23514';
        END IF;
        SELECT objective_contract_id, strategy_version_id, status
          INTO STRICT opportunity_row
          FROM trading.decision_opportunities WHERE id = NEW.decision_opportunity_id;
        IF opportunity_row.objective_contract_id <> NEW.objective_contract_id
           OR opportunity_row.strategy_version_id <> NEW.strategy_version_id
           OR opportunity_row.status <> 'OPEN' THEN
            RAISE EXCEPTION 'v2_episode_opportunity_identity_mismatch' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF OLD.episode_key IS DISTINCT FROM NEW.episode_key
       OR OLD.decision_opportunity_id IS DISTINCT FROM NEW.decision_opportunity_id
       OR OLD.component_version_id IS DISTINCT FROM NEW.component_version_id
       OR OLD.strategy_version_id IS DISTINCT FROM NEW.strategy_version_id
       OR OLD.objective_contract_id IS DISTINCT FROM NEW.objective_contract_id
       OR OLD.trigger IS DISTINCT FROM NEW.trigger
       OR OLD.cutoff_at IS DISTINCT FROM NEW.cutoff_at
       OR OLD.horizon IS DISTINCT FROM NEW.horizon
       OR OLD.experiment_variant IS DISTINCT FROM NEW.experiment_variant
       OR OLD.created_at IS DISTINCT FROM NEW.created_at
       OR OLD.status <> 'DRAFT'
       OR NEW.status NOT IN ('ROUTED','PRE_COMMIT_TERMINAL') THEN
        RAISE EXCEPTION 'v2_episode_immutable' USING ERRCODE='55000';
    END IF;
    IF NEW.status = 'ROUTED' AND NEW.drop_reason IS NOT NULL THEN
        RAISE EXCEPTION 'v2_episode_terminal_shape_invalid' USING ERRCODE='23514';
    ELSIF NEW.status = 'PRE_COMMIT_TERMINAL' AND NEW.drop_reason IS NULL THEN
        RAISE EXCEPTION 'v2_episode_terminal_shape_invalid' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_forecast_episodes_lifecycle "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.forecast_episodes "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_episode()"
    )

    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_information_payload() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE payload jsonb;
BEGIN
    IF TG_TABLE_NAME = 'information_snapshots' THEN
        payload := NEW.content;
    ELSE
        payload := NEW.item_data;
    END IF;
    IF trading.v2_jsonb_has_forbidden_key(payload) THEN
        RAISE EXCEPTION 'v2_information_snapshot_forbidden_key' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    for table in ("information_snapshots", "information_snapshot_items"):
        op.execute(
            f"CREATE TRIGGER trg_{table}_payload_allowlist BEFORE INSERT ON trading.{table} "
            "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_information_payload()"
        )

    op.execute(
        r"""
CREATE FUNCTION trading.v2_guard_gate_decision() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    root_id bigint;
    screening_id bigint;
    opportunity_id bigint;
BEGIN
    IF NEW.gate IN ('G0','R0') THEN
        IF NOT EXISTS (SELECT 1 FROM trading.screening_episodes WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NEW.gate IN ('G1','G2') THEN
        IF NOT EXISTS (SELECT 1 FROM trading.decision_opportunities WHERE id = NEW.target_id) THEN
            RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
        END IF;
    ELSIF NOT EXISTS (SELECT 1 FROM trading.forecast_episodes WHERE id = NEW.target_id) THEN
        RAISE EXCEPTION 'v2_gate_target_missing' USING ERRCODE='23503';
    END IF;

    IF (NEW.gate = 'G0' AND NEW.result NOT IN ('PASS','PREDICTION_RESEARCH_ONLY'))
       OR (NEW.gate = 'R0' AND NEW.result NOT IN ('SELECT','DEFER','REJECT'))
       OR (NEW.gate IN ('G1','G2') AND NEW.result NOT IN ('PASS','FAIL'))
       OR (NEW.gate = 'R1' AND NEW.result NOT IN ('reject','shallow','standard','deep')) THEN
        RAISE EXCEPTION 'v2_gate_result_invalid' USING ERRCODE='23514';
    END IF;
    IF NEW.result IN ('PREDICTION_RESEARCH_ONLY','DEFER','REJECT','FAIL','reject')
       AND NEW.reason_code IS NULL THEN
        RAISE EXCEPTION 'v2_gate_failure_reason_required' USING ERRCODE='23514';
    END IF;

    IF NEW.gate = 'R0' AND NOT EXISTS (
        SELECT 1 FROM trading.gate_decisions gd
         WHERE gd.gate = 'G0' AND gd.target_kind = 'screening'
           AND gd.target_id = NEW.target_id AND gd.result = 'PASS'
    ) THEN
        RAISE EXCEPTION 'v2_gate_order_g0_r0' USING ERRCODE='23514';
    ELSIF NEW.gate = 'G1' THEN
        SELECT COALESCE(o.parent_id, o.id) INTO STRICT root_id
          FROM trading.decision_opportunities o WHERE o.id = NEW.target_id;
        SELECT source_screening_episode_id INTO screening_id
          FROM trading.decision_opportunities WHERE id = root_id;
        IF screening_id IS NULL OR NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'R0' AND gd.target_kind = 'screening'
               AND gd.target_id = screening_id
               AND (gd.result = 'SELECT' OR EXISTS (
                    SELECT 1 FROM trading.screening_episodes se
                     WHERE se.id = screening_id AND se.audit_assigned))
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_r0_g1' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'G2' THEN
        SELECT COALESCE(o.parent_id, o.id) INTO STRICT root_id
          FROM trading.decision_opportunities o WHERE o.id = NEW.target_id;
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
            JOIN trading.decision_opportunities prior ON prior.id = gd.target_id
             WHERE gd.gate = 'G1' AND gd.target_kind = 'opportunity' AND gd.result = 'PASS'
               AND COALESCE(prior.parent_id, prior.id) = root_id
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g1_g2' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.gate = 'R1' THEN
        SELECT decision_opportunity_id INTO STRICT opportunity_id
          FROM trading.forecast_episodes WHERE id = NEW.target_id;
        IF NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'G2' AND gd.target_kind = 'opportunity'
               AND gd.target_id = opportunity_id AND gd.result = 'PASS'
        ) THEN
            RAISE EXCEPTION 'v2_gate_order_g2_r1' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE TRIGGER trg_gate_decisions_semantics BEFORE INSERT ON trading.gate_decisions "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_gate_decision()"
    )

    op.execute(
        r"""
CREATE FUNCTION trading.v2_check_episode_spec_set() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    episode_ref bigint;
    n integer;
    episode_status text;
    opportunity_ref bigint;
    component_status text;
    episode_objective bigint;
    episode_strategy bigint;
    opportunity_objective bigint;
    opportunity_strategy bigint;
    route text;
BEGIN
    IF TG_TABLE_NAME = 'forecast_episodes' THEN
        episode_ref := NEW.id;
    ELSE
        episode_ref := NEW.episode_id;
    END IF;
    SELECT fe.status, fe.decision_opportunity_id, cv.status,
           fe.objective_contract_id, fe.strategy_version_id,
           o.objective_contract_id, o.strategy_version_id
      INTO STRICT episode_status, opportunity_ref, component_status,
                  episode_objective, episode_strategy,
                  opportunity_objective, opportunity_strategy
      FROM trading.forecast_episodes fe
      JOIN trading.forecast_component_versions cv ON cv.id = fe.component_version_id
      JOIN trading.decision_opportunities o ON o.id = fe.decision_opportunity_id
     WHERE fe.id = episode_ref;
    IF component_status <> 'active' OR episode_objective <> opportunity_objective
       OR episode_strategy <> opportunity_strategy THEN
        RAISE EXCEPTION 'v2_episode_identity_or_component_invalid' USING ERRCODE='23514';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM trading.gate_decisions gd
         WHERE gd.gate = 'G2' AND gd.target_kind = 'opportunity'
           AND gd.target_id = opportunity_ref AND gd.result = 'PASS'
    ) THEN
        RAISE EXCEPTION 'v2_episode_requires_g2_pass' USING ERRCODE='23514';
    END IF;
    SELECT count(*) INTO n FROM (
        SELECT ecs.contract_spec_id FROM trading.episode_contract_specs ecs
         WHERE ecs.episode_id = episode_ref
        EXCEPT
        SELECT fcs.contract_spec_id
          FROM trading.forecast_episodes fe
          JOIN trading.forecast_component_contract_specs fcs
            ON fcs.component_version_id = fe.component_version_id
         WHERE fe.id = episode_ref
    ) extra;
    IF n > 0 THEN RAISE EXCEPTION 'v2_episode_spec_extra' USING ERRCODE='23514'; END IF;
    SELECT count(*) INTO n FROM (
        SELECT fcs.contract_spec_id
          FROM trading.forecast_episodes fe
          JOIN trading.forecast_component_contract_specs fcs
            ON fcs.component_version_id = fe.component_version_id
         WHERE fe.id = episode_ref
        EXCEPT
        SELECT ecs.contract_spec_id FROM trading.episode_contract_specs ecs
         WHERE ecs.episode_id = episode_ref
    ) missing;
    IF n > 0 THEN RAISE EXCEPTION 'v2_episode_spec_missing' USING ERRCODE='23514'; END IF;
    IF episode_status IN ('ROUTED','PRE_COMMIT_TERMINAL') THEN
        SELECT count(*), min(route_channel) INTO n, route
          FROM trading.episode_memberships WHERE episode_id = episode_ref;
        IF n <> 1 OR NOT EXISTS (
            SELECT 1 FROM trading.gate_decisions gd
             WHERE gd.gate = 'R1' AND gd.target_kind = 'episode'
               AND gd.target_id = episode_ref AND gd.result = route
        ) THEN
            RAISE EXCEPTION 'v2_episode_r1_route_missing' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    for table, events in (
        ("forecast_episodes", "INSERT OR UPDATE"),
        ("episode_contract_specs", "INSERT OR UPDATE"),
        ("episode_memberships", "INSERT OR UPDATE"),
    ):
        op.execute(
            f"CREATE CONSTRAINT TRIGGER trg_{table}_episode_complete "
            f"AFTER {events} ON trading.{table} "
            "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
            "EXECUTE FUNCTION trading.v2_check_episode_spec_set()"
        )

def _drop_guards() -> None:
    for table in ("episode_memberships", "episode_contract_specs", "forecast_episodes"):
        op.execute(
            f"DROP TRIGGER IF EXISTS trg_{table}_episode_complete ON trading.{table}"
        )
    op.execute("DROP TRIGGER IF EXISTS trg_gate_decisions_semantics ON trading.gate_decisions")
    for table in ("information_snapshot_items", "information_snapshots"):
        op.execute(
            f"DROP TRIGGER IF EXISTS trg_{table}_payload_allowlist ON trading.{table}"
        )
    op.execute("DROP TRIGGER IF EXISTS trg_screening_episodes_semantics ON trading.screening_episodes")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_check_episode_spec_set()")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_forecast_episodes_lifecycle "
        "ON trading.forecast_episodes"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS trg_decision_opportunities_lifecycle "
        "ON trading.decision_opportunities"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS trg_universe_memberships_confirm "
        "ON trading.universe_memberships"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS trg_evaluation_cohorts_lifecycle "
        "ON trading.evaluation_cohorts"
    )
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_episode()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_opportunity()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_gate_decision()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_information_payload()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_screening_episode()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_membership_confirm()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_cohort_lifecycle()")
    for table in reversed(_IMMUTABLE_TABLES):
        op.execute(
            f"DROP TRIGGER IF EXISTS trg_{table}_immutable "
            f"ON {TRADING_SCHEMA}.{table}"
        )


def upgrade() -> None:
    """Create 12 tables + indexes + guards + policy reinforcement + episode spec-set trigger."""
    for table in _STREAM_TABLES:
        op.execute(table.create_sql)
        _create_table_indexes(table)
    _reinforce_policies()
    _create_guards()


def downgrade() -> None:
    """Drop 12 tables (reverse) + guards + undo policy reinforcement."""
    _assert_downgrade_safe()
    _drop_guards()
    for table in reversed(_STREAM_TABLES):
        op.execute(f"DROP TABLE {TRADING_SCHEMA}.{table.name}")
    _unreinforce_policies()
