"""create p1a semantics

Revision ID: b1000012
Revises: b1000011
Create Date: 2026-08-10 10:30:00

v2_0012 —— Contract & Component（WP-01C Checkpoint A）：创建 8 张 semantics 表。

- ``upgrade``：8 表 + 独立索引 + append-only guards（复用 0002 ``v2_reject_immutable_row``）；
  安装 deferred constraint trigger ``v2_check_payout_completeness``：提交时核验 payout 数量=|K_c|、
  token 均属于 snapshot market 与 exact token-version set、truth table key 集=R_c、值 0≤p≤1。
- ``downgrade``：按依赖逆序删除 8 表与 guard 函数；**不**删 0002 的 ``v2_reject_immutable_row``。
- revision DDL 是固定快照，不导入 live ORM。
"""
from dataclasses import dataclass
from typing import Sequence, Union

from alembic import op

TRADING_SCHEMA = "trading"

# revision identifiers, used by Alembic.
revision: str = "b1000012"
down_revision: Union[str, Sequence[str], None] = "b1000011"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


@dataclass(frozen=True)
class _FrozenTableSpec:
    name: str
    create_sql: str
    index_sql: tuple[str, ...] = ()
    append_only: bool = True


_SEMANTICS_TABLES = (
    _FrozenTableSpec(
        name='contract_snapshots',
        create_sql='\nCREATE TABLE trading.contract_snapshots (\n\tmarket_version_id BIGINT NOT NULL, \n\tyes_token_version_id BIGINT NOT NULL, \n\tno_token_version_id BIGINT NOT NULL, \n\tartifact_object_id BIGINT NOT NULL, \n\tquestion TEXT, \n\trules TEXT, \n\tclarification TEXT, \n\tresolution_source TEXT, \n\tcutoff_at TIMESTAMP WITH TIME ZONE, \n\ttimezone_name VARCHAR(64), \n\traw_outcome_mapping JSONB, \n\tcontent_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_contract_snapshots_content_hash UNIQUE (content_hash), \n\tCONSTRAINT ck_contract_snapshots_hash_hex CHECK (content_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_contract_snapshots_distinct_token_versions CHECK (yes_token_version_id <> no_token_version_id), \n\tCONSTRAINT fk_contract_snapshots_market_version FOREIGN KEY(market_version_id) REFERENCES trading.pm_market_versions (id), \n\tCONSTRAINT fk_contract_snapshots_yes_token_version FOREIGN KEY(yes_token_version_id) REFERENCES trading.pm_token_versions (id), \n\tCONSTRAINT fk_contract_snapshots_no_token_version FOREIGN KEY(no_token_version_id) REFERENCES trading.pm_token_versions (id), \n\tCONSTRAINT fk_contract_snapshots_artifact FOREIGN KEY(artifact_object_id) REFERENCES trading.artifact_objects (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_contract_snapshots_market_version ON trading.contract_snapshots (market_version_id)',),
    ),
    _FrozenTableSpec(
        name='contract_specs',
        create_sql='\nCREATE TABLE trading.contract_specs (\n\tcontract_key TEXT COLLATE "C" NOT NULL, \n\tversion_no INTEGER NOT NULL, \n\tsnapshot_id BIGINT NOT NULL, \n\tkc_resolution_states JSONB NOT NULL, \n\ttoken_ids JSONB NOT NULL, \n\ttoken_count INTEGER NOT NULL, \n\tstate_count INTEGER NOT NULL, \n\tcompiler_version VARCHAR(64) NOT NULL, \n\tschema_version INTEGER NOT NULL, \n\tstatus VARCHAR(32) DEFAULT \'pending\' NOT NULL, \n\tcontent_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tg1_reason VARCHAR(128), \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_contract_specs_key_version UNIQUE (contract_key, version_no), \n\tCONSTRAINT uq_contract_specs_key_hash UNIQUE (contract_key, content_hash), \n\tCONSTRAINT ck_contract_specs_status_known CHECK (status IN (\'pending\',\'pass\',\'fail\',\'superseded\')), \n\tCONSTRAINT ck_contract_specs_token_count_positive CHECK (token_count > 0), \n\tCONSTRAINT ck_contract_specs_state_count_positive CHECK (state_count > 0), \n\tCONSTRAINT ck_contract_specs_states_array CHECK (jsonb_typeof(kc_resolution_states) = \'array\'), \n\tCONSTRAINT ck_contract_specs_token_ids_object CHECK (jsonb_typeof(token_ids) = \'object\'), \n\tCONSTRAINT ck_contract_specs_hash_hex CHECK (content_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT fk_contract_specs_snapshot FOREIGN KEY(snapshot_id) REFERENCES trading.contract_snapshots (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_contract_specs_snapshot ON trading.contract_specs (snapshot_id)',),
    ),
    _FrozenTableSpec(
        name='payout_functions',
        create_sql='\nCREATE TABLE trading.payout_functions (\n\tcontract_spec_id BIGINT NOT NULL, \n\tpm_token_id BIGINT NOT NULL, \n\ttoken_version_id BIGINT NOT NULL, \n\toutcome_index INTEGER NOT NULL, \n\tfunction_ir JSONB NOT NULL, \n\ttest_vectors JSONB NOT NULL, \n\talgorithm_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tcontent_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_payout_functions_spec_token UNIQUE (contract_spec_id, pm_token_id), \n\tCONSTRAINT uq_payout_functions_spec_outcome UNIQUE (contract_spec_id, outcome_index), \n\tCONSTRAINT ck_payout_functions_ir_object CHECK (jsonb_typeof(function_ir) = \'object\'), \n\tCONSTRAINT ck_payout_functions_vectors_object CHECK (jsonb_typeof(test_vectors) = \'object\'), \n\tCONSTRAINT ck_payout_functions_outcome_nonneg CHECK (outcome_index >= 0), \n\tCONSTRAINT ck_payout_functions_alg_hash_hex CHECK (algorithm_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_payout_functions_content_hash_hex CHECK (content_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT fk_payout_functions_spec FOREIGN KEY(contract_spec_id) REFERENCES trading.contract_specs (id), \n\tCONSTRAINT fk_payout_functions_token FOREIGN KEY(pm_token_id) REFERENCES trading.pm_tokens (id), \n\tCONSTRAINT fk_payout_functions_token_version FOREIGN KEY(token_version_id) REFERENCES trading.pm_token_versions (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_payout_functions_spec ON trading.payout_functions (contract_spec_id)',),
    ),
    _FrozenTableSpec(
        name='forecast_components',
        create_sql='\nCREATE TABLE trading.forecast_components (\n\tcomponent_key TEXT COLLATE "C" NOT NULL, \n\tcost_budget NUMERIC(38, 0), \n\tdescription TEXT, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_forecast_components_key UNIQUE (component_key), \n\tCONSTRAINT ck_forecast_components_cost_budget_nonneg CHECK (cost_budget >= 0)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='world_schema_versions',
        create_sql='\nCREATE TABLE trading.world_schema_versions (\n\tcomponent_id BIGINT NOT NULL, \n\tversion_no INTEGER NOT NULL, \n\tvariables JSONB NOT NULL, \n\tdomains JSONB NOT NULL, \n\tconstraints JSONB NOT NULL, \n\tfactorization JSONB NOT NULL, \n\tworld_states JSONB NOT NULL, \n\tstate_count INTEGER NOT NULL, \n\tresolution_map JSONB NOT NULL, \n\th_c JSONB NOT NULL, \n\tstatus VARCHAR(32) DEFAULT \'draft\' NOT NULL, \n\tcontent_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tschema_version INTEGER NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_world_schema_versions_component_version UNIQUE (component_id, version_no), \n\tCONSTRAINT uq_world_schema_versions_component_hash UNIQUE (component_id, content_hash), \n\tCONSTRAINT ck_world_schema_versions_variables_object CHECK (jsonb_typeof(variables) = \'object\'), \n\tCONSTRAINT ck_world_schema_versions_domains_object CHECK (jsonb_typeof(domains) = \'object\'), \n\tCONSTRAINT ck_world_schema_versions_constraints_array CHECK (jsonb_typeof(constraints) = \'array\'), \n\tCONSTRAINT ck_world_schema_versions_factorization_object CHECK (jsonb_typeof(factorization) = \'object\'), \n\tCONSTRAINT ck_world_schema_versions_resolution_map_object CHECK (jsonb_typeof(resolution_map) = \'object\'), \n\tCONSTRAINT ck_world_schema_versions_hc_object CHECK (jsonb_typeof(h_c) = \'object\'), \n\tCONSTRAINT ck_world_schema_versions_world_states_array CHECK (jsonb_typeof(world_states) = \'array\'), \n\tCONSTRAINT ck_world_schema_versions_state_count_budget CHECK (state_count > 0 AND state_count <= 4096), \n\tCONSTRAINT ck_world_schema_versions_state_count_exact CHECK (jsonb_array_length(world_states) = state_count), \n\tCONSTRAINT ck_world_schema_versions_hash_hex CHECK (content_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT ck_world_schema_versions_status_known CHECK (status IN (\'draft\',\'active\',\'retired\')), \n\tCONSTRAINT fk_world_schema_versions_component FOREIGN KEY(component_id) REFERENCES trading.forecast_components (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='forecast_component_versions',
        create_sql='\nCREATE TABLE trading.forecast_component_versions (\n\tcomponent_id BIGINT NOT NULL, \n\tversion_no INTEGER NOT NULL, \n\tworld_schema_version_id BIGINT NOT NULL, \n\tstatus VARCHAR(32) DEFAULT \'draft\' NOT NULL, \n\teffective_from TIMESTAMP WITH TIME ZONE, \n\teffective_until TIMESTAMP WITH TIME ZONE, \n\tcontent_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tcost_budget NUMERIC(38, 0), \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_forecast_component_versions_component_version UNIQUE (component_id, version_no), \n\tCONSTRAINT uq_forecast_component_versions_component_hash UNIQUE (component_id, content_hash), \n\tCONSTRAINT ck_forecast_component_versions_status_known CHECK (status IN (\'draft\',\'active\',\'retired\')), \n\tCONSTRAINT ck_forecast_component_versions_hash_hex CHECK (content_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT fk_forecast_component_versions_component FOREIGN KEY(component_id) REFERENCES trading.forecast_components (id), \n\tCONSTRAINT fk_forecast_component_versions_schema FOREIGN KEY(world_schema_version_id) REFERENCES trading.world_schema_versions (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='forecast_component_contract_specs',
        create_sql='\nCREATE TABLE trading.forecast_component_contract_specs (\n\tcomponent_version_id BIGINT NOT NULL, \n\tcontract_spec_id BIGINT NOT NULL, \n\th_c JSONB NOT NULL, \n\ttotality_test_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_forecast_component_contract_specs_pair UNIQUE (component_version_id, contract_spec_id), \n\tCONSTRAINT ck_forecast_component_contract_specs_hc_object CHECK (jsonb_typeof(h_c) = \'object\'), \n\tCONSTRAINT ck_forecast_component_contract_specs_totality_hash CHECK (totality_test_hash ~ \'^[0-9a-f]{64}$\'), \n\tCONSTRAINT fk_forecast_component_contract_specs_cv FOREIGN KEY(component_version_id) REFERENCES trading.forecast_component_versions (id), \n\tCONSTRAINT fk_forecast_component_contract_specs_spec FOREIGN KEY(contract_spec_id) REFERENCES trading.contract_specs (id)\n)\n\n',
        index_sql=('CREATE INDEX ix_forecast_component_contract_specs_cv ON trading.forecast_component_contract_specs (component_version_id)',),
    ),
    _FrozenTableSpec(
        name='portfolio_dependency_edges',
        create_sql="\nCREATE TABLE trading.portfolio_dependency_edges (\n\tfrom_component_id BIGINT NOT NULL, \n\tto_component_id BIGINT NOT NULL, \n\trelation VARCHAR(32) NOT NULL, \n\tedge_kind VARCHAR(32) NOT NULL, \n\tedge_metadata JSONB, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_portfolio_dependency_edges_edge UNIQUE (from_component_id, to_component_id, relation), \n\tCONSTRAINT ck_portfolio_dependency_edges_canonical_order CHECK (from_component_id < to_component_id), \n\tCONSTRAINT ck_portfolio_dependency_edges_relation_known CHECK (relation IN ('stress','correlation')), \n\tCONSTRAINT ck_portfolio_dependency_edges_no_prob_identity CHECK (edge_kind NOT IN ('probability_identity','coherence')), \n\tCONSTRAINT fk_portfolio_dependency_edges_from FOREIGN KEY(from_component_id) REFERENCES trading.forecast_components (id), \n\tCONSTRAINT fk_portfolio_dependency_edges_to FOREIGN KEY(to_component_id) REFERENCES trading.forecast_components (id)\n)\n\n",
    ),
)

_PRE_WP01C_RELATIONS = (
    "artifact_objects", "artifact_lineage_edges", "archive_manifests",
    "retention_manifests", "runtime_config_versions", "strategy_objective_contracts",
    "strategy_versions", "execution_spec_versions", "capital_permission_manifests",
    "model_role_bindings", "release_manifests", "policy_type_scopes", "policy_freezes",
    "secret_vault_entries", "secret_vault_versions", "secret_access_events",
    "idempotency_claims", "transactional_outbox", "outbox_delivery_history",
    "job_completions", "pm_universe_frames", "pm_universe_frame_pages", "pm_events",
    "pm_markets", "pm_market_versions", "pm_tokens", "pm_token_versions",
    "pm_market_lifecycle_events", "pm_market_current", "pm_connection_epochs",
    "pm_source_event_batches", "pm_source_event_index", "pm_book_checkpoints",
    "pm_book_levels", "pm_book_current", "pm_quote_bindings",
)


def _assert_downgrade_safe() -> None:
    """Refuse direct 0012 downgrade before destroying unknown downstream relations."""
    allowed = ", ".join(
        f"'{name}'" for name in (*_PRE_WP01C_RELATIONS, *(t.name for t in _SEMANTICS_TABLES))
    )
    op.execute(
        f"""
DO $v2_wp01c_preflight$
DECLARE unknown_objects text;
BEGIN
    SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
      INTO unknown_objects
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'trading'
       AND c.relkind IN ('r','p','v','m','f')
       AND c.relname NOT IN ({allowed})
       AND NOT EXISTS (
           SELECT 1 FROM pg_inherits i
           JOIN pg_class p ON p.oid = i.inhparent
           JOIN pg_namespace pn ON pn.oid = p.relnamespace
           WHERE i.inhrelid = c.oid AND pn.nspname = 'trading'
             AND ((p.relname = 'outbox_delivery_history'
                   AND c.relname ~ '^outbox_delivery_history_[0-9]{{6}}$')
               OR (p.relname IN ('pm_source_event_batches','pm_source_event_index',
                                  'pm_book_checkpoints','pm_book_levels')
                   AND c.relname ~ ('^' || p.relname || '_[0-9]{{8}}$')))
       );
    IF unknown_objects IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp01c_unknown_object:%', unknown_objects USING ERRCODE='55000';
    END IF;
END $v2_wp01c_preflight$
"""
    )


def _create_table_indexes(table: _FrozenTableSpec) -> None:
    for statement in table.index_sql:
        op.execute(statement)


def _create_guards() -> None:
    for table in _SEMANTICS_TABLES:
        if table.append_only:
            op.execute(
                f"CREATE TRIGGER trg_{table.name}_immutable "
                f"BEFORE UPDATE OR DELETE ON {TRADING_SCHEMA}.{table.name} "
                "FOR EACH ROW EXECUTE FUNCTION trading.v2_reject_immutable_row()"
            )

    op.execute(
        r"""
CREATE FUNCTION trading.v2_jsonb_has_forbidden_key(payload jsonb) RETURNS boolean
LANGUAGE plpgsql IMMUTABLE STRICT AS $v2_guard$
DECLARE
    item_key text;
    item_value jsonb;
BEGIN
    IF jsonb_typeof(payload) = 'object' THEN
        FOR item_key, item_value IN SELECT key, value FROM jsonb_each(payload) LOOP
            IF lower(item_key) IN (
                'probability','odds','quote','price','edge','belief','q','u','mu',
                'expected_value','market_price','payout','forecast','prediction','prior'
            ) THEN
                RETURN true;
            END IF;
            IF jsonb_typeof(item_value) IN ('object','array')
               AND trading.v2_jsonb_has_forbidden_key(item_value) THEN
                RETURN true;
            END IF;
        END LOOP;
    ELSIF jsonb_typeof(payload) = 'array' THEN
        FOR item_value IN SELECT value FROM jsonb_array_elements(payload) LOOP
            IF jsonb_typeof(item_value) IN ('object','array')
               AND trading.v2_jsonb_has_forbidden_key(item_value) THEN
                RETURN true;
            END IF;
        END LOOP;
    END IF;
    RETURN false;
END $v2_guard$
"""
    )
    op.execute(
        r"""
CREATE FUNCTION trading.v2_check_snapshot_token_set() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    market_ref bigint;
    yes_market bigint;
    no_market bigint;
    yes_token bigint;
    no_token bigint;
BEGIN
    SELECT market_id INTO STRICT market_ref
      FROM trading.pm_market_versions WHERE id = NEW.market_version_id;
    SELECT pt.market_id, tv.token_id INTO STRICT yes_market, yes_token
      FROM trading.pm_token_versions tv
      JOIN trading.pm_tokens pt ON pt.id = tv.token_id
     WHERE tv.id = NEW.yes_token_version_id;
    SELECT pt.market_id, tv.token_id INTO STRICT no_market, no_token
      FROM trading.pm_token_versions tv
      JOIN trading.pm_tokens pt ON pt.id = tv.token_id
     WHERE tv.id = NEW.no_token_version_id;
    IF yes_market IS DISTINCT FROM market_ref OR no_market IS DISTINCT FROM market_ref
       OR yes_token = no_token THEN
        RAISE EXCEPTION 'v2_snapshot_token_set_mismatch' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER trg_contract_snapshots_token_set "
        "AFTER INSERT ON trading.contract_snapshots "
        "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
        "EXECUTE FUNCTION trading.v2_check_snapshot_token_set()"
    )

    op.execute(
        r"""
CREATE FUNCTION trading.v2_check_contract_payouts() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    spec_ref bigint;
    spec_status text;
    token_total integer;
    state_total integer;
    states jsonb;
    token_map jsonb;
    snapshot_ref bigint;
    yes_tv bigint;
    no_tv bigint;
    actual integer;
    distinct_actual integer;
    invalid integer;
    payout_row record;
    ir_key text;
    ir_value jsonb;
    payout_text text;
    payout_value numeric;
BEGIN
    IF TG_TABLE_NAME = 'contract_specs' THEN
        spec_ref := NEW.id;
    ELSE
        spec_ref := NEW.contract_spec_id;
    END IF;
    SELECT status, token_count, state_count, kc_resolution_states, token_ids, snapshot_id
      INTO STRICT spec_status, token_total, state_total, states, token_map, snapshot_ref
      FROM trading.contract_specs WHERE id = spec_ref;

    SELECT count(*), count(DISTINCT value)
      INTO actual, distinct_actual
      FROM jsonb_array_elements_text(states);
    IF actual <> state_total OR distinct_actual <> state_total OR EXISTS (
        SELECT 1 FROM jsonb_array_elements_text(states) s(value)
         WHERE value NOT IN ('YES','NO','VOID','PARTIAL','OTHER','INVALID','REFUND')
    ) THEN
        RAISE EXCEPTION 'v2_contract_resolution_states_invalid' USING ERRCODE='23514';
    END IF;
    SELECT count(*) INTO actual FROM jsonb_object_keys(token_map);
    IF actual <> token_total THEN
        RAISE EXCEPTION 'v2_contract_token_map_count_mismatch' USING ERRCODE='23514';
    END IF;
    IF EXISTS (
        SELECT 1 FROM jsonb_each(token_map) token_entry(outcome_key, token_value)
         WHERE outcome_key !~ '^(0|[1-9][0-9]*)$'
            OR jsonb_typeof(token_value) <> 'string'
            OR (token_value #>> '{}') !~ '^[1-9][0-9]*$'
    ) THEN
        RAISE EXCEPTION 'v2_contract_token_map_invalid' USING ERRCODE='23514';
    END IF;

    IF spec_status <> 'pass' THEN
        IF EXISTS (
            SELECT 1 FROM trading.payout_functions WHERE contract_spec_id = spec_ref
        ) THEN
            RAISE EXCEPTION 'v2_nonpass_spec_has_payout' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;

    SELECT yes_token_version_id, no_token_version_id
      INTO STRICT yes_tv, no_tv
      FROM trading.contract_snapshots WHERE id = snapshot_ref;
    IF token_total <> 2 THEN
        RAISE EXCEPTION 'v2_payout_token_count_mismatch:%', token_total USING ERRCODE='23514';
    END IF;
    SELECT count(*), count(DISTINCT token_version_id)
      INTO actual, distinct_actual
      FROM trading.payout_functions WHERE contract_spec_id = spec_ref;
    IF actual <> token_total OR distinct_actual <> token_total THEN
        RAISE EXCEPTION 'v2_payout_count_mismatch:% vs %', actual, token_total USING ERRCODE='23514';
    END IF;
    SELECT count(*) INTO invalid
      FROM trading.payout_functions pf
      JOIN trading.pm_token_versions tv ON tv.id = pf.token_version_id
      JOIN trading.pm_tokens pt ON pt.id = pf.pm_token_id
     WHERE pf.contract_spec_id = spec_ref
       AND (pf.token_version_id NOT IN (yes_tv, no_tv)
            OR pf.pm_token_id <> tv.token_id
            OR pf.outcome_index <> tv.outcome_index
            OR pf.outcome_index <> pt.outcome_index
            OR (token_map ->> pf.outcome_index::text)
               IS DISTINCT FROM pf.pm_token_id::text);
    IF invalid <> 0 THEN
        RAISE EXCEPTION 'v2_payout_exact_token_or_spec_map_mismatch' USING ERRCODE='23514';
    END IF;

    FOR payout_row IN
        SELECT function_ir FROM trading.payout_functions WHERE contract_spec_id = spec_ref
    LOOP
        IF EXISTS (
            SELECT 1 FROM jsonb_array_elements_text(states) s(value)
             WHERE NOT (payout_row.function_ir ? value)
        ) OR EXISTS (
            SELECT 1 FROM jsonb_object_keys(payout_row.function_ir) k(value)
             WHERE NOT (states ? value)
        ) THEN
            RAISE EXCEPTION 'v2_payout_state_set_mismatch' USING ERRCODE='23514';
        END IF;
        FOR ir_key, ir_value IN SELECT key, value FROM jsonb_each(payout_row.function_ir) LOOP
            IF jsonb_typeof(ir_value) <> 'string' THEN
                RAISE EXCEPTION 'v2_payout_not_decimal_string:%', ir_key USING ERRCODE='23514';
            END IF;
            payout_text := ir_value #>> '{}';
            IF payout_text !~ '^(0(\.[0-9]+)?|1(\.0+)?)$' THEN
                RAISE EXCEPTION 'v2_payout_not_canonical_decimal:%', ir_key USING ERRCODE='23514';
            END IF;
            payout_value := payout_text::numeric;
            IF payout_value < 0 OR payout_value > 1 THEN
                RAISE EXCEPTION 'v2_payout_out_of_range:%', ir_key USING ERRCODE='23514';
            END IF;
        END LOOP;
    END LOOP;
    RETURN NEW;
END $v2_guard$
"""
    )
    for table, events in (("contract_specs", "INSERT"), ("payout_functions", "INSERT OR UPDATE")):
        op.execute(
            f"CREATE CONSTRAINT TRIGGER trg_{table}_payout_completeness "
            f"AFTER {events} ON trading.{table} "
            "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
            "EXECUTE FUNCTION trading.v2_check_contract_payouts()"
        )

    op.execute(
        r"""
CREATE FUNCTION trading.v2_check_world_schema() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    actual integer;
    distinct_actual integer;
    world_ids jsonb;
BEGIN
    IF EXISTS (
        SELECT 1 FROM jsonb_array_elements(NEW.world_states) state(value)
         WHERE jsonb_typeof(value) IS DISTINCT FROM 'object'
            OR jsonb_typeof(value -> 'world_state_id') IS DISTINCT FROM 'string'
            OR length(value ->> 'world_state_id') = 0
            OR jsonb_typeof(value -> 'assignment') IS DISTINCT FROM 'object'
    ) THEN
        RAISE EXCEPTION 'v2_world_state_shape_invalid' USING ERRCODE='23514';
    END IF;
    IF EXISTS (
        SELECT 1
          FROM jsonb_array_elements(NEW.world_states) state(value)
          CROSS JOIN LATERAL jsonb_object_keys(state.value) AS fields(field_name)
         WHERE field_name NOT IN ('world_state_id', 'assignment')
    ) THEN
        RAISE EXCEPTION 'v2_world_state_extra_key' USING ERRCODE='23514';
    END IF;
    SELECT count(*), count(DISTINCT value ->> 'world_state_id'),
           coalesce(jsonb_object_agg(value ->> 'world_state_id', true), '{}'::jsonb)
      INTO actual, distinct_actual, world_ids
      FROM jsonb_array_elements(NEW.world_states) state(value);
    IF actual <> NEW.state_count OR distinct_actual <> NEW.state_count THEN
        RAISE EXCEPTION 'v2_world_state_cardinality_mismatch' USING ERRCODE='23514';
    END IF;
    IF trading.v2_jsonb_has_forbidden_key(NEW.variables)
       OR trading.v2_jsonb_has_forbidden_key(NEW.domains)
       OR trading.v2_jsonb_has_forbidden_key(NEW.constraints)
       OR trading.v2_jsonb_has_forbidden_key(NEW.factorization)
       OR trading.v2_jsonb_has_forbidden_key(NEW.world_states)
       OR trading.v2_jsonb_has_forbidden_key(NEW.resolution_map)
       OR trading.v2_jsonb_has_forbidden_key(NEW.h_c) THEN
        RAISE EXCEPTION 'v2_world_schema_forbidden_key' USING ERRCODE='23514';
    END IF;
    IF EXISTS (
        SELECT 1 FROM jsonb_each(NEW.resolution_map) member(spec_hash, mapping)
         WHERE jsonb_typeof(mapping) IS DISTINCT FROM 'object'
    ) OR EXISTS (
        SELECT 1 FROM jsonb_each(NEW.h_c) member(spec_id, mapping)
         WHERE jsonb_typeof(mapping) IS DISTINCT FROM 'object'
    ) THEN
        RAISE EXCEPTION 'v2_world_resolution_map_invalid' USING ERRCODE='23514';
    END IF;
    IF EXISTS (
        SELECT 1
          FROM jsonb_each(NEW.resolution_map) member(spec_hash, mapping)
          CROSS JOIN LATERAL jsonb_object_keys(world_ids) AS worlds(world_id)
         WHERE NOT (mapping ? world_id)
    ) OR EXISTS (
        SELECT 1
          FROM jsonb_each(NEW.resolution_map) member(spec_hash, mapping)
          CROSS JOIN LATERAL jsonb_object_keys(mapping) AS worlds(world_id)
         WHERE NOT (world_ids ? world_id)
    ) OR EXISTS (
        SELECT 1
          FROM jsonb_each(NEW.h_c) member(spec_id, mapping)
          CROSS JOIN LATERAL jsonb_object_keys(world_ids) AS worlds(world_id)
         WHERE NOT (mapping ? world_id)
    ) OR EXISTS (
        SELECT 1
          FROM jsonb_each(NEW.h_c) member(spec_id, mapping)
          CROSS JOIN LATERAL jsonb_object_keys(mapping) AS worlds(world_id)
         WHERE NOT (world_ids ? world_id)
    ) THEN
        RAISE EXCEPTION 'v2_world_resolution_map_not_total' USING ERRCODE='23514';
    END IF;
    IF NEW.status = 'active' AND NOT EXISTS (
        SELECT 1 FROM trading.forecast_component_versions cv
         WHERE cv.world_schema_version_id = NEW.id AND cv.status = 'active'
    ) THEN
        RAISE EXCEPTION 'v2_active_world_schema_without_component_version' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $v2_guard$
"""
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER trg_world_schema_versions_valid "
        "AFTER INSERT ON trading.world_schema_versions "
        "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
        "EXECUTE FUNCTION trading.v2_check_world_schema()"
    )

    op.execute(
        r"""
CREATE FUNCTION trading.v2_check_component_version() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
DECLARE
    cv_ref bigint;
    cv_component bigint;
    cv_status text;
    schema_component bigint;
    schema_status text;
    states jsonb;
    schema_hc jsonb;
    schema_resolution_map jsonb;
    world_ids jsonb;
    member_count integer;
    distinct_spec_hashes integer;
    aggregate_hc jsonb;
    aggregate_resolution_map jsonb;
    member_row record;
    hc_key text;
    hc_value jsonb;
    resolution_states jsonb;
BEGIN
    IF TG_TABLE_NAME = 'forecast_component_versions' THEN
        cv_ref := NEW.id;
    ELSE
        cv_ref := NEW.component_version_id;
    END IF;
    SELECT cv.component_id, cv.status, ws.component_id, ws.status, ws.world_states,
           ws.h_c, ws.resolution_map
      INTO STRICT cv_component, cv_status, schema_component, schema_status, states,
                  schema_hc, schema_resolution_map
      FROM trading.forecast_component_versions cv
      JOIN trading.world_schema_versions ws ON ws.id = cv.world_schema_version_id
     WHERE cv.id = cv_ref;
    IF cv_component <> schema_component THEN
        RAISE EXCEPTION 'v2_component_schema_identity_mismatch' USING ERRCODE='23514';
    END IF;
    IF cv_status <> 'active' THEN
        RETURN NEW;
    END IF;
    IF schema_status <> 'active' THEN
        RAISE EXCEPTION 'v2_active_component_requires_active_schema' USING ERRCODE='23514';
    END IF;
    SELECT coalesce(jsonb_object_agg(value ->> 'world_state_id', true), '{}'::jsonb)
      INTO world_ids FROM jsonb_array_elements(states) state(value);
    SELECT count(*), count(DISTINCT s.content_hash),
           jsonb_object_agg(m.contract_spec_id::text, m.h_c),
           jsonb_object_agg(s.content_hash, m.h_c)
      INTO member_count, distinct_spec_hashes, aggregate_hc, aggregate_resolution_map
      FROM trading.forecast_component_contract_specs m
      JOIN trading.contract_specs s ON s.id = m.contract_spec_id
     WHERE m.component_version_id = cv_ref;
    IF member_count = 0 THEN
        RAISE EXCEPTION 'v2_component_membership_empty' USING ERRCODE='23514';
    END IF;
    IF aggregate_hc IS DISTINCT FROM schema_hc THEN
        RAISE EXCEPTION 'v2_component_schema_hc_mismatch' USING ERRCODE='23514';
    END IF;
    IF distinct_spec_hashes <> member_count
       OR aggregate_resolution_map IS DISTINCT FROM schema_resolution_map THEN
        RAISE EXCEPTION 'v2_component_schema_resolution_map_mismatch' USING ERRCODE='23514';
    END IF;
    FOR member_row IN
        SELECT m.h_c, s.status, s.kc_resolution_states
          FROM trading.forecast_component_contract_specs m
          JOIN trading.contract_specs s ON s.id = m.contract_spec_id
         WHERE m.component_version_id = cv_ref
    LOOP
        IF member_row.status <> 'pass' THEN
            RAISE EXCEPTION 'v2_component_member_spec_not_pass' USING ERRCODE='23514';
        END IF;
        resolution_states := member_row.kc_resolution_states;
        IF EXISTS (
            SELECT 1 FROM jsonb_object_keys(world_ids) AS worlds(world_id)
             WHERE NOT (member_row.h_c ? world_id)
        ) OR EXISTS (
            SELECT 1 FROM jsonb_object_keys(member_row.h_c) AS worlds(world_id)
             WHERE NOT (world_ids ? world_id)
        ) THEN
            RAISE EXCEPTION 'v2_component_hc_not_total' USING ERRCODE='23514';
        END IF;
        FOR hc_key, hc_value IN SELECT key, value FROM jsonb_each(member_row.h_c) LOOP
            IF jsonb_typeof(hc_value) <> 'string'
               OR NOT (resolution_states ? (hc_value #>> '{}')) THEN
                RAISE EXCEPTION 'v2_component_hc_state_outside_spec:%', hc_key USING ERRCODE='23514';
            END IF;
        END LOOP;
    END LOOP;
    RETURN NEW;
END $v2_guard$
"""
    )
    for table, events in (
        ("forecast_component_versions", "INSERT"),
        ("forecast_component_contract_specs", "INSERT OR UPDATE"),
    ):
        op.execute(
            f"CREATE CONSTRAINT TRIGGER trg_{table}_component_complete "
            f"AFTER {events} ON trading.{table} "
            "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
            "EXECUTE FUNCTION trading.v2_check_component_version()"
        )

def _drop_guards() -> None:
    for table in ("forecast_component_contract_specs", "forecast_component_versions"):
        op.execute(
            f"DROP TRIGGER IF EXISTS trg_{table}_component_complete ON trading.{table}"
        )
    op.execute("DROP TRIGGER IF EXISTS trg_world_schema_versions_valid ON trading.world_schema_versions")
    for table in ("payout_functions", "contract_specs"):
        op.execute(
            f"DROP TRIGGER IF EXISTS trg_{table}_payout_completeness ON trading.{table}"
        )
    op.execute("DROP TRIGGER IF EXISTS trg_contract_snapshots_token_set ON trading.contract_snapshots")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_check_component_version()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_check_world_schema()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_check_contract_payouts()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_check_snapshot_token_set()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_jsonb_has_forbidden_key(jsonb)")
    for table in reversed(_SEMANTICS_TABLES):
        if table.append_only:
            op.execute(
                f"DROP TRIGGER IF EXISTS trg_{table.name}_immutable "
                f"ON {TRADING_SCHEMA}.{table.name}"
            )


def upgrade() -> None:
    """Create 8 semantics tables + indexes + immutable guards + deferred payout trigger."""
    for table in _SEMANTICS_TABLES:
        op.execute(table.create_sql)
        _create_table_indexes(table)
    _create_guards()


def downgrade() -> None:
    """Drop 8 tables (reverse order) + 0012-owned guard functions. 0002 的
    ``v2_reject_immutable_row`` 不删除。"""
    _assert_downgrade_safe()
    _drop_guards()
    for table in reversed(_SEMANTICS_TABLES):
        op.execute(f"DROP TABLE {TRADING_SCHEMA}.{table.name}")
