"""runtime config: model credentials + AI switch flags

Revision ID: b1000076
Revises: b1000075
Create Date: 2026-08-15 00:00:00

v2_0076 —— 后台运行时配置（用户拍板，WP-07C 之外先行落地）：

- ``upgrade``：
  - ``trading.runtime_flags``（key/value + updated_by，可变单行）
  - ``trading.runtime_flag_events``（append-only 变更审计：old/new/actor）
  - ``v2:runtime-config:view`` / ``v2:runtime-config:manage`` BUTTON 权限
    （归入 ``v2-admin`` 权限目录）+ 可见页「运行时配置」（归入 ``trading`` 菜单组，
    component ``v2/runtime-config/index``）
- ``downgrade``：先 fail-closed preflight（role_menus 绑定即拒绝），再删菜单/权限/表。

fixed literal DDL；不 import live ORM；无密钥明文。
"""
from typing import Sequence, Union

from alembic import op

revision: str = "b1000076"
down_revision: Union[str, Sequence[str], None] = "b1000075"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_PERM_DIR_SLUG = "v2-admin"
_PAGE_DIR_SLUG = "trading"
_PERM_VIEW = ("v2-runtime-config-view", "Runtime Config", "v2:runtime-config:view")
_PERM_MANAGE = ("v2-runtime-config-manage", "Runtime Config Manage", "v2:runtime-config:manage")
_PAGE = (
    "v2-page-runtime-config", "运行时配置", "/runtime-config",
    "v2/runtime-config/index", "v2:runtime-config:view", True, 16,
)
_ALL_SLUGS = (
    f"'{_PERM_VIEW[0]}', '{_PERM_MANAGE[0]}', '{_PAGE[0]}'"
)


def upgrade() -> None:
    op.execute(
        """
CREATE TABLE trading.runtime_flags (
    flag_key TEXT COLLATE "C" NOT NULL,
    flag_value TEXT NOT NULL,
    updated_by TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (flag_key)
)
"""
    )
    op.execute(
        """
CREATE TABLE trading.runtime_flag_events (
    flag_key TEXT COLLATE "C" NOT NULL,
    old_value TEXT,
    new_value TEXT,
    actor TEXT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    PRIMARY KEY (id)
)
"""
    )
    op.execute(
        "CREATE INDEX ix_runtime_flag_events_flag ON trading.runtime_flag_events (flag_key, id)"
    )
    op.execute(
        f"""
DO $v2_wp_runtime_config_menu$
DECLARE perm_dir bigint;
        page_dir bigint;
BEGIN
    IF to_regclass('public.menus') IS NULL THEN
        RETURN;
    END IF;
    SELECT id INTO perm_dir FROM public.menus WHERE slug = '{_PERM_DIR_SLUG}';
    IF perm_dir IS NULL THEN
        RAISE EXCEPTION 'v2_wp_runtime_config_parent_missing:{_PERM_DIR_SLUG}'
        USING ERRCODE='55000';
    END IF;
    SELECT id INTO page_dir FROM public.menus WHERE slug = '{_PAGE_DIR_SLUG}';
    IF page_dir IS NULL THEN
        RAISE EXCEPTION 'v2_wp_runtime_config_parent_missing:{_PAGE_DIR_SLUG}'
        USING ERRCODE='55000';
    END IF;
    INSERT INTO public.menus (parent_id, type, slug, label, path, template_path, perms,
                              is_visible, sort, status)
    SELECT perm_dir, 2, '{_PERM_VIEW[0]}', '{_PERM_VIEW[1]}', NULL, NULL,
           '{_PERM_VIEW[2]}', false, 0, 1
     WHERE NOT EXISTS (SELECT 1 FROM public.menus m WHERE m.slug = '{_PERM_VIEW[0]}');
    INSERT INTO public.menus (parent_id, type, slug, label, path, template_path, perms,
                              is_visible, sort, status)
    SELECT perm_dir, 2, '{_PERM_MANAGE[0]}', '{_PERM_MANAGE[1]}', NULL, NULL,
           '{_PERM_MANAGE[2]}', false, 0, 1
     WHERE NOT EXISTS (SELECT 1 FROM public.menus m WHERE m.slug = '{_PERM_MANAGE[0]}');
    INSERT INTO public.menus (parent_id, type, slug, label, path, template_path, perms,
                              is_visible, sort, status)
    SELECT page_dir, 1, '{_PAGE[0]}', '{_PAGE[1]}', '{_PAGE[2]}', '{_PAGE[3]}',
           '{_PAGE[4]}', {str(_PAGE[5]).lower()}, {_PAGE[6]}, 1
     WHERE NOT EXISTS (SELECT 1 FROM public.menus m WHERE m.slug = '{_PAGE[0]}');
    IF NOT EXISTS (SELECT 1 FROM public.menus WHERE slug = '{_PERM_VIEW[0]}')
       OR NOT EXISTS (SELECT 1 FROM public.menus WHERE slug = '{_PERM_MANAGE[0]}')
       OR NOT EXISTS (SELECT 1 FROM public.menus WHERE slug = '{_PAGE[0]}') THEN
        RAISE EXCEPTION 'v2_wp_runtime_config_menu_seed_failed' USING ERRCODE='55000';
    END IF;
END $v2_wp_runtime_config_menu$
"""
    )


def downgrade() -> None:
    op.execute(
        """
DO $v2_wp_runtime_config_preflight$
DECLARE missing text;
        bound_count bigint;
BEGIN
    SELECT string_agg(name, ', ' ORDER BY name)
      INTO missing
      FROM (VALUES ('runtime_flags'), ('runtime_flag_events')) AS t(name)
     WHERE to_regclass('trading.' || name) IS NULL;
    IF missing IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp_runtime_config_missing:%', missing
        USING ERRCODE='55000';
    END IF;
    IF to_regclass('public.menus') IS NOT NULL
       AND to_regclass('public.role_menus') IS NOT NULL THEN
        SELECT count(*) INTO bound_count
          FROM public.role_menus rm
          JOIN public.menus m ON m.id = rm.menu_id
         WHERE m.slug IN ({slugs});
        IF bound_count <> 0 THEN
            RAISE EXCEPTION 'v2_wp_runtime_config_menu_bound' USING ERRCODE='55000';
        END IF;
    END IF;
END $v2_wp_runtime_config_preflight$
""".format(slugs=_ALL_SLUGS)
    )
    op.execute(
        f"""
DO $v2_wp_runtime_config_menu_cleanup$
BEGIN
    IF to_regclass('public.menus') IS NOT NULL THEN
        DELETE FROM public.menus WHERE slug IN ({_ALL_SLUGS});
    END IF;
END $v2_wp_runtime_config_menu_cleanup$
"""
    )
    op.execute("DROP TABLE trading.runtime_flag_events")
    op.execute("DROP TABLE trading.runtime_flags")
