"""create p1a evidence partitions

Revision ID: b1000011
Revises: b1000010
Create Date: 2026-08-10 06:30:00

v2_0011 —— source/book evidence（WP-01B Checkpoint C）：创建 7 张 market stream 表。

- ``upgrade``：
  - 4 张证据表（``pm_source_event_batches`` / ``pm_source_event_index`` /
    ``pm_book_checkpoints`` / ``pm_book_levels``）按 ``received_at`` **日 RANGE** 分区，
    无 default partition；创建当前 UTC 日及未来 7 日分区（任务 §5.3）。
  - ``pm_connection_epochs`` 状态机 guard（CONNECTING→SYNCING→LIVE→STALE|CLOSED）；
  - ``pm_book_current`` ``observed_at`` CAS 单调；证据表与 quote binding append-only。
- ``downgrade``：按依赖逆序删除 7 张表（分区随父表删）与 0011 专属 guard 函数；
  **不**删除 0002 拥有的 ``v2_reject_immutable_row``。
- revision DDL 是固定快照，不导入 live ORM。
"""
from dataclasses import dataclass
from datetime import date, datetime, time, timezone, timedelta
from typing import Sequence, Union

from alembic import op

TRADING_SCHEMA = "trading"
# 分区预建：当前 UTC 日 + 未来 PARTITION_LOOKAHEAD_DAYS 日（任务 §5.3）
PARTITION_LOOKAHEAD_DAYS = 7

# revision identifiers, used by Alembic.
revision: str = "b1000011"
down_revision: Union[str, Sequence[str], None] = "b1000010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


@dataclass(frozen=True)
class _FrozenTableSpec:
    name: str
    create_sql: str
    index_sql: tuple[str, ...] = ()
    append_only: bool = False
    partitioned: bool = False


_STREAM_TABLES = (
    _FrozenTableSpec(
        name='pm_connection_epochs',
        create_sql='\nCREATE TABLE trading.pm_connection_epochs (\n\tshard_key TEXT COLLATE "C" NOT NULL, \n\tprovider VARCHAR(32) NOT NULL, \n\tconfig_release_id BIGINT NOT NULL, \n\tstatus VARCHAR(32) DEFAULT \'CONNECTING\' NOT NULL, \n\towner TEXT COLLATE "C", \n\tfencing_token BIGINT, \n\tstarted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tsynced_at TIMESTAMP WITH TIME ZONE, \n\tlive_at TIMESTAMP WITH TIME ZONE, \n\tstale_at TIMESTAMP WITH TIME ZONE, \n\tclosed_at TIMESTAMP WITH TIME ZONE, \n\tclosed_reason VARCHAR(128), \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_pm_connection_epochs_status_known CHECK (status IN (\'CONNECTING\',\'SYNCING\',\'LIVE\',\'STALE\',\'CLOSED\')), \n\tCONSTRAINT ck_pm_connection_epochs_provider_known CHECK (provider IN (\'gamma\',\'clob_public\',\'market_ws\')), \n\tCONSTRAINT ck_pm_connection_epochs_fencing_positive CHECK (fencing_token IS NULL OR fencing_token > 0), \n\tCONSTRAINT fk_pm_connection_epochs_release FOREIGN KEY(config_release_id) REFERENCES trading.release_manifests (id)\n)\n\n',
        index_sql=(
            'CREATE INDEX ix_pm_connection_epochs_shard ON trading.pm_connection_epochs (shard_key, provider, started_at)',
            "CREATE UNIQUE INDEX uq_pm_connection_epochs_active_shard ON trading.pm_connection_epochs (shard_key, provider) WHERE status IN ('CONNECTING','SYNCING','LIVE')",
        ),
    ),
    _FrozenTableSpec(
        name='pm_source_event_batches',
        create_sql='\nCREATE TABLE trading.pm_source_event_batches (\n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tconnection_epoch_id BIGINT NOT NULL, \n\tbatch_no INTEGER NOT NULL, \n\tfirst_receive_seq INTEGER NOT NULL, \n\tlast_receive_seq INTEGER NOT NULL, \n\tfirst_received_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tlast_received_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tevent_count INTEGER DEFAULT \'0\' NOT NULL, \n\tbatch_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tprev_batch_hash VARCHAR(64) COLLATE "C", \n\traw_artifact_id BIGINT NOT NULL, \n\traw_artifact_ref VARCHAR(64) COLLATE "C" NOT NULL, \n\treceived_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id, received_at), \n\tCONSTRAINT uq_pm_source_event_batches_epoch_batch UNIQUE (connection_epoch_id, batch_no, received_at), \n\tCONSTRAINT ck_pm_source_event_batches_batch_no_nonneg CHECK (batch_no >= 0), \n\tCONSTRAINT ck_pm_source_event_batches_event_count_nonneg CHECK (event_count >= 0), \n\tCONSTRAINT fk_pm_source_event_batches_epoch FOREIGN KEY(connection_epoch_id) REFERENCES trading.pm_connection_epochs (id), \n\tCONSTRAINT fk_pm_source_event_batches_raw_artifact FOREIGN KEY(raw_artifact_id) REFERENCES trading.artifact_objects (id)\n)\n PARTITION BY RANGE (received_at)\n\n',
        index_sql=('CREATE INDEX ix_pm_source_event_batches_epoch_seq ON trading.pm_source_event_batches (connection_epoch_id, first_receive_seq)',),
        append_only=True,
        partitioned=True,
    ),
    _FrozenTableSpec(
        name='pm_source_event_index',
        create_sql='\nCREATE TABLE trading.pm_source_event_index (\n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tbatch_id BIGINT NOT NULL, \n\treceived_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tsource VARCHAR(32) NOT NULL, \n\tkind VARCHAR(64) NOT NULL, \n\tattempt_id TEXT, \n\tendpoint TEXT, \n\tmethod VARCHAR(32), \n\thttp_status INTEGER, \n\tlatency_ms INTEGER, \n\terror_code VARCHAR(128), \n\trequest_hash VARCHAR(64) COLLATE "C", \n\tresponse_hash VARCHAR(64) COLLATE "C", \n\tretry_count INTEGER, \n\tconnection_epoch_id BIGINT, \n\tlocal_receive_seq INTEGER, \n\tprovider_time BIGINT, \n\tevent_time TIMESTAMP WITH TIME ZONE, \n\tpayload_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tbatch_ordinal INTEGER DEFAULT \'0\' NOT NULL, \n\tparse_status VARCHAR(16) DEFAULT \'parsed\' NOT NULL, \n\tparse_reason VARCHAR(128), \n\tcondition_id TEXT COLLATE "C", \n\ttoken_id TEXT COLLATE "C", \n\tgamma_market_id TEXT COLLATE "C", \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id, received_at), \n\tCONSTRAINT ck_pm_source_event_index_source_known CHECK (source IN (\'gamma\',\'clob_public\',\'market_ws\')), \n\tCONSTRAINT ck_pm_source_event_index_parse_status_known CHECK (parse_status IN (\'parsed\',\'invalid\',\'unknown\')), \n\tCONSTRAINT ck_pm_source_event_index_latency_nonneg CHECK (latency_ms IS NULL OR latency_ms >= 0), \n\tCONSTRAINT ck_pm_source_event_index_retry_nonneg CHECK (retry_count IS NULL OR retry_count >= 0), \n\tCONSTRAINT ck_pm_source_event_index_http_status_range CHECK (http_status IS NULL OR http_status BETWEEN 100 AND 599), \n\tCONSTRAINT fk_pm_source_event_index_batch FOREIGN KEY(batch_id, received_at) REFERENCES trading.pm_source_event_batches (id, received_at)\n)\n PARTITION BY RANGE (received_at)\n\n',
        index_sql=(
            'CREATE INDEX ix_pm_source_event_index_batch ON trading.pm_source_event_index (batch_id, batch_ordinal)',
            'CREATE INDEX ix_pm_source_event_index_condition_kind ON trading.pm_source_event_index (condition_id, kind, received_at)',
            'CREATE INDEX ix_pm_source_event_index_epoch_seq ON trading.pm_source_event_index (connection_epoch_id, local_receive_seq, received_at)',
            'CREATE INDEX ix_pm_source_event_index_token ON trading.pm_source_event_index (token_id, received_at, batch_id, batch_ordinal)',
        ),
        append_only=True,
        partitioned=True,
    ),
    _FrozenTableSpec(
        name='pm_book_checkpoints',
        create_sql='\nCREATE TABLE trading.pm_book_checkpoints (\n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\ttoken_id TEXT COLLATE "C" NOT NULL, \n\tconnection_epoch_id BIGINT, \n\tsource_kind VARCHAR(32) NOT NULL, \n\tbook_hash VARCHAR(64) COLLATE "C" NOT NULL, \n\tbest_bid NUMERIC(38, 12), \n\tbest_ask NUMERIC(38, 12), \n\ttick_size NUMERIC(38, 12), \n\tmin_order_size NUMERIC(38, 12), \n\tprovider_timestamp BIGINT, \n\traw_artifact_id BIGINT NOT NULL, \n\tartifact_ref VARCHAR(64) COLLATE "C", \n\tcompleteness BOOLEAN DEFAULT false NOT NULL, \n\tvalidity VARCHAR(16) DEFAULT \'VALID\' NOT NULL, \n\treceived_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id, received_at), \n\tCONSTRAINT uq_pm_book_checkpoints_identity_token UNIQUE (id, received_at, token_id), \n\tCONSTRAINT ck_pm_book_checkpoints_source_known CHECK (source_kind IN (\'ws_initial\',\'ws_delta_aggregate\',\'rest_full\',\'rest_batch\')), \n\tCONSTRAINT ck_pm_book_checkpoints_validity_known CHECK (validity IN (\'VALID\',\'STALE\',\'CROSSED\')), \n\tCONSTRAINT fk_pm_book_checkpoints_epoch FOREIGN KEY(connection_epoch_id) REFERENCES trading.pm_connection_epochs (id), \n\tCONSTRAINT fk_pm_book_checkpoints_raw_artifact FOREIGN KEY(raw_artifact_id) REFERENCES trading.artifact_objects (id)\n)\n PARTITION BY RANGE (received_at)\n\n',
        index_sql=(
            'CREATE INDEX ix_pm_book_checkpoints_epoch ON trading.pm_book_checkpoints (connection_epoch_id, received_at)',
            "CREATE INDEX ix_pm_book_checkpoints_token_valid ON trading.pm_book_checkpoints (token_id, received_at) WHERE validity = 'VALID'",
        ),
        append_only=True,
        partitioned=True,
    ),
    _FrozenTableSpec(
        name='pm_book_levels',
        create_sql="\nCREATE TABLE trading.pm_book_levels (\n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcheckpoint_id BIGINT NOT NULL, \n\treceived_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tside VARCHAR(8) NOT NULL, \n\tprice NUMERIC(38, 12) NOT NULL, \n\tsize NUMERIC(38, 12) NOT NULL, \n\tordinal INTEGER DEFAULT '0' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id, received_at), \n\tCONSTRAINT uq_pm_book_levels_checkpoint_side_price UNIQUE (checkpoint_id, side, price, received_at), \n\tCONSTRAINT ck_pm_book_levels_side_known CHECK (side IN ('bid','ask')), \n\tCONSTRAINT ck_pm_book_levels_price_positive CHECK (price > 0), \n\tCONSTRAINT ck_pm_book_levels_size_nonneg CHECK (size >= 0), \n\tCONSTRAINT fk_pm_book_levels_checkpoint FOREIGN KEY(checkpoint_id, received_at) REFERENCES trading.pm_book_checkpoints (id, received_at)\n)\n PARTITION BY RANGE (received_at)\n\n",
        index_sql=('CREATE INDEX ix_pm_book_levels_checkpoint ON trading.pm_book_levels (checkpoint_id, ordinal)',),
        append_only=True,
        partitioned=True,
    ),
    _FrozenTableSpec(
        name='pm_book_current',
        create_sql='\nCREATE TABLE trading.pm_book_current (\n\ttoken_id TEXT COLLATE "C" NOT NULL, \n\tconnection_epoch_id BIGINT, \n\tcheckpoint_id BIGINT, \n\tcheckpoint_received_at TIMESTAMP WITH TIME ZONE, \n\tbest_bid NUMERIC(38, 12), \n\tbest_ask NUMERIC(38, 12), \n\ttick_size NUMERIC(38, 12), \n\tmin_order_size NUMERIC(38, 12), \n\tdepth_hash VARCHAR(64) COLLATE "C", \n\tvalidity VARCHAR(16) DEFAULT \'SYNCING\' NOT NULL, \n\tobserved_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_pm_book_current_token UNIQUE (token_id), \n\tCONSTRAINT ck_pm_book_current_validity_known CHECK (validity IN (\'VALID\',\'STALE\',\'CROSSED\',\'SYNCING\')), \n\tCONSTRAINT ck_pm_book_current_checkpoint_pair CHECK ((checkpoint_id IS NULL) = (checkpoint_received_at IS NULL)), \n\tCONSTRAINT fk_pm_book_current_checkpoint FOREIGN KEY(checkpoint_id, checkpoint_received_at, token_id) REFERENCES trading.pm_book_checkpoints (id, received_at, token_id), \n\tCONSTRAINT fk_pm_book_current_epoch FOREIGN KEY(connection_epoch_id) REFERENCES trading.pm_connection_epochs (id)\n)\n\n',
    ),
    _FrozenTableSpec(
        name='pm_quote_bindings',
        create_sql='\nCREATE TABLE trading.pm_quote_bindings (\n\ttoken_id TEXT COLLATE "C" NOT NULL, \n\tcheckpoint_id BIGINT NOT NULL, \n\tcheckpoint_received_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tbest_bid NUMERIC(38, 12) NOT NULL, \n\tbest_ask NUMERIC(38, 12) NOT NULL, \n\tprice_convention VARCHAR(64) NOT NULL, \n\tas_of TIMESTAMP WITH TIME ZONE NOT NULL, \n\treceived_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tstaleness_policy_ref VARCHAR(64) NOT NULL, \n\tstale_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tdecision_ref TEXT COLLATE "C", \n\tid BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_pm_quote_bindings_token_checkpoint UNIQUE (token_id, checkpoint_id, checkpoint_received_at), \n\tCONSTRAINT ck_pm_quote_bindings_price_positive CHECK (best_bid > 0 AND best_ask > 0 AND best_bid <= 1 AND best_ask <= 1), \n\tCONSTRAINT ck_pm_quote_bindings_not_crossed CHECK (best_ask > best_bid), \n\tCONSTRAINT ck_pm_quote_bindings_stale_after_evidence CHECK (stale_at > as_of AND stale_at > received_at), \n\tCONSTRAINT fk_pm_quote_bindings_checkpoint FOREIGN KEY(checkpoint_id, checkpoint_received_at, token_id) REFERENCES trading.pm_book_checkpoints (id, received_at, token_id)\n)\n\n',
        index_sql=('CREATE INDEX ix_pm_quote_bindings_token ON trading.pm_quote_bindings (token_id, as_of)',),
        append_only=True,
    ),
)

_FOUNDATION_AND_MARKET_RELATIONS = (
    "artifact_objects", "artifact_lineage_edges", "archive_manifests",
    "retention_manifests", "runtime_config_versions", "strategy_objective_contracts",
    "strategy_versions", "execution_spec_versions", "capital_permission_manifests",
    "model_role_bindings", "release_manifests", "policy_type_scopes", "policy_freezes",
    "secret_vault_entries", "secret_vault_versions", "secret_access_events",
    "idempotency_claims", "transactional_outbox", "outbox_delivery_history",
    "job_completions", "pm_universe_frames", "pm_universe_frame_pages", "pm_events",
    "pm_markets", "pm_market_versions", "pm_tokens", "pm_token_versions",
    "pm_market_lifecycle_events", "pm_market_current",
)


def _assert_downgrade_safe() -> None:
    """Fail before any DROP when the milestone schema contains an unknown relation."""
    allowed = ", ".join(
        f"'{name}'"
        for name in (*_FOUNDATION_AND_MARKET_RELATIONS, *(t.name for t in _STREAM_TABLES))
    )
    daily_parents = ", ".join(
        f"'{table.name}'" for table in _STREAM_TABLES if table.partitioned
    )
    op.execute(
        f"""
DO $v2_wp01b_preflight$
DECLARE
    unknown_objects text;
BEGIN
    SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
      INTO unknown_objects
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'trading'
       AND c.relkind IN ('r', 'p', 'v', 'm', 'f')
       AND c.relname NOT IN ({allowed})
       AND NOT EXISTS (
           SELECT 1
             FROM pg_inherits inheritance
             JOIN pg_class parent ON parent.oid = inheritance.inhparent
             JOIN pg_namespace parent_ns ON parent_ns.oid = parent.relnamespace
            WHERE inheritance.inhrelid = c.oid
              AND parent_ns.nspname = 'trading'
              AND (
                   (parent.relname = 'outbox_delivery_history'
                    AND c.relname ~ '^outbox_delivery_history_[0-9]{{6}}$')
                   OR
                   (parent.relname IN ({daily_parents})
                    AND c.relname ~ ('^' || parent.relname || '_[0-9]{{8}}$'))
              )
       );
    IF unknown_objects IS NOT NULL THEN
        RAISE EXCEPTION 'v2_wp01b_unknown_object:%', unknown_objects USING ERRCODE='55000';
    END IF;
END $v2_wp01b_preflight$
"""
    )


def _day_bounds(anchor: date, offset: int):
    """anchor 日 + offset 的 [start, end) 边界（UTC）。"""
    start = datetime.combine(anchor + timedelta(days=offset), time.min, tzinfo=timezone.utc)
    end = start + timedelta(days=1)
    return start, end


def _partition_names(anchor: date, table: str):
    for offset in range(PARTITION_LOOKAHEAD_DAYS + 1):
        start, end = _day_bounds(anchor, offset)
        name = f"{table}_{start:%Y%m%d}"
        yield name, start, end


def _create_table_indexes(table: _FrozenTableSpec) -> None:
    for statement in table.index_sql:
        op.execute(statement)


def _create_partitions(anchor: date) -> None:
    for table in _STREAM_TABLES:
        if not table.partitioned:
            continue
        for name, start, end in _partition_names(anchor, table.name):
            op.execute(
                f"CREATE TABLE {TRADING_SCHEMA}.{name} PARTITION OF "
                f"{TRADING_SCHEMA}.{table.name} "
                f"FOR VALUES FROM ('{start.isoformat()}') TO ('{end.isoformat()}')"
            )


def _create_guards() -> None:
    op.execute(
        """
CREATE FUNCTION trading.v2_guard_epoch_status() RETURNS trigger
LANGUAGE plpgsql AS $v2_guard$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'v2_epoch_immutable' USING ERRCODE='55000';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'CONNECTING' THEN
            RAISE EXCEPTION 'v2_epoch_must_start_connecting' USING ERRCODE='55000';
        END IF;
        RETURN NEW;
    END IF;
    IF OLD.status = NEW.status THEN
        RAISE EXCEPTION 'v2_epoch_noop_update' USING ERRCODE='55000';
    END IF;
    IF NEW.id IS DISTINCT FROM OLD.id
       OR NEW.shard_key IS DISTINCT FROM OLD.shard_key
       OR NEW.provider IS DISTINCT FROM OLD.provider
       OR NEW.config_release_id IS DISTINCT FROM OLD.config_release_id
       OR NEW.owner IS DISTINCT FROM OLD.owner
       OR NEW.fencing_token IS DISTINCT FROM OLD.fencing_token
       OR NEW.started_at IS DISTINCT FROM OLD.started_at
       OR NEW.created_at IS DISTINCT FROM OLD.created_at
       OR (OLD.synced_at IS NOT NULL AND NEW.synced_at IS DISTINCT FROM OLD.synced_at)
       OR (OLD.live_at IS NOT NULL AND NEW.live_at IS DISTINCT FROM OLD.live_at)
       OR (OLD.stale_at IS NOT NULL AND NEW.stale_at IS DISTINCT FROM OLD.stale_at)
       OR (OLD.closed_at IS NOT NULL AND NEW.closed_at IS DISTINCT FROM OLD.closed_at) THEN
        RAISE EXCEPTION 'v2_epoch_identity_immutable' USING ERRCODE='55000';
    END IF;
    IF OLD.status = 'CONNECTING' AND NEW.status = 'SYNCING' AND NEW.synced_at IS NOT NULL THEN
        RETURN NEW;
    END IF;
    IF OLD.status = 'SYNCING' AND NEW.status = 'LIVE' AND NEW.live_at IS NOT NULL THEN
        RETURN NEW;
    END IF;
    IF OLD.status IN ('SYNCING', 'LIVE') AND NEW.status = 'STALE'
       AND NEW.stale_at IS NOT NULL THEN
        RETURN NEW;
    END IF;
    IF OLD.status IN ('CONNECTING', 'SYNCING', 'LIVE', 'STALE') AND NEW.status = 'CLOSED'
       AND NEW.closed_at IS NOT NULL THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'v2_epoch_transition_invalid:%->%', OLD.status, NEW.status
        USING ERRCODE='55000';
END $v2_guard$
"""
    )
    op.execute(
        "CREATE FUNCTION trading.v2_guard_book_current() RETURNS trigger "
        "LANGUAGE plpgsql AS $v2_guard$ "
        "BEGIN "
        "  IF TG_OP = 'UPDATE' AND NEW.observed_at < OLD.observed_at THEN "
        "    RAISE EXCEPTION 'v2_book_current_stale_overwrite' USING ERRCODE='55000'; "
        "  END IF; "
        "  RETURN NEW; "
        "END $v2_guard$"
    )
    op.execute(
        "CREATE TRIGGER trg_pm_connection_epochs_status "
        "BEFORE INSERT OR UPDATE OR DELETE ON trading.pm_connection_epochs "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_epoch_status()"
    )
    op.execute(
        "CREATE TRIGGER trg_pm_book_current_cas "
        "BEFORE UPDATE ON trading.pm_book_current "
        "FOR EACH ROW EXECUTE FUNCTION trading.v2_guard_book_current()"
    )
    for table in _STREAM_TABLES:
        if table.append_only:
            op.execute(
                f"CREATE TRIGGER trg_{table.name}_immutable "
                f"BEFORE UPDATE OR DELETE ON {TRADING_SCHEMA}.{table.name} "
                "FOR EACH ROW EXECUTE FUNCTION trading.v2_reject_immutable_row()"
            )


def _drop_guards() -> None:
    for table in _STREAM_TABLES:
        if table.append_only:
            op.execute(
                f"DROP TRIGGER IF EXISTS trg_{table.name}_immutable "
                f"ON {TRADING_SCHEMA}.{table.name}"
            )
    op.execute("DROP TRIGGER IF EXISTS trg_pm_book_current_cas ON trading.pm_book_current")
    op.execute("DROP TRIGGER IF EXISTS trg_pm_connection_epochs_status ON trading.pm_connection_epochs")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_book_current()")
    op.execute("DROP FUNCTION IF EXISTS trading.v2_guard_epoch_status()")


def upgrade() -> None:
    """Create 7 stream tables + indexes + partitions（当前日+未来 7 日）+ guards。"""
    for table in _STREAM_TABLES:
        op.execute(table.create_sql)
        _create_table_indexes(table)
    _create_partitions(datetime.now(timezone.utc).date())
    _create_guards()


def downgrade() -> None:
    """Drop 7 tables（reverse order；分区随父表删）+ 0011 专属 guard 函数。"""
    _assert_downgrade_safe()
    _drop_guards()
    for table in reversed(_STREAM_TABLES):
        op.execute(f"DROP TABLE {TRADING_SCHEMA}.{table.name}")
