"""Trading ORM 通用 mixin（WP-01A-02）。

- ``BigIntIdentityMixin``：schema-qualified ``BIGINT`` identity PK（``GENERATED BY DEFAULT``）。
- ``CreatedAtMixin`` / ``TimestampMixin``：UTC 创建/更新时间（``TIMESTAMPTZ``，server default now()）。
- ``OptimisticVersionMixin``：乐观锁 version 列，Python 与 server 初值均为 1，并启用
  SQLAlchemy optimistic locking（UPDATE 时 ``WHERE version=:old``，冲突影响行数 0）。
"""

from datetime import datetime

from sqlalchemy import BigInteger, Identity, Integer, func, text
from sqlalchemy.orm import Mapped, declared_attr, mapped_column

from app.models.base import Base
from app.models.trading.constants import TRADING_SCHEMA
from app.models.trading.types import utc_timestamp_type


class TradingBase(Base):
    """所有 trading 模型的基础：物理 schema 固定为 ``trading``。

    子类若自带 ``__table_args__``（约束/分区），必须在末尾元组元素显式
    ``{"schema": TRADING_SCHEMA}``（声明式不合并父级 table_args）。
    """

    __abstract__ = True
    __table_args__ = {"schema": TRADING_SCHEMA}


class BigIntIdentityMixin:
    """``BIGINT GENERATED BY DEFAULT AS IDENTITY`` 主键。"""

    id: Mapped[int] = mapped_column(
        BigInteger,
        Identity(always=False),
        primary_key=True,
    )


class CreatedAtMixin:
    """append-only 记录的创建时间（UTC，server default now()）。"""

    created_at: Mapped[datetime] = mapped_column(
        utc_timestamp_type(),
        nullable=False,
        server_default=func.now(),
    )


class TimestampMixin(CreatedAtMixin):
    """可变记录的创建 + 更新时间（UTC，updated_at 支持 onupdate）。"""

    updated_at: Mapped[datetime] = mapped_column(
        utc_timestamp_type(),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


class OptimisticVersionMixin:
    """乐观锁 version 列；初值 1，SQLAlchemy 自动在 UPDATE 携带 WHERE version=:old。"""

    version: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=1,
        server_default=text("1"),
    )

    @declared_attr
    def __mapper_args__(cls):
        """Bind optimistic locking to the mapped column, not a textual name."""
        return {"version_id_col": cls.version}
