from app.models.base import Base
from app.models.admin_user import AdminUser
from app.models.user import User
from app.models.setting import Setting
from app.models.admin_operation_log import AdminOperationLog
from app.models.admin_login_log import AdminLoginLog
from app.models.menu import Menu
from app.models.role import Role
from app.models.role_menu import RoleMenu
from app.models.admin_user_role import AdminUserRole
from app.models.message import Message
from app.models.file import File
# 内容模块
from app.models.article import Article
from app.models.keyword import Keyword
from app.models.article_keyword import ArticleKeyword
# SEO 模块
from app.models.publish_log import PublishLog
# 数据字典
from app.models.dict import Dict, DictItem
# 数据库备份
from app.models.db_backup import DbBackup

# V2 trading 域（显式导入全部 metadata，供 Alembic 发现；不做动态扫描）
from app.models.trading import (  # noqa: E402,F401
    ArchiveManifest,
    ArtifactLineageEdge,
    ArtifactObject,
    CapitalPermissionManifest,
    ExecutionSpecVersion,
    IdempotencyClaim,
    JobCompletion,
    ModelRoleBinding,
    OutboxDeliveryHistory,
    PMBookCheckpoint,
    PMBookCurrent,
    PMBookLevel,
    PMConnectionEpoch,
    PMEvent,
    PMEventTag,
    PMTag,
    PMMarket,
    PMMarketCurrent,
    PMMarketLifecycleEvent,
    PMMarketVersion,
    PMQuoteBinding,
    PMSourceEventBatch,
    PMSourceEventIndex,
    PMToken,
    PMTokenVersion,
    AuditSample,
    ContractSnapshot,
    ContractSpec,
    DecisionOpportunity,
    DecisionOpportunityMarket,
    EpisodeContractSpec,
    EpisodeMembership,
    EvaluationCohort,
    ForecastComponent,
    ForecastComponentContractSpec,
    ForecastComponentVersion,
    ForecastEpisode,
    GateDecision,
    InformationSnapshot,
    InformationSnapshotItem,
    PayoutFunction,
    PolicyFreeze,
    PortfolioDependencyEdge,
    ScreeningEpisode,
    UniverseMembership,
    WorldSchemaVersion,
    PolicyTypeScope,
    CoherenceCheck,
    EvidenceBundle,
    EvidenceBundleItem,
    EvidenceCoveragePolicy,
    EvidenceRevision,
    ForecastChallenge,
    ForecastInputManifest,
    ForecastLease,
    ForecastSubmission,
    PayoutProjection,
    Prior,
    AIInvocation,
    AIToolCall,
    AIValidationResult,
    ActionCandidate,
    ActionSet,
    ActionSetLeg,
    DiscrepancyReview,
    EconomicActionIntent,
    MarketRelativeDecision,
    ResolutionCashflow,
    TradeDecision,
    UnderwritingPlan,
    Execution,
    Position,
    PositionLot,
    LedgerPosting,
    LedgerTransaction,
    OperatingCostEntry,
    PUniverseFrame,
    PUniverseFramePage,
    ReleaseManifest,
    RetentionManifest,
    RuntimeConfigVersion,
    AccountReconciliation,
    AlertEvent,
    ExchangeOrder,
    ExchangeOrderAttempt,
    ExecutionAuthorizationEnvelope,
    ExchangeTrade,
    ExternalCallAttempt,
    OrderStateEvent,
    WorkflowEvent,
    SecretAccessEvent,
    SecretVaultEntry,
    SecretVaultVersion,
    AccountFundsCurrent,
    CapitalReservation,
    ExecutionLease,
    PMAccount,
    PMBalanceAllowanceSnapshot,
    StrategyObjectiveContract,
    StrategyVersion,
    TransactionalOutbox,
    AccountRiskCurrent,
    LatestChainSummary,
    OpsHealthCurrent,
    PipelineFunnelHourly,
    ProviderCostDaily,
)

__all__ = [
    "Base", "AdminUser", "User", "Setting",
    "AdminOperationLog", "AdminLoginLog",
    "Menu", "Role", "RoleMenu", "AdminUserRole",
    "Message", "File",
    "Article", "Keyword", "ArticleKeyword",
    "PublishLog",
    "Dict", "DictItem",
    "DbBackup",
    # V2 trading
    "ArtifactObject",
    "ArtifactLineageEdge",
    "ArchiveManifest",
    "RetentionManifest",
    "PUniverseFrame",
    "PUniverseFramePage",
    "PMEvent",
    "PMTag",
    "PMEventTag",
    "PMMarket",
    "PMMarketVersion",
    "PMToken",
    "PMTokenVersion",
    "PMMarketLifecycleEvent",
    "PMMarketCurrent",
    "PMConnectionEpoch",
    "PMSourceEventBatch",
    "PMSourceEventIndex",
    "PMBookCheckpoint",
    "PMBookLevel",
    "PMBookCurrent",
    "PMQuoteBinding",
    "ContractSnapshot",
    "ContractSpec",
    "PayoutFunction",
    "ForecastComponent",
    "ForecastComponentVersion",
    "ForecastComponentContractSpec",
    "WorldSchemaVersion",
    "PortfolioDependencyEdge",
    "EvaluationCohort",
    "UniverseMembership",
    "ScreeningEpisode",
    "AuditSample",
    "DecisionOpportunity",
    "DecisionOpportunityMarket",
    "ForecastEpisode",
    "EpisodeContractSpec",
    "EpisodeMembership",
    "InformationSnapshot",
    "InformationSnapshotItem",
    "GateDecision",
    "Prior",
    "EvidenceCoveragePolicy",
    "EvidenceRevision",
    "EvidenceBundle",
    "EvidenceBundleItem",
    "ForecastInputManifest",
    "ForecastSubmission",
    "PayoutProjection",
    "CoherenceCheck",
    "ForecastChallenge",
    "ForecastLease",
    "AIInvocation",
    "AIToolCall",
    "AIValidationResult",
    "MarketRelativeDecision",
    "DiscrepancyReview",
    "TradeDecision",
    "ActionCandidate",
    "ResolutionCashflow",
    "ActionSet",
    "ActionSetLeg",
    "UnderwritingPlan",
    "EconomicActionIntent",
    "Execution",
    "Position",
    "PositionLot",
    "LedgerTransaction",
    "LedgerPosting",
    "OperatingCostEntry",
    "RuntimeConfigVersion",
    "ExecutionAuthorizationEnvelope",
    "ExchangeOrder",
    "ExchangeOrderAttempt",
    "OrderStateEvent",
    "ExchangeTrade",
    "AccountReconciliation",
    "WorkflowEvent",
    "ExternalCallAttempt",
    "AlertEvent",
    "StrategyObjectiveContract",
    "StrategyVersion",
    "ModelRoleBinding",
    "ExecutionSpecVersion",
    "CapitalPermissionManifest",
    "ReleaseManifest",
    "PolicyTypeScope",
    "PolicyFreeze",
    "SecretVaultEntry",
    "SecretVaultVersion",
    "SecretAccessEvent",
    "PMAccount",
    "PMBalanceAllowanceSnapshot",
    "AccountFundsCurrent",
    "CapitalReservation",
    "ExecutionLease",
    "IdempotencyClaim",
    "TransactionalOutbox",
    "OutboxDeliveryHistory",
    "JobCompletion",
    "OpsHealthCurrent",
    "PipelineFunnelHourly",
    "AccountRiskCurrent",
    "ProviderCostDaily",
    "LatestChainSummary",
]
