"""Trading domain 纯函数包（WP-01C / WP-02 / WP-03）。

无数据库、无网络、无隐式 clock 的确定性函数（实施合同 §6）。Logic 负责编排并生成 reason code。
"""

from app.domain.trading.hashing import (
    canonical_bytes,
    canonical_hash,
    deterministic_sample,
)
from app.domain.trading.gates import assert_frozen_gate_binding
from app.domain.trading.payout import (
    apply_payout_lookup,
    validate_payout_ir,
)
from app.domain.trading.probability import (
    bernoulli_p_blind,
    expected_payout,
    normalize_q,
    payout_bounds,
    push_forward_mu,
    validate_u,
)
from app.domain.trading.rounding import (
    cash_to_share_value,
    floor_quantity,
    round_cash,
    round_price,
    round_quantity,
    shares_to_cash,
    tick_ceil,
    tick_floor,
)
from app.domain.trading.valuation import (
    CostComponents,
    DepthFill,
    ValuationResult,
    break_even_payout_probability,
    capital_days,
    depth_walk,
    edge_delay_erosion,
    expected_log_growth,
    full_cost_delta,
    robust_ev,
    roi,
    world_delta_w,
    worst_loss,
)
from app.domain.trading.portfolio import (
    CapCheck,
    LegExposure,
    cap_check,
    marginal_log_growth_delta,
    net_risk_capital,
    worst_loss_cvar,
)
from app.domain.trading.ledger import (
    ASSET_CASH,
    ASSET_TOKEN,
    Posting,
    build_buy_postings,
    build_reversal,
    imbalance,
    net_cash_flow,
    postings_balanced,
)
from app.domain.trading.scoring import (
    BERNOULLI_EPSILON,
    bernoulli_brier,
    bernoulli_log_loss,
    calibration_intercept_slope,
    cluster_bootstrap,
    delta_loss,
    exp_dec,
    expit,
    logit,
    mean_squared_payout_loss,
    multiclass_brier,
    multiclass_log_loss,
    n_eff,
    proper_loss_guard,
    round_score,
    sharpness,
    tail_loss,
)
from app.domain.trading.inference import (
    blind_to_decision_delay_erosion,
    cvar,
    drawdown,
    edge_bucket_monotonicity,
    execution_metrics,
    has_audit,
    horvitz_thompson_weight,
    ht_estimate,
    no_action_regret,
    portfolio_summary,
)

__all__ = [
    "canonical_bytes",
    "canonical_hash",
    "deterministic_sample",
    "assert_frozen_gate_binding",
    "apply_payout_lookup",
    "validate_payout_ir",
    "normalize_q",
    "validate_u",
    "push_forward_mu",
    "expected_payout",
    "payout_bounds",
    "bernoulli_p_blind",
    "round_price",
    "round_cash",
    "round_quantity",
    "floor_quantity",
    "shares_to_cash",
    "cash_to_share_value",
    "tick_floor",
    "tick_ceil",
    "CostComponents",
    "DepthFill",
    "ValuationResult",
    "depth_walk",
    "full_cost_delta",
    "world_delta_w",
    "robust_ev",
    "roi",
    "expected_log_growth",
    "worst_loss",
    "break_even_payout_probability",
    "capital_days",
    "edge_delay_erosion",
    "CapCheck",
    "LegExposure",
    "cap_check",
    "marginal_log_growth_delta",
    "net_risk_capital",
    "worst_loss_cvar",
    "ASSET_CASH",
    "ASSET_TOKEN",
    "Posting",
    "build_buy_postings",
    "build_reversal",
    "imbalance",
    "net_cash_flow",
    "postings_balanced",
    # scoring.py（P3 确定性打分）
    "BERNOULLI_EPSILON",
    "bernoulli_brier",
    "bernoulli_log_loss",
    "multiclass_brier",
    "multiclass_log_loss",
    "mean_squared_payout_loss",
    "delta_loss",
    "calibration_intercept_slope",
    "sharpness",
    "tail_loss",
    "cluster_bootstrap",
    "n_eff",
    "proper_loss_guard",
    "logit",
    "expit",
    "exp_dec",
    "round_score",
    # inference.py（P3 评价/科学推断）
    "horvitz_thompson_weight",
    "ht_estimate",
    "has_audit",
    "edge_bucket_monotonicity",
    "no_action_regret",
    "blind_to_decision_delay_erosion",
    "portfolio_summary",
    "execution_metrics",
    "drawdown",
    "cvar",
]
