"""
WP-01C v2_0012 semantics migration —— 真 PostgreSQL 集成验收（Checkpoint A §8.1）。

覆盖：literal empty / existing Base 升级、upgrade→downgrade→upgrade、固定 DDL、
metadata parity、未知对象 downgrade preflight、deferred payout completeness trigger、
append-only、payout 完整性各类 fail。
"""

import json
from datetime import datetime, timezone
from pathlib import Path

import pytest
from alembic import command, util
from alembic.config import Config
from sqlalchemy import create_engine, text
from sqlalchemy.engine import make_url
from sqlalchemy.pool import NullPool

SERVE_DIR = Path(__file__).resolve().parents[3]
ALEMBIC_DIR = SERVE_DIR / "alembic"
FIXTURE_SQL = SERVE_DIR / "tests/trading/fixtures/base_legacy_schema.sql"
V11 = "b1000011"
V12 = "b1000012"

SEMANTICS_TABLES = [
    "contract_snapshots", "contract_specs", "payout_functions", "forecast_components",
    "world_schema_versions", "forecast_component_versions", "forecast_component_contract_specs",
    "portfolio_dependency_edges",
]


def _run(cmd, revision, db_url):
    cfg = Config()
    cfg.set_main_option("script_location", str(ALEMBIC_DIR))
    engine = create_engine(db_url, poolclass=NullPool)
    conn = engine.connect()
    cfg.attributes["connection"] = conn
    try:
        cmd(cfg, revision)
    finally:
        conn.close()
        engine.dispose()


def _query(db_url, sql, params=None):
    engine = create_engine(db_url)
    try:
        with engine.connect() as c:
            return c.execute(text(sql), params or {}).fetchall()
    finally:
        engine.dispose()


def _execute(db_url, sql, params=None):
    engine = create_engine(db_url)
    try:
        with engine.connect() as c:
            c.execute(text(sql), params or {})
            c.commit()
    finally:
        engine.dispose()


def _exec_multi(db_url, statements):
    """同事务执行多条语句后一次 commit（deferred trigger 需同事务）。"""
    engine = create_engine(db_url)
    try:
        with engine.connect() as c:
            for stmt in statements:
                c.execute(text(stmt[0]), stmt[1])
            c.commit()
    finally:
        engine.dispose()


def _version(db_url):
    return _query(db_url, "SELECT version_num FROM public.alembic_version")


def _trading_tables(db_url):
    return [r[0] for r in _query(
        db_url, "SELECT tablename FROM pg_tables WHERE schemaname='trading' ORDER BY 1"
    )]


def test_literal_empty_roundtrip(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V12, url)
    assert _version(url) == [(V12,)]
    assert set(SEMANTICS_TABLES) <= set(_trading_tables(url))

    _run(command.downgrade, V11, url)
    assert _version(url) == [(V11,)]
    assert set(SEMANTICS_TABLES).isdisjoint(set(_trading_tables(url)))

    _run(command.upgrade, V12, url)
    assert _version(url) == [(V12,)]


def test_existing_base_upgrade_preserves_base(temp_pg_db):
    url = temp_pg_db.url
    # apply Base fixture at baseline
    u = make_url(url)
    import subprocess, os
    cmd = ["psql", "-q", "-v", "ON_ERROR_STOP=1"]
    if u.host:
        cmd += ["-h", u.host]
    if u.port:
        cmd += ["-p", str(u.port)]
    if u.username:
        cmd += ["-U", u.username]
    cmd += ["-d", u.database, "-f", str(FIXTURE_SQL)]
    r = subprocess.run(cmd, capture_output=True, text=True)
    assert r.returncode == 0, r.stderr[-2000:]

    _run(command.upgrade, V12, url)
    assert _version(url) == [(V12,)]
    # Base 18 表保留（含 alembic_version 共 19）
    public_tables = [r[0] for r in _query(
        url, "SELECT tablename FROM pg_tables WHERE schemaname='public' ORDER BY 1"
    )]
    assert len(public_tables) == 19
    assert "alembic_version" in public_tables


def test_metadata_compare_zero_drift_on_semantics_tables(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, "head", url)
    cfg = Config()
    cfg.set_main_option("script_location", str(ALEMBIC_DIR))
    engine = create_engine(url, poolclass=NullPool)
    conn = engine.connect()
    cfg.attributes["connection"] = conn
    try:
        command.check(cfg)
        diffs = []
    except util.AutogenerateDiffsDetected as e:
        diffs = e.diffs
    finally:
        conn.close()
        engine.dispose()
    from tests.trading.fixtures.migration_helpers import split_dynamic_diffs
    dynamic, modeled = split_dynamic_diffs(diffs)
    # modeled 表（56 张全部 trading models）零 drift
    assert modeled == [], f"modeled drift: {modeled[:3]}"
    assert len(dynamic) > 0


def _seed_payout_env(url):
    """插入 market + token + 2 token versions + artifact + snapshot 供 payout 测试。

    PASS spec 必须与完整 payout set 在同一事务提交；这里只预留 spec id 并返回
    对应 INSERT statement，避免用一个暂时不完整的已提交 spec 污染 fixture。
    """
    now = datetime.now(timezone.utc)
    _execute(url, "INSERT INTO trading.pm_markets (gamma_market_id, condition_id, active) VALUES ('m1', 'c1', true)")
    mid = _query(url, "SELECT id FROM trading.pm_markets WHERE gamma_market_id='m1'")[0][0]
    _execute(url, "INSERT INTO trading.pm_tokens (token_id, market_id, outcome_index) VALUES ('t0', :m, 0), ('t1', :m, 1)", {"m": mid})
    t0 = _query(url, "SELECT id FROM trading.pm_tokens WHERE token_id='t0'")[0][0]
    t1 = _query(url, "SELECT id FROM trading.pm_tokens WHERE token_id='t1'")[0][0]
    _execute(url, "INSERT INTO trading.pm_market_versions (market_id, version_no, observed_at, received_at, normalized_hash) VALUES (:m, 1, now(), now(), :h)", {"m": mid, "h": "a" * 64})
    mv = _query(url, "SELECT id FROM trading.pm_market_versions WHERE market_id=:m", {"m": mid})[0][0]
    _execute(url, "INSERT INTO trading.pm_token_versions (token_id, version_no, outcome_index, observed_at, received_at) VALUES (:t, 1, 0, now(), now()), (:t1, 1, 1, now(), now())", {"t": t0, "t1": t1})
    tv0 = _query(url, "SELECT id FROM trading.pm_token_versions WHERE token_id=:t", {"t": t0})[0][0]
    tv1 = _query(url, "SELECT id FROM trading.pm_token_versions WHERE token_id=:t", {"t": t1})[0][0]
    sha = "c" * 64
    _execute(url, "INSERT INTO trading.artifact_objects (sha256, original_size, stored_size, mime, compression, storage_driver, storage_version, locator) VALUES (:sha, 10, 10, 'application/json', 'none', 'local', 'cas/v1', :loc)", {"sha": sha, "loc": f"cas/v1/sha256/{sha[:2]}/{sha[2:4]}/{sha}.raw"})
    art = _query(url, "SELECT id FROM trading.artifact_objects WHERE sha256=:sha", {"sha": sha})[0][0]
    _execute(url, "INSERT INTO trading.contract_snapshots (market_version_id, yes_token_version_id, no_token_version_id, artifact_object_id, rules, resolution_source, clarification, content_hash) VALUES (:mv, :tv0, :tv1, :art, 'r', 'g', 'c', :h)", {"mv": mv, "tv0": tv0, "tv1": tv1, "art": art, "h": "b" * 64})
    snap = _query(url, "SELECT id FROM trading.contract_snapshots ORDER BY id DESC LIMIT 1")[0][0]
    spec = _query(
        url,
        "SELECT nextval(pg_get_serial_sequence('trading.contract_specs', 'id'))",
    )[0][0]
    spec_insert = (
        "INSERT INTO trading.contract_specs "
        "(id, contract_key, version_no, snapshot_id, kc_resolution_states, token_ids, "
        " token_count, state_count, compiler_version, schema_version, status, content_hash) "
        "VALUES (:id, 'c1', 1, :snap, CAST(:states AS jsonb), CAST(:toks AS jsonb), "
        "2, 2, 'lookup/v1', 1, :status, :h)",
        {
            "id": spec,
            "snap": snap,
            "states": json.dumps(["YES", "NO"]),
            "toks": json.dumps({"0": str(t0), "1": str(t1)}),
            "status": "pass",
            "h": "d" * 64,
        },
    )
    return {
        "mid": mid, "t0": t0, "t1": t1, "tv0": tv0, "tv1": tv1,
        "snap": snap, "spec": spec, "spec_insert": spec_insert,
    }


def _payout_stmt(spec, tok, token_version, outcome_index, function_ir):
    return (
        "INSERT INTO trading.payout_functions "
        "(contract_spec_id, pm_token_id, token_version_id, outcome_index, function_ir, "
        " test_vectors, algorithm_hash, content_hash) "
        "VALUES (:s, :t, :tv, :oi, CAST(:ir AS jsonb), '{}'::jsonb, :ah, :ch)",
        {
            "s": spec,
            "t": tok,
            "tv": token_version,
            "oi": outcome_index,
            "ir": json.dumps(function_ir),
            "ah": "e" * 64,
            "ch": ("f" if outcome_index == 0 else "9") * 64,
        },
    )


def test_payout_completeness_deferred_trigger(temp_pg_db):
    """deferred trigger：同事务插入完整 |K_c| 个 payout 才通过。"""
    url = temp_pg_db.url
    _run(command.upgrade, "head", url)
    env = _seed_payout_env(url)

    # 完整：同一事务 2 个 payout → commit 通过
    _exec_multi(url, [
        env["spec_insert"],
        _payout_stmt(env["spec"], env["t0"], env["tv0"], 0, {"YES": "1", "NO": "0"}),
        _payout_stmt(env["spec"], env["t1"], env["tv1"], 1, {"YES": "0", "NO": "1"}),
    ])
    assert _query(url, "SELECT count(*) FROM trading.payout_functions WHERE contract_spec_id=:s", {"s": env["spec"]})[0][0] == 2


def test_pass_spec_without_payouts_fails_commit(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, "head", url)
    env = _seed_payout_env(url)
    with pytest.raises(Exception, match="v2_payout_count_mismatch"):
        _exec_multi(url, [env["spec_insert"]])


def test_payout_must_match_spec_token_map_exactly(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, "head", url)
    env = _seed_payout_env(url)
    # Snapshot/payout rows are correct, but canonical K_c swaps the two token ids.
    env["spec_insert"][1]["toks"] = json.dumps(
        {"0": str(env["t1"]), "1": str(env["t0"])}
    )
    with pytest.raises(Exception, match="v2_payout_exact_token_or_spec_map_mismatch"):
        _exec_multi(url, [
            env["spec_insert"],
            _payout_stmt(env["spec"], env["t0"], env["tv0"], 0,
                         {"YES": "1", "NO": "0"}),
            _payout_stmt(env["spec"], env["t1"], env["tv1"], 1,
                         {"YES": "0", "NO": "1"}),
        ])


@pytest.mark.parametrize("bad_value", [1, None])
def test_payout_values_must_be_decimal_strings(temp_pg_db, bad_value):
    url = temp_pg_db.url
    _run(command.upgrade, "head", url)
    env = _seed_payout_env(url)
    with pytest.raises(Exception, match="v2_payout_not_decimal_string"):
        _exec_multi(url, [
            env["spec_insert"],
            _payout_stmt(env["spec"], env["t0"], env["tv0"], 0,
                         {"YES": bad_value, "NO": "0"}),
            _payout_stmt(env["spec"], env["t1"], env["tv1"], 1,
                         {"YES": "0", "NO": "1"}),
        ])


def _commit_pass_spec(url):
    env = _seed_payout_env(url)
    _exec_multi(url, [
        env["spec_insert"],
        _payout_stmt(env["spec"], env["t0"], env["tv0"], 0,
                     {"YES": "1", "NO": "0"}),
        _payout_stmt(env["spec"], env["t1"], env["tv1"], 1,
                     {"YES": "0", "NO": "1"}),
    ])
    return env


def _next_id(url, table):
    return _query(
        url,
        f"SELECT nextval(pg_get_serial_sequence('trading.{table}', 'id'))",
    )[0][0]


@pytest.mark.parametrize(
    ("world_states", "expected"),
    [
        (["w0"], "v2_world_state_shape_invalid"),
        ([{"world_state_id": "w0", "assignment": {}, "extra": True}],
         "v2_world_state_extra_key"),
        ([{"world_state_id": "w0", "assignment": []}],
         "v2_world_state_shape_invalid"),
        ([
            {"world_state_id": "w0", "assignment": {"x": "0"}},
            {"world_state_id": "w0", "assignment": {"x": "1"}},
        ], "v2_world_state_cardinality_mismatch"),
    ],
)
def test_world_states_require_exact_unique_assignment_objects(
    temp_pg_db, world_states, expected
):
    url = temp_pg_db.url
    _run(command.upgrade, "head", url)
    _execute(
        url,
        "INSERT INTO trading.forecast_components (component_key) VALUES ('shape')",
    )
    component = _query(
        url, "SELECT id FROM trading.forecast_components WHERE component_key='shape'"
    )[0][0]
    ids = {state["world_state_id"] for state in world_states if isinstance(state, dict)}
    nested = {world_id: "YES" for world_id in ids}
    with pytest.raises(Exception, match=expected):
        _execute(
            url,
            "INSERT INTO trading.world_schema_versions "
            "(component_id, version_no, variables, domains, constraints, factorization, "
            " world_states, state_count, resolution_map, h_c, status, content_hash, "
            " schema_version) VALUES "
            "(:c, 1, '{}'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, "
            " CAST(:states AS jsonb), :count, CAST(:resolution AS jsonb), "
            " CAST(:hc AS jsonb), 'draft', :h, 1)",
            {
                "c": component,
                "states": json.dumps(world_states),
                "count": len(world_states),
                "resolution": json.dumps({"spec-hash": nested}),
                "hc": json.dumps({"1": nested}),
                "h": "7" * 64,
            },
        )


def test_active_component_rejects_hc_value_outside_member_spec(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, "head", url)
    env = _commit_pass_spec(url)
    _execute(url, "INSERT INTO trading.forecast_components (component_key) VALUES ('hc')")
    component = _query(
        url, "SELECT id FROM trading.forecast_components WHERE component_key='hc'"
    )[0][0]
    schema_id = _next_id(url, "world_schema_versions")
    component_version = _next_id(url, "forecast_component_versions")
    member_hc = {"w0": "UNKNOWN"}
    with pytest.raises(Exception, match="v2_component_hc_state_outside_spec"):
        _exec_multi(url, [
            (
                "INSERT INTO trading.world_schema_versions "
                "(id, component_id, version_no, variables, domains, constraints, factorization, "
                " world_states, state_count, resolution_map, h_c, status, content_hash, schema_version) "
                "VALUES (:id, :c, 1, '{}'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, "
                " CAST(:states AS jsonb), 1, CAST(:resolution AS jsonb), CAST(:hc AS jsonb), "
                " 'active', :h, 1)",
                {"id": schema_id, "c": component,
                 "states": json.dumps([
                     {"world_state_id": "w0", "assignment": {"x": "0"}},
                 ]),
                 "resolution": json.dumps({"d" * 64: member_hc}),
                 "hc": json.dumps({str(env["spec"]): member_hc}), "h": "1" * 64},
            ),
            (
                "INSERT INTO trading.forecast_component_versions "
                "(id, component_id, version_no, world_schema_version_id, status, content_hash) "
                "VALUES (:id, :c, 1, :ws, 'active', :h)",
                {"id": component_version, "c": component, "ws": schema_id,
                 "h": "2" * 64},
            ),
            (
                "INSERT INTO trading.forecast_component_contract_specs "
                "(component_version_id, contract_spec_id, h_c, totality_test_hash) "
                "VALUES (:cv, :s, CAST(:hc AS jsonb), :h)",
                {"cv": component_version, "s": env["spec"],
                 "hc": json.dumps(member_hc), "h": "3" * 64},
            ),
        ])


def test_component_version_schema_component_identity_is_exact(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, "head", url)
    env = _commit_pass_spec(url)
    _execute(
        url,
        "INSERT INTO trading.forecast_components (component_key) VALUES ('schema-owner'), "
        "('version-owner')",
    )
    schema_component = _query(
        url, "SELECT id FROM trading.forecast_components WHERE component_key='schema-owner'"
    )[0][0]
    version_component = _query(
        url, "SELECT id FROM trading.forecast_components WHERE component_key='version-owner'"
    )[0][0]
    schema_id = _next_id(url, "world_schema_versions")
    component_version = _next_id(url, "forecast_component_versions")
    member_hc = {"w0": "YES"}
    with pytest.raises(Exception, match="v2_component_schema_identity_mismatch"):
        _exec_multi(url, [
            (
                "INSERT INTO trading.world_schema_versions "
                "(id, component_id, version_no, variables, domains, constraints, factorization, "
                " world_states, state_count, resolution_map, h_c, status, content_hash, schema_version) "
                "VALUES (:id, :c, 1, '{}'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, "
                " CAST(:states AS jsonb), 1, CAST(:resolution AS jsonb), CAST(:hc AS jsonb), "
                " 'active', :h, 1)",
                {"id": schema_id, "c": schema_component,
                 "states": json.dumps([
                     {"world_state_id": "w0", "assignment": {"x": "0"}},
                 ]),
                 "resolution": json.dumps({"d" * 64: member_hc}),
                 "hc": json.dumps({str(env["spec"]): member_hc}), "h": "4" * 64},
            ),
            (
                "INSERT INTO trading.forecast_component_versions "
                "(id, component_id, version_no, world_schema_version_id, status, content_hash) "
                "VALUES (:id, :c, 1, :ws, 'active', :h)",
                {"id": component_version, "c": version_component, "ws": schema_id,
                 "h": "5" * 64},
            ),
            (
                "INSERT INTO trading.forecast_component_contract_specs "
                "(component_version_id, contract_spec_id, h_c, totality_test_hash) "
                "VALUES (:cv, :s, CAST(:hc AS jsonb), :h)",
                {"cv": component_version, "s": env["spec"],
                 "hc": json.dumps(member_hc), "h": "6" * 64},
            ),
        ])


def test_payout_count_mismatch_fails_commit(temp_pg_db):
    """缺 1 个 payout → 提交时报 v2_payout_count_mismatch（deferred trigger）。"""
    url = temp_pg_db.url
    _run(command.upgrade, "head", url)
    env = _seed_payout_env(url)
    with pytest.raises(Exception, match="v2_payout_count_mismatch"):
        _exec_multi(url, [env["spec_insert"], (
            "INSERT INTO trading.payout_functions "
            "(contract_spec_id, pm_token_id, token_version_id, outcome_index, function_ir, "
            " test_vectors, algorithm_hash, content_hash) "
            "VALUES (:s, :t0, :tv0, 0, CAST(:ir AS jsonb), CAST('{}' AS jsonb), :ah, :ch)",
            {"s": env["spec"], "t0": env["t0"], "tv0": env["tv0"], "ir": json.dumps({"YES": "1", "NO": "0"}), "ah": "e" * 64, "ch": "f" * 64},
        )])


def test_payout_missing_state_fails(temp_pg_db):
    """payout key 缺 R_c → deferred trigger v2_payout_missing_state。"""
    url = temp_pg_db.url
    _run(command.upgrade, "head", url)
    env = _seed_payout_env(url)
    # 同事务 2 个 payout 都缺 NO → count=2 满足后报 missing_state
    with pytest.raises(Exception, match="v2_payout_state_set_mismatch"):
        _exec_multi(url, [
            env["spec_insert"],
            (
                "INSERT INTO trading.payout_functions "
                "(contract_spec_id, pm_token_id, token_version_id, outcome_index, function_ir, "
                " test_vectors, algorithm_hash, content_hash) "
                "VALUES (:s, :t, :tv, :oi, CAST(:ir AS jsonb), CAST('{}' AS jsonb), :ah, :ch)",
                {"s": env["spec"], "t": env["t0"], "tv": env["tv0"], "oi": 0, "ir": json.dumps({"YES": "1"}), "ah": "e" * 64, "ch": "f" * 64},
            ),
            (
                "INSERT INTO trading.payout_functions "
                "(contract_spec_id, pm_token_id, token_version_id, outcome_index, function_ir, "
                " test_vectors, algorithm_hash, content_hash) "
                "VALUES (:s, :t, :tv, :oi, CAST(:ir AS jsonb), CAST('{}' AS jsonb), :ah, :ch)",
                {"s": env["spec"], "t": env["t1"], "tv": env["tv1"], "oi": 1, "ir": json.dumps({"YES": "0"}), "ah": "e" * 64, "ch": "f" * 64},
            ),
        ])


def test_append_only_guards(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, "head", url)
    env = _seed_payout_env(url)
    env["spec_insert"][1]["status"] = "fail"
    _exec_multi(url, [env["spec_insert"]])
    with pytest.raises(Exception, match="v2_immutable_row:contract_specs"):
        _execute(url, "UPDATE trading.contract_specs SET status='fail' WHERE id=:s", {"s": env["spec"]})
    with pytest.raises(Exception, match="v2_immutable_row:contract_specs"):
        _execute(url, "DELETE FROM trading.contract_specs WHERE id=:s", {"s": env["spec"]})
    with pytest.raises(Exception, match="v2_immutable_row:contract_snapshots"):
        _execute(url, "DELETE FROM trading.contract_snapshots WHERE id=:s", {"s": env["snap"]})


def test_downgrade_fail_closed_on_unknown_object(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V12, url)
    before = set(_trading_tables(url))
    _execute(url, "CREATE TABLE trading.unknown_intruder (id integer)")
    # 需降到底（b1000001）：WP-01B 的 destructive preflight 或 0002 的 schema 非空 fail-closed
    with pytest.raises(
        Exception,
        match="v2_wp01c_unknown_object|v2_wp01b_unknown_object|v2_trading_schema_not_empty",
    ):
        _run(command.downgrade, "b1000001", url)
    assert _query(url, "SELECT to_regclass('trading.unknown_intruder') IS NOT NULL") == [(True,)]
    assert set(_trading_tables(url)) == before | {"unknown_intruder"}
    assert _version(url) == [(V12,)]
