"""WP-06 v2_0052 chain settlement migration —— 真 PostgreSQL 集成（Checkpoint B）。

覆盖：empty/existing roundtrip、4 张新表 + 2 张既有表 lineage、``alembic check`` modeled
drift=0（split_dynamic_diffs 白名单）、downgrade fail-closed（未知对象 / 非 fixture
registry / active operation / chain facts 任一整次拒绝）、registry 发布 guard、operation
状态机 CAS 触发、settlement observation COMPLETE 五元组 deferred trigger、临时库零残留。
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

import pytest
from alembic import command, util
from alembic.config import Config
from sqlalchemy import create_engine, text
from sqlalchemy.pool import NullPool

SERVE_DIR = Path(__file__).resolve().parents[3]
ALEMBIC_DIR = SERVE_DIR / "alembic"
V51 = "b1000051"
V52 = "b1000052"
HEAD_REVISION = V52

NEW_TABLES = [
    "contract_registry",
    "chain_operations",
    "chain_operation_state_history",
    "settlement_observations",
]
_LINEAGE_TABLES = ("executions", "ledger_transactions")
_LINEAGE_COLS = ("chain_operation_id",)
_NEW_TRIGGERS = (
    "trg_contract_registry_immutable",
    "trg_contract_registry_publish_check",
    "trg_chain_operations_lifecycle",
    "trg_chain_operation_state_cas",
    "trg_chain_operation_state_history_immutable",
    "trg_settlement_observations_immutable",
    "trg_settlement_observations_complete_set",
)

# 冻结 fixture registry entry content_hash（downgrade 非 fixture 校验白名单）
FIXTURE_PUSD_HASH = "05b16a969afb53ba80bb7fb179f940e3a0945e2bd61076bc5cdd1d461364b1ee"
SNAPSHOT_BLOCK = 91842167
SNAPSHOT_BLOCK_HASH = "16d35ed4cc72f20c141efcc38d8c0362d4ba95482f3aa96071e85fd06857a47f"


def _run(cmd, revision, db_url):
    cfg = Config()
    cfg.set_main_option("script_location", str(ALEMBIC_DIR))
    engine = create_engine(db_url, poolclass=NullPool)
    conn = engine.connect()
    cfg.attributes["connection"] = conn
    try:
        cmd(cfg, revision)
    finally:
        conn.close()
        engine.dispose()


def _check_diffs(db_url):
    cfg = Config()
    cfg.set_main_option("script_location", str(ALEMBIC_DIR))
    engine = create_engine(db_url, poolclass=NullPool)
    conn = engine.connect()
    cfg.attributes["connection"] = conn
    try:
        command.check(cfg)
        return []
    except util.AutogenerateDiffsDetected as e:
        return e.diffs
    finally:
        conn.close()
        engine.dispose()


def _query(db_url, sql, params=None):
    engine = create_engine(db_url)
    try:
        with engine.connect() as c:
            return c.execute(text(sql), params or {}).fetchall()
    finally:
        engine.dispose()


def _execute(db_url, sql, params=None):
    engine = create_engine(db_url)
    try:
        with engine.connect() as c:
            c.execute(text(sql), params or {})
            c.commit()
    finally:
        engine.dispose()


def _version(db_url):
    return _query(db_url, "SELECT version_num FROM public.alembic_version")


def _trading_tables(db_url):
    return [r[0] for r in _query(
        db_url, "SELECT tablename FROM pg_tables WHERE schemaname='trading' ORDER BY 1"
    )]


def _columns(db_url, table):
    return [r[0] for r in _query(
        db_url,
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_schema='trading' AND table_name=:t",
        {"t": table},
    )]


def _constraints(db_url, table):
    return [r[0] for r in _query(
        db_url,
        "SELECT conname FROM pg_constraint c "
        "JOIN pg_class t ON t.oid=c.conrelid "
        "JOIN pg_namespace n ON n.oid=t.relnamespace "
        "WHERE n.nspname='trading' AND t.relname=:t",
        {"t": table},
    )]


def _triggers(db_url, table=None):
    sql = (
        "SELECT t.tgname FROM pg_trigger t "
        "JOIN pg_class tbl ON tbl.oid=t.tgrelid "
        "JOIN pg_namespace n ON n.oid=tbl.relnamespace "
        "WHERE n.nspname='trading' AND NOT t.tgisinternal"
    )
    params = {}
    if table:
        sql += " AND tbl.relname=:t"
        params = {"t": table}
    return [r[0] for r in _query(db_url, sql, params)]


def _seed_fixture_registry(db_url, *, kind="pusd", content_hash=FIXTURE_PUSD_HASH):
    """插入 fixture pusd registry entry（address 混合大小写 EIP-55）。"""
    engine = create_engine(db_url)
    try:
        with engine.begin() as c:
            return c.execute(
                text(
                    "INSERT INTO trading.contract_registry "
                    "(registry_version, kind, version_no, chain_id, address, proxy_kind, "
                    " runtime_keccak, resolved_implementation_or_beacon, resolved_code_keccak, "
                    " snapshot_block_number, snapshot_block_hash, source_url, retrieved_at, "
                    " content_hash, status) "
                    "VALUES ('polygon-mainnet-v1', :kind, 1, 137, "
                    " '0xC011a7E12a19f7B1f670d46F03B03f3342E82DFB', 'none', "
                    " :rk, NULL, :rk, 91842167, :bh, "
                    " 'https://docs.polymarket.com/resources/contracts', now(), "
                    " :ch, 'ACTIVE') RETURNING id"
                ),
                {"kind": kind, "rk": "0x" + "a" * 64, "bh": "0x" + SNAPSHOT_BLOCK_HASH,
                 "ch": content_hash},
            ).scalar_one()
    finally:
        engine.dispose()


def _seed_operation(db_url, *, status="PREPARED"):
    """用 session_replication_role=replica 绕过深层 FK，插入一条 chain_operation。"""
    engine = create_engine(db_url)
    try:
        with engine.begin() as c:
            c.execute(text("SET LOCAL session_replication_role = replica"))
            return c.execute(
                text(
                    "INSERT INTO trading.chain_operations "
                    "(operation_key, idempotency_key, economic_hash, operation_type, "
                    " chain_id, account_id, wallet_address, condition_id, registry_version_id, "
                    " target_address, permission_ref, release_manifest_id, "
                    " capital_permission_manifest_id, fencing_token, amount_base_units, "
                    " calldata, calldata_keccak, body_hash, call_set_hash, "
                    " expected_operation_hash, preflight_hash1, preflight_hash2) "
                    "VALUES (:op, :idem, :eh, 'REDEEM', 137, 1, :wallet, :cond, 1, "
                    " :target, 'perm/v1', 900001, 900002, 1, 0, :cd, :ch, :bh, :csh, "
                    " :eoh, :p1, :p2) RETURNING id"
                ),
                {"op": status.lower() + "-op", "idem": status.lower() + "-idem",
                 "eh": "e" * 64, "wallet": "0x" + "11" * 20, "cond": "0x" + "22" * 32,
                 "target": "0xAdA100Db00Ca00073811820692005400218FcE1f",
                 "cd": "0x" + "33" * 40, "ch": "c" * 64, "bh": "b" * 64,
                 "csh": "d" * 64, "eoh": "f" * 64, "p1": "a" * 64, "p2": "b" * 64},
            ).scalar_one()
    finally:
        engine.dispose()


def test_literal_empty_roundtrip(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V52, url)
    assert _version(url) == [(V52,)]
    assert set(NEW_TABLES) <= set(_trading_tables(url))
    for table in _LINEAGE_TABLES:
        assert set(_LINEAGE_COLS) <= set(_columns(url, table))

    _run(command.downgrade, V51, url)
    assert _version(url) == [(V51,)]
    assert set(NEW_TABLES).isdisjoint(set(_trading_tables(url)))
    for table in _LINEAGE_TABLES:
        assert "chain_operation_id" not in _columns(url, table), f"lineage not removed: {table}"

    _run(command.upgrade, V52, url)
    assert _version(url) == [(V52,)]
    assert set(NEW_TABLES) <= set(_trading_tables(url))


def test_tables_constraints_triggers_and_alembic_drift(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, "head", url)
    assert _version(url) == [(HEAD_REVISION,)]

    cons = set(_constraints(url, "contract_registry"))
    for c in ("uq_contract_registry_chain_kind_version", "ck_contract_registry_kind_known",
              "ck_contract_registry_proxy_kind_known", "ck_contract_registry_chain_id"):
        assert c in cons, c
    opcons = set(_constraints(url, "chain_operations"))
    for c in ("uq_chain_operations_key", "uq_chain_operations_idempotency",
              "ck_chain_operations_status_known", "ck_chain_operations_finalized_evidence",
              "ck_chain_operations_economic_once"):
        assert c in opcons, c
    histcons = set(_constraints(url, "chain_operation_state_history"))
    assert "ck_chain_op_state_history_transition_exact" in histcons
    obscons = set(_constraints(url, "settlement_observations"))
    assert "ck_settlement_observations_source_known" in obscons

    all_trg = set(_triggers(url))
    assert set(_NEW_TRIGGERS) <= all_trg

    diffs = _check_diffs(url)
    from tests.trading.fixtures.migration_helpers import split_dynamic_diffs

    _dynamic, modeled = split_dynamic_diffs(diffs)
    assert modeled == [], f"modeled tables drift: {modeled}"


def test_downgrade_fail_closed_unknown_object(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V52, url)
    before = set(_trading_tables(url))
    _execute(url, "CREATE TABLE trading.unknown_intruder_0052 (id integer)")
    with pytest.raises(Exception, match="v2_wp06_chain_settlement_unknown_object"):
        _run(command.downgrade, V51, url)
    assert _version(url) == [(V52,)]
    _execute(url, "DROP TABLE trading.unknown_intruder_0052")
    _run(command.downgrade, V51, url)
    assert _version(url) == [(V51,)]
    assert set(NEW_TABLES).isdisjoint(set(_trading_tables(url)))


def test_downgrade_fail_closed_non_fixture_registry(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V52, url)
    _seed_fixture_registry(url, content_hash="aa" * 32)  # 非冻结 content_hash
    with pytest.raises(Exception, match="v2_wp06_chain_settlement_non_fixture_registry"):
        _run(command.downgrade, V51, url)
    assert _version(url) == [(V52,)]


def test_downgrade_fail_closed_active_operation_and_chain_facts(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V52, url)
    _seed_fixture_registry(url)
    _seed_operation(url, status="UNKNOWN")
    with pytest.raises(Exception, match="v2_wp06_chain_settlement"):
        _run(command.downgrade, V51, url)
    assert _version(url) == [(V52,)]

    # 即使 operation 为 terminal（chain fact 仍存在），downgrade 依旧整次拒绝
    engine = create_engine(url)
    try:
        with engine.begin() as c:
            c.execute(text("SET LOCAL session_replication_role = replica"))
            c.execute(
                text(
                    "UPDATE trading.chain_operations SET status='FINALIZED', "
                    "transaction_id='tx-1', transaction_hash=:th, "
                    "receipt_block_number=91842135, receipt_block_hash=:bh, "
                    "finalized_block_number=91842199, pre_balance='{}'::jsonb, "
                    "post_balance='{}'::jsonb, economic_effect_applied=true WHERE id=1"
                ),
                {"th": "0x" + "1" * 64, "bh": "0x" + "2" * 64},
            )
    finally:
        engine.dispose()
    with pytest.raises(Exception, match="v2_wp06_chain_settlement"):
        _run(command.downgrade, V51, url)

    # settlement observation 也是 chain fact，单独阻塞 downgrade
    _execute(
        url,
        "INSERT INTO trading.settlement_observations "
        "(observation_key, source_kind, condition_id, token_set, outcome_index, "
        " numerator, denominator, winner, is_50_50_outcome, redeemable, "
        " label_audit_version, as_of, received_at, raw_artifact_ref, "
        " raw_artifact_hash, content_hash, status) "
        "VALUES ('obs-downgrade', 'gamma_clob_closed', :cond2, "
        " '[\"1\",\"2\"]'::jsonb, 'YES', NULL, NULL, NULL, NULL, NULL, NULL, "
        " now(), now(), NULL, :rh, :ch, 'PENDING')",
        {"cond2": "0x" + "5" * 64, "rh": "a" * 64, "ch": "b" * 64},
    )
    with pytest.raises(Exception, match="v2_wp06_chain_settlement"):
        _run(command.downgrade, V51, url)


def test_registry_guards(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V52, url)
    _seed_fixture_registry(url)

    # append-only：UPDATE/DELETE 拒绝
    with pytest.raises(Exception, match="v2_contract_registry_immutable"):
        _execute(url, "UPDATE trading.contract_registry SET status='SUPERSEDED' WHERE kind='pusd'")
    with pytest.raises(Exception, match="v2_contract_registry_immutable"):
        _execute(url, "DELETE FROM trading.contract_registry WHERE kind='pusd'")

    # 同 chain+kind 第二个 ACTIVE → partial unique 拒绝
    engine = create_engine(url)
    try:
        with engine.begin() as c:
            c.execute(
                text(
                    "INSERT INTO trading.contract_registry "
                    "(registry_version, kind, version_no, chain_id, address, proxy_kind, "
                    " runtime_keccak, resolved_implementation_or_beacon, resolved_code_keccak, "
                    " snapshot_block_number, snapshot_block_hash, source_url, retrieved_at, "
                    " content_hash, status) "
                    "VALUES ('polygon-mainnet-v1', 'pusd', 2, 137, '0x'||repeat('7',40), 'none', "
                    " :rk, NULL, :rk, 91842167, :bh, 'u', now(), :ch, 'ACTIVE')"
                ),
                {"rk": "0x" + "b" * 64, "bh": "0x" + SNAPSHOT_BLOCK_HASH, "ch": "cc" * 32},
            )
    except Exception as exc:
        assert "uq_contract_registry_active_per_chain_kind" in str(exc), str(exc)
    else:
        pytest.fail("second ACTIVE same chain+kind must be rejected")
    finally:
        engine.dispose()

    # 未知 chain → CHECK 拒绝
    with pytest.raises(Exception, match="ck_contract_registry_chain_id"):
        _execute(
            url,
            "INSERT INTO trading.contract_registry "
            "(registry_version, kind, version_no, chain_id, address, proxy_kind, "
            " runtime_keccak, resolved_implementation_or_beacon, resolved_code_keccak, "
            " snapshot_block_number, snapshot_block_hash, source_url, retrieved_at, "
            " content_hash, status) "
            "VALUES ('polygon-mainnet-v1', 'ctf', 1, 42161, '0x4D97DCd97eC945f40cF65F87097ACe5EA0476045', "
            " 'none', '0x'||repeat('c',64), NULL, '0x'||repeat('c',64), 91842167, "
            " '0x'||:bh, 'u', now(), 'ab'||repeat('b',62), 'ACTIVE')",
            {"bh": SNAPSHOT_BLOCK_HASH},
        )


def test_operation_state_machine_cas(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V52, url)
    _seed_fixture_registry(url)
    op_id = _seed_operation(url, status="PREPARED")

    # PREPARED → SUBMITTING 合法，CAS 推进 aggregate
    _execute(
        url,
        "INSERT INTO trading.chain_operation_state_history "
        "(operation_id, sequence_no, transition_from, transition_to, event_type, "
        " event_payload, event_hash, fence_token) "
        "VALUES (:oid, 0, 'PREPARED', 'SUBMITTING', 'SUBMITTING', '{}'::jsonb, :eh, 1)",
        {"oid": op_id, "eh": "1" * 64},
    )
    status = _query(url, "SELECT status FROM trading.chain_operations WHERE id=:oid",
                    {"oid": op_id})
    assert status == [("SUBMITTING",)]

    # CAS mismatch：transition_from != current → 拒绝
    with pytest.raises(Exception, match="v2_chain_operation_cas_mismatch"):
        _execute(
            url,
            "INSERT INTO trading.chain_operation_state_history "
            "(operation_id, sequence_no, transition_from, transition_to, event_type, "
            " event_payload, event_hash, fence_token) "
            "VALUES (:oid, 1, 'PREPARED', 'UNKNOWN', 'UNKNOWN', '{}'::jsonb, :eh, 1)",
            {"oid": op_id, "eh": "2" * 64},
        )

    # fence mismatch → 拒绝
    with pytest.raises(Exception, match="v2_chain_operation_fence_mismatch"):
        _execute(
            url,
            "INSERT INTO trading.chain_operation_state_history "
            "(operation_id, sequence_no, transition_from, transition_to, event_type, "
            " event_payload, event_hash, fence_token) "
            "VALUES (:oid, 1, 'SUBMITTING', 'UNKNOWN', 'UNKNOWN', '{}'::jsonb, :eh, 99)",
            {"oid": op_id, "eh": "3" * 64},
        )

    # 非法倒退 / terminal mutation → 拒绝
    with pytest.raises(Exception, match="v2_chain_operation_transition_invalid"):
        _execute(
            url,
            "INSERT INTO trading.chain_operation_state_history "
            "(operation_id, sequence_no, transition_from, transition_to, event_type, "
            " event_payload, event_hash, fence_token) "
            "VALUES (:oid, 1, 'SUBMITTING', 'PREPARED', 'PREPARED', '{}'::jsonb, :eh, 1)",
            {"oid": op_id, "eh": "4" * 64},
        )

    # 直接 UPDATE status 走同一转移表（无 GUC 绕过）
    with pytest.raises(Exception, match="v2_chain_operation_transition_invalid"):
        _execute(url, "UPDATE trading.chain_operations SET status='FINALIZED' WHERE id=:oid",
                 {"oid": op_id})

    # SUBMITTING → UNKNOWN
    _execute(
        url,
        "INSERT INTO trading.chain_operation_state_history "
        "(operation_id, sequence_no, transition_from, transition_to, event_type, "
        " event_payload, event_hash, fence_token) "
        "VALUES (:oid, 1, 'SUBMITTING', 'UNKNOWN', 'UNKNOWN', '{}'::jsonb, :eh, 1)",
        {"oid": op_id, "eh": "5" * 64},
    )

    # UNKNOWN → FINALIZED 跳过 finality → transition invalid（必须经 RELAYER_CONFIRMED→MINED_PROVISIONAL）
    with pytest.raises(Exception, match="v2_chain_operation_transition_invalid"):
        _execute(
            url,
            "INSERT INTO trading.chain_operation_state_history "
            "(operation_id, sequence_no, transition_from, transition_to, event_type, "
            " event_payload, event_hash, fence_token) "
            "VALUES (:oid, 2, 'UNKNOWN', 'FINALIZED', 'FINALIZED', '{}'::jsonb, :eh, 1)",
            {"oid": op_id, "eh": "6" * 64},
        )


def _obs_params(kind: str, i: int) -> dict:
    """按 source kind 返回满足 pair CHECK 的字段（ctf_payout 必填 numerator/denominator 等）。"""
    return {
        "k": f"obs-{i}-{kind}", "kind": kind, "ts": '["1","2"]',
        "idx": "YES" if kind != "label_audit" else None,
        "num": "1" if kind == "ctf_payout" else None,
        "den": "1" if kind == "ctf_payout" else None,
        "win": "YES" if kind == "clob_winner_5050" else None,
        "iso": False if kind == "clob_winner_5050" else None,
        "red": True if kind == "data_api_redeemable" else None,
        "lav": "p4/v1" if kind == "label_audit" else None,
        "raw": f"raw-{i}", "rawh": f"{i:064x}", "ch": f"{i:064x}",
    }


_OBS_SQL = (
    "INSERT INTO trading.settlement_observations "
    "(observation_key, source_kind, condition_id, token_set, outcome_index, "
    " numerator, denominator, winner, is_50_50_outcome, redeemable, "
    " label_audit_version, as_of, received_at, raw_artifact_ref, "
    " raw_artifact_hash, content_hash, status) "
    "VALUES (:k, :kind, :cond, CAST(:ts AS jsonb), :idx, :num, :den, :win, :iso, "
    " :red, :lav, :asof, :asof, :raw, :rawh, :ch, :st)"
)


def test_settlement_observation_complete_set_deferred(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V52, url)
    cond = "0x" + "44" * 32

    # 只插入 2 种并标记 COMPLETE → 提交时 deferred trigger 拒绝（五元组缺失）
    engine = create_engine(url)
    try:
        with engine.begin() as c:
            for i, kind in enumerate(("gamma_clob_closed", "ctf_payout")):
                p = _obs_params(kind, i)
                c.execute(text(_OBS_SQL).bindparams(
                    cond=cond, asof=datetime.fromisoformat("2026-08-11T00:00:00Z"), st="COMPLETE", **p
                ))
    except Exception as exc:
        assert "v2_settlement_observation_complete_set_missing" in str(exc), str(exc)
    else:
        pytest.fail("COMPLETE with <5 kinds must be rejected at commit")
    finally:
        engine.dispose()

    # 完整五元组原子提交 → 通过
    engine = create_engine(url)
    try:
        with engine.begin() as c:
            for i, kind in enumerate(("gamma_clob_closed", "ctf_payout",
                                      "data_api_redeemable", "clob_winner_5050", "label_audit")):
                p = _obs_params(kind, i)
                c.execute(text(_OBS_SQL).bindparams(
                    cond=cond, asof=datetime.fromisoformat("2026-08-11T00:00:00Z"), st="COMPLETE", **p
                ))
    finally:
        engine.dispose()
    count = _query(url, "SELECT count(*) FROM trading.settlement_observations WHERE condition_id=:c",
                   {"c": cond})
    assert count == [(5,)]
