"""
WP-04 v2_0040 learning migration —— 真 PostgreSQL 集成验收（Checkpoint B）。

覆盖：14 张表 roundtrip、索引 + ``alembic check`` modeled drift=0、label 状态机
fail-closed、append-only immutable、score_target_memberships 权重/双计不变量、
promotion capital fail-closed、metric_runs lifecycle guard、G8 gate deferred 校验、
downgrade fail-closed 与未知对象拒绝。
"""

from pathlib import Path

import pytest
from alembic import command, util
from alembic.config import Config
from sqlalchemy import create_engine, text
from sqlalchemy.pool import NullPool

SERVE_DIR = Path(__file__).resolve().parents[3]
ALEMBIC_DIR = SERVE_DIR / "alembic"
V31 = "b1000031"
V40 = "b1000040"
V41 = "b1000041"
V50 = "b1000050"
V51 = "b1000051"
V52 = "b1000052"
V70 = "b1000070"
V71 = "b1000071"
HEAD_REVISION = V71

LEARNING_TABLES = [
    "resolution_labels", "resolution_clusters", "resolution_cluster_memberships",
    "score_targets", "score_target_memberships", "score_observations", "experiments",
    "experiment_variants", "challenger_variants", "metric_runs", "error_reviews",
    "ablation_runs", "promotion_decisions", "replay_runs",
]

_INDEXES = (
    "ix_resolution_labels_contract",
    "ix_resolution_cluster_memberships_contract",
    "ix_score_observations_submission",
    "ix_score_observations_target",
    "ix_score_target_memberships_target",
    "ix_metric_runs_strategy",
    "ix_metric_runs_release",
    "ix_error_reviews_metric_run",
    "ix_promotion_decisions_metric_run",
)


def _run(cmd, revision, db_url):
    cfg = Config()
    cfg.set_main_option("script_location", str(ALEMBIC_DIR))
    engine = create_engine(db_url, poolclass=NullPool)
    conn = engine.connect()
    cfg.attributes["connection"] = conn
    try:
        cmd(cfg, revision)
    finally:
        conn.close()
        engine.dispose()


def _check_diffs(db_url):
    """运行 ``alembic check``，返回 diffs 列表（不抛）。"""
    cfg = Config()
    cfg.set_main_option("script_location", str(ALEMBIC_DIR))
    engine = create_engine(db_url, poolclass=NullPool)
    conn = engine.connect()
    cfg.attributes["connection"] = conn
    try:
        command.check(cfg)
        return []
    except util.AutogenerateDiffsDetected as e:
        return e.diffs
    finally:
        conn.close()
        engine.dispose()


def _query(db_url, sql, params=None):
    engine = create_engine(db_url)
    try:
        with engine.connect() as c:
            return c.execute(text(sql), params or {}).fetchall()
    finally:
        engine.dispose()


def _execute(db_url, sql, params=None):
    engine = create_engine(db_url)
    try:
        with engine.connect() as c:
            c.execute(text(sql), params or {})
            c.commit()
    finally:
        engine.dispose()


def _insert_id(db_url, sql, params=None):
    engine = create_engine(db_url)
    try:
        with engine.begin() as c:
            return c.execute(text(sql), params or {}).scalar_one()
    finally:
        engine.dispose()


def _exec_multi(db_url, statements):
    engine = create_engine(db_url)
    try:
        with engine.connect() as c:
            for stmt in statements:
                c.execute(text(stmt[0]), stmt[1])
            c.commit()
    finally:
        engine.dispose()


def _version(db_url):
    return _query(db_url, "SELECT version_num FROM public.alembic_version")


def _trading_tables(db_url):
    return [r[0] for r in _query(
        db_url, "SELECT tablename FROM pg_tables WHERE schemaname='trading' ORDER BY 1"
    )]


def _seed_core(url, suffix="40"):
    """strategy_objective_contracts / strategy_versions / execution_spec_versions /
    capital_permission_manifests / runtime_config_versions / release_manifests。"""
    _execute(url, "INSERT INTO trading.strategy_objective_contracts (contract_key, version_no, content, schema_version, content_hash, status) VALUES (:k, 1, '{}'::jsonb, 1, :h, 'active')", {"k": f"obj-{suffix}", "h": "a" * 64})
    obj_id = _query(url, "SELECT id FROM trading.strategy_objective_contracts WHERE contract_key=:k", {"k": f"obj-{suffix}"})[0][0]
    _execute(url, "INSERT INTO trading.strategy_versions (strategy_key, version_no, content, schema_version, content_hash, status) VALUES (:k, 1, '{}'::jsonb, 1, :h, 'active')", {"k": f"strat-{suffix}", "h": "b" * 64})
    strat_id = _query(url, "SELECT id FROM trading.strategy_versions WHERE strategy_key=:k", {"k": f"strat-{suffix}"})[0][0]
    _execute(url, "INSERT INTO trading.capital_permission_manifests (name, mode, capability, limits, evaluation_capital, authorized_capital, content_hash, status) VALUES (:k, 'shadow', '{}'::jsonb, '{}'::jsonb, 0, 0, :h, 'active')", {"k": f"perm-{suffix}", "h": "c" * 64})
    cap_id = _query(url, "SELECT id FROM trading.capital_permission_manifests WHERE name=:k", {"k": f"perm-{suffix}"})[0][0]
    _execute(url, "INSERT INTO trading.runtime_config_versions (config_key, version_no, content, schema_version, content_hash, status) VALUES (:k, 1, '{}'::jsonb, 1, :h, 'active')", {"k": f"cfg-{suffix}", "h": "d" * 64})
    cfg_id = _query(url, "SELECT id FROM trading.runtime_config_versions WHERE config_key=:k", {"k": f"cfg-{suffix}"})[0][0]
    _execute(url, "INSERT INTO trading.execution_spec_versions (spec_key, version_no, content, schema_version, content_hash, status) VALUES (:k, 1, '{}'::jsonb, 1, :h, 'active')", {"k": f"exec-{suffix}", "h": "e" * 64})
    exec_id = _query(url, "SELECT id FROM trading.execution_spec_versions WHERE spec_key=:k", {"k": f"exec-{suffix}"})[0][0]
    _execute(url, "INSERT INTO trading.release_manifests (release_name, config_version_id, strategy_version_id, execution_spec_version_id, capital_permission_manifest_id, git_sha, image_digest, db_revision, total_hash, status) VALUES (:k, :cfg, :strat, :exec, :cap, 'abc', 'img', :rev, :h, 'active')", {"k": f"rel-{suffix}", "cfg": cfg_id, "strat": strat_id, "exec": exec_id, "cap": cap_id, "rev": V40, "h": "f" * 64})
    rel_id = _query(url, "SELECT id FROM trading.release_manifests WHERE release_name=:k", {"k": f"rel-{suffix}"})[0][0]
    _execute(url, "INSERT INTO trading.evaluation_cohorts (cohort_key,status,objective_contract_id,strategy_version_id,release_manifest_id,policy_hashes,seed_hash) VALUES (:k,'DRAFT',:obj,:strat,:rel,'{}'::jsonb,:h)", {"k": f"cohort-{suffix}", "obj": obj_id, "strat": strat_id, "rel": rel_id, "h": "9" * 64})
    cohort_id = _query(url, "SELECT id FROM trading.evaluation_cohorts WHERE cohort_key=:k", {"k": f"cohort-{suffix}"})[0][0]
    return {"obj": obj_id, "strat": strat_id, "rel": rel_id, "exec": exec_id, "cap": cap_id, "cohort": cohort_id}


def _seed_contract_spec(url, key="cs-40"):
    engine = create_engine(url)
    try:
        with engine.begin() as c:
            c.execute(text("SET LOCAL session_replication_role = replica"))
            cspec = c.execute(text(
                "INSERT INTO trading.contract_specs "
                "(contract_key, version_no, snapshot_id, kc_resolution_states, token_ids, "
                " token_count, state_count, compiler_version, schema_version, status, content_hash) "
                "VALUES (:k, 1, 900001, '[\"YES\"]'::jsonb, '{}'::jsonb, 1, 1, 'v1', 1, 'pass', :h) "
                "RETURNING id"
            ), {"k": key, "h": "e" * 64}).scalar_one()
            c.execute(text("SET LOCAL session_replication_role = origin"))
        return cspec
    finally:
        engine.dispose()


def _seed_token(url, market_key="m-40", token_key="t-40"):
    engine = create_engine(url)
    try:
        with engine.begin() as c:
            c.execute(text("SET LOCAL session_replication_role = replica"))
            mid = c.execute(text(
                "INSERT INTO trading.pm_markets (gamma_market_id, condition_id) "
                "VALUES (:mk, :ck) RETURNING id"
            ), {"mk": market_key, "ck": "c-" + market_key}).scalar_one()
            token = c.execute(text(
                "INSERT INTO trading.pm_tokens (token_id, market_id, outcome_index) "
                "VALUES (:tk, :m, 0) RETURNING id"
            ), {"tk": token_key, "m": mid}).scalar_one()
            c.execute(text("SET LOCAL session_replication_role = origin"))
        return token
    finally:
        engine.dispose()


def _insert_metric_run(url, env, run_key="run-40"):
    return _insert_id(
        url,
        "INSERT INTO trading.metric_runs "
        "(run_key, cohort_query_hash, strategy_version_id, release_manifest_id, cohort_id, observation_ids, observation_set_hash, label_versions, "
        " split, time_blocks, code_hash, config_hash, seed, n_market, n_episode, "
        " n_resolution_cluster, n_eff, results, ci, artifact_hash) VALUES "
        "(:k, :cqh, :sv, :rm, :cohort, '[1]'::jsonb, :osh, '{}'::jsonb, 'forward_holdout', "
        " '{\"resolution\":\"2026-08-01\"}'::jsonb, "
        " :ch, :cgh, 1, 1, 1, 1, 1.0, '{}'::jsonb, '{}'::jsonb, :ah) RETURNING id",
        {
            "k": run_key, "cqh": "a" * 64, "sv": env["strat"], "rm": env["rel"],
            "cohort": env["cohort"], "osh": "8" * 64,
            "ch": "b" * 64, "cgh": "c" * 64, "ah": "d" * 64,
        },
    )


def test_literal_empty_roundtrip(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V40, url)
    assert _version(url) == [(V40,)]
    assert set(LEARNING_TABLES) <= set(_trading_tables(url))

    _run(command.downgrade, V31, url)
    assert _version(url) == [(V31,)]
    assert set(LEARNING_TABLES).isdisjoint(set(_trading_tables(url)))

    _run(command.upgrade, V40, url)
    assert _version(url) == [(V40,)]


def test_tables_indexes_and_alembic_drift(temp_pg_db):
    url = temp_pg_db.url
    # alembic check 要求目标库必须在 head（b1000041）才能 autogenerate diff；
    # 0040 表/索引在 head 库中必须仍存在且零 modeled drift。
    _run(command.upgrade, "head", url)
    assert _version(url) == [(HEAD_REVISION,)]
    tables = set(_trading_tables(url))
    assert set(LEARNING_TABLES) <= tables
    for idx in _INDEXES:
        assert _query(url, "SELECT to_regclass('trading.%s') IS NOT NULL" % idx) == [(True,)], idx

    diffs = _check_diffs(url)
    from tests.trading.fixtures.migration_helpers import split_dynamic_diffs

    _dynamic, modeled = split_dynamic_diffs(diffs)
    # 0040 无新分区；dynamic 可能为空（不写死），modeled 必须零 drift。
    assert modeled == [], f"modeled tables drift: {modeled}"


def test_label_state_machine_fail_closed(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V40, url)
    cs = _seed_contract_spec(url, "cs-label-3")

    # 合法首版必须 pending
    v1 = _insert_id(
        url,
        "INSERT INTO trading.resolution_labels (contract_spec_id, label_key, version_no, state, policy_code_hash) "
        "VALUES (:cs, 'lk-a', 1, 'pending', :h) RETURNING id",
        {"cs": cs, "h": "a" * 64},
    )
    assert _query(url, "SELECT state FROM trading.resolution_labels WHERE id=:id", {"id": v1}) == [("pending",)]

    # pending→final_admissible（跳过 provisional）→ 拒
    with pytest.raises(Exception, match="v2_label_(?:transition_invalid|terminal_evidence_incomplete)"):
        _execute(
            url,
            "INSERT INTO trading.resolution_labels (contract_spec_id, label_key, version_no, state, policy_code_hash, supersedes_id, resolution_state) "
            "VALUES (:cs, 'lk-a', 2, 'final_admissible', :h, :sup, 'YES')",
            {"cs": cs, "h": "b" * 64, "sup": v1},
        )

    # final_excluded 无 exclusion_reason → 拒（CHECK）
    with pytest.raises(Exception, match="(?:ck_resolution_labels_excluded_reason|v2_label_terminal_evidence_incomplete)"):
        _execute(
            url,
            "INSERT INTO trading.resolution_labels (contract_spec_id, label_key, version_no, state, policy_code_hash) "
            "VALUES (:cs, 'lk-b', 1, 'final_excluded', :h)",
            {"cs": cs, "h": "c" * 64},
        )

    # final_admissible 有 exclusion_reason → 拒（CHECK）
    with pytest.raises(Exception, match="(?:ck_resolution_labels_admissible_shape|v2_label_terminal_evidence_incomplete)"):
        _execute(
            url,
            "INSERT INTO trading.resolution_labels (contract_spec_id, label_key, version_no, state, policy_code_hash, exclusion_reason) "
            "VALUES (:cs, 'lk-c', 1, 'final_admissible', :h, 'x')",
            {"cs": cs, "h": "d" * 64},
        )

    # supersede 跨 contract → 拒
    cs2 = _seed_contract_spec(url, "cs-label-3b")
    with pytest.raises(Exception, match="v2_label_supersedes_cross_contract"):
        _execute(
            url,
            "INSERT INTO trading.resolution_labels (contract_spec_id, label_key, version_no, state, policy_code_hash, supersedes_id) "
            "VALUES (:cs, 'lk-d', 2, 'provisional', :h, :sup)",
            {"cs": cs2, "h": "e" * 64, "sup": v1},
        )

    # supersede version 不连续 → 拒
    with pytest.raises(Exception, match="v2_label_supersedes_version_gap"):
        _execute(
            url,
            "INSERT INTO trading.resolution_labels (contract_spec_id, label_key, version_no, state, policy_code_hash, supersedes_id) "
            "VALUES (:cs, 'lk-a', 3, 'provisional', :h, :sup)",
            {"cs": cs, "h": "f" * 64, "sup": v1},
        )

    # pending→provisional 合法；缺证据的 terminal revision 必须 fail closed。
    first = _insert_id(url, "INSERT INTO trading.resolution_labels (contract_spec_id,label_key,version_no,state,policy_code_hash) VALUES (:cs,'lk-e',1,'pending',:h) RETURNING id", {"cs": cs, "h": "1" * 64})
    provisional = _insert_id(url, "INSERT INTO trading.resolution_labels (contract_spec_id,label_key,version_no,state,policy_code_hash,supersedes_id) VALUES (:cs,'lk-e',2,'provisional',:h,:sup) RETURNING id", {"cs": cs, "h": "2" * 64, "sup": first})
    with pytest.raises(Exception, match="v2_label_terminal_evidence_incomplete"):
        _execute(url, "INSERT INTO trading.resolution_labels (contract_spec_id,label_key,version_no,state,resolution_state,policy_code_hash,supersedes_id) VALUES (:cs,'lk-e',3,'final_admissible','YES',:h,:sup)", {"cs": cs, "h": "3" * 64, "sup": provisional})


def test_append_only_guards(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V40, url)
    env = _seed_core(url, "ao")
    cs = _seed_contract_spec(url, "cs-ao")

    v1 = _insert_id(
        url,
        "INSERT INTO trading.resolution_labels (contract_spec_id, label_key, version_no, state, policy_code_hash) "
        "VALUES (:cs, 'lk', 1, 'pending', :h) RETURNING id",
        {"cs": cs, "h": "a" * 64},
    )
    with pytest.raises(Exception, match="v2_immutable_row:resolution_labels"):
        _execute(url, "UPDATE trading.resolution_labels SET state='provisional' WHERE id=:id", {"id": v1})
    with pytest.raises(Exception, match="v2_immutable_row:resolution_labels"):
        _execute(url, "DELETE FROM trading.resolution_labels WHERE id=:id", {"id": v1})

    run_id = _insert_metric_run(url, env, run_key="run-ao")
    with pytest.raises(Exception, match="v2_metric_run_immutable"):
        _execute(url, "UPDATE trading.metric_runs SET n_eff=99 WHERE id=:id", {"id": run_id})
    with pytest.raises(Exception, match="v2_metric_run_immutable"):
        _execute(url, "DELETE FROM trading.metric_runs WHERE id=:id", {"id": run_id})

    prom = _insert_id(
        url,
        "INSERT INTO trading.promotion_decisions (promotion_key, metric_run_id, promotion_type, from_ref, to_ref, evidence_manifest_hash, status, reason_code) "
        "VALUES ('pk-ao', :m, 'strategy', :fr, :tr, :eh, 'REJECTED', 'manual_reject') RETURNING id",
        {"m": run_id, "fr": "a" * 64, "tr": "b" * 64, "eh": "c" * 64},
    )
    with pytest.raises(Exception, match="v2_immutable_row:promotion_decisions"):
        _execute(url, "UPDATE trading.promotion_decisions SET status='DEFERRED' WHERE id=:id", {"id": prom})
    with pytest.raises(Exception, match="v2_immutable_row:promotion_decisions"):
        _execute(url, "DELETE FROM trading.promotion_decisions WHERE id=:id", {"id": prom})


def test_score_target_membership_invariants(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V40, url)
    cs = _seed_contract_spec(url, "cs-tgt")
    tok = _seed_token(url, "m-tgt", "t-tgt")
    engine = create_engine(url, poolclass=NullPool)
    try:
        with engine.begin() as c:
            c.execute(text("SET LOCAL session_replication_role = replica"))
            tv = c.execute(text(
                "INSERT INTO trading.pm_token_versions "
                "(token_id, version_no, outcome_index, observed_at, received_at) "
                "VALUES (:t,1,0,now(),now()) RETURNING id"
            ), {"t": tok}).scalar_one()
            pf = c.execute(text(
                "INSERT INTO trading.payout_functions "
                "(contract_spec_id,pm_token_id,token_version_id,outcome_index,function_ir,"
                "test_vectors,algorithm_hash,content_hash) VALUES "
                "(:cs,:t,:tv,0,'{\"YES\":\"1\"}'::jsonb,'{}'::jsonb,:h,:h) RETURNING id"
            ), {"cs": cs, "t": tok, "tv": tv, "h": "a" * 64}).scalar_one()
            c.execute(text("SET LOCAL session_replication_role = origin"))
            cluster = c.execute(text(
                "INSERT INTO trading.resolution_clusters "
                "(cluster_key,cluster_version,split,time_block_start,time_block_end,horizon) "
                "VALUES ('cluster-tgt',1,'train',now(),now()+interval '1 day','resolution') RETURNING id"
            )).scalar_one()
            c.execute(text(
                "INSERT INTO trading.resolution_cluster_memberships "
                "(resolution_cluster_id,contract_spec_id,token_id) VALUES (:c,:cs,:t)"
            ), {"c": cluster, "cs": cs, "t": tok})
            target = c.execute(text(
                "INSERT INTO trading.score_targets "
                "(target_key,target_type,contract_spec_id,resolution_cluster_id,horizon,target_weight,"
                "payout_function_id,canonical_side,payout_type) VALUES "
                "('tgt-1','bernoulli',:cs,:c,'resolution',1,:pf,'YES','binary') RETURNING id"
            ), {"cs": cs, "c": cluster, "pf": pf}).scalar_one()
            c.execute(text(
                "INSERT INTO trading.score_target_memberships "
                "(score_target_id,token_id,member_weight) VALUES (:t,:tok,1)"
            ), {"t": target, "tok": tok})
    finally:
        engine.dispose()
    assert _query(url, "SELECT target_weight FROM trading.score_targets WHERE id=:id", {"id": target}) == [(1,)]
    with pytest.raises(Exception, match="ck_score_targets_weight_range"):
        _execute(url, "INSERT INTO trading.score_targets (target_key,target_type,contract_spec_id,resolution_cluster_id,horizon,target_weight,payout_function_id,canonical_side,payout_type) VALUES ('bad-weight','bernoulli',:cs,:c,'resolution',1.5,:pf,'YES','binary')", {"cs": cs, "c": cluster, "pf": pf})

def test_promotion_capital_never_approved(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V40, url)
    env = _seed_core(url, "promo")
    run_id = _insert_metric_run(url, env, run_key="run-promo")

    with pytest.raises(Exception, match="ck_promotion_decisions_capital_never_approved"):
        _execute(
            url,
            "INSERT INTO trading.promotion_decisions (promotion_key, metric_run_id, promotion_type, from_ref, to_ref, evidence_manifest_hash, status) "
            "VALUES ('pk-cap', :m, 'capital', :fr, :tr, :eh, 'APPROVED')",
            {"m": run_id, "fr": "a" * 64, "tr": "b" * 64, "eh": "c" * 64},
        )

    # 未完成 metric/G8/evidence 的 strategy approval 必须 fail closed。
    with pytest.raises(Exception, match="v2_promotion_evidence_invalid"):
        _insert_id(url, "INSERT INTO trading.promotion_decisions (promotion_key,metric_run_id,promotion_type,from_ref,to_ref,evidence_manifest_hash,status,future_effective_at) VALUES ('pk-strat',:m,'strategy',:fr,:tr,:eh,'APPROVED',now()+interval '1 day') RETURNING id", {"m": run_id, "fr": "d" * 64, "tr": "e" * 64, "eh": "f" * 64})

    # With an immutable completed metric and G8 PASS present, the promotion
    # evidence must bind exactly to metric_runs.artifact_hash.  No unrelated
    # policy hash or external artifact catalog row may substitute for it.
    engine = create_engine(url, poolclass=NullPool)
    try:
        with engine.begin() as c:
            c.execute(text("SET LOCAL session_replication_role = replica"))
            c.execute(text(
                "UPDATE trading.metric_runs SET status='COMPLETED', completed_at=now() "
                "WHERE id=:run"
            ), {"run": run_id})
            c.execute(text(
                "INSERT INTO trading.gate_decisions "
                "(gate,target_kind,target_id,input_hash,policy_hash,version_manifest_id,"
                "result,committed_at) VALUES "
                "('G8','metric_run',:run,:ih,:ph,:release,'PASS',now())"
                ), {"run": run_id, "ih": "1" * 64, "ph": "2" * 64,
                    "release": env["rel"]})
            experiment = c.execute(text(
                "INSERT INTO trading.experiments "
                "(experiment_key,hypothesis,hypothesis_hash,primary_metric,guardrails,"
                " unique_change_field,champion_input_manifest_hash,"
                " challenger_input_manifest_hash,sample_policy,stopping_rule,seed,status,"
                " time_block_start,time_block_end) VALUES "
                "('promo-db-exp','paired',:hh,'bernoulli_brier','{}'::jsonb,"
                " 'strategy_version_id',:fr,:tr,'{}'::jsonb,'{}'::jsonb,1,"
                " 'COMPLETED','2026-07-31T00:00:00Z','2026-08-02T00:00:00Z') "
                "RETURNING id"
            ), {"hh": "7" * 64, "fr": "5" * 64, "tr": "6" * 64}).scalar_one()
            c.execute(text(
                "INSERT INTO trading.experiment_variants "
                "(experiment_id,variant_key,variant_type,input_manifest_hash,"
                " strategy_version_id,release_manifest_id) VALUES "
                "(:e,'champ','champion',:fr,:sv,:rm),"
                "(:e,'chal','challenger',:tr,:sv,:rm)"
            ), {"e": experiment, "fr": "5" * 64, "tr": "6" * 64,
                "sv": env["strat"], "rm": env["rel"]})
            c.execute(text(
                "INSERT INTO trading.challenger_variants "
                "(experiment_id,variant_key,challenger_type,changed_fields,policy_hash,status) "
                "VALUES (:e,'chal','strategy',"
                "'{\"strategy_version_id\":\"next\"}'::jsonb,:ph,'ACTIVE')"
            ), {"e": experiment, "ph": "8" * 64})
            c.execute(text("SET LOCAL session_replication_role = origin"))
    finally:
        engine.dispose()
    with pytest.raises(Exception, match="v2_promotion_evidence_invalid"):
        _execute(
            url,
            "INSERT INTO trading.promotion_decisions "
            "(promotion_key,metric_run_id,promotion_type,from_ref,to_ref,"
            "evidence_manifest_hash,status,future_effective_at) VALUES "
            "('pk-wrong-evidence',:m,'strategy',:fr,:tr,:eh,'APPROVED',"
            "now()+interval '1 day')",
            {"m": run_id, "fr": "3" * 64, "tr": "4" * 64,
             "eh": "f" * 64},
        )
    approved = _insert_id(
        url,
        "INSERT INTO trading.promotion_decisions "
        "(promotion_key,metric_run_id,promotion_type,from_ref,to_ref,"
        "evidence_manifest_hash,status,future_effective_at) VALUES "
        "('pk-exact-evidence',:m,'strategy',:fr,:tr,:eh,'APPROVED',"
        "now()+interval '1 day') RETURNING id",
        {"m": run_id, "fr": "5" * 64, "tr": "6" * 64,
         "eh": "d" * 64},
    )
    assert approved > 0


def test_experiment_and_challenger_controlled_lifecycle(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V40, url)
    _seed_core(url, "experiment-lifecycle")
    base_sql = (
        "INSERT INTO trading.experiments "
        "(experiment_key,hypothesis,hypothesis_hash,primary_metric,guardrails,"
        " unique_change_field,champion_input_manifest_hash,"
        " challenger_input_manifest_hash,sample_policy,stopping_rule,seed,status,"
        " time_block_start,time_block_end) VALUES "
        "(:key,'paired',:hh,'bernoulli_brier','{}'::jsonb,'strategy_version_id',"
        " :champ,:chall,'{}'::jsonb,'{}'::jsonb,42,:status,now(),"
        " now()+interval '1 day') RETURNING id"
    )
    params = {"key": "exp-life", "hh": "1" * 64, "champ": "2" * 64,
              "chall": "3" * 64, "status": "COMPLETED"}
    with pytest.raises(Exception, match="v2_experiment_initial_state_invalid"):
        _insert_id(url, base_sql, params)
    params["status"] = "PLANNED"
    experiment_id = _insert_id(url, base_sql, params)
    with pytest.raises(Exception, match="v2_experiment_immutable"):
        _execute(url, "UPDATE trading.experiments SET hypothesis='changed' WHERE id=:id",
                 {"id": experiment_id})
    _execute(url, "UPDATE trading.experiments SET status='RUNNING' WHERE id=:id",
             {"id": experiment_id})
    _execute(url, "UPDATE trading.experiments SET status='COMPLETED' WHERE id=:id",
             {"id": experiment_id})
    with pytest.raises(Exception, match="v2_experiment_transition_invalid"):
        _execute(url, "UPDATE trading.experiments SET status='RUNNING' WHERE id=:id",
                 {"id": experiment_id})

    challenger_id = _insert_id(
        url,
        "INSERT INTO trading.challenger_variants "
        "(experiment_id,variant_key,challenger_type,changed_fields,policy_hash) "
        "VALUES (:e,'chall','strategy','{\"strategy_version_id\":\"next\"}'::jsonb,"
        ":ph) RETURNING id",
        {"e": experiment_id, "ph": "4" * 64},
    )
    _execute(url, "UPDATE trading.challenger_variants SET status='SUPERSEDED' WHERE id=:id",
             {"id": challenger_id})
    with pytest.raises(Exception, match="v2_challenger_transition_invalid"):
        _execute(url, "UPDATE trading.challenger_variants SET status='ACTIVE' WHERE id=:id",
                 {"id": challenger_id})


def test_metric_run_lifecycle_guard(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V40, url)
    env = _seed_core(url, "lc")
    run_id = _insert_metric_run(url, env, run_key="run-lc")
    assert _query(url, "SELECT status FROM trading.metric_runs WHERE id=:id", {"id": run_id}) == [("RUNNING",)]

    # 缺完整 label/time-block/five-layer/artifact evidence 不得完成。
    with pytest.raises(Exception, match="v2_metric_run_evidence_incomplete"):
        _execute(url, "UPDATE trading.metric_runs SET status='COMPLETED', completed_at=now() WHERE id=:id", {"id": run_id})
    assert _query(url, "SELECT status FROM trading.metric_runs WHERE id=:id", {"id": run_id}) == [("RUNNING",)]


def test_g8_gate_requires_completed_metric_run(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V40, url)
    env = _seed_core(url, "g8")
    run_id = _insert_metric_run(url, env, run_key="run-g8")

    # target 未 COMPLETED → 拒
    with pytest.raises(Exception, match="v2_gate_g8_target_invalid"):
        _execute(
            url,
            "INSERT INTO trading.gate_decisions (gate, target_kind, target_id, input_hash, policy_hash, version_manifest_id, result, committed_at) "
            "VALUES ('G8', 'metric_run', :t, :ih, :ph, :rel, 'PASS', now())",
            {"t": run_id, "ih": "a" * 64, "ph": "b" * 64, "rel": env["rel"]},
        )

    assert _query(url, "SELECT count(*) FROM trading.gate_decisions WHERE gate='G8'") == [(0,)]


def test_downgrade_roundtrip_and_fail_closed(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V40, url)

    _run(command.downgrade, V31, url)
    assert _version(url) == [(V31,)]
    assert set(LEARNING_TABLES).isdisjoint(set(_trading_tables(url)))

    _run(command.upgrade, V40, url)
    assert _version(url) == [(V40,)]
    before = set(_trading_tables(url))
    _execute(url, "CREATE TABLE trading.unknown_intruder_0040 (id integer)")
    with pytest.raises(
        Exception,
        match="v2_wp04_learning_unknown_object|v2_wp04_unknown_object|v2_trading_schema_not_empty",
    ):
        _run(command.downgrade, V31, url)
    assert _query(url, "SELECT to_regclass('trading.unknown_intruder_0040') IS NOT NULL") == [(True,)]
    assert set(_trading_tables(url)) == before | {"unknown_intruder_0040"}


def test_downgrade_rejects_unknown_index(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V40, url)
    _execute(url, "CREATE INDEX unknown_wp04_learning_idx ON trading.resolution_labels(state)")
    with pytest.raises(Exception, match="v2_wp04_learning_unknown_index"):
        _run(command.downgrade, V31, url)
    assert _version(url) == [(V40,)]
    _execute(url, "DROP INDEX trading.unknown_wp04_learning_idx")
    _run(command.downgrade, V31, url)
    assert _version(url) == [(V31,)]
