"""
WP-05 v2_0051 execution orders migration —— 真 PostgreSQL 集成（Checkpoint C）。

覆盖：empty/existing roundtrip、9 张新表 + 4 张既有表 lineage、
``alembic check`` modeled drift=0（split_dynamic_diffs 白名单）、downgrade fail-closed
未知对象拒绝、临时库零残留。
"""

from pathlib import Path

import pytest
from alembic import command, util
from alembic.config import Config
from sqlalchemy import create_engine, text
from sqlalchemy.pool import NullPool

SERVE_DIR = Path(__file__).resolve().parents[3]
ALEMBIC_DIR = SERVE_DIR / "alembic"
V50 = "b1000050"
V51 = "b1000051"
HEAD_REVISION = V51

NEW_TABLES = [
    "execution_authorization_envelopes",
    "exchange_order_attempts",
    "exchange_orders",
    "order_state_events",
    "exchange_trades",
    "account_reconciliations",
    "workflow_events",
    "external_call_attempts",
    "alert_events",
]

_LINEAGE_TABLES = ("executions", "positions", "position_lots", "ledger_transactions")
_LINEAGE_COLS = ("account_id", "envelope_id", "order_id", "trade_id")

_NEW_TRIGGERS = (
    "trg_execution_authorization_envelopes_lifecycle",
    "trg_exchange_orders_lifecycle",
    "trg_exchange_order_attempts_lifecycle",
    "trg_account_reconciliations_lifecycle",
    "trg_execution_envelope_permission_check",
    "trg_execution_envelope_intent_bind",
    "trg_order_state_events_immutable",
    "trg_exchange_trades_immutable",
    "trg_external_call_attempts_immutable",
    "trg_workflow_events_immutable",
    "trg_alert_events_immutable",
)


def _run(cmd, revision, db_url):
    cfg = Config()
    cfg.set_main_option("script_location", str(ALEMBIC_DIR))
    engine = create_engine(db_url, poolclass=NullPool)
    conn = engine.connect()
    cfg.attributes["connection"] = conn
    try:
        cmd(cfg, revision)
    finally:
        conn.close()
        engine.dispose()


def _check_diffs(db_url):
    cfg = Config()
    cfg.set_main_option("script_location", str(ALEMBIC_DIR))
    engine = create_engine(db_url, poolclass=NullPool)
    conn = engine.connect()
    cfg.attributes["connection"] = conn
    try:
        command.check(cfg)
        return []
    except util.AutogenerateDiffsDetected as e:
        return e.diffs
    finally:
        conn.close()
        engine.dispose()


def _query(db_url, sql, params=None):
    engine = create_engine(db_url)
    try:
        with engine.connect() as c:
            return c.execute(text(sql), params or {}).fetchall()
    finally:
        engine.dispose()


def _execute(db_url, sql, params=None):
    engine = create_engine(db_url)
    try:
        with engine.connect() as c:
            c.execute(text(sql), params or {})
            c.commit()
    finally:
        engine.dispose()


def _seed_fixture_account(db_url, *, account_key="fixture-migration-0051"):
    engine = create_engine(db_url)
    try:
        with engine.begin() as c:
            c.execute(text("SET LOCAL session_replication_role = replica"))
            account_id = c.execute(
                text(
                    "INSERT INTO trading.pm_accounts "
                    "(account_key, provider, chain_id, identity_type, funder_address, "
                    " maker_address, signing_identity, wallet_type, signature_type, "
                    " release_manifest_id, capital_permission_manifest_id, network_mode) "
                    "VALUES (:key, 'polymarket', 137, 'FIXTURE_ONLY', :wallet, :wallet, "
                    " :signer, 'deposit_wallet', '3', 900001, 900002, 'fixture') RETURNING id"
                ),
                {
                    "key": account_key,
                    "wallet": "0x" + "a" * 40,
                    "signer": "0x" + "b" * 40,
                },
            ).scalar_one()
            c.execute(
                text(
                    "INSERT INTO trading.execution_leases "
                    "(account_id, lease_role, owner, lease_until, fencing_token) "
                    "VALUES (:account, 'EXECUTION', 'migration-test', "
                    "now() + interval '1 hour', 1)"
                ),
                {"account": account_id},
            )
            return account_id
    finally:
        engine.dispose()


def _version(db_url):
    return _query(db_url, "SELECT version_num FROM public.alembic_version")


def _trading_tables(db_url):
    return [r[0] for r in _query(
        db_url, "SELECT tablename FROM pg_tables WHERE schemaname='trading' ORDER BY 1"
    )]


def _columns(db_url, table):
    return [r[0] for r in _query(
        db_url,
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_schema='trading' AND table_name=:t",
        {"t": table},
    )]


def _constraints(db_url, table):
    return [r[0] for r in _query(
        db_url,
        "SELECT conname FROM pg_constraint c "
        "JOIN pg_class t ON t.oid=c.conrelid "
        "JOIN pg_namespace n ON n.oid=t.relnamespace "
        "WHERE n.nspname='trading' AND t.relname=:t",
        {"t": table},
    )]


def _triggers(db_url, table=None):
    sql = (
        "SELECT t.tgname FROM pg_trigger t "
        "JOIN pg_class tbl ON tbl.oid=t.tgrelid "
        "JOIN pg_namespace n ON n.oid=tbl.relnamespace "
        "WHERE n.nspname='trading' AND NOT t.tgisinternal"
    )
    params = {}
    if table:
        sql += " AND tbl.relname=:t"
        params = {"t": table}
    return [r[0] for r in _query(db_url, sql, params)]


def test_literal_empty_roundtrip(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V51, url)
    assert _version(url) == [(V51,)]
    assert set(NEW_TABLES) <= set(_trading_tables(url))

    _run(command.downgrade, V50, url)
    assert _version(url) == [(V50,)]
    quote_nullable = _query(
        url,
        "SELECT is_nullable FROM information_schema.columns "
        "WHERE table_schema='trading' AND table_name='executions' "
        "AND column_name='quote_checkpoint_id'",
    )
    assert quote_nullable == [("NO",)]
    assert set(NEW_TABLES).isdisjoint(set(_trading_tables(url)))
    # lineage 列必须被移除
    for table in _LINEAGE_TABLES:
        assert "account_id" not in _columns(url, table), f"lineage not removed: {table}"

    _run(command.upgrade, V51, url)
    assert _version(url) == [(V51,)]
    assert set(NEW_TABLES) <= set(_trading_tables(url))


def test_tables_constraints_and_alembic_drift(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, "head", url)
    assert _version(url) == [(HEAD_REVISION,)]
    tables = set(_trading_tables(url))
    assert set(NEW_TABLES) <= tables

    # 9 张表关键约束
    assert "uq_execution_authorization_envelopes_key" in _constraints(url, "execution_authorization_envelopes")
    assert "uq_execution_authorization_envelopes_hash" in _constraints(url, "execution_authorization_envelopes")
    assert "uq_execution_authorization_envelopes_idempotency" in _constraints(url, "execution_authorization_envelopes")
    assert "ck_execution_authorization_envelopes_authority_known" in _constraints(url, "execution_authorization_envelopes")
    assert "uq_exchange_order_attempts_envelope_no" in _constraints(url, "exchange_order_attempts")
    assert "uq_exchange_orders_account_ext" in _constraints(url, "exchange_orders")
    assert "uq_exchange_trades_account_ext" in _constraints(url, "exchange_trades")
    assert "ck_account_reconciliations_completed_pair" in _constraints(url, "account_reconciliations")
    assert "ck_external_call_attempts_request_hash_hex" in _constraints(url, "external_call_attempts")

    # lineage 列
    for table in _LINEAGE_TABLES:
        cols = set(_columns(url, table))
        for col in _LINEAGE_COLS:
            if table == "positions" and col == "trade_id":
                continue
            if table == "position_lots" and col == "envelope_id":
                continue
            assert col in cols, f"lineage col {col} missing on {table}"

    # triggers
    all_trg = set(_triggers(url))
    assert set(_NEW_TRIGGERS) <= all_trg

    diffs = _check_diffs(url)
    from tests.trading.fixtures.migration_helpers import split_dynamic_diffs

    _dynamic, modeled = split_dynamic_diffs(diffs)
    assert modeled == [], f"modeled tables drift: {modeled}"


def test_downgrade_fail_closed_unknown_object(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V51, url)
    before = set(_trading_tables(url))
    _execute(url, "CREATE TABLE trading.unknown_intruder_0051 (id integer)")
    with pytest.raises(Exception, match="v2_wp05_execution_orders_unknown_object"):
        _run(command.downgrade, V50, url)
    assert _version(url) == [(V51,)]
    assert set(_trading_tables(url)) == before | {"unknown_intruder_0051"}
    _execute(url, "DROP TABLE trading.unknown_intruder_0051")
    _run(command.downgrade, V50, url)
    assert _version(url) == [(V50,)]
    assert set(NEW_TABLES).isdisjoint(set(_trading_tables(url)))


def test_existing_base_fixture_compatible(temp_pg_db):
    import subprocess

    url = temp_pg_db.url
    fixture_sql = SERVE_DIR / "tests/trading/fixtures/base_legacy_schema.sql"
    cmd = ["psql", "-q", "-v", "ON_ERROR_STOP=1"]
    if url.startswith("postgresql+psycopg:///"):
        cmd += ["-d", url.split("///", 1)[1]]
    else:
        cmd += [url]
    run = subprocess.run(cmd + ["-f", str(fixture_sql)], capture_output=True, text=True)
    assert run.returncode == 0, f"base fixture load failed: {run.stderr[-2000:]}"
    _run(command.upgrade, "head", url)
    public_tables = [r[0] for r in _query(
        url, "SELECT tablename FROM pg_tables WHERE schemaname='public' ORDER BY 1"
    )]
    assert "alembic_version" in public_tables
    for core in ("admin_users", "users", "settings"):
        assert core in public_tables, f"legacy Base table {core} missing"


def test_reconciliation_terminal_is_exact_and_immutable(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V51, url)
    account_id = _seed_fixture_account(url)
    _execute(
        url,
        "INSERT INTO trading.account_reconciliations "
        "(reconciliation_key, account_id, trigger_reason, ws_watermark, rest_page_cursor, "
        " rest_page_hash, unknown_queries, input_manifest_hash, differences, fencing_token) "
        "VALUES ('recon-complete', :account, 'TEST', 0, '{}'::jsonb, :h, '{}'::jsonb, "
        " :h, '[]'::jsonb, 1)",
        {"account": account_id, "h": "a" * 64},
    )
    _execute(
        url,
        "UPDATE trading.account_reconciliations SET status='COMPLETED', "
        "output_manifest_hash=:h, differences='[]'::jsonb, completed_at=now() "
        "WHERE reconciliation_key='recon-complete'",
        {"h": "b" * 64},
    )
    with pytest.raises(Exception, match="v2_reconciliation_terminal_immutable"):
        _execute(
            url,
            "UPDATE trading.account_reconciliations SET differences='[]'::jsonb "
            "WHERE reconciliation_key='recon-complete'",
        )

    _execute(
        url,
        "INSERT INTO trading.account_reconciliations "
        "(reconciliation_key, account_id, trigger_reason, ws_watermark, rest_page_cursor, "
        " rest_page_hash, unknown_queries, input_manifest_hash, differences, fencing_token) "
        "VALUES ('recon-invalid', :account, 'TEST', 0, '{}'::jsonb, :h, '{}'::jsonb, "
        " :h, '[]'::jsonb, 1)",
        {"account": account_id, "h": "c" * 64},
    )
    with pytest.raises(Exception, match="v2_reconciliation_complete_requires_zero_diff"):
        _execute(
            url,
            "UPDATE trading.account_reconciliations SET status='COMPLETED', "
            "output_manifest_hash=:h, differences='[{\"kind\":\"drift\"}]'::jsonb, "
            "completed_at=now() WHERE reconciliation_key='recon-invalid'",
            {"h": "d" * 64},
        )


def test_order_event_transition_matches_frozen_table(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V51, url)
    account_id = _seed_fixture_account(url)
    engine = create_engine(url)
    try:
        with engine.begin() as c:
            c.execute(text("SET LOCAL session_replication_role = replica"))
            order_id = c.execute(
                text(
                    "INSERT INTO trading.exchange_orders "
                    "(order_key, account_id, token_id, side, price, size) "
                    "VALUES ('event-order', :account, 'token', 'BUY', 0.5, 10) RETURNING id"
                ),
                {"account": account_id},
            ).scalar_one()
    finally:
        engine.dispose()

    with pytest.raises(Exception, match="ck_order_state_events_type_matches_transition"):
        _execute(
            url,
            "INSERT INTO trading.order_state_events "
            "(event_key, order_id, event_type, transition_from, transition_to, event_payload, "
            " event_hash, fence_token) VALUES "
            "('bad-event', :order, 'ACK', 'PARTIAL', 'UNKNOWN', '{}'::jsonb, :h, 1)",
            {"order": order_id, "h": "e" * 64},
        )
    _execute(
        url,
        "INSERT INTO trading.order_state_events "
        "(event_key, order_id, event_type, transition_from, transition_to, event_payload, "
        " event_hash, fence_token) VALUES "
        "('good-event', :order, 'UNKNOWN', 'PARTIAL', 'UNKNOWN', '{}'::jsonb, :h, 1)",
        {"order": order_id, "h": "f" * 64},
    )
    with pytest.raises(Exception, match="v2_immutable_row"):
        _execute(
            url,
            "UPDATE trading.order_state_events SET event_payload='{}'::jsonb "
            "WHERE event_key='good-event'",
        )


def test_exchange_order_guard_matches_frozen_unknown_edges(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V51, url)
    account_id = _seed_fixture_account(url)
    engine = create_engine(url)
    try:
        with engine.begin() as c:
            c.execute(text("SET LOCAL session_replication_role = replica"))
            c.execute(
                text(
                    "INSERT INTO trading.exchange_orders "
                    "(order_key, account_id, token_id, side, price, size) "
                    "VALUES ('guard-order', :account, 'token', 'BUY', 0.5, 10)"
                ),
                {"account": account_id},
            )
    finally:
        engine.dispose()
    _execute(url, "UPDATE trading.exchange_orders SET status='ACK' WHERE order_key='guard-order'")
    _execute(
        url,
        "UPDATE trading.exchange_orders SET status='PARTIAL', filled_size=2 "
        "WHERE order_key='guard-order'",
    )
    _execute(url, "UPDATE trading.exchange_orders SET status='UNKNOWN' WHERE order_key='guard-order'")
    for invalid_terminal in ("FILLED", "CANCELLED", "REJECTED"):
        with pytest.raises(Exception, match="v2_exchange_order_transition_invalid"):
            _execute(
                url,
                "UPDATE trading.exchange_orders SET status=:status "
                "WHERE order_key='guard-order'",
                {"status": invalid_terminal},
            )
    _execute(
        url,
        "UPDATE trading.exchange_orders SET status='RECONCILED' "
        "WHERE order_key='guard-order'",
    )
    with pytest.raises(Exception, match="v2_exchange_order_same_state_mutation_invalid"):
        _execute(
            url,
            "UPDATE trading.exchange_orders SET filled_size=3 WHERE order_key='guard-order'",
        )


def test_downgrade_rejects_unresolved_but_allows_terminal_fixture_facts(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V51, url)
    account_id = _seed_fixture_account(url)
    engine = create_engine(url)
    try:
        with engine.begin() as c:
            c.execute(text("SET LOCAL session_replication_role = replica"))
            c.execute(
                text(
                    "INSERT INTO trading.exchange_orders "
                    "(order_key, account_id, token_id, side, price, size) "
                    "VALUES ('downgrade-order', :account, 'token', 'BUY', 0.5, 10)"
                ),
                {"account": account_id},
            )
    finally:
        engine.dispose()
    with pytest.raises(Exception, match="v2_wp05_execution_orders_downgrade_unresolved_facts"):
        _run(command.downgrade, V50, url)
    assert _version(url) == [(V51,)]
    _execute(
        url,
        "UPDATE trading.exchange_orders SET status='CANCELLED' "
        "WHERE order_key='downgrade-order'",
    )
    _run(command.downgrade, V50, url)
    assert _version(url) == [(V50,)]
    assert "exchange_orders" not in _trading_tables(url)
    _run(command.upgrade, V51, url)
    assert _version(url) == [(V51,)]


def test_downgrade_unknown_external_dependency_is_transactional(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V51, url)
    _execute(
        url,
        "CREATE VIEW public.unknown_0051_dependency AS "
        "SELECT id FROM trading.exchange_orders",
    )
    with pytest.raises(Exception, match="depend"):
        _run(command.downgrade, V50, url)
    assert _version(url) == [(V51,)]
    assert "exchange_orders" in _trading_tables(url)
    _execute(url, "DROP VIEW public.unknown_0051_dependency")
    _run(command.downgrade, V50, url)
    assert _version(url) == [(V50,)]
