"""
WP-01B v2_0010 market master migration —— 真 PostgreSQL 集成验收（Checkpoint B §5.2）。

前置：``V2_TEST_ADMIN_DATABASE_URL`` 存在，否则整模块 skip。在独立 ``pm_v2_test_*``
临时库执行，从不在管理/业务库跑 downgrade。

覆盖：
1. literal-empty roundtrip：b1000002 → b1000010 → b1000002 → b1000010；9 张 market 表 +
   之前 20 张 foundation 表 + 3 分区；public 不产生对象；
2. existing-Base roundtrip：Base 18 表保持不变；
3. ``alembic check`` drift：9 张 modeled 表零 drift，唯一 diff 是 0002 的动态分区子表；
4. 唯一约束：gamma_market_id / condition_id / token_id / (market_id,outcome_index) /
   (frame_id,page_no) / (frame_id,endpoint,cursor_input)；outcome_index 仅 0/1；
5. append-only guard：pages/market_versions/token_versions/lifecycle_events 禁 UPDATE/DELETE；
   frame 只允许 OPEN→COMPLETE|FAILED；market_current ``observed_at`` CAS 单调；
6. FK RESTRICT：被 token/version 引用的 market 不可删除；
7. downgrade fail-closed：trading schema 含未知对象时整次 downgrade 回滚、version 不倒退。
"""

import hashlib
import os
import subprocess
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pytest
from alembic import command, util
from alembic.config import Config
from sqlalchemy import create_engine, text
from sqlalchemy.engine import make_url
from sqlalchemy.pool import NullPool

SERVE_DIR = Path(__file__).resolve().parents[3]
ALEMBIC_DIR = SERVE_DIR / "alembic"
FIXTURE_SQL = SERVE_DIR / "tests/trading/fixtures/base_legacy_schema.sql"
V2 = "b1000002"
V10 = "b1000010"

MARKET_TABLES = [
    "pm_universe_frames",
    "pm_universe_frame_pages",
    "pm_events",
    "pm_markets",
    "pm_market_versions",
    "pm_tokens",
    "pm_token_versions",
    "pm_market_lifecycle_events",
    "pm_market_current",
]

_sha = lambda c: c * 64  # noqa: E731


def _run(cmd, revision, db_url):
    cfg = Config()
    cfg.set_main_option("script_location", str(ALEMBIC_DIR))
    engine = create_engine(db_url, poolclass=NullPool)
    conn = engine.connect()
    cfg.attributes["connection"] = conn
    try:
        cmd(cfg, revision)
    finally:
        conn.close()
        engine.dispose()


def _check_diffs(db_url):
    cfg = Config()
    cfg.set_main_option("script_location", str(ALEMBIC_DIR))
    engine = create_engine(db_url, poolclass=NullPool)
    conn = engine.connect()
    cfg.attributes["connection"] = conn
    try:
        command.check(cfg)
        return []
    except util.AutogenerateDiffsDetected as e:
        return e.diffs
    finally:
        conn.close()
        engine.dispose()


def _query(db_url, sql, params=None):
    engine = create_engine(db_url)
    try:
        with engine.connect() as c:
            return c.execute(text(sql), params or {}).fetchall()
    finally:
        engine.dispose()


def _execute(db_url, sql, params=None):
    engine = create_engine(db_url)
    try:
        with engine.connect() as c:
            c.execute(text(sql), params or {})
            c.commit()
    finally:
        engine.dispose()


def _seed_artifact(db_url, marker="a"):
    sha = hashlib.sha256(marker.encode()).hexdigest()
    locator = f"cas/v1/sha256/{sha[:2]}/{sha[2:4]}/{sha}.raw"
    _execute(
        db_url,
        "INSERT INTO trading.artifact_objects "
        "(sha256, original_size, stored_size, mime, compression, storage_driver, "
        " storage_version, locator) "
        "VALUES (:sha, 2, 2, 'application/json', 'none', 'local', 'cas/v1', :locator) "
        "ON CONFLICT DO NOTHING",
        {"sha": sha, "locator": locator},
    )
    return _query(
        db_url,
        "SELECT id FROM trading.artifact_objects WHERE sha256=:sha ORDER BY id LIMIT 1",
        {"sha": sha},
    )[0][0]


def _seed_frame(db_url, *, owner="worker-1", started_at=None, lease_expires_at=None):
    started_at = started_at or datetime.now(timezone.utc)
    lease_expires_at = lease_expires_at or started_at + timedelta(minutes=10)
    _execute(
        db_url,
        "INSERT INTO trading.pm_universe_frames "
        "(started_at, owner, lease_expires_at, fencing_token) "
        "VALUES (:started, :owner, :lease, 1)",
        {"started": started_at, "owner": owner, "lease": lease_expires_at},
    )
    return _query(
        db_url, "SELECT id FROM trading.pm_universe_frames ORDER BY id DESC LIMIT 1"
    )[0][0]


def _seed_terminal_pages(db_url, frame_id):
    artifact_id = _seed_artifact(db_url, "b")
    now = datetime.now(timezone.utc)
    _execute(
        db_url,
        "INSERT INTO trading.pm_universe_frame_pages "
        "(frame_id, page_no, endpoint, cursor_input, cursor_output, item_count, "
        " raw_artifact_id, raw_artifact_ref, raw_artifact_hash, received_at) VALUES "
        "(:f, 0, 'events_open', NULL, NULL, 1, :a, :h, :h, :t), "
        "(:f, 1, 'events_closed', NULL, NULL, 0, :a, :h, :h, :t), "
        "(:f, 2, 'markets_open', NULL, NULL, 2, :a, :h, :h, :t), "
        "(:f, 3, 'markets_closed', NULL, NULL, 0, :a, :h, :h, :t)",
        {"f": frame_id, "a": artifact_id, "h": _sha("b"), "t": now},
    )


def _version(db_url):
    return _query(db_url, "SELECT version_num FROM public.alembic_version")


def _trading_tables(db_url):
    return [r[0] for r in _query(
        db_url, "SELECT tablename FROM pg_tables WHERE schemaname='trading' ORDER BY 1"
    )]


def _public_tables(db_url):
    return [r[0] for r in _query(
        db_url, "SELECT tablename FROM pg_tables WHERE schemaname='public' ORDER BY 1"
    )]


def _apply_fixture(db_url):
    u = make_url(db_url)
    cmd = ["psql", "-q", "-v", "ON_ERROR_STOP=1"]
    if u.host:
        cmd += ["-h", u.host]
    if u.port:
        cmd += ["-p", str(u.port)]
    if u.username:
        cmd += ["-U", u.username]
    cmd += ["-d", u.database]
    env = dict(os.environ)
    if u.password:
        env["PGPASSWORD"] = u.password
    r = subprocess.run(cmd + ["-f", str(FIXTURE_SQL)], capture_output=True, text=True, env=env)
    assert r.returncode == 0, r.stderr[-2000:]


def _seed_market(db_url):
    """插入一个 frame + market + token 对，返回 dict of ids。"""
    frame_id = _seed_frame(db_url)
    _execute(
        db_url,
        "INSERT INTO trading.pm_events (gamma_event_id, slug, title) VALUES ('evt-1', 's1', 't1')",
    )
    _execute(
        db_url,
        "INSERT INTO trading.pm_markets (gamma_market_id, condition_id, gamma_event_id, question) "
        "VALUES ('mkt-1', 'cond-1', 'evt-1', 'q1')",
    )
    market_id = _query(db_url, "SELECT id FROM trading.pm_markets WHERE gamma_market_id='mkt-1'")[0][0]
    _execute(
        db_url,
        "INSERT INTO trading.pm_tokens (token_id, market_id, outcome_index, outcome_label) "
        "VALUES ('tok-0', :m, 0, 'Yes'), ('tok-1', :m, 1, 'No')",
        {"m": market_id},
    )
    return {"frame_id": frame_id, "market_id": market_id}


# ---------------- 1. literal-empty roundtrip ----------------

def test_literal_empty_roundtrip(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V10, url)
    assert _version(url) == [(V10,)]
    tables = set(_trading_tables(url))
    assert {t for t in tables if not t.startswith("outbox_delivery_history_")} == set(
        [
            "artifact_objects", "artifact_lineage_edges", "archive_manifests", "retention_manifests",
            "runtime_config_versions", "strategy_objective_contracts", "strategy_versions",
            "execution_spec_versions", "capital_permission_manifests", "release_manifests",
            "policy_type_scopes", "policy_freezes", "model_role_bindings",
            "secret_vault_entries", "secret_vault_versions", "secret_access_events",
            "idempotency_claims", "transactional_outbox", "outbox_delivery_history", "job_completions",
        ]
        + MARKET_TABLES
    )
    assert len([t for t in tables if t.startswith("outbox_delivery_history_")]) == 3
    assert _public_tables(url) == ["alembic_version"]

    _run(command.downgrade, V2, url)
    assert _version(url) == [(V2,)]
    assert set(MARKET_TABLES).isdisjoint(set(_trading_tables(url)))

    _run(command.upgrade, V10, url)
    assert _version(url) == [(V10,)]


def test_existing_base_fixture_roundtrip(temp_pg_db):
    url = temp_pg_db.url
    _apply_fixture(url)
    before_base = sorted(t for t in _public_tables(url) if t != "alembic_version")

    _run(command.upgrade, V10, url)
    assert _version(url) == [(V10,)]
    assert sorted(_public_tables(url)) == sorted(before_base + ["alembic_version"])

    _run(command.downgrade, V2, url)
    assert _version(url) == [(V2,)]
    assert set(MARKET_TABLES).isdisjoint(set(_trading_tables(url)))
    assert sorted(_public_tables(url)) == sorted(before_base + ["alembic_version"])


# ---------------- 2. metadata drift ----------------

def test_metadata_compare_zero_drift_on_modeled_tables(temp_pg_db):
    url = temp_pg_db.url
    # ``alembic check`` 要求 DB 在 head（b1000011）；升级到 head 覆盖 0002+0010+0011 全部 modeled 表
    _run(command.upgrade, "head", url)
    diffs = _check_diffs(url)

    from tests.trading.fixtures.migration_helpers import split_dynamic_diffs

    dynamic, modeled = split_dynamic_diffs(diffs)
    # 唯一允许 diff：动态分区子表 + 继承索引（metadata 无法静态表达）
    assert len(dynamic) > 0, f"expected dynamic partition diffs: {diffs}"
    assert modeled == [], f"modeled 表存在 drift: {modeled}"


# ---------------- 3. 唯一约束 ----------------

def test_unique_constraints_enforced(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V10, url)
    _seed_market(url)

    with pytest.raises(Exception, match="uq_pm_markets_gamma_market_id"):
        _execute(
            url,
            "INSERT INTO trading.pm_markets (gamma_market_id, condition_id) VALUES ('mkt-1', 'cond-x')",
        )
    with pytest.raises(Exception, match="uq_pm_markets_condition_id"):
        _execute(
            url,
            "INSERT INTO trading.pm_markets (gamma_market_id, condition_id) VALUES ('mkt-2', 'cond-1')",
        )
    with pytest.raises(Exception, match="uq_pm_tokens_token_id"):
        _execute(
            url,
            "INSERT INTO trading.pm_tokens (token_id, market_id, outcome_index) "
            "SELECT 'tok-0', id, 0 FROM trading.pm_markets WHERE gamma_market_id='mkt-1'",
        )
    with pytest.raises(Exception, match="uq_pm_tokens_market_index"):
        _execute(
            url,
            "INSERT INTO trading.pm_tokens (token_id, market_id, outcome_index) "
            "SELECT 'tok-9', id, 0 FROM trading.pm_markets WHERE gamma_market_id='mkt-1'",
        )
    with pytest.raises(Exception, match="ck_pm_tokens_outcome_index_binary"):
        _execute(
            url,
            "INSERT INTO trading.pm_tokens (token_id, market_id, outcome_index) "
            "SELECT 'tok-8', id, 2 FROM trading.pm_markets WHERE gamma_market_id='mkt-1'",
        )

    fid = _query(url, "SELECT id FROM trading.pm_universe_frames ORDER BY id DESC LIMIT 1")[0][0]
    _execute(
        url,
        "INSERT INTO trading.pm_universe_frame_pages "
        "(frame_id, page_no, endpoint, cursor_input, cursor_output, item_count, "
        " raw_artifact_id, raw_artifact_ref, raw_artifact_hash, received_at) "
        "VALUES (:f, 0, 'markets_open', 'c0', 'c1', 1, :aid, :a, :a, :t)",
        {
            "f": fid, "aid": _seed_artifact(url, "a"), "a": _sha("a"),
            "t": datetime.now(timezone.utc),
        },
    )
    with pytest.raises(Exception, match="uq_pm_universe_frame_pages_frame_page"):
        _execute(
            url,
            "INSERT INTO trading.pm_universe_frame_pages "
            "(frame_id, page_no, endpoint, cursor_input, cursor_output, item_count, "
            " raw_artifact_id, raw_artifact_ref, raw_artifact_hash, received_at) "
            "VALUES (:f, 0, 'events_open', 'c9', 'c9', 1, :aid, :a, :a, :t)",
            {
                "f": fid, "aid": _seed_artifact(url, "b"), "a": _sha("b"),
                "t": datetime.now(timezone.utc),
            },
        )
    with pytest.raises(Exception, match="uq_pm_universe_frame_pages_frame_endpoint_cursor"):
        # 同一 (frame, endpoint, cursor_input) 重复页 → 拒绝（cursor 单调链）
        _execute(
            url,
            "INSERT INTO trading.pm_universe_frame_pages "
            "(frame_id, page_no, endpoint, cursor_input, cursor_output, item_count, "
            " raw_artifact_id, raw_artifact_ref, raw_artifact_hash, received_at) "
            "VALUES (:f, 1, 'markets_open', 'c0', 'c2', 1, :aid, :a, :a, :t)",
            {
                "f": fid, "aid": _seed_artifact(url, "c"), "a": _sha("c"),
                "t": datetime.now(timezone.utc),
            },
        )


# ---------------- 4. append-only / lifecycle / CAS ----------------

def test_market_append_only_guards(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V10, url)
    ids = _seed_market(url)
    mid = ids["market_id"]
    now = datetime.now(timezone.utc)

    _execute(
        url,
        "INSERT INTO trading.pm_market_versions "
        "(market_id, version_no, observed_at, received_at, normalized_hash) "
        "VALUES (:m, 1, :t, :t, :h)",
        {"m": mid, "t": now, "h": _sha("d")},
    )
    with pytest.raises(Exception, match="v2_immutable_row:pm_market_versions"):
        _execute(
            url,
            "UPDATE trading.pm_market_versions SET question='hacked' WHERE market_id=:m",
            {"m": mid},
        )
    with pytest.raises(Exception, match="v2_immutable_row:pm_market_versions"):
        _execute(url, "DELETE FROM trading.pm_market_versions WHERE market_id=:m", {"m": mid})

    tok = _query(url, "SELECT id FROM trading.pm_tokens WHERE token_id='tok-0'")[0][0]
    _execute(
        url,
        "INSERT INTO trading.pm_token_versions "
        "(token_id, version_no, outcome_index, outcome_label, observed_at, received_at) "
        "VALUES (:t, 1, 0, 'Yes', :now, :now)",
        {"t": tok, "now": now},
    )
    with pytest.raises(Exception, match="v2_immutable_row:pm_token_versions"):
        _execute(url, "DELETE FROM trading.pm_token_versions WHERE token_id=:t", {"t": tok})

    _execute(
        url,
        "INSERT INTO trading.pm_market_lifecycle_events "
        "(market_id, event_type, observed_at, received_at, payload_hash) "
        "VALUES (:m, 'created', :t, :t, :h)",
        {"m": mid, "t": now, "h": _sha("e")},
    )
    with pytest.raises(Exception, match="v2_immutable_row:pm_market_lifecycle_events"):
        _execute(
            url,
            "UPDATE trading.pm_market_lifecycle_events SET event_type='resolved' "
            "WHERE market_id=:m",
            {"m": mid},
        )


def test_frame_lifecycle_only_terminal_transition(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V10, url)
    fid = _seed_frame(url)
    _seed_terminal_pages(url, fid)
    frame_artifact_id = _seed_artifact(url, "f")

    _execute(
        url,
        "UPDATE trading.pm_universe_frames SET status='COMPLETE', completed_at=now(), "
        "page_count=4, total_events=1, total_markets=2, content_hash=:h, artifact_id=:a "
        "WHERE id=:f",
        {"f": fid, "h": _sha("f"), "a": frame_artifact_id},
    )
    # COMPLETE/FAILED 后全部列与 child-page 集合冻结。
    with pytest.raises(Exception, match="v2_universe_frame_immutable"):
        _execute(
            url, "UPDATE trading.pm_universe_frames SET total_markets=999 WHERE id=:f", {"f": fid}
        )
    with pytest.raises(Exception, match="v2_universe_frame_not_writable"):
        _execute(
            url,
            "INSERT INTO trading.pm_universe_frame_pages "
            "(frame_id, page_no, endpoint, item_count, raw_artifact_id, raw_artifact_ref, "
            " raw_artifact_hash, received_at) "
            "VALUES (:f, 4, 'markets_open', 0, :a, :h, :h, now())",
            {"f": fid, "a": frame_artifact_id, "h": _sha("f")},
        )
    with pytest.raises(Exception, match="v2_universe_frame_immutable"):
        _execute(
            url, "UPDATE trading.pm_universe_frames SET status='OPEN' WHERE id=:f", {"f": fid}
        )
    with pytest.raises(Exception, match="v2_universe_frame_immutable"):
        _execute(
            url, "UPDATE trading.pm_universe_frames SET status='FAILED' WHERE id=:f", {"f": fid}
        )
    with pytest.raises(Exception, match="v2_universe_frame_immutable"):
        _execute(url, "DELETE FROM trading.pm_universe_frames WHERE id=:f", {"f": fid})


def test_frame_complete_requires_full_cursor_chains_and_counts(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V10, url)
    fid = _seed_frame(url)
    aid = _seed_artifact(url, "g")
    _execute(
        url,
        "INSERT INTO trading.pm_universe_frame_pages "
        "(frame_id, page_no, endpoint, cursor_input, cursor_output, item_count, "
        " raw_artifact_id, raw_artifact_ref, raw_artifact_hash, received_at) "
        "VALUES (:f, 0, 'events_open', NULL, 'missing-next', 1, :a, :h, :h, now())",
        {"f": fid, "a": aid, "h": _sha("g")},
    )
    with pytest.raises(Exception, match="v2_universe_frame_cursor_chain_invalid"):
        _execute(
            url,
            "UPDATE trading.pm_universe_frames SET status='COMPLETE', completed_at=now(), "
            "page_count=1, total_events=1, content_hash=:h, artifact_id=:a WHERE id=:f",
            {"f": fid, "h": _sha("g"), "a": aid},
        )


def test_frame_lease_takeover_is_fenced_cas(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V10, url)
    now = datetime.now(timezone.utc)
    active = _seed_frame(url, started_at=now, lease_expires_at=now + timedelta(minutes=5))
    with pytest.raises(Exception, match="v2_universe_frame_lease_cas_failed"):
        _execute(
            url,
            "UPDATE trading.pm_universe_frames SET owner='worker-2', fencing_token=2, "
            "lease_expires_at=:lease WHERE id=:f",
            {"lease": now + timedelta(minutes=10), "f": active},
        )

    expired = _seed_frame(
        url,
        owner="worker-old",
        started_at=now - timedelta(minutes=10),
        lease_expires_at=now - timedelta(minutes=1),
    )
    _execute(
        url,
        "UPDATE trading.pm_universe_frames SET owner='worker-new', fencing_token=2, "
        "lease_expires_at=:lease WHERE id=:f",
        {"lease": now + timedelta(minutes=10), "f": expired},
    )
    assert _query(
        url,
        "SELECT owner, fencing_token FROM trading.pm_universe_frames WHERE id=:f",
        {"f": expired},
    ) == [("worker-new", 2)]


def test_market_current_cas_monotonic_observed_at(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V10, url)
    mid = _seed_market(url)["market_id"]

    _execute(
        url,
        "INSERT INTO trading.pm_market_current "
        "(market_id, condition_id, gamma_market_id, tokens_ok, mapping_state, eligible, "
        " current_version_no, observed_at) "
        "VALUES (:m, 'cond-1', 'mkt-1', true, 'complete', true, 1, :t)",
        {"m": mid, "t": datetime.now(timezone.utc) - timedelta(seconds=10)},
    )
    # 更新的 observed_at → 允许（新帧）
    _execute(
        url,
        "UPDATE trading.pm_market_current SET observed_at=:t, current_version_no=2 WHERE market_id=:m",
        {"m": mid, "t": datetime.now(timezone.utc)},
    )
    # 旧帧/乱序 observed_at 更小 → fail-closed
    with pytest.raises(Exception, match="v2_market_current_stale_overwrite"):
        _execute(
            url,
            "UPDATE trading.pm_market_current SET observed_at=:t, current_version_no=3 "
            "WHERE market_id=:m",
            {"m": mid, "t": datetime.now(timezone.utc) - timedelta(seconds=100)},
        )


# ---------------- 5. FK RESTRICT ----------------

def test_market_referenced_by_tokens_not_deletable(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V10, url)
    mid = _seed_market(url)["market_id"]
    with pytest.raises(Exception, match="fk_pm_tokens_market"):
        _execute(url, "DELETE FROM trading.pm_markets WHERE id=:m", {"m": mid})


# ---------------- 6. downgrade fail-closed ----------------

def test_downgrade_fail_closed_on_unknown_schema_object(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V10, url)
    before = set(_trading_tables(url))
    _execute(url, "CREATE TABLE trading.unknown_intruder (id integer)")
    with pytest.raises(Exception, match="v2_wp01b_unknown_object"):
        _run(command.downgrade, V2, url)
    # 整次 downgrade 外层事务回滚：unknown 与 modeled 表均保留，version 不倒退
    assert _query(url, "SELECT to_regclass('trading.unknown_intruder') IS NOT NULL") == [(True,)]
    assert set(_trading_tables(url)) == before | {"unknown_intruder"}
    assert _version(url) == [(V10,)]
