"""
WP-04 v2_0041 read projection migration —— 真 PostgreSQL 集成验收（Checkpoint D）。

覆盖：5 张投影表 roundtrip、keyset 索引 + ``alembic check`` modeled drift=0、
append-only 投影 immutable guard（UPDATE/DELETE 拒）、downgrade fail-closed 与
未知对象拒绝、临时库零残留。
"""

from pathlib import Path

import pytest
from alembic import command, util
from alembic.config import Config
from sqlalchemy import create_engine, text
from sqlalchemy.pool import NullPool

SERVE_DIR = Path(__file__).resolve().parents[3]
ALEMBIC_DIR = SERVE_DIR / "alembic"
V40 = "b1000040"
V41 = "b1000041"
V50 = "b1000050"
V51 = "b1000051"
V52 = "b1000052"
HEAD_REVISION = V52

PROJECTION_TABLES = [
    "ops_health_current", "pipeline_funnel_hourly", "account_risk_current",
    "provider_cost_daily", "latest_chain_summary",
]

_INDEXES = (
    "ix_ops_health_current_as_of",
    "ix_pipeline_funnel_hourly_as_of",
    "ix_account_risk_current_as_of",
    "ix_provider_cost_daily_as_of",
    "ix_latest_chain_summary_as_of",
)


def _run(cmd, revision, db_url):
    cfg = Config()
    cfg.set_main_option("script_location", str(ALEMBIC_DIR))
    engine = create_engine(db_url, poolclass=NullPool)
    conn = engine.connect()
    cfg.attributes["connection"] = conn
    try:
        cmd(cfg, revision)
    finally:
        conn.close()
        engine.dispose()


def _check_diffs(db_url):
    """运行 ``alembic check``，返回 diffs 列表（不抛）。"""
    cfg = Config()
    cfg.set_main_option("script_location", str(ALEMBIC_DIR))
    engine = create_engine(db_url, poolclass=NullPool)
    conn = engine.connect()
    cfg.attributes["connection"] = conn
    try:
        command.check(cfg)
        return []
    except util.AutogenerateDiffsDetected as e:
        return e.diffs
    finally:
        conn.close()
        engine.dispose()


def _query(db_url, sql, params=None):
    engine = create_engine(db_url)
    try:
        with engine.connect() as c:
            return c.execute(text(sql), params or {}).fetchall()
    finally:
        engine.dispose()


def _execute(db_url, sql, params=None):
    engine = create_engine(db_url)
    try:
        with engine.connect() as c:
            c.execute(text(sql), params or {})
            c.commit()
    finally:
        engine.dispose()


def _insert_id(db_url, sql, params=None):
    engine = create_engine(db_url)
    try:
        with engine.begin() as c:
            return c.execute(text(sql), params or {}).scalar_one()
    finally:
        engine.dispose()


def _version(db_url):
    return _query(db_url, "SELECT version_num FROM public.alembic_version")


def _trading_tables(db_url):
    return [r[0] for r in _query(
        db_url, "SELECT tablename FROM pg_tables WHERE schemaname='trading' ORDER BY 1"
    )]


_ROW_SPECS = {
    "ops_health_current": (
        "metric_name, metric_value, status, as_of, source_high_watermark, "
        "projection_version, projection_hash",
        "VALUES (:k, 1, 'ok', :asof, 1, 1, :h)",
        {"k": "m"},
    ),
    "pipeline_funnel_hourly": (
        "hour_start, stage, event_count, as_of, source_high_watermark, "
        "projection_version, projection_hash",
        "VALUES (:asof, 'episode', 1, :asof, 1, 1, :h)",
        {},
    ),
    "account_risk_current": (
        "portfolio_namespace, market_id, component_id, exposure, net_risk_capital, "
        "cvar, capital_days, as_of, source_high_watermark, projection_version, projection_hash",
        "VALUES ('shadow-guard', NULL, NULL, 0, 0, 0, 0, :asof, 1, 1, :h)",
        {},
    ),
    "provider_cost_daily": (
        "cost_date, provider, cost_kind, amount, as_of, source_high_watermark, "
        "projection_version, projection_hash",
        "VALUES ('2026-08-11'::date, 'perf', 'INFRASTRUCTURE', 0, :asof, 1, 1, :h)",
        {},
    ),
    "latest_chain_summary": (
        "chain_key, chain_value, period_end, as_of, source_high_watermark, "
        "projection_version, projection_hash",
        "VALUES ('decision.count', 0, :asof, :asof, 1, 1, :h)",
        {},
    ),
}


def _insert_projection_row(url, table, metric_name="m"):
    """向一张投影表插入一行（id/as_of/watermark/version/hash 全显式）。"""
    cols, vals, extra = _ROW_SPECS[table]
    params = {"asof": "2026-08-11T00:00:00Z", "h": "a" * 64}
    if "k" in extra:
        params["k"] = metric_name
    return _insert_id(
        url,
        "INSERT INTO trading.%s (%s) %s RETURNING id" % (table, cols, vals),
        params,
    )


def test_literal_empty_roundtrip(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V41, url)
    assert _version(url) == [(V41,)]
    assert set(PROJECTION_TABLES) <= set(_trading_tables(url))

    _run(command.downgrade, V40, url)
    assert _version(url) == [(V40,)]
    assert set(PROJECTION_TABLES).isdisjoint(set(_trading_tables(url)))

    _run(command.upgrade, V41, url)
    assert _version(url) == [(V41,)]


def test_tables_indexes_and_alembic_drift(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, "head", url)
    assert _version(url) == [(HEAD_REVISION,)]
    tables = set(_trading_tables(url))
    assert set(PROJECTION_TABLES) <= tables
    for idx in _INDEXES:
        assert _query(url, "SELECT to_regclass('trading.%s') IS NOT NULL" % idx) == [(True,)], idx

    diffs = _check_diffs(url)
    from tests.trading.fixtures.migration_helpers import split_dynamic_diffs

    _dynamic, modeled = split_dynamic_diffs(diffs)
    # 0041 无新分区；modeled 必须零 drift。
    assert modeled == [], f"modeled tables drift: {modeled}"


def test_immutable_projection_guards(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V41, url)
    for table in PROJECTION_TABLES:
        row_id = _insert_projection_row(url, table, metric_name=f"m-{table}")
        with pytest.raises(Exception, match=f"v2_immutable_row:{table}"):
            _execute(
                url,
                "UPDATE trading.%s SET source_high_watermark=99 WHERE id=:id" % table,
                {"id": row_id},
            )
        with pytest.raises(Exception, match=f"v2_immutable_row:{table}"):
            _execute(url, "DELETE FROM trading.%s WHERE id=:id" % table, {"id": row_id})


def test_downgrade_roundtrip_and_fail_closed(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V41, url)

    _run(command.downgrade, V40, url)
    assert _version(url) == [(V40,)]
    assert set(PROJECTION_TABLES).isdisjoint(set(_trading_tables(url)))

    _run(command.upgrade, V41, url)
    assert _version(url) == [(V41,)]
    before = set(_trading_tables(url))
    _execute(url, "CREATE TABLE trading.unknown_intruder_0041 (id integer)")
    with pytest.raises(
        Exception,
        match="v2_wp04_projection_unknown_object|v2_wp04_unknown_object|v2_trading_schema_not_empty",
    ):
        _run(command.downgrade, V40, url)
    assert _query(url, "SELECT to_regclass('trading.unknown_intruder_0041') IS NOT NULL") == [(True,)]
    assert set(_trading_tables(url)) == before | {"unknown_intruder_0041"}


def test_downgrade_rejects_unknown_index(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V41, url)
    _execute(url, "CREATE INDEX unknown_wp04_projection_idx ON trading.ops_health_current(status)")
    with pytest.raises(Exception, match="v2_wp04_projection_unknown_index"):
        _run(command.downgrade, V40, url)
    assert _version(url) == [(V41,)]
    _execute(url, "DROP INDEX trading.unknown_wp04_projection_idx")
    _run(command.downgrade, V40, url)
    assert _version(url) == [(V40,)]
    assert set(PROJECTION_TABLES).isdisjoint(set(_trading_tables(url)))
