"""
WP-05 v2_0050 execution readiness migration —— 真 PostgreSQL 集成验收（Checkpoint B）。

覆盖：empty/existing roundtrip、5 张新表 + vault 强化约束/trigger 存在、
``alembic check`` modeled drift=0（split_dynamic_diffs 白名单）、非空 vault precondition
rollback（``VAULT_BACKFILL_DECISION_REQUIRED`` 且 version 不前进）、downgrade fail-closed
未知对象拒绝、临时库零残留。
"""

from pathlib import Path

import pytest
from alembic import command, util
from alembic.config import Config
from sqlalchemy import create_engine, text
from sqlalchemy.pool import NullPool

SERVE_DIR = Path(__file__).resolve().parents[3]
ALEMBIC_DIR = SERVE_DIR / "alembic"
V41 = "b1000041"
V50 = "b1000050"
V51 = "b1000051"
V52 = "b1000052"
V70 = "b1000070"
V71 = "b1000071"
V72 = "b1000072"
V73 = "b1000076"
HEAD_REVISION = V73

NEW_TABLES = [
    "pm_accounts", "pm_balance_allowance_snapshots", "account_funds_current",
    "capital_reservations", "execution_leases",
]

_VAULT_ENTRY_COLS = ("secret_kind", "runtime_identity")
_VAULT_VERSION_COLS = ("version_no", "aad_context", "ciphertext_hash", "status")
_VAULT_ACCESS_COLS = ("secret_version_id", "identity", "key_version", "result")

_VAULT_CONSTRAINTS = (
    "ck_secret_vault_entries_secret_kind_known",
    "uq_secret_vault_versions_entry_version",
    "uq_secret_vault_versions_key_nonce",
    "ck_secret_vault_versions_status_known",
    "ck_secret_vault_versions_ciphertext_hash_hex",
    "fk_secret_access_events_version",
)

_NEW_TRIGGERS = (
    "trg_secret_vault_versions_lifecycle",
    "trg_secret_vault_versions_single_active",
    "trg_capital_reservations_lifecycle",
    "trg_pm_balance_allowance_snapshots_immutable",
)


def _run(cmd, revision, db_url):
    cfg = Config()
    cfg.set_main_option("script_location", str(ALEMBIC_DIR))
    engine = create_engine(db_url, poolclass=NullPool)
    conn = engine.connect()
    cfg.attributes["connection"] = conn
    try:
        cmd(cfg, revision)
    finally:
        conn.close()
        engine.dispose()


def _check_diffs(db_url):
    cfg = Config()
    cfg.set_main_option("script_location", str(ALEMBIC_DIR))
    engine = create_engine(db_url, poolclass=NullPool)
    conn = engine.connect()
    cfg.attributes["connection"] = conn
    try:
        command.check(cfg)
        return []
    except util.AutogenerateDiffsDetected as e:
        return e.diffs
    finally:
        conn.close()
        engine.dispose()


def _query(db_url, sql, params=None):
    engine = create_engine(db_url)
    try:
        with engine.connect() as c:
            return c.execute(text(sql), params or {}).fetchall()
    finally:
        engine.dispose()


def _execute(db_url, sql, params=None):
    engine = create_engine(db_url)
    try:
        with engine.connect() as c:
            c.execute(text(sql), params or {})
            c.commit()
    finally:
        engine.dispose()


def _version(db_url):
    return _query(db_url, "SELECT version_num FROM public.alembic_version")


def _trading_tables(db_url):
    return [r[0] for r in _query(
        db_url, "SELECT tablename FROM pg_tables WHERE schemaname='trading' ORDER BY 1"
    )]


def _columns(db_url, table):
    return [r[0] for r in _query(
        db_url,
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_schema='trading' AND table_name=:t",
        {"t": table},
    )]


def _constraints(db_url, table):
    return [r[0] for r in _query(
        db_url,
        "SELECT conname FROM pg_constraint c "
        "JOIN pg_class t ON t.oid=c.conrelid "
        "JOIN pg_namespace n ON n.oid=t.relnamespace "
        "WHERE n.nspname='trading' AND t.relname=:t",
        {"t": table},
    )]


def _triggers(db_url, table=None):
    sql = (
        "SELECT t.tgname FROM pg_trigger t "
        "JOIN pg_class tbl ON tbl.oid=t.tgrelid "
        "JOIN pg_namespace n ON n.oid=tbl.relnamespace "
        "WHERE n.nspname='trading' AND NOT t.tgisinternal"
    )
    params = {}
    if table:
        sql += " AND tbl.relname=:t"
        params = {"t": table}
    return [r[0] for r in _query(db_url, sql, params)]


def test_literal_empty_roundtrip(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V50, url)
    assert _version(url) == [(V50,)]
    assert set(NEW_TABLES) <= set(_trading_tables(url))

    _run(command.downgrade, V41, url)
    assert _version(url) == [(V41,)]
    assert set(NEW_TABLES).isdisjoint(set(_trading_tables(url)))
    # vault 强化必须被撤销（降回 0002 原样）
    assert "version_no" not in _columns(url, "secret_vault_versions")
    assert "secret_kind" not in _columns(url, "secret_vault_entries")

    _run(command.upgrade, V50, url)
    assert _version(url) == [(V50,)]
    assert set(NEW_TABLES) <= set(_trading_tables(url))


def test_tables_constraints_and_alembic_drift(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, "head", url)
    assert _version(url) == [(HEAD_REVISION,)]
    tables = set(_trading_tables(url))
    assert set(NEW_TABLES) <= tables

    # vault 强化列
    assert set(_VAULT_ENTRY_COLS) <= set(_columns(url, "secret_vault_entries"))
    assert set(_VAULT_VERSION_COLS) <= set(_columns(url, "secret_vault_versions"))
    assert set(_VAULT_ACCESS_COLS) <= set(_columns(url, "secret_access_events"))
    # vault 强化约束
    all_cons = set(_constraints(url, "secret_vault_entries")) | set(
        _constraints(url, "secret_vault_versions")
    ) | set(_constraints(url, "secret_access_events"))
    assert set(_VAULT_CONSTRAINTS) <= all_cons
    # 新表约束
    assert "uq_pm_accounts_key" in _constraints(url, "pm_accounts")
    assert "ck_account_funds_current_identity" in _constraints(url, "account_funds_current")
    assert "ck_capital_reservations_status_known" in _constraints(url, "capital_reservations")
    assert "uq_execution_leases_account_role" in _constraints(url, "execution_leases")
    # trigger
    all_trg = set(_triggers(url))
    assert set(_NEW_TRIGGERS) <= all_trg

    diffs = _check_diffs(url)
    from tests.trading.fixtures.migration_helpers import split_dynamic_diffs

    _dynamic, modeled = split_dynamic_diffs(diffs)
    assert modeled == [], f"modeled tables drift: {modeled}"


def test_vault_precondition_rollback(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V41, url)
    # 塞一行无法无歧义补齐的 vault 行
    _execute(
        url,
        "INSERT INTO trading.secret_vault_entries (name, status) VALUES ('legacy-entry', 'active')",
    )
    with pytest.raises(Exception, match="VAULT_BACKFILL_DECISION_REQUIRED"):
        _run(command.upgrade, V50, url)
    # version 不前进，且 5 张新表不存在
    assert _version(url) == [(V41,)]
    assert set(NEW_TABLES).isdisjoint(set(_trading_tables(url)))


def test_downgrade_fail_closed_unknown_object(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V50, url)
    before = set(_trading_tables(url))
    _execute(url, "CREATE TABLE trading.unknown_intruder_0050 (id integer)")
    with pytest.raises(Exception, match="v2_wp05_execution_vault_unknown_object"):
        _run(command.downgrade, V41, url)
    assert _version(url) == [(V50,)]
    assert set(_trading_tables(url)) == before | {"unknown_intruder_0050"}
    # 清理后可降级
    _execute(url, "DROP TABLE trading.unknown_intruder_0050")
    _run(command.downgrade, V41, url)
    assert _version(url) == [(V41,)]
    assert set(NEW_TABLES).isdisjoint(set(_trading_tables(url)))


def test_existing_base_fixture_compatible(temp_pg_db):
    """在既有 Base public schema（base_legacy_schema.sql fixture）之上 upgrade head 不破坏 legacy 表。"""
    import subprocess

    url = temp_pg_db.url
    fixture_sql = SERVE_DIR / "tests/trading/fixtures/base_legacy_schema.sql"
    cmd = ["psql", "-q", "-v", "ON_ERROR_STOP=1"]
    if url.startswith("postgresql+psycopg:///"):
        cmd += ["-d", url.split("///", 1)[1]]
    else:
        cmd += [url]
    run = subprocess.run(cmd + ["-f", str(fixture_sql)], capture_output=True, text=True)
    assert run.returncode == 0, f"base fixture load failed: {run.stderr[-2000:]}"
    _run(command.upgrade, "head", url)
    public_tables = [r[0] for r in _query(
        url, "SELECT tablename FROM pg_tables WHERE schemaname='public' ORDER BY 1"
    )]
    assert "alembic_version" in public_tables
    # base legacy fixture 至少保留 18 张核心表（抽样）
    for core in ("admin_users", "users", "settings", "menus", "roles"):
        assert core in public_tables, f"legacy Base table {core} missing"
