"""
WP-05 v2_0051 execution orders migration —— 真 PostgreSQL 集成（Checkpoint C）。

覆盖：empty/existing roundtrip、9 张新表 + 4 张既有表 lineage、
``alembic check`` modeled drift=0（split_dynamic_diffs 白名单）、downgrade fail-closed
未知对象拒绝、临时库零残留。
"""

from pathlib import Path

import pytest
from alembic import command, util
from alembic.config import Config
from sqlalchemy import create_engine, text
from sqlalchemy.pool import NullPool

SERVE_DIR = Path(__file__).resolve().parents[3]
ALEMBIC_DIR = SERVE_DIR / "alembic"
V50 = "b1000050"
V51 = "b1000051"
HEAD_REVISION = V51

NEW_TABLES = [
    "execution_authorization_envelopes",
    "exchange_order_attempts",
    "exchange_orders",
    "order_state_events",
    "exchange_trades",
    "account_reconciliations",
    "workflow_events",
    "external_call_attempts",
    "alert_events",
]

_LINEAGE_TABLES = ("executions", "positions", "position_lots", "ledger_transactions")
_LINEAGE_COLS = ("account_id", "envelope_id", "order_id", "trade_id")

_NEW_TRIGGERS = (
    "trg_execution_authorization_envelopes_lifecycle",
    "trg_exchange_orders_lifecycle",
    "trg_exchange_order_attempts_lifecycle",
    "trg_account_reconciliations_lifecycle",
    "trg_execution_envelope_permission_check",
    "trg_execution_envelope_intent_bind",
    "trg_order_state_events_immutable",
    "trg_exchange_trades_immutable",
    "trg_external_call_attempts_immutable",
    "trg_workflow_events_immutable",
    "trg_alert_events_immutable",
)


def _run(cmd, revision, db_url):
    cfg = Config()
    cfg.set_main_option("script_location", str(ALEMBIC_DIR))
    engine = create_engine(db_url, poolclass=NullPool)
    conn = engine.connect()
    cfg.attributes["connection"] = conn
    try:
        cmd(cfg, revision)
    finally:
        conn.close()
        engine.dispose()


def _check_diffs(db_url):
    cfg = Config()
    cfg.set_main_option("script_location", str(ALEMBIC_DIR))
    engine = create_engine(db_url, poolclass=NullPool)
    conn = engine.connect()
    cfg.attributes["connection"] = conn
    try:
        command.check(cfg)
        return []
    except util.AutogenerateDiffsDetected as e:
        return e.diffs
    finally:
        conn.close()
        engine.dispose()


def _query(db_url, sql, params=None):
    engine = create_engine(db_url)
    try:
        with engine.connect() as c:
            return c.execute(text(sql), params or {}).fetchall()
    finally:
        engine.dispose()


def _execute(db_url, sql, params=None):
    engine = create_engine(db_url)
    try:
        with engine.connect() as c:
            c.execute(text(sql), params or {})
            c.commit()
    finally:
        engine.dispose()


def _version(db_url):
    return _query(db_url, "SELECT version_num FROM public.alembic_version")


def _trading_tables(db_url):
    return [r[0] for r in _query(
        db_url, "SELECT tablename FROM pg_tables WHERE schemaname='trading' ORDER BY 1"
    )]


def _columns(db_url, table):
    return [r[0] for r in _query(
        db_url,
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_schema='trading' AND table_name=:t",
        {"t": table},
    )]


def _constraints(db_url, table):
    return [r[0] for r in _query(
        db_url,
        "SELECT conname FROM pg_constraint c "
        "JOIN pg_class t ON t.oid=c.conrelid "
        "JOIN pg_namespace n ON n.oid=t.relnamespace "
        "WHERE n.nspname='trading' AND t.relname=:t",
        {"t": table},
    )]


def _triggers(db_url, table=None):
    sql = (
        "SELECT t.tgname FROM pg_trigger t "
        "JOIN pg_class tbl ON tbl.oid=t.tgrelid "
        "JOIN pg_namespace n ON n.oid=tbl.relnamespace "
        "WHERE n.nspname='trading' AND NOT t.tgisinternal"
    )
    params = {}
    if table:
        sql += " AND tbl.relname=:t"
        params = {"t": table}
    return [r[0] for r in _query(db_url, sql, params)]


def test_literal_empty_roundtrip(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V51, url)
    assert _version(url) == [(V51,)]
    assert set(NEW_TABLES) <= set(_trading_tables(url))

    _run(command.downgrade, V50, url)
    assert _version(url) == [(V50,)]
    assert set(NEW_TABLES).isdisjoint(set(_trading_tables(url)))
    # lineage 列必须被移除
    for table in _LINEAGE_TABLES:
        assert "account_id" not in _columns(url, table), f"lineage not removed: {table}"

    _run(command.upgrade, V51, url)
    assert _version(url) == [(V51,)]
    assert set(NEW_TABLES) <= set(_trading_tables(url))


def test_tables_constraints_and_alembic_drift(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, "head", url)
    assert _version(url) == [(HEAD_REVISION,)]
    tables = set(_trading_tables(url))
    assert set(NEW_TABLES) <= tables

    # 9 张表关键约束
    assert "uq_execution_authorization_envelopes_key" in _constraints(url, "execution_authorization_envelopes")
    assert "uq_execution_authorization_envelopes_hash" in _constraints(url, "execution_authorization_envelopes")
    assert "uq_execution_authorization_envelopes_idempotency" in _constraints(url, "execution_authorization_envelopes")
    assert "ck_execution_authorization_envelopes_authority_known" in _constraints(url, "execution_authorization_envelopes")
    assert "uq_exchange_order_attempts_envelope_no" in _constraints(url, "exchange_order_attempts")
    assert "uq_exchange_orders_account_ext" in _constraints(url, "exchange_orders")
    assert "uq_exchange_trades_account_ext" in _constraints(url, "exchange_trades")
    assert "ck_account_reconciliations_completed_pair" in _constraints(url, "account_reconciliations")
    assert "ck_external_call_attempts_request_hash_hex" in _constraints(url, "external_call_attempts")

    # lineage 列
    for table in _LINEAGE_TABLES:
        cols = set(_columns(url, table))
        for col in _LINEAGE_COLS:
            if table == "positions" and col == "trade_id":
                continue
            if table == "position_lots" and col == "envelope_id":
                continue
            assert col in cols, f"lineage col {col} missing on {table}"

    # triggers
    all_trg = set(_triggers(url))
    assert set(_NEW_TRIGGERS) <= all_trg

    diffs = _check_diffs(url)
    from tests.trading.fixtures.migration_helpers import split_dynamic_diffs

    _dynamic, modeled = split_dynamic_diffs(diffs)
    assert modeled == [], f"modeled tables drift: {modeled}"


def test_downgrade_fail_closed_unknown_object(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, V51, url)
    before = set(_trading_tables(url))
    _execute(url, "CREATE TABLE trading.unknown_intruder_0051 (id integer)")
    with pytest.raises(Exception, match="v2_wp05_execution_orders_unknown_object"):
        _run(command.downgrade, V50, url)
    assert _version(url) == [(V51,)]
    assert set(_trading_tables(url)) == before | {"unknown_intruder_0051"}
    _execute(url, "DROP TABLE trading.unknown_intruder_0051")
    _run(command.downgrade, V50, url)
    assert _version(url) == [(V50,)]
    assert set(NEW_TABLES).isdisjoint(set(_trading_tables(url)))


def test_existing_base_fixture_compatible(temp_pg_db):
    import subprocess

    url = temp_pg_db.url
    fixture_sql = SERVE_DIR / "tests/trading/fixtures/base_legacy_schema.sql"
    cmd = ["psql", "-q", "-v", "ON_ERROR_STOP=1"]
    if url.startswith("postgresql+psycopg:///"):
        cmd += ["-d", url.split("///", 1)[1]]
    else:
        cmd += [url]
    run = subprocess.run(cmd + ["-f", str(fixture_sql)], capture_output=True, text=True)
    assert run.returncode == 0, f"base fixture load failed: {run.stderr[-2000:]}"
    _run(command.upgrade, "head", url)
    public_tables = [r[0] for r in _query(
        url, "SELECT tablename FROM pg_tables WHERE schemaname='public' ORDER BY 1"
    )]
    assert "alembic_version" in public_tables
    for core in ("admin_users", "users", "settings"):
        assert core in public_tables, f"legacy Base table {core} missing"
