"""
WP-01A-02 v2_0002 migration —— 真 PostgreSQL 集成验收（Checkpoint C §4.3）。

前置：``V2_TEST_ADMIN_DATABASE_URL`` 存在，否则整模块 skip。在独立 ``pm_v2_test_*``
临时库执行，从不在管理/业务库跑 downgrade；删除沿用 01A-00 的安全边界。

覆盖：
1. literal-empty roundtrip：b1000001 → b1000002 → b1000001 → b1000002；trading schema +
   20 表 + 3 分区；public 不产生对象；
2. existing-Base fixture roundtrip：Base 对象（18 表 + alembic_version）在升级/降级后
   保持不变，trading 对象被干净移除；
3. ``alembic check`` drift：对 20 张 modeled 表零 drift，唯一 diff 是动态分区子表
   （SQLAlchemy metadata 无法静态表达，按 ``outbox_delivery_history_<YYYYMM>`` 白名单接受）；
4. 分区语义：真实 RANGE 分区、可写入、分区键含 completed_at；
5. downgrade fail-closed：trading schema 含未知对象时禁止删除并抛错、无 CASCADE 副作用。
"""

import os
import subprocess
import uuid
from datetime import datetime, timezone
from pathlib import Path

import pytest
from alembic import command, util
from alembic.config import Config
from sqlalchemy import create_engine, text
from sqlalchemy.engine import make_url
from sqlalchemy.pool import NullPool

SERVE_DIR = Path(__file__).resolve().parents[3]
ALEMBIC_DIR = SERVE_DIR / "alembic"
FIXTURE_SQL = SERVE_DIR / "tests/trading/fixtures/base_legacy_schema.sql"
V1 = "b1000001"
V2 = "b1000002"


def _run(cmd, revision, db_url):
    cfg = Config()
    cfg.set_main_option("script_location", str(ALEMBIC_DIR))
    engine = create_engine(db_url, poolclass=NullPool)
    conn = engine.connect()
    cfg.attributes["connection"] = conn
    try:
        cmd(cfg, revision)
    finally:
        conn.close()
        engine.dispose()


def _check_diffs(db_url):
    """运行 ``alembic check``，返回 diffs 列表（不抛）。"""
    cfg = Config()
    cfg.set_main_option("script_location", str(ALEMBIC_DIR))
    engine = create_engine(db_url, poolclass=NullPool)
    conn = engine.connect()
    cfg.attributes["connection"] = conn
    try:
        command.check(cfg)
        return []
    except util.AutogenerateDiffsDetected as e:
        return e.diffs
    finally:
        conn.close()
        engine.dispose()


def _query(db_url, sql, params=None):
    engine = create_engine(db_url)
    try:
        with engine.connect() as c:
            return c.execute(text(sql), params or {}).fetchall()
    finally:
        engine.dispose()


def _execute(db_url, sql, params=None):
    """执行 DML/DDL（不读取行）。"""
    engine = create_engine(db_url)
    try:
        with engine.connect() as c:
            c.execute(text(sql), params or {})
            c.commit()
    finally:
        engine.dispose()


def _version(db_url):
    return _query(db_url, "SELECT version_num FROM public.alembic_version")


def _trading_tables(db_url):
    return [r[0] for r in _query(
        db_url, "SELECT tablename FROM pg_tables WHERE schemaname='trading' ORDER BY 1"
    )]


def _public_tables(db_url):
    return [r[0] for r in _query(
        db_url, "SELECT tablename FROM pg_tables WHERE schemaname='public' ORDER BY 1"
    )]


def _apply_fixture(db_url):
    u = make_url(db_url)
    cmd = ["psql", "-q", "-v", "ON_ERROR_STOP=1"]
    if u.host:
        cmd += ["-h", u.host]
    if u.port:
        cmd += ["-p", str(u.port)]
    if u.username:
        cmd += ["-U", u.username]
    cmd += ["-d", u.database]
    env = dict(os.environ)
    if u.password:
        env["PGPASSWORD"] = u.password
    r = subprocess.run(cmd + ["-f", str(FIXTURE_SQL)], capture_output=True, text=True, env=env)
    assert r.returncode == 0, r.stderr[-2000:]


def test_literal_empty_roundtrip(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, "head", url)
    assert _version(url) == [(V2,)]
    tables = _trading_tables(url)
    assert len([t for t in tables if not t.startswith("outbox_delivery_history_")]) == 20
    assert len([t for t in tables if t.startswith("outbox_delivery_history_")]) == 3
    assert _public_tables(url) == ["alembic_version"]  # public 不产生对象

    _run(command.downgrade, V1, url)
    assert _version(url) == [(V1,)]
    assert _trading_tables(url) == []
    assert _query(url, "SELECT 1 FROM pg_namespace WHERE nspname='trading'") == []

    _run(command.upgrade, "head", url)
    assert _version(url) == [(V2,)]


def test_existing_base_fixture_roundtrip(temp_pg_db):
    url = temp_pg_db.url
    _apply_fixture(url)
    before_base = sorted(t for t in _public_tables(url) if t != "alembic_version")

    _run(command.upgrade, "head", url)
    assert _version(url) == [(V2,)]
    # Base 18 表原样；upgrade 只新增 Alembic 管理的 version 表
    assert sorted(_public_tables(url)) == sorted(before_base + ["alembic_version"])
    assert len([t for t in _trading_tables(url) if not t.startswith("outbox_delivery_history_")]) == 20

    _run(command.downgrade, V1, url)
    assert _version(url) == [(V1,)]
    assert _trading_tables(url) == []
    assert sorted(_public_tables(url)) == sorted(before_base + ["alembic_version"])
    assert _query(url, "SELECT 1 FROM pg_namespace WHERE nspname='trading'") == []


def test_metadata_compare_zero_drift_on_modeled_tables(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, "head", url)
    diffs = _check_diffs(url)

    partition_diffs = []
    modeled_diffs = []
    for d in diffs:
        kind = d[0]
        name = ""
        if kind in ("remove_table", "remove_index"):
            name = getattr(d[1], "name", "")
        if name.startswith("outbox_delivery_history_"):
            partition_diffs.append(name)
        else:
            modeled_diffs.append(d)
    # 唯一允许的 diff：3 个动态分区子表 + 各自继承索引（metadata 无法静态表达）
    assert len(partition_diffs) == 6, f"partition diffs: {partition_diffs}"
    assert all(n.startswith("outbox_delivery_history_2") for n in partition_diffs)
    assert modeled_diffs == [], f"modeled 20 表存在 drift: {modeled_diffs}"


def test_partitions_are_real_range_partitions_and_writable(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, "head", url)
    assert _query(
        url,
        "SELECT partstrat FROM pg_partitioned_table p "
        "JOIN pg_class c ON c.oid=p.partrelid "
        "JOIN pg_namespace n ON n.oid=c.relnamespace "
        "WHERE n.nspname='trading' AND c.relname='outbox_delivery_history'",
    ) == [("r",)]
    ev = "a" * 64
    _execute(
        url,
        "INSERT INTO trading.outbox_delivery_history "
        "(outbox_event_id, outbox_id, completed_at, status, consumer, attempt) "
        "VALUES (:e, 1, :t, 'DELIVERED', 'c', 1)",
        {"e": ev, "t": datetime.now(timezone.utc).replace(day=5)},
    )
    assert _query(
        url, "SELECT status FROM trading.outbox_delivery_history WHERE outbox_event_id=:e", {"e": ev}
    ) == [("DELIVERED",)]


def test_artifact_ref_shape_and_controlled_values_are_enforced(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, "head", url)
    sha = "b" * 64
    locator = f"cas/v1/sha256/{sha[:2]}/{sha[2:4]}/{sha}.zst"
    _execute(
        url,
        "INSERT INTO trading.artifact_objects "
        "(sha256, original_size, stored_size, mime, compression, storage_driver, "
        " storage_version, locator) "
        "VALUES (:sha, 100, 40, 'application/octet-stream', 'zstd', 'local', "
        "        'cas/v1', :locator)",
        {"sha": sha, "locator": locator},
    )
    assert _query(
        url,
        "SELECT mime, compression, storage_version FROM trading.artifact_objects "
        "WHERE sha256=:sha",
        {"sha": sha},
    ) == [("application/octet-stream", "zstd", "cas/v1")]

    with pytest.raises(Exception, match="ck_artifact_objects_compression_known"):
        _execute(
            url,
            "INSERT INTO trading.artifact_objects "
            "(sha256, original_size, stored_size, mime, compression, storage_driver, "
            " storage_version, locator) "
            "VALUES (:sha, 1, 1, 'text/plain', 'gzip', 'local', 'cas/v1', '/bad')",
            {"sha": "c" * 64},
        )
    with pytest.raises(Exception, match="ck_artifact_objects_storage_version_known"):
        _execute(
            url,
            "INSERT INTO trading.artifact_objects "
            "(sha256, original_size, stored_size, mime, compression, storage_driver, "
            " storage_version, locator) "
            "VALUES (:sha, 1, 1, 'text/plain', 'none', 'local', '1', :locator)",
            {
                "sha": "d" * 64,
                "locator": "cas/v1/sha256/dd/dd/" + "d" * 64 + ".raw",
            },
        )
    with pytest.raises(Exception, match="ck_artifact_objects_raw_size_equal"):
        _execute(
            url,
            "INSERT INTO trading.artifact_objects "
            "(sha256, original_size, stored_size, mime, compression, storage_driver, "
            " storage_version, locator) "
            "VALUES (:sha, 2, 1, 'text/plain', 'none', 'local', 'cas/v1', :locator)",
            {
                "sha": "6" * 64,
                "locator": "cas/v1/sha256/66/66/" + "6" * 64 + ".raw",
            },
        )
    with pytest.raises(Exception, match="ck_artifact_objects_locator_canonical"):
        _execute(
            url,
            "INSERT INTO trading.artifact_objects "
            "(sha256, original_size, stored_size, mime, compression, storage_driver, "
            " storage_version, locator) "
            "VALUES (:sha, 1, 1, 'text/plain', 'none', 'local', 'cas/v1', '/bad')",
            {"sha": "7" * 64},
        )

    _execute(
        url,
        "INSERT INTO trading.capital_permission_manifests "
        "(name, mode, capability, limits, evaluation_capital, authorized_capital, "
        " content_hash) VALUES "
        "('canary-ok', 'canary', '{}'::jsonb, '{}'::jsonb, 0, 0, :hash)",
        {"hash": "e" * 64},
    )
    with pytest.raises(Exception, match="ck_capital_permission_manifests_mode_known"):
        _execute(
            url,
            "INSERT INTO trading.capital_permission_manifests "
            "(name, mode, capability, limits, evaluation_capital, authorized_capital, "
            " content_hash) VALUES "
            "('paper-bad', 'paper', '{}'::jsonb, '{}'::jsonb, 0, 0, :hash)",
            {"hash": "f" * 64},
        )

    _execute(url, "INSERT INTO trading.secret_vault_entries (name) VALUES ('probe')")
    entry_id = _query(
        url, "SELECT id FROM trading.secret_vault_entries WHERE name='probe'"
    )[0][0]
    _execute(
        url,
        "INSERT INTO trading.secret_vault_versions "
        "(entry_id, key_id, key_version, nonce, ciphertext, aad_hash, algorithm) "
        "VALUES (:entry, 'key', 'v1', 'nonce', decode('aa','hex'), :hash, 'aes-256-gcm')",
        {"entry": entry_id, "hash": "1" * 64},
    )
    with pytest.raises(Exception, match="ck_secret_vault_versions_algorithm_known"):
        _execute(
            url,
            "INSERT INTO trading.secret_vault_versions "
            "(entry_id, key_id, key_version, nonce, ciphertext, aad_hash, algorithm) "
            "VALUES (:entry, 'key', 'v2', 'nonce', decode('aa','hex'), :hash, "
            "        'aes-256-cbc')",
            {"entry": entry_id, "hash": "2" * 64},
        )


def test_database_immutability_guards_allow_only_lifecycle_transitions(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, "head", url)

    guarded_tables = {
        row[0]
        for row in _query(
            url,
            "SELECT DISTINCT event_object_table FROM information_schema.triggers "
            "WHERE trigger_schema='trading' AND trigger_name LIKE 'trg_%'",
        )
    }
    partition_guards = {
        name for name in guarded_tables if name.startswith("outbox_delivery_history_")
    }
    assert len(partition_guards) == 3
    assert guarded_tables - partition_guards == {
        "artifact_objects",
        "artifact_lineage_edges",
        "secret_vault_entries",
        "secret_vault_versions",
        "secret_access_events",
        "idempotency_claims",
        "outbox_delivery_history",
        "job_completions",
        "archive_manifests",
        "retention_manifests",
        "runtime_config_versions",
        "strategy_objective_contracts",
        "strategy_versions",
        "execution_spec_versions",
        "capital_permission_manifests",
        "release_manifests",
        "model_role_bindings",
        "policy_type_scopes",
        "policy_freezes",
    }

    sha = "3" * 64
    _execute(
        url,
        "INSERT INTO trading.artifact_objects "
        "(sha256, original_size, stored_size, mime, compression, storage_driver, "
        " storage_version, locator) "
        "VALUES (:sha, 1, 1, 'text/plain', 'none', 'local', 'cas/v1', :locator)",
        {
            "sha": sha,
            "locator": "cas/v1/sha256/33/33/" + sha + ".raw",
        },
    )
    with pytest.raises(Exception, match="v2_immutable_row:artifact_objects"):
        _execute(
            url,
            "UPDATE trading.artifact_objects SET locator='/changed' WHERE sha256=:sha",
            {"sha": sha},
        )
    with pytest.raises(Exception, match="v2_immutable_row:artifact_objects"):
        _execute(
            url, "DELETE FROM trading.artifact_objects WHERE sha256=:sha", {"sha": sha}
        )

    _execute(
        url,
        "INSERT INTO trading.archive_manifests (content, content_hash) "
        "VALUES (jsonb_build_object('v', 1), :hash)",
        {"hash": "4" * 64},
    )
    _execute(
        url,
        "UPDATE trading.archive_manifests SET status='committed' WHERE content_hash=:hash",
        {"hash": "4" * 64},
    )
    with pytest.raises(Exception, match="v2_manifest_immutable:archive_manifests"):
        _execute(
            url,
            "UPDATE trading.archive_manifests SET content=jsonb_build_object('v', 2) "
            "WHERE content_hash=:hash",
            {"hash": "4" * 64},
        )
    with pytest.raises(Exception, match="v2_manifest_immutable:archive_manifests"):
        _execute(
            url,
            "DELETE FROM trading.archive_manifests WHERE content_hash=:hash",
            {"hash": "4" * 64},
        )

    _execute(
        url,
        "INSERT INTO trading.runtime_config_versions "
        "(config_key, version_no, content, schema_version, content_hash) "
        "VALUES ('probe', 1, jsonb_build_object('v', 1), 1, :hash)",
        {"hash": "5" * 64},
    )
    # Draft content remains editable; publication must be a content-preserving transition.
    _execute(
        url,
        "UPDATE trading.runtime_config_versions SET content=jsonb_build_object('v', 2) "
        "WHERE config_key='probe'",
    )
    _execute(
        url,
        "UPDATE trading.runtime_config_versions SET status='active' "
        "WHERE config_key='probe'",
    )
    with pytest.raises(Exception, match="v2_published_control_immutable"):
        _execute(
            url,
            "UPDATE trading.runtime_config_versions SET content=jsonb_build_object('v', 3) "
            "WHERE config_key='probe'",
        )
    _execute(
        url,
        "UPDATE trading.runtime_config_versions SET status='retired' "
        "WHERE config_key='probe'",
    )
    with pytest.raises(Exception, match="v2_published_control_immutable"):
        _execute(
            url,
            "DELETE FROM trading.runtime_config_versions WHERE config_key='probe'",
        )

    # Vault identity only supports the explicit active -> disabled lifecycle; versions and
    # access facts are immutable.  This is a DB boundary, not an ORM convention.
    _execute(url, "INSERT INTO trading.secret_vault_entries (name) VALUES ('guarded')")
    entry_id = _query(
        url, "SELECT id FROM trading.secret_vault_entries WHERE name='guarded'"
    )[0][0]
    _execute(
        url,
        "INSERT INTO trading.secret_vault_versions "
        "(entry_id,key_id,key_version,nonce,ciphertext,aad_hash,algorithm) "
        "VALUES (:entry,'k','v1','n',decode('aa','hex'),:hash,'aes-256-gcm')",
        {"entry": entry_id, "hash": "8" * 64},
    )
    with pytest.raises(Exception, match="v2_immutable_row:secret_vault_versions"):
        _execute(
            url,
            "UPDATE trading.secret_vault_versions SET key_version='v2' "
            "WHERE entry_id=:entry",
            {"entry": entry_id},
        )
    with pytest.raises(Exception, match="v2_vault_entry_immutable"):
        _execute(
            url,
            "UPDATE trading.secret_vault_entries SET name='renamed' WHERE id=:entry",
            {"entry": entry_id},
        )
    _execute(
        url,
        "UPDATE trading.secret_vault_entries SET status='disabled' WHERE id=:entry",
        {"entry": entry_id},
    )
    with pytest.raises(Exception, match="v2_vault_entry_immutable"):
        _execute(
            url,
            "UPDATE trading.secret_vault_entries SET status='active' WHERE id=:entry",
            {"entry": entry_id},
        )


def test_downgrade_fail_closed_on_unknown_schema_object(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, "head", url)
    before = set(_trading_tables(url))
    _execute(url, "CREATE TABLE trading.unknown_intruder (id integer)")
    with pytest.raises(Exception, match="v2_trading_schema_not_empty"):
        _run(command.downgrade, V1, url)
    # 整次 downgrade 在外层事务中回滚：未知对象与 20 张 modeled 表均保留，
    # version 也不得倒退；绝不出现半拆 schema。
    assert _query(url, "SELECT to_regclass('trading.unknown_intruder') IS NOT NULL") == [(True,)]
    tables = set(_trading_tables(url))
    assert "unknown_intruder" in tables
    assert tables == before | {"unknown_intruder"}
    assert _version(url) == [(V2,)]
