"""
WP-01A-01 v2_0001 Base 兼容合同 —— 真 PostgreSQL 集成验收（任务 §6.2）。

前置：``V2_TEST_ADMIN_DATABASE_URL`` 存在，否则整模块 skip。fixture 在独立
``pm_v2_test_*`` 临时库执行，从不在管理/业务库跑 downgrade；删除沿用 01A-00 的
安全边界（前缀 + 非 template 双重校验 fail-closed）。

覆盖：
1. literal-empty：upgrade head → downgrade cdabba1e3903 → upgrade head，不创建任何 Base 表；
2. canonical fixture：升级前后 Base schema 规范化 fingerprint 完全一致，只有
   ``public.alembic_version`` 变化；``alembic check`` 无 Base drift；
3. 添加未知 public 表 + 额外 index/CHECK/default/trigger 后再升级，全部逐项保留；
4. partial 与 incompatible fixture 均在 version 前进前失败，事务回滚且无对象变化；
5. 测试后 ``pm_v2_test_* / pm_v2_fixture_*`` 临时库零残留；
6. （WP-01A-01-r1）复合主键列顺序等价性：``admin_user_roles`` / ``article_keywords`` /
   ``role_menus`` 三组反序 PK，online upgrade 与实际应用 offline SQL 均以
   ``v2_base_schema_incompatible`` 失败，version 停在基线、无部分 DDL；canonical
   fixture 的 offline upgrade 仍成功到 ``b1000001``。
"""

import io
import os
import subprocess
import sys
from pathlib import Path

import pytest
from alembic import command, util
from alembic.config import Config
from sqlalchemy import create_engine, text
from sqlalchemy.engine import make_url
from sqlalchemy.pool import NullPool

from app.base_schema_contract import (
    BASE_LEGACY_TABLES,
    REASON_INCOMPATIBLE,
    REASON_PARTIAL,
    BaseSchemaContractError,
    extract_signature,
)

SERVE_DIR = Path(__file__).resolve().parents[3]
ALEMBIC_DIR = SERVE_DIR / "alembic"
FIXTURE_SQL = SERVE_DIR / "tests/trading/fixtures/base_legacy_schema.sql"
BASELINE_REVISION = "cdabba1e3903"
# WP-03..WP-05 新增 b1000031/b1000040/b1000041/b1000050/b1000051 后 head 前进；v2_0001 的 Base 兼容合同行为不变。
HEAD_REVISION = "b1000070"

ADMIN_URL_ENV = "V2_TEST_ADMIN_DATABASE_URL"
TEMP_PREFIX = "pm_v2_test_"


# ---------------- 工具 ----------------

def _run(cmd, revision, db_url, script_location=None):
    cfg = Config()
    cfg.set_main_option("script_location", str(script_location or ALEMBIC_DIR))
    engine = create_engine(db_url, poolclass=NullPool)
    conn = engine.connect()
    cfg.attributes["connection"] = conn
    try:
        cmd(cfg, revision)
    finally:
        conn.close()
        engine.dispose()


def _check(db_url):
    """运行 ``alembic check``：存在 autogenerate diff 时抛 util.AutogenerateDiffsDetected。"""
    cfg = Config()
    cfg.set_main_option("script_location", str(ALEMBIC_DIR))
    engine = create_engine(db_url, poolclass=NullPool)
    conn = engine.connect()
    cfg.attributes["connection"] = conn
    try:
        command.check(cfg)
    finally:
        conn.close()
        engine.dispose()


def _query(db_url, sql, params=None):
    engine = create_engine(db_url)
    try:
        with engine.connect() as c:
            return c.execute(text(sql), params or {}).fetchall()
    finally:
        engine.dispose()


def _version_rows(db_url):
    return _query(db_url, "SELECT version_num FROM public.alembic_version")


def _non_system_tables(db_url):
    return _query(
        db_url,
        "SELECT schemaname||'.'||tablename FROM pg_tables "
        "WHERE schemaname NOT IN ('pg_catalog', 'information_schema') ORDER BY 1",
    )


def _base_signature(db_url):
    engine = create_engine(db_url)
    try:
        with engine.connect() as c:
            c.execute(text("SET LOCAL search_path TO public, pg_catalog"))
            return extract_signature(c)
    finally:
        engine.dispose()


def _psql(db_url, args):
    """psql 连接参数从 URL 解析；无 host 时走本地 socket peer（与 admin URL 同源）。"""
    u = make_url(db_url)
    cmd = ["psql", "-q", "-v", "ON_ERROR_STOP=1"]
    if u.host:
        cmd += ["-h", u.host]
    if u.port:
        cmd += ["-p", str(u.port)]
    if u.username:
        cmd += ["-U", u.username]
    cmd += ["-d", u.database]
    cmd += args
    env = dict(os.environ)
    if u.password:
        env["PGPASSWORD"] = u.password
    r = subprocess.run(cmd, capture_output=True, text=True, env=env)
    assert r.returncode == 0, f"psql failed: {r.stderr[-2000:]}"
    return r


def _apply_fixture(db_url):
    _psql(db_url, ["-f", str(FIXTURE_SQL)])


def _generate_offline_sql(revision="head"):
    """生成指定 revision/range 的 offline SQL（不连库）。"""
    cfg = Config()
    cfg.set_main_option("script_location", str(ALEMBIC_DIR))
    buf = io.StringIO()
    cfg.output_buffer = buf
    command.upgrade(cfg, revision, sql=True)
    return buf.getvalue()


def _psql_apply(db_url, sql):
    """应用 offline SQL；返回 (returncode, stderr)。不在此断言成败，交给调用方。"""
    u = make_url(db_url)
    cmd = ["psql", "-q", "-v", "ON_ERROR_STOP=1"]
    if u.host:
        cmd += ["-h", u.host]
    if u.port:
        cmd += ["-p", str(u.port)]
    if u.username:
        cmd += ["-U", u.username]
    cmd += ["-d", u.database]
    env = dict(os.environ)
    if u.password:
        env["PGPASSWORD"] = u.password
    r = subprocess.run(cmd, input=sql, capture_output=True, text=True, env=env)
    return r.returncode, r.stderr


# WP-01A-01-r1：三张复合主键表的正常列顺序（用于构造反序反例）。
SWAPPED_PK_CASES = [
    ("admin_user_roles", "admin_user_id", "role_id"),
    ("article_keywords", "article_id", "keyword_id"),
    ("role_menus", "role_id", "menu_id"),
]


def _swap_pk_sql(table, col1, col2):
    """把 ``table`` 主键从 ``(col1, col2)`` 反序为 ``(col2, col1)``。"""
    return (
        f"ALTER TABLE public.{table} DROP CONSTRAINT {table}_pkey;"
        f"ALTER TABLE public.{table} ADD CONSTRAINT {table}_pkey "
        f"PRIMARY KEY ({col2}, {col1});"
    )


def _prepare_baseline(url):
    """apply fixture → upgrade head（canonical COMPATIBLE）→ downgrade 到基线。

    结果：18 表 + alembic_version 行停在 ``cdabba1e3903``。
    """
    _apply_fixture(url)
    _run(command.upgrade, "head", url)
    assert _version_rows(url) == [(HEAD_REVISION,)]
    _run(command.downgrade, BASELINE_REVISION, url)
    assert _version_rows(url) == [(BASELINE_REVISION,)]


def _table_exists(db_url, qualified_name):
    rows = _query(
        db_url,
        "SELECT to_regclass(:q) IS NOT NULL",
        {"q": qualified_name},
    )
    assert rows
    return bool(rows[0][0])


def _index_exists(db_url, idx):
    return bool(
        _query(
            db_url,
            "SELECT 1 FROM pg_indexes WHERE indexname=:i",
            {"i": idx},
        )
    )


def _constraint_exists(db_url, con):
    return bool(
        _query(
            db_url,
            "SELECT 1 FROM pg_constraint WHERE conname=:c",
            {"c": con},
        )
    )


def _trigger_exists(db_url, trg):
    return bool(
        _query(
            db_url,
            "SELECT 1 FROM pg_trigger WHERE tgname=:t AND NOT tgisinternal",
            {"t": trg},
        )
    )


def _column_has_default(db_url, table, column):
    rows = _query(
        db_url,
        "SELECT column_default IS NOT NULL FROM information_schema.columns "
        "WHERE table_schema='public' AND table_name=:t AND column_name=:c",
        {"t": table, "c": column},
    )
    assert rows, f"column {table}.{column} not found"
    return rows[0][0]


def _column_type(db_url, table, column):
    rows = _query(
        db_url,
        "SELECT lower(format_type(atttypid, atttypmod)) FROM pg_attribute a "
        "JOIN pg_class c ON c.oid=a.attrelid JOIN pg_namespace n ON n.oid=c.relnamespace "
        "WHERE n.nspname='public' AND c.relname=:t AND a.attname=:c",
        {"t": table, "c": column},
    )
    return rows[0][0]


# ---------------- 1. literal-empty ----------------

def _public_tables(url):
    return [t for t in _non_system_tables(url) if t[0].startswith("public.")]


def test_literal_empty_upgrade_downgrade_upgrade(temp_pg_db):
    url = temp_pg_db.url
    _run(command.upgrade, "head", url)
    assert _version_rows(url) == [(HEAD_REVISION,)]
    # public 只有 alembic_version，无任何 Base 表（literal-empty → Base no-op）
    assert _public_tables(url) == [("public.alembic_version",)]

    _run(command.downgrade, BASELINE_REVISION, url)
    assert _version_rows(url) == [(BASELINE_REVISION,)]

    _run(command.upgrade, "head", url)
    assert _version_rows(url) == [(HEAD_REVISION,)]
    assert _public_tables(url) == [("public.alembic_version",)]


# ---------------- 2. canonical fixture：指纹不变 + 无 Base drift ----------------

def test_fixture_upgrade_keeps_base_fingerprint(temp_pg_db):
    url = temp_pg_db.url
    _apply_fixture(url)
    before = _base_signature(url)
    assert set(before) == set(BASE_LEGACY_TABLES)
    assert len(before) == 18

    _run(command.upgrade, "head", url)
    assert _version_rows(url) == [(HEAD_REVISION,)]

    # Base schema 规范化 fingerprint 完全一致；只有 alembic_version 变化
    after = _base_signature(url)
    assert after == before
    assert sorted(_public_tables(url)) == sorted(
        [(f"public.{t}",) for t in BASE_LEGACY_TABLES] + [("public.alembic_version",)]
    )

    # alembic check：对 Base/public 零 drift；唯一 diff 是动态分区子表
    # （SQLAlchemy metadata 无法静态表达，按动态分区前缀白名单接受）
    from alembic import util
    from tests.trading.fixtures.migration_helpers import split_dynamic_diffs

    try:
        _check(url)
        diffs = []
    except util.AutogenerateDiffsDetected as e:
        diffs = e.diffs
    dynamic, modeled = split_dynamic_diffs(diffs)
    assert modeled == [], f"unexpected Base drift: {modeled}"
    assert len(dynamic) > 0  # 0002/0011 动态分区子表 + 继承索引


# ---------------- 3. 额外 public 对象逐项保留 ----------------

def test_extra_public_objects_preserved(temp_pg_db):
    url = temp_pg_db.url
    _apply_fixture(url)
    # 添加未知 public 表 + 额外 index/CHECK/default/trigger
    _psql(
        url,
        ["-c", (
            "CREATE TABLE public.unknown_extra_table (id integer PRIMARY KEY);"
            "CREATE INDEX idx_admin_users_email_extra ON public.admin_users(email);"
            "ALTER TABLE public.admin_users "
            "  ADD CONSTRAINT chk_admin_users_status_extra CHECK (status IN (0,1,2));"
            "ALTER TABLE public.admin_users ALTER COLUMN nickname SET DEFAULT 'n/a';"
            "CREATE FUNCTION public.trg_extra_fn() RETURNS trigger "
            "  LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;"
            "CREATE TRIGGER trg_admin_users_extra BEFORE INSERT ON public.admin_users "
            "  FOR EACH ROW EXECUTE FUNCTION public.trg_extra_fn();"
        )],
    )

    _run(command.upgrade, "head", url)
    assert _version_rows(url) == [(HEAD_REVISION,)]

    # 全部逐项保留（autogenerate 不接管 Base/未知 public 对象）
    assert _table_exists(url, "public.unknown_extra_table")
    assert _index_exists(url, "idx_admin_users_email_extra")
    assert _constraint_exists(url, "chk_admin_users_status_extra")
    assert _column_has_default(url, "admin_users", "nickname") is True
    assert _trigger_exists(url, "trg_admin_users_extra")


# ---------------- 4. partial / incompatible 失败回滚 ----------------

def _break_then_fail(url, break_sql, reason):
    _apply_fixture(url)
    _run(command.upgrade, "head", url)               # 先证明 COMPATIBLE 可用
    assert _version_rows(url) == [(HEAD_REVISION,)]
    _run(command.downgrade, BASELINE_REVISION, url)  # version 回到基线
    assert _version_rows(url) == [(BASELINE_REVISION,)]
    _psql(url, ["-c", break_sql])

    with pytest.raises(BaseSchemaContractError, match=reason):
        _run(command.upgrade, "head", url)

    # version 未前进；失败 run 无对象变化（整 run 回滚）
    assert _version_rows(url) == [(BASELINE_REVISION,)]


def test_partial_fails_before_version_advances(temp_pg_db):
    url = temp_pg_db.url
    _break_then_fail(url, "DROP TABLE public.settings;", REASON_PARTIAL)
    # settings 仍缺失（失败 run 没有重建它）
    assert _table_exists(url, "public.settings") is False


def test_incompatible_fails_before_version_advances(temp_pg_db):
    url = temp_pg_db.url
    _break_then_fail(
        url,
        "ALTER TABLE public.admin_users ALTER COLUMN username TYPE text;",
        REASON_INCOMPATIBLE,
    )
    # 列仍为 text（失败 run 没有改回）
    assert _column_type(url, "admin_users", "username") == "text"


# ---------------- 4.5 (WP-01A-01-r1) 复合主键列顺序等价性 ----------------

@pytest.mark.parametrize("table,col1,col2", SWAPPED_PK_CASES)
def test_online_swapped_composite_pk_order_fails(temp_pg_db, table, col1, col2):
    """online：反序复合主键在 version 前进前以 v2_base_schema_incompatible 失败。"""
    url = temp_pg_db.url
    _prepare_baseline(url)
    _psql(url, ["-c", _swap_pk_sql(table, col1, col2)])

    with pytest.raises(BaseSchemaContractError, match=REASON_INCOMPATIBLE):
        _run(command.upgrade, "head", url)

    # version 停基线；失败 run 无部分 DDL（表仍在）
    assert _version_rows(url) == [(BASELINE_REVISION,)]
    assert _table_exists(url, f"public.{table}")


@pytest.mark.parametrize("table,col1,col2", SWAPPED_PK_CASES)
def test_offline_swapped_composite_pk_order_fails(temp_pg_db, table, col1, col2):
    """offline：实际应用生成的 SQL 时反序复合主键同样失败，整个事务回滚。"""
    url = temp_pg_db.url
    # 从真实 baseline 状态执行 range SQL；失败后 version 必须仍是 baseline。
    _prepare_baseline(url)
    _psql(url, ["-c", _swap_pk_sql(table, col1, col2)])

    sql = _generate_offline_sql(f"{BASELINE_REVISION}:head")
    rc, stderr = _psql_apply(url, sql)
    assert rc != 0, "offline SQL unexpectedly succeeded on swapped-PK schema"
    assert REASON_INCOMPATIBLE in stderr

    # 整个 range SQL 事务回滚：version 停在 baseline、无部分 DDL。
    assert _version_rows(url) == [(BASELINE_REVISION,)]
    assert _table_exists(url, f"public.{table}")
    assert _query(
        url, "SELECT count(*) FROM pg_tables WHERE schemaname='public'"
    ) == [(19,)]


def test_offline_canonical_fixture_upgrade_succeeds(temp_pg_db):
    """canonical fixture 的 offline upgrade 仍成功到 b1000001（与 online 等价）。"""
    url = temp_pg_db.url
    _prepare_baseline(url)

    sql = _generate_offline_sql(f"{BASELINE_REVISION}:head")
    rc, stderr = _psql_apply(url, sql)
    assert rc == 0, f"offline canonical apply failed: {stderr[-1500:]}"
    assert _version_rows(url) == [(HEAD_REVISION,)]
    # 18 张 Base 表原样保留
    assert _query(
        url, "SELECT count(*) FROM pg_tables WHERE schemaname='public'"
    ) == [(19,)]


# ---------------- 5. 临时库零残留 ----------------

def test_no_temporary_database_residue():
    admin_url = os.environ.get(ADMIN_URL_ENV)
    if not admin_url:
        pytest.skip(f"{ADMIN_URL_ENV} not set — skip real-PostgreSQL integration")
    admin = create_engine(admin_url, isolation_level="AUTOCOMMIT", poolclass=NullPool)
    try:
        with admin.connect() as c:
            rows = c.execute(
                text(
                    "SELECT datname FROM pg_database "
                    "WHERE datname LIKE 'pm\\_v2\\_test\\_%' "
                    "   OR datname LIKE 'pm\\_v2\\_fixture\\_%' ORDER BY 1"
                )
            ).fetchall()
        assert rows == [], f"temporary database residue: {rows}"
    finally:
        admin.dispose()
